### ISSUE TITLE
Apk filtering by cpu arch not working well with fdroid

### ISSUE THREAD

**Issue by xd003** [ImranR98/Obtainium#1002]
**Describe the bug**
I added https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/ in app source url and added the app. Obtainium displayed option to select apk between the ```arm64-v8a``` & ```armeabi-v7a``` variants of the apk. I didn't turned off the attmept to filter apk by cpu architecture option which is activated by default 

**Please complete the following information:**
 - Device: Iqoo neo 7
 - OS: Funtouch OS 13
 - Obtainium Version: v0.14.28-beta

**Comment by ImranR98** [comment]
![Screenshot_20231014-022505-01](https://github.com/ImranR98/Obtainium/assets/30463115/d027bb58-6a35-49d8-b32e-6d729b2c2997)

I don't see arch info in the filenames.

**Comment by xd003** [comment]
![Picsart_23-10-14_11-59-10-606](https://github.com/ImranR98/Obtainium/assets/26503185/db8a3616-3415-4ce7-b25f-30d860ab0f84)
![Picsart_23-10-14_11-59-41-446](https://github.com/ImranR98/Obtainium/assets/26503185/c641023e-d5b0-47cd-8e42-524d2450b24e)

Even i got the very same thing as yours. Actually they don't mention explicitly mention the cpu arch in the filename. Some apps have single apk for all arch but for ones that don't eg fennec Its the numbers at the end which indicate the cpu. ```1020``` refers to ```arm64-v8a``` & ```1000``` refers to ```armeabi-v7a```. This is what i have noticed as of now even with Mull. I am not 100% sure if its a standard fdroid naming convention

**Comment by ImranR98** [comment]
Yeah if there was a way to get arch info, that might have worked.

**Comment by NicholasFlamy** [comment]
> ![Picsart_23-10-14_11-59-10-606](https://private-user-images.githubusercontent.com/26503185/275152897-db8a3616-3415-4ce7-b25f-30d860ab0f84.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDg3NDcsIm5iZiI6MTcyOTcwODQ0NywicGF0aCI6Ii8yNjUwMzE4NS8yNzUxNTI4OTctZGI4YTM2MTYtMzQxNS00Y2U3LWIyNWYtMzBkODYwYWIwZjg0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE4MzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZDhmODE0OWJlNTE0MmMyYjI3MmYwNzk4OGM1MGM2MWJkZWY1ZWYzZmMzY2QwNTQ5NDAzODQwOThlM2Y5N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b2AgutmBLJP0cB_PsdNi-P2jK2zG8UwD35_DQGGwvno) ![Picsart_23-10-14_11-59-41-446](https://private-user-images.githubusercontent.com/26503185/275152899-c641023e-d5b0-47cd-8e42-524d2450b24e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDg3NDcsIm5iZiI6MTcyOTcwODQ0NywicGF0aCI6Ii8yNjUwMzE4NS8yNzUxNTI4OTktYzY0MTAyM2UtZDViMC00N2NkLThlNDItNTI0ZDI0NTBiMjRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE4MzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwYWQ2Y2NmYTJjYzJmM2Y0YTUyZmMxMTQ1MGVkNTdhN2ExNmZhYTkyNDYzY2FmOWVmZTQ2MWY3ZjBjZGE2NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cm_oTCk0bStWG4wWEc8bzCiJQfP5r5XbJptPrS22h0A)
> 
> Even i got the very same thing as yours. Actually they don't explicitly mention the cpu arch in the filename. Some apps have single apk for all arch but for ones that don't eg fennec Its the numbers at the end which indicate the cpu. `1020` refers to `arm64-v8a` & `1000` refers to `armeabi-v7a`. This is what i have noticed as of now even with Mull. I am not 100% sure if its a standard fdroid naming convention
> 
> Edit - Okey i checked lot more apps, and this doesn't seem to be a common naming convention. Every app seem to be using different ways. For instance https://f-droid.org/en/packages/com.foxdebug.acode/ has 3 digit numbers inside parenthesis for each of the cpu arch files

VLC does this same thing.

**Comment by freijon** [comment]
I think this needs improvement. For example 

![Image](https://github.com/user-attachments/assets/5d79ec71-c0b8-4070-90ca-5955af4d9381)

whereas Droidify seems to be able to detect the architectures just fine:

![Image](https://github.com/user-attachments/assets/9ce60428-da8d-427e-9da1-5feee5075c46)

> Yeah if there was a way to get arch info, that might have worked.

I'm no expert like you, but it seems to be possible if other apps can do it?
