### ISSUE TITLE
Track-Only Option for Some HTML Sources Doesn't Seem to Work

### ISSUE THREAD

**Issue by E0697** [ImranR98/Obtainium#1005]
**Prerequisites**

**Describe the bug**

The app seems to continue to download apks with track-only option for HTML source enabled.

**To Reproduce**

1. Add this source: https://download.kiwix.org/release/kiwix-android/kiwix.apk
2. Enable track-only option
3. The app continues to download the apk (inferred from traffic indicator, didn't let it finish because I have bad conncetion) 

**Please complete the following information:**

 - Device: Realme 7 Pro
 - OS: EvolutionX
 - Obtainium Version: 0.14.29-beta]

**Additional context**

This source usually ends up failing with connection closed error, probably because of bad internet.

I've been experimenting with version detection regex patterns so I enabled track-only option but it continues to download the apk.

The main page is https://kiwix.org/en/applications/. There's a download apk button containg this URL: https://download.kiwix.org/release/kiwix-android/kiwix.apk, which redirects to https://download.kiwix.org/release/kiwix-android/kiwix-3.7.1.apk, then to https://mirror-sites-ca.mblibrary.info/mirror-sites/download.kiwix.org/release/kiwix-android/kiwix-3.7.1.apk.

Which one should I use as source and which as intermediate link (if any)?

**Comment by ImranR98** [comment]
Hmm, I haven't been able to reproduce this by just adding https://kiwix.org/en/applications/ and enabling track-only. What are the exact settings you're using?

**Comment by E0697** [comment]
Can you please try with this url: https://download.kiwix.org/release/kiwix-android/kiwix.apk

You're right about https://kiwix.org/en/applications/, track-only works. 
I'm using kiwix-([0-9.]+).apk as regex pattern for version detection but it doesn't work. Maybe because of the redirects?

**Comment by ImranR98** [comment]
The HTML source doesn't work with direct APK links since it would make update notifications impossible (in this case, you would also have to use version extraction since the APK link doesn't look like it changes on every release). See https://github.com/ImranR98/Obtainium/issues/954#issuecomment-1745970526

**Comment by E0697** [comment]
Thank you!

I just added https://kiwix.org/en/applications/ as the source with https://download.kiwix.org/release/kiwix-android/kiwix.apk as intermediate link and set a regular expression for version detection. It started downloading (track-only enabled), I'll let finish and see if the version is correct.

**Comment by ThreeDeeJay** [comment]
There's also Kiwix Nightly 👀👌

Source:
```
https://download.kiwix.org/nightly
```

Intermediate link:
```
[0-9]*-[0-9]+-[0-9]+/$
 ```

Custom APK link:
```
kiwix-universal-[0-9]*-[0-9]+-[0-9]+.apk
```

**Comment by kelson42** [comment]
There is nightly permalink at https://download.kiwix.org/nightly/kiwix-universal.apk

**Comment by danielwerg** [comment]
https://github.com/ImranR98/Obtainium/issues/1005#issuecomment-2094737004

Updated custom APK link:

```
org.kiwix.kiwixmobile.standalone-universal-[0-9]+-[0-9]+-[0-9]+.apk
```
