### ISSUE TITLE
URL does not match a known source

### ISSUE THREAD

**Issue by SecT0uch** [ImranR98/Obtainium#1006]
**Describe the bug**

I have the following issue since the last update.

**To Reproduce**
1. Go to 'Add App'
2. Leave 'App Source URL' empty
3. In 'Search': whatever, 'aves' for example
4. See error: `URL does not match a known source`

**Please complete the following information:**
 - Device: Fairphone 3+
 - OS: LineageOS for microg
 - Obtainium Version: 0.14.29-beta

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.30-beta
