### ISSUE TITLE
[Feature Request] - Store Most Recent Installed APK for Selected Projects for Offline Distribution

### ISSUE THREAD

**Issue by jeremiah-k** [ImranR98/Obtainium#1007]
One of my main uses for Obtainium is to use it for updating the Meshtastic (offline encrypted meshnets via LoRa) Android app + tracking new firmware releases (thank you for implementing the "Track Only" feature so I'm able to do that).

For this feature request, in situations where internet access is inaccessible having the latest stable apk stored locally would be invaluable for Bluetooth sharing later.

So rather than downloading & installing the apk, then deleting the cache.  It would be great if we could specify a folder to store the last successfully installed version. Also if there are multiple files for different architectures we would be able to select & download those files, even if we are only installing one on our phone.

Thank you!

**Comment by ImranR98** [comment]
Merging this with #29
