### ISSUE TITLE
Notification not disappearing

### ISSUE THREAD

**Issue by eloffmarijan** [ImranR98/Obtainium#101]
When an app gets update, the update available notification will appear but it doesn't disappear after the app is updated.
I have to manually swipe to clear the update notification.

**Comment by ImranR98** [comment]
Should be simple enough to fix, just cancel all update notifications when Obtainium is opened. Will add to the next version.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.6.9-beta
