### ISSUE TITLE
[Feature request] Update check only for installed apps

### ISSUE THREAD

**Issue by kenderipa** [ImranR98/Obtainium#1012]
**Prerequisites**

Done
**Describe the feature**

Hello. 
If I remember correctly, in earlier version existed an option to check for updates only for installed app. Could you please bring it back?

Motivation. Github rate limiting is 60 API calls per hour. I think there are not many people who have more than 60 apps at the same time on their devices. This way no Github access token is needed for the update. At the same time, if one wait for an update for an app which is not installed, one can trigger the update verification by going to the properties page of this app.

**Describe alternatives you've considered (if applicable)**

Darn. Oh well.

**Additional context**

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.31-beta
