### ISSUE TITLE
Tv version

### ISSUE THREAD

**Issue by KUKARAF** [ImranR98/Obtainium#1020]
**Describe the feature**
APK Version for android tv 

n/a

**Comment by ImranR98** [comment]
Duplicate of #281

**Comment by tazztone** [comment]
ye would be nice.
wanted to install smarttube with it. somehow it broke my remote control navigation (buttons were no longer doing what they're supposed to do) and i had to reboot the tv box ( leap s3+). happened many times. not sure what about obtainium could cause this
