### ISSUE TITLE
Check updates for apps installed from third party f-droid repo

### ISSUE THREAD

**Issue by imxade** [ImranR98/Obtainium#1022]
**Describe the feature**

In reference to feature #995, 
Obtainium is unable to check for updates of apps installed from third-party repositories.

> for eg. I installed Mulch from divestOS' f-droid repo, since installation obtainium is unable to find suitable release.

**Describe alternatives you've considered (if applicable)**
using f-droid to check for now.

**Comment by ImranR98** [comment]
It does work. You need to manually select "F-Droid Third Party Repo" in the Source dropdown. By default it will use the HTML Source since we can't tell in advance that a URL if for an F-Droid repo.
