### ISSUE TITLE
On Version Detection for F-Droid

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#1023]
I'm having some trouble with [LibreOffice Viewer](https://f-droid.org/en/packages/org.documentfoundation.libreoffice/).  As you see, the version number looks like this:

Version 7.6.2.1/56f768401134/F-Droid-editing (29) 

Installing the arm64-v8a version, that comes out in Obtainium as (note the "-" as opposed to "/"):

Latest Version: Version 7.6.2.1-56f768401134-F-Droid-editing (29) 
Installed Version: Version 7.6.2.1/56f768401134/F-Droid-editing (29) 

As a result, it's always reported as needing a update.

Second issues is that I can't seem to get any of the filters to recognize the proper version, arm64-v8a.  There is nothing in the apk link that can be used for "Filter APKs by Regular Expression", and neither did this work:

Filter Version by Regular Expression: arm64-v8a

Is there any way to get the proper version recognized?

**Comment by ImranR98** [comment]
I don't remember why I added the find and replace for `/` but removing it doesn't seem to break anything. Will be fixed in the next release. For apk filtering, there's no way to do it as far as I can see, since the APKs don't indicate what architecture they use (there was another issue for this).

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.31-beta
