### ISSUE TITLE
f-droid with 2 releases for each version.

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#1026]
Note that [this f-droid package](https://f-droid.org/en/packages/de.schildbach.wallet/) has two releases for every version number.  One is signed by f-droid and one by the dev.  Links for the most recent are:

https://f-droid.org/repo/de.schildbach.wallet_100600.apk
https://f-droid.org/repo/de.schildbach.wallet_100600_58dcd8a.apk

To select the second, I tried:

Filter APKs by Regular Expression: _58dcd8a\\.apk

The result is "No APK found".  Without that regexp, there is no error.  I have none of the switches on, save "Attempt to filter APKs by CPU architecture if possible".  I tried `_58dcd8a\.apk$` also, to try to distinguish `.apk` from `.apk.asc`.

GrapheneOS, Pixel 7, Obtainium 14.31-beta

**Comment by ImranR98** [comment]
Unfortunately it looks like the F-Droid API does not distinguish between the two - it just shows two identical entries without the `_58dcd8a` suffix: https://f-droid.org/api/v1/packages/de.schildbach.wallet
So until F-Droid updates their API, there's no way (aside from unreliable web scraping) for Obtainium to tell that there's another dev-signed APK available. What I can fix right now is the duplicate entry.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.32-beta

**Comment by DiagonalArg** [comment]
I see.  Thank you.
