### ISSUE TITLE
Downloaded package ID  does not match existing App ID

### ISSUE THREAD

**Issue by NoName-exe** [ImranR98/Obtainium#103]
Used to be that until v5.10,I could update my apps with relatively no issues. However,the new method you're using breaks the app.

I use [this repo](https://github.com/j-hc/revanced-magisk-module) to get twitter and reddit revanced and it just doesn't work from v6.0 (when the new method was introduced).

Heck,even [this](https://github.com/HardcodedCat/termux-monet) doesn't work anymore.

The new method is cool and all but it would be greatly appreciated if you could get those 2 repos to work as they used to until v5.10.

**Comment by NoName-exe** [comment]
> Could you be more specific? Both repos work fine for me.

![Screenshot_20221110-213354_Obtainium.png](https://user-images.githubusercontent.com/52629189/201146799-d9f39187-3588-4cac-bfd7-af260e15361a.png)

![Screenshot_20221110-213439_Obtainium.png](https://user-images.githubusercontent.com/52629189/201146833-543388a3-6377-49b2-8a9d-df7a213bd2ee.png)

![Screenshot_20221110-213354_Obtainium.png](https://user-images.githubusercontent.com/52629189/201146858-06cc99d8-ab37-42fb-99ff-edfde9ff7ffa.png)

This is the error I'm getting and it never used to be there until v6.0

**Comment by ImranR98** [comment]
Ok, that makes sense. The transition from v0.5.10 to v0.6.0 involved a change in the App ID format, so for a while, changing App IDs was allowed so that people could upgrade to v0.6+. But being able to change the App ID upon install is a security risk, so it was disabled in version 0.6.9. I thought there was enough time between v0.6.0 and v0.6.9 that no one was likely to run into this error, guess not.

To fix this, you'll need to remove these Apps and re-add them. This is easy enough if you use multi-select then pick the share URL option, then import the URLs back in.

The other option is to install a version of Obtainium between 0.6.0 and 0.6.8, then update all Apps, then upgrade to the latest version again, but that's more complicated.

**Comment by NoName-exe** [comment]
> Ok, that makes sense. The transition from v0.5.10 to v0.6.0 involved a change in the App ID format, so for a while, changing App IDs was allowed so that people could upgrade to v0.6+. But being able to change the App ID upon install is a security risk, so it was disabled in version 0.6.9. I thought there was enough time between v0.6.0 and v0.6.9 that no one was likely to run into this error, guess not.
> 
> To fix this, you'll need to remove these Apps and re-add them. This is easy enough if you use multi-select then pick the share URL option, then import the URLs back in.
> 
> The other option is to install a version of Obtainium between 0.6.0 and 0.6.8, then update all Apps, then upgrade to the latest version again, but that's more complicated.

Tried both,still doesn't want to work. Guess I'm staying in v0.5.10

**Comment by NoName-exe** [comment]
> Sorry, I didn't realize this also affected App imports. It should be fixed with the latest version: https://github.com/ImranR98/Obtainium/releases/tag/v0.6.11-beta

Apart from the minor inconvenience of having to import [this repo](https://github.com/j-hc/revanced-magisk-module), one for twitter and the other for reddit with having to mark Reddit as updated (to follow that repo's naming scheme), everything works flawlessly!!

Thanks for the fix sir.

**Comment by TheDarkula** [comment]
This is still occurring with [Nextcloud Talk](https://github.com/nextcloud/talk-android) on version v0.13.8-beta of Obtanium.

**Comment by TheDarkula** [comment]
Just to keep things entertaining :)

You may want to enable that toggle when a program has already been added to Obtanium under the edit menu, as it is not there.

**Comment by einarpersson** [comment]
I'm experiencing this when trying to install [synchthing-fork](https://github.com/Catfriend1/syncthing-android) from github.

Turning of _"infer app id"_ indeed seems to have solved the problem. However I have no idea what this means and its potential consequences. I also did not understand what you meant by toggling on after install (I went into edit, but could not find the infer app id setting there). Could you elaborate?

PS. This seems like a very nice project. I have just migrated from iPhone so I'm still unfamiliar to this new ecosystem but I hope that this app will resolve some of my questions

**Comment by ImranR98** [comment]
@einarpersson an app's ID (the unique identifier the app gives to the OS) must be known before it can be added to Obtainium. "infer app id" just means that obtainium will try to figure out the app's ID before downloading it (by looking at the app's code on GitHub). When this is turned off, the app will be downloaded and its ID will be extracted from the APK directly.

So turning this off has no negative impact - it just means that adding the app will take longer (as it must be downloaded first).

**Comment by ImranR98** [comment]
Leaving a note for later: if this error occurs the first time an app is installed *and* "infer app id" was enabled on add, the error should not be displayed - just quietly update the id instead.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.9-beta

**Comment by TheDarkula** [comment]
Thank you!

**Comment by skwde** [comment]
@ImranR98 unfortunately I cannot find the "infer app ID" setting. Would you mind pointing me to it.

**Comment by ImranR98** [comment]
It's no longer a setting. Obtainium just tries to infer the app ID automatically.

**Comment by skwde** [comment]
Ok, so what is the suggestion to fix it then.
I think the problem was that accidentally the app was updated by another store (play store...)

I don't want to end up loosing all the config and having to add all email addresses again...

**Comment by roberta-mb** [comment]
Same question here: in the absence of the "infer ID" option, what would be a solution? I experienced this the other day when Thunderbird released its 10.0b2 app; I had version 9 something and the beta was not recognised. I actually installed Thunderbird Beta using the config on the Obtainium website, but now that version 10.0 is released, I have the beta version and I get the error preventing me to update to the release version..

**Comment by eMPee584** [comment]
Turning off "infer app ID" (only avail when adding!) is a really hard-to-find solution for such a common problem. Many nightly builds on github seem to cause this.. Uninstalled, removed and re-added an app several times over weeks until I found this.

How about presenting the user with the option to confirm the app ID found in the APK instead of just failing with an obscure error message? esp. as the APK has already been downloaded..
