### ISSUE TITLE
"Out of memory" when adding source URI.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ImranR98/Obtainium#1030]
**Prerequisites**
Relevant search returns 0 results.

**Describe the bug**
Per the title.

**To Reproduce**
0.  Enter https://releases.grayjay.app/app-arm64-v8a-release.apk as a new source URI.
0.  See the undermentioned.

**Screenshots and Logs**
![Screenshot_20231020-062302.png](https://github.com/ImranR98/Obtainium/assets/42837531/0f06cf66-22a0-43ec-bdec-0961e56763ae)

**Please complete the following information:**
 - Device: Fairphone FP4
 - OS: Stock Android 13 ROM
 - Obtainium Version: 0.14.31

**Comment by ImranR98** [comment]
You can't add an APK URL directly because this would make it impossible to check for updates. Please take a look at this comment: https://github.com/ImranR98/Obtainium/issues/954#issuecomment-1745970526

**Comment by ImranR98** [comment]
Also, the GrayJay app is self-updating so you don't need Obtanium for this.

**Comment by ImranR98** [comment]
Same goes for the FUTO voice input app if you were wondering.

**Comment by RokeJulianLockhart** [comment]
Perhaps the error message could be improved, then, like

> URIs to installer files are not supported, see documentation.

**Comment by ImranR98** [comment]
There's no reliable way to tell whether a URL points to an HTML or APK file in advance (that I know of). Even using a HEAD request sometimes gives you the wrong answer.

**Comment by RokeJulianLockhart** [comment]
Because of spec infraction or because it's fundamentally impossible to get a reliable MIME type without downloading the file?

**Comment by ImranR98** [comment]
I remember having issues getting the mime type because sometimes there are redirects involved.  It is probably doable with some work but I'm not sure it's worth it.
