### ISSUE TITLE
Not compatible with the latest version of Andriod

### ISSUE THREAD

**Issue by Rack1538** [ImranR98/Obtainium#1033]
**Prerequisites**

**Describe the bug**

First time launching after installation I get the message "Not compatible with the latest version of Android"

**To Reproduce**

Can't reproduce the message, but the app still doesn't seem to be working.

**Screenshots and Logs**

**Please complete the following information:**
 - Device: Pixel 6
 - OS: GrapheneOS
 - Obtainium Version: 0.14.31-beta

**Additional context**

**Comment by ImranR98** [comment]
Could you post a recording or a set of screenshots?

**Comment by ImranR98** [comment]
Did you install `app-arm64-v8a-release.apk `?

**Comment by iDazai** [comment]
No problems with GOS on Android 14 with Pixel 5 and Pixel 8.

**Comment by DiagonalArg** [comment]
I've got people using it on Pixel 6's, and it's working.  Not new installs though.

**Comment by ImranR98** [comment]
@Rack1538 I still have no clue what the issue could be.  Is your device language English?
