### ISSUE TITLE
Token-less update request doesn't work, see screenshot

### ISSUE THREAD

**Issue by kenderipa** [ImranR98/Obtainium#1035]
**Prerequisites**

**Describe the bug**

**To Reproduce**

**Screenshots and Logs**

**Please complete the following information:**
 - Device:  Realme Tab Mini, Samsung Galaxy S23
 - OS:  Android 11, Android 1e
 - Obtainium Version:  latest

**Additional context**

"Only check installed and track-only appy for updates" set to true. Token removed.
![Screenshot_20231021-113424](https://github.com/ImranR98/Obtainium/assets/52325831/0b62cf0a-fb15-435f-848f-052f0789485c)

**Comment by ImranR98** [comment]
I'm assuming these are GitHub apps? Are these all of them or are there some GitHub apps that do work? Also are you able to get the APKs manually from the browser?

**Comment by kenderipa** [comment]
Those are all Github apps. Those are all of them, nothing can be updated right now from Github. I'm able to download an app from a browser.

**Comment by kenderipa** [comment]
I'm assuming, those API requests are for an logged in user. But for token-less update API requests should not concern a user at all.

**Comment by ImranR98** [comment]
Could you try putting something in the github token field and then clearing it?

**Comment by kenderipa** [comment]
Same error happens.

**Comment by kenderipa** [comment]
Any news?

**Comment by kenderipa** [comment]
The error still occurs.

**Comment by ImranR98** [comment]
Can't think of what could be causing this. Are you able to access github through a browser? Maybe you could try reinstalling obtainium.

**Comment by kenderipa** [comment]
Yeah, it works now after reinstallation. Closing.
