### ISSUE TITLE
i get no push notifications for new updates. But i can see the "downloading app" and "checking for updates" notifications

### ISSUE THREAD

**Issue by XxTriviumxX** [ImranR98/Obtainium#1049]
**Prerequisites**

**Describe the bug**

I no longer get push notifications for like a month. However, i do see the "downloading app" and "checking for updates" messages in the notifications area. GrapheneOS user on pixel 6a.

**To Reproduce**

1. allow notifications on obtainium.
2. wait for a new update.
3. I get "checking for updates" messages and "downloading app" messages... but not the "xyz has a new update" push notif.
4. I open obtainium and I can see some apps got new updates despite not having received any push notifications.

note: Uninstalling obtainium + rebooting the phone + reinstalling obtainium did not work.

**Screenshots and Logs**

I cannot screenshot a push notif that i don't receive, sorry.

**Please complete the following information:**
 - Device:  pixel 6a
 - OS:  GrapheneOS
 - Obtainium Version:  i have v0.14.31-beta, but the issue was present with earlier versions.. about 3-4 versions prior.

**Additional context**

Is there a setting in GrapheneOS i could use? Every other push notifications work perfectly.

**Comment by ImranR98** [comment]
This might be the same as #608 (specifically the more recent android 14 issue I commented about). Could you take a look and see if the behaviour you're seeing is the same?

**Comment by XxTriviumxX** [comment]
i can see those notifications, but i can swipe them out. they are not permanent. 

last night i had a surprise.. i opened obtainium and got a notification for a new update. but only when i opened obtainium. now that is in the list of notifications, they might work for good.  ill give it some time and keep you updated if i get a notification or not.

**Comment by ImranR98** [comment]
> but only when i opened obtainium

Yep, sounds like #608. The background task starts, but then gets paused until you reopen the app. This is new on Android 14 (not sure if it's a bug or intended). Either way, that issue is a top priority. Closing this unless it turns out to be something different.

**Comment by XxTriviumxX** [comment]
i got an "updates available" message on the notifications field, but i don't recall hearing any notifications.
