### ISSUE TITLE
Ability to open installed app

### ISSUE THREAD

**Issue by hurried6158** [ImranR98/Obtainium#1052]
![Screenshot_20231026-155641](https://github.com/ImranR98/Obtainium/assets/121438152/2443d5ce-0489-46fc-8527-43042f45e006)

It would be nice if it would be possible to open the app when in the app page by pressing the icon (the bitwarden logo in the case of the attached screenshot). This would of course only be applicable if the app is installed.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.32-beta
