### ISSUE TITLE
Github Versions: Check that you're taking the last segment of the URL

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#1055]
[Standard Notes github](https://github.com/standardnotes/app) is working fine, with "Include Prereleases" and "Fallback to older releases" switched on.  Also, "Attempt to filter APKs by CPU architecture if possible."  Version detection is "Standard version detection", and:

Filter APKs by Regular Expression: app-prod-release\.apk

Results are that while the title of the releases is "Mobile 3.180.3" obtainium identifies versions as:

"@standardnotes/mobile@3.180.3"

I think you're getting the version from this link, and taking the stuff after `tree/`
https://github.com/standardnotes/app/tree/@standardnotes/mobile@3.180.3

I think you should be taking just the last segment of the URL

**Comment by ImranR98** [comment]
We don't use the URL. We use the GitHub tag since that is what works best for most repos. So what you're seeing is expected. If you don't like the way it looks, you could switch to using the release date as the version.
