### ISSUE TITLE
Scroll Bar

### ISSUE THREAD

**Issue by ngocanhtve** [ImranR98/Obtainium#1057]
**Prerequisites**

**Describe the feature**

Need an application search button in the "Apps" tab, to quickly browse to an application in a long list. The internal search button is a basic feature in every application. As well as every scroll bar to know where we are scrolling in the list, to estimate the length of the list of items.

**Comment by ImranR98** [comment]
We already have a filter button on the bottom left.

**Comment by ngocanhtve** [comment]
> We already have a filter button on the bottom left.

I didn't notice that filter button before. But I still think a search button would be easier to spot. Thanks you!

**Comment by ngocanhtve** [comment]
If possible add a search button. In case you have filtered out applications according to criteria but there are still too many entries. Now the search results will be displayed in real time with the letter typed to search.

It's almost like typing a keyword on Google and similar results will appear continuously.

**Comment by ngocanhtve** [comment]
If possible add a search button. In case you have filtered out applications according to criteria but there are still too many entries. Now the search results will be displayed in real time with the letter typed to search.

It's almost like typing a keyword on Google and similar results will appear continuously.

**Comment by ngocanhtve** [comment]
Excuse me, is the scroll bar being processed to be added to the application?
