### ISSUE TITLE
The application always strips the "www" part of the url when using third party f-droid repositories

### ISSUE THREAD

**Issue by TheSandBoxMKG** [ImranR98/Obtainium#1060]
**Prerequisites**

**Describe the bug**

I try to download something at https://www.ma-nic.de/fdroid/repo but the app fails with an "OS Error" message trying to access https://ma-nic.de/fdroid/repo/index.xml

To add contentx, ma-nic.de resolves to nothing but www.ma-nic.de is something that is up.

**To Reproduce**
Set source to:
https://www.ma-nic.de/fdroid/repo/index.xml
Set type to third party F-Dtoid repository
Set app id to:
org.qtproject.friendiqa

**Screenshots and Logs**

![https://0x0.st/Hy0j.png](https://0x0.st/Hy0j.png)
![https://0x0.st/Hy0e.png](https://0x0.st/Hy0e.png)

**Please complete the following information:**
 - Device: Motorola Moto G72 (Argentina) (retar software channel)
 - OS: Android 12
![http://0x0.st/Hy02.png](http://0x0.st/Hy02.png)
 - Obtainium Version: 0.14.31 (2223)

**Additional context**

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.32-beta
