### ISSUE TITLE
App isn't searchable

### ISSUE THREAD

**Issue by Emiller88** [ImranR98/Obtainium#1065]
https://github.com/orgzly-revived/orgzly-android-revived/issues/14#issuecomment-1793431641

For some reason the orgzly-revived app isn't searchable. We're struggling to figure out why exactly.

**Comment by amberin** [comment]
To be clear, https://github.com/orgzly-revived/orgzly-android-revived is our fork of https://github.com/orgzly/orgzly-android. Our fork has releases and tags that look the same to me as thos in the original repo.

[Our application ID](https://github.com/orgzly-revived/orgzly-android-revived/blob/master/app/build.gradle#L14) differs from [the original app's ID](https://github.com/orgzly/orgzly-android/blob/master/app/build.gradle#L14).

**Comment by ImranR98** [comment]
I'm not sure why this app doesn't show up in search results but it isn't an Obtainium issue since we just use GitHub's own search API, for example: https://api.github.com/search/repositories?q=orgzly

**Comment by Emiller88** [comment]
Hmm, that's interesting. Agreed, not a bug with Obtainium, still might be useful to report back here if anyone has an ideas since other apps may be experiencing this.
