### ISSUE TITLE
Allow option for downgrading

### ISSUE THREAD

**Issue by muznyo** [ImranR98/Obtainium#107]
I want to downgrade apps sometimes, because they might be buggy, but it normally isn't possible on Android (also Obtatinium).

But there's an solution. I have this [LSposed module](https://github.com/DavidBerdik/Let-Me-Downgrade) installed, which allows me to downgrade apps. But it doesn't work for Obtainium, because it checks app versions and doesnt let me even install the apk, because it thinks it would fail.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.7.1-beta
