### ISSUE TITLE
Installed applications also appear as installed in Google Play Store

### ISSUE THREAD

**Issue by SilkyRock** [ImranR98/Obtainium#1073]
Certain applications, installed via Obtanium, also appear as installed in Google Play Store. They can also be opened/uninstalled/updated via Play Store.

In my case, these are the applications:
- Proton Mail (source URL: https://github.com/ProtonMail/proton-mail-android)
- Signal (source URL: https://signal.org)
- VLC (source URL: https://videolan.org)

Device information:
- Device: Samsung Galaxy A14
- OS: Android 13
- Obtainium version: 0.14.32-beta

**Comment by ImranR98** [comment]
This isn't something Obtainium can fix. Google Play just grabs a list of all apps on the device and assumes responsibility for updating them if they exist on the Play store. If you're already using Google Play then I don't see why you need Obtainium for these apps.

**Comment by SilkyRock** [comment]
> This isn't something Obtainium can fix. Google Play just grabs a list of all apps on the device and assumes responsibility for updating them if they exist on the Play store. If you're already using Google Play then I don't see why you need Obtainium for these apps.

Understandable, thanks for clearing this up.

Since I'm using Android on a Samsung device, not using Google Play Store is out of the question. My end goal is to have a Pixel + GrapheneOS combo sometime in the future, but for now, I'm just trying out different things. Thanks to you and all the contributors for your work!
