### ISSUE TITLE
Single export function instead of two

### ISSUE THREAD

**Issue by foxjaw** [ImranR98/Obtainium#1075]
Don't pick export directory & then push config there. Instead, let the file picker manage everything. Like Android native document UI giving option to rename, as well as select the destination in the same interface.

**Comment by ImranR98** [comment]
I'm not sure what you mean. Could you explain?

**Comment by foxjaw** [comment]
There are two UI buttons. One is "Pick Export Directory" & other's "Obtainium Export". Should we need this complication ? Just generate the config & push it to the file picker & it'll take care of both the destination & the filename.  
TL;DR: Just one button would be enough to export.

**Comment by ImranR98** [comment]
Yes, because we support continuous export, not just one time export. So, the app needs to have a specific directory where it can continue to automatically save export files, even in the background.

**Comment by ImranR98** [comment]
I'm talking about the auto export toggle.

**Comment by foxjaw** [comment]
Btw, I don't see any auto export toggle in the settings pane.

**Comment by ImranR98** [comment]
Have you selected an export directory?  You should see the toggle on the import/export page.

**Comment by ImranR98** [comment]
We used to have just one button before this feature was added.

**Comment by foxjaw** [comment]
Understood. Tq.
