### ISSUE TITLE
How do you properly validate the signature of the apk?

### ISSUE THREAD

**Issue by vmotnoya** [ImranR98/Obtainium#1086]
Hello,

     I'm trying to properly validate the signature of the apk and I'm not sure how to go about it.  I've researched on the internet on how to do it but I'm still unclear on if I'm doing it right.
     One command I used is "keytool -printcert -jarfile app-arm64-v8a-release.apk" which gave me the signature and the certificate fingerprints but I'm not sure what to do from there.  I see that you have you public key published on your GitHub. How do I use that to validate the signature of the apk?  Clear step by step instructions would be helpful to people like me that aren't developers.

Thank you.

**Comment by ImranR98** [comment]
Depends on what kind of signature it is, but for obtanium the following instructions should work: https://security.stackexchange.com/questions/231249/how-to-verify-a-gpg-file-signature-on-linux-and-windows-without-connecting-to-th
