### ISSUE TITLE
Inner Breeze (github) not being updated properly.

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#1091]
Pixel 7
GrapheneOS
Obtainium v.0.14.32-beta

Inner Breeze:
https://github.com/naoxio/inner_breeze
Fallback to older releases is on
Attempt to filter APKs by CPU architecture if possible is on
All others are off

I have 1.0.8 installed.  Obtainium reports that an update is available, and indeed 1.0.9 is available.  Asking for an update appears to download and install, after which is reported "Apps updated."  But the version doesn't change.

**Comment by ImranR98** [comment]
Looks like the developer forgot to update the version code in their APK. You can let them know about this, and as a temporary workaround you can disable version detection in obtainium.

**Comment by DiagonalArg** [comment]
Done ^^^^
