### ISSUE TITLE
cannot import 3rd party f-droid apps through search

### ISSUE THREAD

**Issue by foxjaw** [ImranR98/Obtainium#1094]
Tried importing microg f-droid apps.
https://microg.org/fdroid/repo  

![Screenshot_20231117-113014](https://github.com/ImranR98/Obtainium/assets/150133625/5831b3d1-5336-4f30-8c0f-1d93fa40499c)

Not just this, I have this issue literally on all 3rd party f-droid repos.

**Comment by ImranR98** [comment]
Are you selecting third party f-droid repo from the source override dropdown? Because this URL works fine for me.

**Comment by ImranR98** [comment]
Reopening because it is a bug on the import export page.

**Comment by ImranR98** [comment]
Not sure what you mean. Where do you want to copy it from?

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.33-beta
