### ISSUE TITLE
Doesn't update LibreTube to v0.20.0

### ISSUE THREAD

**Issue by shellheim** [ImranR98/Obtainium#1095]
**Describe the bug**
[LibreTube](https://github.com/libre-tube/LibreTube) is a [piped](https://github.com/TeamPiped/Piped) client for android. It's latest release 'tag' is [v0.20.0](https://github.com/libre-tube/LibreTube/releases/tag/v0.20.0) but on the [releases](https://github.com/libre-tube/LibreTube/releases) page the highest version seems to be v0.19.0. Because of this (probably) Obtainium doesn't update to v0.20.0 and thinks v0.19.0 is the latest version.  

**To Reproduce**
1. Install LibreTube through obtainium.
2. Confirm the latest tag on LibreTube's repo (v0.20.0)
3. Check the latest version installed by obtainium.

**Screenshots and Logs**  

Latest entry on `/releases` page of LibreTube.

![image](https://github.com/ImranR98/Obtainium/assets/116480892/426c8753-b361-480d-86be-5f7e4efc82c5)  

Latest entry on the `/tag` page of LibreTube.  

![image](https://github.com/ImranR98/Obtainium/assets/116480892/ab3130f5-b13f-482f-a113-24cce14a3e07)  

Latest release installed by obtainium.  

![Hvyb](https://github.com/ImranR98/Obtainium/assets/116480892/2eb14b6b-6291-493c-973e-56e4c4b027f5)
****

**Please complete the following information:**
 - Device: Is it really necessary?
 - OS: Android 8.1 
 - Obtainium Version: v0.14.32-beta
**Additional context**
Is this because obtainium only looks at `/releases` not at `/releases/tags/v.x.y` when the source is gitub? Does this mean apps have to make a 'proper' release on github for obtainium to detect it?

**Comment by ImranR98** [comment]
Yes, you need to have an actual release with APKs attached. If you want to use tags, you'll have to enable track only mode and that would allow you to get update notifications without actually being able to download or install anything.

**Comment by alexwaibel** [comment]
This actually is an issue with GitHub as pointed out in the linked issue. 

The releases URL doesn't show the latest release
https://github.com/libre-tube/LibreTube/releases

But this URL does
https://github.com/libre-tube/LibreTube/releases/latest

Maybe best to use the latter for checking for updates in obtanium?

**Comment by shellheim** [comment]
Yeah I did see that. Unfortunately using that url doesn't work either as it seems that obtainium defaults to `https://github.com/user/project` if that's present in the url. Also according to Imran obtainum only works when it's a proper release.

**Comment by shellheim** [comment]
A temporary fix would be to switch to the f-droid repo for the app.

**Comment by ImranR98** [comment]
You could try the 'verify latest tag' option to see if that helps.

**Comment by shellheim** [comment]
Yeah that was on but it still doesn't seem to work.

**Comment by DarkCrypt** [comment]
I had this same issue with LibreTube v0.20.0. Updating to v0.20.1 went flawless.

If you go and look, v0.20.0 never hit the releases page but was in the tags. V0.20.1 is on the releases page. Definitely a GitHub issue.

Same issue going on with URL-Radio [releases](https://github.com/jamal2362/URL-Radio/releases). V12.8 is in the tags but not on the releases page. Now I assume when v12.9 is released, this will straighten out this issue too... ? Guess we'll see.
