### ISSUE TITLE
Can't add app from apkmirror

### ISSUE THREAD

**Issue by cyberboh** [ImranR98/Obtainium#1097]
**Prerequisites**

**Describe the bug**
ALways get error forbidden message

**To Reproduce**
1. Add 
```
https://www.apkmirror.com/apk/vsco/vsco-cam/
```
2. Set to track only
3. Press add and see forbidden error message

**Screenshots and Logs**
Idk why i can not add screenshot here

**Please complete the following information:**
 - Device: Huawei
 - OS: Android 10
 - Obtainium Version: v0.14.33-beta

**Additional context**

**Comment by ImranR98** [comment]
Unfortunately it looks like APKMirror has started using Cloudflare to prevent web scraping (or at least prevent DDoS, which has the side effect of making web scraping more difficult). I have no clue how this could be worked around.

**Comment by ImranR98** [comment]
Weirdly, it only seems to happen for some URLs. This one seems fine: https://apkmirror.com/apk/instagram/instagram-instagram/

**Comment by BabyOilJohnson** [comment]
Twitter link not working.
```html
https://www.apkmirror.com/apk/x-corp/twitter
```

**Comment by ImranR98** [comment]
Yes, I don't see why signing in would change anything - the Cloudflare protection is probably on a lower level. Once it verifies your connection as "secure" (whatever that means), it adds some cookies that get used next time so you don't repeatedly have to go through the verification (those cookies likely don't care whether you're signed in or not). Obtainium can't deal with cookies, and isn't able to pass the verification anyways.

**Comment by Snowpop** [comment]
Also experiencing this issue with
```
https://www.apkmirror.com/apk/google-inc/youtube/
```

**Comment by ImranR98** [comment]
> Also experiencing this issue with
> 
> ```
> https://www.apkmirror.com/apk/google-inc/youtube/
> ```

Works for me. Cloudflare verification seems to show up inconsistently.

**Comment by ImranR98** [comment]
Closing this issue as I don't think it's realistic to think we could get around CloudFlare's protection. It does seem to happen inconsistently though, myself and other users have had no issues with APKMirror - it might depend on your IP.
