### ISSUE TITLE
How to Import apps from JSON?

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#11]
It's not apparent what app I could use to open and copy the contents of a JSON file. Is it on the roadmap to have import work by importing a backup file or is it possible to have a txt form of backup?

**Comment by ImranR98** [comment]
Unfortunately the Flutter plugin I usually use for file picking does not support Android 13. They are working on it and it will hopefully be updated soon. Until then copy-pasting manually is the only option (if not, I'll add it for older versions of Android at least).

Importing regular text backups (list of URLs) will also be in a release soon.

**Comment by ImranR98** [comment]
File picker plugin was updated 🎉
Added to latest release
