### ISSUE TITLE
Preserve activity data while the app is in the background

### ISSUE THREAD

**Issue by MatsG23** [ImranR98/Obtainium#110]
1. Open an app from the app list
2. Leave the app (do not close it)
3. Come back in the app later
4. All app specific things (logo, name, versions) will be gone and load after a short time

Is it possible to preserve the data specific to the app? It is a bit annoying.

**Comment by ImranR98** [comment]
Will be fixed in the next release.

**Comment by ImranR98** [comment]
Should be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.7.3-beta
