### ISSUE TITLE
Suggestion for version detection in HTLM sources

### ISSUE THREAD

**Issue by hurried6158** [ImranR98/Obtainium#1101]
Currently, version detection for HMTL sources where there is no version string in the HTLM or the apk link is not supported. A case where such support would be nice is for protonapps.com as discussed in #970 and #606. I want to suggest an approach that might or might not be feasible in an Android app (my knowledge in android and app development for that matter is lacking).

I would suggest taking the checksum of something like the first 30 bytes (header of the zip/apk file) of the APK and store this. During a check for updates, only download 30 bytes of the APK, checksum and compare to the currently stored checksum. If they differ, one could conclude that there is a new version available.

Hopefully this approach is sensible.

/H

**Comment by ImranR98** [comment]
Really good idea 👍

**Comment by hurried6158** [comment]
I'm glad you enjoy the idea. I think the ideal way of doing this is with a HTTP range request. Not all servers hosting files support this, but many (or most?) do (this is the case with peotonapps). If they do, they should return HTTP response code 206 wheb the HTTP range request is processed. Since not all do, it might be worth having the version string support left as a fallback. And for scenarios with no support for HTTP range request, and no presense of a version string, it would be unsupported by Obtainium I suppose?

**Comment by hurried6158** [comment]
(Sorry for accidentally pressing "Close with comment")

**Comment by hurried6158** [comment]
So I did some experimenting by curling the Proton Calendar APK with a HTTP range requiest using ´curl´:

```bash
> curl -r 0-29 -O https://protonmail.com/download/CalendarAndroid/ProtonCalendar-Android.apk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    30  100    30    0     0    110      0 --:--:-- --:--:-- --:--:--   109
> xxd -e ProtonCalendar-Android.apk
00000000: 04034b50 00000000 08210000 00000221  PK........!.!...
00000010: 00000000 00000000 00000000     0066  ............f.
```
Looking at the (APK) ZIP file header, unfortunately the relevant fields in the [header](https://en.wikipedia.org/wiki/ZIP_(file_format)#Local_file_header)  such as "File last modification date" and "CRC32 of uncompressed data" are all set to 0. This would probably mean that checksumming/hashing these 30 bytes won't really provide enough information that differs between two releases.

Perhaps one approach would be to checksum/hash something like the first 1KB of the APK. They should reasonably differ I suppose, but I can't say for sure.

**Comment by hurried6158** [comment]
@TotallyAvailable while I agree with a lot of what you're saying, in the case of Proton, there are numerous people who have done such inquiries already with no positive outcome. They only support protonapps.com and google play store as channels for downloading their apps. They do however post Proton VPN and Proton Mail (most often a few weeks behind) on Github releases.

**Comment by hurried6158** [comment]
Thanks! I will let you know if it works in the case of protonapps as soon as they release an update for any of the applicable apps.

**Comment by hurried6158** [comment]
It seemingly works. Got the Proton Calendar update that was released today. Thanks again for implementing this!
