### ISSUE TITLE
versionCode not increased?

### ISSUE THREAD

**Issue by IzzySoft** [ImranR98/Obtainium#1102]
It seems that `versionCode` was not increased when releasing `0.14.33`: as `0.14.32`, it still uses `1226`. As you know, `versionCode` is what Android uses internally to tell versions apart, so this update won't be signaled to those having `0.14.32` installed. Just to let you know :wink:

**Comment by ImranR98** [comment]
Whoops, you're right.

**Comment by IzzySoft** [comment]
Thanks for your fast action!
