### ISSUE TITLE
Better Error Message for Gitlab: version ID & apk available, but "could not find a suitable release"

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#1106]
Pixel 6
GrapheneOS
Obtainium v.0.14.34-beta

This URL with "Fallback to older releases" and "Attempt to filter APKs by CPU architecture" turned on, the rest off:
https://gitlab.com/cosmosapps/candle/

Latest Version is listed as 0.2.3, which is correct, the .apk is available, and I have not yet installed the app.  On Obtainium's update check, it reports, "Could not find a suitable release".

**Comment by ImranR98** [comment]
This is a GitLab limitation - due to the way that APK is linked, it can't be extracted without using the GitLab API, which needs authentication. See #3. You can add a GitLab access token in the settings, after which this should work.

**Comment by DiagonalArg** [comment]
Ah, that explains why I have no errors on my Pixel 7, but only on the Pixel 6 that I've been setting up for a friend.

The "timeout" message I get for github makes it obvious that a key is the solution, but "can not find a suitable release" is a bit more obscure.  Wondering if there's some way to make that more obvious?

Thanks for your input.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases
