### ISSUE TITLE
Filter search in "Add App" tab

### ISSUE THREAD

**Issue by cvoges12** [ImranR98/Obtainium#1107]
### Problem ###

The list of results in search for apps to install can be long and hard to sift through. Especially for more generically named applications such as signal, you'll get many unrelated results. Some times you just want to search something in a particular source or sources because you already know where it would probably come from, ie - Signal, Telegram, Steam, WhatsApp, VLC, etc. Sometimes you may want to exclude certain sources because you might not know the exact source but have an idea of where it isn't.

### Description ###

There should be a way to filter which sources you are searching from. There should be a way to white list the sources you want to search from and black list sources you don't. This doesn't mean the default search for all sources needs to be removed.

There could be a little filter button by the search button or in the search menu. Upon pressing the filter button, a filter menu appears which allows you to check or uncheck sources which you only want to search from. This would allow more granular searching and ease the user's experience without compromising existing features or complicating design.

### Alternatives ###

- You could make it to where you could search each source individually. But this would cut back on the search tool's ability to sift through multiple sources at once.
- You could manually put the URL in. But this is assuming you don't need to search.
- You could manually search the sources yourself. But this doesn't allow you to search multiple sources at once and isn't user friendly.
- You could look for other ways to filter searching.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.35-beta

**Comment by cvoges12** [comment]
@ImranR98 Is it possible to have this feature be able to filter all of the sources? Right now there's github, gitlab, f-droid, and codeberg. But there's also:
- f-droid (third party repos)
- izzyondroid
- sourceforge
- sourcehut
- apkpure
- etc

**Comment by ImranR98** [comment]
Only the sources listed are searchable - search has not been implemented for the others.

The only exception to that is third party repos which are searchable, but are missing from this menu because it's more complicated (you need to provide the repo url) - I wanted to keep the main search simple. So for third party sources, like f-droid repos or gitlab instances, you can use the import/export page (iirc you had another issue for that).
