### ISSUE TITLE
LibreraReader app installed from github apk, Obtainium can't see it. I tried filter apk/release.

### ISSUE THREAD

**Issue by valtoree** [ImranR98/Obtainium#1112]
Hi as per title, 
If you manually install the apk from github, version Pro, from releases

https://github.com/foobnix/LibreraReader/releases

And then go add the app in Obtainium, Obtainium can't see it. Tells me to install app.

I tried using filters with 'Pro', but still nothing.

Can anyone else try it and see if they can get it please?

Thanks for your time.

 - Device:  P6a
 - OS: GrapheneOS
 - Obtainium Version: 0.14.34

**Comment by ImranR98** [comment]
Fixed (you'll need to remove and re-add it): https://github.com/ImranR98/Obtainium/releases/tag/v0.14.35-beta

**Comment by valtoree** [comment]
Ty 🙏 amazing ur speed 🙇‍♂️
