### ISSUE TITLE
"Not a valid APKMirror URL"

### ISSUE THREAD

**Issue by eylenburg** [ImranR98/Obtainium#1114]
If I try to add this URL: https://apkmirror.com/apk/tacit-dynamics/foldersync
I get the response "not a valid APKMirror URL". Which is strange because this exact URL used to work a few months ago when I last tried Obtainium (I have still the .json export to confirm the URL)

Another user seems to have encountered the same problem: https://github.com/ImranR98/Obtainium/issues/130#issuecomment-1807163762_

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.35-beta

**Comment by eylenburg** [comment]
That was quick!
