### ISSUE TITLE
Add APKCombo support

### ISSUE THREAD

**Issue by CharlesCanlom** [ImranR98/Obtainium#1117]
**Prerequisites**

**Describe the feature**

**Describe alternatives you've considered (if applicable)**

**Additional context**
![Screenshot_20231125_190206_Firefox](https://github.com/ImranR98/Obtainium/assets/24204274/3a2b3df1-6187-45c3-b3d8-9e096345cd8f)
The download button links to this: https://download.apkcombo.com/com.sweatwallet/Sweat%20Wallet_46.0_apkcombo.com.apk?ecp=Y29tLnN3ZWF0d2FsbGV0LzQ2LjAvMjAzMy41ZGIyNWY1MzQ0ZmM2NWUzMzJmOTU1YjdkOTk0YWZkZGZkYWQwYWJlLmFwaw==&iat=1700909946&sig=9d20767cc588c335bc9b9bb2833377d7&size=180468530&from=cf&version=latest&lang=en&fp=baeb0950c22b3e2f50ee9720fa02f6cd&ip=(notgonnadoit)

**Comment by DwainZwerg** [comment]
replicate of #341
