### ISSUE TITLE
Delay or cancel all requests for a specific source when rate-limited

### ISSUE THREAD

**Issue by har-nick** [ImranR98/Obtainium#1124]
**Prerequisites**
Checked this request doesn't already exist in other issues.

**Describe the feature**
When a source rate-limits Obtanium, the app still attempts to fetch other apps from that source, usually resulting in a flood of notifications over a short period.

It'd be nice to cancel or delay requests to other apps of the same source, and, instead of showing a separate notification for each app being requested, show a catch-all notification. For example:

> "Github has rate-limited your device. Update/s for \<APP NAME> / X apps (in the case of multiple) have been delayed."

**Comment by ImranR98** [comment]
This is already the case - one notification for multiple apps: 
![Screenshot_1702001567](https://github.com/ImranR98/Obtainium/assets/30463115/c75fe048-c2f5-4613-a8fe-ed084efb48f7)

**Comment by har-nick** [comment]
Closing for now, as I haven't been rate-limited in a couple of weeks to check.
