### ISSUE TITLE
[Feature request] Ability to add a comment or custom download URL to an app

### ISSUE THREAD

**Issue by eylenburg** [ImranR98/Obtainium#1126]
It would be good if you could have a comment field in the "edit app" screen that then gets displayed whenever you click on the app.

Why? In my case I bought the Pro version of an app directly from the developer (rather than through Google Play). I was provided a unique URL where I can download my APK. But this URL is always the same, it resolves to the newest APK but doesn't give any indication which version it will download or whether a new version has been released. Hence I'm using Obtainium to track APKMirror for updates to the non-Pro app. Whenever there's an update, I then have to find the email with the download URL again. It would be nice if I could add a comment containing that URL in Obtainium so that I have it in the same place.

Another alternative I was thinking of would be to have a separate "download URL" you can add in the "edit app" screen. Then you could for example track an app on APKMirror but download it from a user-provided URL. This would be useful for all apps where there's an APK download on their website, but with no version indication, meaning that the website on its own is useless for tracking updates.

**Comment by ImranR98** [comment]
The HTML source now supports fixed URLs so you should try that first.

**Comment by eylenburg** [comment]
No I get "could not find a suitable release". The URL is something crazy like https://click.pstmrk.it/2sm/vendors.paddle.com%2Fdownload%2Fproduct%2F41fef8a5-fe43-4bca-a1d8-355dca1fbe53/RF11HSgN/7cQ/Uq7NRIgY2C/bG9ja2Vy (slightly changed)

I'm happy to open the URL manually in the browser to download the APK, it would just be create to save the URL in Obtainium (e.g. as a comment) so it's in the same place.

**Comment by ImranR98** [comment]
I've added a general "about" field where you can put anything - this will then show up on the app details page. You can long press it to copy.

https://github.com/ImranR98/Obtainium/releases/tag/v0.14.36-beta
