### ISSUE TITLE
Browsing apps from popular repos

### ISSUE THREAD

**Issue by candroid-man** [ImranR98/Obtainium#1131]
**Describe the feature**

Obtainium is an amazing project, however I envision something different, something that could replace F-Droid.

Imagine an app similar to Droid-ify. You open the app, you look at all of the apps available in the repositories you set in the settings, you tap on an app, and hit install. 

So from my experience, I typically find out about the latest FOSS apps from the F-Droid/IzzyOnDroid repos, and then I add those to Obtainium manually. I assume I'm not the only one? Well why don't we just make that process easier?

We can turn Obtainium into a standard app store like Droid-ify, but then when you go to install the app it will go out to the source (GitHub, GitLab, etc.) and grab the latest .APK automatically, and install it rather than downloading it from the repository.

I think you should still be able to manually add apps in case there is some error or something, but I feel like this approach would make Obtainium much more user friendly and simple.

**Comment by ImranR98** [comment]
See #68
