### ISSUE TITLE
Vivaldi

### ISSUE THREAD

**Issue by golf1487** [ImranR98/Obtainium#1132]
Vivaldi has alternative download option on their website:

https://vivaldi.com/android/

Please add an option to download apk directly from their website:

https://downloads.vivaldi.com/stable/Vivaldi.6.4.3171.110_arm64-v8a.apk

**Comment by ImranR98** [comment]
This already works.

**Comment by ImranR98** [comment]
I added https://vivaldi.com/android/ with an APK selection filter. What error do you see?

**Comment by ImranR98** [comment]
See here for an explanation of how the HTML source works: https://github.com/ImranR98/Obtainium/issues/954#issuecomment-1745970526
