### ISSUE TITLE
Error checking for Updates - Nextcloud

### ISSUE THREAD

**Issue by andreapx** [ImranR98/Obtainium#1135]
**Describe the bug**
Every time the app checks for updates I get the error:
_"Error checking for updates"
"Could not find a suitable release [Nextcloud]"_
Obtanium says:
_Latest version is: stable-3.25.0
Installed version: 3.26.0_
In the [Nextcloud android app repository](https://github.com/nextcloud/android) I see the 3.26.0 release

**To Reproduce**

**Please complete the following information:**
 - Device: Pixel 7
 - OS: Android 13
 - Obtainium Version: 0.14.35-beta

**Comment by ImranR98** [comment]
The 3.26 release does not have APK files attached.

**Comment by andreapx** [comment]
> The 3.26 release does not have APK files attached.

Damn, and I thought that I had checked everything...
Thanks!
