### ISSUE TITLE
Add Source From Share Menu

### ISSUE THREAD

**Issue by jollySleeper** [ImranR98/Obtainium#1139]
**Describe The Feature**
It would be great if we can directly add an app source from browser or anywhere using Android Share Menu.
Basically implement an Entry in Android Share Menu for directly adding App Source.

**Comment by ImranR98** [comment]
Obtainium doesn't let you add sources at all. If you meant adding apps, this is already covered by other issues and will be included in the next release.

**Comment by jollySleeper** [comment]
Okay, Thanks
Can I know which issue?
Thank you for your time <3
