### ISSUE TITLE
Show obtanium as "Obtainium" in "Alarms & reminders"

### ISSUE THREAD

**Issue by basings** [ImranR98/Obtainium#1141]
**Prerequisites**

no other issue is open or closed about it

**Describe the feature**
Obtainium is shown as "dev.imranr.obtainium" in Alarms & reminders.

For new Sources, it's preferable (not required) if you suggest how the following details can be extracted from the Source in a reliable way (like an API or through web scraping):
- v0.14.36-beta
- grapheneos A14

**Comment by ImranR98** [comment]
I don't even see it in my Alarms and Reminders menu. Could you try reinstalling?

**Comment by basings** [comment]
Let's hope the backup works

**Comment by basings** [comment]
![Screenshot_20231216-101216](https://github.com/ImranR98/Obtainium/assets/92867705/b5de798c-c546-4264-a259-00e3eba14f67)

It's still shown but now the naming is correct

**Comment by ImranR98** [comment]
Weird how I don't see it on mine - might need a reinstall. Closing.
