### ISSUE TITLE
Apk cannot be installed since latest update from android. 

### ISSUE THREAD

**Issue by mollyuser** [ImranR98/Obtainium#1142]
**Prerequisites**

**Describe the bug**

**To Reproduce**

**Screenshots and Logs**

**Please complete the following information:**
 - Device: pixel 8
 - OS: GrapheneOS & Stock Android (tested on both)
 - Obtainium Version: all releases

**Additional context**

The apk cannot be installed since the last update from android, it is an android bug but it probably wont be fixed by them till february. I think it s best if u find a way to work around this bug because android users on latest release cannot install the apk anymore.

**Comment by ImranR98** [comment]
Could you provide more details? I'm on the latest Graphene OS release and have had no issues installing Obtanium or apps from Obtanium.

**Comment by mollyuser** [comment]
> Could you provide more details? I'm on the latest Graphene OS release and have had no issues installing Obtainium or apps from Obtainium.

I have reported this to GOS devs also, and they have confirmed the issue , it is also on stock os.QPR1 issue they sayd. I am not sure if only the pixel 8 series are affected. If obtainium is already installed everything works fine, the issue is only if u dont have obtainium and u download the apk and try to install it. It wont install. Are u on the 701 release for GOS?

**Comment by mollyuser** [comment]
I got a message from GOS that they are going to fix the issue before google does, so the fix will be added in the next update. If u are on the latest GOS (701) the apk cannot install, i dont think u are on the latest release since it is confirmed that it s not device specific. StockOS will not fix it till february i think.

**Comment by ImranR98** [comment]
Yes I'm on the 701 release. I have not tried reinstalling obtainium though, but updating it and installing other apps through it does still work.

Do you have any links/other info on this?

**Comment by ImranR98** [comment]
Nvm, I see the chat on Matrix

**Comment by ImranR98** [comment]
https://pastebin.com/8ea8HDsK

Well that sucks. I have nowhere near the Android knowledge needed to understand where the error comes from.

**Comment by ImranR98** [comment]
GOS dev:

> it's fixed by the latest release that's coming out soon, please be patient
> if you were on stock OS, you'd be waiting for January or February

**Comment by mollyuser** [comment]
GOS will fix it probably within a day or 2, but stockOS users will have to wait till january, probably february. Hope someone can help you to find a way to work around this bug.

**Comment by mollyuser** [comment]
GOS devs are amazing, always on top of things.

**Comment by skwde** [comment]
FYI, I had the same issue on Pixel 7a with GrapheneOS.

I just ran the latest update and the install worked.

@ImranR98 Can you please comment on

- difference between `app-release.apk` and the different architecture versions? Am I correct to assume that `app-release.apk` contains all of the architecture versions and installs the fitting one?
- I am not quite sure what release GOS release you are referring to with 701?! Please enlighten me.

@mollyuser Can you add the link to the GOS issue?

**Comment by drizzt** [comment]
I have the solution, I'll send a PR later

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.39-beta
