### ISSUE TITLE
Skip this version,  version x.y.z has bug. Dont show me update message or icon for that version. 

### ISSUE THREAD

**Issue by blackholeearth** [ImranR98/Obtainium#1143]
**Describe the feature**

Example app:
Cx explorer has bug  (analyze > apk list > file sizes are wrong. ). 
Affected version:   2.0.3 to 2.1.1

So i deleted apk . İnstalled v2.0.2 from apkpure  .

Added apkpure url to obtainum
( https://apkpure.com/tr/cx-file-explorer/com.cxinventor.file.explorer )

İt shows update available.  

But i want to **"ignore this version: 2.1.1 "** (cuz its buggy )
Dont show me update notification for 2.1.1 again.
And want to  Add note for that specific version.

Note:  ```  its buggy bro. dont install it . Stay on 2.0.2 its good.. ```

----
Lets say , 5 days has passed 
2.1.2 available. İ will get update available message.

And i will also skip that one. (İm pretty sure he wont fix it   for another 2 - 3 months. )

**Comment by ImranR98** [comment]
You can disable version detection and then mark the app as updated.

**Comment by ImranR98** [comment]
Closing as a workaround is available.

**Comment by bilogic** [comment]
> You can disable version detection and then mark the app as updated.

Would be great if we can `Skip this version`, so that if a newer fix/version is released, it still gets detected. The workaround means we stop version detection forever, that is actually quite dangerous.
