### ISSUE TITLE
huawei gallary source abi problem

### ISSUE THREAD

**Issue by qqyc** [ImranR98/Obtainium#1144]
the app downloaded in huawei gallary market is 64bit but those one which installed by obtainium is 32bit, open the detect button was not work to change to 64bit.

**Comment by ImranR98** [comment]
Could you post a link to the app

**Comment by qqyc** [comment]
> Could you post a link to the app

https://appgallery.huawei.com/app/C27162
This is the app version of Huawei AppGallery; the apps downloaded from it are 64-bit

**Comment by ImranR98** [comment]
I haven't been able to find any way to get additional APKs from AppGallery beyond what was originally suggested by a user in issue #756. It's possible there is an alternative URL for the 64 bit version of the app, but for now there doesn't seem to be a way to get to it.
