### ISSUE TITLE
Error : "Name_of_the_app keeps stopping" on launch

### ISSUE THREAD

**Issue by belgiumed** [ImranR98/Obtainium#1146]
**Prerequisites**

**Describe the bug**
Some apps (not all) I've installed with Obtainium (from Apkpure or Aptoide for instance) won't open. I have the message : "(name of the app) keeps stopping" 
I, then, have two options : App Info or Close app.
This happened again today with [Workout time](https://workout-timer-nicolas-bridoux.en.aptoide.com/app) and [Wordreference ](https://m.apkpure.com/wordreference-com-dictionaries/com.wordreference).

When I download those app directly from Apkpure and Aptoide, it works fine.

**To Reproduce**
1. Go the Apkpure or Aptoide
2. Look for the app (wordreference)
3. Copy the URL
4. Add it on Obtainium
5. Download the app
6. Launch the app and the error appears

**Screenshots and Logs**
![Screenshot_20231210-095455](https://github.com/ImranR98/Obtainium/assets/54602938/60961c45-d171-4548-b002-567cbded77d4)

**Please complete the following information:**
 - Device: OnePlus 6T
 - OS: OxygenOS 10.3.10 (Android 10)
 - Obtainium Version: 0.14.36

**Additional context**
I have a rooted phone with no google account on it if that helps.

**Comment by ImranR98** [comment]
When you download from Aptoide, does it install the app directly or does it install the Aptoide store first? Obtainium uses the Aptoide API to get the APK file, for example: https://ws2.aptoide.com/api/7/getApp/app_id/66005254
I don't know of any other way to get APKs from this site.

**Comment by ImranR98** [comment]
For APKPure, it's a different issue likely to do with XAPKs - see #682 and #598.
