### ISSUE TITLE
GitLab: Use Public 'Project Name' Search API for Unauthenticated Users

### ISSUE THREAD

**Issue by skwde** [ImranR98/Obtainium#1147]
**Describe the bug**
Using `Add App` with GitLab search enabled gives an error:

```err
Unexpected Error
GitLab needs additional credentials (in Settings)
```

**To Reproduce**

1. Go to `Add App`
2. Search for some App
3. Ensure `GitLab` is selected as a source
4. See error mentioned above 

**Please complete the following information:**
 - Device: `Pixel 7a
 - OS: `GrapheneOS`
 - Obtainium Version: `v0.14.36-beta`

**Comment by ImranR98** [comment]
Not a bug. GitLab search only works if you have a GitLab API key which you can get for free by making an account. You can add this key in Obtainium's settings.

**Comment by skwde** [comment]
@ImranR98 thanks for your fast reply.

Is this documented somewhere? 
What scope? I.e. I guess read_api should be sufficient?

**Comment by ImranR98** [comment]
No docs right now. Scopes needed are minimal - try it with everything disabled or just read_api.

**Comment by skwde** [comment]
Ok, I can confirm that `read_api` is sufficient.

**Comment by skwde** [comment]
@ImranR98 would you mind commenting on how the search is actually done?

I guess you are using <https://docs.gitlab.com/ee/api/search.html>? (which needs authentication)

While to my understanding <https://docs.gitlab.com/ee/api/projects.html#search-for-projects-by-name> doesn't need authentication. Couldn't this be used to remove the need for the api token?

What's the point of using search instead of project search?

**Comment by ImranR98** [comment]
I just went with the first API I found. Will look into switching to this one.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.37-beta

**Comment by skwde** [comment]
@ImranR98 we discussed above the removal of the GitLab personal access token. Though it seems to be still required, as mentioned as a solution in this issue https://github.com/ImranR98/Obtainium/issues/1380

**Comment by ImranR98** [comment]
This issue was specifically about search - we no longer need an API token for search. We do still need it for improved APK extraction, which is what the other issue is about.
