### ISSUE TITLE
Translate into other language

### ISSUE THREAD

**Issue by JohnsonRan** [ImranR98/Obtainium#115]
I want to translate this app into Simplified Chinese but seems strings are hardcoded...

**Comment by ImranR98** [comment]
With https://github.com/ImranR98/Obtainium/commit/17b1f6e5b0cd050890e4642ad8004f2b12207fe3, it's now possible to add new languages (using the [easy_localization](https://pub.dev/packages/easy_localization) plugin). Contributions are welcome!
