### ISSUE TITLE
Ability To Use Shizuku As Package Installer

### ISSUE THREAD

**Issue by JDKamalakar** [ImranR98/Obtainium#1151]
**Prerequisites**
Shizuku & Android 11+

**Describe the feature**
Add ability to install apps using shizuku on Android 11 & above this will allow apps to be updated in background as well as will not require to tap install or update for every app.

For new Sources of apps that use similar methods: Tachiyomi (One of its fork is in flutter but I can't remember which one it was.), Skydroid, Canta (App Manager)

**Comment by ImranR98** [comment]
Please search through existing issues - this has been discussed before and is not planned.
