### ISSUE TITLE
Unremovable github tokens 

### ISSUE THREAD

**Issue by 1xFF** [ImranR98/Obtainium#1153]
**Prerequisites**

Probably related, but closed: #913

**Describe the bug**

Once a github token expires, removing it from obtainum doesn't stop "Unauthorized" errors.

**To Reproduce**
Add github token to in settings
It expires (probably unnecessary?)
Delete token in settings
Now unauthorized with no token used

**Additional context**
Because the UI reflects the token deletion after a force-stop, I think its trying to use an empty token on whatever endpoint github has for that.

Adding a token fixes this until its removed or expires again.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.37-beta
