### ISSUE TITLE
App track on any websites

### ISSUE THREAD

**Issue by persianGOD** [ImranR98/Obtainium#1158]
I was thinking it would be great if you added this to your app. Some apps that I downloaded from random websites especially those that are not on Google Play when the new versions of them released I must check those websites manually and then match them with the current app version and it's somehow annoying. If you add a feature that lets obtainium track app link on that specific website it would be useful and helpful and I didn't see this feature on any app. It can be like this: we put the link of the page that app in there and then your app tracks any new version of it as they released. This suggestion is for another source, not GitHub or Gitlab or other ones that exist already. Thanks.

**Comment by ImranR98** [comment]
This is already a thing - it's the HTML source that gets used when none of the other sources are a match. See https://github.com/ImranR98/Obtainium/issues/954#issuecomment-1745970526
