### ISSUE TITLE
issue: could not find a suitable release

### ISSUE THREAD

**Issue by FellowGitHubber** [ImranR98/Obtainium#1160]
ive seen a post for this issue but it did not solve my issue

When i put the link in the app source and press add, it says "could not find a suitable release" but the source i am linking too (https://github.com/drawpile/Drawpile) has a apk in each release, i dont understand what its not seeing 

Reproduce
1. Go to "Add App"
2. paste in source https://github.com/drawpile/Drawpile
3. Tap add app
4. see error

 - Device: Galaxy A21s
 - OS: Android
 - Obtainium Version: e.g. 0.14.36-beta

it add the app when i allow prereleases but i dont want the prerelease

**Comment by ImranR98** [comment]
Only the pre-releases have APKs attached, regular releases don't: https://github.com/drawpile/Drawpile/releases
