### ISSUE TITLE
Not centered text at "Select Expot Folder" button

### ISSUE THREAD

**Issue by robertoprubio** [ImranR98/Obtainium#1162]
The text at the "Select Export Folder" is not centered.
Is not a big deal but is here ;)

![image](https://github.com/ImranR98/Obtainium/assets/31618496/7ee360bf-fbd1-4f65-87e1-729081463220)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.38-beta
