### ISSUE TITLE
Latest is not correctly displayed for some apps

### ISSUE THREAD

**Issue by robertoprubio** [ImranR98/Obtainium#1163]
Latest app release is not correctly displayed for RecordYou (https://github.com/you-apps/RecordYou)

Latest release is 7.2
![image](https://github.com/ImranR98/Obtainium/assets/31618496/7f8b4315-817b-4967-80ad-61e7e97ad359)

But in github releases list, I do not know why, 7.2 isn't listed:
![image](https://github.com/ImranR98/Obtainium/assets/31618496/d3f711e3-2ad1-4f21-b0ac-7172b3f6dc8f)

My obtanium settings for RecordYou app:
![image](https://github.com/ImranR98/Obtainium/assets/31618496/e8968b33-48ce-4936-b5ae-e84536ddd4ab)
![image](https://github.com/ImranR98/Obtainium/assets/31618496/1a796394-8533-457d-aba0-8f5ae978a658)
![image](https://github.com/ImranR98/Obtainium/assets/31618496/100c8276-96d0-4f34-bdd1-0d859206b779)

**Comment by ImranR98** [comment]
This sometimes happens for some repos for an unknown reason. The 'Verify latest tag' toggle was supposed to fix that (it's off by default as it doubles the number of API calls). But it seems like it still doesn't work for this app - will be fixed in the next release.

**Comment by robertoprubio** [comment]
No, is not working for this app.
Thanks for the good work!

**Comment by ImranR98** [comment]
That option should work now: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.38-beta

**Comment by robertoprubio** [comment]
Is working now. Thanks!
