### ISSUE TITLE
Too many requests (rate limited)

### ISSUE THREAD

**Issue by sombresu** [ImranR98/Obtainium#1164]
**Describe the bug**
Can't update the apps, which is the only app's sole purpose. 

**To Reproduce**
Try to update app when there's an available update. I'm trying to update Tachiyomi and Obtainium.

**Please complete the following information:**
 - Device: poco x3
 - OS: miui 13
 - Obtainium Version: v0.14.36-beta

**Comment by methicodx** [comment]
me to like this 

![Screenshot_20231217_205838.jpg](https://github.com/ImranR98/Obtainium/assets/141909414/e7c7786b-7fa7-4795-ab0d-05448af79b28)

**Comment by ImranR98** [comment]
This is a limit imposed by GitHub - not something Obtainium can do anything about. You can increase your limit by adding a GitHub API key on the settings page (link to instructions are there too).

Please search through existing issues before creating new ones.

**Comment by methicodx** [comment]
> This is a limit imposed by GitHub - not something Obtainium can do anything about. You can increase your limit by adding a GitHub API key on the settings page (link to instructions are there too).
> 
> Please search through existing issues before creating new ones.

for example

i post by 14 minutes ago but show still in 28 minutes

**Comment by sombresu** [comment]
> This is a limit imposed by GitHub - not something Obtainium can do anything about. You can increase your limit by adding a GitHub API key on the settings page (link to instructions are there too).
> 
> Please search through existing issues before creating new ones.

I did have API key added and expired on February 2024.
