### ISSUE TITLE
3rd Party FDroid Repo for Threema Libre failes with error Message

### ISSUE THREAD

**Issue by DSDV** [ImranR98/Obtainium#1165]
**Describe the bug**
if you visit: https://threema.ch/en/faq/libre_installation 
and copy the provided link to obtanium it does not detect it as 3rd party fdroid repository.
if you select it manually it does not recognize the uri sheme.
a workaround was to delete the `fdroidrepos://` part

**To Reproduce**
1. go to https://threema.ch/en/faq/libre_installation 
2. get link
3. paste into add dialogue of obtanium
4. get error 1
5. select 3rd party fdroid repo
6. get error 2

**Please complete the following information:**
 - Device: Pixel
 - OS: GrapheneOS
 - Obtainium Version: latest

**Additional context**
a workaround was to delete the `fdroidrepos://` part
so for example `releases.threema.ch/fdroid/repo?fingerprint=5734E753899B25775D90FE85362A49866E05AC4F83C05BEF5A92880D2910639E` selected as 3rd party repo will work

_with kind regards 
and big thanks for you project <3_

**Comment by ImranR98** [comment]
> so for example releases.threema.ch/fdroid/repo?fingerprint=5734E753899B25775D90FE85362A49866E05AC4F83C05BEF5A92880D2910639E selected as 3rd party repo will work

This is expected, not a workaround. Obtainium doesn't support the `fdroidrepo://` protocol since it is redundant - all third party repos have an `https://.../index.xml` anyways - and that's the file we want.

**Comment by DSDV** [comment]
Thanks for the clarification (:
