### ISSUE TITLE
Add "Don't Sort" Option to the HTML Source

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [ImranR98/Obtainium#1168]
I am trying to use obtainum to get dolphin emulator updates (because f-droid is too slow to update), but the problem is, I can't filter by beta or development versions. https://dolphin-emu.org/download/

The problem is that in order to differentiate whether the version is a beta version or a dev version, you'd need to check the headings, the download url does not say anything about it, in fact the download urls are the same format no matter what version it is.

**Comment by ImranR98** [comment]
I would rather not add this as its own source to avoid source bloat, but it's not clear how the generic HTML source could be modified to reliably grab specific HTML elements and associate them to specific links like you suggested.

Instead, here's how this could work:
- The latest dev version is always the top link after the links are sorted, so this should be the version that Obtainium currently grabs.
- The latest beta version is always the top link on the page, but only if you don't re-sort them alphabetically. I could add a "don't sort" toggle so you can get either dev or beta depending on that toggle.

**Comment by ego-lay-atman-bay** [comment]
> * The latest beta version is always the top link on the page, but only if you don't re-sort them alphabetically. I could add a "don't sort" toggle so you can get either dev or beta depending on that toggle.

That would actually be better (for general use anyway).

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.39-beta

You'll also need to enable "take first link" since it takes the last link by default.

**Comment by ego-lay-atman-bay** [comment]
It works now, thanks!
![Screenshot_20231221-141506](https://github.com/ImranR98/Obtainium/assets/70973578/97b14e4c-6e91-4551-bbc2-94bb1f453ee5)
