### ISSUE TITLE
After the update, obtainium does not run anymore 

### ISSUE THREAD

**Issue by HATOSHAH** [ImranR98/Obtainium#1169]
After updating to version 0.14.38. obtainium no longer runs and gives this error:
![IMG_20231219_021000](https://github.com/ImranR98/Obtainium/assets/86057784/66d51e4d-393c-45b6-920f-0eda01ef5118)

**Comment by ImranR98** [comment]
Probably due  to a syntax error in some translation file. Will be fixed in the next release.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.39-beta

**Comment by HATOSHAH** [comment]
Thanks
