### ISSUE TITLE
[QUESTION] Why dont search and update work for quik?

### ISSUE THREAD

**Issue by inson1** [ImranR98/Obtainium#1170]
https://github.com/octoshrimpy/quik

So, I tried search it, Obtainium didnt find it. Ok I added the url. Now Obtainium cant update it to last version.

What is the problem?

**Please complete the following information:**
 - Device: Xiaomi Redmi Note 8 Pro
 - OS: Android 11 
 - Obtainium Version: 0.14.38-beta

**Comment by inson1** [comment]
yes, if I try installing the apk my self it worked

**Comment by inson1** [comment]
and what about the search?

**Comment by flame-0** [comment]
> and what about the search?

It does fetch the latest version; the only issue is that the version number isn't updated. Essentially, it keeps reinstalling the latest version when you click 'update.' Just wait for the Quik developer to make the update.

**Comment by inson1** [comment]
@flame-0 I get that :) But when I searched in Obtainium Quik, I didnt found anything

**Comment by flame-0** [comment]
> @flame-0 I get that :) But when I searched Quik in Obtainium, I didnt found anything

Not sure, I just use the URL instead of the find feature.

**Comment by inson1** [comment]
@flame-0 that is second part of this issue :)

**Comment by ImranR98** [comment]
It's not clear why this repo doesn't show up in search, but it's not an Obtainium issue since we just use GitHub's API for search. It doesn't seem to show up on web search either: https://github.com/search?q=quik+octoshrimpy&type=repositories

**Comment by inson1** [comment]
thank you :)

**Comment by inson1** [comment]
problem is that quik is fork, if I search "quik fork:only" then I can find it
https://docs.github.com/en/search-github/searching-on-github/searching-in-forks
