### ISSUE TITLE
HTML problem

### ISSUE THREAD

**Issue by persianGOD** [ImranR98/Obtainium#1171]
https://www.farsroid.com/walli-wallpapers-hd-full/

I use this link for html even with track only on or off, I get this error:
Could not find a suitable release.

what does it mean?

**Comment by ImranR98** [comment]
Unfortunately the download button on this page is loaded in with JavaScript, so it cannot be scraped by Obtainium.

**Comment by austinarchibald** [comment]
@ImranR98 Hello, is there any way to automate downloading apks from Nextcloud web app?

https://nc.workbench.network/s/gdRnpcc2zrXz5Xg

Example link on the page: https://nc.workbench.network/s/gdRnpcc2zrXz5Xg/download?path=%2F&files=source-engine-v1.17.0026.apk

I then try to Filter APKs by RegEx: `^.*source-engine.*$`

But no suitable releases found. Any ideas? Thank you!
