### ISSUE TITLE
Root and Shizuku

### ISSUE THREAD

**Issue by re7gog** [ImranR98/Obtainium#1174]
Well, I have made a working root installer in my fork, shizuku is in the progress, so wait for the contribution
https://github.com/re7gog/Obtainium/tree/re7gog

**Comment by Turhvjbufv** [comment]
Why close as not planned?

**Comment by re7gog** [comment]
Shizuku is difficult, so i'm not sure how long it would take

**Comment by re7gog** [comment]
Yey, I did it, but it needs a little polish

**Comment by re7gog** [comment]
Also say goodbye to android 6, because of shizuku

**Comment by SirenGlitch** [comment]
I see this is currently still in the works, have you managed to get a working version built yet?

**Comment by ImranR98** [comment]
Added thanks to @re7gog: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.41-beta
