### ISSUE TITLE
Download update for all

### ISSUE THREAD

**Issue by AbdulrahmanAlamodi** [ImranR98/Obtainium#1175]
I always press download button to download all in once.

But in the update flow, I need to install the downloaded one before download the others.

Can you add an option to download all then install

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.39-beta

**Comment by ImranR98** [comment]
You'll still need to wait for all downloads to finish before install prompts start showing up - this is due to a limitation in the Flutter plugin we use to install APKs (trying to show multiple install prompts on top of each other does not work).
