### ISSUE TITLE
[Q] How do I add a specific app from a repo w/ multiple app

### ISSUE THREAD

**Issue by vavavr00m** [ImranR98/Obtainium#1183]
I'm new to obtainium and am trying to add [remote-desktop-clients](https://github.com/iiordanov/remote-desktop-clients) but I have no idea how to write REGEX. Here are the apps included in each release:

- CustomChronojumpVnc
- CustomHakkoHmiVnc
- freeaRDP
- freeaSPICE
- freebVNC

Can you please let me know if it's possible to add each app and how? If not, will repos like this be supported?

**Comment by ImranR98** [comment]
You can use the APK filter. For example, for freeaRDP, just put `freeaRDP` in that field. That would filter out all the other APKs except for `freeaRDP-v5.1.4_0-final.apk ` and `freeaRDP-v5.1.4_1-final.apk `. You'd still have to manually pick one of them. If you want to avoid that, you could use a more complicated regex like `freeaRDP-.+_1-final`.

More info on regex: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
