### ISSUE TITLE
Readme.md as app description (GitHub)

### ISSUE THREAD

**Issue by Jaysum57** [ImranR98/Obtainium#1185]
**Describe the feature**
For supported sources: (GitHub, etc.)
Instead of manually inputting app description. It will instead use the app's readme file. That way It's easier to view the things I need to know in each individual app without going to their page in a browser.

**Comment by ImranR98** [comment]
Not sure what you mean - Obtainium doesn't currently store app descriptions. The only place it shows app descriptions is in search results but those are not actually saved for later. The assumption is that a user might need to see descriptions when searching for apps but by the time you've installed an app you already know what it does.
