### ISSUE TITLE
Feature request: Ability to receive alerts for releases on non-Android projects

### ISSUE THREAD

**Issue by jeremiah-k** [ImranR98/Obtainium#119]
I really appreciate your work on this app. I've been looking for something like this for awhile.

There's several projects that I use this for already, one of them being the Android app for Meshtastic. It would be great to be able to watch and receive an alert (and possibly download the files) for the Meshtastic firmware too. I upgrade a few of my devices OTA via my phone.

I know there's other ways to receive alerts for new releases but it would be handy to have that functionality in this app too, especially with the option to download the files directly. Just putting the idea out there, if you're looking for suggestions.

**Comment by S7venLights** [comment]
I assume you don't want to use https://github.com/slapperwan/gh4a with the custom watch settings, since it doesn't download files directly?

**Comment by ImranR98** [comment]
Issue #44 already needs us to add a "track-only" mode for specific sources, so that can definitely be extended to all sources as an option.

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.0-beta

This doesn't let you download any files but will track updates and send update notifications.

**Comment by jeremiah-k** [comment]
Thank you for adding that. Very cool! However, I haven't yet been able to get it to add the main one I want to track.

https://github.com/meshtastic/firmware

I tried adding that while selecting "Track only" and it said "Couldn't find a suitable release."  I also enabled Include Pre-releases (which many of the builds are) and it's still unable to track it so far.

**Comment by ImranR98** [comment]
Whoops. Should work now: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.1-beta

**Comment by jeremiah-k** [comment]
Works great now. Thanks again!
