### ISSUE TITLE
Downgrad an installed app

### ISSUE THREAD

**Issue by skwde** [ImranR98/Obtainium#1191]
**Prerequisites**

**Describe the bug**

When trying to downgarde an app as mentioned in <https://github.com/ImranR98/Obtainium/issues/107> I get an error, like

Cannot install an older version.

**To Reproduce**

1. Open obtainium and edit the app you want to downgrade, e.g. DAVx5 and ensure that the latest version is installed, i.e. `v.4.3.12-ose`
2. Enter the following `Filter release Titles by Regular Expression`: `v4.3.11-ose` to go back to the previous version
3. `Continue` to set the option
4. Ensure that the older version is detected as an update and `Update`
5. See the error appear

**Please complete the following information:**
 - Device: Pixel7a
 - OS: GrapheneOS
 - Obtainium Version: v0.14.41-beta

**Comment by ImranR98** [comment]
Do you have the lsposed module as mentioned in that issue? Android does not usually allow downgrades.

**Comment by skwde** [comment]
Alright, well no. 

Sorry for bothering I should have read the Question description as well not only the title and your answer...
