### ISSUE TITLE
Two Values folders

### ISSUE THREAD

**Issue by RustoMCSpit** [ImranR98/Obtainium#1195]
https://github.com/ImranR98/Obtainium/tree/main/android/app/src/main/res

While I get why you separated values and values-night, I feel like in the long-run it would make sense to merge them because I think it would streamline adding functionality for custom user inputted color values. I am not sure about any of this so close if you feel so.

**Comment by ImranR98** [comment]
This is the Flutter default. Besides it seems to only apply to things like the splash screen and adaptive icon. Not sure what the point of merging them would be.
