### ISSUE TITLE
Issue unable to find a suitable release from Codeberg source

### ISSUE THREAD

**Issue by ngocanhtve** [ImranR98/Obtainium#1199]
Currently Obtainum cannot add app from this codeberg link https://codeberg.org/pabloscloud/Overload. Even when I add the link to the direct apk Obtainum still can't find apk.

**Comment by ImranR98** [comment]
All available releases are marked as pre-release so you need to enable to "include prereleases" toggle.

**Comment by ngocanhtve** [comment]
Got it. Thank you!
