### ISSUE TITLE
Cannot Add Adguard App from html/github

### ISSUE THREAD

**Issue by qiratdahaf** [ImranR98/Obtainium#1202]
**Bug Description**
cannot add adguard android app from their website nor github.

**To Reproduce**
1. Go to 

https://adguard.com/en/adguard-android/overview.html
or
https://github.com/AdguardTeam/AdguardForAndroid/releases

2. in first link app crashes.
3. in 2nd link app doesnt find suitable release.

other sources can be added but app isnt released to them early so i get updates via in app early rather than obtanium. 

if anyone can help please share settings for given links.

**Comment by ImranR98** [comment]
The first link won't work because the APK link isn't part of the HTML itself, it is loaded in with JavaScript later when you click the button. Obtainium doesn't support JS.

The second link doesn't work because the developer has not actually attached APKs to their releases, just the source code.
