### ISSUE TITLE
Please add Amazon App Store as a source, if possible

### ISSUE THREAD

**Issue by DwainZwerg** [ImranR98/Obtainium#1207]
**Prerequisites**
Please ensure your request is not part of an existing issue.
No, it isn't part of an existing issue.
**Describe the feature**
For new Sources, it's preferable (not required) if you suggest how the following details can be extracted from the Source in a reliable way (like an API or through web scraping):
This is the URL of the App Store: https://www.amazon.de/mobile-apps/b?node=1661648031
URL of an App: https://www.amazon.de/KiKA-Player-Videos-Filme-Serien-Kinder/dp/B092D9S8B6/ref=sr_1_3?rnid=1721572031
Note that the Web scraper cannot deal with JavaScript-enabled content. 
I think it's only work with Java-Script, so probably it could not work.

**Comment by ImranR98** [comment]
Yeah I can't see any way to do this without JS (or even without signing in with an Amazon account).
