### ISSUE TITLE
Can't upgrade Obtainium : "Null check operator used on a null value"

### ISSUE THREAD

**Issue by KaKi87** [ImranR98/Obtainium#1209]
**Prerequisites**

Yes

**Describe the bug**
The "Null check operator used on a null value" is thrown when trying to upgrade Obtainium.

**To Reproduce**
1. Click the upgrade button
2. See error

**Screenshots and Logs**
Screenshot :
![](https://media.discordapp.net/attachments/418482899034177557/1190317887169232967/Screenshot_2023-12-29-16-37-21.png)
Logs show the same message without any additional details.
As for `/Android/data/dev.imranr.obtainium/`, I see the upgrade is downloaded there under `cache`, and trying to install it manually throws Android's "There was a problem parsing the package" error.
Deleting it, restarting the app, and re-downloading the file doesn't fix the issue.

**Please complete the following information:**
 - Device: Samsung Galaxy Tab 8.4
 - OS: Android 6
 - Obtainium Version: 0.14.40

**Additional context**
None

---
Thanks

**Comment by ImranR98** [comment]
Could you share an export of your apps list

**Comment by KaKi87** [comment]
There : [obtainium-export-2023-12-29T19-13-09.623800.json](https://github.com/ImranR98/Obtainium/files/13795461/obtainium-export-2023-12-29T19-13-09.623800.json)
By the way, #1029 is still an issue as well.

**Comment by ImranR98** [comment]
Could you check the size of the APK in cache/? I want to confirm that it downloaded the right one.

**Comment by KaKi87** [comment]
![](https://media.discordapp.net/attachments/418482899034177557/1190364743383404635/Screenshot_2023-12-29-19-43-49.png)
![](https://media.discordapp.net/attachments/418482899034177557/1190364742892654622/Screenshot_2023-12-29-19-43-57.png)

**Comment by ImranR98** [comment]
Looks like you got `app-armeabi-v7a-release.apk`. I'm sure this is the issue (pretty much all recent devices would need `app-arm64-v8a-release.apk` but it's not clear why the right one was not auto-selected. Could you disable the "attempt to filter by device architecture" toggle in the app-specific settings? Then post a screenshot of the options it gives you.

**Comment by ImranR98** [comment]
Also is v14.40 the first version of Obtainium you've used?

**Comment by KaKi87** [comment]
> Looks like you got `app-armeabi-v7a-release.apk`. I'm sure this is the issue

Actually, I think that's the right one.

> (pretty much all recent devices would need `app-arm64-v8a-release.apk` but it's not clear why the right one was not auto-selected.

My device isn't recent.

> Could you disable the "attempt to filter by device architecture" toggle in the app-specific settings? Then post a screenshot of the options it gives you.

![](https://media.discordapp.net/attachments/418482899034177557/1190366930268327946/Screenshot_2023-12-29-19-52-49.png)

> is v14.40 the first version of Obtainium you've used?

No, for example, in #1029, I was using v0.14.31 at the time of the initial report.

**Comment by ImranR98** [comment]
Oh, I should've noticed you were on Android 6 earlier. Version 0.15 dropped support for Android 6 since it isn't supported by one of the new dependencies. I was hoping no one would be affected (apparently only ~3.5% of devices use Android 6 or older) but I guess not. Unless that dependency can be removed somehow, I don't think there's a solution.

**Comment by ImranR98** [comment]
Actually it's version v0.14.41. I've updated the release notes.

**Comment by ImranR98** [comment]
The new dependency is from https://github.com/ImranR98/Obtainium/pull/1184 so it is still possible to remove any changes from that PR and re-compile the app for your tablet.

**Comment by KaKi87** [comment]
That would defeat the app's purpose. :/
