### ISSUE TITLE
Be able to edit configurations post application. Especially useful when you've imported the config from someone else.

### ISSUE THREAD

**Issue by darrenhaken** [ImranR98/Obtainium#1213]
**Prerequisites**

**Describe the feature**
I would like to be able to edit configurations which I have imported. There has been a breaking change with some of the configs I'm using over the last 24 hours, I can only assume due to an update for Obtainium. I went to edit the config to debug and fix the issue but the only option on Edit was Additional Configuration with a text box.

Unless I'm missing something, being able to edit the configuration again would be very useful.

**Additional context**
I am trying to import a config I found online for emulation, see here:
https://gist.github.com/RJNY/e65f453ec707661ea13504beef7e86e2

**Comment by ImranR98** [comment]
You can already use a text editor ([Markor](https://github.com/gsantner/markor) is good) to edit the JSON files in `/Android/data/dev.imranr.obtainium/files/app_data`.

What errors are you seeing? There have been some changes but Obtainium should automatically resolve them.

**Comment by ImranR98** [comment]
Looking at the file you linked, I think the error should be fixed by the latest version v0.15.1 so you shouln't need to do it manually.

**Comment by darrenhaken** [comment]
Thanks, so just update to 0.15.1 to fix it?

**Comment by ImranR98** [comment]
Yes

**Comment by darrenhaken** [comment]
> Yes

Yep, working now. Thanks for getting back to me.
