### ISSUE TITLE
Marketplace of configurations for well known apps

### ISSUE THREAD

**Issue by darrenhaken** [ImranR98/Obtainium#1214]
**Describe the feature**
It would be really handy if there was some sort of marketplace of configurations for well-known applications.
I'm attempting to add configs for emulators and there isn't much community conversation around using Obtaininium.

I have found this:
https://gist.github.com/RJNY/e65f453ec707661ea13504beef7e86e2

However, there seems to be some errors with it now. This led me to think, it would be awesome if there was some sort of well known app configs/marketplace/some way of loading some apps easily.

Some of the configs for these apps can be fiddly such as the right Regex to get it right. 
In the spirit of don't repeat yourself (DRY), it feels super handy if there was a repository for these.

**Comment by ImranR98** [comment]
It's a good idea, especially now that you can stuff a whole config into a clickable link that opens directly in Obtainium (https://github.com/ImranR98/Obtainium/issues/368#issuecomment-1858777494). But I don't think I'd be interested in maintaining something like that myself.

**Comment by ImranR98** [comment]
Rather, i'm not intending to list the apps myself. I could put up a public site but the content would need to be contributed with PRs by others.

**Comment by darrenhaken** [comment]
> Rather, I'm not intending to list the apps myself. I could put up a public site but the content would need to be contributed with PRs by others.

I was thinking a website as you suggested or another GitHub repo under the project say App Marketplace (needs a better name) and people can contribute app configs. I guess it would give a PR workflow and VCS for all of it.

If you're up for a website or some sort of GitHub workflow that would be awesome. 

Any thoughts?

**Comment by darrenhaken** [comment]
> It's a good idea, especially now that you can stuff a whole config into a clickable link that opens directly in Obtainium (https://github.com/ImranR98/Obtainium/issues/368#issuecomment-1858777494). But I don't think I'd be interested in maintaining something like that myself.

The protocol idea looks cool, great idea.

**Comment by ImranR98** [comment]
Yes I can put up a simple page and a public repo for PRs.

**Comment by darrenhaken** [comment]
That would be awesome. Let me know when it's setup and I'll take a look. 

Sounds like it should be setup to work with the new protocol

**Comment by ImranR98** [comment]
Site: https://apps.obtainium.imranr.dev/
Repo: https://github.com/ImranR98/apps.obtainium.imranr.dev

Currently very barebones and has no content. Aside from content PRs it would be nice to also have search, a better UI, etc. but this is not likely to be a priority for me.

**Comment by ImranR98** [comment]
I've added a few more apps to the site (mainly from my own export) but haven't categorized them or added descriptions and icons.

**Comment by pabloscloud** [comment]
Looks good wondering if a dialog could be added to obtainium so imports are not added directly but rather need to be approved in the app.

There's also no information that the app has been successfully added to obtainium. Just ideas here

**Comment by ImranR98** [comment]
@pabloscloud created #1232

**Comment by pabloscloud** [comment]
Wow, you're quick!

**Comment by NicholasFlamy** [comment]
@ImranR98 I would like to suggest adding the app source to the listing on the website. (Since some apps can be from both something like Github and F-droid or [insert alternative appstore]) so for example, Syncthing should say "Source: Github"

**Comment by ArnoldSmith86** [comment]
Can somebody add a working source for Discord? 😀

**Comment by NicholasFlamy** [comment]
> Can somebody add a working source for Discord? 😀

This is probably not the place for asking. You should make an issue on the repo: https://github.com/ImranR98/apps.obtainium.imranr.dev

But, for stock regular (unmodified) Discord, you should use the Google Play Store or Aurora Store. Otherwise you have to rely on some not-so-safe sites or pay for apkmirror's subscription to use their app to update it.

**Comment by DwainZwerg** [comment]
> But, for stock regular (unmodified) Discord, you should use the Google Play Store or Aurora Store. Otherwise you have to rely on some not-so-safe sites or pay for apkmirror's subscription to use their app to update it.

I would count apkmirror.com among the less secure stores. However, the ones currently available in Obtainium are not as insecure as some others. You don't have to buy the apkmirror app either, because you also receive notifications from Obtainium for apkmirror and can then download and install the update by clicking on the link in the app overview.

**Comment by NicholasFlamy** [comment]
> > But, for stock regular (unmodified) Discord, you should use the Google Play Store or Aurora Store. Otherwise you have to rely on some not-so-safe sites or pay for apkmirror's subscription to use their app to update it.
> 
> I would count apkmirror.com among the less secure stores. However, the ones currently available in Obtainium are not as insecure as some others. You don't have to buy the apkmirror app either, because you also receive notifications from Obtainium for apkmirror and can then download and install the update by clicking on the link in the app overview.

2 things:
1. Apkmirror is probably the safest unofficial apk site that exists based on what I've seen.
2. I know how Obtainium works. I meant that if you want auto-updating Discord, you need to use apkmirror through their app or you use another site. It's not automatic if you use apkmirror. Also, personally I've just been using Vendetta with it locked to Discord version 206016 in developer options of Vendetta Manager. If you don't care for auto updating, then sure, use apkmirror, if you have a specific source, I'll make you a config and submit it to the repo.

**Comment by ArnoldSmith86** [comment]
I don't have the Play Store and Aurora used to break for me very often. Looks like it's currently working. But I would prefer to have only two app sources instead of three (F-Droid, Obtanium, Aurora).

**Comment by DwainZwerg** [comment]
> But I would prefer to have only two app sources instead of three (F-Droid, Obtanium, Aurora).

Just using two would work. You can also enter any F-Droid app in Obtanium …

**Comment by ImranR98** [comment]
No need to leave this open.
