### ISSUE TITLE
Latest version < Installed version for some (misconfigured) app releases

### ISSUE THREAD

**Issue by lostoliv** [ImranR98/Obtainium#1216]
**Describe the bug**

When installing/updating the latest version of Librera, it will keep seeing the app as "updatable" despite updating it to the latest version.

**To Reproduce**

Add: https://github.com/foobnix/LibreraReader

Install it. It will report the Latest version as 8.9.147 and the Installed version as 8.9.148 (as of 12/29/2023).
Notice that the installed version is greater than the latest version. Because of this will keep the app as "updatable", despite updating it over and over.

It's certainly coming from the latest release:
https://github.com/foobnix/LibreraReader/releases/tag/8.9.147

It's tagged as 8.9.147, however the installed apk (Librera.Pro-8.9.148-arm64.apk) which is part of the 8.9.147 release has version 8.9.148 for some reason.

Not sure why it was released like this - it's not per se Obtainum's fault as it sees the latest version in the repo as different from the installed one and - as such - asks for the app to be updated which is reasonable.

Tho it would be great if it could handle this edge case when app releases are misconfigured and somehow realize that the latest installed apk is part of the latest release, even if the versions don't match. I acknowledge that it might not be trivial to do this reliably as comparing github release versions as strings might not be the most reliable way to find which version is the latest based on the way versions are encoded (especially when one release has multiple versions for different apks) - and apps could be updated outside Obtainium.

A minor annoyance as I can ignore the update tho I wanted to report this. Thanks!

**Please complete the following information:**
 - Device: Pixel 6
 - OS: GrapheneOS
 - Obtainium Version: 0.15.1-beta

**Comment by ImranR98** [comment]
You can get around this by turning off version detection in the additional options for Librera. This will tell Obtainium to ignore the on-device version and only rely on its internal record. More info: https://github.com/ImranR98/Obtainium/wiki#version-detection

**Comment by ImranR98** [comment]
After turning it off you can manually mark the app as updated and it won't revert back.
