### ISSUE TITLE
Intermediate links disappear after restarting the app

### ISSUE THREAD

**Issue by St3ph32** [ImranR98/Obtainium#1219]
**Prerequisites**
Add an app in Obtanium with HTML source that is using at least one intermediate link.

**Describe the bug**
Right after the app is added in Obtanium, it will update and work normally, but after restarting Obtanium all the intermediate links of the app will get deleted and it won't be able to scrape the source correctly.

**To Reproduce**
1. Add an HTML source app.
2. Use at least one intermediate link.
3. After the app is added, restart Obtanium.
4. The intermediate links are now deleted.

**Screenshots and Logs**
Shouldn't be relevant.

**Please complete the following information:**
 - Device: Pixel 7
 - OS: GrapheneOS
 - Obtainium Version: 0.15.1-beta

**Comment by ImranR98** [comment]
Should be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.15.2-beta
