### ISSUE TITLE
Regular Expression: Could not find a suitable release

### ISSUE THREAD

**Issue by lnusilbu** [ImranR98/Obtainium#122]
I am trying to get regular expressions filtering to work. For instance, I have the MPV app (https://github.com/mpv-android/mpv-android) and each time I update it I want to choose the "app-default-universal-release.apk"

No matter what I enter in the regular expression Obtabium gives me an error: "Could not find a suitable release." Is there an easy example of what I need to enter in this field to get the filtering to work?

**Comment by lnusilbu** [comment]
Also, as a feature suggestion, maybe there could be a link within this app dialogue to basic documentation or quick examples of regular expressions for the uninitiated.

**Comment by ImranR98** [comment]
Regular expression filtering is for release titles, not APK file names. A link to more info on regex will be added in the next release.

**Comment by lnusilbu** [comment]
Ah, I misunderstood its purpose. Thanks for the explanation.
