### ISSUE TITLE
Accept www subdomain of f-droid source link

### ISSUE THREAD

**Issue by foxjaw** [ImranR98/Obtainium#1222]
Currently Obtainium can't source f-droid links with www subdomain  
https://www.f-droid.org/packages/com.beemdevelopment.aegis/  
is not accessible, but  
https://f-droid.org/packages/com.beemdevelopment.aegis/  
is.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.3-beta
