### ISSUE TITLE
GitHub's "Fallback" Option Should Work With the APK Filter

### ISSUE THREAD

**Issue by ImranR98** [ImranR98/Obtainium#1236]
Use case: Getting MicroG for ReVanced from https://github.com/revancedapps/revanced.net/releases/ (it only appears on some releases).

**Comment by az-my** [comment]
so, for example lightroom.apk
it only appear in this release https://github.com/revancedapps/revanced.net/releases/tag/2023-49
meanwhile the latest release https://github.com/revancedapps/revanced.net/releases/tag/2023-53
and lightroom does not appear in the latest release.

**Comment by ulil-azmy** [comment]
so, it means we could also get apk that only availabe on older release, with just using apk filter regex? and if somehow theres new release where new version available, it will updateable?

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.4-beta

**Comment by ImranR98** [comment]
> so, it means we could also get apk that only availabe on older release, with just using apk filter regex? and if somehow theres new release where new version available, it will updateable?

Yes
