### ISSUE TITLE
Version Detection RegEx override for Github (Problem)

### ISSUE THREAD

**Issue by NicholasFlamy** [ImranR98/Obtainium#1237]
**Prerequisites**
Done
Done

**Describe the feature**
I would like the regular Version Extraction RegEx available as an override for Github and the others because sometimes all that's needed is the removal of one word. 

For new Sources, it's preferable (not required) if you suggest how the following details can be extracted from the Source in a reliable way (like an API or through web scraping):
- The App version (or any release-specific identifier - a "pseudo-version") for the latest release
- One or more APK URL(s) for the latest release
- Above details for previous releases (optional)

Note that the Web scraper cannot deal with JavaScript-enabled content. -->

**Describe alternatives you've considered (if applicable)**

**Additional context**

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.4-beta

**Comment by ImranR98** [comment]
Note: Version extraction when applied to non-HTML sources will apply to the original version string provided by the source, not the APK link. So for GitHub this would be the 'tag' of the specified release, not the `github.com/<author>/<repo>/release/<tag>/assets/<filename>.apk` link.

**Comment by NicholasFlamy** [comment]
> Note: Version extraction when applied to non-HTML sources will apply to the original version string provided by the source, not the APK link. So for GitHub this would be the 'tag' of the specified release, not the `github.com/<author>/<repo>/release/<tag>/assets/<filename>.apk` link.

I'll add this to the Wiki.

**Comment by NicholasFlamy** [comment]
I'm not certain that I'm able to edit the Wiki.

**Comment by NicholasFlamy** [comment]
> I'm not certain that I'm able to edit the Wiki.

@ImranR98

**Comment by ImranR98** [comment]
Yeah unfortunately it seems like Wiki repos don't support PRs. You can use this method: https://stackoverflow.com/a/11481887
