### ISSUE TITLE
NEW SOURCE OpenFoodFacts

### ISSUE THREAD

**Issue by sonalder-darlene** [ImranR98/Obtainium#124]
The project : https://world.openfoodfacts.org/
The APK file : https://world.openfoodfacts.org/files/off.apk 
The GitHub don't have realease APKs : https://github.com/openfoodfacts/openfoodfacts-server/releases

**Comment by ImranR98** [comment]
Is the app version listed anywhere? Can't seem to find it on their website. Would be required.
