### ISSUE TITLE
Yuzu shows "No version detection"

### ISSUE THREAD

**Issue by NicholasFlamy** [ImranR98/Obtainium#1242]
**Prerequisites**
Done
Done

**Describe the bug**
So "Standard version detection" is greyed out and the version page shows "No version detection" and the notifications show that it "may have been updated" but the estimated Android version is identical to the Yuzu one. Resetting the install status doesn't change anything and shows that it doesn't need an update. Something is off. Since the notifications make it sound unconfident in its updating it concerns me so I check. 

**To Reproduce**
Search yuzu-android and add it from GitHub. When installed it greys out "Standard version detection" and shows the installed version as estimated but it perfectly matches the GitHub version.

**Screenshots and Logs**
![Screenshot_20240103_210259](https://github.com/ImranR98/Obtainium/assets/30300649/0680f819-6513-4c26-a7bd-23c3148bd2eb)
![Screenshot_20240103_210246](https://github.com/ImranR98/Obtainium/assets/30300649/ff0190a0-3090-474f-bbab-95efe79c6e12)
![Screenshot_20240103_210146](https://github.com/ImranR98/Obtainium/assets/30300649/5e494cdd-f033-46e5-a97b-6f3bbb27debe)

**Please complete the following information:**
 - Device: Galaxy S21 (US with Snapdragon 888)
 - OS: OneUI 5.1 Android 13
 - Obtainium Version: 0.15.4-beta

**Additional context**

**Comment by NicholasFlamy** [comment]
Android-reported version:
![Screenshot_20240103_212848_Settings](https://github.com/ImranR98/Obtainium/assets/30300649/566ecfe1-a62f-4d27-b2d8-ba0a568f9534)

**Comment by NicholasFlamy** [comment]
Same problem with another Github app. This one require me to edit the version RegEx to make it work byt now it works perfectly in the same bugged way that Yuzu does. I blurred the name of the app on purpose.
![Screenshot_20240103_214019](https://github.com/ImranR98/Obtainium/assets/30300649/e07e30ba-0d59-48b0-92a8-ff21358024bb)
![Screenshot_20240103_213956](https://github.com/ImranR98/Obtainium/assets/30300649/c28865c7-2307-47af-900b-16767f8655a2)

**Comment by ImranR98** [comment]
> So "Standard version detection" is greyed out and the version page shows "No version detection"

This is normal. `android-181` is not a "standard" version format. Just because the real and source-provided versions both follow the same format does not mean Obtainium will be able to detect that. See: https://github.com/ImranR98/Obtainium/wiki#version-detection

> Notifications show that it "may have been updated".

This is true for all apps regardless of version detection. See: https://github.com/ImranR98/Obtainium/wiki#background-updates

> Resetting the install status doesn't change anything and shows that it doesn't need an update.

That's good - it shows that the formats for both versions match and that the app is fully up to date.

**Comment by NicholasFlamy** [comment]
> `android-181` is not a "standard" version format.

Is it worth suggesting a version Match Group for the Android provided version so that the user can make it standardized?

**Comment by ImranR98** [comment]
I don't think so. Version detection is one of those things that turned out to be unnecessarily complicated so I don't think it's a good idea to mess with it to support a small number of edge cases.

**Comment by ImranR98** [comment]
Also you need to up your censorship game boss, that version/tag is very specific and google-able 😂
