### ISSUE TITLE
Remove Steam from sources

### ISSUE THREAD

**Issue by Ryttch** [ImranR98/Obtainium#1244]
To date https://store.steampowered.com/mobile is a broken mess of a source:

1. The version of Steam Mobile is outdated
2. Steam Link doesn't even have a version
3. And Steam Chat:
The version listed is 1.0.8 https://cdn.cloudflare.steamstatic.com/apps/steam-chat/steam-chat-app-1.0.8.apk
After downloading it installs version 0.9 and Obtainium keeps telling me to update to 1.0.8
Even manual download of the APK installs the wrong version so it's not Obtainium's fault

There are more reliable sources where those apps can be downloaded (Aptoide for example)

If not removed, at least state in Supported Sources:
'Steam (not recommended)'

**Comment by ImranR98** [comment]
You're right, if there's a mismatch the source should not be used. Even if they fix it, the HTML source is now able to handle this site so it doesn't need to be it's own thing. The next update will remove Steam and automatically convert existing Steam entries to HTML ones.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.5-beta
