### ISSUE TITLE
NEW SOURCE Samourai Wallet

### ISSUE THREAD

**Issue by sonalder-darlene** [ImranR98/Obtainium#125]
Adding the samourai Wallet

https://samouraiwallet.com/
https://samouraiwallet.com/download

**Comment by ImranR98** [comment]
With the resolution of issue #72, this is no longer needed. You can use Samourai's F-Droid repo instead.
Add https://repo.samourai.io/fdroid/repo as an App Source, and put "Wallet" as the App name (the full name is "Samourai Wallet" but Obtainium will pick the closest match).
