### ISSUE TITLE
Recent versions are unable to find APKPure address

### ISSUE THREAD

**Issue by SirenGlitch** [ImranR98/Obtainium#1250]
**Prerequisites**

**Describe the bug**
For the last 2 (maybe 3) versions, APKPure hasn't been able to be found

**To Reproduce**
1. Go to 'Add App'
2. Enter a random APKPure app URL
3.Tap 'Add'

**Screenshots and Logs**
`ClientException with SocketException: Failed host lookup: 'apkpure.com' (OS Error: No address associated with hostname, errno = 7), uri=https://apkpure.com/p/com.Beauchamp.Messenger.external/download`

**Please complete the following information:**
 - Device: OnePlus 6T
 - OS: OxygenOS 11
 - Obtainium Version: v0.15.5-beta

**Additional context**

**Comment by Senliast** [comment]
APKpure itself is not available - if you try to open the website through normal browser - it will not open. Already for a few days. Not a fault of Obtainium. But would be interesting to know, what happened to APKpure and if it will be ever available again.

**Comment by SirenGlitch** [comment]
> APKpure itself is not available - if you try to open the website through normal browser - it will not open. Already for a few days. Not a fault of Obtainium. But would be interesting to know, what happened to APKpure and if it will be ever available again.

Ah okay, good to know

**Comment by DireMunchkin** [comment]
@SirenGlitch You should reopen the issue, as there's an Obtainium patch needed to fix the APKPure source to work with their new domain.

**Comment by Senliast** [comment]
Ah okay, i didn't know about it.

**Comment by SirenGlitch** [comment]
> @SirenGlitch You should reopen the issue, as there's an Obtainium patch needed to fix the APKPure source to work with their new domain.

Thanks for letting me know, just reopened

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.8-beta

**Comment by Senliast** [comment]
@ImranR98 I tried the new version now, but unfortunately, still cannot update apps from APKPure, an error appears "unable to lookup d.apkpure.net". As an example, i was using URL https://apkpure.net/de/netflix/com.netflix.mediaclient .

**Comment by St3ph32** [comment]
> @ImranR98 I tried the new version now, but unfortunately, still cannot update apps from APKPure, an error appears "unable to lookup d.apkpure.net". As an example, i was using URL https://apkpure.net/de/netflix/com.netflix.mediaclient .

That's probably because Obtanium uses `d.apkpure.net` to download the APK instead of `d.cdnpure.com`.
Anyways, [APKPure it's working to fix the `.com` domain, the `.net` one should just be used as a backup](https://apkpure.net/news/important-notice-regarding-apkpure-com-site).

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.9-beta
