### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by rafaelazvdo** [ImranR98/Obtainium#1256]
Updating from version 0.15.4 to version 0.15.6 and when starting the application this screenshot screen is displayed and it doesn't go away.![Screenshot_20240107_213540.jpg](https://github.com/ImranR98/Obtainium/assets/122113441/d20a86ed-d787-4e6b-b384-71f903e10eab)

**Comment by rdayltx** [comment]
Same here, probably wrong "pt" translation.
At line 223 "AQUI" is non expected

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.7-beta
