### ISSUE TITLE
Can't Add RetroArch Stable from buildbot URL using intermediate link

### ISSUE THREAD

**Issue by carlos-algms** [ImranR98/Obtainium#1259]
**Describe the bug**

I can't make it download the latest `Stable` version from RetroArch's BuildBot page using regex to match the version folder

The final URL would be:
https://buildbot.libretro.com/stable/1.16.0/android/RetroArch_aarch64.apk
 

**To Reproduce**

1. Tap on `Add App`
2. Set the `App Source URL` to: `https://buildbot.libretro.com/stable` (I've tried with trailing `/` here as well)
3. Add an intermediate link with the regex: `([0-9]+\.)*[0-9]+/$`(as suggested [here](https://github.com/ImranR98/Obtainium/issues/820#issuecomment-1696604543), I also tried with `[0-9]+\.[0-9]+\.[0-9]+`
4. Add a second intermediate link with: `android/$`
5. For the `custom apk link filter`, I've tried:
   - Leave it empty
   - or with `RetroArch_aarch64.apk`
   - or `RetroArch_aarch64.apk$`
   - or `.*\.apk$`
6. Click on `Add` on the top

It fails to add the App. 

However, it works if I use the FULL URL without changing anything else, but it would be locked to the current version only. 

**Screenshots and Logs**

The logs only say:
```
error: Could not find a suitable release
```
It would be great if it logged the full ULR it tried to fetch the APK here. 

| top | second |
|--------|--------|
| ![Screenshot_20240108-110612](https://github.com/ImranR98/Obtainium/assets/4634613/10babe32-1f1e-4832-8d44-ee66d4762a3d) | ![Screenshot_20240108-110626](https://github.com/ImranR98/Obtainium/assets/4634613/d62e4e6d-d2d7-4ea6-9af1-1453d27a7a1e) | 

**Please complete the following information:**
 - Device: `Moto Edge 40 pro`
 - OS: `Android 13`
 - Obtainium Version: `v0.15.7-beta`

**Comment by carlos-algms** [comment]
Even without Regex and adding hardcoded intermediary links, it doesn't work:

Everything else is default settings.
I've tried without `/$` at the end as well. 

![Screenshot_20240108-112836](https://github.com/ImranR98/Obtainium/assets/4634613/ee920e2d-8ce9-441e-ba2a-80bdf3c8de88)

**Comment by ImranR98** [comment]
Should work now: https://github.com/ImranR98/Obtainium/releases/tag/v0.15.8-beta
