### ISSUE TITLE
Add Bitbucket source

### ISSUE THREAD

**Issue by IlIllIl** [ImranR98/Obtainium#1260]
**Prerequisites**

**Describe the feature**

e.g. 
https://bitbucket.org/M66B/fairemail-test/downloads/?tab=downloads

**Describe alternatives you've considered (if applicable)**

**Additional context**

**Comment by ImranR98** [comment]
This already works with the HTML source so there is no need to add it separately.

**Comment by IlIllIl** [comment]
Hi, how to add app from bitbucket using HTML source? Could you help me or add a wiki for beginners?
