### ISSUE TITLE
Can't add Cync from ApkMirror source

### ISSUE THREAD

**Issue by EKolyshkin** [ImranR98/Obtainium#1264]
**Describe the bug**

Cannot add this App Source URL: https://www.apkmirror.com/apk/ge-lighting-a-savant-company/cync-the-new-name-of-c-by-ge.

Get **Unexpected Error. RangeError (end): Invalid value: Not in inclusive range 31..87: 23**. Other APKMirror URLs work as expected.

**To Reproduce**
1. Go to 'Add App'.
2. Tap on input field titled 'App Source URL'.
3. Paste the [aforementioned link](https://www.apkmirror.com/apk/ge-lighting-a-savant-company/cync-the-new-name-of-c-by-ge).
4. Tap 'Add'.
5. Get error listed above.

**Screenshots and Logs**

![Screenshot_20240108-144127](https://github.com/ImranR98/Obtainium/assets/65327703/7fd0b1f0-29bb-4d7c-88c0-dfbc2ab2df42)

**Please complete the following information:**
 - Device: Pixel 6a
 - OS: GrapheneOS
 - Obtainium Version: 0.15.7-beta

**Additional context**

Temporarily tracking Google Play apps via APKMirror while APKPure is down. Other apps did not have problems being tracked from multiple sources, so I don't think this is the problem. Furthermore, the error seems to be an input sanitization issue, but I don't see any strange characters.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.9-beta
