### ISSUE TITLE
Vendetta Manager has a stupid Versioning system that screws up

### ISSUE THREAD

**Issue by NicholasFlamy** [ImranR98/Obtainium#1269]
**Prerequisites**
Done
Done

**Describe the bug**
Basically, I need a way to delete zeros from the last part. Also, it's only a problem every so many versions. 

**To Reproduce**
Install Vendetta Manager off Github

**Screenshots and Logs**
![Screenshot_20240109_081320_Chrome](https://github.com/ImranR98/Obtainium/assets/30300649/1c57f0f5-a352-4b4e-ac7f-d0acfc33535a)
![Screenshot_20240109_081204_Chrome](https://github.com/ImranR98/Obtainium/assets/30300649/64e87309-f07e-466e-a21b-5f9e5bf899d4)
![Screenshot_20240109_081051_Chrome](https://github.com/ImranR98/Obtainium/assets/30300649/995007cf-58a4-40f5-b3e9-8523b56be6fc)
![Screenshot_20240109_080926](https://github.com/ImranR98/Obtainium/assets/30300649/78a5bc25-271f-4b1e-a8d8-27ec9a48558b)
![Screenshot_20240109_080053_Settings](https://github.com/ImranR98/Obtainium/assets/30300649/f516f8cc-ee7a-4dfc-98f0-8df1a84f25c4)
![Screenshot_20240109_080032](https://github.com/ImranR98/Obtainium/assets/30300649/24562d22-69d0-4fbd-a133-0a64c0df6aa9)
![Screenshot_20240109_080008_Chrome](https://github.com/ImranR98/Obtainium/assets/30300649/35f6e54d-f515-46a6-ad8d-a4894d8bcc58)

**Please complete the following information:**
 - Device: Galaxy S21
 - OS: OneUI 5.1 Android 13
 - Obtainium Version: 0.15.8-beta

**Additional context**
The solution is more RegEx and stuff or allowing Github Version extraction on the release name/title instead of the tag.

**Comment by NicholasFlamy** [comment]
It's not that big of a deal. But I feel like having a toggle to extract the version from the release title would be useful for other apps as well.

**Comment by wingio** [comment]
vendetta manager uses the version code for the release tag, rather than the name. an option for that would probably also be welcome

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.9-beta

Versioncodes can now be used as the OS-detected "version".
I haven't added "release title as version" feature as those aren't unique and the added complexity probably isn't worth it for an optional feature like version detection.
