### ISSUE TITLE
Could not get ID from APK [App]

### ISSUE THREAD

**Issue by NicholasFlamy** [ImranR98/Obtainium#1272]
**Prerequisites**
Done
Done

**Describe the bug**
Some apps error and say "Could not get ID from APK [App]"

**To Reproduce**
Add certain apkvision apps. If everything else is right, it downloads the apk but can't find the package id. 

**Screenshots and Logs**
![Screenshot_20240110_075536](https://github.com/ImranR98/Obtainium/assets/30300649/0ec371fc-4534-490c-8519-0a75c7d3bd91)
![Screenshot_20240110_075555](https://github.com/ImranR98/Obtainium/assets/30300649/81b843f4-7477-4fe9-96bc-d8a3e13939c9)

**Please complete the following information:**
 - Device: Galaxy S21
 - OS: OneUI 5.1 Android 13
 - Obtainium Version: 0.15.8-beta

**Additional context**

**Comment by NicholasFlamy** [comment]
Another app had the issue too. I found this had the issue as well so I used it as an example.

**Comment by NicholasFlamy** [comment]
![Screenshot_20240110_075801](https://github.com/ImranR98/Obtainium/assets/30300649/8492d9cc-4941-4e2a-8946-b6d45b4bd15c)

**Comment by ImranR98** [comment]
The APK is most likely incompatible with your device. Try installing it manually to confirm.

**Comment by NicholasFlamy** [comment]
> The APK is most likely incompatible with your device. Try installing it manually to confirm.

Both apps that have this issue install just fine.

**Comment by ImranR98** [comment]
Should work now: https://github.com/ImranR98/Obtainium/releases/tag/v0.15.9-beta

**Comment by NicholasFlamy** [comment]
> Should work now: https://github.com/ImranR98/Obtainium/releases/tag/v0.15.9-beta

Still doesn't.

**Comment by NicholasFlamy** [comment]
The problem occurs after adding it when it downloads the apk and also if I hit install.

**Comment by ImranR98** [comment]
Right, sorry I didn't actually explain what the problem was. The APK download link doesn't actually return an APK unless you include a `Referer` header. You can test this with `curl`:
- `curl https://files.apkvision.org/ladb-local-adb-shell/ladb_v2.3.1.apk` - doesn't work
- `curl https://files.apkvision.org/ladb-local-adb-shell/ladb_v2.3.1.apk -H 'Referer: apkvision.org'` - works

The new update allows you to define custom headers for the HTML source. Add `Referer: apkvision.org` and it should work.

**Comment by NicholasFlamy** [comment]
Ohhhh, okay, I understand. So how do it separate the User Agent part of the header from the Referer part? It seems like normally they would be on separate line.

**Comment by ImranR98** [comment]
Use the "+ Request Header"  button to add more.

**Comment by NicholasFlamy** [comment]
> Use the "+ Request Header" button to add more.

Lol I'm blind.

**Comment by NicholasFlamy** [comment]
Oh, there's a bug. Setting the second request header and hitting save updates the first one to the second one so it becomes duplicated.

**Comment by NicholasFlamy** [comment]
![Screenshot_20240112_124642](https://github.com/ImranR98/Obtainium/assets/30300649/009e6a1f-2ce4-4d0d-9d43-579e39d777f0)
![Screenshot_20240112_124653](https://github.com/ImranR98/Obtainium/assets/30300649/3c0f52bd-3ec4-4375-9249-15d8bc007709)
Then when I delete the second one the first one returns to normal.

**Comment by NicholasFlamy** [comment]
@ImranR98 if I add a third one it makes all of them the value of the second one and if I delete the third they stay the same but when I delete the second one the first one returns to its value.

**Comment by ImranR98** [comment]
Yeah that form input is really buggy and I haven't been able to figure out why. For now you should just delete the existing headers and enter them again when this happens.

**Comment by ImranR98** [comment]
One thing to note is that when you hit save, your new values are actually saved. It's just that re-opening the form shows incorrect values in the UI. So the correct headers you entered will still be sent.

**Comment by NicholasFlamy** [comment]
Okay, so I did a test to see how it works, I copied the download link and pasted it onto an incognito tab and ot redirect to the home page.

**Comment by NicholasFlamy** [comment]
So I need to figure out what header data works.

**Comment by NicholasFlamy** [comment]
Oh, also, how did you get the User-Agent header for Obtainium? Is it preset or is it pulled from the device? Just curious, since the default shows a few versions out of date Chrome compared to my current version.

P.S. I know it doesn't matter if it's a few versions out of date on the header but I just wanna know for the sake of knowing.

**Comment by NicholasFlamy** [comment]
Well, I got one of the 2 apkvision apps working.

**Comment by NicholasFlamy** [comment]
Oh, reopening Obtainium worked.

**Comment by NicholasFlamy** [comment]
![Screenshot_20240112_155943](https://github.com/ImranR98/Obtainium/assets/30300649/3516c60d-20e1-4b39-8763-6cd26f4db114)
I got an error seen at the bottom and second from top in the screenshot which popped up after it downloaded the apk or something but right after when I hit update (or install depending on whether or not it was already installed) it works fine. Not sure what the error is about but they both work.

**Comment by ImranR98** [comment]
Clear your cache

**Comment by nafarinha** [comment]
> The same problem with apps from GitLab

@b2sql , in my case, what I did to be able to add a direct apk link from gitlab.com (using GrapheneOS repo to download the Vanadium apk files):
- on a browser, click the apk link to open the download page (e.g. https://gitlab.com/grapheneos/platform_external_vanadium/-/blob/15/prebuilt/arm64/TrichromeWebView.apk) 
- You'll see the big download link; copy the URL (e.g. https://gitlab.com/grapheneos/platform_external_vanadium/-/raw/15/prebuilt/arm64/TrichromeWebView.apk)
- On Obtainium, paste the copied 'raw' URL in App Source URL, change Override Source to Direct APK Link and click Add to add the new app.
(Tested on 1.1.45)
