### ISSUE TITLE
Identify PWA application available on github pages in the found repository

### ISSUE THREAD

**Issue by antonioconselheiro** [ImranR98/Obtainium#1275]
First of all, thank you very much for Obtainium

**Describe of the feature**
Identify PWA application available on github pages root in the found repository.
This should allow you to find your favorite PWAs and add them to your Obtainium installable list and install it.

Example of PWA app in github pages:
- [Repository](https://github.com/antonioconselheiro/private-qrcode)
- [App](https://antonioconselheiro.github.io/private-qrcode/#/home)

**Comment by ImranR98** [comment]
This is out of scope for Obtainium as it's not an Android app (as a PWA you are not in control of updates anyways - any updates will be sent to you the next time you use the app).

However, you can still add the repo as a track-only app in Obtainium if you want to be notified when the developer creates a new tag (which they may or may not do when the PWA is updated).

**Comment by antonioconselheiro** [comment]
Understood, thanks for the reply
