### ISSUE TITLE
Mullvad Version not Found

### ISSUE THREAD

**Issue by ImranR98** [ImranR98/Obtainium#1276]
The Mullvad site was changed and it no longer seems to specify the version.

The source may have to be removed if a solution is not found (note that they also release on GitHub - maybe an automatic switch can be done like with Steam).

**Comment by ImranR98** [comment]
Decided not to automatically switch existing Mullvad apps to GitHub because, unlike the Steam case (#1244), this is a completely different source so users should not be switched over unawares.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.9-beta

**Comment by heinrichat** [comment]
How do I download the 'latest' apk with version detection directly straight from their homepage?

**Comment by ImranR98** [comment]
You can no longer get the real version string from their site because they don't provide it. You can still add it though, a hash of the APK's first 1kb is used as a "pseudo-version".

**Comment by heinrichat** [comment]
How do I add it? Where do I tell it to check for the first 1kb pseudo version? I don't see the setting.

**Comment by ImranR98** [comment]
It's automatic. Just add https://mullvad.net/en/download/vpn/android with `latest$` as the link filter.
