### ISSUE TITLE
Universal Search Bar on Add App Page

### ISSUE THREAD

**Issue by Baker0o7** [ImranR98/Obtainium#128]
![Screenshot_20221118-190336_Obtainium_1_1.png](https://user-images.githubusercontent.com/113295927/204054061-5dcb7011-8be2-4105-a485-31ba0c084e3c.png) if it can be possible to put search github down there separated tab plus adding trending android repo it will be nice thank you always for your hardworking sir appreciated

**Comment by ImranR98** [comment]
I don't think adding a search tab for every source makes sense (currently only GitHub supports search, but other sources might too later). Instead there could be a single search box in the add app page that searches all search-supported sources with one query.

Regarding the trending apps list, that was explored in issue #68 but there doesn't seem any reliable/trustworthy source of trending Android apps that we can tap into (hardcoding a list is a bad idea).

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.0-beta
