### ISSUE TITLE
Detect App version where there is no version in Release

### ISSUE THREAD

**Issue by ulil-azmy** [ImranR98/Obtainium#1282]
https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root/releases/tag/all

in this release, there is no version code of the app file name neither in release note / title. 
how to detect the version and is it still upgradeable?

for example, i wanna add tiktok.apk

**Comment by ImranR98** [comment]
Version detection is optional - any release-specific identifier will do. In the case of this repo, the repo tag cannot be used since it is fixed (`all`). So you could  use the "release date" version detection instead.

See the Wiki for more info.
