### ISSUE TITLE
Allow rename of app name

### ISSUE THREAD

**Issue by cyberboh** [ImranR98/Obtainium#1283]
**Prerequisites**

**Describe the feature**
Current version of obtainium unable to rename the app name, for example an app from F-Droid repo name is from it's package name, e.g LibreTube https://f-droid.org/en/packages/com.github.libretube , it will be named on Obtainium as `com.github.libretube`.
It's hard to read a full package name on smartphone, but (might be) not if you use Obtainium on tablet which has larger display.
Imagine, if it has a long package name like this : https://f-droid.org/en/packages/com.vincentengelsoftware.vesandroidimagecompare

For screenshoots
![Screenshot_20240113_204308](https://github.com/ImranR98/Obtainium/assets/99109969/109cd837-a7d8-43e9-9e4d-4a977d98b2ec)
![Screenshot_20240113_204326](https://github.com/ImranR98/Obtainium/assets/99109969/e9d2d362-932e-40a4-a837-37b623cce96b)
![Screenshot_20240113_204344](https://github.com/ImranR98/Obtainium/assets/99109969/1f8c2d10-5639-4823-b7dd-946642bee568)

**Comment by ImranR98** [comment]
There is already an 'App Name' field you can use.

Note that the App ID as name is only temporary as it's the best we could do with scraping from the source. When you actually install the app, the name will be updated with the actual name the app has in the OS.
