### ISSUE TITLE
Add a download badge icon

### ISSUE THREAD

**Issue by FredHappyface** [ImranR98/Obtainium#1287]
**Prerequisites**

- [x] https://github.com/ImranR98/Obtainium/issues/918 

**Describe the feature**

When providing download links for the apps I've written, I often use a download badge for each store 

It would be awesome to have a download badge similar to the get from play store/ fdroid/ GitHub etc 

I'd be very happy to submit a pr for this 

**Describe alternatives you've considered (if applicable)**

**Additional context**

See an example of existing badges 

![ResizedImage_2024-01-14_14-15-15_2558](https://github.com/ImranR98/Obtainium/assets/41634689/07f57485-d212-4e1e-b7be-17b42e8a9789)

Related to https://github.com/ImranR98/Obtainium/issues/147

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/blob/main/assets/graphics/badge_obtainium.png

**Comment by FredHappyface** [comment]
Further to this and the addition of a scheme. GitHub do not support many themselves and so using this unfortunately does not work in readmes (see https://github.com/github/markup/issues/933)

Still this'll work great elsewhere, thank you :)

**Comment by TidalMist** [comment]
#1326

**Comment by ImranR98** [comment]
@FredHappyface you could use https://github.com/intradeus/http-protocol-redirector as suggested in #1326

**Comment by r10s** [comment]
thanks a lot for the button and for the option to add apps to Obtainium that way!

we added one to Delta Chat's homepage at https://github.com/deltachat/deltachat-pages/pull/1113 :)

**Comment by inventory69** [comment]
Thanks for the badge! 👍 Using it for [Simple Notes Sync](https://github.com/inventory69/simple-notes-sync)
