### ISSUE TITLE
Adding tags or folders to organize sources.

### ISSUE THREAD

**Issue by vhick** [ImranR98/Obtainium#129]
Now that it capable of tracking from different sources, may I request to have a tags or folder to organize the if we have to many projects to track, like this one for example:

![Screenshot_2022-11-26-10-49-16-268_com nononsenseapps feeder play](https://user-images.githubusercontent.com/2021625/204069732-dea18c19-ffe6-406d-a57c-8c2a8daf2515.jpg)

Many thanks! ☺️

**Comment by S7venLights** [comment]
This would be a nice option in the filter list menu

**Comment by S7venLights** [comment]
I feel like once Obtainium has this feature and the ability to add apps from different F-droid repos, it will be pretty feature complete and perhaps near ready for a stable V1 release. 

Then I could remove or disable other F-droid apps  (to save battery and be minimalist) and use F-droids website for app discovery/searching when needed.

**Comment by ImranR98** [comment]
Leaving some notes for later:
- Obtainium should define a `Map<String, Category> categories`, where the `String` is a fixed category ID, and a `Category` object contains a `String name` and a `Color colour`.
    - This are stored in the App's shared preferences (serialized as JSON).
- The user should be able to add/remove/modify categories from the Settings page.
    - Specifically, in a "Categories" section with a group of coloured `Chip`s for categories that can be clicked to open a modal that lets you delete, rename, or recolour them, along with an "Add Category" button. 
- Each App can optionally be associated with a category (only one) via its ID.
    - If an App ever refers to a non-existent category ID (which would happen when a category is deleted), it should be automatically uncategorized.
        - This should happen on App load, save, and whenever a category is deleted.
- The category for an App should be picked via a dropdown on the App and Add App pages.
- An App's category should be displayed on the App and Apps pages.
    - In the latter case, there may only be enough space to show the category colour (needs experimenting).
- The filter function on the Apps page should support filtering by category.
    - Probably using a group of multi-selectable `Chip`s.

**Comment by ImranR98** [comment]
Added very basic support for App categories: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.0-beta
The UI is kind of unintuitive, but this was a quick addition and I didn't want to clutter the interface too much. Will probably make improvements in the future.

**Comment by bluefly000** [comment]
You can use the category filter by adding categories at the bottom of the settings page and setting the category on the app page.

**Comment by S7venLights** [comment]
Thanks, I figured out part one but not "setting the category on the app page"

**Comment by S7venLights** [comment]
I still don't know how to add apps to a category…

**Comment by ImranR98** [comment]
![Screenshot_20221226-171800](https://user-images.githubusercontent.com/30463115/209586141-1111cac0-9c7e-4afe-9d99-b28e92b71a18.png)

**Comment by S7venLights** [comment]
If I click on an app from the apps tab, it just shows a webview of the github, f-droid or repo page…

**Comment by ImranR98** [comment]
Whoops. Completely forgot about the web view as I rarely use it. Will make an issue for that. In the meantime you can turn off webview in the settings.

**Comment by S7venLights** [comment]
Ah but if I turn of "Show source webview" in settings, then I see that menu of your screenshot. 
Perhaps add category selection to the bottom bar/menu alongside "update remove" buttons. 
So that even when webview is on, one can use the category menu.

**Comment by S7venLights** [comment]
Wow that was fast

**Comment by S7venLights** [comment]
Adding to categories via multi select, could also be nice

**Comment by S7venLights** [comment]
And multiple categories per app could be useful. EG: Games + F-droid

**Comment by ImranR98** [comment]
@S7venLights since you're actively using this feature (I'm not), could you test this build:
[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/10311570/app-x86_64-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/10311571/app-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/10311572/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/10311573/app-arm64-v8a-release.zip)

Addresses #204, #205, #206.

**Comment by ImranR98** [comment]
Slightly newer build with updates for #201, #202.

[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/10311663/app-x86_64-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/10311664/app-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/10311665/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/10311666/app-arm64-v8a-release.zip)

**Comment by S7venLights** [comment]
Wait, this one is now officially released? 0.9.11

**Comment by ImranR98** [comment]
> Wait, this one is now officially released? 0.9.11

Yeah, seemed okay and I wanted to push it out as I probably won't be around for the rest of the week.
