### ISSUE TITLE
Support Direct APK Links

### ISSUE THREAD

**Issue by cautious-bread** [ImranR98/Obtainium#1292]
I've had a search for this in existing issues and also the HTML methods on the Wiki.

When attempting to add the Proton Drive APK directly, Obtainium appear to hang and then lock up, needing a force-close to allow it to open again.

1. Tap "Add App"
2. Paste "**https://proton.me/download/DriveAndroid/ProtonDrive-Android.apk**" into the "app source URL".
3. Tap the "add" button.
4. Watch the spinner for a few seconds before it stops, indicating the app has crashed.
5. Notice the app is not responsive then force-close it.

Trying the higher URLs e.g. **https://proton.me/download/DriveAndroid** or **https://proton.me/download** result in a "Forbidden" response.

No files of use under the /Andoid/data/ directory except for app json files and the Obtainiun cache.apk.

 - Device: Pixel 7a
 - OS: GrapheneOS
 - Obtainium Version: v0.15.11-beta

Nothing else to add - just hoping to get the Proton app APKs added directly.

**Comment by ImranR98** [comment]
The HTML source is for HTML pages with APK links in them - it doesn't take direct APK links.

That said, we could add support for direct links easily now that #1101 has been resolved). I'll leave this issue open to track that feature, but you don't need it for your case. Adding https://proton.me/drive/download will work.

**Comment by cautious-bread** [comment]
Thanks for that concise response @ImranR98 - received and understood.
Using the URL you suggested did the trick.

Cheers.

**Comment by NicholasFlamy** [comment]
So what is the forbidden response? I assume it's because the website wants to prevent bots or something.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.16.0-beta
