### ISSUE TITLE
Shizuku installer freezes Obtainium

### ISSUE THREAD

**Issue by soredake** [ImranR98/Obtainium#1294]
**Prerequisites**

**Describe the bug**
Obtainium is freezing when installing any apk with Shizuku

**To Reproduce**

**Screenshots and Logs**

![Screenshot_20240116-125009](https://github.com/ImranR98/Obtainium/assets/5204968/fd071090-c238-4735-b23d-0536c512ae28)

**Please complete the following information:**
 - Device: Samsung Galaxy Tab A 10.1 (2019) | SM-T510
 - OS: Android 11 OneUI 3.1
 - Obtainium Version: 0.15.10

**Additional context**

**Comment by NicholasFlamy** [comment]
Where did you install Shizuku from? Google Play Store?

**Comment by NicholasFlamy** [comment]
![Screenshot_20240117_133303_Shizuku](https://github.com/ImranR98/Obtainium/assets/30300649/92a33949-9ce0-448c-b86c-f333a493240f)
Also, is Shizuku properly paired and started (does it say at the top that it's running) and have you authorized Obtainium? (tap where I circled)

**Comment by aleks01100001** [comment]
If installing with shizuku is enabled then during the installation the app freezes, but after the installation is successful the app becomes responsible again.

ps. obtanium is not in the shizuku aplication manager settings![Screenshot_20240120_211314_Shizuku.png](https://github.com/ImranR98/Obtainium/assets/49501241/a5edb317-b643-45a9-9f8f-d27436ba6ef4)

**Comment by NicholasFlamy** [comment]
> If installing with shizuku is enabled then during the installation the app freezes, but after the installation is successful the app becomes responsible again.
> 
> ps. obtanium is not in the shizuku aplication manager settings![Screenshot_20240120_211314_Shizuku.png](https://private-user-images.githubusercontent.com/49501241/298305571-a5edb317-b643-45a9-9f8f-d27436ba6ef4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODQzNjIsIm5iZiI6MTcwNTc4NDA2MiwicGF0aCI6Ii80OTUwMTI0MS8yOTgzMDU1NzEtYTVlZGIzMTctYjY0My00NWE5LTlmOGYtZDI3NDM2YmE2ZWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIwNTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZTc5YjQzYTZhYzFlZTMxYzQzYTFiNGQ2MDk4Y2Q1YWZkYTdjOTI5NzNiOGEwMGI4MWVlODk3MzNkMDk1YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t0lmjijU-scJqDZQ-5CU3rY3JluSQFx8wNQoYEmdwyo)

Then you have a problem. Mine shows up.

**Comment by aleks01100001** [comment]
i reinstalled shizuku and now obtanium is in the list.

But the problem persists that the app freezes when trying to install an app.

**Comment by Fummowo** [comment]
Having this issue aswell, tested with Shizuku on both root and non-root phones.
Obtainium asks for Shizuku permission properly and appears as allowed inside Shizuku.
Tested on Android 11 and 12

**Comment by HardNocky** [comment]
Obtainium does freeze for a few moments while it hands the installation to Shizuku, but it will become responsive again as soon as the install is finished. Tapping the screen anywhere will give you the not responding prompt, so I just don't touch the screen until Shizuku has finished installing. If you do touch the screen and get the not responding prompt, just keep tapping Wait until the install completes. This can take anywhere from 5-10 seconds up to a minute, depending on the size of the app and the speed of your device.

**Comment by Ketsuyumi** [comment]
> > If installing with shizuku is enabled then during the installation the app freezes, but after the installation is successful the app becomes responsible again.
> > ps. obtanium is not in the shizuku aplication manager settings![Screenshot_20240120_211314_Shizuku.png](https://private-user-images.githubusercontent.com/49501241/298305571-a5edb317-b643-45a9-9f8f-d27436ba6ef4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODQzNjIsIm5iZiI6MTcwNTc4NDA2MiwicGF0aCI6Ii80OTUwMTI0MS8yOTgzMDU1NzEtYTVlZGIzMTctYjY0My00NWE5LTlmOGYtZDI3NDM2YmE2ZWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIwNTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZTc5YjQzYTZhYzFlZTMxYzQzYTFiNGQ2MDk4Y2Q1YWZkYTdjOTI5NzNiOGEwMGI4MWVlODk3MzNkMDk1YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t0lmjijU-scJqDZQ-5CU3rY3JluSQFx8wNQoYEmdwyo)
> 
> Then you have a problem. Mine shows up. (Galaxy S21 OneUI 5.1.1 Android 13)

mine shows up too, but it still freezes

**Comment by BRBsoup** [comment]
> Obtainium does freeze for a few moments while it hands the installation to Shizuku, but it will become responsive again as soon as the install is finished. Tapping the screen anywhere will give you the not responding prompt, so I just don't touch the screen until Shizuku has finished installing. If you do touch the screen and get the not responding prompt, just keep tapping Wait until the install completes. This can take anywhere from 5-10 seconds up to a minute, depending on the size of the app and the speed of your device.

^ This is exactly the issueand is still happening. Honestly makes using Shizuku Installer with Obtainium pointless, since Session Installer only requires that the first update on the same queue is user-confirmed. I'm only keeping the setting enabled because I'm hard-headed and hope that rather than abandoning the issue that it will get fixed. 

P.S. Disable/Enable Background ANR in Developer Settings has no effect on this from happening regardless.

**Comment by re7gog** [comment]
I got properly working plugin prototype which can work in background asynchronously 🐱
So it should fix all problems
https://github.com/re7gog/shizuku_apk_installer

**Comment by BRBsoup** [comment]
> I got properly working plugin prototype which can work in background asynchronously 🐱 So it should fix all problems https://github.com/re7gog/shizuku_apk_installer

Hey thanks for sharing!

Has anyone implemented this into an APK/Obtainium/Shizuku/Installer app or altogether, to actually make Obtainium and Shizuku working, then? I hope the developer will look into this, and if it's a viable fix then it should be adopted!

**Comment by re7gog** [comment]
> > I got properly working plugin prototype which can work in background asynchronously 🐱 So it should fix all problems https://github.com/re7gog/shizuku_apk_installer
> 
> Hey thanks for sharing!
> 
> Has anyone implemented this into an APK/Obtainium/Shizuku/Installer app or altogether, to actually make Obtainium and Shizuku working, then? I hope the developer will look into this, and if it's a viable fix then it should be adopted!

I'm the contributor, so I'll make this

**Comment by re7gog** [comment]
Try now

**Comment by JasonHK** [comment]
@re7gog I can confirm it no longer freezes

**Comment by re7gog** [comment]
I think this issue can be closed now🚀

**Comment by BRBsoup** [comment]
> I think this issue can be closed now🚀

Thank you so much, Obtainium is now 1,000% more usable thanks to your fix!

**Comment by ImranR98** [comment]
Thanks @re7gog!
