### ISSUE TITLE
Option to determine remote app version from apk name instead of GitHub release name

### ISSUE THREAD

**Issue by soredake** [ImranR98/Obtainium#1296]
**Prerequisites**

**Describe the feature**
I have set up youtube revanced upgrading from this repo https://github.com/shekhawat2/RevancedYT/releases
The problem is, released published with "RevancedYT-<Date>" name which results in Obtainium forever thinking that there are update cause version strings are different.
![Screenshot_20240116-131450_Obtainium](https://github.com/ImranR98/Obtainium/assets/5204968/c1678b4c-aa60-4a35-80a3-8791641523b9)

Regex to match revanced youtube apk: `RevancedYT_.*-noroot\.apk`

**Describe alternatives you've considered (if applicable)**

**Additional context**

**Comment by NicholasFlamy** [comment]
Yep, @ImranR98, I think I mentioned that this would be useful in one of my other issues before but I found multiple alternatives. In this instance, the only version information matching app information is the apk file name. I added this to check and the app versionCode is not useful.

**Comment by NicholasFlamy** [comment]
@soredake, a temporary workaround would be to override the source to HTML, but that would require some manual RegEx.

**Comment by ImranR98** [comment]
This would create unnecessary complexity as release titles and APK names are not unique. It's perfectly fine to use tags as "version strings" - this only means that you wouldn't be able to use "[version detection](https://github.com/ImranR98/Obtainium/wiki#version-detection)" which is an optional feature and is not required for update tracking.

In your screenshot, the real and 'recorded' versions of the app are out of sync. To correct this, just tap the tick icon ("mark as updated").
