### ISSUE TITLE
Does it auto update some apps in the background?

### ISSUE THREAD

**Issue by jayb-g** [ImranR98/Obtainium#1299]
I noticed recently that yesterday Signal and ProtonVPN today got auto updated in the background without obtanium open even in the system tray and came to know by obtanium notification saying:

'_App_ may be updated to version x.x.x.'

I did not update any of those apps by any other app store or manually. 

Is it a functionality? Is it app dependent? It would be awesome if all apps can be updated like that in the background without requiring user action each time.

**Comment by ImranR98** [comment]
Yes, see here: https://github.com/ImranR98/Obtainium/wiki#background-updates

Also just for future reference, this is more of a [discussion](https://github.com/ImranR98/Obtainium/discussions) than an issue.
