### ISSUE TITLE
Download notification

### ISSUE THREAD

**Issue by Baker0o7** [ImranR98/Obtainium#13]
Thank you sir for such amazing app and for your hard work

Can you please add download notification , notify of downloaded Apks and progress 👍

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.2-beta

**Comment by Baker0o7** [comment]
Thank you sir👌

**Comment by S7venLights** [comment]
Is it possible to group the notifications, rather than have 1 per app?
