### ISSUE TITLE
Apkmirror links not working

### ISSUE THREAD

**Issue by eloffmarijan** [ImranR98/Obtainium#130]
I couldn't add apps link from apkmirror.
![Screenshot_20221126-101355](https://user-images.githubusercontent.com/101601874/204072819-5c22f5ec-7dd0-4dbe-942c-9cf1dfac9735.png)

**Comment by ImranR98** [comment]
What's the full url?

**Comment by eloffmarijan** [comment]
https://www.apkmirror.com/apk/samsung-electronics-co-ltd/galaxy-labs/

**Comment by ImranR98** [comment]
It does work on the latest Obtainium 0.8.1, I'm guessing you're on 0.8.0.

**Comment by eloffmarijan** [comment]
But I'm on the latest version(0.8.1-beta)

**Comment by eloffmarijan** [comment]
Now its working.

**Comment by PRSXFENG** [comment]
Unfortunately it doesn't work for me, I tried the following link
https://www.apkmirror.com/apk/textnow-inc/textnow-free-text-calls-2/

Version 0.9.6
I get the same could not find a suitable release error

**Comment by ImranR98** [comment]
> Unfortunately it doesn't work for me, I tried the following link https://www.apkmirror.com/apk/textnow-inc/textnow-free-text-calls-2/
> 
> Version 0.9.6 I get the same could not find a suitable release error

Should work now: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.7-beta

**Comment by PRSXFENG** [comment]
Thanks, it works now!

**Comment by BabyOilJohnson** [comment]
I can't add [Twitter](https://www.apkmirror.com/apk/x-corp/twitter), showing "not a valid apkmirror app url".
