### ISSUE TITLE
"Could not find a suitable release"

### ISSUE THREAD

**Issue by stripeytofu** [ImranR98/Obtainium#1301]
**Prerequisites**

**Describe the bug**
I keep getting this error whenever I try to add any link. I've tried a couple of different versions of Obtainium and messed with the settings but they all prove this result. I'm using an Odin 2 by the way.

**To Reproduce**

**Screenshots and Logs**
[
![Screenshot_20240118-012700](https://github.com/ImranR98/Obtainium/assets/98422185/29937cc1-7b2b-4581-a970-f9212e1e7e62)
](url)

**Please complete the following information:**
 - Device: Odin 2
 - OS: 
 - Obtainium Version: 0.15.11-beta

**Additional context**

**Comment by ImranR98** [comment]
The repo in your screenshot does not publish releases: https://github.com/yuzu-emu/yuzu/releases

There need to be actual releases with APKs attached for Obtainium to grab. For example: https://github.com/deckerst/aves/releases

**Comment by stripeytofu** [comment]
I see! It works now. Thank you!
