### ISSUE TITLE
Help getting ungoogled-chromium to work. 

### ISSUE THREAD

**Issue by testbughub** [ImranR98/Obtainium#1302]
**Describe the bug**
I'm trying to get [ungoogled-chromium](https://github.com/ungoogled-software/ungoogled-chromium-android) to work, but I'm having some issues.  
I think I got the version detection set up correct, but when I try to install, I get the following error:  
```
Downloaded package ID does not match existing App ID - org.ungoogled.chromium.stable [ungoogled-chromium-android]
```  

**To Reproduce**
1. Add "https://github.com/ungoogled-software/ungoogled-chromium-android"
2. Toggle ON fallback to older releases. 
3. Add ".*[^-webview]" to regex to filter out the webview apk's which I don't need. 
4. Standard version detection. 
5. APK filter = "ChromeModernPublic_arm64"
6. Tap Install. 

**Screenshots and Logs**
![Screenshot_20240118-092449](https://github.com/ImranR98/Obtainium/assets/30836300/1c4fba6e-2e9f-4525-b2c8-f59400fc2627)
![Screenshot_20240118-092421](https://github.com/ImranR98/Obtainium/assets/30836300/f9b52ea2-d79f-4db3-9c5a-140dba4b3837)

**Please complete the following information:**
 - Device: Sony Xperia 1 IV
 - OS: Android 14
 - Obtainium Version: 0.15.11

**Additional context**
I hope a haven't missed anything, and I apologize if there is an obvious solution/explanation.

**Comment by testbughub** [comment]
Actually, I only now noticed that that project rarely sees any updates, so it might not be worth it.  
But if I could get some pointers for if I get any similar problems, I'd appreciate it 😃

**Comment by ImranR98** [comment]
As the error says, the app ID has changed. The app ID is the unique name Android uses to identify apps - different ID means different app so the APK would not be applied as an update, you would end up with 2 separate chromium apps.

When you added the app, one of it's APKs was downloaded (following the filter rules you set) and the ID from that APK was picked up. Now, the release/APK being picked for updates has a different app ID.

You would need to look through the repo's releases and APKs, determine why the ID has changed, then add the app to Obtainium again - this time using different filtering options to ensure it only picks up the one you want.
