### ISSUE TITLE
Add Instander to check the version

### ISSUE THREAD

**Issue by update-freak** [ImranR98/Obtainium#1305]
**Describe the feature**
Would be good to have also the possibility to detect the version of Instander.
Repo: https://thedise.me/instander/repo/
Version in the repo: 17.2
Version of the app in android: 263.2.0.19.104

**Describe alternatives you've considered (if applicable)**
Alternative would be to add the soure here: https://apkpure.net/instander/com.instander.android
But from today onwards I got the message in the App to update to newest Instagram version

**Comment by ImranR98** [comment]
If the webpage doesn't provide the correct version string, there's nothing Obtainium can do. It also wouldn't make sense to grab the version string from a different place - no guarantee that they'll always be in sync (it would also require this app to be added as it's own source which is unnecessary). I suggest just turning off the setting "reconcile version string with version detected from OS", then click "Mark as Updated" (checkmark icon). Then Obtainium will just use the version string coming from the webpage and you'll get update notifications as expected.
