### ISSUE TITLE
Snackbar bug when cancelling APK choice dialog

### ISSUE THREAD

**Issue by Outlet7493** [ImranR98/Obtainium#1307]
**Describe the bug**
After pressing cancel on the "Pick an APK" dialog, Obtainium creates a snackbar that says "Apps updated" when no updates were completed as I didn't pick an APK.

**To Reproduce**
1. Click on app that needs updating
2. Press update
3. If Obtainium asks you to pick which APK to download, press cancel or press outside of dialog

**Screenshots and Logs**

https://github.com/ImranR98/Obtainium/assets/122801553/f864ceaf-6e96-4ee7-beb5-163add985d84

**Please complete the following information:**
 - Device: Pixel 7a
 - OS: GrapheneOS
 - Obtainium Version: v0.15.11-beta

**Additional context**
Background updates is off

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.16.1-beta
