### ISSUE TITLE
Please help me i can't Add App or Check for Updates 

### ISSUE THREAD

**Issue by stevenwhat68** [ImranR98/Obtainium#1320]
My phone is Realme c25y
Realme os
Obtainium 0.16.1 beta
![Screenshot_20240121-115516](https://github.com/ImranR98/Obtainium/assets/156883281/f778d98a-b2ca-4635-9b52-e593e50ac132)

**Comment by ImranR98** [comment]
You've been rate limited by GitHub. Wait 28 minutes or add a GitHub token in the settings. See here for more details: https://github.com/ImranR98/Obtainium/wiki#github

**Comment by stevenwhat68** [comment]
How to fix unauthorized error?

**Comment by ImranR98** [comment]
Please provide more details.

**Comment by stevenwhat68** [comment]
Ohh wait i fix it , i just need to generate a new token cause i didn't
check the right box, thank you so much for the help i really appreciate it
🙏🙏, hope you have a wonderful day.
