### ISSUE TITLE
obtainium:// readme.md

### ISSUE THREAD

**Issue by TidalMist** [ImranR98/Obtainium#1326]
Maybe you could make a repository like https://github.com/intradeus/http-protocol-redirector
But Firefox and webview browsers opens not correct link in obtainium. Chrome opens correct. Can be fixed?
> ## Firefox ![IMG_20240122_200530](https://github.com/ImranR98/Obtainium/assets/91356643/0d83a7c6-26a2-46b1-b2c7-a67aa4284ef9)

> ## Chrome ![IMG_20240122_200929](https://github.com/ImranR98/Obtainium/assets/91356643/883421cd-a750-4412-a8f0-6b46d70c2811)

https://intradeus.github.io/http-protocol-redirector?r=obtainium://app/%7B%22id%22%3A%22dev.patrickgold.florisboard.beta%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Fflorisboard%2Fflorisboard%22%2C%22author%22%3A%22florisboard%22%2C%22name%22%3A%22FlorisBoard%20Beta%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Atrue%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionDetection%5C%22%3A%5C%22standardVersionDetection%5C%22%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%7D

> [!IMPORTANT]
> ## https://github.com/ImranR98/apps.obtainium.imranr.dev now has a redirect page
> I close issue

**Comment by TidalMist** [comment]
#1287

**Comment by TidalMist** [comment]
https://github.com/TidalMist/http-protocol-redirector
Firefox opens correct
https://tidalmist.github.io/http-protocol-redirector/?r={"id":"dev.patrickgold.florisboard.beta","url":"https://github.com/florisboard/florisboard","author":"florisboard","name":"FlorisBoard%20Beta","preferredApkIndex":0,"additionalSettings":"{\"includePrereleases\":true,\"fallbackToOlderReleases\":true,\"filterReleaseTitlesByRegEx\":\"\",\"filterReleaseNotesByRegEx\":\"\",\"verifyLatestTag\":false,\"dontSortReleasesList\":false,\"trackOnly\":false,\"versionDetection\":\"standardVersionDetection\",\"apkFilterRegEx\":\"\",\"autoApkFilterByArch\":true,\"appName\":\"\",\"exemptFromBackgroundUpdates\":false,\"skipUpdateNotifications\":false,\"about\":\"\"}"}
Need remove spaces or replace with %20
Idk how i did it. Probably something is wrong

**Comment by ImranR98** [comment]
What version of Firefox are you using? The link in your first comment works fine on my end.

**Comment by TidalMist** [comment]
Latest Iceraven. I have now tried firefox from google play and indradeus link opens not correct too. My fork opens correct. I changed redirect.js

**Comment by ImranR98** [comment]
Seems like a character limit issue then? May be device dependent or unique to the Iceraven builds as I don't see this issue on regular Firefox or Chromium.

**Comment by TidalMist** [comment]
I'm on realme android 13 but now tried on honor android 10 device and its same, firefox and webview browser(1dm) opens without backslashes. Kiwi browser(chrome based) opens with backslashes.
As i wrote in PR, need more people confirm that.
https://github.com/Hamster45105/apps.obtainium.imranr.dev/pull/1
PR fixes for me

**Comment by Hamster45105** [comment]
I can confirm the same thing happens for me on Firefox. Going to: 

https://intradeus.github.io/http-protocol-redirector/?r=obtainium://app/%7B%22id%22%3A%22dev.patrickgold.florisboard.beta%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Fflorisboard%2Fflorisboard%22%2C%22author%22%3A%22florisboard%22%2C%22name%22%3A%22FlorisBoard%20Beta%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Atrue%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionDetection%5C%22%3A%5C%22standardVersionDetection%5C%22%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%7D

will return:
 
![SmartSelect_20240128_082633.png](https://github.com/Hamster45105/apps.obtainium.imranr.dev/assets/133548095/983915be-847f-4b81-820f-dbdcb1ef8095)

I'm on the latest Play Store build.
