### ISSUE TITLE
Add support for Tor source

### ISSUE THREAD

**Issue by muznyo** [ImranR98/Obtainium#133]
Tor browser isn't in official fdroid repository, but it has their own

https://dist.torproject.org/torbrowser/11.5.9/tor-browser-11.5.9-android-aarch64-multi.apk

**Comment by S7venLights** [comment]
#72 would solve this issue

**Comment by ImranR98** [comment]
Yes, now that #72 is resolved this should not be needed. Add https://guardianproject.info/fdroid/repo/ as a source, and use "Tor" as the App name (the full name is "Orbot: Proxy with Tor" but Obtainium will pick the closest match.

**Comment by S7venLights** [comment]
👆 that will add orbot, To add Tor Browser, use Tor Browser as the app name. 

Thanks for this feature ✨

**Comment by S7venLights** [comment]
Is it possible to add this as a source to avoid the F-droid key signing issue: 

https://www.torproject.org/download/#android

**Comment by ImranR98** [comment]
Have you confirmed if the key signing is different on their third party f-droid repo? I thought that was only an issue for the official f-droid repo but that's an assumption.

**Comment by S7venLights** [comment]
Oh yeah I did forget they have a repo separate from F-droids… I also assume it's fine then.
