### ISSUE TITLE
Confusing Message after Signal updates

### ISSUE THREAD

**Issue by skwde** [ImranR98/Obtainium#1330]
**Prerequisites**

**Describe the bug**

Whenever I update Signal, Obtainium sends the following notification

```sh
App Updates Attempted
Signal may have been updated to <version>
```

Does this mean that signal was update or not?

**To Reproduce**

1. Update signal
2. see the notification

**Screenshots and Logs**

**Please complete the following information:**
 - Device:  Pixel 7a
 - OS: GrapheneOS
 - Obtainium Version: 0.16.1-beta

**Additional context**

**Comment by ImranR98** [comment]
The "attempted" notification is fine. See https://github.com/ImranR98/Obtainium/wiki#background-updates

**Comment by skwde** [comment]
@ImranR98, I read the backgroud-updates section you linked but I still don't get why it is normal.

In any case, does that mean that always mean that the app was updated?

**Comment by ImranR98** [comment]
When we try to install apps in the background, there's no way for the installer code to return a success/fail result. So most of the time it succeeds, but even when it fails, there's no way to know about it without actually opening Obtainium and seeing whether the app is up to date or not.
