### ISSUE TITLE
Some errors occured: PathNotFoundException

### ISSUE THREAD

**Issue by skwde** [ImranR98/Obtainium#1331]
**Prerequisites**

**Describe the bug**
After I updated signal and opened Obtainium again I got the error message as shown in the screenshot
![Screenshot_20240124-051135](https://github.com/ImranR98/Obtainium/assets/26454702/a0f59ed7-0530-459d-9e8a-a7a46250c285)

**To Reproduce**

Not sure if the cause was the update but here is what I did

1. Update signal
2. reopen obtainium

**Screenshots and Logs**

**Please complete the following information:**
 - Device: Pixel 7a
 - OS: GrapheneOS
 - Obtainium Version: 0.14.6-beta

**Additional context**

**Comment by ImranR98** [comment]
Clear the cache - it shouldn't happen again (I'm guessing something went wrong during the download).

**Comment by skwde** [comment]
Thanks. Since I experienced the error, it did not occur again. I cleared the cache and updated obtainium.

Closing this.

**Comment by brian6932** [comment]
@ImranR98 I'm getting this now that I updated to Android 14, on 1.1.0, whenever adding any apps. All my previously added apps were wiped when the app was launched for the first time after updating.

**Comment by itskenny0** [comment]
I am also having the same issue on my Android 14 device (Xiaomi Pad 5). Cache was cleared, still occurs.
