### ISSUE TITLE
Enhancement: Add an adaptive icon for Android 13

### ISSUE THREAD

**Issue by mariobrostech** [ImranR98/Obtainium#134]
Hi,

If you could provide an adaptive icon for devices running Android 13, that would be great! Obtainium already support the Android 13 API level, so this should be relatively easy to implement and would help the app fit into setups that have a shortcut to Obtainium on the home screen.

Thanks in advance!

**Comment by ImranR98** [comment]
Will be able to add this once this issue is resolved in the icon plugin Obtainium uses: https://github.com/fluttercommunity/flutter_launcher_icons/issues/419

**Comment by ImranR98** [comment]
Added in https://github.com/ImranR98/Obtainium/releases/tag/v0.10.4-beta thanks to @p1gp1g (turns out the plugin was not a blocker after all).
