### ISSUE TITLE
F-droid app changes doesn't show the actual release note but html code instead

### ISSUE THREAD

**Issue by M0-7** [ImranR98/Obtainium#1340]
**Describe the bug**
Pressing on the obtanium changes button on fdroid apps shows a dialog in which it seems to scrape the wrong part of the website and as a result weird HTML code is displayed instead of the actual release notes.

**To Reproduce**
1. Search for an fdroid app in obtanium e.g antennapod, and download it
2. Press on the changes button to see the weird notes

**Screenshots and Logs**
![Screenshot_20240125_174005](https://github.com/ImranR98/Obtainium/assets/135035314/6b01c479-5da5-4c53-8edb-cb861e0cce0c)
![Screenshot_20240125_173957](https://github.com/ImranR98/Obtainium/assets/135035314/6c01ae21-417b-48b5-9723-87f4db389ec4)

The apps are antennapod and fennec(deblobbed firefox) respectively.

**Please complete the following information:**
 - Device: Samsung z fold 3
 - OS: One ui 6
 - Obtainium Version: 1.00

**Additional context**
This bug started happening in the last 2 versions

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.1
