### ISSUE TITLE
Clarify support for third party git hosting services in supported sources

### ISSUE THREAD

**Issue by ClockGen** [ImranR98/Obtainium#1342]
**Describe the feature**
Currently, app only displays support for "official" git hosting services, even though it supports self-hosted instances of other services as well (https://github.com/ImranR98/Obtainium/pull/502). This is not mentioned in "supported sources" pop-up in "add app" tab and also in wiki, so it might lead users to believe that only "official" instances of these services are supported.   

It might be useful to alter strings in "supported sources" popup for gitlab, codeberg and sourcehut to mention that they also support self-hosted services, for example something like `Codeberg (Searchable) (incl. forgejo/gitea)` or `Gitlab (searchable) (incl. selfhosted)`.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.1
