### ISSUE TITLE
MissingPluginException(No implementation found for method checkPermissionShizuku)

### ISSUE THREAD

**Issue by brian6932** [ImranR98/Obtainium#1343]
**Prerequisites**
- [x] Please ensure your request is not part of an existing issue.
- [x] Please ensure you have checked the Obtainium Wiki.

**Describe the bug**
I get this error like everytime an update check's ran in the background. I can't expand the notification more than that, Idk why it's truncated like that. I use Sui btw.

**To Reproduce**

![](https://github.com/ImranR98/Obtainium/assets/18603393/fd007edc-f540-4bc1-9f2a-47b475ac41fe)

**Please complete the following information:**
 - Device: Zenfone 9
 - OS: OmniROM 13
 - Obtainium Version: 1.0.0

**Comment by ImranR98** [comment]
Do you have the Shizuku app installed and set up?

**Comment by brian6932** [comment]
No as mentioned in the issue, I use Sui

**Comment by TheBrokenG0d** [comment]
> Do you have the Shizuku app installed and set up?

So to throw my hat in as well. I am using the Shizuku app and it is setup and working. But obtainium throws the error when Shizuku is selected.

**Comment by ImranR98** [comment]
Relevant: https://github.com/ImranR98/Obtainium/issues/1200#issuecomment-1922511891

**Comment by soredake** [comment]
Same for me:
![Screenshot 2024-02-05 121341](https://github.com/ImranR98/Obtainium/assets/5204968/3e63b6eb-39ca-4d07-b9fb-8d6de626fd31)

With Sui I have this error, on other device without root i don't have this error.

**Comment by soredake** [comment]
On my new non-rooted device I just got this error, but, the app is updated fine despite that.

**Comment by raulvasquez** [comment]
Same notification error using kitsune magisk w/ sulist  and shizuku install. Install and updates work. The notification is just an annoyance. Root installation method fails.

**Comment by re7gog** [comment]
Check now

**Comment by brian6932** [comment]
Btw, I did swap from Magisk + Sui to KSU + Zygisk Next + Sui about a month or so ago, and I stopped receiving this error. Not entirely positive if that's what helped, but it's very likely, either that or an OTA.

**Comment by soredake** [comment]
I don't get this error anymore on two devices, thank you @re7gog !

**Comment by brian6932** [comment]
Ah, in that case I'll close this
