### ISSUE TITLE
GitHub personal access token scopes

### ISSUE THREAD

**Issue by torgeros** [ImranR98/Obtainium#1344]
GitHub introduced (as a beta test) something called "Fine-grained personal access tokens".

With these, you can select token scopes through a revamped UI. I was wondering, which scopes are required. This should (for the new and old tokens) be documented [in the wiki](https://github.com/ImranR98/Obtainium/wiki#github).

Additionally, it might be interesting to have a help/info dialog in the Obtainium app, next to the API token fields, telling you which scopes you need to select.

The same thing might be relevant to the GitLab token field, too.

**Comment by firefoxlover** [comment]
I think "read access" should be enough. Works very well forn me.

**Comment by ImranR98** [comment]
Added to the Wiki.
