### ISSUE TITLE
make reinstalling apps possible

### ISSUE THREAD

**Issue by firefoxlover** [ImranR98/Obtainium#1345]
1. I have all apps from F-Droid
2. I added their original release URLs to obtainium
3. I want to install them new, update not possible

There is no way I could find. Even worse, when uninstalling an app it also disappears from Obtainium.

A button to reinstall it would be great. Best even to skip androids "keep data" dialog with "yes".

**Comment by DJCrashdummy** [comment]
some kind of a workaround would be to deactivate the slider "automatically remove externally uninstalled apps" in the settings (and uninstall them externally - at least with the app-info of the system via the gear icon at the left bottom).

after that the app is still present in Obtainium and you can download & install it from the chosen source.

**Comment by ImranR98** [comment]
You can multi-select apps from the list using a long press. From there, tap the uninstall icon and disable the "remove from obtainium" toggle while keeping "uninstall" enabled. You can then re-install them from the same multi-select menu.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/assets/30463115/2d33d194-b033-48fb-8e4c-3d48d90929a6
