### ISSUE TITLE
Search Button

### ISSUE THREAD

**Issue by firefoxlover** [ImranR98/Obtainium#1346]
The list UI is very strange. Instead of an advanced filter a simple search is enough. Would be way better to find apps.

Also afaik there is no easy way to change sorting.

**Comment by ImranR98** [comment]
> Instead of an advanced filter a simple search is enough.

More advanced search has been requested by others - you can always stick to the 'App Name' field and ignore the others.

> Also afaik there is no easy way to change sorting.

Settings page.
