### ISSUE TITLE
SourceHut - Accept `/refs`

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#1347]
Not certain if this is a bug.  This SourceHub repo has links that have to be clicked on to get to the secondary page where the .apk's are located.  I used HTML with an intermediate link, and it worked fine, but if it's *supposed* to work with SourceHub, then I thought I should let you know.

https://git.singpolyma.net/cheogram-android/refs

https://git.singpolyma.net/cheogram-android/refs/2.13.0-2

**Comment by ImranR98** [comment]
What settings did you use? Works fine on my end. I'm guessing you either:
1. Used `/refs` in the URL.
2. Didn't select `SourceHut` from the source override menu.

I'll change this issue to track the first case - it should be able to trim the `/refs` automatically.

**Comment by DiagonalArg** [comment]
Ya, I used /refs in the url.  Thanks.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.1
