### ISSUE TITLE
don't refuse to change the "source" aka. distributor

### ISSUE THREAD

**Issue by DJCrashdummy** [ImranR98/Obtainium#1348]
**Prerequisites**
i'm not 100% sure if it's a bug or a feature... :stuck_out_tongue_winking_eye: 

**Describe the bug**
if you already have an app installed (and listed in Obtainium), you just get an error message if you try to add it again resp. change it's "source" (aka. distributor) and Obtainium refuses  to continue.

**To Reproduce**
1. add/install an app via Obtainium eg. from Aptoide
2. notice that this app won't get updates there, was removed, gets quicker updates somewhere else... or for whatever reason you want to change the "source" (aka. distributor).
3. simply add the (new) URL eg. from APKPure as you are used to...
4. Obainium only shows a short notification that this app is already added and refuses to continue.

**Please complete the following information:**
 - Device: Asus Z00ED
 - OS: Resurrection Remix OS
 - Obtainium Version: 1.0.0

**Additional context**
**changing the "source"** (aka. distributor) **shouldn't force you to remove the app** (at least from Obtainium) and add it again... as this is more error prone and might also lead to installing similar but different apps.
IMHO the better approach would be to inform the user that this app is already installed, the "source" (aka. distributor) would be changed but it can only receive future updates (without un- & reinstalling) if the signatures match.
or **even better** if it is possible to instantly check if the signatures match, than don't bother the user with such details and just guide him through reinstalling if the signatures don't match and he wants to do it now (after warning that all settings of the app will be lost).

**Comment by ImranR98** [comment]
Different sources have different additional options and limitations - trying to allow people to change the source for an already added app would cause more issues/confusion than just telling them to remove and re-add it. Note that all the signature verification stuff for updates is done by the OS, not Obtainium.

**Comment by DJCrashdummy** [comment]
oh well... haven't thought about the different "features" of the different "sources" (aka. distributors). :bulb: 
now i see, that a seamless "source"-/distributor-change would cause quite some coding effort which might not be worth it (for now).

**Comment by DJCrashdummy** [comment]
silly idea @ImranR98:
how about a window stating that this app is already added in Obtainium and the "source" (aka. distributor) can/would be changed by simply removing and re-adding the new "source" (aka. distributor) in Obtainium... with the options to *cancel* or *continue* instead of just the short notification, refusing to continue and having to do it manually. :thinking: 
the only remaining issue would be a signature change... but that's exactly the same issue when doing this procedure manually. :shrug: *(with this approach it may be also possible to inform about this issue and/or link the wiki - perhaps in the stated window, instead of letting the user figuring it out by itself.)*

-> this way it is not such a big deal of a feature but also not a big deal in coding... more or less just a convenience thing, which still makes it more likely to not install a similar but different app by accident.
