### ISSUE TITLE
Current version information unavailable when update is available

### ISSUE THREAD

**Issue by kattelk** [ImranR98/Obtainium#135]
When an app can be updated, the display shows "Update Available, See Changes".  I cannot however see what version I have installed once this happens.  This may be important if several updates have been released since the current version was installed, and I need to check all of the entries in the changelog after my current version number.  Currently I am checking the current version by comparing the installed version number with Droid-ify (when the app is available there).

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.2-beta
