### ISSUE TITLE
BAD PGP signature of app-release.apk in v1.0.1

### ISSUE THREAD

**Issue by tomgagdotnet** [ImranR98/Obtainium#1355]
**Describe the bug**
PGP verification of the sha256 file for app-release.apk fails in v1.0.1

**To Reproduce**
1. Download https://github.com/ImranR98/Obtainium/releases/download/v1.0.1/app-release.apk.sha256
2. Download https://github.com/ImranR98/Obtainium/releases/download/v1.0.1/app-fdroid-release.apk.sha256.sig
3. Download and import PGP key https://keyserver.ubuntu.com/pks/lookup?search=contact%40imranr.dev&fingerprint=on&op=index
```
gpg --verify app-release.apk.sha256.sig
gpg: assuming signed data in 'app-release.apk.sha256'
gpg: Signature made Sun 28 Jan 2024 04:11:24 AM CET
gpg:                using EDDSA key 8E27EC48A4FE21C71055E2E3C4EB2B69C138EBEA
gpg: BAD signature from "Imran Remtulla <contact@imranr.dev>" [unknown]
```

**Additional context**
Verification of signature succeeds in v1.0.0, using that for now.

**Comment by ImranR98** [comment]
> 1. Download https://github.com/ImranR98/Obtainium/releases/download/v1.0.1/app-release.apk.sha256
> 2. Download https://github.com/ImranR98/Obtainium/releases/download/v1.0.1/app-fdroid-release.apk.sha256.sig

Looks like you used the `sig` file for the F-Droid variant.

**Comment by tomgagdotnet** [comment]
> Looks like you used the `sig` file for the F-Droid variant.

Ughhh... you're right, my bad! All good :)
