### ISSUE TITLE
I need to manually press on update

### ISSUE THREAD

**Issue by xhaythemx** [ImranR98/Obtainium#1358]
**Prerequisites**

**Describe the bug**

When updating my apps using Obtanuim, Retroarch ask me to press on update after it download the apk.
**To Reproduce**

**Screenshots and Logs**

**Please complete the following information:**
 - Device:  Odin 2
 - OS:  A 13
 - Obtainium Version:  1.0.1

**Additional context**

**Comment by ImranR98** [comment]
The requirements for background updates also apply to foreground updates that skip the default Android confirmation dialog (see here: https://github.com/ImranR98/Obtainium/wiki#background-updates). Assuming that's what you meant.
