### ISSUE TITLE
Could you please add more sponsoring options (e.g. PayPal) to your profile or your project?

### ISSUE THREAD

**Issue by DwainZwerg** [ImranR98/Obtainium#1369]
### Discussed in https://github.com/ImranR98/Obtainium/discussions/1362

<div type='discussions-op-text'>

<sup>Originally posted by **DwainZwerg** February  1, 2024</sup>
Hello @ImranR98 ,
for instance in European countries (especially Germany, Austria (not so much the Scandinavian countries)), where the alternative EC card is used, it is still not common to have (real) credit cards (because the bank fees are usually much more expensive than those of an EC account). If one wants to transfer money to other countries outside the EU, one therefore usually uses PayPal. Could you imagine adding a PayPal account as another supporter option?
Thanks</div>

**Comment by inson1** [comment]
What about crypto (bitcoin, etherium, monero)?

**Comment by DwainZwerg** [comment]
Also highly preferable. But wouldn't help me (because I don't use crypto yet).

**Comment by ImranR98** [comment]
Thanks, I've added a Ko-fi link (they accept paypal).

**Comment by ImranR98** [comment]
@inson1 Not really into crypto (except Monero but not many services accept it anyways - other than Mullvad).

**Comment by DwainZwerg** [comment]
@ImranR98 I somehow can't transfer money via PayPal via Ko-Fi because Ko-Fi only wants me to transfer money via link or credit card. Could this be due to any of your settings? According to Ko-Fi's [FAQ](https://help.ko-fi.com/hc/en-us/articles/115003980093-How-Do-I-Get-Paid#faq-0-5:~:text=I%20want%20to,payments%20through%20Stripe.), you probably need to activate something else?
![Screenshot (32)](https://github.com/ImranR98/Obtainium/assets/97027379/8f3901cd-c269-4f5b-b83e-24b33b358aee)

**Comment by ImranR98** [comment]
Should work now hopefully

**Comment by DwainZwerg** [comment]
https://Ko-fi.com/home/coffeeshop?txid=fd6013a4-a0a8-431c-8a96-20dc588ee439&mode=public&img=ogiboughtsomeone

Wow: You could even use giropay (the European financial and transfer system for EC cards) via ko-Fi. But I've now chosen PayPal anyway because it's easier.
