### ISSUE TITLE
App version issue

### ISSUE THREAD

**Issue by eloffmarijan** [ImranR98/Obtainium#137]
In obtainium, filen app shows i'm on the latest version but i'm not, in their github page its different.
Check: https://github.com/FilenCloudDienste/filen-mobile
![Screenshot_20221205-190812](https://user-images.githubusercontent.com/101601874/205651095-ff4b085c-2cec-4b41-b98d-cf8a72a98874.png)
![Screenshot_20221205-190933_Bromite](https://user-images.githubusercontent.com/101601874/205651117-85887fa4-bfa7-4ee6-90d7-8697efdba952.png)

**Comment by ImranR98** [comment]
This is a weird one. Although the releases webpage shows the latest version, the GitHub API does not list it: https://api.github.com/repos/FilenCloudDienste/filen-mobile/releases
Not sure if this is a bug in the API or if there's some missing option that needs to be used.

Weirdly, asking for the latest release only does work: https://api.github.com/repos/FilenCloudDienste/filen-mobile/releases/latest
But that direct approach can't be used as the fallback to older releases option wouldn't work.

The solution might be to make 2 API requests - one to `/latest` and one for the whole list, but this would be wasteful (the API has a rate limit).

**Comment by eloffmarijan** [comment]
Thanks, so I have to manually download from their github page. Is this a github problem or filen's developer side problem.

**Comment by ImranR98** [comment]
I would say it's a GitHub problem, but that's just a guess. Not something worth accommodating in Obtainium if it's only affecting this one App (I couldn't find any others), due to the mentioned issues (either removing the fallback option or doubling the number of API calls). Will reopen the issue if it turns out to be more widespread.
