### ISSUE TITLE
Import/Export not working on Lineageos 20 (Android 13)

### ISSUE THREAD

**Issue by marfuscha** [ImranR98/Obtainium#1377]
Android - rooted Lineageos 20 on OnePlus 6T without Google Services.

Installed latest Obtainium (F-Droid tested and github version tested with same results).

Issue description
1. Try to export settings --> tap on "import/export" field. New window is shown with options: location for export / Obtainium-Import  and (geyed out) Obtainium-Export.
2.  try to select export location: tap on it, folder manager app opens. Selecting the folder (for example "Downloads"). At the bottom, the button "use this folder" is active - so i click on this to use the selected folder.
3.  new message appears: are you sure you want Obtainium to get access to this folder? --> yes.
4. immediately i am back again on main Obtainium screen. 
5. Click again on "Import/Export" --> export button still greyed out. If i want to select the export path again, same story goes on (as if it was never selected).

This selection of custom folders work in other apps - but not in Obtainium on LineageOs. I am still not sure whether this is an OS issue or App-issue. Hope it can be solved.
A way around would be if there is a standard folder which is pre-defined and "work" out of the box. Then even if the "customize" option is not working i maybe will be able to export / import the settings.

Then i tried to import the settings (found a github file for Obtainium (JSON-File) with predefined adjustments. But it is not accepting the file. I click on it - and Obtainium opens the main screen - nothing happens. Nothing imported.

Hope this bug can be fixed. Wonderful SW. I never used it on previous LineageOS versions. Just started now.

**Comment by ImranR98** [comment]
This is likely due to #1309. You can subscribe to that issue, closing this one (will reopen if needed).

**Comment by DJCrashdummy** [comment]
this is an "app issue" and i'm pretty sure related to resp. the complement to #1309 if not a duplicate.

@marfuscha are you sure the export really does not work...? for me the export still works, but it may be due to the fact that i granted the permissions before upgrading to 1.0.2. :thinking:

**Comment by marfuscha** [comment]
> this is an "app issue" and i'm pretty sure related to resp. the complement to #1309 if not a duplicate.
> 
> @marfuscha are you sure the export really does not work...? for me the export still works, but it may be due to the fact that i granted the permissions before upgrading to 1.0.2. 🤔

Sure, nothing was exported. I checkef thid
