### ISSUE TITLE
Mark as updated not working

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#138]
Title describes issue. 
Since 0.8.2 
I have an app that only has older releases on github but I want to watch it for Guthub releases, so I leave it in obtainium.
But since updating Obtainium, it's showing as update needed persistently.

**Comment by ImranR98** [comment]
Mark as update now only works for Apps whose versions cannot reliably be detected (see #132), so for most Apps that button will have no effect (the wording has been updated to reflect this). In your case, if the App is installed and has a "reliable" version format both on the source and the OS level, then "mark as update" won't work. Instead you can add the App as "track-only".
