### ISSUE TITLE
Aurora Store/gitlab apps update version differs in normal and track-only modes

### ISSUE THREAD

**Issue by jayb-g** [ImranR98/Obtainium#1381]
**Prerequisites**
Install aurora store version older than currently latest version (older than 4.4.1 as of now)

**Describe the bug**
In track-only mode, it shows the update being 4.4.1 but as soon as the track-only toggle is turned off, it goes back to showing currently installed version as the latest one. This results into not being able to update to latest version. Not sure if this is Aurora/gitlab apps specific or generic issue. I've already tried removing cache but that didn't seem to have any effect.

**To Reproduce**

1. After installation as mentioned in prereqs above, edit the app config in obtanium and change it to track only mode.
2. Now it should show the latest update version (4.4.1 as of now) but you won't be able to install since its track only. 
3. Remove track only mode and it goes back to showing currently installed version as the latest version.

**Screenshots and Logs**
Track-only mode:
![](https://i.postimg.cc/05Y2Z3pT/Screenshot-20240208-213717-1.png)

After removing track-only mode:
![](https://i.postimg.cc/BZpfjG5n/Screenshot-20240208-213816-1.png)

**Please complete the following information:**
 - Device: [ Pixel 7 ]
 - OS: [ GrapheneOS ]
 - Obtainium Version: [1.0.2]

**Additional context**

**Comment by ImranR98** [comment]
Track only mode has less strict requirements as Obtainium only looks for the version string, it doesn't need actual APKs. That's why track-only mode works fine. When you disable track-only mode, it tries and fails to find APKs - this is a known issue with Aurora (search for Aurora in the issues tab - there are several).

**Comment by jayb-g** [comment]
@ImranR98 went through issues but it doesn't seem like unfixable since if obtanium is able to extract an older version, why not most recent version?(especially in case of aurora store?

After checking for differences in releases for 4.3.5 and subsequent ones, the difference is that 4.3.5 release had been attached but not released under _packages_ on gitlab; where's subsequent releases up to 4.4.1 are released under _packages_  and not as attachments. The download link for Aurora latest version is https://auroraoss.com/AuroraStore/Stable/AuroraStore_4.4.1.apk. Not sure why it would be a problem for obtanium to get the apk; even though I have provided the gitlab API Key.

![](https://i.postimg.cc/FFSwv1RB/Screenshot-20240209-102805-1.png)

![](https://i.postimg.cc/mrc8S615/Screenshot-20240209-102811-1.png)

![](https://i.postimg.cc/wjrk3c4c/Screenshot-20240209-102816-1.png)

**Comment by ImranR98** [comment]
Without the GitLab API key, Obtainium wouldn't even know that there is an APK link that goes to the Aurora website. Once we have the link from GitLab, we still need to visit that link and for some reason the Aurora website blocks our request. It likely has to do with headers, but you can't set custom headers with the GitLab source.

I would recommend adding this Aurora page directly as an HTML source and playing around with the headers to see if you can find something that it will accept: https://auroraoss.com/AuroraStore/Stable/

**Comment by jayb-g** [comment]
> Once we have the link from GitLab, we still need to visit that link and for some reason the Aurora website blocks our request.

Its same if I try adding https://auroraoss.com/AuroraStore/Stable/ to obtanium. Gives forbidden error.

**Comment by DwainZwerg** [comment]
Hello @jayb-g ,
According to https://gitlab.com/AuroraOSS/AuroraStore/-/issues/1052#note_1778388859, the Aurora Store devs have fixed the problem. The download of AuroraStore should work normally again.

**Comment by jayb-g** [comment]
@DwainZwerg Although Obtainium still shows 4.4.1 as installed and (older version)4.3.5 as an update. Might be related to #920.

When removing 'fall back to older version' it shows 'no apk'

**Comment by DwainZwerg** [comment]
Hello @jayb-g ,
do you use GitLab-Token? If not, use it. If you are using it and Obtainium does not show you the update, you should delete the app from Obtainium and add it again. If it still doesn't work, it's an unknown behaviour, and I'm not sure if it's auroraoss.com's side or Obtainium. We are also in the process of adding a general feature to better retrieve updates from sites that are protected by Cloudflare.
#920 should actually have nothing to do with this, because it's about a problem with the F-Droid-API.
@ImranR98 @Disqu3-mirOir-qt for acknowledgement.

**Comment by jayb-g** [comment]
@DwainZwerg Got it. Works fine with the token
