### ISSUE TITLE
Latest version is not detected with GitLab

### ISSUE THREAD

**Issue by huubert** [ImranR98/Obtainium#1382]
**Describe the bug**
Add this link: https://gitlab.com/AuroraOSS/AuroraStore/
Latest version detected will be 4.3.5, instead of 4.4.1

**Please complete the following information:**
 - Obtainium Version: 1.0.2

**Comment by ImranR98** [comment]
Search through existing issues before adding new ones.

**Comment by huubert** [comment]
Sorry

**Comment by DwainZwerg** [comment]
Hello @huubert  ,
According to https://gitlab.com/AuroraOSS/AuroraStore/-/issues/1052#note_1778388859, the Aurora Store devs have fixed the problem. The download of AuroraStore should work normally again.
