### ISSUE TITLE
(since last release) Error checking updates: late initialization error

### ISSUE THREAD

**Issue by NathanC** [ImranR98/Obtainium#139]
Ever since the last Obtainium release, I'm periodically getting this notification:

###  Notification title: 
```
errorCheckingUpdates
```

### Notification body:
```
LateInitializationError: Field '_locale@(redacted by me: 9 digit int)' has not been initialized
```

### Notification channel:

It's coming from the "Error Checking for Updates" channel

-----

I'm using Graphene OS, Android 13. Let me know if you need any more info!

**Comment by NathanC** [comment]
This was reported before I updated to [v0.8.3-beta](https://github.com/ImranR98/Obtainium/releases/tag/v0.8.3-beta). I do not know if the issue is still present, don't have data either way yet.

**Comment by NathanC** [comment]
Okay, happened again, still an issue in 0.8.3

**Comment by ImranR98** [comment]
Should be fixed in 0.8.4

**Comment by eloffmarijan** [comment]
Still on 0.8.4![Screenshot_20221206-200240_Bromite](https://user-images.githubusercontent.com/101601874/205939723-199f9312-d5cf-4a0e-9297-7155b3f86738.png)

**Comment by S7venLights** [comment]
I also get that error, can send logs if you like

**Comment by rak-rak** [comment]
Im also getting this error in 0.8.3 and 0.8.4 on several devices:

"errorCheckingUpdates
LateInitializationError: Field '_locale@176425997' has not been initialized."

**Comment by Joshndroid** [comment]
Can confirm that I am getting this on both 0.8.3 and 0.8.4.. It doesn't seem to actually affect anything. I do seem to see it randomly when i wake the device up and it must start an update check in the background.

**Comment by ImranR98** [comment]
Should be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.5-beta

**Comment by NaeemBolchhi** [comment]
![Screenshot_20240510-041542_Obtainium](https://github.com/ImranR98/Obtainium/assets/42773187/681847fc-f7f7-471e-b143-50b135c32458)

Facing this in 1.1.7. On DerpFest A14, not currently logged into Play Store, in case that's relevant.

@ImranR98
