### ISSUE TITLE
External Storage Exception When Importing

### ISSUE THREAD

**Issue by Nanianmichaels** [ImranR98/Obtainium#1391]
**Prerequisites**
 
 

I have checked both existing issues and the Obtanium Wiki

**Describe the bug**

As informed by @DJCrashdummy on #1309 (more specifically here: https://github.com/ImranR98/Obtainium/issues/1309#issuecomment-1929861814), when using the Import function the app will give the error "PlatformException(read_external_storage_denied, User did not allow reading external storage, null, null)".

I have enabled the Export folder, and have exported the settings, I just can't import them.

**To Reproduce**
 Steps to reproduce the behavior:
1. Go to 'Import/Export'
2. Tap on 'Obtanium Import'
3. See error 

**Screenshots and Logs**

Cannot access that folder with my current file system app. Please advise of an appropriate app to retrieve logs, if necessary.

**Please complete the following information:**
 - Device:  Motorola G100
 - OS:  Stock (Android 12)
 - Obtainium Version:  1.02

**Additional context**

Also reproducible on Waydroid. Same error occurs on both an updated install (G100, started with 1.01) and non-updated one (Waydroid, 1.02 directly installed).

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.3
