### ISSUE TITLE
How to download and update Krita

### ISSUE THREAD

**Issue by guaje** [ImranR98/Obtainium#1392]
**Prerequisites**
- [x] Please ensure your request is not part of an existing issue.
- [x] Please ensure you have checked the Obtainium Wiki.

**Describe the feature**

I'm looking for advice on how to download and check for updates for Krita obtained from this link:

https://download.kde.org/Attic/krita/

So far, I have tried with an `HTML` source and different variations of the following regex:

`([0-9]+\.)*[0-9]+\/krita-arm64-v8a-([0-9]+\.)*[0-9]+\-release-signed.apk`

But always get messages like:

- `Could not find a suitable release`
- `Could not determine release version`

Any suggestions/ideas on how to add this to Obtainium?

PS.: I'm using v1.0.2 on a Samsung Galaxy Tab S8+.

**Describe alternatives you've considered (if applicable)**

Tried to look for inspiration/similar configurations in https://apps.obtainium.imranr.dev/, but couldn't find any.

**Additional context**

**Comment by ImranR98** [comment]
Try this (opens in Obtainium): <a href="http://apps.obtainium.imranr.dev/redirect.html?r=obtainium://app/%7B%22id%22%3A%22org.krita%22%2C%22url%22%3A%22https%3A%2F%2Fdownload.kde.org%2FAttic%2Fkrita%22%2C%22author%22%3A%22download.kde.org%22%2C%22name%22%3A%22Krita%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22krita%2F(%5B0-9%5D%2B%5C%5C%5C%5C.)*%5B0-9%5D%2B%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22partialAPKHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22krita%2F(%5B%5E%2F%5D%2B)%2F%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%221%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%7D">Krita</a>

**Comment by raldone01** [comment]
This always downloaded the wrong arch for me x86.

To get the correct one you can add:

`krita-arm64-v8a-[\d.]+-release`

Also the 5.2.6 release has the wrong version number 5.2.8.
