### ISSUE TITLE
Shows old veraion

### ISSUE THREAD

**Issue by PitchAbyss** [ImranR98/Obtainium#1397]
I am trying to add aurora store even though 4.4.1 is released obtanium shows old version

![Screenshot_20240215_151120_Chrome.jpg](https://github.com/ImranR98/Obtainium/assets/13099434/5cdaec92-5f0a-42b7-8299-4797c5d9f103)

**Comment by DwainZwerg** [comment]
Hello @PitchAbyss ,
this is a known bug. New versions are no longer uploaded to GitLab, but link to [auroraoss.com](https://auroraoss.com). However, Obtainium cannot access auroraoss.com because cloudflare blocks this. A possible workaround is to enable the new auto-update option in the AuroraStore and, if you don't want to track the changes by other means, subscribe to the GitHub releases as an rss feed. You can also add the [F-Droid source](https://f-droid.org/en/packages/com.aurora.store/) for tracking.

**Comment by PitchAbyss** [comment]
> Hello @PitchAbyss , this is a known bug. New versions are no longer uploaded to GitLab, but link to [auroraoss.com](https://auroraoss.com). However, Obtainium cannot access auroraoss.com because cloudflare blocks this. A possible workaround is to enable the new auto-update option in the AuroraStore and, if you don't want to track the changes by other means, subscribe to the GitHub releases as an rss feed. You can also add the [F-Droid source](https://f-droid.org/en/packages/com.aurora.store/) for tracking.

i tried with fdroid links but i guess they are old releases everywhere

**Comment by DwainZwerg** [comment]
Yes, they haven't uploaded a new version yet. But as you know, they need something to check new versions of apps.

**Comment by ImranR98** [comment]
Thanks for dealing with these duplicates @DwainZwerg, people should really be searching before opening new issues.

**Comment by DwainZwerg** [comment]
Hello @PitchAbyss ,
According to https://gitlab.com/AuroraOSS/AuroraStore/-/issues/1052#note_1778388859, the Aurora Store devs have fixed the problem. The download of AuroraStore should work normally again.

**Comment by PitchAbyss** [comment]
> Hello @PitchAbyss ,
> According to https://gitlab.com/AuroraOSS/AuroraStore/-/issues/1052#note_1778388859, the Aurora Store devs have fixed the problem. The download of AuroraStore should work normally again.

Thankyou so much sir for the update

**Comment by PitchAbyss** [comment]
> Hello @PitchAbyss ,
> According to https://gitlab.com/AuroraOSS/AuroraStore/-/issues/1052#note_1778388859, the Aurora Store devs have fixed the problem. The download of AuroraStore should work normally again.

I dnt know if its fixed 


![Screenshot_20240225_090523.jpg](https://github.com/ImranR98/Obtainium/assets/13099434/76fcb11e-1221-49d1-b633-ea3bfc615ac8)
