### ISSUE TITLE
Difficulty with 3rd party fdroid repo

### ISSUE THREAD

**Issue by pressRtowin** [ImranR98/Obtainium#1399]
Trying to add a third party fdroid repo and it doesn't seem to be working as I expected it to. 

Specifically trying to use Chimbori's own repo for Hermit which can be found here: https://apps.chimbori.com/

After entering the repo URL, setting the override source to "F-Droid Third-Party Repo" and entering just about every possible app name or ID, I only get a "not found" error. Not sure if something's broken or I'm doing something wrong.

**Comment by ImranR98** [comment]
According to the warning at the bottom of that page it uses a new kind of f-droid repo. I didn't know that there was a new type of f-droid repo so I'll need to look into it and add support for it in Obtanium.

**Comment by ImranR98** [comment]
Oh, I just read the warning and made a guess since there doesn't seem to be an 'index.xml' hosted there which I'd expect to see (for all I know, index.xml might be the "new format" and the issue is something else). Needs looking into.

**Comment by ImranR98** [comment]
Ah, I see the problem now. The actual URL to use is https://apps.chimbori.com/fdroid/repo

I'll improve the code to automatically add the `/fdroid/repo` part if the original query fails.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.3
