### ISSUE TITLE
"automagically" discover sources

### ISSUE THREAD

**Issue by asanghc** [ImranR98/Obtainium#1401]
ability to discover a source and/or alternate sources from app identifier (example "com.xbit.bitwarden")
ability to discover a source and/or alternate sources from already installed apps
you could then select the preferred source to use [(see 1402)](https://github.com/ImranR98/Obtainium/issues/1402)

**Comment by ImranR98** [comment]
There is already a search function for some sources. For most of them (except F-Droid), the search isn't guaranteed to always provide valid results. For example in GitHub search, you'll get a list of repos, but not all of them will be Android apps and not all Android app repos will have valid release APKs, so the user still needs to be able to recognize what they want. Even for F-Droid, there would be issues with APK signatures conflicting.

So in general, search requires the user to know what they're doing. It seems like you're suggesting an automated search which grabs a list of the user's installed apps, searches for them on supported sources, and adds them automatically. Without fixing the issues above, this feature would be too error prone - probably failing for most apps.
