### ISSUE TITLE
allow multiple prioritized sources

### ISSUE THREAD

**Issue by asanghc** [ImranR98/Obtainium#1402]
First, I'd like to state just how great an app obtainium is. It is truely awesome and has quickly become a necessity.
Thank you so much for this app.

It would be even greater if, we could specify multiple sources and priority between them (Will app signatures make this problematic?)

1-github,2f-droid,3-izzy,4aptoide,5apkpure, etc...

Maybe, eventually, even able to discover any/all sources? (see [this other issue](https://github.com/ImranR98/Obtainium/issues/1401))

**Comment by ImranR98** [comment]
This would add unnecessary complexity and would likely not be reliable. Each Source has different available settings, limitations, and quirks and things would get messy trying to make them work as one unit.

For example:
- GitHub gives you access to past releases, beta/non-beta flags, etc. but has no reliable way to extract App IDs or version numbers (tags may or may not correspond to actual versions).
- F-Droid gives you easy access to version names and App IDs, but the API is very limited and has been unreliable in the past when it comes to figuring out which release is the latest/recommended one.
- Apps often release earlier on GitHub, and show up on F-Droid a few days later.
- So trying to figure out when to use GitHub and when to fallback to F-Droid would be tough (also GitHub has it's own "fallback to older releases" that would now have to work differently).
- The same app may be signed with a different key on different sources.
- Etc. - a lot of issues like that are likely to come up.

**Comment by DwainZwerg** [comment]
@ImranR98 ,
the idea would not be that Obtainium decides which source to use and which to fallback to, but that you can enter an app as multiple apps from different sources in Obtainium if you just want to track them. I don't mind if I get K-9Mail five times, but always from different sources.

**Comment by ImranR98** [comment]
@DwainZwerg old issue but just saw your comment. You can already do this - apps added as track only do not use the real app ID so you can add the same one multiple times.
