### ISSUE TITLE
desktop accessible app collection manager

### ISSUE THREAD

**Issue by asanghc** [ImranR98/Obtainium#1403]
We need a desktop accessible manager that would facilitate the creation and maintaining of multiple obtainium application lists. Think a GUI to paste source URLs and drag and drop between lists, toggle between different sources...
It should be web-based so it can be used from any Desktop (and even mobile) OS.

This isn't exactly a feature/enhancement request I guess... It is an idea for a partner tool app manager.
I'm guessing at least some of the code could be shared from the obtainium app though.

I'm constantly importing/exporting and merging json files and losing my mind.
A mobile interface is just not practical for the initial setup.
We do it now, because there just isn't anything better yet.
If I'm the only user that feels this way, please trash this request.

As a less convenient/flexible option, there is [this](https://github.com/ImranR98/Obtainium/issues/452)

Thanks for your great work!!

**Comment by ImranR98** [comment]
This isn't an bug/enhancement/issue, the discussions tab would be a better place for it. Maybe post there with more details (I don't think I'll work on a tool like this, but maybe someone will contribute).
