### ISSUE TITLE
How to add Source from www.celsoazevedo.com

### ISSUE THREAD

**Issue by ulil-azmy** [ImranR98/Obtainium#1404]
https://www.celsoazevedo.com/files/android/google-camera/dev-shamim/

what i wanna do is to always get latest version from developer called shamim, here it all version from his release.

and what kind of additional options/config should i enabled in obtainium tu acoomplish this thing?

**Comment by ImranR98** [comment]
Please read the issue templates and search for existing issues (#1182).
