### ISSUE TITLE
Add Google Play Badge to README.md if authorised under licensing conditions

### ISSUE THREAD

**Issue by DwainZwerg** [ImranR98/Obtainium#1406]
**Prerequisites**
- [x] Please ensure your request is not part of an existing issue
- [x] Please ensure you have checked the Obtainium Wiki.

**Describe the feature**
Add Google Play Badge to README.md if authorised under licensing conditions. Here is the page to create the badge: https://play.google.com/intl/en_us/badge If I knew that this was okay under licence terms, I would simply create a PR myself.

**Comment by ImranR98** [comment]
Obtainium isn't on google play though

**Comment by DwainZwerg** [comment]
But Obtainium used to be on Google Play, or am I wrong?

**Comment by ImranR98** [comment]
No, had to remove it because there was some permission Obtainium uses that they don't allow (i think it was either the apk install permission, or maybe the query packages permission).
