### ISSUE TITLE
Issues in update notification title

### ISSUE THREAD

**Issue by ImranR98** [ImranR98/Obtainium#141]
![Screenshot_20221208-173955-01](https://user-images.githubusercontent.com/30463115/206582325-5880e88e-fb11-4b58-8b0d-e26f9f5d03d8.jpeg)

- There should be a number in place of {}
- "updates" not "updated".

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.8.7-beta

**Comment by eloffmarijan** [comment]
In the app log section too.
![Screenshot_20221211-203234](https://user-images.githubusercontent.com/101601874/206911379-66edad74-7695-4c92-8a02-90f91db7730f.png)

**Comment by ImranR98** [comment]
> In the app logs section too. ![Screenshot_20221211-203234](https://user-images.githubusercontent.com/101601874/206911379-66edad74-7695-4c92-8a02-90f91db7730f.png)

https://github.com/ImranR98/Obtainium/releases/tag/v0.8.9-beta
