### ISSUE TITLE
Override source type option missing for github URLS

### ISSUE THREAD

**Issue by oniGino** [ImranR98/Obtainium#1420]
Need ability to override source type on a github URL and force HTML or direct download

example:

https://github.com/FurTrader/OverkillSolarBMS/tree/master/OKS_Mobile_App_APK_files

**Comment by ImranR98** [comment]
I'm not sure there's a point to this - even if you could use the HTML source for GitHub, it wouldn't work since all the content on the GitHub page is loaded in with JavaScript, which Obtainium cannot scrape.

**Comment by ImranR98** [comment]
Adding this feature is simple, but I'm not sure there's a good use case for it. Closing the issue for now as it would just add confusion (will add it if anyone has a good use case).

**Comment by oniGino** [comment]
> I'm not sure there's a point to this - even if you could use the HTML source for GitHub, it wouldn't work since all the content on the GitHub page is loaded in with JavaScript, which Obtainium cannot scrape.

Fair enough , in that case, I don't have much to say as far as how to solve the problem , in a perfect world they would use versioned releases , but that's unfortunately not up to me..

Can you think if a work around that might work for me here ?

**Comment by ImranR98** [comment]
Actually hold on - the JavaScript thing was an assumption based on past experience with other pages on GitHub. This one does have some content loaded directly, including the APK links.

**Comment by ImranR98** [comment]
It still doesn't seem possible to do this for your specific case. When I send a request to GitHub with the right headers in Curl, it sends back a page that does contain the APK links. But when I do it in the app (even with the headers), it doesn't. Looks like the headers I put in are being overwritten instead of merged. Not clear how to fix it with the current HTTP library.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.4
