### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by Sami32** [ImranR98/Obtainium#1424]
![Screenshot_2024-02-26-13-10-37-353_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/18471069/ce732fe5-805d-4628-939b-2ae2a97d98ce)

**To Reproduce**
1. Go to 'Add App'
2. Tap on '+'
3. Enter an App source URL that is already installed
4. Then when the option to update it highlight, select it and this error message should appear

**Please complete the following information:**
 - Device: Xiaomi Redmi Note 4
 - OS: Android 7.0
 - Obtainium Version: 1.0.3

**Additional context**
After adding a new App this is already installed and trying to update this App this error message appear.
Restarting Obtainum "fix" it; that make Obtainium finally detect the already installed App and not enabling "Update" anymore.

**Comment by ImranR98** [comment]
Just to make things clearer for me, could you:
1. Share the app configuration as an HTML link (to do so, go to the apps page, long-press on the app, click the "3 dots" button at the bottom of the page, then the "export" button on the right of the popup menu).
2. Share a screen recording of the exact steps you take to get this error.

**Comment by Sami32** [comment]
<p>These links work on devices with Obtainium installed:</p>  <ul>     <li><a href="obtainium://app/%7B%22id%22%3A%22com.kunzisoft.keepass.libre%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2FKunzisoft%2FKeePassDX%22%2C%22author%22%3A%22Kunzisoft%22%2C%22name%22%3A%22KeePassDX%22%2C%22preferredApkIndex%22%3A1%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Afalse%2C%5C%22fallbackToOlderReleases%5C%22%3Afalse%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Atrue%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22useLatestAssetDateAsReleaseDate%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%7D">KeePassDX</a></li> </ul>  <p><a href="https://github.com/ImranR98/Obtainium">About</a></p>

**Comment by Sami32** [comment]
The above is what i get using the "export" data in HTML format.

**Comment by ImranR98** [comment]
Thanks, this will be fixed in the next release.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.4
