### ISSUE TITLE
可以添加https://liteapks.com/吗

### ISSUE THREAD

**Issue by Tree-New-Beee** [ImranR98/Obtainium#1428]
**Prerequisites**

**Describe the feature**

**Describe alternatives you've considered (if applicable)**

**Additional context**

**Comment by DwainZwerg** [comment]
Could you answer the following questions: Use the site HTML instead of JavaScript, or has the site an API? Where can I find the API?

**Comment by ImranR98** [comment]
Also a duplicate of #1239 (guess they've changed the design since then which is good).

**Comment by DwainZwerg** [comment]
In the meantime, the version extraction is working again or is still not working (see https://github.com/ImranR98/Obtainium/issues/1510#issuecomment-2030531069).
