### ISSUE TITLE
Unauthorised 

### ISSUE THREAD

**Issue by mjain234** [ImranR98/Obtainium#143]
I have open the app after a long time but Its just suddenly started showing me "unauthorised" and I am not able to update any of the app. 

Check this video:
https://user-images.githubusercontent.com/70900505/206715632-70fdb918-4622-44e8-9600-5dd96d27402a.mp4

**Comment by ImranR98** [comment]
Have you added a GitHub PAT token on the settings page?

**Comment by mjain234** [comment]
> Have you added a GitHub PAT token on the settings page?

Yaah, i removed it and it works fine for now, but it didn't give problem before.

**Comment by ImranR98** [comment]
Most likely an invalid or expired PAT.

**Comment by mjain234** [comment]
> Most likely an invalid or expired PAT.

Ok, then it would have been expired as the token only valid for 30 days as I have set it while creating GitHub token. Thanks for clarifying 💫
