### ISSUE TITLE
Weekly / biweekly / monthly update options for background update checking interval option

### ISSUE THREAD

**Issue by soredake** [ImranR98/Obtainium#1431]
**Describe the feature**
It would be nice to have weekly / biweekly / monthly update options for background update checking interval option so when https://github.com/ImranR98/Obtainium/issues/1295 will be implemented I can set certain apps (like youtube revaneced) to be updated monthly.

**Describe alternatives you've considered (if applicable)**
Not having these options.

**Additional context**

**Comment by DwainZwerg** [comment]
Why didn't you just edit your old issue? This is practically a duplicate of your old issue?

**Comment by soredake** [comment]
> This is practically a duplicate of your old issue.

In what way it is a duplicate?

This request is about adding "weekly/monthly/etc" update options, the https://github.com/ImranR98/Obtainium/issues/1295 is about adding per-app update frequency.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.4
