### ISSUE TITLE
Backup export suggestion 

### ISSUE THREAD

**Issue by hotice52** [ImranR98/Obtainium#1432]
Is it possible, instead of creating a new file every time the setting is changed, to overwrite the first file created every time the link/app addition/removal settings change?

**Comment by ImranR98** [comment]
Right now we create a new file because the filename contains the export date. This could be modified so that a constant filename is used (and the export date is listed inside the file). But I'm curious as to why you need this?

**Comment by DwainZwerg** [comment]
If so, then you should have the choice. I think the current backup method is much better.

**Comment by hotice52** [comment]
> Right now we create a new file because the filename contains the export date. This could be modified so that a constant filename is used (and the export date is listed inside the file). But I'm curious as to why you need this?

So that I don't fill up the folder on my phone and Google drive and have a multitude of files when I need to restore the backup

**Comment by hotice52** [comment]
> Right now we create a new file because the filename contains the export date. This could be modified so that a constant filename is used (and the export date is listed inside the file). But I'm curious as to why you need this?

So that I don't fill up the folder on my phone and Google drive and have a multitude of files when I need to restore the backup

**Comment by hotice52** [comment]
> If so, then you should have the choice. I think the current backup method is much better.

Yes, well I mean to give the possibility of choice, not to replace the method

**Comment by hotice52** [comment]
> If so, then you should have the choice. I think the current backup method is much better.

Yes, of course I intend to give the possibility of choosing not to replace the backup method

**Comment by hotice52** [comment]
> If so, then you should have the choice. I think the current backup method is much better.

Yes, of course I intend to give the possibility of choosing not to replace the backup method

**Comment by ImranR98** [comment]
> So that I don't fill up the folder on my phone and Google drive and have a multitude of files when I need to restore the backup

This shouldn't happen. When Obtainium makes an automatic backup, it deletes the previous auto-backup. Only manual backups are kept.
