### ISSUE TITLE
Keep wanting update an already up to date App

### ISSUE THREAD

**Issue by Sami32** [ImranR98/Obtainium#1437]
![IMG_20240229_141805](https://github.com/ImranR98/Obtainium/assets/18471069/8c14f241-ca6e-48cf-ade8-d7e478ef716b)
![IMG_20240229_141712](https://github.com/ImranR98/Obtainium/assets/18471069/e922967f-fd8d-427e-8ae4-2df0d5958364)

**Please complete the following information:**
 - Device: Xiaomi Redmi Note 4
 - OS: Google Android 7.0
 - Obtainium Version: 1.0.3

Did i missed something?
Since i just discovered your great App i could have misunderstood some of its settings, so please feel free to close this issue if it's only come from an incorrect use.

**Comment by DwainZwerg** [comment]
You should toggle „Include prerelease“ (first point in the settings) on because that releases are prerelease.

**Comment by ImranR98** [comment]
Yep, @DwainZwerg is right. Closing.

**Comment by Sami32** [comment]
But i don't want pre-releases and its not tagged as such on GitHub.

Please, can you elaborate?
![Uploading Screenshot_2024-03-01-13-15-28-975_net.waterfox.android.release.jpg…]()

**Comment by DwainZwerg** [comment]
I could swear that the last time I looked, version 1.8.17 was tagged as pre-release. But this couldn't be possible? Otherwise, it might be good to enable "Verify the 'latest tag'"?

**Comment by Sami32** [comment]
Nope...it has never been tagged at all, so no "Pre-release" or "Latest" tag, that is why i post my config at first.

Well, i'm just testing your App, so i've still to discover its limitations.
