### ISSUE TITLE
Apkpure truncates long version names, causing Obtainium to incorrectly read version

### ISSUE THREAD

**Issue by 9t8** [ImranR98/Obtainium#1443]
**Describe the bug**

Apkpure truncates version names at 30 or 40 characters. This causes Obtanium always to think the online latest version differs from the installed version and say that a new version is available.

**To Reproduce**

The latest version of the Frameskip app has a long version name. [Install it from Apkpure.](https://apkpure.net/frameskip-video-timing-tool/co.azurestudios.frameskip) Obtainium should always think there is a newer version.

 - Device: Samsung A12
 - OS: Android
 - Obtainium Version: 1.0.4

**Comment by ImranR98** [comment]
Not much we can do to get the full version name. You can just turn off the "reconcile version..." toggle in the settings for this app - then Obtainium won't try to compare the real OS version with the one from APKPure.

**Comment by 9t8** [comment]
Maybe Obtainium could truncate Apkpure versions at 30 characters for comparisons?
