### ISSUE TITLE
Aurora Store via Gitlab - the latest in Obtainium is 4.3.5 ?

### ISSUE THREAD

**Issue by acress1** [ImranR98/Obtainium#1450]
Hi all,

Aurora Store just published a week ago their 4.4.2 version (after 4.4.1 and 4.4.0), but in Obtainium, the latest available version is still 4.3.5.
I checked the settings and I believe everything is right.
Maybe there is something to check?

Thanks,
cress

**Comment by DwainZwerg** [comment]
Hallo @acress1 ,
You are probably not using a GitLab token. Either you add a GitLab token or you wait for the next release of Obtanium, because then it will also be possible without a GitLab token (https://github.com/ImranR98/Obtainium/pull/1438#issuecomment-1975324096).

**Comment by acress1** [comment]
Hi, yes sorry I forgot to enter my token..  Thanks a lot !
