### ISSUE TITLE
Help extracting version from revanced-apks

### ISSUE THREAD

**Issue by vufly** [ImranR98/Obtainium#1452]
**Describe the bug**
I'm not sure if this is a bug. I'm setting up VSCO revanced from [GitHub](https://github.com/revanced-apks/build-apps/releases/tag/v2024.03.02-2041)

For version string extraction regex, I used `/vsco-revanced-v(\d+)-arm64-v8a\.apk/` but it doesn't work. The app kept promting that it could not determine release version.

I cannot find on wiki exactly what is the input to run the regex through, so my regex could be wrong. Very appreciate if you can help me to correct it. Thank you.

**Please complete the following information:**
 - Obtainium Version: 1.0.4

**Comment by DarkCrypt** [comment]
You can add this app without a regex or filter.

App Source URL -> Override Source: GitHub or None -> Toggle your preferences -> Add -> Pick an APK -> Continue.

**Comment by vufly** [comment]
@DarkCrypt Yes I can add that app, but I want to narrow down the results to 1 so that I don't have to select the APK. Also I want to extract the exact version from the APK name to avoid false update notification.

**Comment by ImranR98** [comment]
> I believe you have to remove the forward slashes at the beginning and end

Yep, the regex provided above works.

> Also I want to extract the exact version from the APK name to avoid false update notification.

There's no way to do this since we use tag names as versions, not APKs. You can just turn off the "Reconcile version string..." toggle for this app, then use the tick button to mark it as updated (only needs to be done once).
