### ISSUE TITLE
Cannot add Apktool M HTML page as source: "Forbidden"

### ISSUE THREAD

**Issue by JinglingB** [ImranR98/Obtainium#1453]
**Describe the bug**
Attempting to add the Apktool M webpage, https://maximoff.su/apktool/?lang=en, as a source just brings up a message 

**To Reproduce**
1. Go to 'Add App'
2. Put `https://maximoff.su/apktool/?lang=en`  as the source
3. Tap 'Add'
4. See error: a message saying "Forbidden" appears at the bottom of the screen

No other changes are made to the 'Add App' screen.

**Please complete the following information:**
 - Device: Huawei MatePad 11.5 
 - OS: HarmonyOS 3.1.0 (Android 11-based, I think, but the reported API level is 31)
 - Obtainium Version: 1.0.4

**Additional context**
A `curl "https://maximoff.su/apktool/?lang=en"` on my PC does indeed output

```
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx-reuseport/1.21.1</center>
</body>
</html>
```

However, `curl -H "User-Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36" "https://maximoff.su/apktool/?lang=en"` (which is the same UA Obtainium displays to me as a request header) does output the expected HTML page.

**Comment by DarkCrypt** [comment]
"Forbidden" = Cloudflare.

**Comment by DarkCrypt** [comment]
Cloudflare is a pain in the ass for Obtainium. The good news is Apktool M has a self-updater which works great.

**Comment by DarkCrypt** [comment]
@JinglingB 
I got it to work.

Import App -> [Apktool M](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22ru.maximoff.apktool%22%2C%22url%22%3A%22https%3A%2F%2Fmaximoff.su%2Fapktool%2F%3Flang%3Den%22%2C%22author%22%3A%22maximoff.su%22%2C%22name%22%3A%22Apktool%20M%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22Apktool%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22matchLinksOutsideATags%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%2C%7B%5C%22requestHeader%5C%22%3A%5C%22Cookie%3A%20beget%3Dbegetok%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22partialAPKHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%5C%5C%5Cd%2B%5C%5C%5C%5C.%5C%5C%5C%5Cd%2B%5C%5C%5C%5C.%5C%5C%5C%5Cd%2B-%5C%5C%5C%5Cd%2B%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22Apktool%20M%5C%22%2C%5C%22appAuthor%5C%22%3A%5C%22Maximoff%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22Edit%20any%20APK%20directly%20on%20Android.%5C%22%2C%5C%22refreshBeforeDownload%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3Anull%7D)

**Edit:**
Config stopped working, added a Cookie header to fix it.
