### ISSUE TITLE
Odd: Github APK Filter RexExp can not include the \.apk suffix

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#1456]
Pixel 7
GrapheneOS
Obtainium 1.0.4

[HeliBoard](https://github.com/Helium314/HeliBoard) comes up with three options.  When I try to select one by using:

Filter APKs by Regular Expression: `HeliBoard_.*nouserlib\.apk`

The response is, "Could not find a suitable release".  Same if I just try `nouserlib\.apk`.  But, if I do it with `nouserlib`, it works.

**Comment by ImranR98** [comment]
That's weird - that exact regex works for me. Could you post your full app config?

**Comment by DiagonalArg** [comment]
Well, this is extremely strange.  As mentioned above, I got `nouserlib` to work, but `nouserlib\.apk` did not.  Here, a few days later (and after installing the app), I added `\.apk`again and ... it's not complaining.  

Not sure what to make of this.  I'll reopen if I get trouble later.
