### ISSUE TITLE
Obtanium as a market app

### ISSUE THREAD

**Issue by IlIllIl** [ImranR98/Obtainium#1457]
**Prerequisites**

1. Add market detail url sheme in AndroidManifest.xml and more.
2. Add app id field to track-only app source.

**Describe the feature**

Open the detail page of Obtanium in Obtanium via market://details?id=dev.imranr.obtainium to check a single app updates (including track-only source)

**Describe alternatives you've considered (if applicable)**

**Additional context**

**Comment by ImranR98** [comment]
We already have a protocol to add an app config directly, and one to open the 'Add App' page with the URL filled in. See here: https://apps.obtainium.imranr.dev
