### ISSUE TITLE
Incorrect version detection and missing update notifications

### ISSUE THREAD

**Issue by bluefly000** [ImranR98/Obtainium#146]
device: Pixel 6a running GrapheneOS
app version: 0.8.9

Version detection is incorrect even though the app was installed in Obtainium.
I manually set it to "Mark as Updated", but when Obtainium checks for updates in the background, it reverts back to the original state.

I don't know if this is the cause, but I don't get notifications of updates even when there are updates for the application.
I just received an update for [Tutanota](https://github.com/tutao/tutanota/releases/tag/tutanota-android-release-3.105.9), but Obtainium did not notify me of it.

![Screenshot_20221213-021208](https://user-images.githubusercontent.com/101441707/207110915-f118db87-7629-4706-b7f5-cd85e550be2b.png)
![Screenshot_20221213-020258](https://user-images.githubusercontent.com/101441707/207110940-f68f2359-f4a5-43da-bd78-48f3044e8fc3.png)

**Comment by ImranR98** [comment]
I haven't been able to reproduce the issue you're having with KeePassDX and Geometric Weather, but I have noticed missing notifications. Not sure what the problem is yet, but I'd guess it's because the Flutter plugin that is supposed to detect installed Apps is failing in the background (it's happened before). Weird because it works in the Android emulator.
Anyways, will try to fix and release an update today.

**Comment by ImranR98** [comment]
Please give this version a try and see if it helps (note this is unreleased, so ignore the "update available" for Obtainium):

[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/10213564/app-x86_64-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/10213565/app-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/10213566/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/10213567/app-arm64-v8a-release.zip)

**Comment by bluefly000** [comment]
Thank you. I will test it later and report back whether the problem has been resolved or not.

**Comment by bluefly000** [comment]
I have updated Obtainium to version 0.8.10, but an error occurred when checking for updates in the background.

![Screenshot_20221213-122708](https://user-images.githubusercontent.com/101441707/207219880-fbcec784-9bd7-4385-a65f-b94c33525ecf.png)

**Comment by ImranR98** [comment]
Yep, I get it too. Think I know where the problem is, will update tomorrow.

**Comment by S7venLights** [comment]
I have had the same issues just for my 2 cents. 
Also the 'See changes' option is not displaying anymore

**Comment by ImranR98** [comment]
> Also the 'See changes' option is not displaying anymore

Still there; the "update available" text is also a link to changes (i hoped the underline would be enough of a hint)

**Comment by ImranR98** [comment]
Try this one:

[app-release.zip](https://github.com/ImranR98/Obtainium/files/10222715/app-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/10222717/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/10222718/app-arm64-v8a-release.zip)
[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/10222714/app-x86_64-release.zip)

**Comment by bluefly000** [comment]
I have tested the new version. The version displays in KeePassDX and Geometric Weather were correct when I checked for updates in the background, and I also received a notification of the update.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.8.10-beta
