### ISSUE TITLE
Support for MEGA.io 

### ISSUE THREAD

**Issue by blacktornadog7** [ImranR98/Obtainium#1460]
**Describe the feature**
Support for downloading and updating APKs from shared folders on MEGA.io

**Additional context**
tried downloading using HTML but it didnt work
here is the link: https://mega.nz/folder/b0Fj2QJC#Nhp7jmpBGRlIHENkyJYfXg

(btw: Thank you for creating such an amazing app, tried and searched for something like this for a long time but nothing even comes close, been using it almost since it came out (since beta releases) and everytime it gets even better and better with even more and more features, truly thank you)

**Comment by ImranR98** [comment]
Mega loads everything in with JS so it can't be scraped  - we can reopen this if anyone provides an alternative (like an API w/ usage examples).
