### ISSUE TITLE
The installation buttons on the add apps page are not evenly spaced

### ISSUE THREAD

**Issue by ngocanhtve** [ImranR98/Obtainium#1467]
**Describe the bug**
When adding an app, in github for example, to the step of opening the github page of the application to be added, the bottom sheet will have 4 buttons including edit, three dots, install (text) and delete.

The issue is that they are not evenly spaced and are not aesthetically pleasing.

**To Reproduce**
1. Go to **Add** tab
2. Paste app link into **App source URL** file
3. Press the **Add** button
4. On the app's detailed source page, you will see that the function buttons on the bottom bar are not evenly spaced

**Screenshots and Logs**
![](https://i.imgur.com/yZxZniM.png)

**Please complete the following information:**
 - Device: Sony Xperia 1
 - OS: Crdroid 10.2 - Android 14 UQ1A.240205.004
 - Obtainium Version: 1.0.5

**Comment by ImranR98** [comment]
One issue with centering the 'install' button is that it would require an equal number of buttons on the left and right side - which is not possible with an odd number of buttons (plus the number of buttons differ depending on the app and settings). You could always add empty space in place of a button but that would end up with a max. of 3 "button spaces" taken up on each side, making the Install/Update button much smaller. I also think it's more intuitive to have the delete button isolated on the right, separate from all the others. Plus the aesthetic thing is subjective - I think it looks fine.
