### ISSUE TITLE
Incorrect notification of "Apps Installed"

### ISSUE THREAD

**Issue by ngocanhtve** [ImranR98/Obtainium#1469]
**Describe the bug**
When i finish installing a new application from the **Add** tab, there will be a notification that the **Apps updated**. The problem is that it should have a notification that **Apps installed** instead of updated, right?

**To Reproduce**

1. Install new app through **Add** tab
2. Will see

**Screenshots and Logs**
![](https://i.imgur.com/9dMFUfX.png)

**Please complete the following information:**
 - Device: Sony Xperia 1
 - OS: Crdroid 10.2 - Android 14 UQ1A.240205.004
 - Obtainium Version: v1.0.5

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.6
