### ISSUE TITLE
[Request] Badge to Display on "how to get" page

### ISSUE THREAD

**Issue by rcarteraz** [ImranR98/Obtainium#147]
Can you create a badge with the obtainium logo that is similar to "get it on GitHub" or "get it on f-driod" for obtainium? Is "Obtain with Obtainum" too on the nose? 😆

**Comment by ImranR98** [comment]
Would be nice 🙂, but probably not very useful unless Obtainium could open links made specifically for it. Could be done, but we'd also need a website as a fallback for devices without Obtainium installed (definitely not going to do that).
