### ISSUE TITLE
Doesn't update app if it's on the same release

### ISSUE THREAD

**Issue by rajarshikhatua100** [ImranR98/Obtainium#1471]
the app doesn't see the update if a github repo only updates the app from a single release, so if I make a release in GitHub and don't release the next update in next release but update the app in previous release itself - obtainium doesn't see that, also I saw that those apps does this thing in Pre-release Build, 
see [this](https://github.com/recloudstream/cloudstream/releases) app's pre-release, they currently does this, also I have seen more repos do that. I don't fully understand the things, but if it's a bug- look into the thing, 
if my words are unclear I am open for reply 😊

**Comment by ImranR98** [comment]
You can combine enable these 2 toggles:
- Use release date as version string
- Use latest asset upload as release date

**Comment by rajarshikhatua100** [comment]
thank you
