### ISSUE TITLE
Cannot install brave browser in background

### ISSUE THREAD

**Issue by Zumux** [ImranR98/Obtainium#1472]
**Describe the bug**

I cannot install brave browser in the background. If I initiate the update from the app and keep it open then it will complete, mind you quite slowly (took close to 10 minutes recently). It's been happening for a while but I kept forgetting to report it. Since it started it has only worked in the background maybe once or twice. 

I have never had this issue when updating any other apps in the background, just brave browser. What network  I'm connected to or whether I'm connected to a vpn make no difference. The logs in obtanium don't seem to contain any useful any information, just stuff about BG task started, etc as well as saying it cleared 1 log and such.

**To Reproduce**

1. Wait for obtanium to try to update brave in the background
2. See notifications for issues

**Screenshots and Logs**

![Screenshot_20240313-195012](https://github.com/ImranR98/Obtainium/assets/59784734/13555085-1c55-47fd-8d4b-4c42069c14ec)

**Please complete the following information:**
 - Device:  Pixel 6a
 - OS:  GrpaheneOS
 - Obtainium Version:  v1.0.5

**Additional context**

**Comment by ImranR98** [comment]
Can you check how long the download takes when you do it manually from a browser?
