### ISSUE TITLE
Battery issue

### ISSUE THREAD

**Issue by islam2hamy** [ImranR98/Obtainium#1473]
**Prerequisites**

**Describe the bug**

Hello,

app keep running in background
- Background update checking interval : never
- Enable background updates : disabled

**Please complete the following information:**
 - Device: Radmi note 12
 - OS: HyperOS
 - Obtainium Version: 1.0.4

**Comment by ImranR98** [comment]
To keep background updates reliable, the task runs even when you disable background updates, but it doesn't do anything - it just starts up a background task, realizes that it isn't supposed to do anything, then turns off. This happens every 15 minutes regardless of the interval or other setting.

That said, it shouldn't use up much battery at all. What battery usage stats are you seeing? I'd expect <1%. You can also try restricting background activity in the Android settings.
