### ISSUE TITLE
[Feature Request] Add link/button to show release notes from app/update page

### ISSUE THREAD

**Issue by kaysond** [ImranR98/Obtainium#1474]
**Prerequisites**

**Describe the feature**
When you open an update available notification, it takes you to the app update screen, but there's no way to see the release notes. I know I can go back to the main page and check them from there, but it would be nice to not have all the extra steps (since then you have to go into the update page again to actually install)

**Describe alternatives you've considered (if applicable)**

**Additional context**

**Comment by DwainZwerg** [comment]
> since then you have to go into the update page again to actually install

That's not true. You can also update/mark as up-to-date from the home screen:
![signal-2024-03-14-211830](https://github.com/ImranR98/Obtainium/assets/97027379/18b6b394-0998-43ad-90a6-d83cf55b644b)
… nevertheless, I don't want to deny your feature request. It makes a lot of sense to be able to display the changelog in the app overview (there would be space for an icon to the left of the bin).

**Comment by ImranR98** [comment]
The version on the app page is now clickable and opens the changelog (if any): https://github.com/ImranR98/Obtainium/releases/tag/v1.0.6

**Comment by kaysond** [comment]
This is great. Thank you!!
