### ISSUE TITLE
Can't download APK from TorProject Gitlab

### ISSUE THREAD

**Issue by skariko** [ImranR98/Obtainium#1475]
**Prerequisites**

**Describe the bug**

Can't download APK from Gitlab TorProject: https://gitlab.torproject.org/tpo/applications/vpn/-/packages

**To Reproduce**

Insert as a source https://gitlab.torproject.org/tpo/applications/vpn/-/packages I tried any kind of "source"

**Screenshots and Logs**

**Please complete the following information:**
 - Device: Pixel 6a
 - OS: GrapheneOS
 - Obtainium Version: 1.05

**Additional context**

**Comment by ImranR98** [comment]
They haven't released any APKs on that repo: https://gitlab.torproject.org/tpo/applications/vpn/-/releases

**Comment by skariko** [comment]
> They haven't released any APKs on that repo: https://gitlab.torproject.org/tpo/applications/vpn/-/releases

Okay, that's clear. Effectively the official "release" section is empty as they just release alpha-release.

However, I was wondering why I still can't get Obtainium to find the APKs on this page: https://gitlab.torproject.org/tpo/applications/vpn/-/packages not even via HTML control or anything.

**Comment by DwainZwerg** [comment]
> However, I was wondering why I still can't get Obtainium to find the APKs on this page: https://gitlab.torproject.org/tpo/applications/vpn/-/packages not even via HTML control or anything.

Because we don't know of any API or RSS feed that can access it. Perhaps you know one? HTML extraction can't work either, because the entries are loaded via JavaScript.

**Comment by skariko** [comment]
> > However, I was wondering why I still can't get Obtainium to find the APKs on this page: https://gitlab.torproject.org/tpo/applications/vpn/-/packages not even via HTML control or anything.
> 
> Because we don't know of any API or RSS feed that can access it. Perhaps you know one? HTML extraction can't work either, because the entries are loaded via JavaScript.

No actually from that page you can't seem to get any RSS.

I just point out, in case anyone reads and might find it useful, this RSS from the "[tag](https://gitlab.torproject.org/tpo/applications/vpn/-/tags)" page: https://gitlab.torproject.org/tpo/applications/vpn/-/tags?format=atom where new releases are posted (but without the APK).
