### ISSUE TITLE
Ability to archive apps or disable tracking

### ISSUE THREAD

**Issue by novocaiin** [ImranR98/Obtainium#1477]
**Prerequisites**

**Describe the feature**

Either a toggle allowing to disable tracking app updates on an individual basis or ability to archive apps where apps in the archive aren't tracked, and no notifications are sent admitt them.

**Describe alternatives you've considered (if applicable)**

**Additional context**

I have recently run into two separate issues with two separate apps.

1. https://github.com/mpv-android/mpv-android publish the version I want in a pull request (https://github.com/mpv-android/mpv-android/pull/58) instead of the releases page for now. Result? Obtainium keeps tracking it and telling me there is an update even when the installed version is latest. I still want to have it in Obtainium for
 - when the version gets finally included in releases I can remove it from the archive/toggle tracking
 - when an update is released I'll at least see that the version numbers differ and go and download the new version from the PR.

2. https://github.com/Sangwan5688/BlackHole I assume were taken down, and I'm getting *constant error notifications* from Obtainium about it. Right now I have seven cluttering my notification bar. I actually think it's contributed to an increased battery drain in the last few days due to the constant checks. Now, it's a good thing it's notifying me. But what is it expecting me to do? Repos *have* been reinstated in the past (see youtube-dl) so I don't want to just delete it in case it comes back. But I also don't want it constantly checking Blackhole for updates and bombarding me with error messages and draining my battery.

Both these issues could be solved by making the apps "dormant" through an archive or a toggle.

**Comment by DwainZwerg** [comment]
> Either a toggle allowing to disable tracking app updates on an individual basis […]

This function is already largely supported. In the app overview of each GitHub app, after clicking on the pen icon at the bottom, you can select the two options "Exempt from background updates (if enabled)" and "Skip update notifications". What is still missing is the deactivation of forground updates and your second feature request:
> […] ability to archive apps where apps in the archive aren't tracked, and no notifications are sent admitt them.

**Comment by ImranR98** [comment]
Yes, you can already disable notifications on a per-app basis, and disable background updates as well.

I don't see the point of adding a "disable update checking" for foreground checking since you can just not click on "update".

**Comment by DwainZwerg** [comment]
> I don't see the point of adding a "disable update checking" for foreground checking since you can just not click on "update".

@ImranR98 If you open Obtainium and swipe down to check all apps for updates in the foreground, the app for which the background update checks are deactivated should also be checked, right? However, the TE wants the app not to be checked for updates even then, which I can certainly understand.
