### ISSUE TITLE
Sourceforge - Can't install correct version of Emacs for Android

### ISSUE THREAD

**Issue by zetaomegagon** [ImranR98/Obtainium#1479]
**Prerequisites**
I checked and don't see this specific issue.

I didn't find anything in the wiki, except potentially using HTTP instead of release URL

Unfortunately, I'm unsure if this expected or not. I read over a few issues created previously, and this doesn't seem to be intended behavior

**Describe the bug**
When trying to add the latest version of Emacs for Android from the Termux directory in [this Sourceforge directory](https://sourceforge.net/projects/android-ports-for-gnu-emacs/files/termux/), an old version is listed OR the incorrect architecture is listed.

I tried various attempts at detecting the correct version and architecture.

I expect to get:

- `emacs-30.0.50-29-arm64-v8a.apk`
- (or a list of all APKs in the dir? Maybe?)

But get one of the below instead:

- `emacs-30.0.50-21-arm64-v8a.apk` (wrong version)
- `emacs-30.0.50-16-armabi-v7a.apk` (wrong arch)
- `No apk found`

**To Reproduce**

###### Wrong Arch

1. Add the link
2. Leave defaults
3. press add

###### Wrong Version

1. Uninstall correct version
4. Add the link
5. Use this version string regex: `[0-9]+\.[0-9]+\.[0-9]+-[0-9]+-arm64-v8a`
6. Press add

###### Adding APK Regex
1. Add link
2. Add APK name Regex
3. Press add
4. Result: No apk found

**Screenshots and Logs**

- If you need screenshots can get them. On mobile and can't upload screenshots currently.
- Device not rooted so can't access Obtanium home dir.
- Not familiar with Android logging, so don't know where to look. Let me know and I'll gather what I can

**Please complete the following information:**
 - Device: One Plus 9 Pro
 - OS: DivestOS 20
 - Obtainium Version: 1.0.6

**Additional context**
The emacs packages in that directory all have their Shared User ID set to `com.termux`.

I'm at a loss O_o

**Comment by zetaomegagon** [comment]
Okay, so I modified the version regex to match the apk I want:

`[0-9]+\.[0-9]+\.[0-9]+-29-arm64-v8a`

That results in:

`emacs-30.0.50-29-arm64-v8a.apk`

But that means version detection won't work, right?

**Comment by ImranR98** [comment]
The SourceForge Source was added back when the HTML Source was a lot simpler and couldn't do the job. It was also made with a specific directory structure in mind, like [this one](https://sourceforge.net/projects/opencamera/files/) where each version is a subfolder, with no nested subfolders. This isn't always true (the folder hierarchy can be anything) so people have had issues with this source in the past. Doesn't look like the current SF code would be able to properly handle this repo.

These days I would suggest just using HTML as it can handle SourceForge, with a lot more flexibility for any folder structure. The SF Source should probably be removed (but I'd have to write something to automatically convert peoples' existing SF apps to HTML).

Could you try these settings:
- Source Override: `HTML`
- Custom APK link filter: `-arm64-v8a\.apk/download$`
- Version extraction RegEx: `emacs-([^-]+)-[0-9]+-arm64`
- Match group to use: `1`

**Comment by ImranR98** [comment]
Ignore above comment, just realized SF links in the UI don't work.

**Comment by ImranR98** [comment]
Okay, the settings in that hidden comment do work, you just need to also clear out the request headers (remove the default user-agent header):

Could you try these settings:
- Source Override: `HTML`
- Custom APK link filter: `-arm64-v8a\.apk/download$`
- Version extraction RegEx: `emacs-([^-]+)-[0-9]+-arm64`
- Match group to use: `1`
- Request headers: none

**Comment by zetaomegagon** [comment]
Okay, cool. TYVM :)

**Comment by zetaomegagon** [comment]
Update: worked like a charm

**Comment by zetaomegagon** [comment]
@ImranR98 sorry. Quick question: when testing for needed headers with the HTML source, what tools other than Obtanium do you use (curl, dev tools, etc) ?

Ty

**Comment by ImranR98** [comment]
Yes mostly just curl and the firefox devtools.

**Comment by vvirtues** [comment]
I'm not sure how this works, I've updated, but how do I use this for opencamera? I'm a little lost

**Comment by DwainZwerg** [comment]
> [H]ow do I use this for opencamera? I'm a little lost

Yes, I've already asked myself the same thing: https://github.com/ImranR98/Obtainium/discussions/1509

**Comment by vvirtues** [comment]
> > [H]ow do I use this for opencamera? I'm a little lost
> 
> Yes, I've already asked myself the same thing: #1509

I ended up using direct apk link (https://sourceforge.net/projects/opencamera/files/latest/download)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/discussions/1509#discussioncomment-8977647
