### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by HRTK92** [ImranR98/Obtainium#148]
I would like to have Japanese language support!
Not right now, but i can make ja.json.
But when I looked at the app settings I could not find an item to change the language.
If you will support multiple languages in the future I will create ja.json, what do you think?

**Comment by ImranR98** [comment]
Hi,
I think it should automatically pick up the OS langauge setting. Not sure though, will check and get back to you.

**Comment by ImranR98** [comment]
Confirmed. Creating a `ja.json` and adding `Locale('ja')` to the `supportedLocales` array (in `main.dart`) is enough to get it to switch to using that file when the OS language setting is set to Japanese.

**Comment by HRTK92** [comment]
I understand.
Thank you.
