### ISSUE TITLE
Obtainium can't sense SimpleX Chat pre-release.

### ISSUE THREAD

**Issue by summoner001** [ImranR98/Obtainium#1483]
**Prerequisites**

**Describe the bug**

**To Reproduce**
Try install SimpleX chat from github
https://github.com/simplex-chat/simplex-chat/releases

Obtainium always try install stable release. But pre-release installation is enabled in obtainium.

**Screenshots and Logs**

**Please complete the following information:**
 - Device: Cubot Quest
 - OS: Android 9
 - Obtainium Version: v1.0.6

**Additional context**

**Comment by ImranR98** [comment]
Work fine for me. What additional options have you set?

**Comment by summoner001** [comment]
After uninstall and install the app Obtainium and simplex chat. The problem no longer occurs.
Sorry for the mistake. If the problem occurs again I will post here.

**Comment by summoner001** [comment]
If the prAfter uninstall and install the app Obtainium and simplex chat. The problem no longer occurs.
Sorry for the mistake. If the problem occurs again I will post here.
