### ISSUE TITLE
Filter issue?

### ISSUE THREAD

**Issue by Sami32** [ImranR98/Obtainium#1490]
That could be probably only incorrectly using Obtainium from my side, but when i try to filter the stable APK no entry is found, and by default (no filter) the beta version is notified.

https://github.com/Gedsh/InviZible/releases

![Screenshot_2024-03-21-17-40-31-183_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/18471069/975d1410-936d-4187-a2f6-ebe5e31aa64e)

Android 7.0 (Xiaomi stock)
Obtainium v. 1.0.6

**Comment by ImranR98** [comment]
The dev hasn't actually marked their beta releases as pre-releases on github. Here's an example of a correctly marked release, you can see the yellow pre-release label which is missing in your case: https://github.com/ImranR98/Obtainium/releases/tag/v0.16.1-beta

The dev has only put "Beta" in the release title, so you can use the release title filter instead.

**Comment by ImranR98** [comment]
Basically clear out the release notes filter from your screenshot (wouldn't work) and put `Stable` in the title filter instead.

**Comment by Sami32** [comment]
Thank you +1

My bad, i thought that the release note was this:
![IMG_20240321_175408](https://github.com/ImranR98/Obtainium/assets/18471069/5390ab71-321a-4e47-b200-bfba6bfc5783)

**Comment by ImranR98** [comment]
That's the tag, which Obtainium takes as the app's version.
