### ISSUE TITLE
How to properly config App that came from Github.

### ISSUE THREAD

**Issue by ulil-azmy** [ImranR98/Obtainium#1492]
https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root/releases

that release contains all apk that i wanna add. i really noob to this stuff. what tooggle should i set to on if i wanna to make sure all apk i added from those repo got updated?

thanks

**Comment by ImranR98** [comment]
Issues are for reporting bugs or requesting enhancements. For support, use the GitHub discussions page instead. I've copied this issue to a post and added an answer there: https://github.com/ImranR98/Obtainium/discussions/1494
