### ISSUE TITLE
Generic latest release download to folder

### ISSUE THREAD

**Issue by Lucidic15** [ImranR98/Obtainium#1493]
Add the ability to monitor any github release section to download latest assets, for instance a zip. Not just APKs.

Assign a folder for the downloads. Click "Update" or "Download" to get the latest release.

For example, getting latest Turnip Drivers.

**Comment by ImranR98** [comment]
You can now download any GitHub release asset by clicking 'Download release asset' on the app detail page or from the multi-select menu: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.2

**Comment by ImranR98** [comment]
@DwainZwerg I'd prefer to continue keeping temporary downloads in the cache folder so that Android's "clear cache" function keeps working, and because it's easier than dealing with SAF to use a different path (the Downloads folder probably wouldn't feel right to most users since they never used any 'download' function).

The feature requested here is separate, and files downloaded this way do get sent to the Downloads folder.

**Comment by DwainZwerg** [comment]
> I'd prefer to continue keeping temporary downloads in the cache folder so that Android's "clear cache" function keeps working

I can understand that. Since Android 14, it has become much more complicated to make a good decision.

> The feature requested here is separate, and files downloaded this way do get sent to the Downloads folder.

This is fine. Then you can access these downloaded files via the download feature.

**Comment by skyerjoe** [comment]
Where ist the Option vor the apk Download ?
I couldnt find the Button 

Best regards

**Comment by ImranR98** [comment]
Just above the category selector on any app detail page. Or on the apps page, long press on the list to enter multi select mode, select some app, then click the three dot menu -> "Download release asset".

The first time after updating, use pull to refresh so that all github apps are rechecked.

**Comment by Lucidic15** [comment]
Hmm, sounds like from your last message here that you changed it so that you can download all assets from a github that HAS an APK in the release. 

With the original enhancement, I was hoping to add stuff to watch and collect that doesn't have an APK. Like Turnip drivers. Doesn't seem like this is an option still, can you confirm?

**Comment by ImranR98** [comment]
No, this works for track-only apps too.

**Comment by Lucidic15** [comment]
That's great, but I am not understanding how to add something like Turnip Drivers.

I went to Add Apps, enter the releases URL in App Source URL, then add. I get, cannot find suitable release.

What am I missing? Do I need to do regex to accept only certain assets in the release that aren't APKs?

**Comment by ImranR98** [comment]
You need to enable track-only mode in the additional settings

**Comment by Lucidic15** [comment]
Ok, so it will show me that there is an update next time there is a release that isnt the release after I have added it to my tracking list? But I will still need to go to the github to grab it. No option to have obtanium pull anything?

**Comment by ImranR98** [comment]
Yes, you'll be notified of new releases. You can also download any release assets (including source code zip/tar) from inside the app.

**Comment by Lucidic15** [comment]
Ahh, download release asset, I see it now.

Thank you for adding this feature!

**Comment by Lucidic15** [comment]
Though, picking a download folder would be nice. But maybe nitpicking my use case. Up to you on that one of course. Maybe a setting, Download Track Only to Downloads / Pick Download Location for Track Only

**Comment by ImranR98** [comment]
You can open another issue for that

**Comment by DwainZwerg** [comment]
Aren't https://github.com/ImranR98/Obtainium/issues/29, https://github.com/ImranR98/Obtainium/issues/1181 and https://github.com/ImranR98/Obtainium/issues/1007 solved by this [commit](https://github.com/ImranR98/Obtainium/commit/3d1113c057fc4b6c8365f01e635561597575b881) so that they can be closed?

**Comment by KaKi87** [comment]
Hi,
Where does the "Download release asset" downloads the file ?
Thanks

**Comment by ImranR98** [comment]
It should be in the Downloads folder
