### ISSUE TITLE
Brave update stopped working

### ISSUE THREAD

**Issue by ceskyDJ** [ImranR98/Obtainium#1495]
**Describe the bug**

I have the same configuration of Obtainium for some weeks, but yesterday Brave updates sopped working. I tried it manually, too, but it doesn't work, too. It just gives me poor error message (see attached screenshots).

**To Reproduce**

1. Open Obtainium
2. Go to details of Brave (previously set up with this configuration:)
    - Include prereleases: `false`
    - Fallback to older releases: `true`
    - Filter Release Titles by Regular Expression: `Release v.+`
    - Filter Release Notes by Regular Expression: ` `
    - Verify the 'latest' tag: `true`
    - Retain release order from API: `false`
    - Use latest asset upload as release date: `false`
    - Track-Only: `false`
    - Version String Extraction RegEx: ` `
    - Match Group to Use for Version String...: `$0`
    - Reconcile version string with version detected from OS: `true`
    - Use release date as version string (pseudo-version): `false`
    - Use app versionCode as OS-detected version: `false`
    - Filter APKS by Regular Expression: `BraveMonoarm64\.apk`
    - Invert regular expression (Filter APKs by Regular Expression): `false`
    - Attempt to filter APKs by CPU architecture if possible: `true`
    - App Name: ` `
    - Exempt from background updates (if enabled): `false`
    - Skip update notifications: `false`
    - About: ` `
3. Tap on "Update"
4. See error "Some errors Occurred": "Invalid [Brave]"

**Screenshots and Logs**
![Screenshot_20240323_134900](https://github.com/ImranR98/Obtainium/assets/48548230/b2b6e51d-da10-41ae-ad24-09587bbe7a6b)
![Screenshot_20240323_142020](https://github.com/ImranR98/Obtainium/assets/48548230/0ad60a56-47e5-45ca-8f2c-29493b6f8d56)

**Please complete the following information:**
 - Device: Samsung Galaxy S22
 - OS: Android 14
 - Obtainium Version: 1.0.6

**Comment by ImranR98** [comment]
Works on my end. Could you try clearing the cache?

**Comment by ceskyDJ** [comment]
Hmm, it helped. Thanks a lot!

**Comment by ImranR98** [comment]
Glad it worked. Not sure why it happened though - cached files that fail to install are supposed to be deleted automatically. Or did this error show up before the actual install prompt (during/before the download)?

**Comment by ceskyDJ** [comment]
It seems like it showed up even before downloading. I tapped on ”Update“ and after a few seconds the error raised.

**Comment by ImranR98** [comment]
Hmm okay, that would help narrow it down but I should have asked you to upload the cached file (not sure I can debug without it). Closing the issue until it comes up again (probably will for someone).

**Comment by ceskyDJ** [comment]
I think it just used an already downloaded APK file, which was cached there. For some reason the file was corrupted, so it didn't work or something like that. What do you mean?

**Comment by ImranR98** [comment]
Yes I thought corrupt APKs would be deleted automatically (so you could just retry without clearing the cache) but just found the bit of code where a delete is missing. Will be fixed in the next release.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.0
