### ISSUE TITLE
GitLab / GitHub Tags And Track-Only

### ISSUE THREAD

**Issue by 43qcc2cn** [ImranR98/Obtainium#1496]
I'm not sure if this is a bug or user error on my part but, I'm sure this used to work in previous releases of Obtainium.

Two slightly different issues when trying to add a repo as Track-Only that has no releases, only tags.

**https://gitlab.com/divested-mobile/mull-fenix**

Obtainium reports:
"Could not find a suitable release"

![Screenshot_20240327-093640_Obtainium](https://github.com/ImranR98/Obtainium/assets/25418755/34174e77-d751-4a89-b687-f238e68bb1fc)

Calling the API directly returns the latest tag:
`curl --silent https://gitlab.com/api/v4/projects/22366051/repository/tags/ | jq --raw-output '.[].name' | head -1
v124.1.0`

**https://github.com/Divested-Mobile/Mull-Fenix**

Obtainium reports:
"v107.1.0"

![Screenshot_20240327-093609_Obtainium](https://github.com/ImranR98/Obtainium/assets/25418755/c07dce2e-70e7-41af-a3a3-5d9009e204b1)

Calling the API directly returns the latest tag:
`curl --silent https://api.github.com/repos/Divested-Mobile/Mull-Fenix/tags | jq --raw-output '.[].name' | head -1
v124.1.0`

 - Device: Samsung Galaxy S10
 - OS: LineageOS 20 (Android 13)
 - Obtainium Version: v1.0.6

For info, I am aware that there are F-Droid repos for this application but I would prefer to use the source repos for tracking if possible.

Any advice much appreciated. Thanks in advance.

**Comment by ImranR98** [comment]
This was a bug. It should be fixed in the latest release: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.0
