### ISSUE TITLE
Added apps' icon not visible. 

### ISSUE THREAD

**Issue by anurag565** [ImranR98/Obtainium#1497]
Device:- M13 5G
Android:-14 One UI 6.0
I cant see any icon other than of obtanium under added apps section. I guess its a bug. 
![Screenshot_20240328_001958](https://github.com/ImranR98/Obtainium/assets/143786347/196e7b15-85b6-4823-ba6f-8b1e451d4b60)

**Comment by DwainZwerg** [comment]
Hello @anurag565 ,
I see that you are using pseudo versions (probably from apkmirror.com). If this is the case, this behaviour is the known one and not a bug. Because Obtanium does not find the equivalent of the app in the system (because it does not search for it), the image cannot be extracted from the system.

**Comment by ImranR98** [comment]
Depending on how an app is added, it may have a randomly generated ID instead of a real one - so we can't extract an icon for it.

**Comment by anurag565** [comment]
> Hello @anurag565 , I see that you are using pseudo versions (probably from apkmirror.com). If this is the case, this behaviour is the known one and not a bug. Because Obtanium does not find the equivalent of the app in the system (because it does not search for it), the image cannot be extracted from the system.

Even the apps like magisk, added from github dont show app icon. And apps are installed in system

**Comment by anurag565** [comment]
> Depending on how an app is added, it may have a randomly generated ID instead of a real one - so we can't extract an icon for it.

So what i have to do to see app icon?

**Comment by DwainZwerg** [comment]
> Even the apps like magisk, added from github dont show app icon. And apps are installed in system

But you use for magisk from github also pseudoversions, isn't?

**Comment by anurag565** [comment]
> > Even the apps like magisk, added from github dont show app icon. And apps are installed in system
> 
> But you use for magisk from github also pseudoversions, isn't?

I dont know what's a pseudo version is. I got magisk on github, downloaded and installed. No where its written its pseudo version. Or idk much about github, im new here.

**Comment by DwainZwerg** [comment]
Go to the app overview of the respective app and click on the pencil-icon. Deactivate the pseudo versions there.

**Comment by DwainZwerg** [comment]
Details: https://github.com/ImranR98/Obtainium/wiki#version-detection

**Comment by ImranR98** [comment]
@dwainzerg this isn't doesn't have anything to do with pseudo-versions. @anurag565 please export your apps list and attach it here.

**Comment by anurag565** [comment]
> @DwainZwerg this doesn't have anything to do with pseudo-versions. @anurag565 please export your apps list and attach it here.

Sure. Here's app list.
[obtainium-export-2024-03-28T02-42-01.825559.json](https://github.com/ImranR98/Obtainium/files/14781232/obtainium-export-2024-03-28T02-42-01.825559.json)

**Comment by ImranR98** [comment]
Yep, all these apps have a random ID. For the APKMirror ones that is normal. For the GitHub ones, you must have used one of the external import options instead of adding them directly.

You should re-install these apps from Obtainium instead of just marking them as updated. There is a warning about this at the bottom of the import/export page.

**Comment by anurag565** [comment]
> Yep, all these apps have a random ID. For the APKMirror ones that is normal. For the GitHub ones, you must have used one of the external import options instead of adding them directly.
> 
> You should re-install these apps from Obtainium instead of just marking them as updated. There is a warning about this at the bottom of the import/export page.

Yes i often manually root device and then install basic apps before installing obtanium. I just wanted icons and dont wanna download them from obtanium app. Because i just like downloading them manually ig. Anyways, thanks and hope you do something for it.

**Comment by ImranR98** [comment]
You could always download them through the app once, then manually after that. Not much can be done otherwise (you could try manually modifying the JSON files and adding each app ID yourself but that is not practical).

**Comment by anurag565** [comment]
> You could always download them through the app once, then manually after that. Not much can be done otherwise (you could try manually modifying the JSON files and adding each app ID yourself but that is not practical).

Yeah right, thanks. I was thinking if app could download just icon image just after adding link so that it wont matter when you installed the app. I know you are the developer so if you say its not possible, it's not for sure
