### ISSUE TITLE
Progress percentage overflow

### ISSUE THREAD

**Issue by deadcombo** [ImranR98/Obtainium#1498]
Pixel 7 Pro, GrapheneOS 14 QPR2, Obtainium 1.06

While updating an app resumed from an interrupted download the progress percentage began at 39% and went up to ~250%.

![Screenshot_20240328-094614](https://github.com/ImranR98/Obtainium/assets/37187650/841d7cee-bcb0-4d31-88b0-76de2a77aaed)

Afterwards the update failed and download restarted but did not progress past 0%.

**Comment by DwainZwerg** [comment]
Can you clear the cash? There could be corrupt APKs

**Comment by deadcombo** [comment]
Cleaning the cache did in fact make sure everything installed correctly and strangely also made the download progress much faster than usual, thank you.

My aim was to raise awareness of the small counter bug, feel free to close this when you'd like.

**Comment by ImranR98** [comment]
Unclear what caused this, I've added a check to automatically delete a download if it goes too far over 100%. If it happens again, please attach the cached file and link to the app's repo.
