### ISSUE TITLE
Updateable Apps not all shown on top

### ISSUE THREAD

**Issue by firefoxlover** [ImranR98/Obtainium#1499]
**Prerequisites**

**Describe the bug**
I have some apps that are not shown on the top when they have updates. [Podcini](
https://github.com/XilinJia/Podcini) is one of them. They are displayed somewhere in the list., also QField and other Github releases.

**To Reproduce**
Wait until apps have updates, some are not displaxed at the top.

**Screenshots and Logs**
Some apps show in the list.

**Please complete the following information:**
 - Device: Pixel 6a
 - OS: GrapheneOS
 - Obtainium Version: 1.0.6

**Comment by ImranR98** [comment]
Haven't been able to reproduce this. Is the "pin updates to top" setting enabled? Do you see the update icon in the apps list?

**Comment by firefoxlover** [comment]
both yes.

**Comment by ImranR98** [comment]
Could you do an export and attach it here? Make sure to enable "include settings" but _make sure to manually remove and GitLab/GitHub API tokens in the file (if any) before attaching_.

**Comment by ImranR98** [comment]
Removed your link since you forgot to remove your GitLab token. The reason you're not seeing updated apps at the top is because you have pinned 99 apps, and pinned apps take order priority over updates.

**Comment by firefoxlover** [comment]
oh, omg forgot that this existed, will quickly delete it, thanks a lot.

Okay this must be an issue then, as I never manually pinned any app
