### ISSUE TITLE
Downloafs fail to prompt install, when navigating tabs

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#150]
Using 0.8.10

If I start some downloads, and navigate to Obtainiums other tabs [Settings, add app etc] and the downloads complete while I'm in those menus, Then Obtainium won't prompt to install the apps. 
When I go back to the apps tab, the apps show as update available again.
Clicking download then brings up the install prompts without re-downloading again at least.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.13-beta
