### ISSUE TITLE
Itch.io source

### ISSUE THREAD

**Issue by monyarm** [ImranR98/Obtainium#1501]
It doesn't appear to be possible to grab games from itch.io using the HTML source. (example game: https://nomnomnami.itch.io/charm-studies )
It takes 2 intermediate links to reach the actual download buttons. But they use javascript, and aren't direct links to the file.

**Comment by ImranR98** [comment]
Obtainium can't deal with JS (please use the issue template).

**Comment by hchasens** [comment]
I know it can't deal with JS, but having some way to grab itch.io APK downloads would be great. Maybe someone could set up a proxy server or an RSS with direct links? Currently, I don't believe there's any installer that officially supports itch.io APKs.

**Comment by UlyssesZh** [comment]
Why is #2405 deleted?
