### ISSUE TITLE
Could not get ID from APK - GitLab source app

### ISSUE THREAD

**Issue by b2sql** [ImranR98/Obtainium#1506]
![Screenshot_20240329-195128](https://github.com/ImranR98/Obtainium/assets/81143526/9063dc3d-8f95-40b8-bc15-abeca459ab82)
Can't add https://gitlab.com/cavebros/openmw-android-docker/-/releases to Obtainuim. I've been receiving "Could not get ID from APK" on every attempt.

**Comment by ImranR98** [comment]
The app is most likely not compatible with your device. Try downloading/installing it manually to confirm that.

**Comment by ImranR98** [comment]
Found the issue. The APK link on the release page isn't actually a link to an APK. It's a link to another GitLab CI/CD artifact page which in turn contains a link to an APK. So not exactly a bug, more like missing support for CI/CD asset links - this can be added.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.1
