### ISSUE TITLE
Obtainium can't scrape this website, help!

### ISSUE THREAD

**Issue by gothmog123** [ImranR98/Obtainium#1508]
Obtainium fails to get an apk from this website:

https://www.completedynamics.com/?page=downloads

Any tips? Thank you

**Comment by GenericMale** [comment]
The downloads on this page are in an iframe. Try this: https://www.completedynamics.com/pages/downloads.php?lang=en

**Comment by gothmog123** [comment]
> The downloads on this page are in an iframe. Try this: https://www.completedynamics.com/pages/downloads.php?lang=en

Thank you so much
