### ISSUE TITLE
"Couldn't find a release version"

### ISSUE THREAD

**Issue by itzshoaibmalik** [ImranR98/Obtainium#1510]
I have been trying to add apk download link from liteapks.com which follows [https://liteapks.com/download/truecaller-89/1]()

It keeps saying couldn't find a release version. Why's that even after using html source...

**Comment by DwainZwerg** [comment]
That's right. The link generation is done there via Java Script and Cloudflare. Either I made a mistake in https://github.com/ImranR98/Obtainium/issues/1428#issuecomment-1966411996 and it didn't work back then or they have changed something in the page design in the meantime. In any case, Obtanium cannot scrape Java script, so the statement in https://github.com/ImranR98/Obtainium/issues/1239#issuecomment-1874863197 that we cannot (currently) support liteapks.com still applies.
