### ISSUE TITLE
PathNotFoundException: Cannot open file

### ISSUE THREAD

**Issue by brian6932** [ImranR98/Obtainium#1512]
**Prerequisites**
- [x] Please ensure your request is not part of an existing issue.
- [x] Please ensure you have checked the Obtainium Wiki.
- [x] Please ensure your request is an actual bug and not intended behaviour (this is frequently the case for issues involving version strings and the HTML source.

**Describe the bug**
Caused by an update to Android 14, all previously added apps were wiped, error occurs whenever adding any apps. Reinstalling or clearing data doesn't help, although the error's still somewhat similar to #1331.

**To Reproduce**

1. Install Android 14
1. Go to `Add App`
1. Paste link and press add

**Screenshots and Logs**

![](https://github.com/ImranR98/Obtainium/assets/18603393/ed97ddfd-bb81-4d44-9bb2-179cb7d50ba2)

**Please complete the following information:**
 - Device: Zenfone 9
 - OS: omni-14-202403121645-zenfone9-GAPPS
 - Obtainium Version: 1.1.0

**Additional context**

**Comment by ImranR98** [comment]
Hmm, i wonder if it's due to your OS - there shouldn't be any issue like this on A14. Could you use a file manager to check whether the cache folder in the error exists?

**Comment by brian6932** [comment]
The cache folder's there, but the `apk.part` file isn't.

**Comment by DwainZwerg** [comment]
Does \storage\emulated\0Android\data\dev.imranr.obtanium\data exist? The app configurations should be stored there.

**Comment by brian6932** [comment]
I already answered that

**Comment by brian6932** [comment]
This was actually due to a Kernel incompatibility with my ROM 😅
