### ISSUE TITLE
Selfhosted Gitea and Forgejo Instances do not work when overriding with Codeberg when link does not start with www

### ISSUE THREAD

**Issue by WreckingBANG** [ImranR98/Obtainium#1514]
**Prerequisites**

**Describe the bug**
I have a selfhosted Forgejo Instance. If i want to add a App from it, with overriding with Codeberg it does not work because the regex code assumes it is using www. but my link layout is forgejo.mydomain.tld. I also tried changing my forgejo domain to www.mydomain.tld. It worked perfect.

I think this can be solved by removing the www from the regex in /lib/app_sources/codeberg.dart. I would do a PR but i have no Access to my PC right now.

**To Reproduce**
1. Go to add Source
2. Add any Forgejo or Gitea Instance not starting with www.
3. Override with Codeberg
4. Cannot add it

**Screenshots and Logs**

**Please complete the following information:**
 - Device: Pixel 7 Pro
 - OS: GrapheneOS 14
 - Obtainium Version: 1.1.0

**Additional context**

**Comment by ImranR98** [comment]
The `www` is part of a regex and is optional. That regex isn't applied when you override a source anyways so it can't be the issue. Would you be able to provide a link to your repo?

**Comment by WreckingBANG** [comment]
Sadly my instance is only on my local network, but you might be able to test it with code.forgejo.org

**Comment by ImranR98** [comment]
I created this test repo: https://code.forgejo.org/ImranR98/TestRepo/releases

It works fine for me.

**Comment by ImranR98** [comment]
I made a test repo which works fine for me: https://code.forgejo.org/ImranR98/TestRepo

One thing to remember is that when the override option is used, Obtainium won't know how to automatically trim the URL, so you need to be exact. For example, https://code.forgejo.org/ImranR98/TestRepo works while https://code.forgejo.org/ImranR98/TestRepo/Releases does not work, because the `/Releases` is added by the code later.

**Comment by ImranR98** [comment]
Ping - we need a repo that gets this error.

**Comment by WreckingBANG** [comment]
I tested it again and it seems the url i was entering was somehow wrong. I am sorry. It works fine if you enter the base url without /releases.
