### ISSUE TITLE
Add an option to install older or different version of an app

### ISSUE THREAD

**Issue by ThaDaVos** [ImranR98/Obtainium#1515]
**Prerequisites**

**Describe the feature**

The option to install a older/specific version of an app - why? Sometimes one wants to install an older version to check from what version on something is broken - now I hoped this would be part of Obtaniun already but as far as I can see it's not

**Describe alternatives you've considered (if applicable)**

Manually downloading apks and shuffling them trying to find the cause of an issue 

**Additional context**

**Comment by ImranR98** [comment]
This is out of scope for Obtainium and would add too much complexity (and would be impossible for some sources anyways). What you can do is, for sources that allow it, use filtering option + "fallback to older releases" to get the version you want. Keep in mind Android won't allow you to "update" to an older version of an app anyways.
