### ISSUE TITLE
Heliboard - Unable to install 

### ISSUE THREAD

**Issue by tordenflesk** [ImranR98/Obtainium#1517]
![Screenshot_2024-04-04-15-11-07-60_a13e17678c56528bd2f18fcaaa8af4ba](https://github.com/ImranR98/Obtainium/assets/2136727/f831c0fb-d485-40bf-85ea-ceec3b47af4f)
Log is unhelpful. APK installs just fine manually.

**Comment by ImranR98** [comment]
Please follow the issue template - I have no idea what source you're even using.

**Comment by sxarthur** [comment]
Been having this Error with no description too with basically everything. Can't update or download anything. tried Fdroid and github Source

**Comment by tordenflesk** [comment]
> Please follow the issue template - I have no idea what source you're even using.

**Describe the bug**
Installing HeliBoard from GitHub doesn't work and the log doesn't really tell me why.

**To Reproduce**
<!-- Steps to reproduce the behavior:
1. Search HeliBoard
2. Select it
3. ...
4. "Some errors occured", log only says it failed with no specifics.

**Please complete the following information:**
 - Device: Oneplus Nord
 - OS: Android 12
 - Obtainium Version: 1.1.0

**Comment by ImranR98** [comment]
Closed - not enough info.
