### ISSUE TITLE
Ability to re-update or re-install apps. 

### ISSUE THREAD

**Issue by JDKamalakar** [ImranR98/Obtainium#1527]
Sometimes when obtanium detects the wrong version number of app install, there is no way to force install that app in order to get it to the latest update.

**Comment by ImranR98** [comment]
The OS level version detection should turn itself off if it doesn't work right. In rare cases it might not turn itself off but you can do that in the settings manually.

Once that is disabled you'll be able to manually reset the version that Obtainium thinks is installed, and it will then allow you to reinstall.

In the worst case scenario you can use the release asset download button to download the APK and install it manually.
