### ISSUE TITLE
[Bug/FR] Obtainium does not remember app architecture/apk choice

### ISSUE THREAD

**Issue by jayb-g** [ImranR98/Obtainium#1528]
**Describe the bug**
Once an app which has multiple apk options(such as armv7/arch64/fdroid release) is installed using Obtainium, it doesn't remember it for future updates meaning at the time of the next update, you have to choose the apk again. _Attempt to filter apks by CPU  architecture_ toggle doesn't seem to have any effect on the behavior. This might also be preventing the app from auto-updating in the background. I don't know if this is a bug or intended behavior.

**To Reproduce**
1. Add and install any app which gives multiple apk options upon installation. One such example is Rustdesk. Choose any apk option (fdroid/other) when installing.
2. Upon next release of Rustdesk, it would require you to choose the apk again.

**Screenshots and Logs**
N/A

**Please complete the following information:**
 - Device: P8
 - OS: AOSP14 LASTEST
 - Obtainium Version: 1.1.2

**Additional context**
Might also be the cause which holds back auto update in the background for some apps which have multiple apk options.

**Comment by jayb-g** [comment]
Bitwarden is another example

**Comment by ImranR98** [comment]
This has been covered in previous issues. There is no way for Obtainium to automatically select an APK for you because the number of APKs, their ordering, and the exact differences between them are arbitrary and can change from one release to the next.

You should use the APK release filter option to tell the app how to narrow down the options. If your filter is specific enough to narrow things down to one option, then that one option will be selected automatically and you won't have to choose again.

**Comment by jayb-g** [comment]
@ImranR98 Obtainium already has an option to filter apks by regex when adding the app. 

At the time of manual selection, if Obtainium can create regex itself automatically based on selected apk and differences from other apks then it can definitely be possible. Just an idea.

**Comment by ImranR98** [comment]
That's not realistic because the APK options are different for every repo and can even change between different releases on the same repo. Some repos contain different APKs for different CPU architectures. Others also have different variants for fdroid. Some repos even have multiple applications in the same repo. So there's no way to really automate this.

**Comment by jayb-g** [comment]
Based on selection? And automatic diff? 

Say Obtainium has two releases:
1. app.arm64-v8a-release.apk
2. app.arm64-v8a-fdroid-release.apk

If user chooses \#1 then required regex would be  _^((?!fdroid).)*$,_ otherwise _fdroid_. If we limit words in this update filter, like you said, to only include barchitrcure and commonly used words such as aarch64, arm64, v8, v7 armabi, fdroid etc then it would be fairly automatic. I think this keyword can be derived by diffing the release names vs selected name.

And Obtainium seems to add apk filter fdroid by default for itself upon installation. It still doesn't use that filter at the time of update. If its used for updates too then I think it will reduce manual intervention for selection at the time of update.

**Comment by jayb-g** [comment]
Or at least the update can use the already entered regex by user at the time of install.

**Comment by ImranR98** [comment]
> It still doesn't use that filter at the time of update.

That's weird - it should. Could you file a bug report?

**Comment by ImranR98** [comment]
> Based on selection? And automatic diff?

I'm not convinced this could be done reliably enough to be worth doing. PRs are welcome though, if anyone has a solution that covers a broad range of cases (maybe use some apps from https://apps.obtainium.imranr.dev for testing).

**Comment by jayb-g** [comment]
> I'm not convinced this could be done reliably enoug

Right.. But still worth trying.

**Comment by DwainZwerg** [comment]
> > I'm not convinced this could be done reliably enough
> 
> Right. But still worth trying.

I agree

**Comment by jayb-g** [comment]
> That's weird - it should. Could you file a bug report?

I'll have to check the behavior in case of other apps too to make sure if its Obtainium specific or same for all apps.

**Comment by jayb-g** [comment]
> That's weird - it should. Could you file a bug report?

I would, but my bug reports/feature requests end up getting closed due to missing template but I don't get a template i.e. its blank when creating new issue for this repo.

**Comment by ImranR98** [comment]
@jayb-g you can copy from here: https://github.com/ImranR98/Obtainium/blob/main/.github/ISSUE_TEMPLATE/bug_report.md?plain=1
