### ISSUE TITLE
Can't find suitable version on Sourceforge

### ISSUE THREAD

**Issue by jlh-makeen** [ImranR98/Obtainium#1541]
Dear Obtainium developer,

I am trying to get update for the Xiaomi.eu app using Obtainium but there has still been a bug or problem with the update.

Link is the following: 
https://sourceforge.net/projects/xiaomi-eu-multilang-miui-roms/files/xiaomi.eu/Xiaomi.eu-app/XiaomiEUModule_2024.02.29.apk/download

It is not very clear from the wiki how I'm supposed to setup the source for this application.

![Screenshot_2024-04-15-07-26-21-875_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/67622881/5a400822-9192-446f-bede-350a52e36fc1)

Could anyone help me to find the correct configuration I'm supposed to enter here ?

**Comment by DwainZwerg** [comment]
Source URL: https://sourceforge.net/projects/xiaomi-eu-multilang-miui-roms/files/xiaomi.eu/Xiaomi.eu-app/
Intermediate Link (1): /XiaomiEUModule_$.apk/download

_(untested)_

**Comment by jlh-makeen** [comment]
> Source URL: https://sourceforge.net/projects/xiaomi-eu-multilang-miui-roms/files/xiaomi.eu/Xiaomi.eu-app/ Intermediate Link (1): /XiaomiEUModule_$.apk/download
> 
> _(untested)_

Thank you for your answer,
Unfortunately this syntax doesn't work either:
![Screenshot_2024-04-15-08-44-28-657_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/67622881/123ce4ae-3b6d-412d-b3e1-445ca72cba38)


Maybe you have more explainations about the version checking regex ?

As you could see, Xiaomi.eu is using XiaomiEUModule_yyyy.mm.dd.apk version encoding in the apk name.

**Comment by DwainZwerg** [comment]
Maybe XiaomiEUModule_[0-9]+\.(0?[1-9]|[1][0-2])\.[0-9]+\.apk?

**Comment by DwainZwerg** [comment]
No, as an intermediate Link

**Comment by jlh-makeen** [comment]
> No, as an intermediate Link

My bad:
![Screenshot_2024-04-15-09-23-10-999_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/67622881/810c7273-6468-40a9-8982-b49381e61530)
![Screenshot_2024-04-15-09-22-53-153_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/67622881/5ce236d7-c3ea-44c7-80e8-67c9f62be44f)

There is some progress but now it fails with get ID ?

**Comment by ImranR98** [comment]
SF does not work with the default HTML headers - you need to delete them. I've added a note about this to the Wiki: https://github.com/ImranR98/Obtainium/wiki#notes-for-various-other-sources

Also your APK link filter is unnecessarily complicated - you can just use `\.apk/download`.

**Comment by jlh-makeen** [comment]
> SF does not work with the default HTML headers - you need to delete them. I've added a note about this to the Wiki: https://github.com/ImranR98/Obtainium/wiki#notes-for-various-other-sources
> 
> Also your APK link filter is unnecessarily complicated - you can just use `\.apk/download`.

Thank you Imran,

I've added the app following your instructions :)

![Screenshot_2024-04-16-07-39-22-556_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/67622881/9c2d370c-8c1b-4b45-94cf-a39d4029fe5a)
