### ISSUE TITLE
Can't add Novalauncher beta via HTML source

### ISSUE THREAD

**Issue by Kasi07** [ImranR98/Obtainium#1542]
#### Description
When trying to add the Novalauncher beta version via the HTML source like described in #1048 it only shows a popup "ok" but doesn't actually add the App to the apps list.

#### To Reproduce
1. Add new App with
    - Base URL: `https://novalauncher.com/beta`
    - Custom APK LInk Filter: `packageName=com.teslacoilsw.launcher&betaType=public&versionCode=`
    - Version String extraction: `versionCode=([0-9]+)$`
    - Match Group to Use for Version string extraction: `1`
2. Tap on **Add**

#### Screenshots and Logs
![image](https://github.com/ImranR98/Obtainium/assets/63197565/a7d69251-fa50-4e78-b0d8-7b557f343ad5)

**Please complete the following information:**
 - Device: Tested on Pixel 7 with GrapheneOS and Windows Subsystem for Android
 - Obtainium Version: 1.1.3

**Comment by ImranR98** [comment]
Should work now: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.4
