### ISSUE TITLE
The pure black theme is broken 

### ISSUE THREAD

**Issue by Zaxx69** [ImranR98/Obtainium#1552]
In the latest update of obtainium , the pure black theme doesn't work at all

**Comment by re7gog** [comment]
Check theme setting over black theme switch, it should probably be light theme, switch it to system or dark

**Comment by DwainZwerg** [comment]
> I changed this setting default because Android < 10 doesn't support syncing system theme

This is nevertheless possible via [third-party apps](https://play.google.com/store/search?q=Dark+Mode&c=apps). Please change this to the older version.

**Comment by re7gog** [comment]
> > I changed this setting default because Android < 10 doesn't support syncing system theme
> 
> This is nevertheless possible via [third-party apps](https://play.google.com/store/search?q=Dark+Mode&c=apps). @re7gog Please change this to the older version.

Sorry, i didn't know that it's possible, I will rollback

**Comment by DwainZwerg** [comment]
@ImranR98: @re7gog already fixed the bugs two days ago. Would you please bring his PR forward, among so that I have a DarkMode again.

**Comment by ImranR98** [comment]
Merged: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.6
