### ISSUE TITLE
Share appconfig via Android share menu

### ISSUE THREAD

**Issue by DwainZwerg** [ImranR98/Obtainium#1553]
**Prerequisites**
- [x] Please ensure your request is not part of an existing issue.
- [x] Please ensure you have checked the Obtainium Wiki.

**Describe the feature**
It would be cool to be able to create [such configuration links](http://apps.obtainium.imranr.dev/redirect.html?r=obtainium://app/%7B%22id%22%3A%22net.sourceforge.opencamera%22%2C%22url%22%3A%22https%3A%2F%2Fsourceforge.net%2Fprojects%2Fopencamera%2Ffiles%22%2C%22author%22%3A%22sourceforge.net%22%2C%22name%22%3A%22opencamera%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22%2Ffiles%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%2C%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22%2Fv_%5B%5E%2F%5D%2B%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%5C%5C%5C.apk%2Fdownload%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%2F(%5B%5E%2F%5D%2B)%2F%5B%5E%2F%5D%2B%2Fdownload%24%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%221%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%7D) using a “Share config” button in the respective app detail list of Obtainium and share them via the Android share menu.

**Describe alternatives you've considered (if applicable)**
Don't have the feature.

**Comment by ImranR98** [comment]
This can already be done from the multi-select menu

**Comment by ImranR98** [comment]
I guess it could also be added somewhere on the app detail page, along with some changes to the link format (currently outputs HTML which I'm not sure most people want).

**Comment by ImranR98** [comment]
Changed to use web links instead of direct protocol links, and removed HTML formatting. Not adding to the app detail page (don't think it's worth the unnecessary clutter).
