### ISSUE TITLE
In addition to the overview page and app logs, you could also refer to the wiki and the app configurations

### ISSUE THREAD

**Issue by DwainZwerg** [ImranR98/Obtainium#1554]
**Prerequisites**
- [x] Please ensure your request is not part of an existing issue.
- [x] Please ensure you have checked the Obtainium Wiki.

**Describe the feature**
In addition to the overview page and app logs, you could also refer to the [wiki](https://github.com/ImranR98/Obtainium/wiki) and the [app configurations](https://apps.obtainium.imranr.dev/) (see screenshot).
**Describe alternatives you've considered (if applicable)**
Don't have the feature.
**Additional context**
![signal-2024-04-21-131342](https://github.com/ImranR98/Obtainium/assets/97027379/fcb192db-53a0-4e55-bb91-a4a5a9dcb666)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.7

**Comment by DJCrashdummy** [comment]
sorry for getting slightly OT, but it's funny resp. also reassuring, that someone else - according to your screenshot @DwainZwerg - seems to have similar struggles with sorting by source as i described at #1290.
