### ISSUE TITLE
Silence `Obtanium must be open to install updates` for Shizuku and Root

### ISSUE THREAD

**Issue by brian6932** [ImranR98/Obtainium#1561]
**To Reproduce**
1. Select Shizuku/Root
1. Update apps
1. Go home
1. App gets mad

**Please complete the following information:**
 - Device: Zenfone 9
 - OS: OmniROM 14
 - Obtainium Version: 1.1.4

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases
