### ISSUE TITLE
SourceForge, OpenCamera, failing Obtainium 1.1.5

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#1564]
Obtainium v.1.1.5
GrapheneOS on Pixel 7.

I see [past issues](https://github.com/ImranR98/Obtainium/issues/391) with OpenCamera.  On update to Obtainium 1.1.5, I'm getting problems with a profile that used to work.

App Source URL: https://sourceforge.net/projects/opencamera/files/
(I then also tried: https://sourceforge.net/projects/opencamera/)
Custom APK Link Filter by Regexp: blank (nothing)

I have tried various other things for the Custom APK Link Filter by Regexp, but have been unsuccessful getting Obtainium to identify that there is an apk for v_1_52.  I've tried in turn:

blank (nothing)
v_[0-9_]*/OpenCamera\.apk
v_[0-9_]*/OpenCamera\.apk/download

and various others.

**Comment by DwainZwerg** [comment]
[This config](http://apps.obtainium.imranr.dev/redirect.html?r=obtainium://app/%7B%22id%22%3A%22net.sourceforge.opencamera%22%2C%22url%22%3A%22https%3A%2F%2Fsourceforge.net%2Fprojects%2Fopencamera%2Ffiles%22%2C%22author%22%3A%22sourceforge.net%22%2C%22name%22%3A%22opencamera%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22%2Ffiles%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%2C%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22%2Fv_%5B%5E%2F%5D%2B%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%5C%5C%5C.apk%2Fdownload%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%2F(%5B%5E%2F%5D%2B)%2F%5B%5E%2F%5D%2B%2Fdownload%24%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%221%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%7D) doesn't work?

**Comment by DiagonalArg** [comment]
Wow, two intermediate links!  Yes it works, thank you.  Question.  I see:

https://sourceforge.net/projects/opencamera/files

intermediate link #1: `/files/$`
intermediate link #2: `/v_[^/]+/$`

It appears `/files` is appearing twice here?  Could you just collapse `/files` into the sourceforge.net link?

**Comment by ImranR98** [comment]
Yes, you can put `/files` directly in the link and have a single intermediate.

**Comment by DiagonalArg** [comment]
Sorry to revisit this, but in that config [above](https://github.com/ImranR98/Obtainium/issues/1564#issuecomment-2072399249):

1. Deleting the first intermediate link (`/files/$`) is not accepted.
2. Attempting to recreate the config as either a sourceforge or an HTML source and using only one intermediate link with otherwise the same regexps, produces "Could not get ID from APK".

So, I tried to recreate exactly what you have in the config above, and I get the same problem with the ID!  I then noticed that in [the link/ config](http://apps.obtainium.imranr.dev/redirect.html?r=obtainium://app/%7B%22id%22%3A%22net.sourceforge.opencamera%22%2C%22url%22%3A%22https%3A%2F%2Fsourceforge.net%2Fprojects%2Fopencamera%2Ffiles%22%2C%22author%22%3A%22sourceforge.net%22%2C%22name%22%3A%22opencamera%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22%2Ffiles%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%2C%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22%2Fv_%5B%5E%2F%5D%2B%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%5C%5C%5C.apk%2Fdownload%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%2F(%5B%5E%2F%5D%2B)%2F%5B%5E%2F%5D%2B%2Fdownload%24%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%221%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%7D) you gave me, the first section says `id%22%3A%22net.sourceforge.opencamera`.  Is that something you added because of the same problem?  Is there a way to do that via the interface?

This further point is tangential, but I notice that once created, it seems impossible (?) to tell if a config is using some over-ride (eg. in this case, whether yours is using HTML instead of sourceforge).  This might be something to add to the interface?  Should I make a feature request?

**Comment by DwainZwerg** [comment]
> So, I tried, using the interface, to recreate exactly what you have in the config above, and I get the same problem ["Could not get ID from APK"]

That shouldn't be the case. Are you still using 1.1.5 or are you now using 1.1.6?

> then noticed that in [the link/ config](http://apps.obtainium.imranr.dev/redirect.html?r=obtainium://app/%7B%22id%22%3A%22net.sourceforge.opencamera%22%2C%22url%22%3A%22https%3A%2F%2Fsourceforge.net%2Fprojects%2Fopencamera%2Ffiles%22%2C%22author%22%3A%22sourceforge.net%22%2C%22name%22%3A%22opencamera%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22%2Ffiles%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%2C%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22%2Fv_%5B%5E%2F%5D%2B%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%5C%5C%5C.apk%2Fdownload%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%2F(%5B%5E%2F%5D%2B)%2F%5B%5E%2F%5D%2B%2Fdownload%24%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%221%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%7D) you gave me, the first section says `id%22%3A%22net.sourceforge.opencamera`. Is that something you added because of the same problem? Is there a way to do that via the interface?

The app ID for the operating system is always written to the .json document containing the app's config for all sources; if it is imported from an external source (such as this link), this is also specified because the json document is transmitted.

> using HTML instead of sourceforge

Sourceforge no longer exists. HTML is now used.

**Comment by DiagonalArg** [comment]
> > So, I tried, using the interface, to recreate exactly what you have in the config above, and I get the same problem ["Could not get ID from APK"]
> 
> That shouldn't be the case. Are you still using 1.1.5 or are you now using 1.1.6?

I'm using 1.1.6, and I just tried it again with the same results.

Source URL:
https://sourceforge.net/projects/opencamera/files/  
HTML

Intermediate links:
/files/$
/v_[^/]+/$

Custom APK Link Filter:
\.apk/download$

Version:
/([^/]+)/[^/]+/download$
1

The only switches that are on are:
"Reconcile version string with version detected from OS" 
"Attempt to filter APKs by CPU architecture if possible".

> > using HTML instead of sourceforge
> 
> Sourceforge as a source no longer exists. HTML is now used.

Ok, but my initial comment & question still stands:

>> ... I notice that once created, it seems impossible (?) to tell if a config is using some over-ride .... This might be something to add to the interface? Should I make a feature request?

**Comment by LightWayUp** [comment]
@DiagonalArg When accessing the file download URL, SourceForge serves HTML content if the request header contains a browser-like user agent string (like `User-Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36`). Obtainium adds this header by default for HTML app sources to get better result from web scraping.  
With the header added, the error ["Could not get ID from APK"] is reproducible. To download the APK file, **delete** the pre-filled request header when you're adding OpenCamera (or other apps from SourceForge), and it'll work.

See [Obtainium wiki](https://github.com/ImranR98/Obtainium/wiki#notes-for-various-other-sources) and [related previous discussion](https://github.com/ImranR98/Obtainium/issues/1479#issuecomment-2005704493).

**Comment by DwainZwerg** [comment]
@LightWayUp We had already realized that by now (in another thread) …
