### ISSUE TITLE
Error when checking for updates

### ISSUE THREAD

**Issue by luffy3298** [ImranR98/Obtainium#1566]
Device: oneplus7t pro
 - OS: lineage 20.0
 - Obtainium Version: 1.1.5
 
![Screenshot_20240423-212917_Obtainium](https://github.com/ImranR98/Obtainium/assets/7558492/59069c05-0ba8-4561-a8cc-b0f48b726c5f)

**Comment by ImranR98** [comment]
Does this happen every time or only this once? I doubt it's an Obtainium issue - looks like a bad connection.

**Comment by ImranR98** [comment]
Are you on a VPN? Are these all GitHub apps?

**Comment by ImranR98** [comment]
Do you have another device that you could test with? To see if the issue is device specific.

**Comment by karthickspk08** [comment]
This error is happening to me in Samsung F34 as well, no vpn, all are GitHub apps
Connection reset by peer [Nextcloud, Infinity, NewPipe, AnkiDroid, TrackerControl, Calculator, and Arcticons Material You]

**Comment by DigitalNXZ** [comment]
for me it also happens, but more with like only F-Droid apps, NextDNS x ProtonVPN (RethinkDNS) github works fine with a token
