### ISSUE TITLE
AppGallery URL gets malformed

### ISSUE THREAD

**Issue by StSav012** [ImranR98/Obtainium#1570]
**Prerequisites**
Either GitHub search fails or this is a new issue indeed.

**Describe the bug**

In an AppGallery URL, there may be the `cloud` part already present. Without the proper check, the app adds the part into the URL. This may result in a malformed URL and the corresponding error:

```plaintext
ClientException with SocketException: Failed host lookup: 'appgallery.cloud.cloud.huawei.com' (OS Error: No address associated with hostname, errno = 7), uri=https://appgallery.cloud.cloud.huawei.com/appdl/C000000000
```

**To Reproduce**
1. Go to the main screen.
2. Tap on _Add App_
3. In the _App Source URL_ field, enter `https://appgallery.cloud.huawei.com/appdl/C000000000` (or with a valid app number)
4. Select _Override Source_ to _Huawei AppGallery_.
5. Click the _Add_ button.
6. See the error message.

**Please complete the following information:**
 - Device: Motorola moto g¹⁰⁰ (XT2125-4)
 - OS: Android 12 (S1RTS32.41-20-16-1-9)
 - Obtainium Version: 1.1.6

**Additional context**
When I enter the URL I can get from the browser (like `https://appgallery.huawei.com/#/app/C000000000`), the app complains that the URL is invalid. The trick is to replace the `/#/app/` part with `/appdl/`. This is not trivial. Please consider the fix for that, too.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.7
