### ISSUE TITLE
Updates makes the app on light mode

### ISSUE THREAD

**Issue by Turhvjbufv** [ImranR98/Obtainium#1573]
**Prerequisites**

**Describe the bug**

In recent updates of obtainium, every update of  obtainium makes the app theme light
**To Reproduce**

Make app theme dark and then install new update 
**Screenshots and Logs**

**Please complete the following information:**
 - Device:  A72
 - OS:  lineage os 
 - Obtainium Version: 1.1.6

**Additional context**

**Comment by DwainZwerg** [comment]
Will probably happen again after the next update, there is still a bug in the theme (see https://github.com/ImranR98/Obtainium/issues/1574).
