### ISSUE TITLE
UI bugged

### ISSUE THREAD

**Issue by BhaturaGuy** [ImranR98/Obtainium#1574]
![Screenshot_2024-04-24-18-29-14-69_a13e17678c56528bd2f18fcaaa8af4ba](https://github.com/ImranR98/Obtainium/assets/93109835/d33dc78c-a89e-447a-97d0-c0940b88bd7a)

**Please complete the following information:**
 - Device:  Oneplus Nord 2
 - OS:  Oxygen OS 13
 - Obtainium Version: 
1.1.6
**Additional context**

After recent update

**Comment by re7gog** [comment]
I don't know what to say
Try changing theme settings back forward

**Comment by ImranR98** [comment]
@BhaturaGuy is this still an issue?

**Comment by BhaturaGuy** [comment]
No, don't know which version fixed it
