### ISSUE TITLE
"remember" APK name from "Pick an APK" screen for updates

### ISSUE THREAD

**Issue by cheintz** [ImranR98/Obtainium#1576]
**Prerequisites**

**Describe the feature**

It would be desirable to remember the string used in the APK Picker, especially to allow background updates. Even Obtainium requires the user to select between fdroid and regular release with every update. In some cases, this could even be determined by signing keys. 

**Describe alternatives you've considered (if applicable)**

The alternative is selecting the appropriate APK file with every update.

**Additional context**

<img src="https://github.com/ImranR98/Obtainium/assets/8992681/431cf52a-7199-4606-a14f-9e20093506de" width="250">

**Comment by ImranR98** [comment]
Please search through existing issues before opening new ones because this has been discussed before. You can already narrow down the APK options to one, using the APK filter regex. Obtainium cannot automate this for various reasons that have been discussed in other issues.
