### ISSUE TITLE
Can't download asset after successfully adding app

### ISSUE THREAD

**Issue by xcpn** [ImranR98/Obtainium#1578]
**Describe the bug**
Upon adding app and trying to download asset, results in error. More information can be found here: https://github.com/ImranR98/Obtainium/discussions/1577

**To Reproduce**
1. Tap 'add app'
2. Add app source url: https://download.wireguard.com/android-client/
3. Set 'match group' to '$1' and 'version string extraction' to 'wireguard\.android-(.+)\.apk'
4. Add the app

**Please complete the following information:**
 - Device: Galaxy Note 20 Ultra
 - OS: Android 13
 - Obtainium Version: 1.1.5

**Comment by xcpn** [comment]
@ImranR98 any idea when will this be fixed and added in the update?

**Comment by ImranR98** [comment]
Likely over the weekend.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.7

**Comment by heinrichat** [comment]
> @heinrichat Is it Wireguard for you too?

yes. works from the same IP with vanadium, so it must be the user agent.
