### ISSUE TITLE
Error Checking for Updates

### ISSUE THREAD

**Issue by bluefly000** [ImranR98/Obtainium#158]
device: Pixel 6a runnning GrapheneOS
app ver: 0.8.13

### Notification Title
`Error Checking for Updates`

### Notification body
`type '_ClientSocketException' is not a subtype of type 'AppSource' in type cast`

![Screenshot_20221216-183535](https://user-images.githubusercontent.com/101441707/208072032-97663012-5803-4efa-b88a-9ac4f4a2cd9c.png)

**Comment by ImranR98** [comment]
Should be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.14-beta
