### ISSUE TITLE
Asset is downloaded with incorrect file format

### ISSUE THREAD

**Issue by xcpn** [ImranR98/Obtainium#1581]
**Describe the bug**

When selecting asset to download in ZIP format, the asset is downloaded in APK format.

**To Reproduce**
1. Add and save GitHub source: https://github.com/alexbakker/aegis-simple-icons
2. After added, tap on 'Download release asset'
3. Select 'aegis-simple-icons-v154.zip'
4. Tap 'continue'

The asset is now downloaded as 'aegis-simple-icons-v154.apk' instead of '.zip', even though explicitly selected desired file format.

**Please complete the following information:**
 - Device: Galaxy Note 20 Ultra
 - OS: Android 13
 - Obtainium Version: 1.1.5

**Comment by xcpn** [comment]
@ImranR98 I just realized that there's another problem with this bug.

If you choose _aegis-simple-icons-v154.zip_, it will download as _aegis-simple-icons-v154.apk_.

If you choose _154.zip_, it will download correctly as _154.zip_.

The new problem is that downloading either file, the downloaded file will be broken and won't work (it will throw an error when importing the ZIP file via Aegis settings).

Downloading it manually from GitHub it works as expected.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.7
