### ISSUE TITLE
"Include prereleases" option has opposite effect

### ISSUE THREAD

**Issue by bobdole4prez** [ImranR98/Obtainium#1583]
**Describe the bug**
The "Include prereleases" toggle in the "Additional Options" page for Brave browser (and I would expect other apps) is having the opposite effect it should: if "Include prereleases" is unset/false, then Obtainium offers the latest nightly version but if "Include prereleases" is set/true, then Obtainium offers the latest release.
Toggling the "Verify the 'latest' tag" option has no effect.

**To Reproduce**
1. Import the attached Obtainium settings
2. Open Brave from the App screen
3. Note version being offered
4. Open the additional options screen (pencil)
5. Toggle "Include prereleases" switch
6. Note version being offered.

**Screenshots and Logs**

With "Include prereleases" on ([obtainium settings export](https://github.com/ImranR98/Obtainium/files/15139571/obtainium-export-2024-04-27T14-47-52.264623.json))
![Screenshot_20240427-145802_Obtainium resized](https://github.com/ImranR98/Obtainium/assets/7410531/a31beaf0-5428-4f60-ad43-f94904efaa2b)

With "Include prereleases" off ([obtainium settings export](https://github.com/ImranR98/Obtainium/files/15139570/obtainium-export-2024-04-27T14-22-43.076550.json))
![Screenshot_20240427-145822_Obtainium resized](https://github.com/ImranR98/Obtainium/assets/7410531/c50df471-8ac7-4640-a78e-31e5c79b85b8)

**Please complete the following information:**
 - Device: OnePlus 7 Pro
 - OS: [DivestOS](https://divestos.org/) 20 (latest version: 2024/04/05) / Android 13
 - Obtainium Version: 1.1.6

**Additional context**
This was working fine before.  I discovered the problem today when I was offered an update for Brave that wouldn't install because it had a different package name (for the nightlys).

**Comment by rimaout** [comment]
I had a similar problem try to write `Releas` in the "Filter Titles by Regular Expression" section

![signal-2024-04-28-163141_002](https://github.com/ImranR98/Obtainium/assets/116072651/a23fc476-2db6-4b44-ae55-64157f0c8f45)

**Comment by ImranR98** [comment]
Yes, this has been covered in past issues. Brave do not correctly mark their betas/alphas with GitHub's yellow 'pre-release' tag so you need to rely on the release titles instead.

**Comment by gabrielparca** [comment]
had that same issue with Nightly, all good now that I detoggled the "include prereleases" option
