### ISSUE TITLE
Brave Browser doesn't run

### ISSUE THREAD

**Issue by rimaout** [ImranR98/Obtainium#1584]
Hi, I'm fairly certain this isn't an Obtanium bug, but I couldn't find another place to ask for help, so I'm reaching out here.

**Describe the bug:**
After uninstalling the Brave browser, which was initially installed via the Aurora Store, I attempted to reinstall it using Obtanium. Despite using the correct settings and trying different APKs, the app freezes upon launch. Uninstalling and reinstalling Brave via the Aurora Store also fails to resolve the issue, leaving me unable to use Brave on my device.

**Steps to Reproduce:**

1. Before installing Brave with Obtanium, I had it already installed via the Aurora Store.
2. I uninstalled Brave.
3. I installed Brave via Obtanium with the following settings: `{\"includePrereleases\"%3Afalse%2C\"fallbackToOlderReleases\"%3Atrue%2C\"filterReleaseTitlesByRegEx\"%3A\"Releas\"%2C\"filterReleaseNotesByRegEx\"%3A\"\"%2C\"verifyLatestTag\"%3Atrue%2C\"dontSortReleasesList\"%3Afalse%2C\"useLatestAssetDateAsReleaseDate\"%3Afalse%2C\"trackOnly\"%3Afalse%2C\"versionExtractionRegEx\"%3A\"\"%2C\"matchGroupToUse\"%3A\"\"%2C\"versionDetection\"%3Atrue%2C\"releaseDateAsVersion\"%3Afalse%2C\"useVersionCodeAsOSVersion\"%3Afalse%2C\"apkFilterRegEx\"%3A\"\"%2C\"invertAPKFilter\"%3Afalse%2C\"autoApkFilterByArch\"%3Atrue%2C\"appName\"%3A\"\"%2C\"shizukuPretendToBeGooglePlay\"%3Afalse%2C\"exemptFromBackgroundUpdates\"%3Afalse%2C\"skipUpdateNotifications\"%3Afalse%2C\"about\"%3A\"\"}"`.
4. I selected the universal arm APK (I also tried the others).
5. I installed it.

Now, when I try to open the app, it launches but freezes like this: 
<img width="200" alt="image" src="https://github.com/ImranR98/Obtainium/assets/116072651/6a994e77-924f-4a29-9271-db230051a8cb">

I've also tried uninstalling Brave and reinstalling it via the Aurora Store, but that doesn't seem to work either. It seems like I'm doomed to not use Brave anymore. 😅

**Comment by ImranR98** [comment]
If brave used to work but now doesn't, I'd suggest re-installing it from wherever you got the working version from (grab the exact version that used to work), then clear the app's data/cache in the OS settings.
