### ISSUE TITLE
app still refuse to add even after giving valid source GitHub link 

### ISSUE THREAD

**Issue by GreenArchiveForever** [ImranR98/Obtainium#1586]
![Screenshot_20240429-214235](https://github.com/ImranR98/Obtainium/assets/136427398/b872352e-9610-4aa4-8d20-d28cc644ca84)

what happened?
source:
https://github.com/tasks/tasks/releases

**Comment by ImranR98** [comment]
There are no APKs attached to those releases.

**Comment by GreenArchiveForever** [comment]
> There are no APKs attached to those releases.

so release should contain APK? i see
sorry about that

**Comment by ImranR98** [comment]
Yes, see Obtainium's releases section to compare.
