### ISSUE TITLE
Easier access to information about update

### ISSUE THREAD

**Issue by HFPasfho** [ImranR98/Obtainium#1588]
I'm currently following a few apps on github. Unfortunately, with each update I have to manually visit the appropriate repositories to see what the changes are. It would be useful to have a convenient way to check this directly in the application, as is possible, e.g. in F-Droid. This even applies to the Obtainium application itself, which doesn't look very good.

**Comment by ImranR98** [comment]
You can already click on the release date link (if underlined) to view the changelog for most apps. It will either open in-app (if supported) or in a browser.

**Comment by HFPasfho** [comment]
@ImranR98 Didn't know about that. It's very cryptic and unintuitive. Maybe it's worth thinking about a better design from the user experience point of view?

**Comment by ImranR98** [comment]
I think underlined text being a link isn't that unintuitive. But am open to suggestions as long as it doesn't increase UI clutter.

**Comment by HFPasfho** [comment]
I beg to differ. Blue underlined text in the context of a web browser is quite intuitive. A date written in gray underlined italic is not at all like that. It doesn't look like something you can click on at all. And the date itself as a link to the changelog is unintuitive.
