### ISSUE TITLE
NEW SOURCE Steam mobile

### ISSUE THREAD

**Issue by zachvlat** [ImranR98/Obtainium#159]
Here is the url for [Steam Mobile](https://media.steampowered.com/apps/steam-android/steam-3.0.0.apk)

**Comment by parkerlreed** [comment]
How would Obtanium know if there's an update? It's versioned so you would have to know ahead of time the new version number.

**Comment by ImranR98** [comment]
Should be possible. Version number is on [their website](https://store.steampowered.com/mobile#mobile_section).

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.14-beta
