### ISSUE TITLE
Time change

### ISSUE THREAD

**Issue by kaorlol** [ImranR98/Obtainium#1590]
It's April 30th for me and when I have an app that updated today, after refreshing the apps, it would change the updated time from 2024-4-30 to 2024-5-01

**To Reproduce**
2. Tap on '....'
4. See error -->
Go to obtainium 
Refresh apps
(Probably only shows if the app updated on a day that's right before a month)

**Screenshots and Logs**

https://github.com/ImranR98/Obtainium/assets/96850544/4202500e-7076-4f9a-9688-f65566cf46e1

Device: Pixel 7
OS: Android 15 1.2
Obtainium Version: 1.1.6

**Comment by ImranR98** [comment]
Forgot to close this earlier. Was fixed in https://github.com/ImranR98/Obtainium/releases/tag/v1.1.7
