### ISSUE TITLE
Most recent version from same day not automatically picked up

### ISSUE THREAD

**Issue by skwde** [ImranR98/Obtainium#1592]
**Prerequisites**

**Describe the bug**
I added an app from a git repo (https://github.com/ReVanced/revanced-manager) there are two releases on 2024-04-05, v1.20.1 and v1.20.0. Obtainium picks 1.20.1 as the most recent one.

Once installed it says v1.20.0 Installed/Latest.
Though there is a newer release.

**To Reproduce**
1. Open the app and search for revanced
2. choose the https://github.com/ReVanced/revanced-manager repo
3. use default settings
4. see that it doesn't pick the newest version

**Please complete the following information:**
 - Device: Pixel 7a
 - OS: GOS
 - Obtainium Version: V1.1.6

**Additional context**
As a workaround, enabling `Verify the 'latest' tag` makes obtainium pick v1.20.1.

**Comment by ImranR98** [comment]
The "verify latest" toggle was added for cases like this, where the latest release by date isn't actually the one marked as "latest". Just leave that on.
