### ISSUE TITLE
Issue to add app, rate limit error

### ISSUE THREAD

**Issue by Karthikn341** [ImranR98/Obtainium#16]
When i try add github app..get error rate limit reached, try again in 27.72...... minutes

**Comment by ImranR98** [comment]
Unfortunately nothing can be done about this as GitHub imposes a rate limit on their API. You need to wait up to 30 minutes for the limit to be reset.

**Comment by Karthikn341** [comment]
Mm thanks..

May i know how to add pre release apk?

https://github.com/florisboard/florisboard/releases/download/v0.4.0-alpha04/florisboard-0.4.0-alpha04.apk

**Comment by ImranR98** [comment]
Right now prerelease apks are only grabbed if a full release is not found. But I'll try to add a manual toggle for this in the next release - I'll make a separate issue for that.

**Comment by Karthikn341** [comment]
> Right now prerelease apks are only grabbed if a full release is not found. But I'll try to add a manual toggle for this in the next release - I'll make a separate issue for that (#18).

Thanks..
