### ISSUE TITLE
[QUERY] Apps installed through Obtainium are still managed by Google Play Services

### ISSUE THREAD

**Issue by github-random-827495** [ImranR98/Obtainium#1601]
Hello - I have recently migrated to GrapheneOS and initially used Google Play Services to install some applications. I have since heard of Obtainium and are trying to migrate to it and move away from Google Play Services as much as possible. I have noticed that some applications (Signal, RedReader) once installed through Obtainium still show in Google Play Services and Google will still update the app!

Am I doing something wrong? Is this expected?

**Comment by pabloscloud** [comment]
Yes, this is what will happen if Auto updates are on inside of Google play store.

You can disable auto-update of apps in the play store (also individually) so that only obtainium updates the(-se) apps.

**Comment by DarkCrypt** [comment]
> Is this expected?

This is common like pabloscloud said. It happens because the apps are the same (app ID/signature).

> move away from Google Play Services as much as possible.

I hope you do! If I can't update an app with Obtainium, I use Aurora Store as a Play Store alternative.
