### ISSUE TITLE
Add an option to send request via POST method

### ISSUE THREAD

**Issue by MoeBakaW** [ImranR98/Obtainium#1603]
**Describe the feature**

Some apps get new versions information via their in-app API, and sending request via POST method, but Obtainium app only provides HTML source and get the webpage via GET method.

So I am requesting to add the option to get app updates via POST (it would be nice to be able to add parameters)

**Describe alternatives you've considered (if applicable)**

**Additional context**

**Comment by ImranR98** [comment]
It's unlikely this could be added in a generic way thatvwoupd work for a large number of such sources, since I expect most such APIs would be totally different from each other. Do you have an example of a source like this?

**Comment by ImranR98** [comment]
Closing due to no response
