### ISSUE TITLE
Sources with use dates instead of version or use both in apk name

### ISSUE THREAD

**Issue by ghazzor** [ImranR98/Obtainium#1609]
**Describe the bug**
As stated in the title , if a build was made on 8/12/24 and one on 30/5/24 , it selects the older build  

**To Reproduce**
1. Add 'https://auroraoss.com/downloads/AuroraStore/Nightly' as a source
2. It installs a older build

**Please complete the following information:**
 - Device: galaxy m21
 - OS: oneui 4.1 / android 12
 - Obtainium Version:   v1.1.7

**Comment by ghazzor** [comment]
Adding a way to take the last link (just like how it can select the first link) would fix the issue here ig

**Comment by ImranR98** [comment]
This is already possible - there's a "take first link" toggle (by default, links are sorted and the last one is picked).

**Comment by ghazzor** [comment]
> This is already possible - there's a "take first link" toggle (by default, links are sorted and the last one is picked).

That just picks the older version

**Comment by ImranR98** [comment]
I see the issue. The APK file names have a weird date formatting where the day comes first, so the Automatic sorting doesn't give you the right order. Just enable the "skip sorting" toggle and leave the "pick first" disabled.

**Comment by ghazzor** [comment]
> I see the issue. The APK file names have a weird date formatting where the day comes first, so the Automatic sorting doesn't give you the right order. Just enable the "skip sorting" toggle and leave the "pick first" disabled.

Still no luck , it's still the older version of 30 4 2024
