### ISSUE TITLE
Adding gitlab repo with multiple APK

### ISSUE THREAD

**Issue by rancidfrog** [ImranR98/Obtainium#1614]
I am trying to add bunny media editor, https://gitlab.shinice.net/pixeldroid/bunny
But, I get multiple options:
![](https://i.postimg.cc/Nj5gvRJ3/Screenshot-20240510-141807-Obtainium-1.png)

How to select the correct version, i.e. APK (arm64-v8a)
Will the code 101,102,103,104 change with new versions?
Because if I check manually then it should be 102

**Comment by rancidfrog** [comment]
https://gitlab.shinice.net/pixeldroid/bunny/-/releases
![](https://i.postimg.cc/j2dpQrBp/Screenshot-20240510-143112-Cromite-1.png)
APK (arm64-v8a) --> https://gitlab.shinice.net/pixeldroid/bunny/-/releases/1.0/downloads/package/bunny-1.0-102.apk

**Comment by ImranR98** [comment]
You can use the apk filter for this.

**Comment by rancidfrog** [comment]
> You can use the apk filter for this.

Is there an easy way to do it?
You should have a way for normal users to add filters with reduced complexity,
Playing with the forms does not seem to work:
![](https://i.postimg.cc/QdRpWX64/Screenshot-20240603-224325-Obtainium-1.png)
