### ISSUE TITLE
Problem with the version with celsoazevedo source

### ISSUE THREAD

**Issue by LK024** [ImranR98/Obtainium#1615]
By adding celsoazevedo as a source and configuring the various filters (found in another issue here on GitHub) all the content of the page is taken as a version 
![Screenshot_20240511-105728](https://github.com/ImranR98/Obtainium/assets/99796580/d0bd7b72-42d5-4f24-ae8a-9c5da9c34bcd)

For example in this screenshot it should stop at V7

**Comment by ImranR98** [comment]
Your version extraction regex is wrong. This is not a bug or feature request so the discussions tab would be a better place to put it.
