### ISSUE TITLE
It is recommended to add a "source" logo to the right of the software name

### ISSUE THREAD

**Issue by nichousha123** [ImranR98/Obtainium#1624]
The following content comes from Google Translate

![Screenshot_20240516_010627](https://github.com/ImranR98/Obtainium/assets/147991448/8edd0770-0951-460d-9e42-5c324500a91e)

as the picture shows

Determine which platform it comes from based on the pasted "source URL", and then indicate it in the red box

**Comment by ImranR98** [comment]
This would add too much clutter. You can already filter by source if needed.
