### ISSUE TITLE
New Firefox Android APK download sources

### ISSUE THREAD

**Issue by pq15239** [ImranR98/Obtainium#1625]
As of version 126, the previous Firefox Android APK download source:

- https://github.com/mozilla-mobile/firefox-android

now apparently has been replaced with:

- https://hg.mozilla.org/mozilla-central

But it does not seem to offer APK files.

And neither does:

- https://www.mozilla.org/firefox/browsers/mobile/android

There seems to be:

- https://download.cdn.mozilla.net/pub/fenix/releases/126.0/android/
- https://ftp.mozilla.org/pub/fenix/releases/126.0/android/

But Obtainium does not seem to support this URL. And unlike for the desktop version of Firefox, there also does not seem to be a directory that always points to the latest version, such as:

- https://download.cdn.mozilla.net/pub/firefox/releases/latest/
- https://ftp.mozilla.org/pub/firefox/releases/latest/

Is there a way to get automatic Firefox Android APK updates working again?

**Comment by baduhai** [comment]
I'm trying to fetch Firefox and Firefox Klar from these links, but obtanium just crashes when I try. As far as I can tell, these links should always return the latest release.

https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v3.firefox-android.apks.fenix-release.latest.arm64-v8a/artifacts/public%2Fbuild%2Ftarget.arm64-v8a.apk

https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v3.firefox-android.apks.klar-release.latest.arm64-v8a/artifacts/public%2Fbuild%2Ftarget.arm64-v8a.apk

**Comment by ImranR98** [comment]
@baduhai if you want to add a direct APK link, you need to pick "Direct APK Link" in the "Source Override" dropdown menu.

@pq15239 you can add https://download.cdn.mozilla.net/pub/fenix/releases/ or https://ftp.mozilla.org/pub/fenix/releases/ and use intermediate links to tell Obtainium how to find the latest version. See the Wiki or other issues where the HTML source, intermediate links, etc. have been explained with examples.

**Comment by johannesneyer** [comment]
I am having trouble adding this as HTML source. For testing I entered https://download.cdn.mozilla.net/pub/fenix/releases/126.0/android/fenix-126.0-android-arm64-v8a/ as source but Obtainium always shows a `Not Found` error. Shouldn't Obtainium, without changing any settings, automatically find the apk on that link?

**Comment by Idesmi** [comment]
https://download.cdn.mozilla.net/pub/fenix/releases/

Intermediate links:

```
[0-9]+\.[0-9]b[0-9]+/$

android/$

fenix-[0-9]+\.[0-9]b[0-9]+-android-arm64-v8a/$
```

I would like to download the latest beta.
I don't understand what am I doing wrong

**Comment by johannesneyer** [comment]
@ImranR98  any ideas?

**Comment by ImranR98** [comment]
Your regex is fine. Looks like there's a bug - Obtainium removes the trailing slash from the URL. That's usually fine but in this case the URL without a slash gives a 404: https://download.cdn.mozilla.net/pub/fenix/releases

Will be fixed in the next release.

**Comment by ImranR98** [comment]
It should work down: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.10

**Comment by johannesneyer** [comment]
great, thank you. it works now
