### ISSUE TITLE
Failed to get the release date for an old AppGallery app

### ISSUE THREAD

**Issue by StSav012** [ImranR98/Obtainium#1630]
Obtainium fails to find the release date for `https://appgallery.cloud.huawei.com/appdl/C104450749` and, possibly, other apps published years ago.

#### Steps to Reproduce:
1. Add an app using this URL: `https://appgallery.cloud.huawei.com/appdl/C104450749`.
1. Click the *Add* button.
1. See error: `FormatException: Trying to read yy from ru-/d-l/-ap-pd-l/-ap-pl-ic-at-io-n/-ap-k/-32-/3-2d-dd-aa-c6-30-34-75-b9-6d-cb-98-04-da-16-96-4/-16-66-97-26-48-78-4--16-55-e5-a0--e-85-5--46-33--9-34-6--42-66-7a-74-4c-5c at 0` or another beginning.

#### Investigation
The server redirects to `https://appdlc-drru.hispace.dbankcloud.ru/dl/appdl/application/apk/32/32dddaac6303475b96dcb9804da16964/1666972648784-1655e5a0-e855-4633-9346-42667a744c5c.apk?maple=0&trackId=0&distOpEntity=HKS`

The app adds numerous dashes due to the lines:
https://github.com/ImranR98/Obtainium/blob/cbe41de7342c90c6c02e308ec0317d76805d8bf8/lib/app_sources/huaweiappgallery.dart#L80-L84

Before that, the app gets the first part of the URL:
https://github.com/ImranR98/Obtainium/blob/cbe41de7342c90c6c02e308ec0317d76805d8bf8/lib/app_sources/huaweiappgallery.dart#L76-L77

Namely,
- `res.headers['location']` is `https://appdlc-drru.hispace.dbankcloud.ru/dl/appdl/application/apk/32/32dddaac6303475b96dcb9804da16964/1666972648784-1655e5a0-e855-4633-9346-42667a744c5c.apk?maple=0&trackId=0&distOpEntity=HKS` (or another host, depending on the load balancer).
- `res.headers['location']?.split('?')[0]` is `https://appdlc-drru.hispace.dbankcloud.ru/dl/appdl/application/apk/32/32dddaac6303475b96dcb9804da16964/1666972648784-1655e5a0-e855-4633-9346-42667a744c5c.apk` (or another host, depending on the load balancer).
- `res.headers['location']?.split('?')[0].split('.').reversed.toList()[1]` is `ru/dl/appdl/application/apk/32/32dddaac6303475b96dcb9804da16964/1666972648784-1655e5a0-e855-4633-9346-42667a744c5c` (or another beginning, depending on the load balancer).
See that the latter contains no `'.'`.

#### The Solution
Check whether `relDateStr` contains a `'/'`.
- If so, 
    ```dart
    var relDate = DateTime.fromMillisecondsSinceEpoch(int.parse(relDateStr?.split('/').last.split('-').first));
    ```
    Or something like that. It's my first Dart line.
- Otherwise, use the existing code:
    https://github.com/ImranR98/Obtainium/blob/cbe41de7342c90c6c02e308ec0317d76805d8bf8/lib/app_sources/huaweiappgallery.dart#L78-L87

**Comment by ImranR98** [comment]
This URL seems to be different from AppGallery pages I've seen before - it leads to a direct download, and https://appgallery.huawei.com/app/C104450749 is empty. It might not be possible to use it since we can't get a valid app ID or release date. Do you have a link to the actual app listing page?

**Comment by StSav012** [comment]
That seems to mean that the app is geo-restricted. I haven't expected that.

The page I see following https://appgallery.huawei.com/app/C104450749 looks like this:
![image](https://github.com/ImranR98/Obtainium/assets/10685968/c1d1475b-6117-4882-a4af-d284a0751116)

The page also reads that the app was updated on 10/31/2022. I couldn't find another app that's _that_ old.

I'm unsure if the issue is relevant for anyone but me, then.
