### ISSUE TITLE
Auto add installed apps for update check

### ISSUE THREAD

**Issue by NripPrajapat** [ImranR98/Obtainium#1632]
You should check the app called APK-updater.
Com.apkupdater
https://github.com/rumboalla/apkupdater

What I am asking is, it should automatically add the apps that are already installed on the device. What that app does is it checks the updates from all the sources it has. It saves the time of adding all the installed apps. One doesn't have to add them one by one. Even the sources are similar, that your app uses and that app.

Why I am asking?
I don't want to have two apps, that does almost same things but can't uninstall both because of their unique features.

**Comment by ImranR98** [comment]
Please search through existing issues before creating new ones.
