### ISSUE TITLE
Add an option to change the installer

### ISSUE THREAD

**Issue by I21b** [ImranR98/Obtainium#1634]
**Describe the feature**
Just like the title.

**Additional context**
Use other installer with "open with" menu and set it to default.

**Comment by ImranR98** [comment]
This has been discussed before. There's no Flutter plugin I know of that allows you to install apps through the "open with" menu while waiting for and returning the install result - they all do the installs asynchronously and do not return a pass/fail/cancel result. Given that there's a lot of functionality built around the assumptions that installs are synchronous, this isn't going to be implemented (unless that changes).

**Comment by I21b** [comment]
> This has been discussed before. There's no Flutter plugin I know of that allows you to install apps through the "open with" menu while waiting for and returning the install result - they all do the installs asynchronously and do not return a pass/fail/cancel result. Given that there's a lot of functionality built around the assumptions that installs are synchronous, this isn't going to be implemented (unless that changes).

Just add an option that lets us open the apk?
