### ISSUE TITLE
Understanding version extraction regexp

### ISSUE THREAD

**Issue by breversa** [ImranR98/Obtainium#1636]
Hello!

I'm trying to set up Obtainium to get the latest version of sherpa-oonx for my language from https://k2-fsa.github.io/sherpa/onnx/tts/apk-engine.html

The (current) latest version I'm looking for is `https://huggingface.co/csukuangfj/sherpa-onnx-apk/resolve/main/tts-engine-2/sherpa-onnx-1.9.25-arm64-v8a-fr-tts-engine-vits-piper-fr_FR-upmc-medium.apk`

The version is `1.9.25`

My current set up is the following:
- Source = `https://k2-fsa.github.io/sherpa/onnx/tts/apk-engine.html`
- ~~Follow first link (as newer versions are at the top of the list)~~ This gives the *oldest* version :-/
- Sort on the last segment of the link (as all links differ only by the filename)
- Filter APKs by regexp: `sherpa-onnx-.+-arm64-v8a-fr-tts-engine-vits-piper-fr_FR-upmc-medium.apk` (basically leaving only the version as `.+`)

And this works well enough to get the latest version, however I'm unable to extract the version string (here, `1.9.25`)

Am I correct that the version extraction regexp should include one (and only one) **capture group** that will give the version? It's never mentioned in the documentation: https://github.com/ImranR98/Obtainium/wiki#html

If that's the case, the correct version extraction regex should then be `sherpa-onnx-(.+)-arm64-v8a-fr-tts-engine-vits-piper-fr_FR-upmc-medium.apk` ?

Also, since that download page is very long, is there any performance improvement that can be made in setting up Obtainium?

**Comment by ImranR98** [comment]
There can be any number of groups. You can use the "match group" to specify which one you want. In your case it should be '1' for the first group ('0' is the whole match).

**Comment by breversa** [comment]
… but there needs to be capture groups, right?

Otherwise, how can I define that I only want the `1.9.25` part of `https://huggingface.co/csukuangfj/sherpa-onnx-apk/resolve/main/tts-engine-2/sherpa-onnx-1.9.25-arm64-v8a-fr-tts-engine-vits-piper-fr_FR-upmc-medium.apk`?

**Comment by breversa** [comment]
Found it!

By using `-(\d+(\.\d+)*)-` as version extraction regexp, and just 1 as correspondance group, I was able to extract `1.9.25`. Thanks for your help! :-)

Any hint regarding the performance improvement?
Would using longer regexp (with static parts) be more efficient?

Ex:
`sherpa-onnx-(\d+(\.\d+)*)-arm64-v8a-fr-tts-engine-vits-piper-fr_FR-upmc-medium`
instead of
`-(\d+(\.\d+)*)-`
?

**Comment by ImranR98** [comment]
I don't think there would be any significant performance issue.

**Comment by breversa** [comment]
Note to self for Sherpa TTS fr_FR Siwis low:

- URL: https://k2-fsa.github.io/sherpa/onnx/tts/apk-engine.html
- Sort on last link segment: on
- Version extraction regex: `-(\d+(\.\d+)*)-`
- Use app version code: on
- APK filter regex: `sherpa-onnx-.+-arm64-v8a-fr-tts-engine-vits-piper-fr_FR-siwis-low.apk`
- Filter by CPU: on
