### ISSUE TITLE
default 3rd party app icon not visible in dark mode

### ISSUE THREAD

**Issue by grrrrr** [ImranR98/Obtainium#1637]
**Describe the bug**

When in dark mode, if an app added to obtanium does not yet have an app icon, the default icon is very hard to view (purple on black).    

If the theme for obtanium is light the default icon is more visible.

**Screenshots and Logs**

![icon2](https://github.com/ImranR98/Obtainium/assets/1025506/4a78a50f-4a84-4166-ad81-7940322530ff)

**Please complete the following information:**
 - Device: Pixel 7a
 - OS: GrapheneOS
 - Obtainium Version:  1.1.9

**Comment by ImranR98** [comment]
Improved the contrast to make it more consistent: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.10

**Comment by grrrrr** [comment]
Thanks @ImranR98  did the icon get included in that push or was it a code change only?  It still looks similar to what it was

**Comment by ImranR98** [comment]
The change might not be noticeable without a side by side comparison - I only increased the opacity by around 10%. It's a subjective thing but I don't want the placeholder icon to stand out too much.

**Comment by grrrrr** [comment]
ok,  makes sense.
