### ISSUE TITLE
Version extraction regex fails

### ISSUE THREAD

**Issue by Araxeus** [ImranR98/Obtainium#1640]
**Prerequisites**

**Describe the bug**
Version extraction regex fail when set.

**To Reproduce**
Add a version extraction regex, example provided below

**Screenshots and Logs**

![Screenshot_2024-05-23-00-19-51-213_dev.imranr.obtainium-edit.jpg](https://github.com/ImranR98/Obtainium/assets/78568641/463a67dd-b8a6-4061-81d7-3b60a2d3149d)
![Screenshot_2024-05-23-00-21-26-327_dev.imranr.obtainium-edit.jpg](https://github.com/ImranR98/Obtainium/assets/78568641/d2c8c092-ef02-451e-8613-aa5f22d959d6)

**Please complete the following information:**
 - Device: Poco F3
 - OS: MIUI 14
 - Obtainium Version: 1.1.9

**Additional context**

Here is an example:
(It works ok if you remove regex extraction )

https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/{"id":"tv.twitch.android.app","url":"https://github.com/j-hc/revanced-magisk-module","author":"j-hc","name":"Twitch","preferredApkIndex":0,"additionalSettings":"{\"includePrereleases\":false,\"fallbackToOlderReleases\":true,\"filterReleaseTitlesByRegEx\":\"\",\"filterReleaseNotesByRegEx\":\"Twitch:\",\"verifyLatestTag\":false,\"dontSortReleasesList\":false,\"useLatestAssetDateAsReleaseDate\":false,\"trackOnly\":false,\"versionExtractionRegEx\":\"twitch-revanced-v(.+)-all\",\"matchGroupToUse\":\"1\",\"versionDetection\":false,\"releaseDateAsVersion\":false,\"useVersionCodeAsOSVersion\":false,\"apkFilterRegEx\":\"twitch-revanced\",\"invertAPKFilter\":false,\"autoApkFilterByArch\":false,\"appName\":\"Twitch-Revanced\",\"shizukuPretendToBeGooglePlay\":false,\"exemptFromBackgroundUpdates\":false,\"skipUpdateNotifications\":false,\"about\":\"\"}","overrideSource":null}

**Comment by ImranR98** [comment]
Version extraction can only help you trim down the full version string when needed (in this case, that's `20220941`). The only exception is the HTML source which has more complex version extraction. So it isn't possible to use it in this case.

**Comment by Araxeus** [comment]
Why can't it extract version from the apk name?
It seems pretty easy to do?

**Comment by y-hbb** [comment]
Is it possible to get the version from filename instead of tag? Can it be added as a flag?
