### ISSUE TITLE
APKMirror updates

### ISSUE THREAD

**Issue by vasilispngs** [ImranR98/Obtainium#1642]
How i can fix this?
Both are stable versions.

![Screenshot_20240523-110105_Obtainium](https://github.com/ImranR98/Obtainium/assets/110207897/37d73651-1586-4b62-96c0-bf1485da3d39)
![Screenshot_20240523-110230_Obtainium](https://github.com/ImranR98/Obtainium/assets/110207897/581bae8a-35bb-44c2-8803-9a52763044a3)

**Comment by ImranR98** [comment]
Please read the Wiki, especially the section on track-only apps. And follow the issue template (I can't tell what the problem is meant to be here).

**Comment by ImranR98** [comment]
Since it's a track-only source, the "OS version detection" is disabled. So Obtainium has no way of knowing the real version you have on your OS. You can use the "mark as updated" button to correct this.
