### ISSUE TITLE
in app search, when github selected don't search forked repos

### ISSUE THREAD

**Issue by noriban** [ImranR98/Obtainium#1651]
Tried searching some forked app, like [Round-Sync](https://github.com/newhinton/Round-Sync), but its not searchable

Xiaomi mi note 10 lite
android 11

**Comment by ImranR98** [comment]
Not an Obtainium issue - the repo doesn't show up on GitHub's own search page either: https://github.com/search?q=round-sync&type=repositories
The search API also doesn't have any params for forks (they seem to be always included): https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-repositories
