### ISSUE TITLE
Obtainium 0.8.18 keeps suggesting to upgrade Chromium although there is no update

### ISSUE THREAD

**Issue by hariskar** [ImranR98/Obtainium#166]
Maybe the long app title causes the problem.
This is Chromium I use:
https://github.com/macchrome/droidchrome

**Comment by ImranR98** [comment]
The GitHub title says 108.0.5389.123 but the actual app version is 108.0.5359.123. Not sure if this is intentional or a mistake on their end, but it's why version detection causes a mismatch.

**Comment by hariskar** [comment]
OK, I see, thank you for explanation and thank you for great app!!!

**Comment by ImranR98** [comment]
Currently playing around with a manual "disable version detection" toggle that can be used for Apps like this.

**Comment by ImranR98** [comment]
You should be able to turn off version detection now: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.22-beta
