### ISSUE TITLE
[Bug] App already added

### ISSUE THREAD

**Issue by ngocanhtve** [ImranR98/Obtainium#1661]
**Describe the bug**
When an app has been previously imported using a json file but not installed, Then add the link to the Add page for manual installation, Obtainium announces that the app already added instead of proceeding with the installation. 

**To Reproduce**
1. Import apps from json file
2. Add a link (duplicates one of the imported apps) from Add page

**Screenshots and Logs**

![](https://github.com/ImranR98/Obtainium/assets/125894401/21a45c84-d152-4432-850c-2133440bbb2c)
![](https://github.com/ImranR98/Obtainium/assets/125894401/5948c51e-98c3-45f8-979d-6085a84ee3d0)

**Please complete the following information:**
 - Device: Sony Xperia 1.
 - OS: DerpfestOS, Android 14, build AP1A.240505.005.
 - Obtainium Version: v1.1.10.

**Additional context**
Even though the app already added, but not yet installed, the user is installing it manually, Obtainium should install it instead of refusing to install just because a link was previously imported but not installed.

**Comment by ImranR98** [comment]
This is intended behaviour - the 'Add' page is for adding a new app that isn't already on the list. If you want to install an existing app, you can use the install button on the main list page or the app's details page.

**Comment by ngocanhtve** [comment]
It's really illogical
