### ISSUE TITLE
Do not show the change date with some applications

### ISSUE THREAD

**Issue by Sami32** [ImranR98/Obtainium#1664]
Do not show the application change date with some of the non installed in track-only mode and one installed manually.

**To Reproduce**
1. Open Obtainium and leave it auto-update Apps
2. Look at the displayed applications informations
3. Some non installed applications (Kiwi browser, aTalk) in track-only mode will miss their change date information

**Screenshots and Logs**
![IMG_20240610_122439](https://github.com/ImranR98/Obtainium/assets/18471069/b4494df0-1a71-411d-950b-9ea5e39cf404)

**Please complete the following information:**
 - Device: xiami Redmi Note 4
 - OS: Google Android 7.0
 - Obtainium Version: 1.1.10

**Additional context**
Kiwi browser (not installed, Track-only mode) & SMSsecure (Installed manually, updated)
https://github.com/kiwibrowser/src.next/releases
https://f-droid.org/packages/org.smssecure.smssecure/

**Comment by Sami32** [comment]
When the realeases page is empty Obtainium doesn't provide any date change information.

My suggestion is that in such cases where we track-only some applications, the _**Tags**_ page date information should be used instead.

https://codeberg.org/iNPUTmice/Conversations/tags
https://github.com/cmeng-git/atalk-android/tags

**Comment by ImranR98** [comment]
For GitHub I'm not sure where the dates on the tags page come from, but they're not available in the API request. For example: https://api.github.com/repos/ImranR98/Obtainium/tags

Codeberg on the other hand does provide a date, for example: https://codeberg.org/api/v1/repos/iNPUTmice/Conversations/tags
Same goes for GitLab: https://gitlab.com/api/v4/projects/AuroraOSS%2FAuroraStore/repository/tags
So I'll add those in the next release.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.11

**Comment by Sami32** [comment]
Nice, thanks.

But your code still fail to pick the date at GitHub release with the above mentioned repo:
https://api.github.com/repos/kiwibrowser/src.next/releases

About GitHub Tags creation it can be got from their commit:
https://api.github.com/repos/ImranR98/Obtainium/commits/06cbe74c6c6518c556b2c7e04ffd9c44f29236fe

Or with TAG_COMMIT_DATE from the GitHub GraphQL API v4:
https://docs.github.com/en/graphql

**Comment by ImranR98** [comment]
It's not practical to make a separate API request for each tag to get its release date from the commit API. We would need one API endpoint that returns all the tags plus their release dates, like in the codeberg example.

**Comment by Sami32** [comment]
I agree, they could have cared more for their API tags but we've to deal with it, sadly:

https://pub.dev/packages/graphql#query
https://github.com/juancastillo0/leto

https://github.com/orgs/community/discussions/37203
