### ISSUE TITLE
Ability to update from GitHub actions tab.

### ISSUE THREAD

**Issue by b2sql** [ImranR98/Obtainium#1665]
Add ability to download files from repo's action tab. Some Devs don't push through "release" tab, but through "actions". Please allow to download from actions with branch choose support.

**Comment by DwainZwerg** [comment]
See https://github.com/ImranR98/Obtainium/issues/1599

**Comment by kaorlol** [comment]
it doesnt look like he'll be adding that soon but you can see these two things i made to help out with that. 

https://github.com/kaorlol/obtainium-helper
https://github.com/kaorlol/obtainium-artifact-downloader

**Comment by kaorlol** [comment]
> > it doesnt look like he'll be adding that soon but you can see these two things i made to help out with that.
> > https://github.com/kaorlol/obtainium-helper https://github.com/kaorlol/obtainium-artifact-downloader
> 
> Thank you, I'll give it a shot.

No problem

**Comment by ImranR98** [comment]
Duplicate of #102

**Comment by DwainZwerg** [comment]
@kaorlol How do your scripts work? How can I run them?

**Comment by kaorlol** [comment]
> @kaorlol How do your scripts work? How can I run them?

Just follow the readme, it says fork the repo, and change the settings.json to use whatever app you want. The readme also explains how everything in settings.json works.

**Comment by DwainZwerg** [comment]
That is clear to me so far (I have read). But what do I do with the forked repo or the changed settings.json? The workflow update-checker can only be executed in the browser? And then is something downloaded or do I just get notifications about what needs to be updated?

**Comment by kaorlol** [comment]
Oh you go to the GitHub actions tab after you've updated the settings.json
and run the workflow. Also if you want to test it without running the
workflow you can also clone the repo to a folder on your PC and install
golang and run it that way just for testing.

**Comment by b2sql** [comment]
> Oh you go to the GitHub actions tab after you've updated the settings.json
> and run the workflow. Also if you want to test it without running the
> workflow you can also clone the repo to a folder on your PC and install
> golang and run it that way just for testing.
> […](#)

Your scripts are gone now. Would you mind re-creating?
