### ISSUE TITLE
Add support for multiple API

### ISSUE THREAD

**Issue by 9Mik9** [ImranR98/Obtainium#1667]
I have many apps in Obtainium (like 120+ apps mostly GitHub) so my single GitHub API can't even handle 1 refresh, so I want to request feature that Obtainium can store more than 1 API(both GitHub and GitLab if possible) and if source response with something like "too many requests (rate limited)" then use second API, third, forth, fifth, ... . Something like that. Is it possible?

**Comment by 9Mik9** [comment]
> a gh api token can take 5000 requests per hour it can handle so idk how youre getting that.
> 
> https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28

Well, in my case, my GitHub API keep hitting me with "too many requests (rate limited)"

**Comment by DarkCrypt** [comment]
Is your access token expired?

**Comment by ImranR98** [comment]
> If source response with something like "too many requests (rate limited)" then use second API, third, forth, fifth

I think this is out of scope for Obtainium - the rate limit (5k requests as noted above) for authenticated users should be more than enough.

If you really need more than 5k requests an hour, maybe you could setup a proxy server that accepts your requests and forwards them to GitHub with one of many stored tokens. Then force Obtainium to use the "GitHub" source for your non-GitHub API. But I'm guessing your token is just expired as suggested above.

**Comment by 9Mik9** [comment]
> > If source response with something like "too many requests (rate limited)" then use second API, third, forth, fifth
> 
> I think this is out of scope for Obtainium - the rate limit (5k requests as noted above) for authenticated users should be more than enough.
> 
> If you really need more than 5k requests an hour, maybe you could setup a proxy server that accepts your requests and forwards them to GitHub with one of many stored tokens. Then force Obtainium to use the "GitHub" source for your non-GitHub API. But I'm guessing your token is just expired as suggested above.

Ok, thank you. I will try some other things myself to resolve this.🥰👍
