### ISSUE TITLE
Impossible to add an App from a GIT repo?

### ISSUE THREAD

**Issue by Sami32** [ImranR98/Obtainium#1679]
Cannot add this App in Track-Only mode:
https://git.silence.dev/Silence/Silence-Android/-/tags

**To Reproduce**
1. Go to 'Add App'
2. In the source URL type 'https://git.silence.dev/Silence/Silence-Android/-/tags'
3. Enable 'Track-Only'
4. Add and see error "Could not find a suitable release"

**Screenshots and Logs**
![IMG_20240618_094802](https://github.com/ImranR98/Obtainium/assets/18471069/33664344-f307-4c0a-823c-ce8e5d68eda1)

**Please complete the following information:**
 - Device: Xiaomi Redmi Note 4
 - OS: Google Android 7.0
 - Obtainium Version: 1.1.11

**Comment by Sami32** [comment]
https://git.xx.network/elixxir/client-android/-/tags

**Comment by imwints** [comment]
Also both repositories don't publish any releases so unless you find a binary distribution for these apps you're out of luck here

**Comment by Sami32** [comment]
@imwints You seem have missed the bug that it shouldn't search a release in **Track-Only** mode.
And document that Obtainium only support GitLab, GitHub and Codeberg or so?

**Comment by imwints** [comment]
Yes I missed that. However you still need to tell Obtainium that this is a gitlab repository, so you need to set `Override Source` to `Gitlab`

**Comment by Sami32** [comment]
@imwints Good point +1
I missed that one.

**Comment by ImranR98** [comment]
Sounds like this was resolved.
