### ISSUE TITLE
Pull to refresh not possible with small app list

### ISSUE THREAD

**Issue by imwints** [ImranR98/Obtainium#1680]
It is not possible to refresh the main page when the list of apps doesn't cover the whole screen or in other words the list of apps is not scroll-able.

I can reproduce this on any fresh install with only Obtainium tracking itself.

 - Device: Not relevant
 - OS: Not relevant
 - Obtainium Version: 1.1.11

I'm pretty sure that this is a regression as this worked for me before some recent update™

**Comment by OsitoGrande** [comment]
Hi, I can concur with this finding.
All good on 1.1.10 - but upgrading to 1.1.11 creates this problem. Also happens with fresh installs of 1.1.11. Checked on Google Pixel 8/Android 14 and Samsung S24/Android 14. (With latest available security updates).

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.12

**Comment by OsitoGrande** [comment]
Perfect! Confirmed fixed by end user too 😉.
Thank you! 🤩
