### ISSUE TITLE
Adding F-Droid Third-Party Repo to "Add App" search

### ISSUE THREAD

**Issue by martin-braun** [ImranR98/Obtainium#1681]
- Tab "Add App" lists "F-Droid Third-Party Repo (Searchable)" under "Supported Sources", so I assumed, I can add this somewhere, however
- Search (Some Sources Only) would only allow me to pick "F-Droid Official"
- As the documentation points out, I can search my third party source in "Import/Export"/"Search Source"/"F-Droid Third-Party Repo", this indeed works, but
- My third party source will not be remembered. Say I want to add another app, I still need to grab the URL and paste it in

My intuition was searching for a way to add a third party repo, so that "Add App"/"Search (Some Sources Only)" would also allow me to pick "F-Droid Third-Party Repos" (missing) to search through my own repos that I added.

I think this would be a great addition to avoid so much confusion.

_Originally posted by @martin-braun in https://github.com/ImranR98/Obtainium/issues/1671#issuecomment-2171468759_

There are some possible solutions to the problem:

- A section in the settings to maintain third party repositories for F-Droid
- Remembering previously searched third party repositories and auto-search them under "Add App" - this would require to have any way to remove third party repositories again

Thoughts?

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.12

**Comment by johnkennyuk** [comment]
> @ImranR98 Awesome, this is the first step in the right direction. However, I was having in my mind that it would be great to have a way to store those third party repositories in some way to not having to paste them every time I search through them.
> 
> This is a low priority issue though.

Agree with this, I recently discovered Obtanium. Went through the importing from source urls then picked F-Droid 3rd party repo and input the url wirh the search term. It worked fine and the app was imported, but I too had the assumption that the source urls for the F-Droid 3rd party repos would be stored so that previously used urls could be recalled easily without having to dig them out and reinput. 

Thanks
