### ISSUE TITLE
[UIX enhancement]: Apps name truncated, overlayed

### ISSUE THREAD

**Issue by Sami32** [ImranR98/Obtainium#1683]
Extending a little the available Apps name field will avoid many overlaying:
(It seem that using at least 3 more characters for the name field shouldn't make the overall UIX ugly or unreadable?)

![IMG_20240619_221009](https://github.com/ImranR98/Obtainium/assets/18471069/084f780c-b099-4e87-a333-f71d868126c9)
![IMG_20240619_220943](https://github.com/ImranR98/Obtainium/assets/18471069/e36b3cae-0036-46c4-8a18-f0b984dd9256)
![IMG_20240619_220909](https://github.com/ImranR98/Obtainium/assets/18471069/2e36f8d3-6774-4eb1-8ba2-3c0b2c307ca7)

**Comment by ImranR98** [comment]
I looked into this. It seems like that extra space is part of the Flutter ListTile component - there's no way for me to adjust it.

**Comment by ImranR98** [comment]
I can slightly reduce the space between the update button and version text, but it's a very tiny adjustment.

**Comment by Sami32** [comment]
And remove the unecessary used space : "Not installed" instead of "Not installed p..."

**Comment by ImranR98** [comment]
The width of the field is fixed, so removing the "pseudo version" text wouldn't give you any extra space. And it would make things less informative for larger screen users.
