### ISSUE TITLE
Fail to pick the date from Kiwi browser GitHub release

### ISSUE THREAD

**Issue by Sami32** [ImranR98/Obtainium#1684]
No change date displayed for the Kwi browser App from its GitHub release repository.
https://api.github.com/repos/kiwibrowser/src.next/releases

But the date is provided by the GitHub API.
Probably a parsing issue.

**To Reproduce**
1. Add App 'https://www.github.com/repos/kiwibrowser/src.next/releases"
2. See the 'change' text displayed under the version, instead of a date

**Screenshots and Logs**
![IMG_20240619_223307](https://github.com/ImranR98/Obtainium/assets/18471069/c2d700f6-b7ba-4a4e-8c8d-be2ba5f6cf86)

**Please complete the following information:**
 - Device: Xiaomi Redmi Note 4
 - OS: Google Android 7.0
 - Obtainium Version: 1.1.11

**Comment by ImranR98** [comment]
This was already covered in #1664. "Track-only" github apps use the tags API, which doesn't provide dates.

**Comment by ImranR98** [comment]
Actually it does use the releases API when releases are available, but falls back to the tags API otherwise. In the case of Kiwi browser, no releases are available (except pre-releases but I assume you have not included those). If you include pre-releases, you should see dates for those.

**Comment by Sami32** [comment]
OUPS...my bad, i missed the pre-releases setting 8~

Thank you +1
