### ISSUE TITLE
Option : Share with AppVerifier

### ISSUE THREAD

**Issue by Maell1** [ImranR98/Obtainium#1686]
Hello,

I don't understand the option "Share with AppVerifier".
I installed AppVerifier and when I update an app, I don't have any information about the signature...

Maybe it shows a message when the signature doesn't match?

Thanks

**Comment by ImranR98** [comment]
You only need to verify the signature when you install the app. For updates, Android makes sure the new APK's signature is identical to the existing one: https://source.android.com/docs/core/connect/wifi-tofu

When you install a new app, you'll be prompted to share it with AppVerifier first.

**Comment by sarmong** [comment]
But what exactly does 'Share with AppVerifier' does? For me it just opens the the app view in appverifier and does nothing. Internal database shows Not Found, Verification Status shows Unknown. What is it supposed to do?

**Comment by landry314** [comment]
yeah, it says "share to appverifier" but unless it is in the internal database, nothing happens. i mean, pasting from the clipboard is suppose to compare but it doesnt allow me to copy the signature into the clipboard. i am using grapheneOS.

**Comment by ImranR98** [comment]
That's not an Obtainium issue. I suggest reading up on how AppVerifier works.
