### ISSUE TITLE
Request headers ignored for direct apk link

### ISSUE THREAD

**Issue by 1RandomDev** [ImranR98/Obtainium#1688]
I'm trying to add an app from a private repository that requires HTTP basic authentication via the direct apk link option. I entered the source URL and changed the source type to direct apk link. As request header I added `Authorization: Basic <base64>`. When I now click on add, none of the specified headers are sent to the server and I get an Unauthorized error at the bottom.

I tried many things with a test server and not even the default User-Agent header is added to the request. As user agent `Dart/3.4 (dart:io)` is used all the time and all other custom headers are completely missing.

Using Obtanium version 1.1.11

**Comment by ImranR98** [comment]
It should be fixed, we can reopen the issue if there are still problems: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.12
