### ISSUE TITLE
Two or more app in single repository

### ISSUE THREAD

**Issue by code3AGL3** [ImranR98/Obtainium#1690]
I'm using Obtainium for various apps, one of them is OSS documents scanner by Akylsa https://github.com/akylas/com.akylas.documentscanner here is the link. Earlier it was doing fine but when they add another app to the same repository now Obtainium can't distinguish between both app when they release a new version of second app it shows update on my first app too. It lets me download the update which is actually the second app then it wont install further upon going toh the github i realised that they have two apps in same repository.

Please fix this issue.

**Comment by DarkCrypt** [comment]
This issue has already been discussed in 2 separate issues and 1 PR within the said repo above. They made it stupid easy to add each app right in the ReadMe.

![OSSDocumentScanner-ObtainiumButton](https://github.com/ImranR98/Obtainium/assets/121076677/66a9b393-3286-41b3-bb4c-a3d645ff0266)

Here's how:

1. Go to the above repo's readme.
2. Click the button "GET IT ON Obtainium".
3. Obtainium opens to import app with json.
4. Click continue.

**Comment by ImranR98** [comment]
Thanks @DarkCrypt

**Comment by DarkCrypt** [comment]
@ImranR98
You're welcome friend.
___
These 2 apps can also be added manually by typing the app name within the "Filter Release Titles By Regular Expression".

OSS Document Scanner: `Document Scanner`

OSS Card Wallet: `Card Wallet`

_Even though this works, the import json method in my previous comment includes a few more filters._
