### ISSUE TITLE
New source (vivo app store)

### ISSUE THREAD

**Issue by I21b** [ImranR98/Obtainium#1692]
**Describe the feature**

[App link like this](http://info.appstore.vivo.com.cn/detail/51699)

[Download link like this](http://info.appstore.vivo.com.cn/dl/TmNiK2Z2czRMNEU9)

**Comment by ImranR98** [comment]
Please read and use the issue templates. We need a way to get the APK download link from the main app page link without running any JavaScript. We also need a way to associate a version identifier with the APK link.
