### ISSUE TITLE
Don't download release asset without user confirmation

### ISSUE THREAD

**Issue by issuant** [ImranR98/Obtainium#1694]
It's not immediately apparent what 'Download release asset' means. Is it referring to docs or something else? That phrasing is ambiguous and I had to go through the issues here to figure it out.

'APK' is the more colloquial term for what it really is referring to, so the clearer options that come to mind are a) 'Download APK', b) 'Save APK', and c) 'Keep APK'. I'm biased towards (c).

Adding to the ambiguity is the fact that it currently looks like a link to a webpage instead of a button that actually does something. It should be a toggle button on the app page, and save you from having to download the APK twice, once when updating an app and again when you 'press the button'.

**Comment by ImranR98** [comment]
It's not just APKs though - you can download any asset attached to the release ("release" and "asset") are the terms used by GitHub so I don't think it's unreasonable to use them. The asset could be an APK, but it could also be other files (especially for track-only repos that people might use) and also source code archives.

**Comment by DwainZwerg** [comment]
However, it might still make sense to mark the button as a button (like the categories) and not as a link. This could eliminate ambiguities.

**Comment by ImranR98** [comment]
This feature was requested specifically for use with track-only apps and non-APK assets. I don't think it's worth splitting things up as it adds complexity, both in the UI and backend. The reason your file began downloading is because there was only one asset available so there was no need to show a selection menu. I guess we could add a confirmation prompt there.

**Comment by ImranR98** [comment]
Using the term "release asset" also allows us to re-use this feature for other sources that might also have non-APK assets in the future (like GitLab, Codeberg, etc.) - sure this is less useful for sources like F-Droid or APKMirror but the majority of apps people tend to add to Obtainium (from what I've seen are from GitHub, GitLab, and HTML).

**Comment by ImranR98** [comment]
No, this button covers your use case already, plus others.

**Comment by ImranR98** [comment]
When you tap "Update", the APK is downloaded to the cache directory, installed, and deleted. The purpose of "download release asset" is different - the file is saved to ~/Downloads and Obtainium doesn't do anything else with it.

If you want the cached APK to be left in the cache dir after installing an update, I believe there is already an issue for that (please search before creating a new issue).

**Comment by ImranR98** [comment]
Yep, that's not what it's about.

**Comment by ImranR98** [comment]
Added the confirmation prompt for single-asset releases. Also if you enable "highlight less obvious touch targets" in the settings, it will make the button look more like a button.
