### ISSUE TITLE
[UIX enhancement]: Remove unecessary data in the App version field

### ISSUE THREAD

**Issue by Sami32** [ImranR98/Obtainium#1695]
**Describe the feature**
Remove the unecessary data before the App version (parsed by default or as an option).
Example: "android.", "release_”, " hin2n_”

**Additional context**
![IMG_20240627_110232](https://github.com/ImranR98/Obtainium/assets/18471069/d7d0f14f-4534-4e6b-b89b-0937e2026628)
![IMG_20240627_110210](https://github.com/ImranR98/Obtainium/assets/18471069/ef8073ae-e720-4ecb-8f7d-0ea0f9701423)
![IMG_20240627_110152](https://github.com/ImranR98/Obtainium/assets/18471069/6c23627d-d064-458e-b9e3-152744e1d6b1)

**Comment by ImranR98** [comment]
This is not feasible - the app version string provided by a source can be anything at all - there's no way for Obtainium to know what part of the string is important and what isn't (except in the case of "standard" version formats which does not apply here).

You can use the "version extraction" setting to specify your own string trimming for each app.

**Comment by Sami32** [comment]
I tried your suggestion but didn't got the expected result, removing the text before the version display:
![Screenshot_2024-06-29-22-23-55-062_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/18471069/9dbefa7a-7114-4059-9c24-6bcb4c7f90e7)

What i missed?

**Comment by ImranR98** [comment]
Please search for issues involving regex or loop up the wiki and documentation. You'll need to use a regex along with match groups.

**Comment by Sami32** [comment]
It would be great if your wiki was more informative about how your App handle Regex IMHO...

I'll try to find out in issues.

**Comment by ImranR98** [comment]
For example, try `release_(.+)` with a match group of `1`.

**Comment by Sami32** [comment]
I'm not sure that we are talking the same thing.
The versions displayed don't change.

But the version picking does because it show the download checkmark.

So it just doesn't seem possible to modify how the applications version are displayed in your App?

**Comment by ImranR98** [comment]
Yeah I'm not sure I understand what you're asking. Maybe send a screenshot?

**Comment by Sami32** [comment]
I just want hide the part in orange square:
![IMG_20240629_232928](https://github.com/ImranR98/Obtainium/assets/18471069/3f4b42cb-0e89-4b99-bb0b-23a4420a7853)

**Comment by ImranR98** [comment]
Yes, that's exactly what you can do with "version extraction" + "match group" - I just tried it myself with `hin2n_` and `1`. You'll need to tap the checkmark ("mark as updated") because Obtainium doesn't know that the version string change is exclusively due to your changes and not an actual update.

**Comment by Sami32** [comment]
Aaahhh...i didn't knew that and didn't found anything in your wiki.
Thank you very much for your help +1
