### ISSUE TITLE
"Bad state: No element"

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#1697]
I've had a profile for addy.io working for some time, but it's now reporting an error on attempted update: "Some Errors Occurred.  Bad state: No element [addy.io]"

Pixel 7, GrapheneOS
Obtainium: 1.1.12

https://gitlab.com/Stjin/anonaddy-android

The proper release is available:
https://gitlab.com/Stjin/anonaddy-android/-/raw/0b17fb06a059b67ec7e7e45aa2c5db77770ad5e0/app/gplayless/release/app-gplayless-release.apk

Fallback to older releases - on
Filter APKs by Regular Expression - gplayless
Attempt to filter APKs by CPU architecture if possible - on
Everything else is off.

Right now, 5.2.3 is installed, and 5.2.6 is the latest.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.13
