### ISSUE TITLE
The translation of URL (which is probably URL in every language) in the F-Droid third party repo in the "Add app" tab is missing

### ISSUE THREAD

**Issue by DwainZwerg** [ImranR98/Obtainium#1699]
Unlike the English language, the German language displays "l.other *" instead of "URL". I guess that the translations into the individual languages are still missing (although they are quite unnecessary in this case). See the screenshot:
![signal-2024-06-29-092602](https://github.com/ImranR98/Obtainium/assets/97027379/a8395e69-a41d-4271-b679-ef11d3fd0b13)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.14
