### ISSUE TITLE
RU translation error 

### ISSUE THREAD

**Issue by eXense-auth** [ImranR98/Obtainium#1703]
**Prerequisites**

**Describe the bug**
here the text "source" is translated as "Исходный код", which in Russian means "source code", but it should be written "Источник" or "Ресурс"

**To Reproduce**

**Screenshots and Logs**
![Screenshot_20240702-143252_Obtainium_1](https://github.com/ImranR98/Obtainium/assets/53921092/de4934aa-b186-4c68-96d0-846960978f69)

**Please complete the following information:**
 - Device: 
 - OS: 
 - Obtainium Version: 

**Additional context**

**Comment by DwainZwerg** [comment]
I have created a PR: https://github.com/ImranR98/Obtainium/pull/1710
