### ISSUE TITLE
Swipe Typing Not Working In Reddit Search

### ISSUE THREAD

**Issue by iSuckAtCoding8** [ImranR98/Obtainium#1704]
- Device: ZTE Axon 10 Pro
 - OS: Android 10
 - Obtainium Version: 1.1.13

**Comment by DwainZwerg** [comment]
What does Obtainium have to do with Reddit search?

**Comment by iSuckAtCoding8** [comment]
> What does Obtainium have to do with Reddit search?

Oops, I thought I was posting on Futo Keyboard. I'll try to delete this.

**Comment by iSuckAtCoding8** [comment]
Please delete

**Comment by DwainZwerg** [comment]
Please close it as resolved.
