### ISSUE TITLE
Error: Unauthorized

### ISSUE THREAD

**Issue by Chump2074** [ImranR98/Obtainium#1705]
**Describe the bug**
I can't add any apps from GitHub since I get the error "Unauthorized"

**To Reproduce**
1. Click in "Add app"
2. Search for the app on Github or add an Github URL
3. Try to add it

**Screenshots and Logs**
![Screenshot_20240703-151420](https://github.com/ImranR98/Obtainium/assets/155765374/a5d37330-0a38-4259-8439-680edbfa0d63)

**Please complete the following information:**
 - Device: Pixel 7a
 - OS: GrapheneOS
 - Obtainium Version: 1.1.13

**Additional context**
I've already tried adding a Personal Access Key (but I don't know if I applied the correct permissions that are needed) and reinstalling the app, but that didn't help.

**Comment by DwainZwerg** [comment]
Did you enter the URL directly or did you use the GitHub search? If I use GitHub search (which I don't normally do), I can reproduce this on my phone (Samsung Galaxy A3 (2017-FL); Android 8.0.0; StockRom (One UI)), but not on my Windows subsystem for Android (Windows 11 Pro (10.0.22631 build 22631); subsystem version 2311.400000.5.0; Android 13).

**Comment by DarkCrypt** [comment]
Using the GitHub search, issue is reproducible only if user includes additional filters. I was able to add app with default filters. Adding additional filters after the app was added seemed to work properly.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.14

**Comment by nalladev** [comment]
This error was shown when my github token expired. But I could not find the reason of the error for sometime. A better error msg that suggests to check if the github token is expired would be nice 

![Image](https://github.com/user-attachments/assets/1f1ab05c-5e16-4750-a540-d7389495a57a)
