### ISSUE TITLE
could not find find suiteable releases (GOS)

### ISSUE THREAD

**Issue by sudo-joe** [ImranR98/Obtainium#1707]
Obtainuim [v1.1.13](https://github.com/ImranR98/Obtainium/releases/tag/v1.1.13)
GrapheneOS 20240624 / Android 14

I am trying to install the following app with Obtainium via -> Add App -> Search
When the app is found/listed in Obtainium, the following "URL" is inserted into the upper field of Obtainium
 
- https://github.com/Divested-Mobile/Mull-Fenix
- https://github.com/mvglasow/satstat

But after pressing "Add" the follwoing message is shown:

"could not find find suiteable releases" 

The same with both apps :)

Thank's in advance for any help!

PS
When those two apps are downloader from F-Droid, they can be insalled without any issues.

**Comment by DwainZwerg** [comment]
[Mull Fenix](https://github.com/Divested-Mobile/Mull-Fenix/releases) hasn't any releases. You could add Mull Fenix as track only source for the tags (https://github.com/Divested-Mobile/Mull-Fenix/tags). satstat has moved to gitlab: https://gitlab.com/mvglasow/satstat

**Comment by DarkCrypt** [comment]
No releases in both repos. You'll have to get updates from F-Droid or set as track-only.

**Comment by sudo-joe** [comment]
Thank's a lot for your help/feedback. I am not even sure what releaes are.. :(

Do I need Obtainium to check if there are releases or is the lack of releases already obvious to see/identify on the page of the app developer ( https://github.com/Divested-Mobile/Mull-Fenix ) ? How?

Thank you!

**Comment by DwainZwerg** [comment]
Obvious (do you've had read the wiki in which explained how Obtainium works?):
- [Releases](https://github.com/Divested-Mobile/Mull-Fenix/releases)
- [Tags](https://github.com/Divested-Mobile/Mull-Fenix/tags)

**Comment by DwainZwerg** [comment]
@sudo-joe Please close this issue as resolved.
