### ISSUE TITLE
"FormatException: invalid port" for HTML source

### ISSUE THREAD

**Issue by 946923759** [ImranR98/Obtainium#1715]
**Describe the bug**
I want to add an HTML source from a non default port, but it says this when trying to add it.

**To Reproduce**
1. On a computer, do `python3 -m http.server` or some equivalent that runs a HTTP server on a port other than 80 or 443. And have some valid files in the folder, of course.
2. Try adding it in Obtainium, in this case it was `http://192.168.12.242:8000`
3. Despite the HTTP server showing it was accessed, the source cannot be added

**Screenshots and Logs**
Oddly, the `/` is also missing. Changing the source to `http://192.168.12.242:8000/` does not fix it.
```
FormatException: Invalid port (at character 23)
http://192.168.12.242:8000testApp_v10.7.52.arm64.apk
                      ^
```

**Please complete the following information:**
 - Device: Surface Duo
 - OS: Android 12
 - Obtainium Version: 1.1.13

**Comment by 946923759** [comment]
After switching to a default port, the missing / seems to be causing issues with adding the source. The HTML looks like `<a href="testApp_v10.7.52.eng-arm64.apk">testApp_v10.7.52.arm64.apk</a>` (no / at the beginning)

It can be solved by writing a custom index.html, at least.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.14
