### ISSUE TITLE
[Request] Backup To Google Account

### ISSUE THREAD

**Issue by zero77** [ImranR98/Obtainium#1719]
**Prerequisites**

**Describe the feature**

Unless you remember to make regular backups, after a format or if you get a new phone, you will lose all settings and filters and have to manually add them.

It would be ideal if Obtainium could back up to your google account. 
As an alternative regular automatic backups that are saved to the phone would also help.

https://developer.android.com/guide/topics/data/autobackup

**Describe alternatives you've considered (if applicable)**

**Additional context**

**Comment by ImranR98** [comment]
Google Drive integration is out of scope (unless someone has a decent PR). You can already do an auto-export to a specified local directory whenever there is a change to any app config (not exactly a backup, but you can use something like Syncthing to go from there).
