### ISSUE TITLE
"Codeberg" source should really be called "Gitea/Forgejo"

### ISSUE THREAD

**Issue by ThatOneCalculator** [ImranR98/Obtainium#1722]
Codeberg runs on the open source Forgejo software (which is a fork of Gitea) that many self hosted git servers run. Changing the name should make it clearer when downloading from Gitea/Forgejo forged that aren't codeberg.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.14

**Comment by beedell-roke** [comment]
> [The] "Codeberg" source should really be called "Gitea/Forgejo"

@ThatOneCalculator, Forgejo is a *hard* fork of Gitea, so they're not equivalent.

**Comment by ThatOneCalculator** [comment]
1) This was closed/added literally a year ago, why are you commenting here
2) Being a hard fork doesn't mean they don't share API routes/design

**Comment by arichiardi** [comment]
Thank you!

Was trying to fetch this [app](https://gitea.angry.im/PeterCxy/OpenEUICC) and after an hour of trying to get the HTML regexes right I just stumbled into this issue.
I then used the search button against forgejo, changed the host to `gitea.angry.im` and it worked right away!
