### ISSUE TITLE
Unable to update to Alpha 

### ISSUE THREAD

**Issue by expatri0tic** [ImranR98/Obtainium#1724]
**Describe the bug**
Obtainium notes that there is a new install available. But refuses to download it saying it's unable to download an older version. I'm attempting to go from the 0.8.4 Beta to 0.9 alpha...

**To Reproduce**
Download Beta of Zeus LN app from their GitHub.
Then try to update to closed Alpha (need to contribute to their project to get URL as it's not indexed to the site)

**Screenshots and Logs**
![camphoto_684387517](https://github.com/user-attachments/assets/36df5928-1653-4825-b64e-5b6e62ce0bf7)

https://github.com/user-attachments/assets/6698c007-000e-4cee-9cfb-613b0a4a258d

https://github.com/user-attachments/assets/0cd72ff8-804e-4fce-83cb-bb2345b89bd8

![IMG_1236](https://github.com/user-attachments/assets/e9705055-4310-4c5f-8a09-23e8cabaa731)
![IMG_1237](https://github.com/user-attachments/assets/f20bebd5-8dde-4801-b8dc-9548274a060f)

**Please complete the following information:**
 - Device: Pixel 8a
 - OS: GrapheneOS
 - Obtainium Version: version 1.1.13 code 22703

**Comment by DwainZwerg** [comment]
For further bug reports (also in other projects): In the future, could you please take screenshots instead of photos of the dialogs on your respective device? That makes life a lot easier for others.

**Comment by expatri0tic** [comment]
> For further bug reports (also in other projects): In the future, could you please take screenshots instead of photos of the dialogs on your respective device? That makes life a lot easier for others.

Absolutely. My apologies. Was sending it as I had it to give. Didn't originally know I'd be including them in a report.

**Comment by ImranR98** [comment]
Android doesn't actually look at the version string, it looks at the `versionCode` (like 86003) and won't allow you to install an update with a lower `versionCode` (it's an Android restriction, not Obtainium, which is why it failed to install even from the file manager). You'll need to uninstall the current version then install the new one.
