### ISSUE TITLE
F-Droid Alpha not detected

### ISSUE THREAD

**Issue by DatHypnoboi** [ImranR98/Obtainium#1726]
**Prerequisites**

**Describe the bug**
F-Droid will commonly release alpha versions of their client before the full release, but Obtainium doesn't seem to recognize them. The latest version is currently 1.21.0-ALPHA0, but Obtainium only detects 1.20.0 as the latest release

**To Reproduce**

1. Add F-Droid to Obtainium: https://f-droid.org/packages/org.fdroid.fdroid/
2. Check latest version

**Screenshots and Logs**

![Screenshot_20240715-045301](https://github.com/user-attachments/assets/22de5cf6-7083-47d5-afd7-f7a37317490d)
![Screenshot_20240715-045324](https://github.com/user-attachments/assets/2f771063-6ee0-4794-acb5-96e8beb8a8c4)

**Please complete the following information:**
 - Device:  Pixel 6a
 - OS:  Android 14
 - Obtainium Version: 1.1.14

**Additional context**

Unsure if this is intentional or not, but if it is intended, there should probably be an option to include prereleases for F-Droid like there is for GitHub

**Comment by ImranR98** [comment]
This is the info provided by the F-Droid API: https://f-droid.org/api/v1/packages/org.fdroid.fdroid

Obtainium can only use the info provided above. You could enable the "select suggested versioncode" option which looks like it would help here.
