### ISSUE TITLE
Move Obtainium Apps to Add App Screen

### ISSUE THREAD

**Issue by Coehill** [ImranR98/Obtainium#1727]
**Describe the feature**
I did not know that the [obtainiun suggested apps](https://github.com/ImranR98/apps.obtainium.imranr.dev?tab=readme-ov-file) screen even existed until after months of using obtainium. It is hidden away at the bottom of the setting screen after tapping the 4 squares icon.
![Screenshot_1](https://github.com/user-attachments/assets/091ad2c4-ee48-47ea-9c24-ab71070e0e64)

I propose that this screen be moved to the top of the "Add App" section under a "Community App Sources" button. This will make this feature known and not hidden away in settings. It will also make Obtainiun more user friendly so people can install apps from source without needing to understand how GitHub releases work.
![screenshot_2](https://github.com/user-attachments/assets/cb786472-f741-431b-9ff6-31b9acdc912b)

**Comment by DJCrashdummy** [comment]
\*lol\* i use Obtainium since pre 1.0 versions and know of https://apps.obtainium.imranr.dev/ but i never noticed/tried this button in the settings. :facepalm:

**Comment by DwainZwerg** [comment]
> but i never noticed/tried this button in the settings.

The button has only existed since the sixth of May and was created by me (https://github.com/ImranR98/Obtainium/issues/1554). By the way, I've also been an Obtainium user from the very beginning.

**Comment by segln** [comment]
Wouldn't adding that repository to the supported sources solve the issue without needing to add a button?
