### ISSUE TITLE
Add the info when there is a new update on some app

### ISSUE THREAD

**Issue by weiliang011** [ImranR98/Obtainium#1728]
**Describe the feature**
I want that when I need to update the app, the info shows when I click on the app, likely the info is the changelog, but pls add the info

**Comment by DwainZwerg** [comment]
I don't understand: There is both the change log and the install/update button in the general overview as well as in the app detail view. What exactly do you want?

**Comment by weiliang011** [comment]
![Screenshot_20240716-205244](https://github.com/user-attachments/assets/3d385f55-9d85-4a9f-964a-56a7db6d226e)
This info: What's Changed

**Comment by DwainZwerg** [comment]
As I said, you can already display the release notes (=change log) both in the app overview and in the app detail view: [Video](https://www.dropbox.com/scl/fi/zqtuqqm86q0mbq9szlpnp/Aufzeichnung-2024-07-17-100912.mp4?rlkey=fa3omc6io683upotqt9chuhg3&st=6pzsl8ya&dl=0)

**Comment by weiliang011** [comment]
> As I said, you can already display the release notes (=change log) both in the app overview and in the app detail view: [Video](https://www.dropbox.com/scl/fi/zqtuqqm86q0mbq9szlpnp/Aufzeichnung-2024-07-17-100912.mp4?rlkey=fa3omc6io683upotqt9chuhg3&st=6pzsl8ya&dl=
i can't Watch the video but i already found an option to overview the page ,so thanks
