### ISSUE TITLE
Bitwarden download wrong version that is not existing

### ISSUE THREAD

**Issue by Grkrz** [ImranR98/Obtainium#1732]
Hi 
I have a question.
I using obtanium to get the bitwarden apk but today something  strange happened.
Obtanium asked my to download the new version 2024.7.0 version 11080 and now it asks me again to download but it is referring to version 2024.6 ...
The version 11080 does not even exist on github. 

The thing is I did not wanted to download pre releases.

**Comment by ImranR98** [comment]
Same thing happened to me. The only explanation is that they released 2024.7.0 as a non-prerelease then deleted it later. The solution is to uninstall and reinstall 2024.6 or just keep it installed and wait for a newer version to come out. Hopefully they don't do it again.

**Comment by Grkrz** [comment]
Could be a thing that some hacker has injected there own version that we downloaded?
I have noticed yestarday when I left my session opened for a long time it was still active. After few hours, that has never happened before.

**Comment by Grkrz** [comment]
The new beta looks newer then the previous version is it was not the beta one. 
Beta has different number then this was included in the app.

**Comment by DwainZwerg** [comment]
See also https://github.com/ImranR98/apps.obtainium.imranr.dev/pull/151 & https://github.com/ImranR98/apps.obtainium.imranr.dev/pull/109

**Comment by sokai** [comment]
FYI: https://github.com/bitwarden/mobile/issues/3358#issuecomment-2236122723
> A [mobile](https://github.com/bitwarden/mobile) repository GitHub Release was created too soon and was removed. It's going through a testing phase now and should be released next week.
