### ISSUE TITLE
Support cross-line matching in HTML source mode

### ISSUE THREAD

**Issue by jbwfu** [ImranR98/Obtainium#1735]
When matching [qianjiapp.com](https://docs.qianjiapp.com/change-log/change_log_android.html), the latest version number cannot be obtained.

The regular expression I used is `.*Version ([0-9.]*).*`, and the version I want to obtain is `4.0.8` (the first match of the regular expression in HTML), but the actual version obtained is `1.0` (the last match of the regular expression in HTML).

Using cross-line matching can theoretically obtain the latest version number (4.0.8), but it seems that it is not supported at present?

The configuration I use is [Obtainium qianjiapp config, click to import](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.mutangtech.qianji%22%2C%22url%22%3A%22https%3A%2F%2Fdocs.qianjiapp.com%2Fchange-log%2Fchange_log_android.html%22%2C%22author%22%3A%22docs.qianjiapp.com%22%2C%22name%22%3A%22%E9%92%B1%E8%BF%B9%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22gw%5C%5C%5C%5C.apk%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Atrue%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Atrue%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Atrue%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22.*Version%20(%5B0-9.%5D*).*%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%241%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3Anull%7D)

**Comment by ImranR98** [comment]
Not sure what you mean by "cross line matching". The RegEx is applied to the whole page (if you enable that option) but the last item is picked. We could add a "pick first match" toggle - sounds like that would work.

**Comment by jbwfu** [comment]
``html
`<p><a href="https://app.qianjiapp.com/qianji_408_932_gw.apk" target="_blank">https://app.qianjiapp.com/qianji_408_932_gw.apk</a></p>
<h3 id="version-408">Version 4.0.8</h3>
<p>2024-07-13</p>
<ul>
```

The HTML to be matched is the above part. "pick first match" can indeed make it work for this app, but a more general way is to support cross-line matching (i.e. regex matching in multiple lines). In the above HTML, the Regex `/p>\n<h3 id="version-[0-9]*">Version ([0-9.]*)` can be used to match the required version number. (I have turned on "Apply version string extraction Regex to entire page", but it seems that nothing can be matched? Maybe my regex is wrong?) If this kind of matching can be supported, it may be more suitable than "pick first match".

**Comment by ImranR98** [comment]
[This config should work](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.mutangtech.qianji%22%2C%22url%22%3A%22https%3A%2F%2Fdocs.qianjiapp.com%2Fchange-log%2Fchange_log_android.html%22%2C%22author%22%3A%22docs.qianjiapp.com%22%2C%22name%22%3A%22App%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22gw%5C%5C%5C%5C.apk%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Atrue%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22partialAPKHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22.apk%3C%2Fa%3E%3C%2Fp%3E%5C%5C%5C%5C%5C%5C%5C%5Cn%3Ch3%20id%3D%5C%5C%5C%22version-%5B0-9%5D*%5C%5C%5C%22%3EVersion%20(%5B0-9.%5D*)%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%221%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%2C%22overrideSource%22%3Anull%7D). You needed to escape the `\n` and add `.apk</a>` at the start to avoid older releases.
