### ISSUE TITLE
Weird text wrapping in the tabbar

### ISSUE THREAD

**Issue by kjurel** [ImranR98/Obtainium#1741]
**Describe the bug**
The bottom tabbar specifically the "Import/Export" tab text wraps and is left aligned. Im not sure if there is a better way to describe it, but it does not look like the intended behavior.

**Screenshots and Logs**
![Screenshot_20240721_205052.jpg](https://github.com/user-attachments/assets/2fe1bdb1-c028-49e5-8864-5e4263dcdf9b)

 - Device : Samsung 
 - OS: Android 14 (OneUI 6.1)
 - Obtainium Version: v1.1.14

**Comment by ImranR98** [comment]
Duplicate of #1054
