### ISSUE TITLE
Can't update auto-auto-rotate

### ISSUE THREAD

**Issue by dik23** [ImranR98/Obtainium#1742]
**Describe the bug**
Can't update auto-auto-rotate although I used Obtainium to install it and I can download the apk from the gitlab page

**To Reproduce**
1. Install auto-auto-rotate on 26 Jun 24 using Obtainium from [https://gitlab.com/juanitobananas/auto-auto-rotate](https://gitlab.com/juanitobananas/auto-auto-rotate)
2. auto-auto-rotate releases update which Obtainium notifies me about
3. Open Obtainium, open auto-auto-rotate in Obtainium, choose Update
4. Error message appears (see screenshots)
5. "Download release asset" gives same error

![installed](https://github.com/user-attachments/assets/afe5e33f-a3bf-406c-9c43-ff7847785dfc)

![error](https://github.com/user-attachments/assets/b2c10f6e-b8ab-4815-878e-8067b37e6a50)

**Please complete the following information:**
 - Device: Pixel 8
 - OS:  GrapheneOS
 - Obtainium Version: 1.1.14

**Comment by LightWayUp** [comment]
Gitlab recently changed their URL format for file attachments. On Gitlab, files can be attached to issues, merge requests, release descriptions, and more.  
Previously, file attachment URLs have the format:
```
https://gitlab.com/<username>/<project name>/uploads/<32-character ID>/<filename>
```
In this case, `<username>/<project name>` is `juanitobananas/auto-auto-rotate`.  
Now, the format has changed to:
```
https://gitlab.com/-/project/<project ID>/uploads/<32-character ID>/<filename>
```
Where `<project ID>` is a numerical ID of the project. URL-encoded path of the project (like `juanitobananas%2Fauto-auto-rotate`) doesn't work here.

Obtainium tries to construct the download URL using the old format which leads to `404` (Not Found) response status.

---

Obtainium will need to change to use the new format to fix this issue. A note is that Gitlab instances can be self-hosted, and the instances may be of older versions, so in case following the new-format download URL returns `404` status, Obtainium should fall back to the old format and try again before showing errors.

**Comment by Felitendo** [comment]
> Gitlab recently changed their URL format for file attachments. On Gitlab, files can be attached to issues, merge requests, release descriptions, and more. Previously, file attachment URLs have the format:
> 
> ```
> https://gitlab.com/<username>/<project name>/uploads/<32-character ID>/<filename>
> ```
> 
> In this case, `<username>/<project name>` is `juanitobananas/auto-auto-rotate`. Now, the format has changed to:
> 
> ```
> https://gitlab.com/-/project/<project ID>/uploads/<32-character ID>/<filename>
> ```
> 
> Where `<project ID>` is a numerical ID of the project. URL-encoded path of the project (like `juanitobananas%2Fauto-auto-rotate`) doesn't work here.
> 
> Obtainium tries to construct the download URL using the old format which leads to `404` (Not Found) response status.
> 
> Obtainium will need to change to use the new format to fix this issue. A note is that Gitlab instances can be self-hosted, and the instances may be of older versions, so in case following the new-format download URL returns `404` status, Obtainium should fall back to the old format and try again before showing errors.

Could you fork Obtanium and fix this issue. That would be really great :)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.15

**Comment by Aadam-Marshall** [comment]
@ImranR98, hi, I have the same issue with

https://gitlab.com/juanitobananas/scrambled-exif/

Before the latest update, the error was "Not found", now it's "App already added", but the app isn't actually added. Tell me if I should open a separate issue.

**Comment by ImranR98** [comment]
Huh, I'm able to add it fine. Could you check if this file exists (and if so delete it): `/Android/data/dev.imranr.obtainium/files/app_data/com.jarsilio.android.scrembledeggsif.json`

**Comment by Aadam-Marshall** [comment]
The file did exist, I deleted it and that solved it, thank you.
