### ISSUE TITLE
Extract the version number from GitHub's apk name 

### ISSUE THREAD

**Issue by jbwfu** [ImranR98/Obtainium#1743]
>Why can't it extract version from the apk name?
>It seems pretty easy to do?
>
>(Or extract version from release notes or release name?)

_Originally posted by @Araxeus in https://github.com/ImranR98/Obtainium/issues/1640#issuecomment-2126235124_

Some software releases tags only contain part of the version number used in the app. For example, the latest tag of [QAuxiliary](https://github.com/cinit/QAuxiliary) is 'v1.5.2', but the actual version used in the app is the more detailed '1.5.2.r2263.c3d9cc2'. This version number can be extracted from the apk name, but at present, Obtainium does not seem to support extracting the version number from the apk name.

**Comment by ImranR98** [comment]
This would not work for releases with multiple APKs where the user hasn't set any filters to narrow them down to 1. And even when the user sets a filter, we can't guarantee that future releases won't break it and cause errors.
