### ISSUE TITLE
Unable to add Whatsapp

### ISSUE THREAD

**Issue by tzMpDDYL** [ImranR98/Obtainium#1747]
I am unable to add Whatsapp using the download link from the website.

- Visit https://www.whatsapp.com/android.
- Copy the link that says Download Whatsapp directly.
- Go to Obtainium app and paste link in App Source URL
- Select Whatsapp from Override Source menu
- Click Add button

Result: "Forbidden" error message.

Same thing happens if I use the actual website url as App Source URL (https://www.whatsapp.com/android).

Just in case, the direct download link is: https://scontent.whatsapp.net/v/t61.25591-34/10000000_1861761754338549_778185249926849873_n.apk/WhatsApp.apk?ccb=1-7&_nc_sid=c49adc&_nc_ohc=P_nWDuAH0PQQ7kNvgFDfElx&_nc_ht=scontent.whatsapp.net&oh=01_Q5AaIGiztEtHDcBqRfLoC1pLexJy7H9ZYdD3V1kjFoURwaP7&oe=66C858C3

Is it something I am doing wrong or is it just not working? 

Obtainium app version 1.1.14
Android OS: GrapheneOS
Google Pixel 6a

**Comment by DarkCrypt** [comment]
Duplicate of #357.

You can add this app in multiple ways...
1. Same URL as above: `https://www.whatsapp.com/android`
Override Source: `None`
2. Main URL: `https://www.whatsapp.com`
Override Source: `WhatsApp`
3. Obtainium's crowd source app configurations: [apps.obtainium.imranr.dev](https://apps.obtainium.imranr.dev/)

**Comment by ImranR98** [comment]
The Whatsapp source works fine. I'd guess your Forbidden error is some network based blocking. Try again from a different network.

**Comment by prasetyodedy** [comment]
@DarkCrypt can you help share your whatsapp config?
thank you, i cant add manually error 400

**Comment by DarkCrypt** [comment]
@prasetyodedy 
Delete the request header when adding the app.

Version extraction is possible but pointless, the posted version on the website never matches the downloaded version.

_Edit:_
Import App -> [WhatsApp](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.whatsapp%22%2C%22url%22%3A%22https%3A%2F%2Fwww.whatsapp.com%2Fandroid%22%2C%22author%22%3A%22www.whatsapp.com%22%2C%22name%22%3A%22WhatsApp%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22matchLinksOutsideATags%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22partialAPKHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22WhatsApp%5C%22%2C%5C%22appAuthor%5C%22%3A%5C%22WhatsApp%20LLC%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22Secure%2C%20free%20messaging%20and%20calling%20app%20developed%20by%20Meta%20that%20allows%20users%20to%20send%20text%20messages%2C%20make%20voice%20and%20video%20calls%2C%20and%20share%20media%20across%20devices.%5C%22%2C%5C%22refreshBeforeDownload%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3A%22HTML%22%7D
)
