### ISSUE TITLE
PathAccessException #2 (on secondary user profiles)

### ISSUE THREAD

**Issue by genericusername87** [ImranR98/Obtainium#1754]
**Prerequisites**

Possibly related to #1668, but issue is already closed.

**Describe the bug**

When using the "Download release asset" function in a secondary or work Android profile,
Obtainium tries to download the file into "/storage/emulated/**0**/Download/" (which is the path of the 'Owner' profile) instead of the Download folder of the profile where Obtainium is running (which would be "/storage/emulated/10/Download"). This results in a 'Permission denied' error with an PathAccessException.

Furthermore, after picking an export directory for settings backup, "Download release asset" tries to save the files into the specified export directory instead of the Download folder. But this results in a PathNotFoundException.

Regarding the storage access permission discussed in #1668: Obtainium doesn't ask for selecting a Download directory or storage access (except for picking the export directory) nor can I grant it equivalent permissions in the Android Settings -> Apps -> Obtainium page.

**To Reproduce**

1. Create a secondary user profile
2. Install Obtainium 
3. Inside Obtainium go to app detail page
4. Tap on "Download release asset"
5. Select release asset and tap continue 
6. See PathAccessException error

7. Go to Import/Export
8. Tap on "Pick export directory"
9. Select folder via Files app
10. Go back to Apps screen
11. Tap on app on go to app detail page
12. Tap on "Download release asset"
13. Select release asset and tap continue
14. See PathNotFoundException 

**Screenshots and Logs**

PathAccessException:

![ResizedImage_2024-07-28_19-43-55_3573.png](https://github.com/user-attachments/assets/5ad2e3a8-da2d-42b4-bda0-d70de989edf5)

PathNotFoundException after picking export directory:

![ResizedImage_2024-07-28_19-41-48_1511.png](https://github.com/user-attachments/assets/e7361130-385d-4847-952b-a121dfccf0e3)

In-app logs don't provide more information than the screenshots, but for copy-paste ability:

```
2024-07-28 18:13:22.434: info: Cleared 1 log (before = 2024-07-21 18:13:22.421646, after = null)

2024-07-28 18:20:27.316: error: PathAccessException: Cannot open file, path = '/storage/emulated/0/Download/app-arm64-v8a-release.apk.part' (OS Error: Permission denied, errno = 13) [app-arm64-v8a-release.apk]

2024-07-28 18:21:20.241: error: PathNotFoundException: Cannot open file, path = '/tree/primary%3ADocuments%2FBackup%2FObtainium/app-arm64-v8a-release.apk.part' (OS Error: No such file or directory, errno = 2) [app-arm64-v8a-release.apk]


2024-07-28 18:55:31.715: info: BG update task: Started (51).
```
I can't detect anything useful in the logcat output either, but I can provide them if you wish.

**Please complete the following information:**
 - Device:  Pixel 8
 - OS:  GrapheneOS 2024071600
 - Obtainium Version:  v1.1.14

**Additional context**

If relevant, Obtainium is installed in the owner profile, too. Unfortunately I can't remember whether I installed Obtainium in the secondary profile via direct APK download or via GrapheneOS's 'install apps from owner to other profile'-functionality.

**Comment by ImranR98** [comment]
This should now be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.29
