### ISSUE TITLE
AIMP

### ISSUE THREAD

**Issue by Aadam-Marshall** [ImranR98/Obtainium#1756]
Creating this to help future users who are going to look for a way to download AIMP from the official website. I searched issues and there's nothing about AIMP, so I figured it out myself, and I write this to save others' time from figuring it out themselves.

Paste this link into Obtainium: https://www.aimp.ru/?do=download.file&id=13

In `Override Source`, choose `Direct APK Link`

Done. It's easy, but it's faster to search for GitHub issues than to figure it out by yourself.

**Comment by Flashwalker** [comment]
Here is the json import file with the variant with the version number: 

[obtainium-export-AIMP_html_page-2026-07-22T09-16-31.042669-count-1.json.txt](https://github.com/user-attachments/files/30249874/obtainium-export-AIMP_html_page-2026-07-22T09-16-31.042669-count-1.json.txt)

<details><summary>Screenshot</summary>

<img width="1440" height="3168" alt="Image" src="https://github.com/user-attachments/assets/4f3f90da-61f6-407b-9926-f06b1cd7f5c8" />

</details>
