### ISSUE TITLE
Test version as a update

### ISSUE THREAD

**Issue by hrshtein** [ImranR98/Obtainium#1757]
**Description of the bug**
Obtainium is showing test version as a update. The app here is cromite, Cromite developer has published test apk in github, even though github is showing previous normal build as latest but obtainium is showing the test version as update.

**To Reproduce**
1. Add repo https://github.com/uazo/cromite
2. Check the latest update version
3. Go to github and check the recommended version

**Screenshots and Logs**
![Screenshot_2024-07-30-23-00-39-97_918ba2602cfd2790bdafeb7f907490a7](https://github.com/user-attachments/assets/9f41b4bc-8363-4c09-9fcb-c0ccbf7ea5cf)
![Screenshot_2024-07-30-23-01-04-48_50ecd26a21c2c56ce608de5e94733463](https://github.com/user-attachments/assets/3d927d12-896d-4719-b5bd-f8c6e43f04fd)

**Device Info**
 - Device: Realme 9pro 5g
 - OS: Android 14
 - Obtainium Version: 1.1.15

**Comment by akramer-zibra** [comment]
@hrshtein you can simply fix this with a regexp to filter for releases with a version title. I use the following regexp for this: `v[.0-9a-zA-Z-]*`

![Cromite-regexp](https://github.com/user-attachments/assets/d505cbe3-634a-4147-ab58-28e0df82a503)

**Comment by ImranR98** [comment]
Yes - you should be able to use the additional options/filters to deal with this repo.
