### ISSUE TITLE
Add Search Button

### ISSUE THREAD

**Issue by Felitendo** [ImranR98/Obtainium#1762]
Could you please add a Search Button, where we can search for installed/added Apps. Especially for me who has 50+ Apps added into Obtainium, it's hard to find specific ones you want to edit.

**Comment by Felitendo** [comment]
That's good, but it's not really the same as a search button. It's also hard to find for new users...

**Comment by ImranR98** [comment]
> it's not really the same as a search button.

I don't see how it's different.

> It's also hard to find for new users...

Yeah, might be a good idea to use a search icon instead

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.16
