### ISSUE TITLE
French translation completely revised

### ISSUE THREAD

**Issue by Kevinr99089** [ImranR98/Obtainium#1769]
I've reworked the entire french file using the English version of the file.
My motivation was that some words were not centred in French (like "Ajouter une Application"), and some words were not correctly translated, which made it difficult to understand certain phrases.
However, I kept some phrases that I thought were correct.
[fr.json](https://github.com/user-attachments/files/16500130/fr.json)

Apart from that, this application is really useful and saves time, congratulations on your work.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.16
