### ISSUE TITLE
Duplicate "Background Update Checking Interval" setting

### ISSUE THREAD

**Issue by bluefly000** [ImranR98/Obtainium#178]
device: pixel 6a runnning GrapheneOS
app ver: 0.9.0

"Backgroud Update Cheking Interval" setting exists in two locations.

![Screenshot_20221221-210854](https://user-images.githubusercontent.com/101441707/208904608-4faa6325-80ed-4030-90af-05dc869bfa71.png)

**Comment by eloffmarijan** [comment]
Same here.

**Comment by ImranR98** [comment]
Accidentally copy/pasted something. Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.1-beta
