### ISSUE TITLE
can't install StandardNotes

### ISSUE THREAD

**Issue by Yolakalemowa** [ImranR98/Obtainium#1780]
**Describe the bug**
I receive an error message that just says (invalid) when attempting to install standardnotes.

The thing is, I've already done this before and had no issues. But I had to uninstall SN for some reason and now want to reinstall it.

**To Reproduce**

1. Go to 'Add App'
2. Type Standardnotes in search field
3. check Github as a source
4. find standardnotes, check third option (standardnotes/app), 
5. choose to include prereleases (cause standardnotes stable mobile apps are marked prereleases on github as long as the version matches the latest desktop stable release afaik), 
6. input latest version number in filter release titles field (in this case 3.193.10). 
7. install

**Please complete the following information:**
 - Device: Pixel 8
 - OS: Graphene OS
 - Obtainium Version: v1.1.19

**Comment by ImranR98** [comment]
Yes, try again but with `Mobile` as the filter. I just tried this on a P8P with no issues.
