### ISSUE TITLE
Skip updating apps that can't be updated

### ISSUE THREAD

**Issue by candroid-man** [ImranR98/Obtainium#1782]
**Describe the feature**

Sometimes an app isn't able to update due to various reasons such as being a conflict (whatever that means), and whenever I hit the update all button it'll go out and get the APK files and attempt to update the apps, but if there is an error with one of the apps it will cancel all of the installations. What I'd like is for Obtainium to check for errors for every app, and if there is an error for whatever reason and the app cannot be updated, then the rest of the apps will update as normal.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.21
