### ISSUE TITLE
Can't find suitable release

### ISSUE THREAD

**Issue by astrophilehuwan** [ImranR98/Obtainium#1786]
I can't seem to install Mixplorer Beta, it always say can't find suitable release. Upon checking, it's trying to install x64 version of the app when it should be arm64 or arm version. Is there a way to change this?

**Comment by Gl17chV** [comment]
Why was it closed? What is the solution supposed to be?

**Comment by zecavalo** [comment]
Same error happening

https://mixplorer.com/beta/

**Comment by DwainZwerg** [comment]
Nutzt ihr die Konfiguration von [apps.obtainium.imranr.dev](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.mixplorer.beta%22%2C%22url%22%3A%22https%3A%2F%2Fmixplorer.com%2Fbeta%22%2C%22author%22%3A%22mixplorer.com%22%2C%22name%22%3A%22MiXplorer%20(Beta)%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22A%20file%20manager%20app%20for%20Android%20devices%2C%20offering%20advanced%20features%20such%20as%20root%20access%2C%20cloud%20storage%20integration%2C%20and%20customization%20options.%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%7D)? An der kann ich keine Probleme entdecken.

**Comment by zecavalo** [comment]
Yes, using that default configuration.

**Comment by DwainZwerg** [comment]
Like I said, I can't reproduce it on my end. Weird @ImranR98 any ideas?

**Comment by ImranR98** [comment]
Works for me too.
@zecavalo are you able to download it manually from the website? Might be a network specific issue.

**Comment by ImranR98** [comment]
Also just to confirm - your device uses arm64?

**Comment by zecavalo** [comment]
I can download the correct arm version from the website and it works. 
But the app only gives x86 option.

![Screenshot_20240911_175228.jpg](https://github.com/user-attachments/assets/3eb2eab1-fd6c-4e28-885a-1e9cf8647bba)

**Comment by DarkCrypt** [comment]
I figured this out. What version are you wanting? I'll post an install link.

**Comment by zecavalo** [comment]
> I figured this out. What version are you wanting? I'll post an install link.

Arm64

**Comment by DarkCrypt** [comment]
I'm not sure what the main issue is.

This install link is for arm64 with version number extraction. I've tried this link multiple times and sometimes throws an error. If it does try again and it'll work.

[MixPlorer Beta](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.mixplorer.beta%22%2C%22url%22%3A%22https%3A%2F%2Fmixplorer.com%2Fbeta%2F%22%2C%22author%22%3A%22mixplorer.com%22%2C%22name%22%3A%22MiXplorer%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5B0-9%5D%2B%5C%5C%5C%5C.%5B0-9%5D%2B%5C%5C%5C%5C.%5B0-9%5D%2B%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22arm64%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%2C%22overrideSource%22%3A%22HTML%22%7D
) - arm64

**Comment by DarkCrypt** [comment]
I decided to retry the config from the config website to see if I can diagnose this issue. I received the same result as posted by the other users. This is what I noticed...

After importing app:
1. Obtainium automatically selects x64.
2. No version extraction in place.
3. No apk filter in place.

**Comment by TechniKris** [comment]
It seems that the failure to pick up the `arm64-v8a` variant occurs when the desired APK file has the architecture listed in a slightly different way.
For example:
- Tor Browser lists 64bit ARM as `aarch64`, leading to the report here https://github.com/ImranR98/Obtainium/issues/1013#issuecomment-1890015073,
- Mixplorer Beta lists 64bit ARM as `arm64` (without the `-v8a`), leading to this report.
Both `https://www.torproject.org/download/` ("aarch64") and `https://mixplorer.com/beta/` ("arm64") seem to fail in the same way.

**I suggest aliasing `aarch64` and `arm64` to `arm64-v8a`.**

My specs are:
 - Device: Galaxy A52s 5G
 - OS: stock (Android 14, OneUI 6.1)
 - Obtainium Version: 1.1.58 (F-Droid build)
   - also occurs in 1.2.0 (non-F-Droid build from GitHub releases)

Since I'm using an 64bit ARM device, I'm only affected by `arm64` and `aarch64`, but maybe it'd be a good idea to include more aliases (such as `i386`-`i686`, `IA-32` for 32bit x86; `AMD64`, `x64` for 64bit x86, etc.) to ensure this issue doesn't happen again for someone on a different architecture.

**Comment by Dfainher** [comment]
I don't know if it's ok to comment to an old(er) thread or that I should create my own, but I'm having the same problem with Joplin:

https://github.com/laurent22/joplin-android/releases

I don't use Fdroid and apparently the version on there is missing some features and you don't have the choice between stable and pre-releases. So I would really like to install it through Obtainium...

If anyone could help me I would really appreciate it! 

Thanks in advance! :)

**Comment by DarkCrypt** [comment]
@Dfainher
Adding Joplin only requires the URL for stable releases. Toggle on "Include prereleases" for prereleases as well.

**Comment by Dfainher** [comment]
> [@Dfainher](https://github.com/Dfainher) Adding Joplin only requires the URL for stable releases. Toggle on "Include prereleases" for prereleases as well.

Hey DarkCrypt, thank you for the reply!

What do you mean exactly with 'only requires the URL' ? I did just add the URL mentioned in Obtainium, I also tried with prereleases toggled on but I got the same message.

Do you maybe mean I should add it like this?:
https://github.com/laurent22/joplin-android/

Without the the 'releases' part in the URL or adding the fdroid URL?

Sorry I'm still quite new with this :)

**Comment by DarkCrypt** [comment]
@Dfainher 
Apologies, I should of been more clear.

Adding an app from a Git source (e.g. GitHub, GitLab, Codeberg, etc.) only requires the **main repo URL**.

> Do you maybe mean I should add it like this?:
https://github.com/laurent22/joplin-android/
>
> Without the the 'releases' part in the URL

Yes, precisely. But also without the last `/` (this last character will also throw an error).

So like this: `https://github.com/laurent22/joplin-android`

**Comment by Dfainher** [comment]
@DarkCrypt 
No apologies needed at al!!! I'm very happy that you were willing to help me out, so thank you! :)

I was already trying a bunch of other 'notes' apps, but none of them really did what I wanted them to do. So I'm happy I finally got my trusted Joplin back!

Also, for most (all other?) apps I installed I did add the URL with the 'releases' part at the end and they all worked up until Joplin. Is that 'bad practice' or if it works it works and it's fine?

Thanks again!

**Comment by DarkCrypt** [comment]
@Dfainher 
You're welcome, I'm happy to help if I can!

> Also, for most (all other?) apps I installed I did add the URL with the 'releases' part at the end and they all worked up until Joplin. Is that 'bad practice' or if it works it works and it's fine?

I wouldn't necessarily say adding the releases URL is "bad practice". Obtainium is designed to automatically trim the releases URL down to the main repo URL when adding an app.

I'm not sure why but I've seen a few repos struggle with this and produce an error similar to Joplin. So I always recommend fellow users to use the main repo URL to help avoid these errors. But as long as it works either way is what matters most.

**Comment by Dfainher** [comment]
@DarkCrypt 
Sorry for the late response, thanks for getting back to me. Now it's all clear to me! :)

**Comment by Zokii0** [comment]
Hello, from today for some reason "some errors occured", why is that? It never happened before.

Edit: seems like it fixed itself.

**Comment by Zokii0** [comment]
It's again giving errors that it can't find source etc for more days now.

**Comment by Zokii0** [comment]
Any solution?

**Comment by DarkCrypt** [comment]
@Zokii0 
It looks like Hootan stopped releasing arm64 versions and switched to universal builds for beta.

If you have `arm64` as an APK filter you need to delete that and it should work again.

Or you can try this config I attempted to create as a "fail safe" to retrieve the arm64 version or universal build.

Import App -> [MiXplorer (Beta)](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.mixplorer.beta%22%2C%22url%22%3A%22https%3A%2F%2Fmixplorer.com%2Fbeta%2F%22%2C%22author%22%3A%22mixplorer.com%22%2C%22name%22%3A%22MiXplorer%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22BETA%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22matchLinksOutsideATags%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22partialAPKHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%5C%5C%5Cd%2B%5C%5C%5C%5C.%5C%5C%5C%5Cd%2B%5C%5C%5C%5C.%5C%5C%5C%5Cd%2B%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%5C%5C%5Cbarm%5C%5C%5C%5Cb%7Cx86%7Cx64%5C%22%2C%5C%22invertAPKFilter%5C%22%3Atrue%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22MiXplorer%20(Beta)%5C%22%2C%5C%22appAuthor%5C%22%3A%5C%22Hootan%20Parsa%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22A%20file%20manager%20app%20for%20Android%20devices%2C%20offering%20advanced%20features%20such%20as%20root%20access%2C%20cloud%20storage%20integration%2C%20and%20customization%20options.%5C%22%2C%5C%22refreshBeforeDownload%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3A%22HTML%22%7D)

**Comment by prasetyodedy** [comment]
>It looks like Hootan stopped releasing arm64 versions and switched to universal builds for beta.

mixplorer now released based on architecture, and link above this comment 👆 still works

<img width="240" height="262" alt="Image" src="https://github.com/user-attachments/assets/b0c2f889-6ccd-4824-b705-59e253799988" />
