### ISSUE TITLE
Remember collapse state of category groupings

### ISSUE THREAD

**Issue by grrrrr** [ImranR98/Obtainium#1789]
**Describe the feature**

Obtanium allows the categorization of apps.  When categorized, you can expand or collapse a one or mote categories on the main screen.

If you collapse a categories, this state is only remembered until you navigate away from the main screen,  as which point the category is expanded again

I would like to see Obtanium being able to remember the collapsed status of a category through out its use.

This would allow, for example to have a `not used` category collapsed and the apps out of view until you expand the category

**Comment by ImranR98** [comment]
Including this as part of #1729.
