### ISSUE TITLE
Could not get ID from APK - GitLab source app Key Driver

### ISSUE THREAD

**Issue by alexwaibel** [ImranR98/Obtainium#1790]
**Prerequisites**

Appears similar to this resolved issue: https://github.com/ImranR98/Obtainium/issues/1506

**Describe the bug**

When attempting to add `https://gitlab.com/kunzisoft/android-hardware-key-driver`, I get the error "Could not get ID from APK".

**To Reproduce**

Screen looks identical to the one shown in the related issue linked above and I didn't see any relevant artifacts. Happy to provide more details though if you need.

**Please complete the following information:**
 - Device: Pixel 6
 - OS: Latest GrapheneOS
 - Obtainium Version: v1.1.19

**Additional context**

I can see the release artifact at `https://gitlab.com/kunzisoft/android-hardware-key-driver/-/releases`. In other related incidents I see it was suggested the app may not be compatible with my device, but I was able to manually install the apk from that release page.

Thanks for all the hard work on this project! It's been a great way to manage my apps, would love to migrate this one from Aurora to Obtainium.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.20
