### ISSUE TITLE
Obtainium is not marked to track pre-releases, yet I was offered to update

### ISSUE THREAD

**Issue by stdedos** [ImranR98/Obtainium#1798]
**Prerequisites**

**Describe the bug**

Release is marked as pre-release at the time of writing:

![image](https://github.com/user-attachments/assets/bdfb40fd-b7c6-4939-aa9e-cae46ff1cba2)
https://github.com/rustdesk/rustdesk/releases/tag/1.3.0

Obtainium is not marked to track pre-releases:

![image](https://github.com/user-attachments/assets/bacd35ce-5b3b-4be3-8a3e-5d2f12c27adc)

Yet I was offered to update

https://github.com/rustdesk/rustdesk/releases/releases/latest leads to https://github.com/rustdesk/rustdesk/releases/tag/1.2.7

**To Reproduce**

**Screenshots and Logs**

**Please complete the following information:**
 - Device: 
 - OS: 
 - Obtainium Version: 

**Additional context**

**Comment by ImranR98** [comment]
If you pull to refresh, does it still say that 1.3.0 is the latest?

**Comment by stdedos** [comment]
No, it "disappeared" and it returned to 1.2.7

Fluke / "Issue of the moment"?

**Comment by ImranR98** [comment]
The most likely explanation is that 1.3.0 had not been marked as a pre-release when Obtainium checked before.
