### ISSUE TITLE
Bug: does not show the latest version of the apk available

### ISSUE THREAD

**Issue by lamyergeier** [ImranR98/Obtainium#1804]
**Prerequisites**

**Describe the bug**

The screenshot is self explanatory. See the  version number for the latest and installed apk. 

**To Reproduce**

![Screenshot_20240821_170642.jpg](https://github.com/user-attachments/assets/85d6258c-1f79-408f-b4d0-3aaf684902a1)

**Screenshots and Logs**

**Please complete the following information:**
 - Device:  Samsung A33
 - OS:  14
 - Obtainium Version:  1.1.20

**Additional context**

**Comment by ImranR98** [comment]
What do your additional settings looks like? You most likely have some bad filters/options there.

[This link](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.github.catfriend1.syncthingandroid.debug%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2FCatfriend1%2Fsyncthing-android%22%2C%22author%22%3A%22Catfriend1%22%2C%22name%22%3A%22Syncthing-Fork%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Afalse%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22useLatestAssetDateAsReleaseDate%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22github_%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%2C%22overrideSource%22%3Anull%7D) will give you a config that works
