### ISSUE TITLE
Use Wix Madefor Text for small text

### ISSUE THREAD

**Issue by FixItKit** [ImranR98/Obtainium#1808]
**Describe the feature**
Wix Madefor Text should be used for small or medium sized text (app authors, the names of settings, app descriptions,  instead of Wix Madefor Display. The display font is not intended to be used for small or medium sized text.

**Comment by ImranR98** [comment]
Wix may have decided to make small adjustments to each variant of the font for their own purposes, but I doubt there is any actual impact to readability in an app like Obtainium where most text elements are only a few words long. Besides, most fonts don't even make the distinction between "for text" and "for display" uses, and I don't think it's been an issue for them.

So unless you have evidence this font is actually more readable than the one we currently use, I'm still going with my comment in PR #1793.

**Comment by ImranR98** [comment]
Unnecessary complexity
