### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by Ketsuyumi** [ImranR98/Obtainium#1812]
When refreshing the app to check for updates, I get too many requests saying to wait for 28 minutes and it says the same after I waited, reinstalled the app deleted cache restarted phone resetted wireless debugging idk what else to try. Can't use the app:/

 - Device: Samsung Galaxy S23 Ultra
 - OS: One UI 6.1
 - Obtainium version: 1.1.20

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/wiki#github
