### ISSUE TITLE
[Question]: Briar?

### ISSUE THREAD

**Issue by Sami32** [ImranR98/Obtainium#1814]
Did anyone succeed to add this application?

https://code.briarproject.org/briar/briar/-/tags
https://briarproject.org/fdroid/repo/

**Comment by DarkCrypt** [comment]
A few ways to add this app.

1. Website
URL: `https://briarproject.org/installing-apps-via-direct-download/`
Override Source: `HTML`
Filter APKs by Regular Expression: `briar.apk`

2. F-Droid Third Party Repo
URL: `https://briarproject.org/fdroid/repo/`
Override Source: `F-Droid Third Party Repo`
App ID or Name: `briar`

3. F-Droid
URL: `https://f-droid.org/en/packages/org.briarproject.briar.android`
Override Source: `F-Droid Official`

4. Search feature within the Add App tab or Import/Export tab.

**Comment by Sami32** [comment]
@DarkCrypt Thank very much for your help and very informative answer +1

**Comment by Sami32** [comment]
Sadly no one work for me with Android 7.0 (Xiaomi)
![IMG_20240829_014848](https://github.com/user-attachments/assets/6e31615c-28f4-4dd0-b4da-44d42cd6e333)

**Comment by DarkCrypt** [comment]
@Sami32 
You're welcome friend. That sucks it's not working for you.

**Comment by DarkCrypt** [comment]
@ImranR98 
According to the above screenshot, duplicate of #1663. Just a different app. Appears to be device specific?

**Comment by ImranR98** [comment]
Yes, looks like a duplicate
