### ISSUE TITLE
Сделайте что из телеграмм канала можно было отслеживать и скачивать апк | Make it possible to track and download the apk from the telegram channel

### ISSUE THREAD

**Issue by livxbox5** [ImranR98/Obtainium#1818]
Сделайте что из телеграмм канала можно было отслеживать и скачивать апк файлы и устанавливать в автоматически  режиме 

Make it possible to track and download apk files from the telegram channel and install in automatic mode

**Comment by DwainZwerg** [comment]
Duplicate See #1
