### ISSUE TITLE
Incorrect source detected with direct .apk link

### ISSUE THREAD

**Issue by Ghoelian** [ImranR98/Obtainium#1820]
**Describe the bug**
When adding a direct link to an .apk file, Obtainium seems to auto-detect the source as HTML. When I click add, it loads for a while, after which the "could not find a suitable release" toast pops up.

If I manually override the source to direct APK link, everything works as expected.

**To Reproduce**
1. Add new source
2. Paste https://proton.me/download/DriveAndroid/ProtonDrive-Android.apk
3. Click add without override
4. Source doesn't get added

**Screenshots and Logs**

**Please complete the following information:**
 - Device: Pixel 8 Pro
 - OS: GrapheneOS
 - Obtainium Version: 1.1.19 (F-Droid)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.21
