### ISSUE TITLE
Location services not working Whatsapp and Organic Maps

### ISSUE THREAD

**Issue by Rootbeat** [ImranR98/Obtainium#1822]
**Describe the bug**
Whatsapp and Organic Maps are nooit getting a location. I thick three location services are not working properly. For other apps it is working. Also for the F-droid version of Organic Maps (through Droid-ify) it is working. Location permissions are set properly.

**Please complete the following information:**
 - Device: poco f2 pro
 - OS: crDroid
 - Obtainium Version: 1.1.2

**Additional context**
I doubt if it is an Obtainium bug, but I only experience it with apps installed with Obtainium.

**Comment by ImranR98** [comment]
Definitely not an Obtainium issue (unless the apps are checking where they were installed from and modifying their behaviour based on that, which is possible but unlikely).
