### ISSUE TITLE
Please lower severity of notifications

### ISSUE THREAD

**Issue by ratti** [ImranR98/Obtainium#1823]
**Describe the feature**

Saturday morning. 
7:00 a.m. 
My phone: "DRING!!!!!!" — a notification.

What happened? “Obtainium could not… (some network message because Github wasn't available) 

Suggestion:
I don't want to sound unfriendly, but Obtainium is not _that_ important. It should not cause notifications with sound.

**Comment by DwainZwerg** [comment]
You can set this yourself in the notification settings. Just like the "Do not disturb" mode.

**Comment by ImranR98** [comment]
This is subjective. Android lets you customize the behaviour of different notifications in a very granular way, per notification type.

**Comment by ratti** [comment]
Well… not nice.
I know I can reconfigure that, that was the first thing I did AFTER I was woken up at 7 in the morning. But… why? A home network going away for some time is quite normal thing - if every app would ring and tell the user, the phone would ring half the day?
