### ISSUE TITLE
Add per-app option to allow insecure downloads (expired certificate, certificate for wrong domain etc.)

### ISSUE THREAD

**Issue by soredake** [ImranR98/Obtainium#1825]
**Prerequisites**

**Describe the feature**
This will help with problems like this:
https://github.com/ImranR98/Obtainium/issues/1458
https://github.com/ImranR98/Obtainium/issues/1819

**Describe alternatives you've considered (if applicable)**
Not being able to update certain app because sys-admins too lazy to renew certificate for example.

**Additional context**

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.21

Only tested with the "expired certificate" page on https://badssl.com/ (obviously no APK available, just compared error messages). Hopefully it works for actual use cases too.
