### ISSUE TITLE
Show live info when adding apps

### ISSUE THREAD

**Issue by y-hbb** [ImranR98/Obtainium#1828]
**Prerequisites**

**Describe the feature**

In add apps screen, can you display matching APK/release/info live and update matches as regex or other fields change.

**Describe alternatives you've considered (if applicable)**

**Additional context**

**Comment by ImranR98** [comment]
Not practical given how the UI works (plus it would very quickly lead to rate limiting from GitHub and probably other sources).

**Comment by y-hbb** [comment]
You could get the response once for the url. If you are scrapping using html, you could use the same response to get the updated result. I am hoping it would be the same for github as well. Might work if you think of using caching.
