### ISSUE TITLE
Certificate Verification fails for 3rd-Party F-Droid Repo

### ISSUE THREAD

**Issue by AntiMarinetti** [ImranR98/Obtainium#1829]
I started setting up a local (i.e., "3rd-Party") F-Droid-Server on my local network. The integration to Obtainium was easily being done and I was able to install a couple of Apps.

The problem is, that,once I enabled SSL-encryption on the F-Droid-Server I get the following Error: `CERTIFICATE_VERIFY_FAILED: unable to get local Issuer`. The certificate  of the F-Droid server is signed by my own root CA, the corresponding root certificate is installed on the device that runs Obtainium (e.g., I can reach the F-Droid-Website with a Browser via SSL without any problems).

Does Obtainium use its own certificate-store, and if so, how to add certificates to it?

**To Reproduce**
1. Click on `Add App`
2. Enter the address of your local F-Droid-Server (e.g., `https://fdroid.my-own-network/`, which is reachable e.g. via Browser)
3. Add arbitrary `App-ID`
4. Error `CERTIFICATE_VERIFY_FAILED: unable to get local Issuer`

**Please complete the following information:**
 - Device: Pixel 6A
 - OS: GrapheneOS
 - Obtainium Version:  v1.1.20

**Comment by ImranR98** [comment]
This is a known issue with flutter apps, somehow they don't pick up on certificates added to the OS. See existing issue #1458.

There's a new per-app toggle that was just added in yesterday's update that tells Obtainium to accept insecure connections. Give it a try and let me know if it works.

**Comment by ImranR98** [comment]
Follow up in the existing issue.

**Comment by AntiMarinetti** [comment]
Hi, yes, that works, thanks. Of course it's not the optimal solution, but if it's a flutter issue, there's probably nothing better we could do...
