### ISSUE TITLE
Signal controlled by Obtainium refuses to restore backup from former not-Obtainium controlled Installation

### ISSUE THREAD

**Issue by Peter0** [ImranR98/Obtainium#1833]
**Prerequisites**
I used to use messenger Signal on Android-derivate by installing it via https://signal.org/android/apk/

**Describe the bug**
When installing current Signal via Obtainium, after starting Signal and choosing to restore from existing backup, signal hangs/refuses to restore from backup.
After choosing the backup file, Signal prompts for the 30 or so digit restoring key. After that, it shows progress by counting the number of restored messages (it shows only integer multiples of 100). After a while, progress shows some thousands of messages, but far from being completed, it repeats to ask for backup file. Now, it's almost immediately that it asks again and again. It doesn't matter then if I enter the correct 30-digit key or a wrong one. (Haven't tested what happens if I enter a wrong one in the first place.)

After deinstall Signal and reinstall it from signal.org/android/apk as formerly done, there is no problem in restoring the backup.

**To Reproduce**

1. Download Signal from mentioned url; install it by means of file manager
2. Set it up and use it.
3. Make a backup with Signal's chat-backup functionality
4. Deinstall Signal
5. Use Obtainium to reinstall it
6. Start freshly installed Signal and try to restore the backup

**Please complete the following information:**
 - Device: Samsung Galaxy J5
 - OS: /e/OS
 - Obtainium Version: 1.1.19

**Additional context**
May it has something to do with the context from where the installation is launched? First place this is file manager, that takes the apk file and hands it over to installer. Later, it is Obtainium that provides the apk file and launches the installer.

**Comment by ImranR98** [comment]
That is very weird given that Obtainium just automates the manual process - it downloads the exact same APK. I'm not convinced it's an Obtainium issue but will keep the issue open and try to see if I get the same error on my device later.
Could you try repeating your steps multiple times? I want to make sure it happens consistently.

**Comment by Peter0** [comment]
May you give me the (temporary?) location where I can find the APK file that Obtainium has downloaded? Just to double check and compare the APKs?

**Comment by ImranR98** [comment]
`/Android/data/dev.imranr.obtainium/cache`

Some file managers can't access the `data` folder though, so you might need to try different ones.

**Comment by Peter0** [comment]
> I'm not convinced it's an Obtainium issue 

Probably it's an Signal issue. But due to Signals policy to say "use Play Store only if you want to get support" I think it the best to try to let Signal feel no difference from where it is installed.
I hope I find the time to give it another try.

**Comment by sammumm42** [comment]
@ImranR98 Just recovered: 

1. Signal.org landing page leads, all paths i could find, to Google Playstore
2. Playstore delivers 8.8.2 (!) - this should have been applied to dead xperia too
3. https://signal.org/android/apk/ delivers apk 8.7.3. (labeled 'danger zone', are they kidding?)
4. Obtainium delivered 8.7.3, which is not so wrong, with an eye on 3.
5. Flatpak@xubuntu delivers 8.8.0 - combines with 8.8.2
6. apkmirror flags 8.8.2 as beta (other apk sites not, appearently apkmirrors mistake)

what the hell drives Signal to host an old apk on their site?

In the end, they force us to Use Playstore or drop our Signal history.
