### ISSUE TITLE
Home Page UI Improvement Suggestions

### ISSUE THREAD

**Issue by yqs112358** [ImranR98/Obtainium#1834]
**Describe the feature**

I love Obtainium so much when I discovered it. Although I have not yet tried Flutter, I hope I can make some suggestions to make him better🥰

Actually I think the design of the fixed footer can be improved. It would be visually clearer to split these functions into two groups, based on the default state and the state of selecting apps

In default state, the difference:
<img src="https://github.com/user-attachments/assets/ad99b031-e024-4ce7-970e-6974fcbffdf0" width="75%" />

And when long-press any app, it will change into selection mode. Maybe we can make designs like either one of them:
<img src="https://github.com/user-attachments/assets/bd68eea7-f894-4bb1-8b98-955559abb451" width="75%" />

**Comment by ImranR98** [comment]
I think having some controls at the top of the screen would be confusing and harder to reach. Also prefer the existing design in general (though that's subjective). The drop shadows and floating buttons in general don't fit in with the rest of the flat look.
