### ISSUE TITLE
Cache app icons

### ISSUE THREAD

**Issue by FixItKit** [ImranR98/Obtainium#1837]
**Describe the feature**
Obtainium should cache app icons to reduce slowdown while Obtainium is loading the icons. Obtainium should check if the icon has changed and reload it if it has.

Also could you check out this earlier issue I made: https://github.com/ImranR98/Obtainium/issues/1766

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.22
