### ISSUE TITLE
Cloud backup and F-Droid Third-Party Repos

### ISSUE THREAD

**Issue by katastrophe92** [ImranR98/Obtainium#1838]
Hello Obtainium team and community!

It would be great to be able to have the option to save the Apps and settings to a cloud backup.

I would like to have a F-Droid Third-Party Repos list and pick only the Repos I want to have. The same Third-Party Repos system like F-Droid, Neo Store and Droid-ify.  Or the option to import a link list of Third-Party Repos to save into Obtainium.
Hope those are good Features and will be implemented in the future.

Hope you understand what I mind, English is not my first language. Thanks!

**Comment by ImranR98** [comment]
I think a first party cloud backup system is out of scope. You could use the auto-export feature alongside a third party cloud backup. For example Syncthing works (though that's not exactly cloud backup).

See also #1267.

**Comment by katastrophe92** [comment]
@ImranR98 hi and thanks for the reply.
And what do you think about a F-Droid Third-Party Repos list to have inside Obtainium?

**Comment by ImranR98** [comment]
You should open a separate issue for that as it is a totally different thing.
