### ISSUE TITLE
Can't install Anki

### ISSUE THREAD

**Issue by oleksiidn** [ImranR98/Obtainium#1843]
**Prerequisites**

**Describe the bug**
I can't install Anki https://github.com/ankitects/anki by providing a link to the github repository, or release page.

**To Reproduce**

Open Add app tab in Obtanium app and provide a [link](https://github.com/ankitects/anki/releases) and press add button. 

**Screenshots and Logs**
![image](https://github.com/user-attachments/assets/fb8e7ea7-e1b5-453d-85ed-b34440ebb37c)

**Please complete the following information:**
 - Device: Readme Note 10 pro
 - OS: Android 13
 - Obtainium Version: v1.1.21 

**Additional context**

**Comment by ImranR98** [comment]
The repo doesn't have any APKs attached to its releases (doesn't look like it's even a repo for an Android app).

**Comment by Tvastr-ops** [comment]
That's not the Android fork repo. That's the orginal anki repo bro.
