### ISSUE TITLE
App cannot Install. 

### ISSUE THREAD

**Issue by prajwalpatil2204** [ImranR98/Obtainium#1845]
When installing or Updating App, it downloads but cannot Install. When the install starts, package installer instance doesn't open obtainium directly exits.
Also, when adding app from uptodown, it says enter valid URL. 

Phone details
Redmi note 10
MIUI 14 Android 12
Obtainium version - 1.1.21

**Comment by DwainZwerg** [comment]
Regarding uptodown: Can you check what kind of URL you are trying to add? One with language code, such as https://de.uptodown.com/ or one without language code https://uptodown.com/? Can you try it again without language code if you tried it with language code before?

**Comment by ImranR98** [comment]
I'm assuming this is the same as https://github.com/ImranR98/Obtainium/issues/1321#issuecomment-1902702621. Try disabling the MIUI setting.

**Comment by prajwalpatil2204** [comment]
I have followed the steps given in the issue. I helps to solve the problem.
