### ISSUE TITLE
Firefox version is parced incorrectly

### ISSUE THREAD

**Issue by IRainman** [ImranR98/Obtainium#1847]
Current version is 130.0.1, but obtainium says that only version  130.0 is available

**Comment by DwainZwerg** [comment]
As I have already explained [here](https://github.com/ImranR98/apps.obtainium.imranr.dev/discussions/155#discussioncomment-10081390), it is not possible to record these intermediate versions without also recording the beta versions.

**Comment by patrickstedem** [comment]
This is an issue with the configuration. I played around with it when I first started using Obtainium to install/update Firefox until the intermediate versions worked properly. 130.0.1 works fine for me using this: [Config](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22org.mozilla.firefox%22%2C%22url%22%3A%22https%3A%2F%2Fdownload.cdn.mozilla.net%2Fpub%2Ffenix%2Freleases%2F%22%2C%22author%22%3A%22download.cdn.mozilla.net%22%2C%22name%22%3A%22Firefox%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.)%3F(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.)%3F(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.%5C%5C%5C%5Cd%2B)%2B%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Atrue%7D%2C%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22android%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%2C%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22fenix-(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.)%3F(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.)%3F(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.%5C%5C%5C%5Cd%2B)%2B-android-arm64-v8a%2F%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.)%3F(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.)%3F(%3F%3A(%5C%5C%5C%5Cd%2B)%5C%5C%5C%5C.%5C%5C%5C%5Cd%2B)%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22Gecko-based%20browser%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3Anull%7D)

**Comment by DarkCrypt** [comment]
Slightly adding to the existing config also selects 130.0.1.
