### ISSUE TITLE
"Follow System" in language setting does not work properly

### ISSUE THREAD

**Issue by bluefly000** [ImranR98/Obtainium#185]
device: pixel 6a runnning GrapheneOS
app ver: 0.9.3

The first time Obtainium is launched, it works correctly, but if you change to another language and then change back to "Follow System", the language in the application will be set to English.
The system language of my smartphone is Japanese. I changed the system language to Chinese and reinstalled Obtainium, and the same thing happened.

![Screenshot_20221222-173150](https://user-images.githubusercontent.com/101441707/209096410-cca6e21f-0d9f-493f-9599-c5ae89873a02.png)

**Comment by ImranR98** [comment]
Should be okay now: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.4-beta
