### ISSUE TITLE
multi assets update bug (Youtube Revanced)

### ISSUE THREAD

**Issue by TanujairamV** [ImranR98/Obtainium#1852]
**Prerequisites**
yes
yes

**Describe the bug**
when i add https://github.com/revanced-apks/build-apps and install it, even though the revanced apk is in the latest version it is asking for an update

**To Reproduce**

**Screenshots and Logs**

![image](https://github.com/user-attachments/assets/975acd25-4c72-49e0-a7a0-09ad4e9c4663)

**Please complete the following information:**
 - Device: HP (using obtanium on Windows Subsystem for Android)
 - OS: Windows 11
 - Obtainium Version: Latest

**Additional context**

**Comment by DarkCrypt** [comment]
Revanced publishes releases in an unusual way. The release date is the detected version.

This config will fix the update and pick the apk you want. After importing or manually changing the below options, click the check mark and "Mark as Updated".

[YouTube Music - Revanced](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22app.revanced.android.apps.youtube.music%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Frevanced-apks%2Fbuild-apps%22%2C%22author%22%3A%22revanced-apks%22%2C%22name%22%3A%22YouTube%20Music%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Afalse%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22useLatestAssetDateAsReleaseDate%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22music-revanced-v%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%2C%22overrideSource%22%3A%22GitHub%22%7D) - install link

Config= YouTube Music - Revanced
App Source URL: `https://github.com/revanced-apks/build-apps`
Override Source: `GitHub`
Toggle off: `Reconcile version string with version detected from OS`
Filter APKs by Regular Expression: `music-revanced-v`

**Comment by Tanujairam-TG** [comment]
Fixed ! Thank you for responding.

**Comment by TanujairamV** [comment]
https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root

In this repo they releases the apk with the same releases , 
Am I able to use this repo with Obtanium
