### ISSUE TITLE
SourceHut Broken

### ISSUE THREAD

**Issue by Hamster45105** [ImranR98/Obtainium#1864]
**Describe the bug**

Trying to add [Cheogram](https://git.singpolyma.net/cheogram-android/) to Obtainium using the _SourceHut_ source results in `Could not find a suitable release`

**To Reproduce**

1. Try to add [https://git.sr.ht/~singpolyma/cheogram-android/refs](https://git.sr.ht/~singpolyma/cheogram-android/refs) using the SourceHut source
2. See error

**Please complete the following information:**
 - Obtainium Version: 1.1.23

**Additional context**

**Comment by ImranR98** [comment]
Whoops. Just realized you're the person who posted this: https://github.com/ImranR98/apps.obtainium.imranr.dev/issues/241#issuecomment-2381641672

Your config does work for me (in fact the one I posted above does not). Is the config from your comment not working on your end?

**Comment by ImranR98** [comment]
Ah, your config has some intermediate links that ideally should not be needed.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.25
