### ISSUE TITLE
GitHub packages do not fall back to global GitHub token

### ISSUE THREAD

**Issue by mordae** [ImranR98/Obtainium#1866]
Adding a GitHub package without specifying the access token in its options results in quota exceeded errors since the globally configured token is not used. One must repeat the token for every such package, which is tedious.

On top of that, it is impossible to change the per-package token, meaning after one finds that they have too many packages, one has to go through them all and re-add them.

Once the token expires, one would have to re-add all the packages to change the token as well.

1. Please make it so that the packages fall back to the globally configured token.
2. Remove the per-package token or make it editable so that one could replace it once it expires.

**Comment by ImranR98** [comment]
Not sure what you mean by GitHub "package" - could you provide an example?

**Comment by mordae** [comment]
Packages installed from GitHub releases. Added by searching GitHub from Obtainium.

For example Obtainium.

**Comment by mordae** [comment]
My case:

1. Add a bunch of packages by searching GitHub.
2. Quota exceeded.
3. Add global token.
4. Search goes fine, add or update gives quota exceeded.
5. Remove all packages and add them with the same token explicitly repeated in their configuration.
6. Worry I'd have to do it again in a year or so after the token expires.

**Comment by ImranR98** [comment]
> 5. Remove all packages and add them with the same token explicitly repeated in their configuration.

There is no way to provide a token for each app individually for GitHub. The only exception is if you use the "source-override" dropdown which is meant for users who want to point to an unofficial GitHub-compatible API. If your apps are on GitHub, just let Obtainium figure out what source to use (unless you explicitly want to use a different token from the one in the settings page).

If I've misunderstood, please upload a screen recording of what you're trying to do.

**Comment by ImranR98** [comment]
Should be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.26
