### ISSUE TITLE
Please add an option to parse versions from GitHub release titles instead of release tag

### ISSUE THREAD

**Issue by foundObjects** [ImranR98/Obtainium#1875]
**Describe the feature**

Per title please add an option to parse versions from GitHub release titles rather than their tag.

Shattered Pixel Dungeon beta releases are all released under a single `vN.N.N-BETA` tag updated with the current beta version. Accurate version info is contained in the release title (`vN.N.N-BETA-N`) and APK file name, multiple beta updates aren't detected without using release time pseudo versioning.

See:
https://github.com/00-Evan/shattered-pixel-dungeon/releases

A new beta should be available within the next couple of days (following 2024-10-01)

**Describe alternatives you've considered (if applicable)**

Using pseudo versioning works but makes it difficult to see which version is installed from within obtainium

**Comment by ImranR98** [comment]
You can use the title as a "version" now, then use the "trim version" field: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.26

**Comment by foundObjects** [comment]
Thanks! This is exactly what I needed.
