### ISSUE TITLE
Working with monorepos

### ISSUE THREAD

**Issue by slcw** [ImranR98/Obtainium#1877]
**Prerequisites**
I searched existing issues and looked through the wiki and didn't find anything about this using the keywords I thought were most relevant. 

**Describe the feature**
Some developers have made the decision to use a single co-mingled repo for multiple apps. Tuta is one, Ente is another. Obtainium is unable to differentiate between the multiple apps, and it returns updates for whichever app happens to be most current. If you only use one of the apps, Obtainium returns repeated errors about the downloaded package ID not matching when a new version of the unused apps is posted. 

The current solution is to manually download the desired package when it's updated. But new available version indicator remains in Obtainium, and it throws an error everytime it checks for updates. It would be good if Obtainium could discern when there are multiple package IDs in a single repo, and handle them accordingly.

**Comment by ImranR98** [comment]
There is no way to tell in advance (at least for most GitHub apps) what the appid is without downloading the APK, which is not practical. You can use the various filtering options to get the APK you want - see the wiki for details. You can add the same URL multiple times as long as the resulting appid is different.
