### ISSUE TITLE
Invalid WireGuard version detection

### ISSUE THREAD

**Issue by marcoismobile** [ImranR98/Obtainium#1879]
**Describe the bug**
After adding the following WireGuard URL:
https://download.wireguard.com/android-client

The application is added correctly and can be installed, but the showed version seems to be incorrect:
1.0.20231018 Installed
5235326 Latest

However the APK url is as follow:
https://download.wireguard.com/android-client/com.wireguard.android-1.0.20231018.apk

Not sure if this is fixable in some way by changing the regex version in settings, or does it need some other 'fix'?

Thanks in advance!

**To Reproduce**
- Add WireGuard app with https://download.wireguard.com/android-client url
- Install WireGuard

**Please complete the following information:**
 - Device: Pixel 8
 - OS: GrapheneOS
 - Obtainium Version: 1.1.26

**Comment by DarkCrypt** [comment]
Add a Version String Extraction ReGex:
`[0-9]+\.[0-9]+\.[0-9]+` or `\d{1,2}\.\d{1,2}\.\d{8}`

Either one will work.

**Comment by marcoismobile** [comment]
@DarkCrypt Thanks this works perfectly!

This solves my problem, so I am closing the issue.

**Comment by CodeWithMa** [comment]
Add to https://apps.obtainium.imranr.dev/?

**Comment by DarkCrypt** [comment]
@DwainZwerg & @Hamster45105
Request above.
