### ISSUE TITLE
Bug: Kiwi Browser

### ISSUE THREAD

**Issue by User1l0** [ImranR98/Obtainium#1893]
Says app not found for kiwi browser link
https://github.com/kiwibrowser/src.next/releases

**Comment by DwainZwerg** [comment]
Did you use the search or try it manually (in principle it should work either way, just to check the problem the info would be helpful)?

**Comment by ImranR98** [comment]
You need to enable "include prereleases".
It's also a good idea to use an APK filter given that there are so many to choose from.
