### ISSUE TITLE
could not get ID from APK

### ISSUE THREAD

**Issue by ExpandingMan** [ImranR98/Obtainium#1898]
**Describe the bug**
When attempting to install https://apkpure.net/apple-music/com.apple.android.music , get error message
```
Could not get ID from APK [Apple Music]
```
It's possible this happens with other apps from apkpure, I haven't checked.

**To Reproduce**
Add apple music app from https://apkpure.net/apple-music/com.apple.android.music.
Try to install

**Please complete the following information:**
 - Device: Pixel 8 Pro
 - OS: Graphene OS latest
 - Obtainium Version: 1.1.26

**Comment by ImranR98** [comment]
I just tried installing Apple Music from APKPure manually and it doesn't work that way either, regardless of whether I choose APK or XAPK. So this is not an Obtainium issue - it looks like what APKPure is providing just isn't compatible despite being labelled arm64-v8a (I'm also on a Graphene P8P).

I've noticed this happening with other apps on APKPure too. No obvious way to tell which releases have this issue.
