### ISSUE TITLE
Can you add Root Install (silent install) option?

### ISSUE THREAD

**Issue by matt873** [ImranR98/Obtainium#19]

**Comment by ImranR98** [comment]
No plans for special support for rooted devices.
If you mean silent background updates (after first-time prompted install), that will be added when there is a Flutter plugin that provides it (see https://github.com/ImranR98/Obtainium/issues/12#issuecomment-1248796683).

**Comment by rajarshikhatua100** [comment]
what about this https://github.com/2shrestha22/libsu_flutter
