### ISSUE TITLE
Allow to downgrade an app install? Or chose a release?

### ISSUE THREAD

**Issue by Joshndroid** [ImranR98/Obtainium#1903]
I was wondering after recent issues with the nextcloud android app if we could have the ability to downgrade an app?

I assume due to the way android doesn't like that it is possibly not able to be done

But as an alternative I wonder if we could have the ability to choose a prior version and have it chained to the uninstallation of the previous app. So that it uninstalls the possibly broken app and then it installs the most recent prior release

**Comment by ImranR98** [comment]
Android won't allow you to downgrade, but it is possible with some workaround. See #107.
Chaining to uninstall is a niche feature and would require significant changes to the code (how would update checking work if a version is hardcoded).
