### ISSUE TITLE
Obtainium suggests downgrade from v1.10 to v1.9

### ISSUE THREAD

**Issue by inflationsbereinigt** [ImranR98/Obtainium#1908]
**Prerequisites**

Set up Harmony Music: [Config](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.anandnet.harmonymusic%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Fanandnet%2FHarmony-Music%22%2C%22author%22%3A%22anandnet%22%2C%22name%22%3A%22Harmony%20Music%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Atrue%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Atrue%2C%5C%22dontSortReleasesList%5C%22%3Atrue%2C%5C%22useLatestAssetDateAsReleaseDate%5C%22%3Afalse%2C%5C%22releaseTitleAsVersion%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22v%3F(%5B0-9.%5D%2B)%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%241%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22.*-arm64-v8a-release.apk%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%2C%22overrideSource%22%3A%22GitHub%22%7D)

**Describe the bug**
The latest version suggested is v1.9.2, however the actual latest version is 1.10.x. I suspect thty Obtainium doesn't correctly sort versions (i.e. versuon sorting should match the output of `sort -v`), making 1.9 end up above 1.10.

**To Reproduce**
1. Set up the config
2. Check for updates
3. Check the suggested version on the app detail view.

**Please complete the following information:**
 - Device: FP4
 - OS: Android 14 (Calyx)
 - Obtainium Version: 1.1.26 F-Droid

**Comment by DarkCrypt** [comment]
Not an Obtainium issue, your config is wrong.

Using your config, if you delete your entire filter from "Filter APKs by Regular Expression" it works.

Also, you're doing too much. The other filters you have set are unnecessary. The default filters are enough.
