### ISSUE TITLE
List of niche app sources and their support

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#191]
No pressure to implement these sources, as few apps use them,  but I figure it would be nice for people to have a place to post niche sources and find information about their support. 
And to have a place to find out how to add from certain sources.

**Comment by S7venLights** [comment]
###Sourceforge (unsupported)

Open Camera: 
https://sourceforge.net/projects/opencamera/files
(Available on F-droid and Playstore)

**Comment by S7venLights** [comment]
InviZible Pro

Code is released on Gitlab and website, but easiest to use this Github: 

https://github.com/gedsh/invizible

**Comment by S7venLights** [comment]
KDE Android 
Code Source https://invent.kde.org/plasma-mobile/krecorder.git

But use the Third party F-droid repo: 
https://cdn.kde.org/android/fdroid/repo

Use the app ID to add the right app eg: 

org.kde.krecorder

**Comment by S7venLights** [comment]
UntrackMe

Code released at: 
https://framagit.org/tom79/nitterizeme
(Not supported)

Only at: 
https://www.f-droid.org/packages/app.fedilab.nitterizeme/

**Comment by ImranR98** [comment]
> ###Sourceforge (unsupported)
> 
> Open Camera: https://sourceforge.net/projects/opencamera/files (Available on F-droid and Playstore)

SourceForge is supported (specifically just tried Open Camera).

**Comment by ImranR98** [comment]
Also I don't think GitHub issues is the right place for this kind of info, especially as it is not directly related to the app (it's up to the user to figure out what source to get their apps from).

**Comment by S7venLights** [comment]
Was just thinking, if people come and post issues about apps in future. They may see this one and not re-post.
Save you some time. 
But I've noticed you really don't like open issues 😋. 
I could put info like this elsewhere where you could link to. Let me know if you want that.

**Comment by ImranR98** [comment]
> But I've noticed you really don't like open issues 😋. 

Hate em 😁

The issue doesn't need to be open though, we could always pin it even as a closed issue - I just don't think it's that necessary.

I'm mainly just thinking that it isn't this repo's job to maintain specific app lists for people. Especially since in many cases it should be obvious to the user what to do - for example UntrackMe has an F-Droid link right on their webpage.

**Comment by S7venLights** [comment]
"for example UntrackMe has an F-Droid link right on their webpage."

Yes but since the point of this app is to avoid F-droid, I posted Untrack me's Framagit as an unsupported one.

**Comment by S7venLights** [comment]
No stress though

**Comment by sevmonster** [comment]
I recommend https://github.com/ImranR98/Obtainium/issues/285, it's easy and zero-cost.
