### ISSUE TITLE
Best way to check and update app with broken versioning?

### ISSUE THREAD

**Issue by noto10** [ImranR98/Obtainium#1911]
I have an app on my list which does not report correct version and thus, keeps showing a non-existent update.

This is the app:

https://github.com/billthefarmer/specie/releases

I've searched past issues and noted in particular the following:

[https://github.com/ImranR98/Obtainium/issues/404](url) which seems to describe a similar problem.

What would be the way, if any, to configure Obtainium to work with an app like this?

Recording of update failure:

https://github.com/user-attachments/assets/86cb756f-db19-42ff-96d3-63f238e7f002

**Comment by GhostShadow0316** [comment]
I have the same problem with updates of the app [Linkora](https://github.com/sakethpathike/Linkora/releases/)
it keeps showing there's an update even though the installed one is the latest
![Screenshot_20241017_235419](https://github.com/user-attachments/assets/fa87124d-482a-425b-b17b-95862c288a59)
I clicked the "Update" but after the "Apps Updated" message
it still shows there is a new update

**Comment by DarkCrypt** [comment]
@noto10 
Not an Obtainium issue.

Looking at the GitHub releases v1.8 is still v1.7 which is producing your initial conflict. Besides this, there's no apk to download within the releases after v1.8 so Obtainium cannot update the app beyond this version.

**Comment by DarkCrypt** [comment]
@GhostShadow0316 
There must be something wrong with your config. It shouldn't be saying "31 installed". You can try this config...

Linkora Config:
- GitHub: [GitHub](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.sakethh.linkora%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Fsakethpathike%2FLinkora%22%2C%22author%22%3A%22sakethpathike%22%2C%22name%22%3A%22Linkora%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Afalse%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22useLatestAssetDateAsReleaseDate%5C%22%3Afalse%2C%5C%22releaseTitleAsVersion%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22github%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%2C%22overrideSource%22%3A%22GitHub%22%7D)
- F-Droid: [F-Droid](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.sakethh.linkora%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Fsakethpathike%2FLinkora%22%2C%22author%22%3A%22sakethpathike%22%2C%22name%22%3A%22Linkora%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Afalse%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22useLatestAssetDateAsReleaseDate%5C%22%3Afalse%2C%5C%22releaseTitleAsVersion%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22fdroid%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%2C%22overrideSource%22%3A%22GitHub%22%7D)

**Comment by noto10** [comment]
> @noto10 Not an Obtainium issue.
> 
> Looking at the GitHub releases v1.8 is still v1.7 which is producing your initial conflict. Besides this, there's no apk to download within the releases after v1.8 so Obtainium cannot update the app beyond this version.

I understand this. I'm looking for a workaround in configuring Obtainium to deal with this. Would you have any suggestions?

**Comment by DarkCrypt** [comment]
@noto10 
All you can really do is set the app as track-only and "Mark Updated". This will eliminate the update notification and make Obtainium think the latest version is installed.

**Comment by noto10** [comment]
> @noto10 All you can really do is set the app as track-only and "Mark Updated". This will eliminate the update notification and make Obtainium think the latest version is installed.

That's what I ended up doing. But this only takes away the erroneous reporting of updates. Is there no other way to check for new releases?

**Comment by DarkCrypt** [comment]
@noto10 
The track-only option was implemented to help deal with the issue of no apk. No apk, no release to download. I'm not sure what else you can do besides track it. Otherwise, you could revert to F-Droid for releases as this is the only other official channel.

Another way to eliminate the update notification is to toggle off "Reconcile version string with version detected from OS". Obtainium would then show v1.08 as the installed version.

**Comment by noto10** [comment]
Thanks for the suggestions. Track only seems the best compromise.
