### ISSUE TITLE
Apply background updates only when charging (optional)

### ISSUE THREAD

**Issue by Zocker1999NET** [ImranR98/Obtainium#1914]
**Prerequisites**

**Describe the feature**

Similar to the setting "disable background updates when not on Wi-Fi", I would like to have a setting "disable background updates when not charging", especially because I have Wi-Fi at most places where I am but want my phone to preserve as much battery as possible.

**Describe alternatives you've considered (if applicable)**

I'm not sure if there are viable alternatives. One could setup an external app stopping & starting Obtainium, but this requires either root or an API & has the chance of increasing battery usage overall, while being complicated to setup & maintain.

**Additional context**

My phone often drains way too much battery as part of a de-Googled-experience because too many apps just mind their own business, like apps which do neither support UnifiedPush nor GCM in their non Google Play versions.
After re-discovering Obtainium today, I really like the idea & now use it to avoid non-working app releases being pushed by F-Droid sometimes (some builds of Tailscale just cannot launch due to a misconfigured Go binary build by F-Droid, and somewhat understandably, they do not test every update manually, but Tailscale also pushes their own builds outside Google Play, which they always try to launch every time). So I'm really thankful for this app as it enables me to retain automatic updates for apps without needing to rely on F-Droid.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.28
