### ISSUE TITLE
Obtainium crashes when trying to update Firefox

### ISSUE THREAD

**Issue by kattelk** [ImranR98/Obtainium#192]
Obtainium crashes when trying to update to the latest version of Firefox 108.1.1. It crashes before the apk has finished downloading. Affects both arm versions.

**Comment by ImranR98** [comment]
Hmm. Seems to work for me. Could you also share the file at `/Android/data/dev.imranr.obtainium/files/app_data/org.mozilla.firefox`?

**Comment by kattelk** [comment]
[org.mozilla.firefox.zip](https://github.com/ImranR98/Obtainium/files/10303463/org.mozilla.firefox.zip)

**Comment by kattelk** [comment]
After uninstalling and reinstalling Obtanium, this works as expected again.
