### ISSUE TITLE
opt out to not use explicitly static 

### ISSUE THREAD

**Issue by ay6z** [ImranR98/Obtainium#1922]
https://youtu.be/0R01HDtZtmI , 
![Screenshot_20241021_145625_One UI Home](https://github.com/user-attachments/assets/bb0871fa-664e-4202-8567-e2cf7f03fa7f)
, nobody want help me, Playlist revanced mess lot inappropriate content unlock ,I just remove,kindly help ,act stupid , my apologies,act itself

**Comment by ImranR98** [comment]
wut
