### ISSUE TITLE
APKPure App Source URL with non-English characters stopped working

### ISSUE THREAD

**Issue by qwyop** [ImranR98/Obtainium#1926]
**Prerequisites**
I believe there hasn't been any issues made between the time #1916 was implemented and my bug report that pertain to the issue I'm having

**Describe the bug**
After #1916 was implemented, the App Source URL https://apkpure.com/エイリアンのたまご-放置系バトル育成rpgゲームアプリ/com.paondp.game2.padp.etg stopped working and gave the error "Illegal argument(s): Illegal percent encoding in URI [エリたま]" when opening Obtainium, and while looking at the app gave the same error popup without the brackets

I had to delete the App in Obtainium and re-add it using https://apkpure.com/%E3%82%A8%E3%82%A4%E3%83%AA%E3%82%A2%E3%83%B3%E3%81%AE%E3%81%9F%E3%81%BE%E3%81%94-%E6%94%BE%E7%BD%AE%E7%B3%BB%E3%83%90%E3%83%88%E3%83%AB%E8%82%B2%E6%88%90rpg%E3%82%B2%E3%83%BC%E3%83%A0%E3%82%A2%E3%83%97%E3%83%AA/com.paondp.game2.padp.etg to stop the errors. Trying to add this link while the previous one is still in Obtainium gives the message "App already added"

**To Reproduce**
1. Already have the https://apkpure.com/エイリアンのたまご-放置系バトル育成rpgゲームアプリ/ App Source URL added in Obtainium
2. Get a mobile notification from Obtainium about the error while it checks for updates in the background
3. Open Obtainium and get the same error in a pop up window
4. Check on the problem app's details and once again see the same error

**Screenshots and Logs**
![Screenshot_20241023-015233_Gallery](https://github.com/user-attachments/assets/3e811559-4a4e-42dc-8d75-63c669b799dc)
![Screenshot_20241022-002713_Obtainium](https://github.com/user-attachments/assets/ef1b7a53-befe-41c1-ac23-388a54b8a966)
![Screenshot_20241022-002719_Obtainium](https://github.com/user-attachments/assets/f474e851-8866-4a0a-9a21-dadd8c240695)
![Screenshot_20241022-002853_Obtainium](https://github.com/user-attachments/assets/5adebdf1-6ad9-41a9-ba54-069811a0c13e)

**Please complete the following information:**
 - Device: Samsung Galaxy Note 8
 - OS: One UI 1.0 (Android 9)
 - Obtainium Version: 1.1.28

**Additional context**
I used this link because before #1916 % symbols/characters caused the "Could not find a suitable release" error I had in #1810

**Comment by ImranR98** [comment]
Yes this is definitely due to the change in #1612. Will be fixed in the next release.

**Comment by ImranR98** [comment]
Should work now: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.29
