### ISSUE TITLE
Accrescent?

### ISSUE THREAD

**Issue by Jeffrey2307** [ImranR98/Obtainium#1927]
hey i would love to see the App on Accrescent Store (which is the most secure and private Store and better solution than Github) maybe you can apply there, because it would be the best and better solution and I would love to see you Guys there

**Comment by Hamster45105** [comment]
@Jeffrey2307 if you could please close the discussion as not planned that would be great!

**Comment by Jeffrey2307** [comment]
Of course!

**Comment by DwainZwerg** [comment]
@Hamster45105 @Jeffrey2307 No that isn't the same issue as #1817. Issue 1817 discuss publishing Obtanium on Ascreescent. This issume dicuss using Ascreescent as a Sourcecode in Obtainium

**Comment by Jeffrey2307** [comment]
@DwainZwerg No that is not true. I was asking if Obtainium could be launched in Accrescent.
