### ISSUE TITLE
Remove Signal Source

### ISSUE THREAD

**Issue by Hamster45105** [ImranR98/Obtainium#1928]
**Describe the feature**

Seeing as Signal has now started providing releases with APKs [on their GitHub repo](https://github.com/signalapp/Signal-Android) it would probably be a good idea to remove the Signal source-specific source. I've noticed the APK on the website often gets out of date with the Google Play store, so GitHub seems like a better choice now anyway.

**Additional context**

People who already have the Signal source added would need their configs automatically converted to the HTML/GitHub source.

**Comment by Hamster45105** [comment]
> not everyone wants to retrieve apps from GitHub. Some people may have installed Obtainium just to install apps directly from the vendor website and/or from GitLab and/or from Forgejo (Codeberg). If they were now deprived of this option, they would rightly complain.

Yeah I agree, I don't think it should be converted to the GitHub source, it should be converted to the HTML source with possibly the option to use the GitHub one instead. People using the Signal source right now wouldn't notice a difference - their config should just automatically be converted to the HTML source. For those that want to add it in the future, they would go to the config website, just like all the other apps.

I do not see why Signal (or any other of the app-specific sources for that matter) deserve their own source (unless getting updates via that app is not possible with the HTML source), and with the introduction of GitHub releases it seems like an ideal time to remove it.

> the latest stable version of Signal is (according to the Google Play Store) 7.20.2 (which [signal.org/android/apk](https://signal.org/android/apk/) offers). In the GitHub repo, the oldest version is already 7.21.4 (a beta version), which, however, is not tagged as a pre-release (as well as the latest version isn't tagged as pre-release).

While at the moment the website and Google Play Store are in sync, I often notice that the website version is behind Google Play, meaning most of the time I get updates there before Obtainium.

**Comment by DwainZwerg** [comment]
If there is a working configuration for Signal/WhatsApp/Telegram/VLC that can be retrieved from the same page using the general HTML source, the configuration should always be adapted to simplify the maintainability of the Obtainium source code.

**Comment by Hamster45105** [comment]
Yes [here it is](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22org.thoughtcrime.securesms%22%2C%22url%22%3A%22https%3A%2F%2Fupdates.signal.org%2Fandroid%2Flatest.json%22%2C%22author%22%3A%22updates.signal.org%22%2C%22name%22%3A%22Signal%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22partialAPKHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%5C%5C%5Cd%2B.%5C%5C%5C%5Cd%2B.%5C%5C%5C%5Cd%2B%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%2C%22overrideSource%22%3Anull%7D).

**Comment by Hamster45105** [comment]
Here are some other app-specific sources that could be removed in favour of HTML:

[WhatsApp](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.whatsapp%22%2C%22url%22%3A%22https%3A%2F%2Fwhatsapp.com%2Fandroid%2F%22%2C%22author%22%3A%22whatsapp.com%22%2C%22name%22%3A%22WhatsApp%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Atrue%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22Version%20(%5C%5C%5C%5Cd%2B%5C%5C%5C%5C.%5C%5C%5C%5Cd%2B%5C%5C%5C%5C.%5C%5C%5C%5Cd%2B%5C%5C%5C%5C.%5C%5C%5C%5Cd%2B)%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%241%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3A%22HTML%22%7D)

[VLC](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22org.videolan.vlc%22%2C%22url%22%3A%22https%3A%2F%2Fget.videolan.org%2Fvlc-android%2Flast%2F%22%2C%22author%22%3A%22get.videolan.org%22%2C%22name%22%3A%22VLC%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22arm64-v8a%5C%5C%5C%5C.apk%24%5C%22%2C%5C%22filterByLinkText%5C%22%3Atrue%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22partialAPKHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%5C%5C%5Cd%2B.%5C%5C%5C%5Cd%2B.%5C%5C%5C%5Cd%2B%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3A%22HTML%22%7D)

**Comment by ImranR98** [comment]
@Hamster45105 your VLC source would be less reliable due to #715 - VLC downloads are mirrored, and the mirrors available at any given time can change. The current VLC source automatically picks a mirror link at download time, instead of at update checking time (https://github.com/ImranR98/Obtainium/blob/main/lib/app_sources/vlc.dart#L82). Using your HTML-based config, if a user receives an update notification but does not immediately install it, the link may be expired (mirror may be down) by the time they actually try installing it (if they don't pull to refresh or open the app detail page to grab a newer link).

There is a similar issue for WhatsApp: https://github.com/ImranR98/Obtainium/issues/357#issuecomment-1751770284

Your Signal source looks good though. We can definitely get rid of the dedicated Signal source and automatically switch existing entries to your config.

May as well keep Telegram since it works and we can't get the real version number through the HTML source.

**Comment by Hamster45105** [comment]
Sounds good. Probably for another issue, but would it be possible to add an additional option like`Refresh on download` that would automatically refresh the app when you click the update button?

**Comment by DwainZwerg** [comment]
According to the Google Play Store, the last stable version of Signal at that time was 7.20.2. In the GitHub repos, the oldest version at that time was 7.21.4 (a beta version), which, like the latest version at that time, was not marked as a pre-release version.
