### ISSUE TITLE
F-Droid URL With Language Code Not Working

### ISSUE THREAD

**Issue by Hamster45105** [ImranR98/Obtainium#1933]
**Describe the bug**

When trying to add an F-Droid app with a language code, Obtainium says "Not a valid F-Droid Official App URL". 

**To Reproduce**

Try to add a F-Droid URL with a language code such as `https://f-droid.org/en/packages/eu.faircode.email/` and see the error.

The same thing does not happen to URLs without a language code, such as `https://f-droid.org/packages/eu.faircode.email/`

**Please complete the following information:**
 - Obtainium Version: 1.1.28

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.29
