### ISSUE TITLE
Min and Target SDK

### ISSUE THREAD

**Issue by ghost** [ImranR98/Obtainium#1935]
Hey,

i saw that the App has Target SDK on 34 and Minimum SDK on 24 and I wanted to ask if you could make Target SDK to 35 for Android 15 and Minimum SDK to 26/28/29/31? I would appreciate that! (Higher is always better)

A higher Minimum SDK version implies that your app supports fewer Android versions, minimizing compatibility issues. Because higher SDK means also Versions which are supported better. It makes the work easier. because Android 12 (SDK 31) is the last version that receives security patches. Further more, the less minSdk, the more internal compatibility layers, techniques etc. For example, lower SDK versions require v1/v2 signing, have somewhat different optimization levels, etc.

**Comment by ImranR98** [comment]
Are there specific compatibility concerns you have with SDK 24? It used to be lower until the Shizuku features were added, which apparently required a higher minSDK. I don't see the point of increasing it until we actually have to, especially since it would cause some devices to lose support (there was at least one person for whom even SDK 24 was too high so you never know).

I agree about increasing the target SDK.

**Comment by ImranR98** [comment]
For the target SDK version, I don't set that myself - it depends on the version of Flutter used (manually changing this might cause compatibility issues, idk). Right now, Flutter stable targets SDK 34: https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L56

Closing this issue. The target SDK will be moved up naturally at some point when there is a Flutter update.

**Comment by Korb** [comment]
Currently, when trying to launch `Obtainium 1.2.1` (2025-07-25) from `IzzyOnDroid`, the following notification appears:

> This app isn't compatible with the latest version of Android. Check for an update or contact the app's developer.

Target SDK 35 (Android 15)
Min SDK 24 (Nougat)

---
Model: Vivo T1 (4G) / V2153
OS version: Funtouch OS 14 (Android 14)
Hardware version: MP_0.1
Build number: PD22010F_EX_A_14.2.14.0.W20
Baseband version: .HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.10 7
Kernel version: 4.19.157-perf+. 1 Thu May 8 10:36:27 CST 2025
Compile time: 8 May 2025 05:31:38
Android security update: 1 May 2025
Google Play system update: 1 April 2025
Software parameter update: 14 March 2025
