### ISSUE TITLE
[HTML Source] subdomain.domain.tld urls are not parsed properly

### ISSUE THREAD

**Issue by 0x33taji** [ImranR98/Obtainium#1937]
### Discussed in https://github.com/ImranR98/Obtainium/discussions/1936

`subdomain.domain.tld` urls are **not** parsed properly.
`subdomain.domain.tld/path` urls are parsed properly.

**Comment by ImranR98** [comment]
What is the `href` value of the links on your page?

**Comment by 0x33taji** [comment]
The href entries in the HTML are like this:
```html
<li><a href="com.brave.browser_1.71.118.apk">com.brave.browser_1.71.118.apk</a></li>
```

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.29
