### ISSUE TITLE
Export obtainium settings don't work

### ISSUE THREAD

**Issue by summoner001** [ImranR98/Obtainium#194]
My device: Android 9
Obtainium version: 0.9.7-beta
Obtainium storage permission: Enabled

When I click the export button nothing happens.

Don't export datas. Or I can't find them on my device folders?

**Comment by ImranR98** [comment]
Should work now: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.10-beta

**Comment by summoner001** [comment]
> Should work now: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.10-beta

Yes! Its work for now. Thank you very much! Happy xmas!
