### ISSUE TITLE
Add Option To Recheck APK URL On Update

### ISSUE THREAD

**Issue by Hamster45105** [ImranR98/Obtainium#1943]
**Describe the feature**

An option for the HTML source like `Refresh on download` that would automatically refresh the app to get the latest URL when you click the update button. 

**Describe alternatives you've considered (if applicable)**

None. 

**Additional context**

Multiple apps such as VLC and WhatsApp seem to have the problem of using mirrors/constantly updating downloading links so this would fix that problem. If this was implemented, almost every app-specific source would be able to be removed in favour of HTML.

**Comment by ImranR98** [comment]
Done: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.33

VLC and WhatsApp were removed with auto-migration for existing installs.
Telegram app was also removed (unrelated to the change in this issue, could have been done earlier).
There's only one app-specific source remaining, which can't be covered by the HTML source.
