### ISSUE TITLE
Could not find suitable release for VLC

### ISSUE THREAD

**Issue by Topkack** [ImranR98/Obtainium#1946]
**Prerequisites**
Obtainium on Android

**To Reproduce**
Add app
Search for VLC
Pick the offering by videolan
Add app

**Comment by Hamster45105** [comment]
I assume you are trying to use the GitHub repo, which does not provide releases (https://github.com/videolan/vlc). VLC is it's own source which you can add by inputting https://videolan.org or you can get it from [F-Droid](https://f-droid.org/en/packages/org.videolan.vlc)
