### ISSUE TITLE
[Permission] Can i use the code to make the best "app market" app out there, possibly?

### ISSUE THREAD

**Issue by Tanzin01** [ImranR98/Obtainium#1949]
Hello , sup

Lets tour to a background story: Due to reasons,   there is a  urge to run an app store/market or app web (market).

So, quite some time passed but almost zero progress made. (Looked into aurora store, i guess im just pure unmotivated with it at the same time)

Recently, probably this week, i found this app. Which matches some of the different core goal i have which is not available in aurora.

**So, May i be permitted to use this app  to possibly, create and run the biggest app store out there?**
 Who knows i might become a zillionare with the  "to be created app store"! Insha Allah.

Yes, i did notice the gpl 3 license but still i see the need to ask for permission from the owner.

Important  additinal info-
** at core, my visioned app will just be a simple middle man. App developer gives their app link, my app featches them to ordinary user in a ordinary manner(user interface). And yes, fdroid will be scraped too. Kind of like your app(obtianium) but it  may shall try to give the vibe of a vibrant , simple app store/app web market or whatever.

*** at some point, the to be, hopefully , will be created app will add money earning stuff which you probably can assume from my zillionare statement.

Ohh btw i shall be fair and equal to everyone.
To express this elaborately a bit, the to be created app shall facilitate the uploading of modded / virus app. Wait, dont get the wrong assumption, im not a bad man neither will i ever try, Insha Allah. Of course , there be a slight filtering. 
Anyway, everyone needs a place and a considarate filtering shall make everyone happy.
[Btw i may add  two mode, filtered and wild for ordinary and unordinary people to use the to be hopefully created app store.]

**Comment by ImranR98** [comment]
Sure, it's open source so anyone can fork it. Keep in mind the GPL license is copyleft, meaning anything you make with Obtianium's code will also have to be open source and use the same license. Changing the license would need agreement by all contributors.

**Comment by DarkCrypt** [comment]
Why would people use your app instead of [Appteka](https://github.com/solkin/appteka-android) where anyone can upload/download apps (original, modded, etc.)?
