### ISSUE TITLE
Show no of apps selected 

### ISSUE THREAD

**Issue by eloffmarijan** [ImranR98/Obtainium#195]
Add how many apps are selected in apps section, like 1 apps selected.

**Comment by ImranR98** [comment]
Tried this, but it causes issues due to space constraints on smaller screens. It can probably be done conditionally depending on screen size, so I'll leave the issue open but it is not a high priority. In the meantime, you can long-press the select button to see the selection count.

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.9-beta

**Comment by eloffmarijan** [comment]
Thanks dev bro.
