### ISSUE TITLE
Some app icons are not displayed

### ISSUE THREAD

**Issue by Chungaa** [ImranR98/Obtainium#1950]
Some app icons are not displayed.
For example, if you add a Github repo and then click on apply, the icon symbol of the app is not displayed.

Here are a few examples:
https://github.com/bttv-android/bttv
https://github.com/fgl27/smarttv-twitch
https://github.com/Kunzisoft/KeePassDX/releases

**Comment by ImranR98** [comment]
Is this before or after installing the app? If it's before then that's expected since icons are taken from the OS (for installed apps).

**Comment by ImranR98** [comment]
Closing - expected behaviour (and there is an existing issue to change that).
