### ISSUE TITLE
Cannot download apk from Github page/Obtainium doesn't recognize installed application

### ISSUE THREAD

**Issue by Arhont713** [ImranR98/Obtainium#1953]
Can't download or update installed application from this page https://github.com/NoName-exe/revanced-extended/releases (or this https://github.com/NoName-exe/revanced-extended)
Selected apk (red square on screenshot) cannot be installed but the rest are installed and downloaded without any problems. So, I've got this message (Screenshot 2).
If I install that app not with Obtainium, it identifies that application as not installed.

![Screenshot_1](https://github.com/user-attachments/assets/862bd111-e154-4b6a-ba5c-be61345a813c)
![photo_2024-11-07_16-21-09](https://github.com/user-attachments/assets/b3264c29-1c08-47a2-8b11-e9cd423f642f)

**Comment by DarkCrypt** [comment]
I cannot reproduce, Obtainium was able to install both apps without issue.

YouTube (all):
- URL: `https://github.com/NoName-exe/revanced-extended`
- Override Source: `GitHub`
- Filter APKs by Regular Expression: `all`

YouTube Music:
- URL: `https://github.com/NoName-exe/revanced-extended`
- Override Source: `GitHub`
- Filter APKs by Regular Expression: No filter or `v8a` or `v7a`

**Comment by Arhont713** [comment]
> I cannot reproduce, Obtainium was able to install both apps without issue.
> 
> YouTube (all):
> 
> * URL: `https://github.com/NoName-exe/revanced-extended`
> * Override Source: `GitHub`
> * Filter APKs by Regular Expression: `all`
> 
> YouTube Music:
> 
> * URL: `https://github.com/NoName-exe/revanced-extended`
> * Override Source: `GitHub`
> * Filter APKs by Regular Expression: No filter or `v8a` or `v7a`

Oh, thanks, my bad. "Filter APKs by Regular Expression: all" fixed that, thanks!

**Comment by kvmgithub** [comment]
Seems not to be working with ente auth and ente photos and ente auth. https://github.com/ente-io/ente/releases

**Comment by kvmgithub** [comment]
Seems not to be working with ente auth and ente photos.
https://github.com/ente-io/ente/releases

**Comment by DarkCrypt** [comment]
@kvmgithub 
Working without issue. You just need to add a filter which you can do 2 different ways.

Ente Auth:
- Filter Release Titles by Regular Expression: `auth`
Or
- Filter APKs by Regular Expression: `auth`

Ente Photos:
- Same as above but use `photos`

**Comment by kvmgithub** [comment]
@DarkCrypt 
I tried both ways. It always says app already added.

**Comment by DarkCrypt** [comment]
@kvmgithub 
Obtainium will tell you if the app is already added as you just found out, haha. You still need to add a filter to retrieve updates properly from this particular repo. Did you get this resolved?

**Comment by kvmgithub** [comment]
@DarkCrypt 
I realized I'd rather stick to Keepass for OTPs, so I removed ente auth. ¯\_(ツ)_/¯
