### ISSUE TITLE
SHA-256 fingerprint

### ISSUE THREAD

**Issue by skarpinis** [ImranR98/Obtainium#1957]
Where I can find SHA-256 fingerprint to verify obtainium itself?

**Comment by ImranR98** [comment]
That's a good point - I don't think I've actually published that info anywhere. AppVerifier does have Obtainium's signature hash stored in its internal database though, so you can use that as your source for now. I'll publish that somewhere soon.

**Comment by skarpinis** [comment]
great thank you

**Comment by ImranR98** [comment]
Added to the README and the website.

**Comment by DarkCrypt** [comment]
Also, apps like [AppManager](https://github.com/MuntashirAkon/AppManager) or [PackageManager](https://github.com/SmartPack/PackageManager) displays this info and more.
