### ISSUE TITLE
Merry Christmas! 🎄 and Thanks! 

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#196]
I know, I know, another issue open… 😋 

But this is a thanks for all your hard work on this app this year. 
It's cool to see how far it's come. I can't wait to share it more once it's out of beta.
Thanks and well done @Imran98

**Comment by ImranR98** [comment]
Thanks, I appreciate your help with testing and giving feedback on various issues too. As for going out of beta, I was hoping to get background/silent installs to work first but that's starting to look unrealistic. We'll see.

Merry Christmas!
