### ISSUE TITLE
Obtainium will often fail to install the correct version of Fennec on F-Droid

### ISSUE THREAD

**Issue by Candelus** [ImranR98/Obtainium#1961]
**Describe the bug**
I [found](https://www.reddit.com/r/fossdroid/comments/1gkvdoo/anyway_to_updateuse_fennec_without_fdroid_most/) out that you can use Obtainium to update Fennec on F-Droid, however, someone commented this

![image](https://github.com/user-attachments/assets/ecb33f44-95d0-4b40-82f6-abbeefb6f3ce)

I am unsure of how to check if an android app is 32bit or 64bit so I am unable to "reproduce" and determine if it is a problem at all. The person who commented claimed to be a [maintainer](https://www.reddit.com/r/degoogle/comments/1gmecim/comment/lw2svjv/) of Mull and Fennec so there should be credibility to that.

**Please complete the following information:**
 - Device: Pixel 8 Pro
 - OS: Google's Pixel 8 Pro Android 15
 - Obtainium Version: 1.1.29

**Additional context**
I'm not sure about this but would adding a feature that allow you to set which version to download and install from F-Droid/Github work if this is a problem at all? Because I can select the armv8 version and Obtainium will remember the choice everytime there's an update, right?

**Comment by DarkCrypt** [comment]
I doubt this as an issue and I disagree with the "maintainer".

Fennec has 2 releases on F-Droid as stated: 
- arm64-v8a (64/32bit)
- armeabi-v7a (32bit)

We can also see 2 different version codes:
- arm64-v8a (1320020)
- armeabi-v7a (1320000)

Looking through the previous releases we can see a pattern which the arm64-v8a version code is always higher than the armeabi-v7a version code.

Obtainium already has a filter in place to handle this:
- Auto-select highest versionCode APK: `Toggle ON`

*F-Droid and GitHub work differently with Obtainium but both have filters to retrieve the apk you want.

**Comment by ImranR98** [comment]
Yeah, I don't think we can do better than relying on the version code since the F-Droid API doesn't give us architecture info. For example: https://f-droid.org/api/v1/packages/net.sourceforge.opencamera

You could try the "use suggested version" toggle but I'm not sure how F-Droid decides which one to suggest.

**Comment by Candelus** [comment]
> Looking through the previous releases we can see a pattern which the arm64-v8a version code is always higher than the armeabi-v7a version code.
> 
> Obtainium already has a filter in place to handle this:
> 
>     * Auto-select highest versionCode APK: `Toggle ON`
> 
> 
> *F-Droid and GitHub work differently with Obtainium but both have filters to retrieve the apk you want.

That's great to know, I've toggle it on. How would I do the same for Github? Apologies if I'm asking the obvious but I've only begun to explore these things.


> Yeah, I don't think we can do better than relying on the version code since the F-Droid API doesn't give us architecture info. For example: https://f-droid.org/api/v1/packages/net.sourceforge.opencamera
> 
> You could try the "use suggested version" toggle but I'm not sure how F-Droid decides which one to suggest.

I think the highest version code APK toggle is good enough, couldn't thank you enough for making this app :)

**Comment by ImranR98** [comment]
> How would I do the same for Github?

Depends on the app - there is no consistent release system for apps on GitHub. Most of the time the architecture info and Obtainium will automatically filter for you.

**Comment by Candelus** [comment]
> > How would I do the same for Github?
> 
> Depends on the app - there is no consistent release system for apps on GitHub. Most of the time the architecture info and Obtainium will automatically filter for you.

I figured as much. Thanks for the clarification and quick to answer!
