### ISSUE TITLE
Ability to download & manage multiple apk files on same repository

### ISSUE THREAD

**Issue by RoonMoonlight** [ImranR98/Obtainium#1963]
**Prerequisites**

Ok

**Describe the feature**

Currently, only one APK at a time are supported. However, some repository's release have two types of apk ([NoName-Exe's RVX releases](https://github.com/NoName-exe/revanced-extended/releases), for example.), and currently Obtainium can only track one APK files' update at the same time.

With the option to have multiple apks in same repositories, it will allow people to manage two or more apk apps in the same repositories without issue.

**Describe alternatives you've considered (if applicable)**

None.

**Additional context**

None.

**Comment by DarkCrypt** [comment]
Duplicate of #1953.

This is already possible. You can update both apps from the same GitHub release page by using a simple filter. I've explained how to do so in the linked thread.

**Comment by RoonMoonlight** [comment]
Oh wow, I couldn't find any similar issue and finally found one, thanks! I will close the issue for now.
