### ISSUE TITLE
Can not install any apps,I suspect it might be an issue with the operating system.

### ISSUE THREAD

**Issue by warglaive6046** [ImranR98/Obtainium#1970]
**Describe the bug**
I am unable to install any apps, including updates for Obtanium itself. It completes the download process, but cannot invoke the system's own installer.

**To Reproduce**
1. Go to any app details page
2. Click the update button or install button
3. The download process ran perfectly. 
4. There is no sign of installation taking place; the download button has changed to the install button.

**Screenshots and Logs**
![Screenshot_2024-11-13-11-45-52-204_dev imranr obtainium](https://github.com/user-attachments/assets/3ba56236-abe5-4b6a-9d58-c81138af2f7a)

**Please complete the following information:**
 - Device: RedMi K70U
 - OS: hyperOS 1.0.27.0UNNCNXM(base on  Android 14)
 - Obtainium Version: 1.1.30(2024-11-10)
 - Packageinstaller: com.miui.packageinstaller 5.2.8.0.0-20240913

**Comment by Duke486** [comment]
Same problem, the os is Xiaomi Hyper OS 1.0.13 Android14

**Comment by ImranR98** [comment]
MIUI is known to cause problems by "optimizing" Android APIs. Could you try and see if disabling optimizations fixes the issue? See here: https://github.com/ImranR98/Obtainium/issues/583#issuecomment-1763106004
