### ISSUE TITLE
Initially collapsed category groups option

### ISSUE THREAD

**Issue by Sagitee** [ImranR98/Obtainium#1981]
**Prerequisites**

**Describe the feature**

Hi and thank you for this great app.

I would like to suggest an additional "Collapsed by default" sub-option to the existent "Group by category" settings option.

Now, the category groups are initially expanded (and additionally even if one manually collapses them one by one, they tend to "arbitrarily" re-expand (issue #1789)), which is an issue in case that there is a large number of apps and groups.

![1_Obtainium](https://github.com/user-attachments/assets/5d4256e1-3999-4dc4-8d43-4989cbf672c0)

**Describe alternatives you've considered (if applicable)**

**Additional context**

**Comment by ImranR98** [comment]
I think #1729 would make this redundant.
