### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by PrivacyAndSecurity** [ImranR98/Obtainium#1986]
Hey,

i noticed a mini Translation thing in the Settings. It says: "Pure Black Dark Theme verwenden" could you change that to: "Rein schwarzen Hintergrund verwenden" ? Because that would be more accurate German Translation. Otherwise it is mixed. I would appreciate that a lot!

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.32
