### ISSUE TITLE
Time to refresh

### ISSUE THREAD

**Issue by PrivacyAndSecurity** [ImranR98/Obtainium#1987]
Hey,

it bothers me a bit that this warning comes that I only can refresh after 29 Minutes. Could you remove that totally? Or would it make more load on the Servers?

**Comment by DarkCrypt** [comment]
You can eliminate GitHub's rate limit by using a Personal Access Token.

**Comment by DarkCrypt** [comment]
It's not hard to do but the choice is yours friend.

**Comment by DwainZwerg** [comment]
Here is a short guide: https://github.com/user-attachments/assets/4769c5da-a8dd-4cd9-824d-60989b58930e
