### ISSUE TITLE
Can't download apps

### ISSUE THREAD

**Issue by Potatovibin** [ImranR98/Obtainium#1988]
**Please complete the following information:**
 - Device: Huawei Y9s
 - OS: EMUI 9
 - Obtainium Version: 1.1.31 (Droid-ify)
 
 When i open the app there is no apps to download or to update 

![Screenshot_20241123_125516_dev imranr obtainium fdroid](https://github.com/user-attachments/assets/984ed5a2-3b50-4b33-bc3f-a96f3d3303b0)

**Comment by ImranR98** [comment]
You need to add the apps yourself. Please refer to the Wiki for more info: https://wiki.obtainium.imranr.dev/
