### ISSUE TITLE
Add import link from sharing menu

### ISSUE THREAD

**Issue by NripPrajapat** [ImranR98/Obtainium#1991]
Whenever I copy a link, it should simply provide an option to add it to Obtainium,
In clipboard strip or Sharing menu.

**Comment by DarkCrypt** [comment]
Duplicate of #109.

**Comment by NripPrajapat** [comment]
It is simply the best and simpler way to add a link and save a user's time, why won't you add this?
It'll save time, don't you think it will?

**Comment by ImranR98** [comment]
@NripPrajapat yes, there is already an open issue for this
