### ISSUE TITLE
Selected Apps Disappear/Won't Re-Add on Retroid Pocket 5

### ISSUE THREAD

**Issue by biomagnet** [ImranR98/Obtainium#1993]
**Describe the bug**
When installing Obtainium on the new [Retroid Pocket 5](https://www.goretroid.com/collections/frontpage/products/retroid-pocket-5-handheld) (Android 13 on SD865 chip), Obtainium functions as intended during the first boot. You may add as many apps as you'd like, but once you close the app and attempt to re-enter, all apps are gone, including the original Obtainium setting and only an error appears when trying to re-add them.

**To Reproduce**
1. Install Obtainium
2. Add any apps desired
3. Update/install if wished
4. Close app entirely
5. Re-enter app
6. All apps are gone, and new ones cannot be added

**Screenshots and Logs**
![image](https://github.com/user-attachments/assets/c1faed0b-622c-414d-982e-44202e4671db)
![image](https://github.com/user-attachments/assets/c7e37ccd-cd25-4f0a-b511-73576e31c519)

**Please complete the following information:**
 - Device: [Retroid Pocket 5](https://www.goretroid.com/collections/frontpage/products/retroid-pocket-5-handheld)
 - OS: Android 13
 - Obtainium Version: Tried as recently as [1.1.32](https://github.com/ImranR98/Obtainium/releases/tag/v1.1.32).

**Additional context**
Seems to be a consistent problem in the Retroid discord for those trying to set up automatic app updates. Retroid has also been contacted about the issue by another user, but I wanted to have it known here as well to pincer attack the problem.

**Comment by ImranR98** [comment]
Looks like a permission issue - Obtainium can't open its cache folder. But afaik, Android doesn't have permissions for that - apps are always allowed to access their own cache folders. Seems like an OS issue. Do you have the same issue with other apps that use the cache folder?

**Comment by ImranR98** [comment]
I know this is blasphemy in some circles but maybe you could test with TikTok - it seems to store a lot of files in the cache dir.

**Comment by biomagnet** [comment]
Ha! I'm about to head to work, but I'll report back tonight once I can (gasp) try installing TikTok to see if it runs into similar issues with the cache folder. Thanks for the response!

**Comment by GlazedBelmont** [comment]
Issue is fixed with the R1.0.0.51 firmware update for the RP5
