### ISSUE TITLE
VLC is stuck on 3.5.4

### ISSUE THREAD

**Issue by ngrigoriev** [ImranR98/Obtainium#1994]
**Prerequisites**
There were some issues in the past reported for VLC source, but this one seems to be ongoing.

**Describe the bug**
Added source repo https://get.videolan.org/vlc-android/ with "Override source" set to "VLC". Obtanium detects the version 3.5.4 only while there is version 3.5.7 there. And 3.5.7 is on GP too.

**To Reproduce**
1. Click Add
2. Enter https://get.videolan.org/vlc-android/ as Source URL
3. Select VLC as "Override Source"
4. Observe the version 3.5.4 detected as latest. 

**Please complete the following information:**
 - Device: Pixel 7 Pro
 - OS: GrapheneOS
 - Obtainium Version: 1.1.32

**Comment by ngrigoriev** [comment]
Took a while to get an account there but finally: https://code.videolan.org/videolan/vlc/-/issues/28900

**Comment by ImranR98** [comment]
> There must be a reason why a dedicated source called "VLC" was introduced...

The current VLC configuration that uses the HTML source is functionally identical to the previous dedicated VLC source. Your issue was about the old source anyways, but the problem is still there. They need to update the version on their site - this isn't something that Obtainium can fix.

**Comment by ngrigoriev** [comment]
@ImranR98 Yes, and this is what I have identified.  I was wondering why the "generic" HTML-based source won't work for VLC.

**Comment by ngrigoriev** [comment]
@dsh2dsh

That configuration installs only a specific release. And I am not sure why does videolan.org put their artifacts in two different places...I assume that the "right" place is the one referred from their web page (outdated now).

**Comment by ngrigoriev** [comment]
```
   "apkUrls": "[[\"1044570241-VLC-Android-3.5.7-arm64-v8a.apk\",\"https://artifacts.videolan.org/vlc-android/release/VLC-Android-3.5.7-arm64-v8a.apk\"]]",
```
Oh, I see, this must be a "dump" of the current state, not just the configuration?

**Comment by dsh2dsh** [comment]
> this must be a "dump" of the current state, not just the configuration?

Correct.

**Comment by ngrigoriev** [comment]
That vlc.json does not work for me out of the box. I have cleaned the cache and ensured no VLC is installed. It seems it downloads the corrupted APK. When sharing it with AppVerifier, I get "APK FAILED TO PARSE".

**Comment by dsh2dsh** [comment]
> That vlc.json does not work for me out of the box. I have cleaned the cache and ensured no VLC is installed. It seems it downloads the corrupted APK. When sharing it with AppVerifier, I get "APK FAILED TO PARSE".

Sorry about that. I don't know why. I just exported it from my obtainium.

**Comment by ngrigoriev** [comment]
The APK files for the same version are different in:

https://get.videolan.org/vlc-android/3.5.7/
and
https://artifacts.videolan.org/vlc-android/release/

Size is different by 131091 bytes. The first repo provides at least sha256 checksum to validate the file...

**Comment by ngrigoriev** [comment]
Finally, with the last update to Obtanium (thanks!) I was able to get what I needed from the right source:

```
        {
            "id": "org.videolan.vlc",
            "url": "https://get.videolan.org/vlc-android/",
            "author": "get.videolan.org",
            "name": "VLC",
            "installedVersion": "3.5.7",
            "latestVersion": "3.5.7",
            "apkUrls": "[[\"223076381-VLC-Android-3.5.7-arm64-v8a.apk\",\"https://get.videolan.org/vlc-android/3.5.7/VLC-Android-3.5.7-arm64-v8a.apk\"]]",
            "otherAssetUrls": "[]",
            "preferredApkIndex": 0,
            "additionalSettings": "{\"intermediateLink\":[{\"customLinkFilterRegex\":\"([0-9.]+)/$\",\"filterByLinkText\":false,\"skipSort\":false,\"reverseSort\":false,\"sortByLastLinkSegment\":false}],\"customLinkFilterRegex\":\"VLC-Android-[0-9.]+-arm64-v8a.apk$\",\"filterByLinkText\":false,\"skipSort\":false,\"reverseSort\":false,\"sortByLastLinkSegment\":false,\"versionExtractWholePage\":false,\"requestHeader\":[{\"requestHeader\":\"User-Agent: Wget/1.13.2 (linux-gnu)\"}],\"defaultPseudoVersioningMethod\":\"partialAPKHash\",\"trackOnly\":false,\"versionExtractionRegEx\":\"VLC-Android-([0-9.]+)-arm64-v8a.apk$\",\"matchGroupToUse\":\"$1\",\"versionDetection\":true,\"useVersionCodeAsOSVersion\":false,\"apkFilterRegEx\":\"\",\"invertAPKFilter\":false,\"autoApkFilterByArch\":true,\"appName\":\"\",\"shizukuPretendToBeGooglePlay\":false,\"allowInsecure\":false,\"exemptFromBackgroundUpdates\":false,\"skipUpdateNotifications\":false,\"about\":\"\",\"refreshBeforeDownload\":false}",
            "lastUpdateCheck": 1734026000510286,
            "pinned": false,
            "categories": [],
            "releaseDate": null,
            "changeLog": null,
            "overrideSource": "HTML",
            "allowIdChange": false
        }
```

Maybe I should get some regexes a bit stricter but this works. And the trick seems to use the user agent string that does not belong to a known browser. Otherwise the site displays an intermediate Web page.

**Comment by hr0dv1tn1r** [comment]
1. You can use the https://apps.obtainium.imranr.dev/ website, it's an official APK Search fork Obtainium. 
2. Click on the "Add to Obtainium" and after that edit the App intermediate link from "^[0-9]\" to "/last".
3. Install, it will work.

Obs: The alert from source "https://espejito.fder.edu.uy/videolan/vlc-android/..." it's okay, this is the link from download from the website "https://get.videolan.org/vlc-android/last/...". Unless the website it's already hacked and the link itś false, it will be fine.
