### ISSUE TITLE
Installing assets fails with PathNotFoundException

### ISSUE THREAD

**Issue by wookey** [ImranR98/Obtainium#1998]
I have just installed Obtainium and configured it to download a couple of apps. One common one (Signal) from the croudsourced configs found at https://apps.obtainium.imranr.dev/, and one obscure one (Topodroidx) found here: http://marcocorvi.altervista.org/caving/speleoapps/speleoapks/TopoDroidApks.html

**To Reproduce**
In both cases if I click on the app inthe 'Apps' list, it finds an update, and I click on 'Download release asset', whih takes me to a 'select release asset' radio button dialog where one can pick the desired architecture (for Signal, there is no choice for Topodroid). Clicking on 'continue' there gives a 'Some Errors Occurred' dialog, giving a 'PathNotFoundException'.

The two respective paths reported are:
Cannot open file, path = 'storage/emulated/0/Download/http://marcocorvi.altervista.org/caving/speleoapps/speleoapks/topodroid_apk/TopoDroidX-6.3.6-35.apk.part'(OS Error:No such file or directory, errno = 2) [http://marcocorvi.altervista.org/caving/speleoapps/speleoapks/topodroid_apk/TopoDroidX-6.3.6-35.apk]

Cannot open file, path = 'storage/emulated/0/Download/http://updates.signal.org/android/Signal-Android-website-prod-universal-release-7.26.1.apk.part' (OS Error:No such file or directory, errno = 2) [http://updates.signal.org/android/Signal-Android-website-prod-universal-release-7.26.1.apk]

So it looks an awful lot like obtainium is forgetting to just strip the .apk filename off the end and save that inside the Downloads folder, but is trying to save the file as the whole URL, which is tricky because the URL contains // which makes for a (probably) invalid path, and the subdirectories don't exist.

This seems quite a fundamental problem, but it presumably works for other people. 

 - Device: Nexus 5G
 - OS: LineageOS 18.1
 - Obtainium Version: 1.1.32

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.33

**Comment by wookey** [comment]
> > In both cases if I click on the app inthe 'Apps' list, it finds an update, and I click on 'Download release asset', which takes me to a 'select release asset' radio button dialog where one can pick the desired architecture (for Signal, there is no choice for Topodroid).
> 
> Is there actually a reason why you don't just click on 'Update'? 

No. I never saw the 'update' button down the bottom of the screen till now (because you mentioned it). I had never used the app before and just found the 'download release asset' link first. 

I guess it's because that link seems obviously associated with the particular app on-screen. The update button down the bottom seems more separate to me and part of the general UI. 

> The 'download release asset' is meant to download any file (including the compressed source code or the SHA key) that comes with the release (the only file that is on [this page](https://updates.signal.org/android/latest.json) is the current stable apk). The button should of course still work.

OK. That explains why everyone wasn't complaining that the app was completely broken :-)

Thanks for the fix (and the advice to use the update button, which does indeed work a lot better :-)
