### ISSUE TITLE
Can't add AnonAddy GitLab repository

### ISSUE THREAD

**Issue by muznyo** [ImranR98/Obtainium#2]
https://gitlab.com/Stjin/anonaddy-android

**Comment by ImranR98** [comment]
Looks like Anondaddy doesn't provide binaries on their GitLab releases page. You could open an issue there and ask them to release APKs there.

**Comment by Stjin** [comment]
I always include a direct permalink to a pre-built binary to my releases (instead of a copy of the binary).

Is it possible to somehow add support for that? Or should I just attach binaries manually as well?

**Comment by ImranR98** [comment]
The gitlab releases page content is loaded in with javascript, and i'm not sure how to get info from it (just grabbing and parsing the html) doesn't work, so Obtainium can only get the info included in the [tags RSS feed](https://gitlab.com/Stjin/anonaddy-android/-/tags?format=atom) from Gitlab, and your permalink is not included. When you attach binaries directly, links to those are included in the RSS, for example https://gitlab.com/AuroraOSS/AuroraStore/-/tags?format=atom.
