### ISSUE TITLE
Obtainium Badge is missing its margin

### ISSUE THREAD

**Issue by PrOF-kk** [ImranR98/Obtainium#2003]
**Describe the bug**
The [Obtainium badge](https://github.com/ImranR98/Obtainium/blob/main/assets/graphics/badge_obtainium.png), unlike [other similar badges](https://github.com/ImranR98/Obtainium/blob/main/README.md?plain=1#L53-L61), is missing some transparent margin, which makes it look weird next to the others

<img src="https://raw.githubusercontent.com/ImranR98/Obtainium/refs/heads/main/assets/graphics/badge_obtainium.png"
    alt="Get it on Obtainium"
    height="80">
<img src="https://raw.githubusercontent.com/NeoApplications/Neo-Backup/034b226cea5c1b30eb4f6a6f313e4dadcbb0ece4/badge_github.png"
    alt="Get it on GitHub"
    height="80">
<img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png"
     alt="Get it on IzzyOnDroid"
     height="80">
<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">

**Comment by PrOF-kk** [comment]
Unfortunately the left and right margins don't align anyway and the clickable area is smaller compared to the others.

<img src="https://raw.githubusercontent.com/ImranR98/Obtainium/refs/heads/main/assets/graphics/badge_obtainium.png"
    alt="Get it on Obtainium"
    height="54">
<img src="https://raw.githubusercontent.com/NeoApplications/Neo-Backup/034b226cea5c1b30eb4f6a6f313e4dadcbb0ece4/badge_github.png"
    alt="Get it on GitHub"
    height="80">
<img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png"
     alt="Get it on IzzyOnDroid"
     height="80">
<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">

**Comment by ImranR98** [comment]
Added an alt image w/ padding consistent with the other badges: https://github.com/ImranR98/apps.obtainium.imranr.dev/blob/main/README.md

<img src="https://github.com/user-attachments/assets/713d71c5-3dec-4ec4-a3f2-8d28d025a9c6"
    alt="Get it on Obtainium"
    height="80">
<img src="https://raw.githubusercontent.com/NeoApplications/Neo-Backup/034b226cea5c1b30eb4f6a6f313e4dadcbb0ece4/badge_github.png"
    alt="Get it on GitHub"
    height="80">
<img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png"
     alt="Get it on IzzyOnDroid"
     height="80">
<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">

**Comment by PrOF-kk** [comment]
Thanks!
