### ISSUE TITLE
Let the user set apk / release asset download folder for app updates

### ISSUE THREAD

**Issue by bagarwa** [ImranR98/Obtainium#2006]
### Prerequisites
Searched "apk location" and no posts for this feature. 
Checked the wiki. 

### Describe the feature
Let me set a "Download location" in the app settings, so that whenever Obtainium downloads any apps' update, the apk would get downloaded to that user selected folder, instead of Obtainium's own private folder inaccessible to the user. 

This way, the user will always have access to the downloaded apk, and then can manually reinstall that app if needed. 

### Describe alternatives you've considered (if applicable)
I know the app currently has a "download release asset", which can download the apk to user accessible folder. But that's wasting bandwidth / storage, imo. For example - 

1. Say Iconify has an update. I tap update button. 
2. Obtainium downloads the apk to own private folder, runs it and updates Iconify.
3. But I want the apk. So, I tap "download release asset". 
4. Obtainium again downloads the apk, this time to Downloads folder.

So, it downloads the apk twice and now the same apk is stored in two different places, one accessible to user, one inaccessible. 

Instead, if my feature request is implemented, this would happen - 
1. Say Iconify has an update. I tap update button. 
2. Obtainium downloads the apk to Downloads folder, runs it and updates Iconify.
3. User has access to the apk.

**Comment by ImranR98** [comment]
You should already have read access to Obtainium's cache folder through the OS file manager: `/Android/data/dev.imranr.obtainium/cache`

**Comment by bagarwa** [comment]
> You should already have read access to Obtainium's cache folder through the OS file manager: `/Android/data/dev.imranr.obtainium/cache`

I have Pixel 9 Pro XL, running Android 15.
 
Under /Android/data, I see only 6 apps' folders - `Aftership`, `Audible`, `Maps`, `Timehop`, `FM Player`, `Solid Explorer`. None of the other tens of apps' folders are visible to me here. I'm using Solid Explorer as my file manager and it has been granted the "all files access" permission, as well as root permission. I think it has something to do with Scoped Storage that prevents other apps from seeing content of /Android/data.

**Comment by ImranR98** [comment]
The fact that you see apps' real names tells me the file explorer is doing it's own thing instead of just being a file explorer - you should be seeing the actual app package IDs. Could you use the explorer that came with the phone?

**Comment by ImranR98** [comment]
I think this has been requested in previous issues - using an external directory as a cache dir is not practical since it (A) requires extra permissions that would need to manually be granted (could cause issues if the permission is lost etc.) and because (B) Android's "clear cache" function would no longer work as intended.

**Comment by bagarwa** [comment]
> The fact that you see apps' real names tells me the file explorer is doing it's own thing instead of just being a file explorer - you should be seeing the actual app package IDs. Could you use the explorer that came with the phone?

No, I'm not seeing the apps' real names. I didn't want to copy paste the package names of 6 apps one by one, so I typed the app names. Here's how it looks - 
![Data](https://github.com/user-attachments/assets/766a471a-8d3f-4c87-abd5-8204b6ff53af)

Anyway, thanks for responding.

**Comment by ImranR98** [comment]
Ah, got it. Either way, the folder is definitely there - your file explorer isn't showing it.

**Comment by DwainZwerg** [comment]
This is due to Android Scope Storage. Normal file managers cannot display the contents of the path at all. Good ones (and the system file manager) can now only display the data of the last six apps used. On some devices, the unrestricted Total Commander (from the website and not from the Google Play Store) and the MiXplorer (available from the developer free of charge from XDA) can still display all apps.

**Comment by ImranR98** [comment]
Huh, I guess the GrapheneOS file manager (which I'm pretty sure is just AOSP's default) bypasses this.
