### ISSUE TITLE
Telegram keeps failing to update

### ISSUE THREAD

**Issue by mercertom** [ImranR98/Obtainium#2009]
I tried to download release asset and manually update, no dice.

"A Pseudo-Version is in Use"

Installed is 666817363
Latest is 799431557

**Comment by ImranR98** [comment]
Obtainium can not tell that the app was updated manually - this is because the app is being tracked by a "pseudo" version string instead of the real app version. So after any manual updates, you need to tick the checkmark ("mark as updated") to let Obtainium know that the app was updated.

Telegram now uses the "Direct Link" source type, which means you cannot get the real version - pseudo-version must be used. The dedicated Telegram source was removed since the Direct Link is now sufficient (app-specific dedicated sources are bloat and must be kept to a minimum).

To learn more about how Obtainium works (if anything above is unclear), please read the Wiki.

**Comment by ImranR98** [comment]
Could you post your Telegram config?

**Comment by mercertom** [comment]
I deleted it and trying to re-add it from telegram.org/dl/Android/apk, telegram.org/dl/Android/ and it's failing with "could not find a suitable release". What do you recommend? I think that many people should follow the best practice for telegram on obtanium, but I don't know what that is.

**Comment by ImranR98** [comment]
Open this on your device, find Telegram, and click "Add to Obtainium": https://apps.obtainium.imranr.dev/?categories=messaging

**Comment by ImranR98** [comment]
Alternatively just add it manually. Use this URL: `https://telegram.org/dl/android/apk` and set the "override source" option to "Direct APK Link".

**Comment by mercertom** [comment]
Thanks. I did that. It updated. Whatever Telegram configuration I used to have was stable for many months but recently broke a few days ago, and it would install update but then still need updating, and clearly be at least one version old (version # starting with a 6 vs the 7 most recent).

**Comment by ImranR98** [comment]
Yeah the Telegram source was removed in yesterday's update. Existing Telegram entries were supposed to be automatically modified to the new config but maybe that failed somehow.

**Comment by mercertom** [comment]
Telegram back to purgatory. Click update, or downloads, installs, then is needing update right after finishing. Version 766657373.

-------- Original Message --------

**Comment by mercertom** [comment]
It's going in a cycle between 4 versions: 3------, 666817363, 766657373, 8-----, then loops back to 3------

-------- Original Message --------

**Comment by mercertom** [comment]
It's still broken, cycling between 4 different versions, with different numbers than 4-5 days ago.

662326190, 704459756, 487811849, 947353626.

If I refresh, it cycles between which version it considers the latest.

How do I fix this?

**Comment by ImranR98** [comment]
It's weird that I can't reproduce this issue. Do you see it in different network environments? Maybe try diaabling some VPN or proxy if any?
If that failed, the solution would be to either restore the old Telegram source that does not rely on pseudo versions, or to figure out if the version can be extracted from somewhere using the HTML source.

**Comment by mercertom** [comment]
Switched to cellular network, same issue w different set of pseudo versions to cycle through. No VPN/proxy to speak of. I don't remember how I used to have it set up. Any other ideas for how to help you diagnose it?

**Comment by dsh2dsh** [comment]
Hi,

I'm observing the same behavior. Right now I see

510545309 Installed
691265021 Latest

now I'm doing pull-to-refresh and I see
5274452 Latest

pull-to-refresh again and
867355221 Latest

**Comment by JayXT** [comment]
I'm seeing a similar behavior. Obtanium shows that there's a Telegram update (version 12.9.1), but no matter how many times I'd try to update it, the app version remains at 12.9.0 and it's shown as needing update.

<img width="360" height="800" alt="Image" src="https://github.com/user-attachments/assets/116b86e4-4089-4a5b-b251-495dfb40ea53" />

<img width="360" height="800" alt="Image" src="https://github.com/user-attachments/assets/ba967375-89e3-4d73-85fe-85dbb98c66fa" />
