### ISSUE TITLE
Improve `Use latest asset upload as release date` setting

### ISSUE THREAD

**Issue by RestAFK** [ImranR98/Obtainium#2012]
**Describe the feature**
- Settings for explanation
  1. App Source URL
`https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root`
  2. Use latest asset upload as release date
  ON
  3. Use release date as version string (pseudo-version)
  ON
  4. Filter APKs by Regular Expression
  `fx-file-explorer`

- Description of what needs to be improved
  1. The latest upload date of the `fx-file-explorer` app (that i added to Obtainium) is "October 20, 2024"
  2. For example, the latest upload date for the `facebook.+beta` app (that i haven't added to Obtainium) is "December 9, 2024"
  3. However, the latest date of the `fx-file-explorer` app that appears on Obtainium is "December 9, 2024", not "October 20, 2024"
  4. Eventually, as the beta releases of the `facebook.+beta` app come out dozens of times, the `fx-file-explorer` app, even though has not been released yet, will also be updated dozens of times. This makes you quite tired.
  5. As a result, I would like the latest date criteria of the `Use latest asset upload as release date` setting to be limited to files filtered by a Regular Expression.

**Additional context**
Depending on how you look at it, it may be a bug rather than a feature, It seems closer to a bug.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.35
