### ISSUE TITLE
Not updating chrono beta

### ISSUE THREAD

**Issue by atom-smasher** [ImranR98/Obtainium#2014]
**Describe the bug**

Install [chrono](https://github.com/vicolo-dev/chrono) v0.6.0-beta1 - https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1

Set up Obtainium to update `chrono`.

Obtainium shows that `chrono 0.6.0-beta1` is `Installed`, and `v0.6.0-beta2` is `Latest`.

Press the `Update` button in Obtainium.

See a message to update from `0.6.0-beta1` to `0.6.0-beta1`.

**To Reproduce**

As above.

**Screenshots and Logs**

![obt-1](https://github.com/user-attachments/assets/8b9e53f5-7683-4054-afb1-01b56be5bf5a)

![obt-2](https://github.com/user-attachments/assets/a2962d99-de7e-495f-8547-bb238c47c4ed)

**Please complete the following information:**
 - Device: Motorola Moto G8 Power
 - OS: RR
 - Obtainium Version: 1.1.32

**Additional context**
N/A

**Comment by ImranR98** [comment]
I just installed the APK from their "Beta 2" release. The actual version string in the app is still Beta 1. So this is an issue with the APK. If you want Obtainium to stop trying to detect the "real" version string from the OS, turn off the "Reconcile version string..." toggle in the app config, then manually "mark as updated". See the Wiki for more details on how that works. The better option though, is for the app dev to update their APK.

**Comment by atom-smasher** [comment]
> If you want Obtainium to stop trying to detect the "real" version string from the OS, turn off the "Reconcile version string..." toggle in the app config, then manually "mark as updated". See the Wiki for more details on how that works. The better option though, is for the app dev to update their APK.

I disabled the "Reconcile version string..." option, and I'm getting the same update message, about updating from beta1 to beta1.

If I select "Download release asset", I can confirm the correct apk, click "Continue", that does grab the correct file, and I can install from there.
