### ISSUE TITLE
App infinitely refreshes

### ISSUE THREAD

**Issue by An-anonymous-coder** [ImranR98/Obtainium#2015]
**Describe the bug**
After updating to v1.1.33, whenever I open the app, the line at the top of the "Apps" tab will be stuck on the loading animation, even if nothing is loading.

**To Reproduce**
1. Update to v1.1.33
2. Open the app

**Screenshots and Logs**

https://github.com/user-attachments/assets/e41bcd2a-1167-4452-bcbe-6b64302790ff

**Please complete the following information:**
 - Device: Google Pixel 8
 - OS: GrapheneOS 2024120400 Android 15 (AP3A.241105.007)
 - Obtainium Version: version 1.1.33 versionCode 22903 (Installed via GitHub Releases APK)

**Additional context**

I have tried everything imaginable to get this to go away. I don't know if it's actually refreshing anything or not. It also causes some lag.

**Comment by ImranR98** [comment]
Do you have one or more of VLC, WhatsApp, or Telegram in your apps list? I'm guessing something went wrong when migrating them to the HTML source (dedicated sources for those apps were removed).

**Comment by ImranR98** [comment]
Since you're on Graphene, you should be able to delete the VLC file from `/Android/data/dev.imranr.obtainium/files/app_data`.

Try that and see if it helps. You can add a new VLC config from here: https://apps.obtainium.imranr.dev/?categories=video_player
