### ISSUE TITLE
Searching for apps through the "Add app" button gives out an error

### ISSUE THREAD

**Issue by matchboxbananasynergy** [ImranR98/Obtainium#202]
Steps to reproduce:

1. Open Obtainium
2. Tap on "Add app" on the bottom bar
3. Try searching for an app via the search option
4. Results pop up, check one of the results
5. Trying to add checked result gives a "null check operator used on a null value" error.

Important to note that searching through the "Import/Export" screen seems to work fine. It's just the "Add app" search feature that doesn't work.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.11-beta
