### ISSUE TITLE
Whatsapp detected version always changing

### ISSUE THREAD

**Issue by justbispo** [ImranR98/Obtainium#2022]
**Prerequisites**

**Describe the bug**
Since maybe the penultimate update, every time I refresh the Whatsapp entry, it shows a different version. It seems like the website changes the apk name each time it requests the file.

**To Reproduce**
1. Add Whatsapp from [Obtainium Apps](https://apps.obtainium.imranr.dev)
2. Install the app
3. Refresh the Whatsapp entry

**Screenshots and Logs**
https://github.com/user-attachments/assets/ffa86edf-c504-44f6-a7b3-88067c1e5f3b

**Please complete the following information:**
 - Device: Huawei P Smart 2019
 - OS: Android 10
 - Obtainium Version: 1.1.34

**Additional context**

**Comment by ImranR98** [comment]
Is the "Pseudo-Versioning Method" set to "Partial APK Hash"?

**Comment by justbispo** [comment]
No, it's "APK Link Hash"

**Comment by ImranR98** [comment]
This is likely due to https://github.com/ImranR98/Obtainium/issues/2027 (the setting gets reset for some reason). For now, you can manually change it back to "Partial APK Hash" and then mark as updated.

**Comment by ImranR98** [comment]
Fixed. Make sure to switch to partial APK hash - it won't revert now.
