### ISSUE TITLE
Seeing an error on checking for update.

### ISSUE THREAD

**Issue by anurag565** [ImranR98/Obtainium#2029]
Shared the screenshot and Obtainium export file, Check it please.  

**To Reproduce**
 Just check for updates by refreshing
 
![Screenshot_20241211_175754_Obtainium](https://github.com/user-attachments/assets/7070eadc-55f4-4d79-ac46-9907809f17a9)
[obtainium-export-2024-12-11T18-05-28.500137.json](https://github.com/user-attachments/files/18095523/obtainium-export-2024-12-11T18-05-28.500137.json)

 - Device: Samsung M13 5G
 - OS: OneUI 6.1
 - Obtainium Version: 1.1.34

**Comment by DarkCrypt** [comment]
Comparing your screenshot to your Obtainium export, all the "Forbidden" errors are because of APKMirror.

See issue https://github.com/ImranR98/Obtainium/issues/1973.

**Comment by anurag565** [comment]
Ok got it
