### ISSUE TITLE
Notification icon color

### ISSUE THREAD

**Issue by eloffmarijan** [ImranR98/Obtainium#203]
Adding white color notification icon is good for better visibility IMO.

**Comment by ImranR98** [comment]
I'm not sure what you mean by this - as Android automatically colours the notification icon appropriately. Could you send a screenshot and point out the icon you're talking about?

**Comment by eloffmarijan** [comment]
This is how obtainium notification icon color looks in my phone![Screenshot_20221228-082721.png](https://user-images.githubusercontent.com/101601874/209750769-acdfd397-be93-4d18-a61a-b087d794ea2b.png)
This is how I want it to look like, here a reference![Screenshot_20221228-081405_Samsung capture.png](https://user-images.githubusercontent.com/101601874/209751936-fa351911-8ef0-4950-9f64-3be8d88730ae.png)

**Comment by ImranR98** [comment]
Huh, guess it displays differently on other Android skins. Will be white in the next version (hopefully there aren't other phones that have the icon over a white background).

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.11-beta
