### ISSUE TITLE
A `No APK found` message bug by a `Filter APKs by Regular Expression` option

### ISSUE THREAD

**Issue by RestAFK** [ImranR98/Obtainium#2032]
**To Reproduce**

- Example of bug occurrence conditions
  1. App Source URL
  `https://github.com/j-hc/revanced-magisk-module`
  2. Filter APKs by Regular Expression
  `reddit-extended`

**Describe the bug**

In Obtainium v1.1.35, you will see a `No APK found` message due to the absence of the `reddit-extended` app in the latest release notes.

Originally it automatically found the latest notes with the `reddit-extended` app ([this](https://github.com/j-hc/revanced-magisk-module/releases/tag/20220969)). Looks like a hotfix is ​​needed.

**Comment by ImranR98** [comment]
There is no reddit extended apk in that repo.

**Comment by ImranR98** [comment]
You'd need to enable fallback to older releases to get the older release which does have it.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.36
