### ISSUE TITLE
BCR = basic call recording cannot find suitable release.

### ISSUE THREAD

**Issue by jekv2** [ImranR98/Obtainium#2035]
https://github.com/chenxiaolong/BCR

![Screenshot_20241213-134308](https://github.com/user-attachments/assets/a04b5754-6b29-450a-b371-b813635592b5)

**Comment by bagarwa** [comment]
Just out of curiosity.. any reason you want to track it in Obtanium instead of just Magisk app itself?

**Comment by jekv2** [comment]
> Just out of curiosity.. any reason you want to track it in Obtanium instead of just Magisk app itself?

update notification through ob.

@bagarwa

**Comment by DarkCrypt** [comment]
There's no apk to download within the releases. App is "Track-Only".
