### ISSUE TITLE
eapk support

### ISSUE THREAD

**Issue by Bhardwaj10Ankit** [ImranR98/Obtainium#2041]
**Describe the feature**
Can't add [Echo Extentions](https://github.com/brahmkshatriya/echo-youtube-extension/releases/tag/v2ed3dc2) (which are eapk format files) to update or even to track in obtainium, please include the support for the it if possible

**Comment by DarkCrypt** [comment]
Obtainium can track these extensions with the `Track-Only` toggle.

**Comment by ImranR98** [comment]
Installing eapk files is out of scope for Obtainium. You can still add the repo as track-only to get update notifications.
