### ISSUE TITLE
Not fetching if the apk is released inside same release

### ISSUE THREAD

**Issue by TanujairamV** [ImranR98/Obtainium#2045]
**Prerequisites**

**Describe the bug**

https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root
They are releasing their apk by editing a same release.
So Obtanium doesn't update tha app.
Is there any fix for it ? 

**To Reproduce**

**Screenshots and Logs**

**Please complete the following information:**
 - Device: 
 - OS: 
 - Obtainium Version: 

**Additional context**

**Comment by DarkCrypt** [comment]
See issue https://github.com/ImranR98/Obtainium/issues/2036.

**Comment by ImranR98** [comment]
Yes, this is already supported - see the Wiki and/or the issue linked above.
