### ISSUE TITLE
F-Droid Link

### ISSUE THREAD

**Issue by stantonlarson** [ImranR98/Obtainium#2046]
Can you please provide me a link so I can set up f-droid in Obtainium please

**Comment by DarkCrypt** [comment]
There's nothing to setup. Every app you want to add to Obtainium from F-Droid is a separate F-Droid link.

**Comment by stantonlarson** [comment]
Hello

Do you know what the link is ? thanks 



Dec 23, 2024, 23:22 by ***@***.***:

**Comment by DarkCrypt** [comment]
The link is the F-Droid page of the app you want.

Example for Gadgetbridge.
https://f-droid.org/packages/nodomain.freeyourgadget.gadgetbridge/

**Comment by stantonlarson** [comment]
thanks
-- 
 Secured with Tuta Mail: 
 https://tuta.com/free-email


Dec 24, 2024, 23:50 by ***@***.***:
