### ISSUE TITLE
Allow for Multiple Categories per App

### ISSUE THREAD

**Issue by ImranR98** [ImranR98/Obtainium#206]
As mentioned in #129.

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.11-beta

**Comment by S7venLights** [comment]
Quick check, are app categories saved in Obtainium exports, I would test, but I don't want to risk losing my categories

**Comment by ImranR98** [comment]
Yes and no. Imports should restore categories but only if those categories only exist in Obtainium. Now that you mention it, that probably should be fixed - imports should automatically create missing categories if needed.
