### ISSUE TITLE
enhancement idea: when update available display github releases page instead of code page

### ISSUE THREAD

**Issue by pjv** [ImranR98/Obtainium#209]
obtanium is great work - thanks!

when a github-installed app has an available update, the releases page/tab of the repo is probably more informative for a user that has already installed that app than the "code" ("home") page/tab of the repo. Most devs have at least some kind of changelog or description of the release on the releases page.

i know for me, when i tap on an app showing an available update i am scrolling to the bottom of the code page that obtanium shows and then tapping the releases link every time so i can see the changelog. Would be nice if obtanium did that for me.

**Comment by ImranR98** [comment]
The underlined "Update Available" text on the App listing already doubles as a link to the releases/changelog page.
