### ISSUE TITLE
 Feature request: custom application name

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#21]
Have the ability to add a custom name similar to the Read You RSS reader method from side of Burittos.
Then it will be  easy to navigate and search apps.

**Comment by ImranR98** [comment]
Decided not to add custom names, seems like too niche of a need that makes sense for an RSS reader but not necessarily this. Instead, the latest version has search/filter options: https://github.com/ImranR98/Obtainium/releases/tag/v0.3.0-beta

**Comment by S7venLights** [comment]
Okay, new changes are nice but reason I suggested this feature is because some apps have bad/different naming scheme on github,  eg: 
Author/name

Nextcloud/android
becomes
android by nextcloud
If I search for app Nextcloud I won't find it. 

or the app Noice
android-app by trynoice
if I search noice I find nothing

or Droidify
Gh4a
by Slapperwan
can't search droidify

**Comment by ImranR98** [comment]
Basic custom App name support has been added to the latest release: https://github.com/ImranR98/Obtainium/releases/tag/v0.4.0-beta

**Comment by S7venLights** [comment]
ƪ(ړײ)‎ƪ​​ Whoop whoop! 
I see it works, when first adding an app, thanks
