### ISSUE TITLE
Add Playstore as a 'Track Only' Source

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#212]
I have Auroura Store to update certain apps that do not release anywhere else, EG on Github.
But Auroura Store does not notify me of updates.

It would be nice if Obtainium could track releases from Playstore by web scraping perhaps.
Then we could get timely notififications of updates for just about anything.

I know downloading from playstore is too involved a process so people should just use Auroura Store for that. 

Feel free to close issue as unplanned though if this is not on the cards for you. 
I can still 'Track only' those apps on F-droid and open Auroura Store when they update.

**Comment by ImranR98** [comment]
Yeah, not sure if this is worth adding given the very niche use case. I did take a look at the website but it seems very tricky to scrape the version. Besides, using one source (Play Store) to track updates from another (Aurora) could lead to problems if they are out of sync; I've heard Aurora grabs data from random different countries' versions of the Play Store, and App updates are not always published in all countries at the same time. Aurora could/should probably just support notifications.
