### ISSUE TITLE
Treat PAT Field as a Password Field (Hidden Using Dot Characters)

### ISSUE THREAD

**Issue by bakinazik** [ImranR98/Obtainium#215]
Can you add a blur on token section? If someone review in for example youtube video or in a live streaming its so difficult to introduce.

**Comment by ImranR98** [comment]
PAT input is now obscured: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.14-beta

**Comment by eloffmarijan** [comment]
Adding show password button also good.

**Comment by BabyOilJohnson** [comment]
> Adding a show PAT button also good, to know what was entered or correct any mistake.

Any updates?
