### ISSUE TITLE
Difficult to tap the three dots on a smartphone with a small screen

### ISSUE THREAD

**Issue by bluefly000** [ImranR98/Obtainium#216]
device : pixel 4a running GrapheneOS
app ver : 0.9.13

On a phone with a large screen like the Pixel 6a, this is not a problem, but on a phone with a smaller screen like the Pixel 4a, you will have to tap well to the left of the three dots to get a response.
On a phone with a smaller screen than the Pixel4a, you would not be able to tap the three dots.

https://user-images.githubusercontent.com/101441707/210963084-0ed4e965-5ff3-40fb-8dbe-0758e8ce6f42.mp4

**Comment by ImranR98** [comment]
The bottom bar is now scrollable: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.14-beta
