### ISSUE TITLE
No update notification

### ISSUE THREAD

**Issue by BabyOilJohnson** [ImranR98/Obtainium#221]
I'm not getting update notification, when obtainium app has update but other apps have no problem.

**Comment by ImranR98** [comment]
Did you see the "update available" in Obtainium when you open the app but without opening the App detail page? And are you certain that update checking ran in the background before that?

**Comment by eloffmarijan** [comment]
> Did you see the "update available" in Obtainium when you open the app but without opening the App detail page?

I see the "update available" in obtainium when I opened the app.

> And are you certain that update checking ran in the background before that?

Yes, the background update checker ran an hour ago before I opened.

**Comment by ImranR98** [comment]
Haven't been able to reproduce this on my end. Could ypu attach app logs?

**Comment by eloffmarijan** [comment]
Sure.

**Comment by ImranR98** [comment]
Weird, all the update checks found 0 updates. Are the log timestamps right for the time you missed the notification?

**Comment by eloffmarijan** [comment]
Yes.

**Comment by ImranR98** [comment]
Hopefully it's just a one-off bug as I haven't been able to find anything that could have caused this - Obtainium update checking works the same as any other app.

**Comment by ImranR98** [comment]
What Android version are you on? I've tried Android 12 and 13 and haven't had this problem.

**Comment by BabyOilJohnson** [comment]
Android 11.

**Comment by ImranR98** [comment]
Hey, just checking in - are you still having this issue? I tried an Android 11 emulator and it works fine there too.

**Comment by BabyOilJohnson** [comment]
Now it's working fine.
