### ISSUE TITLE
Support Codeberg as Release Source

### ISSUE THREAD

**Issue by lephyrus** [ImranR98/Obtainium#222]
Would you consider supporting apps hosted on Codeberg? My preferred radio app has moved there: https://codeberg.org/y20k/transistor

At first glance it looks very similar to GitHub, so hopefully not a lot of customization is needed. Thanks for your work so far!

**Comment by ImranR98** [comment]
It definitely is very similar; added: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.0-beta
