### ISSUE TITLE
Do already installed apps have to be added manually? 

### ISSUE THREAD

**Issue by e-t-l** [ImranR98/Obtainium#223]
I have some apps I've already installed from github, and I just discovered Obtanium. Is Obtanium supposed to be able to detect what apps have github repos, or do I have to add them each to Obtanium manually?

**Comment by ImranR98** [comment]
Yes, auto-adding installed Apps is not supported as it would need a reliable way to get an App's package ID from GitHub (or other sources) without downloading it. F-Droid does support this but it can't be used as it would cause conflicts with the installed Apps. See #163.
