### ISSUE TITLE
Feature Request: Multi-select actions + link copying/sharing

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#23]
This would just be a nice to have. Some sort of method to copy links off Github repos either by long pressing and copying in the webview or by long pressing and copying/sharing from the app list of Obtainium.

**Comment by ImranR98** [comment]
Good idea. Will broaden this a bit.

Ability to long press items in the apps list to enter multi-select mode, and tap multiple apps to select them. From there, we should be able to perform mass actions on them:
- Share URL
- Mark as Installed
- Mark as Not Installed
- Remove

**Comment by ImranR98** [comment]
Multi-select options (including URL sharing) have been added in the latest release: https://github.com/ImranR98/Obtainium/releases/tag/v0.4.0-beta
