### ISSUE TITLE
Unexpected error: Type 'Null' is not a subtype 'String' in type cast

### ISSUE THREAD

**Issue by strasharo** [ImranR98/Obtainium#231]
When I'm trying to add https://github.com/connectbot/connectbot in Obtainium I'm getting the following exception
![Screenshot_20230120-110338](https://user-images.githubusercontent.com/3337997/213658064-55986510-33d2-4315-90d4-5eecc84cc957.png)

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.3-beta
