### ISSUE TITLE
Home Assistant "Could not find a suitable release"

### ISSUE THREAD

**Issue by mike-lloyd03** [ImranR98/Obtainium#237]
Thanks so much for this app!

I'm trying to add [Home Assistant Android](https://github.com/home-assistant/android/) but it keeps saying "Could not find a suitable release" if I do not enable "Include prereleases" (which I don't want to do).

The Home Assistant repo appears to (annoyingly) create a pre-release tag for _every_ commit. So there are hundreds of them since that last stable release last month. I'm wondering if Obtainium is just not looking back far enough to find the suitable release.

I tried adding a regex of `\d{4}\.\d{1,2}\.\d{1,2}` to filter out the noise but it didn't help.

**Comment by ImranR98** [comment]
You're right, GitHub provides the last 30 releases by default so it wasn't looking far back enough. I've changed the request to ask for the last 100 releases (the max per-request limit), which should hopefully be enough for this App (from what I see, it's about 45 releases between full releases, so it should be fine).

https://github.com/ImranR98/Obtainium/releases/tag/v0.10.5-beta

**Comment by mike-lloyd03** [comment]
Thanks! I'm really enjoying this app!
