### ISSUE TITLE
Feature Request: Remember which APK to install

### ISSUE THREAD

**Issue by riley-martine** [ImranR98/Obtainium#238]
When installing an update, Obtainium provides me with a choice of APKs. If the names of all of them are the same, I would like it to remember which one I selected last time, and choose it automatically. For example, Simple-Gallery has a proprietary and FOSS release, and I am slightly annoyed having to pick the FOSS one every time I update. (This app has frequent releases.)

https://github.com/SimpleMobileTools/Simple-Gallery/releases/tag/6.26.3

**Comment by ImranR98** [comment]
There is no consistent APK naming scheme between Apps or even between releases of the same App, so trying to pick one automatically would be unreliable and error prone. Instead, there could be an option to filter APKs using a regular expression - that the user can customize it on a per-app basis, and it would be on them to make sure they get it right.

**Comment by ImranR98** [comment]
This has been added: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.5-beta
You will need to set the option on a per-App basis.

**Comment by riley-martine** [comment]
Thank you, and I will set that up!
