### ISSUE TITLE
Error message about package conflicts when attempting to update

### ISSUE THREAD

**Issue by droidus** [ImranR98/Obtainium#239]
I tried to update a few of my packages.  I got this error message: "App not installed as package conflicts with an existing package".

**Comment by ImranR98** [comment]
This is a problem with the APK, not Obtainium - you should get the same error after downloading and installing the APK manually.

Most likely cause is the new APK being signed with a different key from the existing installed one. This can happen (for example) if you try to update an App from F-Droid with an update from a different source.
