### ISSUE TITLE
Bug: Install fails on device sleep

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#24]
Running the 0.2.4 beta:  

Sometimes I click update on an app and the download starts and if I leave the app or the phone sleeps at some point during or after download, then I can't install the update when returning to Obtainium.
If I open the repo, the update button is greyed out, and unless I remove the app from obtanium and re-add it I can't install the latest version.

**Comment by ImranR98** [comment]
Weird. I tried it just now: started download, went to home screen, turned screen off, and returned to app 5 minutes later. The first time I faced the same issue as you, but it worked the second time. So I'm guessing something is wrong with the foreground/background detection (using [this plugin](https://pub.dev/packages/flutter_fgbg)) or the way it's being used. Does it fail consistently for you?

**Comment by S7venLights** [comment]
I can't say yet if it's consistent, I'll keep an eye out and test more. I have seen that notification at times but it doesn't always present, I'm removing androids battery optimization to see if that helps.

**Comment by ImranR98** [comment]
I just noticed the new installer plugin used in the [latest release](https://github.com/ImranR98/Obtainium/releases/tag/v0.4.0-beta) (changed as part of #25) does not need us to manually wait for the user to return to the foreground. So there may still be bugs with the notification being sent, but the install itself should now be more consistent in waiting for you to return to the App.
My basic testing was fine, but I'll reopen this issue if you're still having problems.
