### ISSUE TITLE
Request: uninstall, app settings

### ISSUE THREAD

**Issue by Efreak** [ImranR98/Obtainium#247]
Would be nice to have a way to [uninstall the app](https://stackoverflow.com/a/62196226). Either a dedicated button, or when clicking remove provide options to uninstall, remove from obtainium, or both.

Would also be nice to have a link to app settings. See second example for [Android Intent Plug-in](https://github.com/fluttercommunity/plus_plugins/tree/main/packages/android_intent_plus)

**Comment by ImranR98** [comment]
From what I remember, the uninstall permission is only available to system apps. But I'll look into it and add the settings link at least.

**Comment by Efreak** [comment]
Uninstall is certainly available. Fdroid, 3c toolbox, Nova launcher, etc are all capable of requesting an app be uninstalled. AFAIK system signature is only needed for apps that install/uninstall packages in the background without user interaction. Package installer can be called manually from any app, as long as it's been granted permission (or on older apps, the systemwide permission to allow third party apps to be installed)

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.7-beta

**Comment by ImranR98** [comment]
Also, thanks for making me aware of the Intent Plug-In - might be useful for resolving some other issues or dropping some other plugin dependencies.
