### ISSUE TITLE
Not finding latest version

### ISSUE THREAD

**Issue by droidus** [ImranR98/Obtainium#249]
I have the immich app installed (v1.42).  The link in obtanium that I have is: https://github.com/immich-app/immich.  When I go to that link and look at releases, it shows 1.43.1 as the latest release.  Yet obtanium is showing there is no update.  Am I doing something wrong?

**Comment by ImranR98** [comment]
The latest release does not have an APK attached (check the 'Assets' section). The last version with an APK is 1.42.

**Comment by droidus** [comment]
Interesting; it is available in the Aurora store.  So someone must have compiled/built it?
