### ISSUE TITLE
Please add Divest Os Repo for Mull browser 

### ISSUE THREAD

**Issue by Bizz912** [ImranR98/Obtainium#251]
Can you please add Divest repo for downloading Mull Browser. Your app is awesome. Been on and off since last year on Obtainium. 10/10

**Comment by ImranR98** [comment]
You can already do this. Paste their [repo URL](https://divestos.org/fdroid/official) into the 'Add App' page and specify 'Mull' as the App Name under Additional Options.
I've assumed you mean their F-Droid repo. If not, please provide more info.

**Comment by Bizz912** [comment]
Thanks

**Comment by Bizz912** [comment]
I use Mull directly from Divest Os Repo not of fdroid but DivestOS Official repo from Droidify.

**Comment by ImranR98** [comment]
You mean the official f-droid repo? You can add it from there too.

**Comment by Bizz912** [comment]
Got it. Thanks
