### ISSUE TITLE
Export does not work

### ISSUE THREAD

**Issue by resiehnnes** [ImranR98/Obtainium#252]
Huawei P30 Pro running Android 10
Obtainium 0.10.6-beta
Storage permission is allowed

Here's the screenshot:

![e965141f-a6e4-4127-bdd4-5ccd82043791](https://user-images.githubusercontent.com/52158526/215800005-4dc77f5a-81b6-45ef-b9b3-7b98ffe6fc32.jpg)

**Comment by ImranR98** [comment]
Have you granted storage access to the app?

**Comment by ImranR98** [comment]
Should be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.7-beta

**Comment by resiehnnes** [comment]
> Should be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.7-beta

Thanks, export is working now.
