### ISSUE TITLE
Page switch during transition effect results in blank page

### ISSUE THREAD

**Issue by Lukas-Heiligenbrunner** [ImranR98/Obtainium#254]
Hey, 

When switching from homepage to another one and back fast enough (during transition effect) the homepage results in a blank page.

App Version: v0.10.6-beta

Phone: Xiaomi Redmi  Note 11s
Android version: 11
MIUI version: 13.0.9Stable
Kernel Version: 4.14.186

![Screenshot_2023-02-04-11-52-05-442_dev imranr obtainium](https://user-images.githubusercontent.com/30468956/216763372-235ed7e5-b202-469c-856e-d57dcb28a6af.jpg)

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.7-beta
