### ISSUE TITLE
Bug:- if adding pre-installed app, obtainium is re downloading selected apk. 

### ISSUE THREAD

**Issue by soymadip** [ImranR98/Obtainium#261]
As of now if we wanna add a app which is already installed on device, obtainium is re downloading selected apk. 
When we are on cellular data (limited), it's a waste if obtainium r-edownloads it. 
- it should check if the app is installed, if it's installed, obtainium shouldn't download the apk. 
- if app is not installed, then it should download the app and install.

https://user-images.githubusercontent.com/84225810/217001751-0acc41ab-6fb3-481e-8282-a36b876e4103.mp4

**Comment by ImranR98** [comment]
In order to tell that a downloaded app is the same as an installed one (among other reasons), we need the app's unique package ID (the app name is not enough).

The only way to get this ID is through the APK (for most sources at least, including GitHub).

So downloading the APK is unavoidable.

**Comment by soymadip** [comment]
Understood, in that case a button to choose if we want to install/download the apk can solve the problem I guess😅

**Comment by ImranR98** [comment]
The app ID is required for adding apps in general, not just for comparing with existing installed apps. It's not possible to add apps in obtainium without doing this (with the exception of third party imports, but those don't work correctly until you download the APK later anways). So there's no way to avoid APK download.

Technically there could be an option for the user to manually select the ID from a list of already installed apps, but I don't think it is worth doing for such a niche use case (after all, adding an app only needs to be done once).

**Comment by soymadip** [comment]
Got it 🙂
