### ISSUE TITLE
please do not force to redownload from obtanium

### ISSUE THREAD

**Issue by Simpath** [ImranR98/Obtainium#265]
It doesn't work unless app is reinstalled via obtainium. Doesn't work even if previously installed from GitHub itself. This is not good. Half of my mobile data is gone now. Upgrade all & oss tracker (apps) work just fine. Could you please fix it?

**Comment by ImranR98** [comment]
Not sure if I understand what you mean, but I guess it's the same as #261 - please see that issue.

**Comment by Simpath** [comment]
yes this issue was same as #261
but

i was saying, upgrade all and oss tracker are similiar apps to obtainium but they don't redownload the apps. could you look into them and might be able to find a way
