### ISSUE TITLE
app is not updating to latest version

### ISSUE THREAD

**Issue by droidus** [ImranR98/Obtainium#269]
I am using obtanium v0.10.7-beta.  There is an update for Immich.  I am running v.1.46, and it shows 1.46.1 available.  I update, and when done, I open the Immich app, and it still says v.1.46.  In obtanium, it still shows an update is available, even after refreshing the page/app.  
https://github.com/immich-app/immich/releases/tag/v1.46.1

**Comment by ImranR98** [comment]
I've manually installed the latest APK from their GitHub and it shows up as `1.46.0`, so it looks like they've just uploaded an older APK.

**Comment by mike-lloyd03** [comment]
@droidus let the Immich team know in their Discord. They are quick to fix these kinds of things.

**Comment by bo0tzz** [comment]
This isn't a bug per se. 1.46.1 was a server-only hotfix, so the app didn't get a release in that version.
