### ISSUE TITLE
Can't update or install Dicio

### ISSUE THREAD

**Issue by mike-lloyd03** [ImranR98/Obtainium#270]
Obtainium shows an update for [Dicio](https://github.com/Stypox/dicio-android) is available. When I tap update, nothing happens. Uninstalling the app and trying to install it through Obtainium does nothing either. After manually installing the update from GitHub, Obtainium shows it still not installed.

**Comment by ImranR98** [comment]
Hmm, I thought Android didn't allow Apps to change their package ID between updates, but apparently that isn't true as [Dicio has changed their App ID](https://github.com/Stypox/dicio-android/commit/66fa7d0008c2dc5f0070481fe47218e32dd7ac9e) in the latest update.

Obtainium currently blocks this, and doesn't show an error either (which is a bug).

The next release will remove App ID checking and fix the no error bug.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.8-beta

**Comment by ImranR98** [comment]
Actually, nevermind. Android does not allow Apps to change their ID, Dicio 0.9 just gets installed as a new, separate App from Dicio 0.8. Obtainium should block this as you generally want to make sure the App you're installing as an update is the same one that you had before.

I'll revert the latest update change. You should remove Dicio from Obtainium and re-add it - it will install version 0.9 separately.

**Comment by ImranR98** [comment]
You should still see an actual error now explaining the issue: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.9-beta
