### ISSUE TITLE
Support selfhosted gitlab and gitea/forgejo servers

### ISSUE THREAD

**Issue by Sertonix** [ImranR98/Obtainium#271]
Gitlab and gitea/forgejo servers can be self hosted and the would have protocols that could be understand by obtainium.
It would be nice to have an option to select what type of server the url is.
Potentially it would be nice to add other servers as sources so that you can search on them.

**Comment by ImranR98** [comment]
Custom Sources will be tricky to add, but definitely a good idea and worth doing. Aside from GitLab/Gitea it would also improve the experience for third-party F-Droid repos.

**Comment by ImranR98** [comment]
Could you link to a custom GitLab host to test with?

**Comment by Sertonix** [comment]
I found this one: [VLC](https://code.videolan.org)

**Comment by ImranR98** [comment]
Leaving some notes for later:
- App schema should have a new property that is identical to `additionalAppSpecificSourceAgnosticSettingFormItems`, except that these settings will only be available during the initial App add step, and cannot be changed later.
    - The obvious name for this new list would be something like `additionalFixedAppSpecificSourceAgnosticSettingFormItems` but that's too long. Use this as a chance to rename all such lists to something shorter.
- The first member of this new list will be `overrideSource`, an optional string which is `null` by default.
    - This should only be set when the App is added and should not be modifiable after that, hence the need for the new settings list.
- `getSource` should be modified to take an optional `overrideSource` string, and immediately return the override source if one is given and actually exists.
    - Existing uses of `getSource` should be changed to make use of this new param where appropriate.
- Wherever `standardizeURL` is used, don't use it if the App specifies an override source - just return the existing URL.
    - This is because we don't know what crazy URLs third party or self-hosted gitlab/gitea/fdroid/etc repos may have).
- On the Add App page, make sure the new settings list is being used, but it should actually be placed right below the search bar (above the "Additional Options for ..." heading). 
- Also on the Add App page, show a warning dialog when the user clicks "Add" if the new override source setting is not null. 2 warnings:
    - User is told that their target site may not work and they should only use "Auto" unless they know what they're doing (think about good phrasing).
    - User is told to enter an exact repo URL (since `standardizeURL` can no longer be relied on to reliably grab the 'standard' URL and discard the rest. Again, think of better wording (is it obvious what "exact URL" is supposed to mean?).


Above should be okay but will probably have some unforeseen issues.

**Comment by ImranR98** [comment]
> I found this one: [VLC](https://code.videolan.org)

Doesn't look like any repos on this site have APKs attached to the releases. Could you provide the repo you made this issue for (assuming you had one)?

**Comment by ImranR98** [comment]
Closing this for now, the feature has been added in the latest version: https://github.com/ImranR98/Obtainium/releases/tag/v0.12.0-beta

Have not tried it with third-party gitlab repos so we may need to reopen this issue if it turns out not to work. Works with third-party F-Droid repos.
