### ISSUE TITLE
[Suggestion] - Clicking "Update available" should go to app's Obtainium update screen, not app's github page

### ISSUE THREAD

**Issue by jeremiah-k** [ImranR98/Obtainium#274]
I personally don't have a problem with the current behavior, but I set up a friend (who isn't very tech savvy) with Obtainium for updating a certain app and when she looks at the list of apps and sees that an update is available, she clicks "Update available" on the right and ends up at Github, not understanding why it isn't updating. Some other people might find this confusing too.

**Comment by ImranR98** [comment]
Makes sense, I've actually absentmindedly clicked it a couple of times too when trying to update.
That said, I'd like to keep a button to open the app's changelog page as well without making the UI too cluttered - definitely something to play around with.

**Comment by Sertonix** [comment]
I really like having a ui full of information. Maybe consider having some opt-in options

**Comment by ImranR98** [comment]
Messed around w/ the UI - things should be clearer: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.0-beta
