### ISSUE TITLE
OpenCamera

### ISSUE THREAD

**Issue by rancidfrog** [ImranR98/Obtainium#28]
OpenCamera, net.sourceforge.opencamera
Is a widely used camera app on android.
Unfortunately for some reason dev uses sourceforge for releases.
https://sourceforge.net/projects/opencamera/files/

Is there a way to add this source?

**Comment by ImranR98** [comment]
Basic SourceForge support has been added in the latest release: https://github.com/ImranR98/Obtainium/releases/tag/v0.4.0-beta
More advanced options (like falling back to older releases if the latest one does not have an APK) can be added later if anyone needs it.
