### ISSUE TITLE
HTML source cannot handle relative HREFs

### ISSUE THREAD

**Issue by sevmonster** [ImranR98/Obtainium#286]
In the HTML source provider:
https://github.com/ImranR98/Obtainium/blob/bf7b0c5702504695bc3e0c0fc81dc2cf96b7d873/lib/app_sources/html.dart#L40 The `href` is prepended with the source URI origin if it does not begin with `https://` or `https://`. This does not work for relative links, i.e. links not beginning with `/` (relevant to the site root not the current directory)

For example, for the site `https://example.com/my/file.apk`, and a link `href` of `dl.php`, the resulting download link will be `https://example.com/dl.php` instead of the correct relative URI `https://example.com/my/dl.php`

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.11-beta

**Comment by ImranR98** [comment]
Apparently the example in the above comment was not exactly right. See https://github.com/ImranR98/Obtainium/issues/455#issuecomment-1505783521
