### ISSUE TITLE
Add neutroncode.com and/or more robust HTML provider

### ISSUE THREAD

**Issue by sevmonster** [ImranR98/Obtainium#287]
The non-Google builds of Neutron Player (required if you paid outside of Google) have downloads you are redirected to after `POST`ing a form to the download page. The only other way to download would be to `GET` the actual download URL, which seems to be unchanging, and does not require form data or anything despite the redirect requiring it.

Example download pages:
https://neutroncode.com/downloads/file/4-neutronmpapkarm64-usb-no-def
https://neutroncode.com/download/NeutronMP_ARM64_USB_NO_DEF.apk

In the mean time I set up a scraper to provide a download link in a format Obtainium understands:
https://sev.monster/obtainium/neutron.php

Example download for the file linked above:
https://sev.monster/obtainium/neutron.php?url=4-neutronmpapkarm64-usb-no-def

I offer no warranty or other guarantees so use at your own risk.

I originally just hotlinked to the download page, but that resulted in the version being set to the APK name. I realized then that the HTML code is very basic—it only looks for download links matching `link/versioncode.apk` and this is very restrictive. I had to add a download redirect to my script so that Obtainium didn't see the filename as the version. I also discovered #286 while doing this as I initially used a relative URI, before getting a 404 error for my efforts.

In case it is helpful here is the script source:
https://sev.monster/obtainium/neutron.php.src

I hacked it together in an hour or so, so it's not very good.

**Comment by ImranR98** [comment]
This would have to be added as its own source, that way we can use the fixed APK link while scraping the webpage to get the version.

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.10-beta
