### ISSUE TITLE
Support Google Drive (MiXplorer + betas)

### ISSUE THREAD

**Issue by sevmonster** [ImranR98/Obtainium#288]
While it's certainly not common, some developers release their apps via Google Drive (and other cloud services). It would be nice to be able to select the app download and its version based on some regex matching the filename.
https://mixplorer.com/
https://forum.xda-developers.com/showpost.php?p=23109280&postcount=2
https://drive.google.com/drive/mobile/folders/1BfeK39boriHy-9q76eXLLqbCwfV17-Gv

**Comment by ImranR98** [comment]
Doesn't look like Google provides a simple way to download files from Drive programatically - from what I could find you would need to use their API.

**Comment by soymadip** [comment]
> Doesn't look like Google provides a simple way to download files from Drive programatically - from what I could find you would need to use their API.

I guess the answer is no,  but is it possible to  add telegram?

**Comment by ImranR98** [comment]
> I guess the answer is no, but is it possible to add telegram support?

See issue #1

**Comment by soymadip** [comment]
> > I guess the answer is no, but is it possible to add telegram support?
> 
> See issue #1

Got it 🙎

**Comment by fellinir** [comment]
@soymadip But still doable, isn't? Many apps, also open sources, can manage files in GDrives. And unfortunately this is not only a trend with MiXplorer.

**Comment by soymadip** [comment]
> @soymadip But still doable, isn't? Many apps, also open sources, can manage files in GDrives. And unfortunately this is not only a trend with MiXplorer.

Yeah

**Comment by TameemS** [comment]
If you don't wanna deal with APIs, there is [gdown](https://github.com/wkentaro/gdown) which may help.

As for MiXplorer, there is https://mixplorer.com/beta which is a basic HTML page that has an APK link to the latest beta, but when I try to add it as a source it says "Not found". Only tracking works.
I'm new to Obtanium so... am I doing anything wrong?

**Comment by ImranR98** [comment]
> As for MiXplorer, there is https://mixplorer.com/beta which is a basic HTML page that has an APK link to the latest beta, but when I try to add it as a source it says "Not found". Only tracking works. I'm new to Obtanium so... am I doing anything wrong?

Turned out to be a bug. Should work now: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.35-beta

**Comment by sevmonster** [comment]
I only recently found that page, and it is sometimes newer than the Drive uploads even... Forgot to report it. Thanks, I don't see a reason to keep this open anymore.

**Comment by DJCrashdummy** [comment]
FWIW: if you don't want to use betas and prefer stable versions, you can use Uptodown where it and its addons are availabe (as APKMirror is unfortunately a track-only source).

**Comment by seventyiris83** [comment]
hi, could someone help me to make obtainium select the first apk on https://mixplorer.com/beta please? only the apk verison **without** x64 or x86 is compatible with my phone and obtainium defaults to the x64 version which i don't want. thanks!

**Comment by DarkCrypt** [comment]
@seventyiris83 
I posted an install link for arm64 including a config breakdown for any version [here](https://github.com/ImranR98/Obtainium/issues/1786#issuecomment-2351203533).

**Comment by seventyiris83** [comment]
> @seventyiris83 I posted an install link for arm64 including a config breakdown for any version [here](https://github.com/ImranR98/Obtainium/issues/1786#issuecomment-2351203533).

thank you!!

**Comment by WhoMI7** [comment]
how do I add Mixplorer addons to obtanium?
there's https://github.com/driftywinds/mixplorer-releases but they don't release addons

**Comment by sevmonster** [comment]
I don't believe the author releases the addons outside of the Play Store, and Google Drive IIRC. They don't change frequently enough to benefit IMO.

**Comment by hdjdb** [comment]
Mixplorer is a one-stop shop for images, PDFs, archives and they've even added and encryption add-on. Any updates that they *do* get, you'll want asap.
