### ISSUE TITLE
Steam source Steam app shows Steam Chat version code if both are added

### ISSUE THREAD

**Issue by sevmonster** [ImranR98/Obtainium#289]
![Screenshot_20230215-062817](https://user-images.githubusercontent.com/16788697/219027537-a46cf4a0-fa68-48ee-bcf9-cdbddc25d067.png)
1.0.8 is Steam Chat. The actual version is 3.0.0. (Play Store version is 3.3)

**Comment by ImranR98** [comment]
Should be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.11-beta
