### ISSUE TITLE
Support for Telegram Web

### ISSUE THREAD

**Issue by NaeemBolchhi** [ImranR98/Obtainium#290]
Telegram Web (the unrestricted variant) is available for download at https://telegram.org/dl/android/apk, but this link isn't supported by Obtainium.

Supposing that support can be added, version tracking is impossible without downloading the apk first, as the website doesn't mention the version number of the file anywhere (to my knowledge).

Hence. What if Obtainium could track the Play Store link for the version number and download from the above link instead? It'll work since Telegram releases both variants together. They have different package names but share the package version number.

Of course, this variant of Telegram can update by itself. It would still be pretty cool to be able to add it to Obtainium. Just thinking out loud.

**Comment by ImranR98** [comment]
Regarding Play Store: https://github.com/ImranR98/Obtainium/issues/212#issuecomment-1369229752
The Telegram site could be added as a Source on its own, but I can't find where they list the latest app version, which would be needed.

**Comment by NaeemBolchhi** [comment]
I was able to create a scraper that gets the version number of the last released apk from https://t.me/s/TAndroidAPK. Seems like Obtainium will only pick up URLs if they end in ".apk", so the download link of https://telegram.org/dl/android/apk isn't picked up by default. So I changed it to https://telegram.org/dl/android/apk?v9.4.2.apk, where both the version number and the apk extension appear in the URL.

Here is my Cloudflare Worker scraper: https://telegram.naeembolchhi.workers.dev/
Source Code: https://pastebin.com/rR5L669A

Obtanium accepted this, but there were two new issues.

![Screenshot_20230216-205224_Obtainium](https://user-images.githubusercontent.com/42773187/219400630-8f969d15-06e6-4987-9a24-224593fd5c8a.png)

In this case, the developer name is automatically set to the domain name, which I was hoping could be customized (only Telegram or Telegram.org). Also, the version number looks weird, and might look better if the "?apk" part was not included.

To make the HTML Fallback more robust, my suggestion would be:
- #293 Reg Ex that lets me specify which apk to download
- New toggle under "Additional Options for HTML" called "Match and Replace Version String" (1)
- New toggle under "Additional Options for HTML" called "Custom Developer Name"

*(1) This should ideally offer two text fields, one for Match and one for Replace. This would allow matching /.*v(.*)/ and replacing it with "$1" for a cleaner versioning.

I have no idea how much of this is even feasible, so I'll leave that to your better judgement.

**Comment by ImranR98** [comment]
I was not aware of https://t.me/s/TAndroidAPK
With that, Telegram can be added as its own source

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.10-beta
