### ISSUE TITLE
Refresh bug with only Obtainium

### ISSUE THREAD

**Issue by NaeemBolchhi** [ImranR98/Obtainium#292]
![Screenshot_20230216-153450_Obtainium](https://user-images.githubusercontent.com/42773187/219326630-399f924b-460c-4c07-af85-545387272b3b.png)

This is a bug that can't be tested on the latest version, I think. I don't know. Anyway.

The error in the screenshot appears when the app list has only Obtainium, usually after first install from an older version of the app. Just try to refresh the empty app list with only Obtainium in it to reproduce the issue.

**Comment by NaeemBolchhi** [comment]
The bug seems to disappear if I close the app once. The next time I'm in the app, it checks for update nornally and the error doesn't show up anymore. It seems to only appear after first install, but during that time, it appears every time I try to refresh the app list.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.12-beta
