### ISSUE TITLE
Regular Expression on HTML Fallback

### ISSUE THREAD

**Issue by NaeemBolchhi** [ImranR98/Obtainium#293]
For links like this https://www.torproject.org/download/#android that have multiple apk files, Obtainium automatically picks the last apk. That's expected behavior and is also mentioned on the project README file.

So, if I wanted to pick the first apk, which has "aarch64" in the URL, setting that as Regular Expression should select the "last matching apk". But that does not happen.

Instead, adding any Regular Expression that does not match the last apk link returns a "No APK Found" error.

I was hoping we could use RegEx to narrow down our selection of the apk, as otherwise there is no meaning in having RegEx with HTML Fallback pages.

This is only an example, and I know there's an fdroid repo for Tor Browser.

**Comment by ImranR98** [comment]
Good catch. Originally I selected the last APK as there was no RegEx option. Now that we have source-agnostic APK selection via RegEx, it is safe for the HTML source to return all APK URLs instead of just one.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.12-beta
