### ISSUE TITLE
"Could not find a suitable release" message blocks buttons

### ISSUE THREAD

**Issue by AliceDTRH** [ImranR98/Obtainium#296]
![Screenshot_20230216_225644](https://user-images.githubusercontent.com/57547425/219496204-c50a7582-7c76-4cfa-aba2-35fafda4a372.jpg)
When there is no suitable release the message to inform you about it blocks the buttons. 
I found out you can hide the message by dragging down on it but it would still be nice if this message could be moved somewhere else or if it went away quicker.

**Comment by ImranR98** [comment]
I think the message timeout is reasonable (especially since it is the Flutter default) - the user should have enough time to read it.
