### ISSUE TITLE
Add date along with version in app list, and allow sorting by date.

### ISSUE THREAD

**Issue by greenerk** [ImranR98/Obtainium#298]
Feature request.

Sometimes a project can go stale and get forgotten about.  This can lead to old, insecure apps being left on the phone.
Having the release date with the version (_maybe under the version, the same way the project owner is under the project name_) and allowing to sort by this would make is easy to see how long it's been since an app was last updated.

![image](https://user-images.githubusercontent.com/56622533/219694803-52df93be-c013-4fe2-a3f0-85eee26c08c8.png)

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.0-beta
