### ISSUE TITLE
[Feature Request] Add App per release type

### ISSUE THREAD

**Issue by fellinir** [ImranR98/Obtainium#299]
See as sample: https://github.com/brave/brave-browser
Releases over there are split in many types and I wished to install both the Stable and the Beta apks.
At first, I added a Brave App item properly configured with regex to download only the stable release. Then decided to add another Brave App and make it slightly different, only the regex to catch the release was modified, to grab the Beta.

By doing this, the app downloaded the Beta but replaced the App item which was configured before. So we can download only one release type per source.

I did a workaround by adding again the Brave App with a different source link,
this time:
https://github.com/brave/brave-browser/releases
Instead of:
https://github.com/brave/brave-browser

By doing this, now I have got Brave Apps in menu, tracking two different releases.
This workaround is not an ideal solution since it is buggy anyway, so a proper feature to allow this is preferred.
![Screenshot_20230218-233405_Obtainium](https://user-images.githubusercontent.com/92597054/219896619-d74216da-5606-4b4c-ba89-5f79366199db.png)
![Screenshot_20230218-233429_Obtainium](https://user-images.githubusercontent.com/92597054/219896629-91d76220-9814-452b-9818-9b5ceb6b12f0.png)
![Screenshot_20230218-233438_Obtainium](https://user-images.githubusercontent.com/92597054/219896634-e435f614-d469-4c4d-9d49-5f0ca5200e21.png)

**Comment by ImranR98** [comment]
Should be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.0-beta

**Comment by chris122380** [comment]
https://github.com/brave/brave-browser/releases is giving me Brave nighty. How do I have Obtainium give me Brave stable?
