### ISSUE TITLE
Chromium seems strange in app list

### ISSUE THREAD

**Issue by hariskar** [ImranR98/Obtainium#303]
After update to 0.11 in the list with installed apps Chromium from https://github.com/macchrome/droidchrome looks not good.
ByMacchrome is written vertically so Chromium entry is as big as 2-3 entries.

**Comment by BeautyyuYanli** [comment]
Same issue 

![Screenshot_20230220-041431_Pixel Launcher.png](https://user-images.githubusercontent.com/32453863/219972944-cce7ec29-1fdf-4c19-8b71-c49e3cc6cfc2.png)

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.1-beta
