### ISSUE TITLE
Lost connection not properly handled

### ISSUE THREAD

**Issue by Sertonix** [ImranR98/Obtainium#304]
When you download an update and your internet connection is lost the programm throws an error and the progress bar is stuck.
You have to restart the app to download it again.
You can test that by just turning of the internet.

I assume that fetching the latest versions could have similar problems but I don't know how to check that.

It would also be nice if a download could be continued and doesn't need to be restarted every time.

**Comment by ImranR98** [comment]
Auto-recovery is tricky - I don't see a way to do it using the existing plugin (don't know enough about networking to build a custom system). That said, the issue itself is now fixed in that the progress bar no longer gets stuck and you don't need to restart the app.
