### ISSUE TITLE
Apkmirror

### ISSUE THREAD

**Issue by VasilisPng** [ImranR98/Obtainium#307]
Hello, adding a download link always gets the latest and it's usually in an alpha version or a beta version. Can you somehow do version control only in stable version? Thank you very much for your work.

**Comment by ImranR98** [comment]
We can't automatically select releases for APKMirror for the same reason as why we can't for GitHub (see #20). Instead, there's now an option to filter releases using [Regular Expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) (like we already have for GitHub). A bit complicated since the user needs to know what RegEx to use, but it is the only reliable generalized method. For example, a RegEx to avoid any releases with `beta` in the title would be `^((?!beta).)*$`.

Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.1-beta

**Comment by VasilisPng** [comment]
In stable versions it doesn't say stable version next to the name like it does in alpha and beta. How do I filter for the stable? For alpha and beta I can filter.

**Comment by VasilisPng** [comment]
In stable versions it doesn't say stable version next to the name like it does in alpha and beta. How do I filter for the stable? For alpha and beta I can filter.

Στάλθηκε από την Αλληλογραφία<https://go.microsoft.com/fwlink/?LinkId=550986> για τα Windows

Από: Imran ***@***.***>
Αποστολή: Δευτέρα, 20 Φεβρουαρίου 2023 01:58
Προς: ***@***.***>
Κοιν.: ***@***.***>; ***@***.***>
Θέμα: Re: [ImranR98/Obtainium] Apkmirror (Issue #307)


We can't automatically select releases for APKMirror for the same reason as why we can't for GitHub (see #20<https://github.com/ImranR98/Obtainium/issues/20>). Instead, there's now an option to filter releases using Regular Expressions<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions> (like we already have for GitHub). A bit complicated since the user needs to know what RegEx to use, but it is the only reliable generalized method. For example, a RegEx to avoid any releases with beta in the title would be ^((?!beta).)*$.

Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.1-beta

**Comment by ImranR98** [comment]
> For example, a RegEx to avoid any releases with beta in the title would be `^((?!beta).)*$`.

**Comment by VasilisPng** [comment]
Any example with the facebook application? You can?

Στάλθηκε από την Αλληλογραφία<https://go.microsoft.com/fwlink/?LinkId=550986> για τα Windows

Από: Imran ***@***.***>
Αποστολή: Δευτέρα, 20 Φεβρουαρίου 2023 02:18
Προς: ***@***.***>
Κοιν.: ***@***.***>; ***@***.***>
Θέμα: Re: [ImranR98/Obtainium] Apkmirror (Issue #307)


For example, a RegEx to avoid any releases with beta in the title would be ^((?!beta).)*$.

**Comment by ImranR98** [comment]
I haven't tried it, but I think this will work: `^((?!beta|alpha).)*$`

**Comment by VasilisPng** [comment]
It worked! Thank you very much brother! I hope installing via apkmirror inside your app comes back sometime!

Στάλθηκε από την Αλληλογραφία<https://go.microsoft.com/fwlink/?LinkId=550986> για τα Windows

Από: Imran ***@***.***>
Αποστολή: Δευτέρα, 20 Φεβρουαρίου 2023 02:34
Προς: ***@***.***>
Κοιν.: ***@***.***>; ***@***.***>
Θέμα: Re: [ImranR98/Obtainium] Apkmirror (Issue #307)


I haven't tried it, but I think this will work: ^((?!beta|alpha).)*$
