### ISSUE TITLE
Always update available

### ISSUE THREAD

**Issue by xmha97** [ImranR98/Obtainium#308]
Always update available

![Screenshot_2023-02-20-01-24-55-269_dev.imranr.obtainium.jpg](https://user-images.githubusercontent.com/23485114/219977553-60fe7b26-3436-49e6-90b9-d7b56ec92cae.jpg)

https://github.com/RetroMusicPlayer/Paisa

Please fix this issue.

**Comment by ImranR98** [comment]
The Paisa app's latest release has the `v3.3.1` tag even though the App's actual version is `3.3.2`. Note that the tag is important, not the release title.

Not an Obtainium issue; needs to be fixed by the dev.
