### ISSUE TITLE
UI improvement for version detection options

### ISSUE THREAD

**Issue by markus-gitdev** [ImranR98/Obtainium#312]
Since it's now possible to use the release date as version, wouldn't it be better to have a dropdown, which has the 2 options "Use Release Date as Version" and "No version detection" combined?

I think about something like ...

Version detection:
- Use Version (which is the default option)
- Use Release Date (which is the option for the current setting "Use Release Date as Version")
- None (which is the option for the current setting "No version detection")

**Comment by ImranR98** [comment]
Good idea! Done: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.3-beta
