### ISSUE TITLE
[New source] Skyline emulator

### ISSUE THREAD

**Issue by sonalder-darlene** [ImranR98/Obtainium#315]
Skyline is a Free and Open Source Nintendo Switch Emulator for Android. The source code is available on GitHub but there is no APK in releases (at least for now)

Official website : https://skyline-emu.one/
Official GitHub : https://github.com/skyline-emu/skyline

APK download link : https://skyline-emu.one/download/

**Comment by ImranR98** [comment]
Releases on their download page are loaded in dynamically with JS, so we can't scrape the page normally.
