### ISSUE TITLE
Unable to install Organic Maps

### ISSUE THREAD

**Issue by Mortein** [ImranR98/Obtainium#317]
After adding [Organic Maps](https://github.com/organicmaps/organicmaps), and filtering to the "web" APK, I get the following error:

![Screenshot_20230222-215319.jpg](https://user-images.githubusercontent.com/1147858/220571157-4a00eba6-3d4f-4b1f-84e9-d916adce5188.jpg)

I'm using version 0.11.1 of Obtainium.

**Comment by ImranR98** [comment]
I can't seem to reproduce this. Could you let me know the exact steps followed? Also if possible, send the file in `/Android/data/dev.imranr.obtainium/files/app_data/<organic maps ID>.json`

**Comment by Mortein** [comment]
Hmm, in an attempt to document the process, I seem to have accidentally fixed the issue by clearing the cache for Obtainium.

I was switching from the F-Droid release.

**Comment by ImranR98** [comment]
That explains it. F-Droid Apps usually use a different package ID from non F-Droid releases, so you can't switch between them directly.
