### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by venkat2305** [ImranR98/Obtainium#319]
![Screenshot_2023-02-23-02-10-57-688_dev.imranr.obtainium.jpg](https://user-images.githubusercontent.com/55329452/220754036-f5737c94-ab8e-4340-8ef3-d1fc4f5a00e0.jpg)

The installed version is the latest but it's showing a previous version as the latest. I tried to install the update but it ended up installing the latest version, and then showing there's an update available

**Comment by ImranR98** [comment]
Please search for issues before creating new ones. See #308 and #310.
