### ISSUE TITLE
Consider accepting donations?

### ISSUE THREAD

**Issue by JaxiiRuff** [ImranR98/Obtainium#32]
I think you should consider enabling github sponsors! The rate of improvement on this app is incredible in such short time. Truly hope this becomes a respectable standard besides F-Droid repos.

Anyway, thanks for the hard work on this project.

**Comment by ImranR98** [comment]
Thanks for the kind words 🙂
I'll continue working on this app when I can, but donations would kinda add pressure so I'd rather not.
If you have money to give I'd suggest considering [GrapheneOS](https://grapheneos.org/) 🔥
