### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by venkat2305** [ImranR98/Obtainium#320]
![Screenshot_2023-02-23-02-26-02-077_dev.imranr.obtainium.jpg](https://user-images.githubusercontent.com/55329452/220757050-95ce4dcb-f543-4f85-b61a-7f21c25a1a70.jpg)

The app is showing the previous version as the latest one. It is downloading the previous version. I did include pre releases for this app

**Comment by ImranR98** [comment]
Note sure what's going on - I can't reproduce the issue on my end. Try removing the App and reinstalling it. Keep in mind that you can't update between pre-release and release versions for this App since they use different package IDs, so you'll have to use the release filter regular expression option to avoid errors. Let me know how it goes.

**Comment by ImranR98** [comment]
It's also possible that they posted v1.17.3 that you downloaded, then they deleted it - I don't see that version on the releases page.

**Comment by ImranR98** [comment]
Will reopen if this turns out to be an actual bug.

**Comment by venkat2305** [comment]
![Screenshot_2023-02-23-10-58-38-893-edit_com.github.android.jpg](https://user-images.githubusercontent.com/55329452/220827726-a96f0751-de44-4c2a-9e34-049b76cb3ddf.jpg)

https://user-images.githubusercontent.com/55329452/220827739-a7cc8145-59c2-4cda-b081-6b68c024c084.mp4

The latest version is 1.17.3 and I didn't include the pre-releases.

**Comment by venkat2305** [comment]
I removed the app and tried again. The latest version is showing as 1.17.2.
https://user-images.githubusercontent.com/55329452/220828284-40662f04-8bcb-4787-a41f-aaa52b4248e8.mp4

**Comment by ImranR98** [comment]
It's not on their releases page: https://github.com/mateusz-bak/openreads-android/releases

**Comment by venkat2305** [comment]
Do you mean 1.17.3 is not on the release page? I can see it on the release page.
