### ISSUE TITLE
Add 'Marked updated' button for all added apps.

### ISSUE THREAD

**Issue by soymadip** [ImranR98/Obtainium#322]
As of now, when obtainium finds a outdated 'track only' app, it shows a button to mark them as updated. 

But when we update a outdated app (not trak only) manually(like through the app's inbuilt update system), obtainium still shows update option to update them. Even if the app is already updated. 
![IMG_20230223_230405](https://user-images.githubusercontent.com/84225810/220985280-e3720f47-c572-4b0e-8df4-3d633634db9e.jpg)

- Now if 'mark as updated button is added for all apps, we can manually mark them as updated. 
- the above solution is my own preference, if there's any better fix, please do as you please 😅

**Comment by ImranR98** [comment]
App versions are supposed to be detected automatically but this fails for some apps with non standard versioning schemes. Use the 'disable version detection' toggle for such apps - then you should see an option to mark as updated.

**Comment by soymadip** [comment]
> App versions are supposed to be detected automatically but this fails for some apps with non standard versioning schemes. Use the 'disable version detection' toggle for such apps - then you should see an option to mark as updated.

Yeah I know but then if I want to update through obtainium, I can't update 😅

**Comment by ImranR98** [comment]
You're thinking of "Track Only". Use "no version detection" which is a separate toggle.
