### ISSUE TITLE
Improvement for App Sorting

### ISSUE THREAD

**Issue by markus-gitdev** [ImranR98/Obtainium#325]
![grafik](https://user-images.githubusercontent.com/82206269/221136793-3a6d2f9c-1f74-465b-978f-9639c411e276.png)

As shown in the screenshot, the drop-down arrow for ``appSortBy`` is slightly overlapping with the drop-down selection of ``appSortOrder``.
**NOT a functional issue**, but it doesn't look good.

I guess this is because ``releaseDate`` is in German too long for the field ("Veröffentlichungsdatum") and there is no good alternative to name it.

So my question is, if these fields could be set to dynamic width (to fit in combination the whole screen) or the fields could be set into own columns?

Best regards,
Markus

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.3-beta
