### ISSUE TITLE
Import from opml

### ISSUE THREAD

**Issue by ippocratis** [ImranR98/Obtainium#326]
I also have enjoyed and  Motivated from the  Side Of Burritos - You should use this instead of F-Droid | How to use app RSS feed YouTube video and I have been using rss readers as my app updates source
I have already manualy inserted my sources there and exported it as opml file.
It would make sense to have an option to insert into obtanium that opml source list exported from the rss reader. 
It will save me (or other users motivated from that great idea) a lot of time

**Comment by ippocratis** [comment]
A workraround a come up with is

`cat /sdcard/ReadYou.opml |grep -oP '(?<=htmlUrl=").*?(?=.atom")' > URL_list.txt`

And import as URL list in obtainium

**Comment by ImranR98** [comment]
Added a general feature to extract URLs from any file (including OPMLs): https://github.com/ImranR98/Obtainium/releases/tag/v0.11.3-beta
