### ISSUE TITLE
Update Checking is Broken for > 30 GitHub Apps

### ISSUE THREAD

**Issue by ImranR98** [ImranR98/Obtainium#33]
GitHub has a rate limit which causes updated checking to fail after roughly 30 Apps. This means there is no way to check for updates for Apps after the 30th one, as discussed in #6.

Fix to be implemented:
- Apps should store a "last update checked" date.
- When checking for updates, Apps should be sorted in order of least recently checked to most recently checked, so that the first 30 Apps checked are not always the same 30, but the 30 that haven't been checked for the longest time.
- When the user manually checks for updates, the current behaviour remains; they get an error message when the rate limit is reached. The difference being that when they do it again after 30 minutes, a different set of Apps will be checked.
- Background checking is more complicated as the 30 minute wait and retry should happen automatically, transparent to the user. Does Android allow for a "background task" to run for as long as it needs (hopefully) or is there a limit? Needs testing.

**Comment by S7venLights** [comment]
Does the background task need to run for that long or can it just be triggered by the next 'background update checking interval'
and continue where it left off.

**Comment by S7venLights** [comment]
I suppose it would be good to have a short description of this behaviour in the app. Perhaps in the settings menu. 
Something like: 

Due to Github limitations, update checks are every for 30 apps at a time, every 30 minutes.

**Comment by ImranR98** [comment]
It could continue where it left off, but the update checking interval may be a lot longer than the rate limit timeout. To check for updates for 65 apps for example, would take 3 days if the user has picked a 1 day interval, even though it could've been done in a couple of hours.

**Comment by S7venLights** [comment]
🤔 Or you could change the 'background update intervals' to say:

- Full update check cycle, three times a day, twice a day/once a day / every 2nd day. 

And adjust accordingly. 

- Alternatively have a dedicated Github update interval setting saying: 

Github collections over 30 apps have update check limitations, please choose a separate frequency for Github updates if you have more than 30 repos:

30 apps at a time every 30 minutes twice a day. 
etc. 

- Or simply have a tip under the 'background update interval' setting saying: 

For more than 60 Github apps, an update interval under 3 hours is recommended. Github only allows 30 update checks per 30 min.

**Comment by ImranR98** [comment]
I'd prefer to keep things simple; give the user easy settings and handle things in the background. But yeah if that doesn't work out then worst case scenario there will be a separate GitHub setting. But then any other sources with rate limits in the future would need their own thing with separate settings etc. so hopefully it won't go there.

**Comment by S7venLights** [comment]
I think option 1 will be the most simple (least confusing) interface for the user.

Then Obtanium just adjust the checking interval in the background according to how many Github apps a person has and the current rate limit.
The user doesn't need to do any math.

**Comment by Joshndroid** [comment]
Is it possible for those of us with a github account to oauth or something with github to login and get around the rate limit? (i am not sure how the limit works fully)

**Comment by ImranR98** [comment]
> Is it possible for those of us with a github account to oauth or something with github to login and get around the rate limit? (i am not sure how the limit works fully)

Should be possible, and I think that would give you a higher rate limit but haven't looked into it. You can make an issue for it if you want

**Comment by ImranR98** [comment]
For update checking, I didn't want to hardcode a specific number of Apps to process at a time as that number may change in the future (for example, if a user is using their own API token which is a potential feature that will be added), which is why I prefer to just sort them by last check date and then go through oldest -> newest until the rate-limit error is hit.

Similarly, the earlier suggestion of "full cycle 3 times a day, once a day, etc." is not what I'd prefer to do as you can't calculate those without knowing in advance how long the rate-limit timeout is. For GitHub right now, it's 30 minutes, but again hardcoding this is not a good idea as it can change in the future, and will be different for other rate-limited sources.

The best thing would be to update as many Apps as possible in order of oldest -> newest (could be 30 Apps, 60, anything) then, when a rate-limit is reached, we look at the number of minutes that the error from GitHub (or any source) tells us to wait, then wait for that exact number before trying again. These smaller "retry" tasks would be scheduled on an individual one-time basis whenever needed, from inside of the fixed-period "parent" task that the user sets to run every few hours or days. It has to be done this way because each task can only run for 10 minutes (Android's limit).

Unfortunately it looks like this is not possible to do with with the [Workmanager](https://github.com/fluttercommunity/flutter_workmanager) plugin. You cannot schedule another task from within an existing one, so there's no way to schedule a new "retry" task from inside the main update checking background task.

I've filed an issue with them (https://github.com/fluttercommunity/flutter_workmanager/issues/428), maybe it's possible and I don't know how. In the meantime, I've added a warning telling users that it may take several update cycles to check all Apps. The default 3 hour interval should be an okay compromise for most users.

**Comment by ImranR98** [comment]
Fixed in the latest release: https://github.com/ImranR98/Obtainium/releases/tag/v0.5.0-beta

**Comment by S7venLights** [comment]
Nice, how does one use the source-specific setting? Perhaps it needs to be more like a toggle of settings.

**Comment by ImranR98** [comment]
There's no new setting. Background update checking just waits for the specified time and try again if a rate limit is encountered. Foreground (manual) checking just shows you the error and expects you'll wait before trying again.
