### ISSUE TITLE
Move text of Uninstalled apps lacking icons to the same column as installed apps.

### ISSUE THREAD

**Issue by Toiletmason** [ImranR98/Obtainium#330]
It would make the app look cleaner. I understand rust uninstalled apps aren't going to have icons as they don't have anywhere to fetch them from. However, fixing the text can at least help clean up things.

**Comment by ImranR98** [comment]
Added a placeholder icon: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.6-beta
