### ISSUE TITLE
"Follow System" in language setting load missing assets

### ISSUE THREAD

**Issue by jojoto** [ImranR98/Obtainium#334]
device: Sony XA2 (H3113)
Rom: LineageOS 19.1 (pioneer - nightly) 
app ver: 0.11.4

Hello :wave: 
My phone is in French, therefore the app that doesn't have a French translation so it fallback to English. But if I change the language to anything else and then select "Follow System" again, it uses the system language "FR" but the asset doesn't exist and the app doesn't switch to English and instead displays an error message.

![Peek 27-02-2023 16-47](https://user-images.githubusercontent.com/29695477/221612138-8d1eb957-9f3a-4074-8725-b73b6cc2dc39.gif)

**Comment by jojoto** [comment]
Similar to #185 ?

**Comment by ImranR98** [comment]
Should be fixed now: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.5-beta
