### ISSUE TITLE
Problem with pre-release

### ISSUE THREAD

**Issue by blap** [ImranR98/Obtainium#339]
Example: [joplin-android](https://github.com/laurent22/joplin-android)
This github put pre-releases in "Tags" and not in "Releases". So the function to updates pre-releases do not work.
Another problem with this is if I install manually the pre-release, obtanium will try to get and install an anterior version from "Releases".

**Comment by ImranR98** [comment]
I don't see any prereleases on that repo. In any case, the pre-release toggle is meant to work with GitHub's standard prerelease indicator. If a developer uses their own non-standard approach, we can't support it (no consistency). You could try filtering by release title if possible.

**Comment by ImranR98** [comment]
Apparently a developer can create a tag and even attach an APK to it, without creating a release. I don't see a way in the API docs to get APKs for a non-release tag. Aside from that, supporting this would require doubling the number of API requests we make to GitHub and this would be an issue for users without an API key. Not worth it given this system is only used by a rare few apps.

For reference:
- API page for the App's tags (no APKs): https://api.github.com/repos/laurent22/joplin-android/tags
- API page for the App's releases (no way to include non-release tags): https://api.github.com/repos/laurent22/joplin-android/releases
- Similar but not identical to #137

Let me know if there's any API params or other tricks we could use, but as it stands this is not worth supporting.

**Comment by blap** [comment]
> Apparently a developer can create a tag and even attach an APK to it, without creating a release. I don't see a way in the API docs to get APKs for a non-release tag. Aside from that, supporting this would require doubling the number of API requests we make to GitHub and this would be an issue for users without an API key. Not worth it given this system is only used by a rare few apps.
> 
> For reference:
> 
> * API page for the App's tags (no APKs): https://api.github.com/repos/laurent22/joplin-android/tags
> * API page for the App's releases (no way to include non-release tags): https://api.github.com/repos/laurent22/joplin-android/releases
> * Similar but not identical to [App version issue #137](https://github.com/ImranR98/Obtainium/issues/137)
> 
> Let me know if there's any API params or other tricks we could use, but as it stands this is not worth supporting.

I can only think now in web scraping but it is not the best option.
Sorry.
