### ISSUE TITLE
Add Peach bitcoin as a new source

### ISSUE THREAD

**Issue by sonalder-darlene** [ImranR98/Obtainium#353]
Peach bitcoin have an APK on their website but it's not an open source app so no GitHub.

Website : https://peachbitcoin.com/
APK page : https://peachbitcoin.com/apk/

- Universal APK : https://download.peachbitcoin.com/apks/latest/app-prod-universal-release.apk
- ARM64-V8 APK : https://download.peachbitcoin.com/apks/latest/app-prod-arm64-v8a-release.apk

PlayStore : https://play.google.com/store/apps/details?id=com.peachbitcoin.peach.mainnet

**Comment by ImranR98** [comment]
Their website design already works with the HTML fallback source. Paste the APK page URL into Obtainium and give it a try (use the APK filter to select the right file).
