### ISSUE TITLE
Feature Request: Add app by Author/App shorthand

### ISSUE THREAD

**Issue by jinncarry** [ImranR98/Obtainium#355]
I would like to add sources by simply giving the author and project name. I have these two data in mind right before I open Obtanium, so it would be ideal if I could just enter: ImranR98/Obtainium and click Add

**Comment by ImranR98** [comment]
You'd still need to specify what source you're talking about since Obtainium supports many. I assume you mean GitHub, in which case the normal URL pattern is already very close to what you need; just type: `github.com/` before `Author/Name`.
