### ISSUE TITLE
Issues with some sources

### ISSUE THREAD

**Issue by E0697** [ImranR98/Obtainium#356]
If I try to add this app https://f-droid.org/packages/com.github.muellerma.coffee , it says "Not found".

And this one https://gitlab.com/cosmosapps/stealth , it says "No APK found"

**Comment by ImranR98** [comment]
Looks like this is not an Obtainium issue. For some reason, the API request for this app fails: https://f-droid.org/api/v1/packages/com.github.muellerma.coffee

That exact request ([as documented on their website](https://f-droid.org/docs/All_our_APIs/)) works for any other F-Droid app (for example https://f-droid.org/api/v1/packages/net.sourceforge.opencamera) so this is an F-Droid API issue.

**Comment by E0697** [comment]
I see. Thanks for clarifying!

**Comment by ImranR98** [comment]
Okay, looks like the second repo is due to a known limitation with GitLab. Duplicate of #3 (and #282).

Nothing Obtainium can do unless there is a way to get APKs from these kinds of repos.

**Comment by E0697** [comment]
Got it. Sorry about the duplicate!

**Comment by ImranR98** [comment]
Users with GitLab API keys should now be able to add the Stealth app: https://github.com/ImranR98/Obtainium/releases/tag/v0.13.16-beta
