### ISSUE TITLE
WhatsApp

### ISSUE THREAD

**Issue by xmha97** [ImranR98/Obtainium#357]
https://www.whatsapp.com/android

![Screenshot_2023-03-14-12-57-19-446_org mozilla fenix](https://user-images.githubusercontent.com/23485114/224957288-e345ab62-8eac-4064-bf5b-b0cf4e18052c.jpg)

**Comment by xmha97** [comment]
Ok, thanks for your reply.

**Comment by eylenburg** [comment]
Hi, I have an idea. Would it be possible to follow Whatsapp on APKMirror and whenever a (non-beta) update is found on APKMirror, then Obtainium will go and download the latest APK from the Whatsapp website? I think it's worth building in such a workaround for Whatsapp because it's one of the most popular apps.

**Comment by xmha97** [comment]
> Hi, I have an idea. Would it be possible to follow Whatsapp on APKMirror and whenever a (non-beta) update is found on APKMirror, then Obtainium will go and download the latest APK from the Whatsapp website? I think it's worth building in such a workaround for Whatsapp because it's one of the most popular apps.

Good idea but usually the version of WhatsApp on site is not the same as the latest version of WhatsApp in APKMirror.

![PhotoGrid_1681476076793.jpg](https://user-images.githubusercontent.com/23485114/232047148-6c4db73a-715d-4502-8d88-2072d7ac8aa0.jpg)

**Comment by kneejuicer** [comment]
It seems that the APK on their website is now up to date. The version on the website (2.23.11.78) seems to be the same as the latest version on APKmirror. It is even newer than the version on Google Play (for my device anyway - 2.23.11.77)

**Comment by ImranR98** [comment]
@kneejuicer checked today, the version on their website is still out of date. But I did get this suggestion via email:

> I know you looked at WhatsApp support before. It should be feasible to add now. I am reading that some WhatsApp users are having issues if they don't obtain the APK through the official Google Play Store client or through the official APK on their site. It would be great to see support for the WhatsApp official APK in Obtainium. Here is the feature request:
> 
> **Prerequisites**
> This request was previously created as #357 and closed because of issues with detecting version numbers. With a hashed URL approach similar to what is added in #630, it is now possible to add WhatsApp support to detect new versions.
> 
> **Describe the feature**
> The WhatsApp APK is available for download from the [WhatsApp website](https://www.whatsapp.com/android). The APK is served using WhatsApp CDN. With the CDN query parameters removed, the download URL looks like this:
> 
> `https://scontent.whatsapp.net/v/t61.25591-34/379811005_1686747128506680_3720520979901344336_n.apk/WhatsApp.apk`
> 
> The _full_ WhatsApp link has a variety of CDN query parameters appended. You can see an example on the WhatsApp Android download site. For example there are `oh` and `oe` query parameters which represent URL signature and URL signature expiration. More details about those are in this [blog post](https://ysamm.com/?p=404). By itself, that URL without CDN query parameters is not valid for actually downloading the APK because the query parameters have the required URL signature.
> 
> Some of those query parameters (such as oh) will change even for the same version. This can be seen by loading the WhatsApp Android download page in two separate browsers. Even though the query parameters may change, the main part of the URL does not change for a specific version.
> 
> If the query parameters are ignored entirely, a hashed URL approach of the rest of the WhatsApp download link can be used as a track-only version detection source.
> 
> To enable both track-only and downloading, the download link without CDN query parameters can be used for new version detection and the full URL with query parameters can be used to perform an actual download.
> 
> Many thanks

**Comment by ImranR98** [comment]
Forgot to close this issue earlier (was resolved in https://github.com/ImranR98/Obtainium/releases/tag/v0.14.24-beta).

**Comment by xmha97** [comment]
Thanks 🙏
