### ISSUE TITLE
Removed App Returns "Once"

### ISSUE THREAD

**Issue by NaeemBolchhi** [ImranR98/Obtainium#359]
I've had this issue a few times, though I haven't tried reproducing it for reference.

If I delete an app that I installed via Obtainium (from phone settings or another app manager), it is listed as an app I can install again on Obtainium. Great. Makes sense.

So I choose to remove the app from Obtainium as well, and it goes away at first. If I immediately do a swipe down for refresh of the app list, the removed app magically comes back on the list. If I remove it once again, it doesn't come back a second time.

I hope I explained that right.

**Comment by ImranR98** [comment]
Can't seem to reproduce this on my end.

**Comment by NaeemBolchhi** [comment]
Nothing else, sorry. I tried doing it again and it's not happening, so maybe just me. Will comment if it happens again.

**Comment by ImranR98** [comment]
Think I know what may be causing this. Not exactly what you described, but if I open an App's detail page and hit "Remove" quickly, it comes back. I think what's happening is that when you open the detail page, Obtainium checks for updates in the background for that App. If you remove it before the update check is done, the update check completes and recreates the entry. Will confirm if this is what's happening and fix it.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.11.14-beta
