### ISSUE TITLE
Issues with f-droid labelling link as 'not a valid FDroid app URL'

### ISSUE THREAD

**Issue by Joshndroid** [ImranR98/Obtainium#36]
I have a few fdroid apps added however some of them are not being accepted as a valid link

https://f-droid.org/packages/at.bitfire.davdroid/
https://f-droid.org/packages/us.spotco.fennec_dos/

**Comment by ImranR98** [comment]
I thought f-droid links always had a language code in the url, guess not. Will fix in the next release. In the meantime, add a language code after `.org/`, like https://f-droid.org/en/packages/at.bitfire.davdroid/

**Comment by Joshndroid** [comment]
Thanks, trying not to spam with issues but also trying to help with things being a user since your first release.

**Comment by ImranR98** [comment]
Fixed in the latest release: https://github.com/ImranR98/Obtainium/releases/tag/v0.5.0-beta
