### ISSUE TITLE
Regex Fails Sometimes?

### ISSUE THREAD

**Issue by NaeemBolchhi** [ImranR98/Obtainium#360]
For reference, I faced the issue on this repo—
https://github.com/NoName-exe/revanced-extended

It contains three apk files, and I use `all` as regex to catch the apk for ReVanced Extended. Even though this regex clearly matches an apk, Obtainium showed no apk matches on two different devices I tried this on.

To reproduce the issue, I believe you have to add the regex before clicking the "Add" button, on your very first try. If you click add without any regex, you get the choice list, and if you cancel the choice and then add the regex, it works normally.

I assume, if I already know what regex to use, and Obtainium hasn't touched that link yet, adding the regex on the first try fails. It eventually works after a few restarts of the app though.

**Comment by ImranR98** [comment]
Can't reproduce. Is this what you're doing?
https://user-images.githubusercontent.com/30463115/226030768-a4ab686d-2cd9-4ec2-81b0-757f40560f89.mp4

**Comment by NaeemBolchhi** [comment]
That is what I was doing, yes. If the issue isn't reproducible, then maybe not everyone will be facing it anyway. Let's close this for now and I'll get back if it happens to me again and I know more about what's going on.

**Comment by deadcombo** [comment]
Hello,

Also suffering from this on certain apps.

https://github.com/Livinglist/Hacki

In this I added app-arm64-v8a-release.apk to the filter and get back 'Could not find a suitable release' even though that's the exact name of the apks

**Comment by NaeemBolchhi** [comment]
Hi @deadcombo. Try adding a smaller part of the file name as regex first. For that file name, either `v8a` or `arm64` should work. Best of luck.

**Comment by deadcombo** [comment]
Yep, started with those, same result.

**Comment by ImranR98** [comment]
@deadcombo that regex with that repo does work for me. I'm guessing you're using the release title filter instead of the APK filter, which is a separate field below the version detection dropdown.

**Comment by deadcombo** [comment]
Indeed I am, I'm very sorry to disturb you with lack of reading. 

Thank you for the help and great project.

**Comment by Julian-1-2-3-4-5** [comment]
had the same problem, also didn't realize there was another field for apk title, Thank you
