### ISSUE TITLE
Duplicate Downloads, Name Errors

### ISSUE THREAD

**Issue by NaeemBolchhi** [ImranR98/Obtainium#361]
Sometimes, clicking the update button doesn't immediately start a download. That seems to be the case for me on [this repo](https://github.com/NoName-exe/revanced-extended/).

The download button doesn't really go away, so I just think the click didn't work. I tap it a few times for good measure, and now I have Obtainium downloading the same file multiple times, all hogging my bandwidth, slowing down the downloads.

At the end of it all, if I wait patiently, I'll get a bunch of errors telling me something about names. I suppose that's because the first download to finish already put the apk there, and downloading the same thing again can neither replace that, nor have a numbered name for duplication.

But at least one download works, which lets me update the app.

I figure that this could be easily solved if the download/update button/icon disappeared after the first click and was replaced with a "trying" or "buffering" or "loading" icon. Like those dots that go round and round.

This should tell the user that their click has been registered and that Obtainium is trying to start the download.

**Comment by ImranR98** [comment]
Install/update button should now be greyed out immediately - no change to press more than once: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.9-beta
