### ISSUE TITLE
VideoLAN (VLC) website not working as app source

### ISSUE THREAD

**Issue by wqp53625** [ImranR98/Obtainium#367]
Hi @ImranR98 ,

Thanks a lot for this useful app.

There is an issue when trying to add the following URL as an app source:

* https://www.videolan.org/vlc/download-android.html

Using this URL does not seem to work in Obtainium, even though the webpage has a download link to the VLC APK.

Using the following URLs also does not seem to work:

* https://get.videolan.org/vlc-android
* https://get.videolan.org/vlc-android/3.5.3

Regards

**Comment by ImranR98** [comment]
That link doesn't end with `.apk` so Obtainium doesn't recognize it (see https://github.com/ImranR98/Obtainium/issues/262#issuecomment-1419725658). Even if it did, the link doesn't work directly - it takes you to a mirror page.

VLC has been added as its own Source: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.12-beta
