### ISSUE TITLE
[Feature Request] Protocol for Importing Apps through Links

### ISSUE THREAD

**Issue by NaeemBolchhi** [ImranR98/Obtainium#368]
Can we have a protocol for Obtainium (like `mailto:` or `magnet:`) that will open a link directly in Obtainium and import the supplied JSON as a backup to be restored? I want to create an app gallery type website where users can select apps from my collection to dynamically create a backup json and import it in Obtainium in one click without needing to download it and place it somewhere in their internal storage first.

I think it's already possible for Android apps to overtake certain URLs and open them as the default app (like how YouTube takes over youtube links). So, could Obtainium catch special links like `obtainium:{["JSON"]}` and use the JSON as a backup file on the fly?

**Comment by zachatrocity** [comment]
@ImranR98 are you open to contributors? I'd like to implement this capability. Mostly cause I want "get it on obtainum" links in my repo instead of dealing with fdroid:

![image](https://github.com/ImranR98/Obtainium/assets/6200670/434aa28c-7f14-43b4-8146-3ea2ae13f807)

Do you have any specifics for how you'd like this implemented?  Would [uni_links](https://pub.dev/packages/uni_links) fit the bill?

**Comment by ImranR98** [comment]
Yes, any contributions are welcome. Not sure about that plugin though, it hasn't been updated in 2 years.

**Comment by zachatrocity** [comment]
https://pub.dev/packages/uni_links/score

If it ain't broke ya know?

**Comment by ImranR98** [comment]
@zachatrocity sorry, missed your reply somehow.

This has been implemented in the latest release: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.37-beta

Both these types of links should work:

- [obtainium://add/github.com/ashinch/readyou](obtainium://add/github.com/ashinch/readyou)
- obtainium://app/%7B%22id%22%3A%22me.ash.reader%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2FAshinch%2FReadYou%22%2C%22author%22%3A%22Ashinch%22%2C%22name%22%3A%22ReadYou%22%2C%22latestVersion%22%3A%220.9.8%22%2C%22apkUrls%22%3A%22%5B%5B%5C%22ReadYou-0.9.8-84156d2.apk%5C%22%2C%5C%22https%3A%2F%2Fapi.github.com%2Frepos%2FAshinch%2FReadYou%2Freleases%2Fassets%2F108404529%5C%22%5D%5D%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Afalse%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionDetection%5C%22%3A%5C%22standardVersionDetection%5C%22%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%7D
