### ISSUE TITLE
About changelog

### ISSUE THREAD

**Issue by BabyOilJohnson** [ImranR98/Obtainium#369]
It's about the `<br>`

![Screenshot_20230319-183535](https://user-images.githubusercontent.com/101601874/226177357-17bb1c06-94e1-4373-8139-d25eeb3b73b2.png)

By the by thanks for added this feature 👍

**Comment by NaeemBolchhi** [comment]
I guess the markdown isn't being translated.

**Comment by ImranR98** [comment]
Changelogs are now rendered as MarkDown: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.12-beta

Keep in mind this won't fix the `<br>` as that is not standard MarkDown (though a lot of MarkDown renderers support it - the Flutter one doesn't). But actual MarkDown formatting should display correctly.

**Comment by NaeemBolchhi** [comment]
Can't you just catch `<br>`, `<br/>`, and `<br />` and replace them with a line break before translating the markdown with the flutter plugin?

**Comment by ImranR98** [comment]
I'd rather not. There's always edge cases like if the `<br>` is part of a code block, for example.
