### ISSUE TITLE
Allow editing of Custom Name/Repo for apps after initial adding/import

### ISSUE THREAD

**Issue by Joshndroid** [ImranR98/Obtainium#37]
Please allow the ability to change the name or repo link for apps already added. 
At present it appears you need to delete the app from obtanium and then readd it to be able to change these.
I see the feature is there for when you add the app at present however there is no way to edit it later.
I assume the edit button could be added to where the trash/download/share icons are as there appears to be enough space/padding.

**Comment by ImranR98** [comment]
Added in the latest release: https://github.com/ImranR98/Obtainium/releases/tag/v0.5.0-beta
