### ISSUE TITLE
Integrate UnifiedPush as a notification option

### ISSUE THREAD

**Issue by Mr-Bajs** [ImranR98/Obtainium#379]
Would be great UnifiedPush would be integrated as an notification option for this app.
https://github.com/UnifiedPush

Unified Push is an tool that's FOSS and possibly selfhosting notifications provider, more or less an FOSS-replacement for Googles notifications. Having each app that doesn't relies on Googles notifications has to check for notifications them selfs, that drains battery. That's why apps in ineed of notifications that doesn't rely on google should use UnifiedPush for the sake of privacy AND batterypower.
That's atleast my understanding.

Hope you atleast could check it out.

**Comment by ImranR98** [comment]
This is only useful for push notifications that need to be sent to your device from elsewhere. Obtainium's notifications are all local - generated on your device only.

Obtainium doesn't have any server/backend component at all.

**Comment by Mr-Bajs** [comment]
Ah okey. 
So it doesn't check for updates in realtime. It's checks in the timely manner that you set in the app. Ofcourse.

**Comment by ImranR98** [comment]
That's right. Realtime notifications would have to be supported by the source services themselves (like GitHub).

**Comment by bingoxo** [comment]
> That's right. Realtime notifications would have to be supported by the source services themselves (like GitHub).

GitHub offers rss feeds and email notifications for releases 

the best way i can think of it to handle this is have a server listening for those notifications and pass them to obtainium

pros : 
faster/instant updates
no background polling which should be better for battery life

cons :
relying on a extra(failure) point 

i think it's a great idea especially if made optional
