### ISSUE TITLE
Obtainium should reopen after updating itself

### ISSUE THREAD

**Issue by Kreuger** [ImranR98/Obtainium#381]
If there are multiple updates, sometimes Obtainium will update itself but then the app doesnt reopen and continue with the rest of the updates.

**Comment by ImranR98** [comment]
This has been discussed before - see #84 and #118. It's part of #99 and blocked for now. The workaround would be to add a delay after bringing up the obtainium prompt (which I did) but I guess the delay isn't long enough. Will increase it in the next release and close this issue but #99 remains open until a proper fix.

**Comment by ImranR98** [comment]
Actually the delay is already half a second, which should work most of the time. Not worth increasing the delay for this workaround - better to focus on an actual fix (synchronous installs) in #99.

**Comment by BHydden** [comment]
#99 has been merged but Obtainium still doesn't reopen after updating itself. Could this issue be re-opened? Or should a new one be started?

**Comment by ImranR98** [comment]
As far as I know it is not possible for apps to open themselves

**Comment by BHydden** [comment]
I thought it was a thing I had seen stores do in the past but now I'm doubting my memory. I'll keep an eye out going forward.

**Comment by Kreuger** [comment]
Im pretty sure if you update NeoStore from in itself, it reopens.

**Comment by BHydden** [comment]
I have a feeling Accrescent does too... but I'm waiting for the next update to confirm.
