### ISSUE TITLE
Handshake error in client

### ISSUE THREAD

**Issue by flufficat** [ImranR98/Obtainium#383]
Version: v0.11.13-beta and v0.11.12-beta
Steps to reproduce:
1: press update button
2: select version, press continue
3: the error appears

The error has happened with Obtainium and Bitwarden
After a few tries Bitwarden did update, I updated Obtainium from the GitHub .apk

I have attached a screenshot of the error from Bitwarden
<br></br>
<img src="https://user-images.githubusercontent.com/112202351/227642547-61882add-d543-48bb-b835-dabccaf1ccd7.png" width="300"/>

**Comment by ImranR98** [comment]
Is this on Android 7 or older?

**Comment by flufficat** [comment]
Android 13
LineageOS

**Comment by ImranR98** [comment]
Closing as duplicate of #375 (open).
