### ISSUE TITLE
Storage Permissions not asked for so cannot Export

### ISSUE THREAD

**Issue by tquest1** [ImranR98/Obtainium#385]
I have version 0.11.14 running on GrapheneOS. I can't export due to storage permissions but none were asked for. How can I add the permssions?

**Comment by basiljelly** [comment]
By default, the export goes to your Download folder. No additional permissions are needed.

https://grapheneos.org/usage#storage-access

Without any storage permission, an app is allowed to:
create media files in standard directories (audio in Music/, Ringtones/, etc, images in Pictures/ and DCIM/, videos in DCIM/ and Movies/)
create files of any type (both media and non-media) in Documents/ and Download/
create new directories inside standard directories
rename/delete files that were created by the app itself
rename/delete directories if it can rename/delete all files within those directories

**Comment by ImranR98** [comment]
Yes, you could try allowing all permissions manually in the App's settings but it shouldn't be needed. What Android version are you on? And what do you see when clicking the export button?

**Comment by tquest1** [comment]
I'm on Android 13, latest grapheneos build, pixel 6a. 
![Obt-error](https://user-images.githubusercontent.com/43093959/227791378-b38df945-c708-4ae5-8903-f5622b46ed22.jpg)

**Comment by tquest1** [comment]
> Yes, you could try allowing all permissions manually in the App's settings but it shouldn't be needed. 

There are no permissions that are Not allowed in the App permission settings so I can't add storage permissions.

**Comment by ImranR98** [comment]
> I'm on Android 13, latest grapheneos build, pixel 6a.

Weird. I'm also on GOS 13, I can't think of why it wouldn't work. Does the Download folder exist on your phone (I know it's a default folder, but who knows)?

**Comment by jacobranson** [comment]
I am seeing the same thing on GOS for what its worth. Even a fresh install, same thing.

**Comment by ImranR98** [comment]
Yep, I also get this on a fresh second profile, but not on my main profile (even when I uninstall/reinstall Obtainium). Makes no sense and seems to be GrapheneOS specific.

**Comment by ImranR98** [comment]
I've added a workaround in the latest version: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.21-beta

If the Downloads folder can't be accessed, it will fall back to Obtainium's internal directory (`Android/data/dev.imranr.obtainium/files`). Less convenient for the user, and the files will be lost if Obtainium is uninstalled, but at least it works.

Unless someone reports this on AOSP (or I can replicate it there), I'll assume it's a GOS-specific bug and close the issue.
