### ISSUE TITLE
Support for "Protonmail"

### ISSUE THREAD

**Issue by Mightyretro** [ImranR98/Obtainium#389]
Hi.

is it possile to add Protonmail APK https://proton.me/mail/download

// Retro

**Comment by ImranR98** [comment]
Hi,
I don't see the app version listed on the page - the source can't be added without it.

Either way, web scraping is unreliable and i don't see the point of adding this as a source when the protonmail APK is already available on their github: https://github.com/ProtonMail/proton-mail-android/releases
