### ISSUE TITLE
[Feature Request] Visual indicator for apk names

### ISSUE THREAD

**Issue by p1gp1g** [ImranR98/Obtainium#390]
Apk names are usually something like `name-arch-vxx.yy.zz.apk`. It will be great to have a visual indicator to easily spot the one to install.

Here is a solution I have in mind:
- Color letters in common with the previous name.
- Highlight the apk if the name is the exact same (useful for app that does not include the version - like obtainium does).

As an example, it would be like this for obtainium:

![image](https://user-images.githubusercontent.com/31284753/227806672-e54d496d-e483-4495-b5bb-df528ef3f126.png)

**Comment by ImranR98** [comment]
Not sure what the point of this would be. APK names have no consistency between apps/devs and the APK to install is determined by the user (depending on device architecture, f-droid vs. google play build, etc.). So I'm not sure what criteria we'd use to highlight a specific APK or why differences in names matter.

**Comment by ImranR98** [comment]
For context, see #5 and #96.

**Comment by ImranR98** [comment]
Note that the APK picker already pre-selects whichever APK the user picked previously (by position in the list), and there's an APK filter option to bypass having to pick manually.

**Comment by p1gp1g** [comment]
> APK names have no consistency between apps/devs and the APK to install is determined by the user (depending on device architecture, f-droid vs. google play build, etc.). So I'm not sure what criteria we'd use to highlight a specific APK or why differences in names matter.

That is why I suggest to highlight letters in common with the previously installed apk 's name.

**Builds with constant names**

If I have previously installed 'app-foss-arm64-v8a.apk', a visual indication showing it matches exactly the previous name would help to know we already did the choice.

**Builds with a variable in the name**
*The variable is usually the version*

When the app name contain the version : compare letters in common in both directions. Highlighting common letters + the build with the maximum letters in common.

For instance  with molly builds. If I have installed **Molly-v6.11.7-1-FOSS.apk**, the next 2 builds are:
* __Molly-v6.1__ 4.5 __-1-FOSS.apk__ (21 in common : build highlighted)
* __Molly-v6.1__ 4.5 __-1.apk__ (16 in common)
