### ISSUE TITLE
[UI Bug] Add App page can't scroll to end.

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#392]
When adding a new app to Obtainium, the categories section is just out of reach when scrolling down. 
The bottom menu covers it.

**Comment by ImranR98** [comment]
What's your device's screen size and resolution?

**Comment by S7venLights** [comment]
Hi it's a pixel 3 but I remember I set a custom display size (maximum width 432) in Developer options, perhaps that's why, I can test in the morning…

**Comment by ImranR98** [comment]
Is it morning yet 🫠

Found the problem - this should now be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.23-beta

**Comment by S7venLights** [comment]
Oh sorry, haha thanks
