### ISSUE TITLE
Third party F-Droid repos

### ISSUE THREAD

**Issue by Sir-Photch** [ImranR98/Obtainium#393]
Not every third party f-droid repo obeys `/fdroid/<word>`.

For example: https://fluffychat.im/repo/stable/repo/
Is a valid fdroid-repository, but obtainium falls back to html.

**Comment by ImranR98** [comment]
Yes, this is the downside of trying to automatically determine the source based on user input. Eventually we'll need to have a dropdown that can be used to manually override the source. Will be done as part of #271.

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.12.0-beta

When the URL you enter is not recognized, Obtainium will fallback to the HTML source as usual but you now get a dropdown to override the source manually.

**Comment by Sir-Photch** [comment]
great stuff!
