### ISSUE TITLE
AntennaPod GitHub source - wrong latest version

### ISSUE THREAD

**Issue by yannikreiter** [ImranR98/Obtainium#396]
I added the AntennaPod app to Obtainium:
https://github.com/AntennaPod/AntennaPod/releases
The latest version that is available in GitHub currently is 2.7.1. The latest version that is picked up by Obtainium is 1.0

**Comment by ImranR98** [comment]
Look at the releases page - 1.0 is the latest version with an actual APK attached. Dev hasn't attached an APK to 2.7.1 so Obtainium falls back to an older release.
