### ISSUE TITLE
Mullvad Source doesn't work anymore

### ISSUE THREAD

**Issue by muznyo** [ImranR98/Obtainium#399]
When i try to add Mullvad in Obtainium, it shows this:

 ![Screenshot_20230330-153439_Obtainium.png](https://user-images.githubusercontent.com/24987471/228853286-ef4c574a-68e9-4024-a051-2735177ff578.png)

**Comment by ImranR98** [comment]
Yes, this is due to a slight change in their website design. Will be fixed in the next release.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.16-beta
