### ISSUE TITLE
Cant add Gitlab repos

### ISSUE THREAD

**Issue by Kreuger** [ImranR98/Obtainium#4]
I tried to add a couple of repos from Gitlab and it tells me there is no APK.

[Medilog](https://gitlab.com/toz12/medilog) very clearly has apks on their release page. And I just realized that the other one I tried does not have up to date releases on their page.

**Comment by ImranR98** [comment]
The Medilog release is not hosted on GitLab, so Obtainium failed to find it since it only looks for APKs uploaded to GitLab. This is fixed in the latest release - externally hosted APKs can now be picked up, and the user is warned about this and asked for additional confirmation on install.

**Comment by Kreuger** [comment]
Forgive me as Im a little confused. [The release page](https://gitlab.com/toz12/medilog/-/releases) has APKs right on it. Is that not hosted on Gitlab? Anyways Im glad you have a way around this. Just want to understand it better.

**Comment by ImranR98** [comment]
Yes, the APK on the release page links to a different website, you can hover the mouse over it (or long press on it on mobile) to see the url goes to https://zell-mbc.com/documents/app-release.apk.

**Comment by Kreuger** [comment]
Thanks!

**Comment by ImranR98** [comment]
See issue #697

Adding an API key will improve Obtainium's ability to find APKs. This probably needs to be better communicated in the app itself somehow.

**Comment by cloudlena** [comment]
Thanks, @ImranR98!
