### ISSUE TITLE
Bug: App doesn't find apks in Gitlab when under 'other'

### ISSUE THREAD

**Issue by Universal-Igloo** [ImranR98/Obtainium#41]
When I try to add the Ultrasonic gitlab repo (https://gitlab.com/ultrasonic/ultrasonic) to Obtainium, it says "No APK found". Whereas the repo does have APK files under releases. See screenshots below:

![Screenshot_20221003-155837](https://user-images.githubusercontent.com/95539123/193557573-aa35202e-a1af-4a0d-aadf-8a43ea892c8f.png)

![Screenshot_20221003-155830](https://user-images.githubusercontent.com/95539123/193557610-b1a5fecd-677c-4c0f-840c-837ca1472b50.png)

**Comment by ImranR98** [comment]
Users with GitLab API keys should now be able to add this app: https://github.com/ImranR98/Obtainium/releases/tag/v0.13.16-beta
