### ISSUE TITLE
Support F-Droid Cloudflare Mirror

### ISSUE THREAD

**Issue by NaeemBolchhi** [ImranR98/Obtainium#418]
Please add support for this mirror.
https://cloudflare.f-droid.org/
https://cloudflare.f-droid.org/en/

**Comment by ImranR98** [comment]
Any reason to use this over the regular f-droid?

**Comment by NaeemBolchhi** [comment]
Regular fdroid is slow in my region. I get better download speeds from this mirror.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.11.23-beta
