### ISSUE TITLE
Improve search(?)

### ISSUE THREAD

**Issue by martin-braun** [ImranR98/Obtainium#419]
Great app and useful to get rid of F-Droid in the long run. Thanks for making this.

However, today I noticed that I won't find `https://gitlab.com/AuroraOSS/AuroraStore` when searching for `auroraoss/aurora`, so I guess the search does not compare the string with the URLs as well?

This would be handy if you know the URL, but don't like to type it.

Thanks.

**Comment by ImranR98** [comment]
Search only works for supported sources which are listed as `(Searchable)`.

**Comment by martin-braun** [comment]
@ImranR98 My bad, I kinda failed to recognize that GitLab is not in the searchable sources when I made this issue.
