### ISSUE TITLE
Feature request: Option to open releases/changelog page directly for every app that has an update available

### ISSUE THREAD

**Issue by Universal-Igloo** [ImranR98/Obtainium#42]
It's always helpful to see what new changes are in the app, the current flow for me is to open the app page on obtainium, click on the repo link, scroll all the way down in the repo, click releases, read changes.

An option to open releases/changelog page directly for every app that has an update (of just every app in general) would be great.

Thoughts?

**Comment by S7venLights** [comment]
+ Not an immediate need, but I would use this feature, perhaps it could be implemented as a button that says changes, next to apps that say the update available EG display: 

Obtanium___________[Update Available] 
By ImranR98___________[See Changes]

**Comment by ImranR98** [comment]
How about if the 'Update Available' button is a clickable link (underlined/coloured to indicate this)? I'd rather not clutter the UI with more buttons.

**Comment by ImranR98** [comment]
Added in https://github.com/ImranR98/Obtainium/releases/tag/v0.5.5-beta

Ended up going with the initial suggestion of a separate 'See Changes' link as that is clearer (a link saying 'Updates Available' might be confused for an update button).
