### ISSUE TITLE
Allow to edit app's name, installed version 

### ISSUE THREAD

**Issue by Lapse176** [ImranR98/Obtainium#420]
I want to track ticktick app through apkmirror source but the name was like this. 
![Screenshot_20230404-204419.jpg](https://user-images.githubusercontent.com/119111604/229813170-8d02ec2e-c2a3-4e38-a98a-058e1b3eecea.jpg)
If possible please add app's icon for this source too.

**Comment by ImranR98** [comment]
You can now override the App name: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.23-beta

Adding an icon is not feasible.
