### ISSUE TITLE
Do not show archived repositories

### ISSUE THREAD

**Issue by martin-braun** [ImranR98/Obtainium#421]
The search term `opencontacts` will try to suggest to use `https://github.com/sultanahamer/OpenContacts`, which has been archived in favor of `https://gitlab.com/sultanahamer/OpenContacts`.

**Comment by ImranR98** [comment]
Archived repos are now labelled as such (not removed as a user might still want an archived app): https://github.com/ImranR98/Obtainium/releases/tag/v0.11.23-beta

**Comment by martin-braun** [comment]
This is a good compromise, good job @ImranR98.
