### ISSUE TITLE
Support searching on Gitlab

### ISSUE THREAD

**Issue by martin-braun** [ImranR98/Obtainium#422]
It would be very handy.

**Comment by ImranR98** [comment]
I've looked into this before and I remember not being able to find a public search API for Gitlab. Can't use web scraping either as they use js (even if we could, I prefer to minimze web scraping). Will reopen if a solution is proposed.

**Comment by martin-braun** [comment]
@ImranR98 Hey no problem, I understand that. Shouldn't we leave this issue open anyways? It will just be dependent on Gitlab, but we should not forget about that. I might reach out to Gitlab and will refer this issue. They should absolutely provide a search API.

Is [this](https://stackoverflow.com/questions/65680355/gitlab-api-search-project) only for self-hosted and Enterprise?

**Comment by ImranR98** [comment]
Following up on this, looks like the API needs a key: https://docs.gitlab.com/ee/api/search.html

Definitely doable.

**Comment by martin-braun** [comment]
> You can create as many personal access tokens as you like.
> 
> - In the upper-right corner, select your avatar.
> - Select Edit profile.
> - On the left sidebar, select Access Tokens.
> - Enter a name and optional expiry date for the token.
> - Select the [desired scopes](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#personal-access-token-scopes).
> - Select Create personal access token.

Source: https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#create-a-personal-access-token

So, you could allow to save the personal access token in the settings of your app and it could work out. Nice!

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.0-beta
