### ISSUE TITLE
Cannot remove app from app list

### ISSUE THREAD

**Issue by Zumux** [ImranR98/Obtainium#427]
I am trying to remove Mullvad VPN from my app list. After clicking the remove button it appears to be removed until the app is closed and reopened and it reappears. From my limited testing this seems to be happening exclusively to the Mullvad VPN.

**Comment by Anvil5465** [comment]
I've been having this issue for weeks. Usually I'm eventually able to delete the app from the list after a few tries, but at the moment there's an app in my list that I've deleted many times over the past couple weeks to no avail.

**Comment by E0697** [comment]
This keeps happening for me.
I have to remove an app multiple times until it's finally gone for good.

**Comment by E0697** [comment]
I use RealmeUI, Android 12.

**Comment by ImranR98** [comment]
Is there any difference between deleting from the main list vs. the app detail page? Also do you usually uninstall at the same time as delete?

**Comment by E0697** [comment]
I haven't tried it extensively but I think deleting from the app list works properly. (Will test and report back). Most of the time yes, I uninstall the app when removing.

**Comment by 1xFF** [comment]
I may have been able to replicate this bug. I got it to happen by uninstalling mullvad through its app settings and not obtainium, then quickly clicking the remove button before obtainium detects it's no longer installed.

That wont happen if you stay on the app page until the app icon disappears or if you uninstall the app through obtainium.

**Comment by ImranR98** [comment]
Latest release contains a potential fix by @1xFF: https://github.com/ImranR98/Obtainium/releases/tag/v0.13.14-beta
Will close this issue in a week or so if no one reports it still happening.

**Comment by 1xFF** [comment]
@ImranR98 Probably safe to close
