### ISSUE TITLE
sorry, but how does adding an app in the telegram app work?

### ISSUE THREAD

**Issue by speedlorenzo12** [ImranR98/Obtainium#428]

**Comment by NaeemBolchhi** [comment]
Write `telegram.org` in the URL section of the Add App page.

**Comment by speedlorenzo12** [comment]
A video for example?

**Comment by NaeemBolchhi** [comment]
![ZomboMeme 05042023174800](https://user-images.githubusercontent.com/42773187/230071460-83a4f6f9-70c0-44d8-86dd-f38dbb049887.jpg)

**Comment by speedlorenzo12** [comment]
Dont find a release

**Comment by ImranR98** [comment]
@speedlorenzo12 could you post a screen recording? @NaeemBolchhi 's instructions are right, and work on my end.

**Comment by speedlorenzo12** [comment]
Is equal if is in italian?

**Comment by ImranR98** [comment]
Wrong URL. It's telegram.org, not .com.

**Comment by speedlorenzo12** [comment]
Ok thanks
