### ISSUE TITLE
Improved support for high refresh rate screens

### ISSUE THREAD

**Issue by q-Sci** [ImranR98/Obtainium#429]
I am currently using a phone with a 90Hz screen, however the app only runs at 60 frames per second, which feels slightly stuttering on my device.
This might be related to an issue with Flutter itself(?), as discussed under https://github.com/flutter/flutter/issues/35162, but there might be a workaround using https://github.com/ajinasokan/flutter_displaymode.

**Comment by ImranR98** [comment]
What method are you using to determine framerate? I have a 90Hz screen too and don't see a noticeable difference (I usually can tell). Also the issue you linked has been resolved.

**Comment by q-Sci** [comment]
That's interesting. Maybe the issue is specific to some device configurations. I have provided some footage about my frame rates (sorry for the bad video quality, using a screen recorder locked the entire screen to 60fps for the rest of the recording when switching applications). My device is an Oppo Find X3 Lite 5G if that helps.


https://user-images.githubusercontent.com/97528607/230202130-ed3a1c09-df19-42cf-b660-2bdc3b7d8062.mp4

![Screenshot_2023-04-05-22-08-13-43_a13e17678c56528bd2f18fcaaa8af4ba](https://user-images.githubusercontent.com/97528607/230202145-5cb76391-772f-417e-86f6-1658a0a7b53c.jpg)
![Screenshot_2023-04-05-22-08-48-84_320a9a695de7cdce83ed5281148d6f19](https://user-images.githubusercontent.com/97528607/230202156-9f2df352-280b-4e1a-b443-5295d31cb9ca.jpg)

**Comment by ImranR98** [comment]
Just tried this on my Pixel 7 (I assumed you're using the developer option to show refresh rate). Obtainium does run at 90Hz for me so this looks like a device specific issue. Does it happen with other Flutter apps? You can try some from https://github.com/tortuvshin/open-source-flutter-apps

**Comment by q-Sci** [comment]
Seems like the problem exists with most Flutter apps I've tested. I'm closing this issue.
