### ISSUE TITLE
Codeberg broken filenames in release selection

### ISSUE THREAD

**Issue by NaeemBolchhi** [ImranR98/Obtainium#432]
![Screenshot_20230406-031559_Obtainium](https://user-images.githubusercontent.com/42773187/230213475-b3b71129-ad4b-4ace-bd29-99106b924db5.png)

The package names are weird like this.

I was using this repo— 
https://codeberg.org/qwerty287/ftpclient/

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.11.25-beta
