### ISSUE TITLE
Adding /releases directory to github app links

### ISSUE THREAD

**Issue by ayo-x** [ImranR98/Obtainium#435]
Hello. It would be nice if we could get an option to change the github app links to lead directly to the releases page, instead of the main app page. Most developers post their apps' chance logs on the releases page, so it would really save some time for those of us who wish see these change logs. Thanks. 
![Ss_1](https://user-images.githubusercontent.com/35936440/230238354-2b7912cb-f07c-4c16-b0d2-a954664d8732.jpg)

**Comment by ImranR98** [comment]
You can already see change logs by tapping the app's release date on the main list page.

**Comment by ayo-x** [comment]
Didn't know that. Thanks a lot!
