### ISSUE TITLE
Add APKMirror as a source

### ISSUE THREAD

**Issue by noClaps** [ImranR98/Obtainium#44]
Seeing your comment in #3, it seems that you use RSS feeds to get the APKs from sources like GitHub. Seeing as APKMirror also provides an RSS feed for apps, is it possible to add it as a new source for apps?

**Comment by rancidfrog** [comment]
But isn't the whole point of Obtanium :
> Get Android App Updates Directly From the Source

**Comment by ImranR98** [comment]
Yeah originally it was just for FOSS apps from GitHub, but APKMirror support would be useful for some use cases.

For example, the Play Store won't let me install Netflix since I use GrapheneOS, and I'd rather not download a whole separate app (Aurora store) just for that, so I guess APKMirror support would be good for that.

**Comment by rancidfrog** [comment]
Depends, really.
Apkmirror can start pushing malware.
That is why this project is interesting, to not rely on 3rd party.
Might as well implement PS scraping for apps that only in store.
But then again some devs do not bother pushing APKs into github, which can be signed and released automatically, but rather they depend on unreliable fdroid releases for their own app when they have the infrastructure to do it all, gitlab and github support releases 🙆🤷

**Comment by noClaps** [comment]
> Apkmirror can start pushing malware

Wouldn't that apply to any other source? F-Droid builds apps from source signs them with their own keys, which means they could have made modifications to the builds on the main F-Droid repo.

Similarly, the prebuilt APKs in GitHub Releases could also have malware in them, even if the source code doesn't. You're always trusting someone.

The logic behind my suggestion was the reason that the dev provided. There are certain apps that aren't open source, and APKMirror has been a pretty reliable source so far.

> Might as well implement PS scraping for apps that only in store.

I feel like it would be easier to use the RSS feed from APKMirror, since the code for that seems to already have been implemented for sources like GitHub and GitLab.

**Comment by ImranR98** [comment]
Added in https://github.com/ImranR98/Obtainium/releases/tag/v0.5.5-beta

Just noting that this turned out to be more complicated than just parsing an RSS feed, as the RSS feed doesn't contain APK URLs. The actual approach ended up requiring web scraping with more requests than any other App Source, and even needed the request to include a browser User-Agent. The APK URLs themselves even get generated every time and expire after a while, so it seems APKMirror doesn't really want web scraping. So this may break in the future but it works for now.

**Comment by archon810** [comment]
@ImranR98 I run APKMirror and found your project today. You're correct in your assumption that APKMirror is against scraping that results in leeching our bandwidth for free without giving anything in return (viewing advertising on pages or using [APKMirror Premium](https://www.apkmirror.com/premium/) for ad-free experience).

The way APKMirror access is currently implemented in your app bypasses our pages and takes the raw file.

Other tools, like APK Grabber and APK Updater have taken different approaches - they query by scraping or even using an API, then when it's time to download, send the user to the relevant download page. I even worked with the authors of these tools to make sure the API works well for them, and that's the kind of relationship I would like to have with Obtainium as well. I dropped you an email so we can chat further if you're interested.

Thanks.

**Comment by ImranR98** [comment]
We can discuss this (have DMed you) but in the meantime APKMirror will be disabled as an App Source in the next release, whenever that is (see https://github.com/ImranR98/Obtainium/issues/14#issuecomment-1279898918).

**Comment by ImranR98** [comment]
For now, I've disabled APKMirror in the latest version (https://github.com/ImranR98/Obtainium/releases/tag/v0.6.0-beta) as I'd prefer not to include it if the developers don't want it to be (anyways, it would be easy for them to make a change that breaks the current hacked together approach).
Haven't had any communication, am closing this issue for now. Will reopen if there is an update.

**Comment by archon810** [comment]
I DMed you yesterday FWIW, would like to connect still.

**Comment by ImranR98** [comment]
Great, haven't seen it yet. May not be able to get back to you for a few days.

**Comment by ImranR98** [comment]
As discussed, the best way to support APKMirror will be as a new kind of "notifications-only" source that can be checked for update notifications without being able to directly download and install APKs. Instead users would be directed to the external download page.

Currently, a lot in Obtainium is based on the assumption that APKs can be downloaded, so adding this new source type will require a lot of changes. Definitely worth doing at some point but not a high priority.

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.0-beta

**Comment by vhick** [comment]
This is a great addition. Now I can use only one app to track some of the apps from APKmirror or some other projects on Github on zip files like Magisk modules. But I noticed that when I search for direct url feeds from APKmirror. It doesn't give any info if it is a stable or beta version. I also noticed that it doesn't support .atom url for tracking.

Currently I used Feeder for tracking some github releases.

![Screenshot_2022-11-26-10-39-51-004_dev imranr obtainium](https://user-images.githubusercontent.com/2021625/204069294-16629fd6-c32f-4bac-9dbb-56538bc84f82.jpg)
![Screenshot_2022-11-26-10-32-39-650_com nononsenseapps feeder play](https://user-images.githubusercontent.com/2021625/204069298-93148164-64c9-4578-82df-b371c45401c2.jpg)
![Screenshot_2022-11-26-10-32-31-856_dev imranr obtainium](https://user-images.githubusercontent.com/2021625/204069344-72ef5a8b-1691-422b-ae57-cf481f57c8ff.jpg)


Thank you.

**Comment by ImranR98** [comment]
The GitHub repo in your first screenshot doesn't have APKs on their releases page, which is why you get the error. And yeah, RSS feeds are not supported (everything in your URL after 'rvx-builder' is ignored). You can still toggle the "track only" option so it doesn't look for APKs, you'll still get notifications.

The second YouTube screenshot is concerning though, not sure why the version isn't being picked up. Am re-opening the issue to fix that.

**Comment by vhick** [comment]
I try to toggle the "track only" option. But the add button is disabled once I toggle it. It means that it is applicable to apk releases only?

![Screenshot_2022-11-26-11-13-36-551_dev imranr obtainium](https://user-images.githubusercontent.com/2021625/204070417-e664bea9-8ef7-4185-9f98-eca82a50a909.jpg)

**Comment by ImranR98** [comment]
Hmm, seems like a bug. You can fix it by backspacing on a character in the url bar and typing it again (any change in the bar should trigger the button enable).

**Comment by ImranR98** [comment]
Versioning issue fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.1-beta
