### ISSUE TITLE
[Feature request] Filter by "latest" tag

### ISSUE THREAD

**Issue by CryptMaverick** [ImranR98/Obtainium#441]
It would be much easier if we could filter the release with the ```latest``` tag. To mitigate the need to use regex on ```https://github.com/brave/brave-browser/releases``` and on ```https://github.com/mozilla-mobile/firefox-android/releases```, for example.

**Comment by ImranR98** [comment]
Not sure what you mean. The latest release is already the one that is picked, and if you disable "fall back to older releases" then it is the only release that will be considered.

**Comment by ImranR98** [comment]
Actually there might be a bug when both those options are disabled. Will look into it.

**Comment by CryptMaverick** [comment]
> The latest release is already the one that is picked
This is the point, if you look at the examples I gave, you will see that either of the latest releases is not actually the latest release. The latest release in both examples has a "latest" label.

**Comment by ImranR98** [comment]
Thr release title filter was made for this exact kind of situation.
