### ISSUE TITLE
Parse App ID from build files

### ISSUE THREAD

**Issue by Sertonix** [ImranR98/Obtainium#448]
I am not an export in creating android applications but I think there is a build config file which defines the app id in most cases.
Maybe this could be used to skip downloading the release apk.

**Comment by ImranR98** [comment]
Searching for the build config in each App's repo has a few issues:
- Location of config file may vary for a lot of reasons (Flutter VS Native, Android-specific repo VS multi-platform, different branches for different releases, etc.).
- Searching for the file would be messy and result in a lot of repeated API requests (users with no GitHub token would hit the rate limit much earlier).
- This would have to be done separately for each source and even then it would only work for sources that provide source code and a search API for it. The current approach works for all sources that need it.
