### ISSUE TITLE
Obtainium Export doesn't restore additional options

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#45]
Ideally: 
Importing an obtanium backup would retain 'additional options' such as custom name, pre-release preference etc.  Perhaps also install status and version.

This is time consuming to fix when needing to restore the app after a bug.

**Comment by ImranR98** [comment]
You're right about install status/version, those were excluded from import (don't remember the exact thought process behind why) but I guess it's okay to include them).
Regarding the other additional options, though, I just did an export of 30 Apps, one of which had non-default additional options, and they all imported with the options intact. Not sure what went wrong on your end. It possibly has something t do with upgrading from an older version (before additional options) to this one. If you attach your export I can take a look and maybe figure out what went wrong.

**Comment by S7venLights** [comment]
How can I send it without attaching publicly here?

**Comment by ImranR98** [comment]
imranr98@pm.me

**Comment by S7venLights** [comment]
Sent

**Comment by ImranR98** [comment]
I just tried the files you sent me and all Apps were imported with settings intact. Checked an app with a non-default toggle and another app that had a custom name. Like #48 I can't tell what the issue might be.

**Comment by ImranR98** [comment]
I'll assume this is also fixed as per #48
