### ISSUE TITLE
Issues with changing app name

### ISSUE THREAD

**Issue by Zumux** [ImranR98/Obtainium#450]
Found some issues with changing an apps name

- Getting rid of the app name you entered yourself still keeps the last thing that was entered as the name and does not go to default
- Changing an apps name that **is** installed updates the name in that app screen but doesn't on the apps list
- Changing an apps name that **isn't** installed seems to work properly 

Also maybe more so related to sorting the apps by name. It seems to sort from A-Z, a-z. So changing an apps name to begin with a lowercase letter moves it to the bottom of the list

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.11.30-beta

**Comment by ImranR98** [comment]
Note that for your first point, Apps whose names were previously changed will not change back with this update, but it should work for new apps moving forward.
