### ISSUE TITLE
[Feature Request] Import app urls from single url

### ISSUE THREAD

**Issue by pswilde** [ImranR98/Obtainium#452]
Hi,
I was wondering if it may be possible to enable importing many urls from one single url?
For example, I have a page on my website which has a list of git repo urls for apps I use. I use this if I ever reinstall Obtainium (i.e. I've wiped my device and need to reinstall everything) and I can just copy and paste urls on this list without having to find an obtainium export file etc. I find this a much quicker process.
But, if I could just point Obtainium to the url of this list, it would be a huge timesaver. 
Currently, my list is just a list of urls, but I'd be happy to host an obtanium export file in the same location as I suspect that's a lot less work to implement.
Anyway, not a problem if not on the todo list, I can cope with the current process.

Obtainium is great by the way - keep up the good work!

**Comment by ImranR98** [comment]
You can already import all the URLs at once using the "Import from URL List" button on the Import/Export page - you'd just need to copy/paste them from your website in a couple of clicks.

**Comment by pswilde** [comment]
Yep, no problem. I'll manage with the current process 
Just to give a little extra info on my reasoning (though I'm not trying to force you into changing anything of course!) The copy and paste of urls is fine, except with third-party FDroid repos where an app name needs to be set. It would be cool if I could host an Obtanium Export file (which contains these app names) somewhere and just import via a URL. But that's all, it's not a big deal at all, I can just copy/paste and then fill in the app names later - it's only a few apps I have this way.

Thanks again!
