### ISSUE TITLE
Gitlab add "Fallback to older releases"

### ISSUE THREAD

**Issue by loaidheach** [ImranR98/Obtainium#456]
For a few days ago I get a "No APK Found" for AuroraStore everytime Obtainium checks for updates. From the AuroraStore atom feed it looks like they created the tag for version 4.2.0, but added no release files yet. For cases like this it would be nice to have the same "Fallback" option that is available for Github to avoid such errors.

**Comment by XxTriviumxX** [comment]
to be fair, i think this is an issue on aurora store's side.  The owner has life issues to take care of. The 4.2.0 version was released by a maintainer that doesn't have access to the owner's signature, preventing the creation of an apk. The apk was compiled by f-droid's engine if you want to use 4.2.0 now...

If the owner was available, there would have been no errors on obtainium (correct me if i'm wrong)

**Comment by loaidheach** [comment]
Yes, this is definitely an issue on Aurora's side and that's OK (thank for the link, btw). AuroraStore was just an example. This is a case that can happen with other repos as well for different kinds of reasons. So it would be nice if Obtainium had a graceful way to handle it.

**Comment by XxTriviumxX** [comment]
it would be weird to go back to 4.1.1... and not being notified by 4.2.1 for example... this requires a specific mecanism to work.. I think they can pull it off though!

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.11.33-beta
