### ISSUE TITLE
Feature Request: Pull "release notes" from github or other sources

### ISSUE THREAD

**Issue by jessesmith4** [ImranR98/Obtainium#458]
Hello. Love the app. Thanks for your hard work.. I was thinking it might be nice (and hopefully easy) to scape the release notes some app developers put in GitHub releases page above the Apk files and some how show in obtainium.. I like to see what changed prior to installing.. I can certain navigate to GitHub and do that but it would nice if it pulled in somewhere.

Thanks!

**Comment by jessesmith4** [comment]
Oh great! Sorry for the dup. I did search but I guess not the right terms.. I don't know why I never thought to click that date.. but it makes sense now.

**Comment by ImranR98** [comment]
Thanks @Zumux
