### ISSUE TITLE
Install fail, don't redownload app 

### ISSUE THREAD

**Issue by jessesmith4** [ImranR98/Obtainium#459]
On a few occasions an app wont install after downloading mostly because I will switch apps and it will not install since I didnt hit the prompt. Is it possible to cache the app download and attempt to re use it if the app is attempted to be reinstalled within a certain time period? For example brave is a big download so it can get annoying to have to redownload if it fails.. didnt know if there was a way to check "I have downloaded this file already let me use it" rather than just downloading again..

Thanks again.

**Comment by ImranR98** [comment]
Currently, all downloaded APKs are deleted when the app is opened (no reason to pick that trigger, but some trigger is needed). Deleting/keeping APKs in a smarter way is currently not possible due to the APK install happening asynchronously (see also #25, #99, #111).

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.12.1-beta
