### ISSUE TITLE
Switch to Radio Buttons

### ISSUE THREAD

**Issue by NaeemBolchhi** [ImranR98/Obtainium#460]
![Screenshot_20230412-212154_Obtainium](https://user-images.githubusercontent.com/42773187/231506113-593b2bef-de5b-4e09-ac02-220b094b47b7.png)

The square checkboxes used in this selection screen work like radio buttons. That can cause some misunderstanding.

Square checkboxes suggest that multi-selection is possible, while round radio buttons suggest that only one option may be selected. I believe switching to radio buttons here would be better for UX, unless you have plans to allow multi-selection in the future.

Reference: https://ux.stackexchange.com/a/101585

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.11.33-beta
