### ISSUE TITLE
App not installed as package conflicts with an existing package

### ISSUE THREAD

**Issue by jehsehjhsh** [ImranR98/Obtainium#463]
Clicked update on "do you want to update this app?" prompt, update downloads, then this error: "App not installed as package conflicts with an existing package."

This happened for 2 apps so far, K-9 Mail (source Github) and Calendar by SimpleMobileTools (Github). New version of app installs successfully if I uninstall the app first. Using GrapheneOS.

**Comment by ImranR98** [comment]
Not sure what's going on - I just tried both those apps with no issue. Either way, the error message you quoted doesn't come from Obtainium - it is an Android error that normally shows up when you're trying to update to an older version of an app, or one signed with a different key. Are you updating these Apps from outside of Obtainium (like F-Droid)?

**Comment by jehsehjhsh** [comment]
No, though I initially installed them outside of Obtainium, before I had installed it.

**Comment by ImranR98** [comment]
> No, though I initially installed them outside of Obtainium, before I had installed it.

From F-Droid?

**Comment by jehsehjhsh** [comment]
Yes pretty sure

**Comment by ImranR98** [comment]
That explains it. For all but a tiny minority of apps, F-Droid signs the app with their own key as opposed to the original developer's key (which is what APKs on GitHub are signed with). So Android won't let you mix these APKs (update from one to the other) as they don't appear to be from the same developer. See #239, #317.

**Comment by gunar** [comment]
Is there a way to migrate an app installation from D-Droid to Obtanium without uninstalling the app and losing app data in the process?
