### ISSUE TITLE
Link to APK for purchased app hosted on Paddle not working

### ISSUE THREAD

**Issue by eylenburg** [ImranR98/Obtainium#464]
Hi. I bought the app FolderSync Pro through a direct purchase from the developer rather than through Google Play. I don't get update notifications but I can download the app from a link I got in an email. 

The link looks like this (slightly amended to break the link because I think it's a unique link tied to my license so not to be shared publicly): https://click.pstmrk.it/2sm/vendors.paddle.com%2Fdownload%2Fproduct%2F41dcd8a5-fe43-4bca-a1d8-355d1acfbe53/RF11HSgN/7cQ/Uq7NVRkY2C/bG9ja2Vy

Adding this link to Obtainium will say it didn't find anything.

However, opening that link in a browser will immediately offer to download the APK. 

I prepended "view-source:" to the URL to investigate it more and apparently the above link actually resolves to the latest APK available which is hosted on Amazon AWS, like this (I again changed the link here): https://paddle.s3.amazonaws.com/fulfillment_downloads/31397/529456/v7dL0gClRtmEjQqaR4pS_folderSync-app-directSale-release-3.4.5.apk
I guess this link would work in Obtainium but it's pointless because it's only for one version.

So I'm wondering if there's any way to add the original link to Obtainium?

**Comment by ImranR98** [comment]
See #262. You'd need a (public) HTML page with the APK link on it (where the link ends with `.apk`).
