### ISSUE TITLE
pCloud updater

### ISSUE THREAD

**Issue by xmha97** [ImranR98/Obtainium#468]
Hi,
Please add support pCloud.
https://www.pcloud.com/release-notes/android.html
Thanks.

**Comment by xmha97** [comment]
May be helpful:
https://docs.pcloud.com/methods/public_links/getpublinkdownload.html

**Comment by xmha97** [comment]
If you change user agent to Android:
![image](https://user-images.githubusercontent.com/23485114/231973928-528b4a9e-de03-4413-bc67-9e5fafafe5cb.png)

**Comment by ImranR98** [comment]
The website uses JS for everything (including generating the download) so it can't be scraped in Obtainium. Also the API link you mentioned has to do with downloading a user's own uploaded files, not the pCloud APK. Will reopen if a reliable way to extract the APK version and download link is proposed.

**Comment by xmha97** [comment]
Ok, thanks.
