### ISSUE TITLE
Stocks widget app not working

### ISSUE THREAD

**Issue by Grkrz** [ImranR98/Obtainium#470]
Hi tried to update the stocks widget but I could not update the app despite the name looks the same etc. I could unistall and install this app but it is a lot of work due to can save the stocks positions. Not sure if this is an issue related to obtanium or stocks widget app. Thank you

**Comment by ImranR98** [comment]
No idea what App you're referring to or what you mean by "name looks the same" and "could not update". Please provide details like the App URL, error message, additional settings used, details like whether the app was already installed when added, how it was added, etc. Maybe post a screen recording if that's easier.

**Comment by Grkrz** [comment]
Sorry for being not clear. 
https://github.com/premnirmal/stockticker/releases

app-purefoss-debug.apk - this name I meant.

Before I had downloaded this app and now is new update. 
![IMG_20230415_194950](https://user-images.githubusercontent.com/107203983/232245286-16b90e24-af3f-4fbc-87dc-c90bef845f95.jpg)

app-purefoss-debug.apk This is the one I had downloaded before and it was done through Obtainium.

Hopefully those info will be useful

**Comment by ImranR98** [comment]
That error is not coming from Obtainium. Whatever APK you had before is conflicting with the new one (probably different app signature) and android doesn't allow this.

Try downloading the APK from GitHub manually in your browser and you should get the same error. I'm not sure if the developer has changed their signing key with the latest version or if the previous version you had was from f droid but either way it's an issue with the apk.
