### ISSUE TITLE
Icon disappeared

### ISSUE THREAD

**Issue by rantoforest** [ImranR98/Obtainium#475]
Hello , Dev  .. Thanks for this great app .
Obtainium icon disappeared after updating to version 30, the same problem with version 31, 32 as well .
Android : 7.1.2 ( AOSP based )

**Comment by ImranR98** [comment]
Do you mean the icon in your app drawer?

**Comment by ImranR98** [comment]
Have not been able to reproduce this on an Android 7 emulator. What was the last version you used that had the proper icon? Also anything else that you can think of that might affect this like a custom launcher?

**Comment by ImranR98** [comment]
You could also try uninstalling/reinstalling - might just be a one off bug.

**Comment by ImranR98** [comment]
Hmm, there were no changes to anything icon related around that version :(

**Comment by ImranR98** [comment]
Stuck on this for now, not sure what else to try. Could you install another Flutter app and see if it has the same issue? I'm wondering if this is a bug in the OS or Flutter, rather than something Obtainium-specific.

**Comment by ImranR98** [comment]
Okay, this has shown up on my Android 7 emulator now. Weird.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.5-beta
