### ISSUE TITLE
Error when installing apps from github

### ISSUE THREAD

**Issue by rantoforest** [ImranR98/Obtainium#476]
After importing app from github search and click install button , it gave this error after app is downloaded 
![Img1](https://user-images.githubusercontent.com/130922902/232330129-06b20f71-b87b-41fd-afde-d9a82dd1f7a2.png)

To solve this , i go back to main tab of obtainium app then choose the app and click install button again
Android : 7.1.2 (AOSP based)

**Comment by Beariddle** [comment]
I ran into this issue as well, when on a new custom rom flash. Don't know if this is related, but for me the entry of that particular app, or several apps if I multi-selected, would disappear. And only re-appear again when I force closed the obtainium and then re-opened the obtainium again afterwards.

Not really a big issue for me personally, but it did happen to me on three occasions. Could not find a reliable way to reproduce it on other devices, however in my case.

**Comment by ImranR98** [comment]
Does this happen with any app or search term, or specific ones?

**Comment by ImranR98** [comment]
Could you provide a screen recording if possible? Might help to see exactly what's going on as I haven't been able to get this to happen on my end.

**Comment by ImranR98** [comment]
Perfect, I misunderstood what you were doing before. Have reproduced the error, will look into it.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.11.34-beta
