### ISSUE TITLE
Protonmail update bug

### ISSUE THREAD

**Issue by BabyOilJohnson** [ImranR98/Obtainium#478]
In Protonmail's github, the latest ver is 3.0.12 but in Obtainium it's ver 3.0.11. Is it a github bug?
Gh link: https://github.com/protonmail/proton-mail-android
![Screenshot_20230418-171729](https://user-images.githubusercontent.com/101601874/232769968-6d689e10-f049-4561-aab0-8b9448d6a5ae.png)

**Comment by loyl1** [comment]
I can confirm the bug. Proton is doing something funky on the releases page. V 3.0.11 from January is at the top of the releases page. The more recent v 3.0.12 from April is listed below 3.0.11. 

"Use release date as version" option does not pick up the newer version

https://github.com/ProtonMail/proton-mail-android/releases

**Comment by ImranR98** [comment]
Yep, the API returns version 3.0.11 as the first item (which is assumed to be the latest) even though the second item is newer. Looks like the API doesn't sort results by release date, but something else (probably the date the tag was created, but would need to confirm),

This is the same problem as issue #137. I closed that one as "not planned" as I didn't think there was a way to fix it without doubling the number of API calls. On second thought Obtainium could just re-order the API results, sorting by release date. Not sure if that would negatively affect other apps. I'll test it with a bunch of different Apps and see how it goes.

**Comment by loyl1** [comment]
Good progress, Protonmail shows up in obtainium, ready to update. However, now GrapheneOS sees it as an older version and won't install it. Proton has done something funky here

**Comment by loyl1** [comment]
> > Good progress, Protonmail shows up in obtainium, ready to update. However, now GrapheneOS sees it as an older version and won't install it. Proton has done something funky here
> 
> Sounds like you somehow updated to 3.0.12 already (maybe the play store if you have it?) - you can confirm this in the app. Obtainium sees that the installed version is different from what it thinks is the latest version (3.0.11) for the reasons mentioned before. So it tries to "update" to a lower version, which the OS blocks.

You are correct. I have already updated to 3.0.12, and obtainium does show latest version 3.0.11, installed version 3.0.12 because of how Proton listed it on GitHub.

Thanks for your help and an awesome app

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.11.33-beta
