### ISSUE TITLE
Bug: Obtanium Export/Import only restores 15 apps

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#48]
V0.5.4 
Title describes it all. Only 15 of my 25 Github apps exported. 

Export/Import URL list does work however.

**Comment by ImranR98** [comment]
Not sure what the issue is on your end. I just exported and imported 30 Apps with no issue. Maybe send your export file so I can take a look.

**Comment by S7venLights** [comment]
Sent

**Comment by ImranR98** [comment]
I just tried the files you sent me and I was able to import all of them fully. 25 apps from 0.5.6, 27 apps in the other two. Not sure why it's not working for you - maybe try clearing cache or something? Do you see any error messages?

**Comment by S7venLights** [comment]
Tested again (without clearing cauche) and it works as expected. Not sure why it happened before… You can close the issue thanks.
