### ISSUE TITLE
Improve changelog UI

### ISSUE THREAD

**Issue by milindgoel15** [ImranR98/Obtainium#482]
Currently, I have not found any option that we can use to view changelogs of apps when new updates are available for them. Can this be implemented where instead of opening the GitHub repo of such an app, we can view in the form of dialog or bottom sheet?

**Comment by ImranR98** [comment]
The changelog shown is always for the latest available version, not the currently installed version. I can see how this isn't obvious in the UI. Could add a "for version X" label or something.

**Comment by milindgoel15** [comment]
I have some design ideas for the home UI. The download button could be conditionally rendered as it is right now, whenever new updates are available for an app. 
![image](https://user-images.githubusercontent.com/45682747/233696111-007160da-961d-4b8a-9d6b-8eec60e0cbfe.png)

**Comment by ImranR98** [comment]
I've made the dialog change: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.33-beta

Your UI for the apps list looks good but I'd rather not take up so much vertical space per app. Info about the current vs. latest versions is probably too much detail for the list - the user can open the details page for that. Also remember that not all version strings are so short - some can be really long (especially those from the HTML source), same goes for titles and author names so you need to account for those.

**Comment by milindgoel15** [comment]
Could be wrapped with flexible or expanded widget so longer names wont overlap with trailing widgets.

**Comment by milindgoel15** [comment]
![Screenshot_2023-04-23-17-41-20-007_dev.imranr.obtainium.jpg](https://user-images.githubusercontent.com/45682747/233839062-dd6ee234-873f-45ba-9448-3a425bca1127.jpg)

Could the dialog's height be adjusted as per the content max height?

**Comment by ImranR98** [comment]
> Could the dialog's height be adjusted as per the content max height?

I played around with that for far too long but kept getting constraint errors. Something about the markdown render plugin seems to want to take up all available space.

**Comment by Marocco2** [comment]
May I say that button trigger for changelogs is very small and prone to misses? 

You could design all the right part of app item as a trigger for changelogs and you could add a small separator to distinguish between left and right part

**Comment by milindgoel15** [comment]
Also, not related to changelog UI, could the update button be conditionally rendered when only the latest version is greater than the installed version? Making it display only when the installed version is lower than the latest version.
