### ISSUE TITLE
Obtainium refuses to download due to version detection

### ISSUE THREAD

**Issue by Aayu1254** [ImranR98/Obtainium#484]
The version number is weird for this release but it's supposed to ignore when i disable the version detection but it is the same in every option, but obtainium refuses to download it and shows the following error.

![Screenshot_2023-04-21-20-10-24-14](https://user-images.githubusercontent.com/79454297/233666288-35c62de4-9a09-4638-a650-9f110f8cbd2a.jpg)

My device is android 10.

**Comment by ImranR98** [comment]
Revanced manager doesn't have weird version format so you don't need to turn off version detection. It just looks like you're trying to install an older version than what you already have - you should confirm this by checking the versions in your phone settings and comparing it to the latest version shown by obtainium. Try manually downloading the apk you want from github and installing it - you should see an error from android too.
