### ISSUE TITLE
[Bug][UI] Truncated app's name and metadata in home screen

### ISSUE THREAD

**Issue by fellinir** [ImranR98/Obtainium#485]
The other apps in the home screen render correctly, but Tor browser for some reason does not:

![Home](https://user-images.githubusercontent.com/92597054/233794513-e7fec3a2-abf3-4d13-93a1-672da47c8f07.png)

![App details](https://user-images.githubusercontent.com/92597054/233794531-a3703a83-4174-43c8-9509-74e979ffb29f.png)

**Comment by ImranR98** [comment]
This comes down to your small screen size and the fact that Obtainium needs to leave some space between text to keep things legible, plus the version string for Tor being a large unbroken string. I've made some changes in the latest version that should improve things but there might still be some truncation: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.33-beta

**Comment by fellinir** [comment]
My phone screen is not small, but I actually enlarged text and UI a bit from the OS settings for better readability.
