### ISSUE TITLE
Optional for installing unknown sources

### ISSUE THREAD

**Issue by jcperil** [ImranR98/Obtainium#488]
Before I can add any link, the app is asking me to enable `Install from unknown source`. The app is not functional if I don't enable it. I just want to use Obtanium for release notifications.

**Comment by ImranR98** [comment]
You won't be asked for that permission if you add the app as "Track-Only" which does what you need (notifications only).

**Comment by ImranR98** [comment]
On second thought, there probably was no real need to enforce the permission. Removed in the latest version: https://github.com/ImranR98/Obtainium/releases/tag/v0.12.0-beta
