### ISSUE TITLE
Light Diamond icons for not installed apps in the Obtainium dark themes.

### ISSUE THREAD

**Issue by Toiletmason** [ImranR98/Obtainium#490]
They are all so dark you can only see them on the light theme. It's not a huge deal, but it's something that would improve the overall look of the app.

**Comment by ImranR98** [comment]
Increased the opacity a bit (don't want to take it too far as these should be obvious placeholders): https://github.com/ImranR98/Obtainium/releases/tag/v0.11.35-beta
