### ISSUE TITLE
can't update obtainium 

### ISSUE THREAD

**Issue by mxwmnn** [ImranR98/Obtainium#493]
![Screenshot_20230425-231409](https://user-images.githubusercontent.com/105636539/234405823-bbb7d8be-f699-41ad-b9b4-8fba1afe3f3c.png)

Can't update obtainium on gos pixel 6 pro everything updated.

From version
![Screenshot_20230425-231700](https://user-images.githubusercontent.com/105636539/234406135-f387df13-09d7-4452-b990-9eda0c0aeb0b.png)

Using armv8a version

**Comment by ImranR98** [comment]
This was fixed in version 0.11.33 but you'll have to update to it manually since you can't do so from the app.
