### ISSUE TITLE
[Bug] App from IzzyOnDroid F-Droid Repo is not found

### ISSUE THREAD

**Issue by jcperil** [ImranR98/Obtainium#497]
I was trying to add [Ambient Music Mod](https://apt.izzysoft.de/fdroid/index/apk/com.kieronquinn.app.ambientmusicmod) but Obtanium is unable to find it.

https://user-images.githubusercontent.com/89805719/235285162-cf11eab0-5365-4980-aa27-fd968296dd71.mp4

**Comment by ImranR98** [comment]
Only android.izzysoft.de URLs are supported. Use this instead: https://android.izzysoft.de/repo/apk/com.kieronquinn.app.ambientmusicmod
