### ISSUE TITLE
[Feature Request] Option to stop displaying the Track Only dialog box

### ISSUE THREAD

**Issue by jcperil** [ImranR98/Obtainium#498]
If you select Track Only and add an app, a dialog box always appears informing you of the consequences. Can you please add a tick field to stop displaying it again?

<img src="https://user-images.githubusercontent.com/89805719/235285535-71511fb0-3240-495c-8eec-25d4c5908bdd.jpg" width="250px" />

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.12.0-beta
