### ISSUE TITLE
Apk

### ISSUE THREAD

**Issue by bornhustler07** [ImranR98/Obtainium#5]
Hi sir thank you for such amazing app and for your hard work I'll like to request is it possible to add in setting to choose default between Arm64-v8a and armeabi-v7a instead of every time to choose thanks again👍

**Comment by ImranR98** [comment]
Hi. There's no way to tell what CPU architecture an APK is built for except by its filename. There's no standard, so different apps may have different naming schemes, meaning we would need to have a separate setting for each app. Even then, app developers may not use the same naming scheme consistently, or might even have a different number of APKs in different releases. Right now, you pick the APK you want manually and Obtainium saves the index of your choice, to save you an additional tap next time.

I think this is a reasonable system for now. In the future, there might be an option to match APKs using regular expressions (see #1) and that could also be used to match for specific architecture strings.
