### ISSUE TITLE
[Feature Request] Different color code if an app has an update available

### ISSUE THREAD

**Issue by jcperil** [ImranR98/Obtainium#500]
<img src="https://user-images.githubusercontent.com/89805719/235285946-ac94ca9e-c607-4326-ad6b-2736a9bbce7f.jpg" width="300px" />

Perhaps you can assign it the accent color depending on the Obtanium or Material You theme.

**Comment by ImranR98** [comment]
Not sure what the picture is meant to show - the UI does not look like that (maybe it did on older versions). There's already an update icon next to any apps that have updates and this should be enough of a visual indicator.
