### ISSUE TITLE
Correct app names

### ISSUE THREAD

**Issue by jcperil** [ImranR98/Obtainium#507]
When I add [OctoDroid GitHub Repo](https://github.com/slapperwan/gh4a) and [ProtonVPN for Android GitHub Repo](https://github.com/ProtonVPN/android-app), Obtanium assumes the names **gh4a** and **android-app**.

Usually, the official name of an app can be found in the README.md file which might be difficult to scrap.

As an alternate solution, can you please let us rename the apps while adding?

**Comment by ImranR98** [comment]
Already doable - take a look at the additional options

**Comment by ImranR98** [comment]
Also note that the apps real name would be used once you install it anyways

**Comment by jcperil** [comment]
Thank you and sorry about that. I hadn't seen it.
