### ISSUE TITLE
Go directly to Apps section after an app is added

### ISSUE THREAD

**Issue by jcperil** [ImranR98/Obtainium#508]
In the process of adding an app, we see the following windows in order.

#### 1. Enter details of the app you want to add
<img src="https://user-images.githubusercontent.com/89805719/235342856-c36a38bd-d69c-4870-8e1e-64b6143e87af.jpg" height="250px" />

#### 2. Click Add and the following window appears
<img src="https://user-images.githubusercontent.com/89805719/235342861-4613b39c-8860-4d12-bec8-cb5ebab4b750.jpg" height="250px" />

#### 3. Press back button and Add App window appears again
<img src="https://user-images.githubusercontent.com/89805719/235342871-643165b0-ec0e-4c2e-ba29-09893f8d0925.jpg" height="250px" />

#### 4. Press back button again to go to Apps
<img src="https://user-images.githubusercontent.com/89805719/235342880-ad30afe5-e458-4828-a43b-6eedc05ca74f.jpg" height="250px" />

---

### Question:
Do we need to see the third window? Wouldn't it simpler if pressing back button once jumps directly to **Apps** section? Please let me know what you think.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.12.2-beta
