### ISSUE TITLE
Open link support on android 12

### ISSUE THREAD

**Issue by Baker0o7** [ImranR98/Obtainium#51]
Thanks always Sir  instead of copying the link and go to paste on android 12 link can be added in setting pressing the link and take you direct to the app 🙏 it will nice if you kindly add that

**Comment by ImranR98** [comment]
Not sure I understand. Do you mean an App link like 'github.com/.../...' ?

**Comment by Baker0o7** [comment]
![Screenshot_20221008-194903_Settings_1](https://user-images.githubusercontent.com/113295927/194718567-88a873fd-507b-4d2f-89a2-a2416493a77f.png)

**Comment by ImranR98** [comment]
According to https://developer.android.com/training/app-links, Web links will only open in the web browser on Android 12 and above, no third party app support.
I don't think adding this feature is worth supporting if it's only on older Android versions.

**Comment by S7venLights** [comment]
I'm on android 12 and Octodroid opens github links by default
