### ISSUE TITLE
Build and Release updates with GitHub Actions

### ISSUE THREAD

**Issue by JohnBetaro** [ImranR98/Obtainium#513]
I like your wonderful app and I have been using it for a while now, however can you please consider using GitHub Actions to build and release your updates, just to offer more transparency so people can actually verify everything that happens and make things easier on you in the future, you won't have to build then upload everytime you change something.

You have all my respect for your efforts to build such a great app, I hope you will think about my suggestion.

**Comment by iDazai** [comment]
I like this idea. 
One app where I'd use it is Element.
The .apk on github is the one with google services, but in their github actions list there is also the fdroid version.
Neither the app in the Fdroid repo, nor the Google Play repo is as up to date as the Github version is.
For example: https://github.com/vector-im/element-android/actions/runs/5146729889

**Comment by ImranR98** [comment]
Thanks @JohnBetaro for your work on this. I made some changes (tagging, manual-only trigger, etc.) - latest release was done through GitHub actions: https://github.com/ImranR98/Obtainium/actions/workflows/release.yml

**Comment by ImranR98** [comment]
I decided to trigger the job manually instead of on merges since sometimes things get merged that aren't ready for release (for example I might not have incremented the package version yet). You're right about the draft though, I guess it's fine to release directly since the trigger is manual already.
