### ISSUE TITLE
Add a Generic URL App Source

### ISSUE THREAD

**Issue by Gottarocket** [ImranR98/Obtainium#52]
Please add aurorastore nightly [build](https://files.auroraoss.com/AuroraStore/Nightly/). It would be better if you can add an option to parse and download apk directly on links which only has apk and nothing else. Just comparing versions.

**Comment by S7venLights** [comment]
Aren't all Aurora OSS apps on gitlab

**Comment by Gottarocket** [comment]
Nightly build isnt

**Comment by parkerlreed** [comment]
Aurora is tricky since there's no static URL to pull the APK from. My custom solution was pulling thje HTML and parsing out the last URL from the page

```
	auroradroid)
		url=$(lynx -dump https://files.auroraoss.com/AuroraDroid/Nightly/ | awk '/http/{print $2}' | tail -1)
		pull_and_update Aurora $url
		;;
```

I agree a generic URL parser would be a fantasic addition. Maybe parse page for apk links and use that as the URL list that is currently implemented?

**Comment by faustaahmad** [comment]
@Gottarocket check [Aurora's gitlab activity](https://gitlab.com/groups/AuroraOSS/-/activity) 
Aurora's Nightly builds probably automated everyday regardless of updates in their repos, just stick with stable builds in fdroid/gitlab releases

**Comment by Gottarocket** [comment]
Sure. But generic url parser as @parkerlreed mentioned would be helpful.

**Comment by ImranR98** [comment]
I agree, a generic Source that takes any URL and tries looking for APK links on the page is a good idea. It covers Aurora and won't break if they change their URL scheme (which they have done - [this link](https://files.auroraoss.com/AuroraStore/Nightly/) posted in the issue no longer works but [this](https://files.auroraoss.com/?folder=AuroraStore/Nightly) now does).

**Comment by ImranR98** [comment]
Added, tested with AuroraDroid: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.0-beta

**Comment by parkerlreed** [comment]
@ImranR98 Thanks! Your releases URL 404's without the extra 0 (10.0.00)
