### ISSUE TITLE
Reset Install Status after adding an app that was installed via F-Droid?

### ISSUE THREAD

**Issue by martin-braun** [ImranR98/Obtainium#527]
I added an app that is already installed via F-Droid via F-Droid repo URL, so in theory it should just continue to work when updating via Obtainium.

I got a "Reset Install Status", but pressing it, does nothing. Will it actually work (updating, etc) when a new release is available? I will uninstall F-Droid after adding all F-Droid apps to Obtainium.

Thanks.

**Comment by ImranR98** [comment]
"Reset Install Status" usually shows up for Apps with version detection turned off, which happens automatically for some Apps with weird versioning schemes. When you press it, the version gets reset to empty, but it is immediately auto-refilled with the value taken from your OS (the button is meant to be there just for fixing version mismatches). Assuming this is what's happening in your case, everything is fine and you shouldn't have any problems with updates. Also it is always useful to include the app URL in issues.

**Comment by martin-braun** [comment]
Thanks @ImranR98 That was helpful. The app in question is 8Vim on F-Droid. I think it'll be alright then. 🙏

**Comment by ImranR98** [comment]
> The app in question is 8Vim on F-Droid.

Okay that makes sense. "`iteration-1`" is definitely not a version name that Obtainium's version detection can work with.

**Comment by martin-braun** [comment]
@ImranR98 Will updating still work? Also, if the version is not parsable, maybe extracting the last number could be a fallback? Or maybe it's best to ignore version comparing and just offering the new version when its version string differs from the previous one? What is the best / recommend way in this case?

**Comment by ImranR98** [comment]
> Will updating still work?

Yes

> Also, if the version is not parsable, maybe extracting the last number could be a fallback?

That would work for this specific App but break others. There's probably some complicated way to account for all possible versioning schemes but I messed with this for a long time (see #136) and eventually came to the current system which works for like 90% of apps, so not worth messing with again.

> Or maybe it's best to ignore version comparing and just offering the new version when its version string differs from the previous one?

Yep, that's exactly what "no version detection" does.

**Comment by martin-braun** [comment]
@ImranR98 Reasonable choices and it seems the app is set to "no version detection" automatically. I'm happy with that, it's a fine trade-off.

Good job!
