### ISSUE TITLE
Not found error - Regex parsing not correct

### ISSUE THREAD

**Issue by martin-braun** [ImranR98/Obtainium#528]
For some reason Obtainium reports "Not found" when trying to add an app with this URL: `https://f-droid.org/en/packages/com.github.muellerma.coffee/`. I think Obtainum confuses this URL with GitHub, but actually the developer decided to pick an app ID that contains `github`.

**Comment by hiteshbedre** [comment]
If you remove `/en` from url it should get matched. Issue lies at: https://github.com/ImranR98/Obtainium/blob/main/lib/app_sources/fdroid.dart#L23

Regex pattern wont url having `/en`

**Comment by hiteshbedre** [comment]
@ImranR98 do you see value to support such url? if Yes, I will be happy to update the regex accordingly.

**Comment by martin-braun** [comment]
@hiteshbedre I was adding a lot of apps with `/en` in its URL and it worked. Removing `/en` did not solve the issue. Also there is value in supporting those URLs, because these are served by the website of F-Droid.

**Comment by ImranR98** [comment]
Nothing to do with the regex. @hiteshbedre there are two regexes in that function - one for `/en/` and one without.

For some reason, the F-Droid API does not work for this app.
- Here's the API URL: https://f-droid.org/api/v1/packages/com.github.muellerma.coffee
- Here's the same URL for another App, which does work: https://f-droid.org/api/v1/packages/net.sourceforge.opencamera

Not something Obtainium can fix - F-Droid just isn't returning the info. No idea why but it would be something to contact them about.

**Comment by ImranR98** [comment]
Looks like this app does have releases on github though, so you could use that.

**Comment by martin-braun** [comment]
@ImranR98 I will report this to F-Droid and hopefully it will be fixed. I still wish to get the app from F-Droid and not GitHub, so I will ask about getting this API URL fixed, so Obtainium works with it.

**Comment by licaon-kter** [comment]
> I still wish to get the app from F-Droid

Huh? Then why bother with Obtainium? :)

**Comment by martin-braun** [comment]
@licaon-kter Just having multiple sources and avoiding client issues with F-Droid is a big win for me. I also did some research and each repository has its own signing key on F-Droid as well. F-Droid apps are still audited and FOSS approved, while on a rolling GitHub release I have to audit myself. I prefer to trust one organization over a dozen of developers, because I consider the attacking vector to be minimal this way. Also some apps are still not available on F-Droid, but on GitHub, so Obtainium is the right choice for me.

This is my personal take. @ImranR98 did an incredible work here that could be universal enough to be free to pick your source and it just works. I hope F-Droid support will be continued.
