### ISSUE TITLE
Updater resets altered names

### ISSUE THREAD

**Issue by ph00lt0** [ImranR98/Obtainium#53]
After running an app update the customized name is reset to the default. Not very useful.

**Comment by ImranR98** [comment]
What version are you on?

**Comment by ImranR98** [comment]
That's weird, I thought this was a duplicate of #50 but I guess not. Does this happen with all Apps? I just tried with a random one and it works for me, no custom name reset.

**Comment by ImranR98** [comment]
Could you confirm in the App settings if it's really 0.5.7-beta? There was an issue fixed recently where an App would appear to be updated even though it wasn't. It's possible you're still on the older version without knowing it.
