### ISSUE TITLE
Incorrect update prompt for old version

### ISSUE THREAD

**Issue by BHydden** [ImranR98/Obtainium#534]
I used Obtainium last week to successfully update Proton Mail to 3.0.14 ( current [latest](https://github.com/ProtonMail/proton-mail-android/releases) ) 

Now Obtainium is prompting me "update" to 3.0.12

Sorry if this is a duplicate issue. Tried to search for a few key words and couldn't find anything related.

![app-data](https://user-images.githubusercontent.com/28991649/236591832-0ae395f4-f40d-4562-8ff5-f6d912394390.png)

![protonmail-latest](https://user-images.githubusercontent.com/28991649/236591861-201b08ee-77e5-4383-b959-516b6aa671e8.png)

![obtainium-update-prompt](https://user-images.githubusercontent.com/28991649/236591881-8e7b8ecd-a8f4-4bb0-a059-933e6590e1d8.png)

**Comment by BHydden** [comment]
Forgot a few details:

Device: 
Pixel 6 Oriole
Android 13
Graphene OS
Version TQ2A.230505.002.2023050100

Obtainium:
Version 0.12.3
dev.imranr.obtainium
versionCode 2163

Installed: 13 Mar 2023; 13:18
Updated: 4 May 2023; 22:18

**Comment by ImranR98** [comment]
Protonmail keeps having these issues. Last time (see #478) I changed the way releases were sorted to prioritize the "publish date" but this time they have the "created date" as being higher. The only surefire way to fix this is by adding an additional API call (to get the 'latest' release), but that would double the number of API calls and is not worth doing for such a rare problem.

I'll switch to a tag/version-based sorting for apps (like ProtonMail) that have "standard" versions for which we can reasonably expect that "higher = newer". Other Apps will still have date-based sort.

**Comment by BHydden** [comment]
Awesome thanks for the quick reaponse ❤️ sorry I failed to find the existing issue I didn't consider searching for proton specifically

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.0-beta

**Comment by BHydden** [comment]
Fix worked. Obtainium now correctly recognises 3.0.14 as latest version of Proton Mail. Thanks
