### ISSUE TITLE
[Feature request]When select manual check updates:

### ISSUE THREAD

**Issue by TidalMist** [ImranR98/Obtainium#539]
add option to auto check updates on open app when selected manual check.
like in read you app 
![IMG_20230506_105935](https://user-images.githubusercontent.com/91356643/236611525-03e6386b-4b45-4337-ab0f-9ebce72bda03.jpg)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.1-beta

**Comment by TidalMist** [comment]
Big thanks!!
