### ISSUE TITLE
add support for xapks

### ISSUE THREAD

**Issue by Sukii23** [ImranR98/Obtainium#541]
now that apkpure is added there are certain apps that are compiled into xapks and it seems the app doesn't know how to deal with them.

**Comment by ImranR98** [comment]
Basic support added: https://github.com/ImranR98/Obtainium/releases/tag/v0.13.1-beta

Not sure how it will cope with OBB files or multiple APKs, but I tested it with https://apkpure.com/microsoft-lens-pdf-scanner/com.microsoft.office.officelens and that works at least.

Will re-open the issue if (when) someone reports an app it doesn't work for.

**Comment by Sukii23** [comment]
I tried downloading Asphalt 9 as a test and it didn't work

**Comment by ImranR98** [comment]
What's the error message?

**Comment by Sukii23** [comment]
in my case it didn't give any error message, it just had selected a previous version that had apk and ignored all xapks

**Comment by ImranR98** [comment]
Could you try this build and see if anything has changed:

[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/11427329/app-armeabi-v7a-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/11427330/app-arm64-v8a-release.zip)
[app-release.zip](https://github.com/ImranR98/Obtainium/files/11427323/app-release.zip)
[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/11427319/app-x86_64-release.zip)

**Comment by Sukii23** [comment]
I tested some popular games like brawl stars, among us and asphalt 9. Brawl stars and among us installed without any problems, aspahlt 9 now shows the correct version of the app. but for some reason the download stops in the middle or almost at the end.. I believe it is a network problem and not Obtainium.

a technical question, why does Obtainium download apps slower than a browser or an official store? Is there anything that limits this?

**Comment by Sukii23** [comment]
![Screenshot_20230509-204425](https://github.com/ImranR98/Obtainium/assets/127705451/eb4e31a7-09fc-4f69-baa4-7ce1ae1a998e)
Deu erro ao tentar baixar esse addon do mixplorer (apkpure mixplorer archiver, 64bit device)

**Comment by Sukii23** [comment]
![Screenshot_20230509-204425](https://github.com/ImranR98/Obtainium/assets/127705451/2c9310f1-789a-4348-a6e7-7a4c70ced4b8)

got error when trying to download mixplorer archiver addon in apkpure (64bit, android 10)

**Comment by ImranR98** [comment]
@Sukii23 can you try installing that same xapk manually? It works on my phone so I'm guessing the app just isn't compatible with your phone.

**Comment by Sukii23** [comment]
I'm going to close this error because I believe it's just some incompatibility with my cell phone. Thank you for developing such an amazing app!

**Comment by Sukii23** [comment]
proton drive does not install the latest version of the app. I tested on two architecture versions (32 and 64) and both failed to download the latest version of the proton drive. I deleted it and tried to install it through Obtainium and it still didn't install, the same thing goes for proton vpn on the two devices I tested.

**Comment by ImranR98** [comment]
I haven't had problems with XAPKs so far aside from Asphalt 9, where the network times out (more resilient downloading is a different issue). Weirdly, Proton Drive, Proton VPN, and MiXplorer are all normal APKs, not XAPKs so it's concerning if those are having problems.

**Comment by ImranR98** [comment]
Tentatively closing, will reopen if there's an XAPK that doesn't work once downloaded.

**Comment by thaenalpha** [comment]
Hi, I have the same problem with Google Home from APKPure source.
![Screenshot_20230520_101735.jpg](https://github.com/ImranR98/Obtainium/assets/44464788/1320a638-fd7e-4657-bfd8-7813480aa1bd)

**Comment by DrIT2016** [comment]
I have also issue with xapk files it seems. In this case snapchat and discord have currently latest version only xapk on apkpure. 
So after install/update in obtainium both apps crash on startup (something with libclient.so or libkv_storage.so not found according to logcat).
When download older apk file directly downloaded from apkpure and install it, it works (and can be updated with Aurora store to latest version). Also current version from apkmirror (also an apk) works fine.
So for the moment i setted both to track only, otherwise app will be broken again on update when new version comes out.
