### ISSUE TITLE
Apkpure mobile url check?

### ISSUE THREAD

**Issue by BingoKingo** [ImranR98/Obtainium#543]
On mobile phone, user open Apkpure link in mobileview most, could you add check for their mobile url : https://m.apkpure.com/ ?

**Comment by ImranR98** [comment]
Because of the way the matching works, adding an additional check for subdomains would be a bit complicated. Instead you can manually pick APKPure from the Override dropdown in the latest version: https://github.com/ImranR98/Obtainium/releases/tag/v0.13.4-beta
