### ISSUE TITLE
"Bad state: No element" error

### ISSUE THREAD

**Issue by rodrigoswz** [ImranR98/Obtainium#549]
When I try to add any source or download any file I got this error.

Device: POCO F3
OS: Paranoid Android Topaz (Android 13)
App version: 0.13.1

![Screenshot_20230507-140421.png](https://user-images.githubusercontent.com/14058427/236878816-ada7115b-3ccd-4c56-8bd4-bf98edee0f0e.png)

**Comment by ImranR98** [comment]
Can you do an export and post it here?

**Comment by rodrigoswz** [comment]
Sure

[obtainium-export-1682966922656.zip](https://github.com/ImranR98/Obtainium/files/11423038/obtainium-export-1682966922656.zip)

**Comment by rodrigoswz** [comment]
Same problem

https://i.imgur.com/SqBS1dr.gif

**Comment by ImranR98** [comment]
Hmm. I tried the same app and had no problems. Could you try older versions of obtainium and let me know what the most recent version that worked is?

**Comment by rodrigoswz** [comment]
Done, the last one working perfectly is version 0.12.0
From 0.12.1 the error starts

**Comment by ImranR98** [comment]
So the issue is probably related to the new install plugin as that's what changed between 12 and 12.1.

It's possible that your custom ROM has some bug related to app installs or error catching because I have not been able to reproduce this on AOSP (with and without Gapps) or GrapheneOS even for older versions of Android.

Could you try installing an app through droid-ify and see if that works? Also post a screenshot of the install method setting page to make sure it's using the newer method.

**Comment by rodrigoswz** [comment]
> Could you try installing an app through droid-ify and see if that works? Also post a screenshot of the install method setting page to make sure it's using the newer method.

I tested every installer option and it works

![Screenshot_20230508-184241.png](https://user-images.githubusercontent.com/14058427/236942279-56ad7bfd-71cf-4a54-bb55-28f1caa06c8c.png)

**Comment by ImranR98** [comment]
Okay, might have been testing the wrong version before. Reproduced the error on an Android 7 emulator, looking into it.

**Comment by ImranR98** [comment]
Could you try the build attached here:

https://github.com/ImranR98/Obtainium/issues/541#issuecomment-1539400161

**Comment by rodrigoswz** [comment]
> Could you try the build attached here:
> 
> https://github.com/ImranR98/Obtainium/issues/541#issuecomment-1539400161

Works to add a new source, but I can't download anything yet (same error)

**Comment by ImranR98** [comment]
> Works to add a new source, but I can't download anything yet (same error)

Just to clarify you are able to add an app now, but still not install it?

**Comment by rodrigoswz** [comment]
> > Works to add a new source, but I can't download anything yet (same error)
> 
> Just to clarify you are able to add an app now, but still not install it?

Sorry, I went to test again now to confirm this but I must have been wrong. I still can't add or download apps.

**Comment by ImranR98** [comment]
Latest release has a change that might help - lmk if it changes anything.

**Comment by ImranR98** [comment]
Assuming it is fixed - lmk if the issue should be re-opened.

**Comment by BabyOilJohnson** [comment]
> Hi, I seem to be having this issue with the Addy.io app. Could you look into it, please? https://gitlab.com/Stjin/anonaddy-android/-/releases

Same here

**Comment by DarkCrypt** [comment]
@drakelight & @BabyOilJohnson
Addy.io works now, see issue #1697.
