### ISSUE TITLE
Add feature to "verify the release with author's PGP keys"

### ISSUE THREAD

**Issue by snazzybytes** [ImranR98/Obtainium#553]
Maybe a long shot, but would be nice to have the ability to verify the integrity and authenticity of the binary releases with authors PGP keys.  As you know, many android application releases come with i.e "manifest-v0.8.sig" "manifest-v0.8.txt" in the same directory you are already downloading the release from. That would be insanely cool and a step up cypherpunk move if possible 🚀. Obtanium^2 then in my opinion

**Comment by ImranR98** [comment]
Duplicate of #255
