### ISSUE TITLE
Unexpected Error: Null check operator used on a null value

### ISSUE THREAD

**Issue by BHydden** [ImranR98/Obtainium#561]
Trying to add Collabora Office to Obtainium. Get the above error for both the website apk and the official 3rd party f-droid repo.

`https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/`

`https://www.collaboraoffice.com/downloads/fdroid/repo/`

Pixel 6
Android 13
GrapheneOS
TQ2A.230505.002.2023050500

Obtainium Version 0.13.2

dev.imranr.obtainium
versionCode 2166

targetSdk 33
minSdk 23

Installed: 13 Mar 2023; 13:18
Updated: 13 May 2023; 09:12

![install screen](https://github.com/ImranR98/Obtainium/assets/28991649/47f1018d-0de2-478b-920b-3560cc7144e9)

![Error screen](https://github.com/ImranR98/Obtainium/assets/28991649/ec6ad122-1de4-41d0-b591-935821dcb2c9)

**Comment by BHydden** [comment]
In case its relevant, I can successfully download and install the apk manually. Error occurs whether app is already installed or not.

**Comment by ImranR98** [comment]
Whoops, made an assumption I shouldn't have. Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.13.3-beta

**Comment by BHydden** [comment]
Lightning response time man that's amazing! 
Issue fix confirmed after update ❤️
