### ISSUE TITLE
Changelog Touch Target Too Small

### ISSUE THREAD

**Issue by BabyOilJohnson** [ImranR98/Obtainium#565]
Happened after updated to v0.13.3
![Screenshot_20230513-231230](https://github.com/ImranR98/Obtainium/assets/101601874/caaa6f2d-85e1-4bb9-8046-ea175fa1c1be)

**Comment by ImranR98** [comment]
I didn't change anything - this is a design decision by the Flutter developers. I'll leave it as-is, but will make the touch target bigger (see https://github.com/ImranR98/Obtainium/issues/482#issuecomment-1546830676)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.4-beta
