### ISSUE TITLE
GitHub: Use Tags if no Release available in Track-Only mode

### ISSUE THREAD

**Issue by maof97** [ImranR98/Obtainium#566]
Really like this app, but some apps that only mirror to GitHub like Wireguard-Android just use Tags for new versions (https://github.com/WireGuard/wireguard-android/tags) so it would be nice to add a tracking function for that as well to be informed of new versions.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.4-beta

**Comment by maof97** [comment]
Wow that was fast. Thank you 🙏

**Comment by ImranR98** [comment]
No, you would just use it to track updates and get notifications. You'd still have to get the APK manually from somewhere else.
