### ISSUE TITLE
How to add project gitlab apk folder as source of apps?

### ISSUE THREAD

**Issue by huuhaa** [ImranR98/Obtainium#569]
How to add project gitlab apk folder as source of apps?

Example project:

https://gitlab.com/leos1/leosium/-/tree/main/Apks

**Comment by ImranR98** [comment]
Unfortunately it doesn't look like this is possible. The GitLab source is for APKs attached to the GitLab releases themselves, not files in the repo. You couldn't use web scraping to get files from this page either as the page uses JS to load items (there may be a more complex way to scrape this but not with the simple scraping that Obtainium uses).
