### ISSUE TITLE
Change how adding an application works

### ISSUE THREAD

**Issue by nvllz** [ImranR98/Obtainium#574]
Now, when you add a new app, the first thing the app does is download, and the app will not be visible in the Apps list until it has been successfully downloaded. It would be more convenient to add the desired application to the list first, so that you can download it from there whenever you want, in case of a bad connection or some other reason. In many cases, it would be more handy to have the application you've just added in the list even if it hasn't been downloaded yet.

**Comment by ImranR98** [comment]
This is already the case for sources that reliably provide the App's ID (package ID). For example, F-Droid or APKPure. For sources like GitHub, the only way to get an App's ID is by downloading it and checking the APK itself. We need the App ID for many reasons (existing install detection, avoidance of duplicate Apps, etc.), so we can't add the App without knowing it's package ID first.

The exception to this is track-only Apps and non-Obtainium imports, where Apps are added with a random number as an ID. In the case of imports this leads to problems with install detection (as noted at the bottom of the import export page) but these are fixed when the imported App is actually installed.
