### ISSUE TITLE
signal.org Unexpected Error FormatException

### ISSUE THREAD

**Issue by hpigot** [ImranR98/Obtainium#576]
Adding app by source url https://signal.org/ gives "Unexpected Error FormaException: Unexpected character (at character 17)"

Is the apk still available on Signal's website? I don't see it anywhere, and here https://signal.org/android/apk/ it just says "Loading...". If so, perhaps remove from README.md?

**Comment by ImranR98** [comment]
Hmm, yeah it says "Loading..." for me too but there is a network request being returned with the right APK URL so it's a surface level problem with the website. Hopefully temporary, but there's no need for web scraping now that I know what request is being sent to get that info.

Will fix in the next release. Request URL is https://updates.signal.org/android/latest.json

**Comment by ImranR98** [comment]
Actually, the problem is that that endpoint is not returning a `versionName` or `versionCode` so it wouldn't work (probably why the website is broken too). So we just need to wait for Signal to fix it on their end.

**Comment by ImranR98** [comment]
No longer an issue.

**Comment by hpigot** [comment]
Thanks Imran, and thanks for all the great work you're doing with Obtanium!
