### ISSUE TITLE
Support mirror sites

### ISSUE THREAD

**Issue by momobobe** [ImranR98/Obtainium#581]
There are mirror sites for sources like GitHub, F-droid (also self-hosted GitLab sites). Please consider to support them. No need to collect those mirror sites and build them in the app. Just provide an option (not conflicted to main sites) for users to fill in.

**Comment by ImranR98** [comment]
You should already be able to do this with the source override

**Comment by ImranR98** [comment]
So like custom sources that use the same logic as an existing source but for a different host. I think that has been brought up before but would add a lot of extra complexity - the source override serves that purpose already.
