### ISSUE TITLE
Cannot update any apks

### ISSUE THREAD

**Issue by arft1kwerg** [ImranR98/Obtainium#583]
Attempting to update any of the apps gives some empty(?) error message. On version 0.13.4.

![Screenshot_2023-05-19-22-34-51-711_com.google.android.packageinstaller.jpg](https://github.com/ImranR98/Obtainium/assets/29517963/ebf04f86-d68b-40ab-8c30-832c73a010a1)

![Screenshot_2023-05-19-22-35-01-915_dev.imranr.obtainium.jpg](https://github.com/ImranR98/Obtainium/assets/29517963/f41c4089-d3d2-4f49-8e2c-8a55c56f4c5a)

![Screenshot_2023-05-19-22-37-02-780_dev.imranr.obtainium.jpg](https://github.com/ImranR98/Obtainium/assets/29517963/8bcf660c-9fa6-4874-ad87-bec0c48c7c47)
)

**Comment by ImranR98** [comment]
What Phone/OS? Does this happen with Apps at random or some specific ones?

**Comment by arft1kwerg** [comment]
Among the apps where I can test to update the following throw similar errors:
![IMG_20230520_002835.jpg](https://github.com/ImranR98/Obtainium/assets/29517963/e6139241-9013-427d-bf6b-dd938936ff75)

As for phone specifications:
Android 11 RKQ1.200826.002
Since it is a Rednote (Mi 9t pro), it runs MIUI global 12.5.1

**Comment by CryptMaverick** [comment]
Have you tried force stop in app settings, clear cache and perform update process again? In my case it did, if that solves the problem, let us know here.

**Comment by arft1kwerg** [comment]
> Have you tried force stop in app settings, clear cache and perform update process again? In my case it did, if that solves the problem, let us know here.

Sadly it does nothing. Still get the same error when trying to update a variety of apps after clearing cache.

**Comment by ImranR98** [comment]
Haven't been able to figure this out given the info. Do you think you could install Flutter on your PC and try debugging the code?

**Comment by arft1kwerg** [comment]
Sorry. After spending 8 hours getting nowhere. I can set up the basic environment and enable usb-debugging, but I get stuck. I don't have the tech know-how or experience to properly run and debug android apps using Flutter. Only got a little experience with VSCodium.

**Comment by ImranR98** [comment]
@kawaiier could read #103 and see if the solution there works for you. If not, you should create another issue (the error is different from this issue).

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
I am having this same issue, might be able to give some more background. All of the apps in my case were already installed, with f-droid originally. I added the links to the source for each app into obtainium and uninstalled f-droid, and this error happens when attempting to update those apps. I can also confirm that clean installing the apps by first uninstalling and reinstalling does work - however this deletes app data which is a problem. I'm guessing this has something to do with the app being installed from another source.

**Comment by ImranR98** [comment]
@rsedxcftvgyhbujnkiqwe by "same issue" do you mean you're getting "empty" error messages like in arft1kwerg's screenshots? It sounds like your problem is just due to mixing f-droid and non f-droid apps. If that's the case then this is not an issue in Obtainium - Android just doesn't let you update an app with an APK signed using a different key. F-droid signs apps with their own key so trying to update an f-droid app with a github apk usually fails.

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
@ImranR98 
No I was getting "Conflict" in the error message. That makes sense, thanks I will just have to go ahead and reinstall the apps.

**Comment by EinderJam** [comment]
@ImranR98 I also have experienced this kind of error trying to update or straight up install apps from a GitHub source.
Phone and OS are the exact same as @arft1kwerg 

Remembering that MIUI optimization was often linked with issues installing apks, I went on to disable it in developer settings, and sure enough, Obtainium was able to update my apps afterwards.

**Comment by ImranR98** [comment]
With the latest release, the error message should no longer be empty - you should at least see an HTTP error code that might give us more info on this.

**Comment by ImranR98** [comment]
@arft1kwerg could you confirm if disabling MIUI's optimizations fixes this issue?

**Comment by arft1kwerg** [comment]
> @arft1kwerg could you confirm if disabling MIUI's optimizations fixes this issue?

Disabling MIUI optimization fixes the empty error messages and allows it to download/update some apps. Image with some apps that throw an error on update: ![Screenshot_2023-10-14-20-20-07-900_dev.imranr.obtainium.jpg](https://github.com/ImranR98/Obtainium/assets/29517963/a6b83e81-d4cd-414a-8952-71c3b9e3f156)

**Comment by ImranR98** [comment]
Great. These errors are unrelated. The first one means you're trying to update an app with an APK that has a different signing key, and the second one means the version code of the new APK is lower than the currently installed one.
