### ISSUE TITLE
Recognize App ID before fetching APK from repo sources like GitHub

### ISSUE THREAD

**Issue by momobobe** [ImranR98/Obtainium#588]
Downloading from some sources like APKpure, App ID can be recognized immediately as it's obvious, but for repo sources like GitHub, App ID is only shown after obtaining the APK file. However, since most repos contain the source code for apps, maybe we can try to get App ID from `applicationId` in file `build.gradle` at certain common positions in repo like `/android/app/`, `/src/app/`, etc. Of course there's no guarantee to work for all projects, but should work for common ones.
  
This is useful when the user just wants to take a full record (currently App ID is missing, which is critical) for a newly found app without downloading (and installing) it, since sometimes download could be painful and total unnecessary. Also with `build.gradle` more metadata, like `minSdkVersion`, `targetSdkVersion` could be added to information of apps.

**Comment by ImranR98** [comment]
Implemented: https://github.com/ImranR98/Obtainium/releases/tag/v0.13.6-beta

With sources (like F-Droid) where the package ID is in the URL, we can assume it will match the real App ID. On GitHub, the ID in `build.gradle` might not always match the one in the APK - for example, in situations where the beta and stable version of the App have different IDs but are on the same GitHub releases page (with beta on a separate branch of the repo). To account for this, there's a toggle on the Add App page (for GitHub Apps) which will disable the new ID inferring method.
