### ISSUE TITLE
Can't update app

### ISSUE THREAD

**Issue by BabyOilJohnson** [ImranR98/Obtainium#595]
Getting error when trying to update this specific app
Link: https://gitlab.com/Stjin/anonaddy-android
![Screenshot_20230530-102007](https://github.com/ImranR98/Obtainium/assets/101601874/3a653a1f-54df-4da7-91cf-585b1f2a66f8)

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.13.7-beta
