### ISSUE TITLE
APKPure apps are not filtered by architecture

### ISSUE THREAD

**Issue by maah** [ImranR98/Obtainium#598]
Apps from APKPure are not filtered by CPU architecture, and are wrongly detected as an update.  
The APKPure download page specifies the supported architecture(s) of the (X)APK so this should be trivial to implement.  

Example with Discord:
- This is the latest x86 update (v178.19): https://apkpure.com/discord-talk-chat-hang-out/com.discord/download/178019-APK
- This is the detected update (v180.15 - only supports arm64_v8a): https://apkpure.com/discord-talk-chat-hang-out/com.discord/download/180015-XAPK
- Download page used by Obtainium (v180.15, arm64_v8a): https://web.archive.org/web/20230531141106/https://apkpure.com/discord-talk-chat-hang-out/com.discord/download

Obtainium will install v180.15, making Discord crash on launch (because of the architecture mismatch).

**Comment by ImranR98** [comment]
Obtainium assumes that for any given version of an App, all architectures will be available. The latest version (along with all available APK URLs for that version) is grabbed, then that list is filtered for a specific architecture. That code applies to the "general" source on top of which all source-specific code is implemented. So reversing that for ApkPure is not so simple. Could probably be done through a "fallback to older releases" toggle like GitHub has, but not a high priority. Also not sure how/where the app would tell the user that APK filters work differently for APKPure compared to other sources.

**Comment by maah** [comment]
> Obtainium ***assumes*** that [...] all architectures will be available.

Which is never guaranteed for APKPure releases.

I'm not sure how Obtainium filters the version list, but since the supported architectures are show on the download page, unsupported ones could simply not be added to the list (as a workaround) in [getLatestAPKDetails()](https://github.com/ImranR98/Obtainium/blob/main/lib/app_sources/apkpure.dart#L33), no?
Either way, a "fallback to older releases" is likely necessary for APKPure, as many (but not all) apps unfortunately have this issue.

A "preferred architecture" setting could work, and be used by other sources for automatic detection too (e.g filenames like 
_app-arm64-v8a-release.apk_)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.1.16
