### ISSUE TITLE
Browsable list of packages

### ISSUE THREAD

**Issue by Hate9** [ImranR98/Obtainium#599]
I think it would make the app much more inviting to use, if there was some kind of curated list of packages to browse. It makes new app stores much less threatening, and can introduce people to new apps!

**Comment by ImranR98** [comment]
This was suggested in #68. I prefer not to have a fixed list of suggestions baked in to the app. We'd need an external API that can provide a reliable list of FOSS Android apps based on popularity, maintenance status, etc. and provides non-F-Droid URLs for them. If you have suggestions, please comment on that original issue.
