### ISSUE TITLE
Same app installed from different URL retains the old version.

### ISSUE THREAD

**Issue by rawalplawit** [ImranR98/Obtainium#602]
Having the same issue as #601 

Created a new issue as even after I switched from https://github.com/LNReader/lnreader to https://github.com/LNReader/lnreader-preview
but the version number didn't change. 

I basically deleted the old app and added the new link.

![image](https://github.com/ImranR98/Obtainium/assets/39916917/dd3a3a6f-31dd-4dbc-932f-2a78605b180a)
![image](https://github.com/ImranR98/Obtainium/assets/39916917/b8b8fed5-3358-4978-a77b-372ca357752e)
![image](https://github.com/ImranR98/Obtainium/assets/39916917/7bf1504c-d853-4112-bf53-94dbf97db18a)

**Comment by ImranR98** [comment]
You can see at the bottom of your second screenshot (of the Android settings page) that the version of the app really is 1.1.14. So it looks like the developer forgot to increment the version in their APK manifest.

You could open an issue on the app's repo to get this corrected. For now, you could turn off version detection for the app (use the pencil icon on the bottom left corner in Obtainium). That way, the real version of the app will be ignored and you can just get Obtainium to use the version string from GitHub.
