### ISSUE TITLE
Github release does not recognize package name

### ISSUE THREAD

**Issue by zeroadam** [ImranR98/Obtainium#604]
@zeroadam not the same issue. You should make a new issue and please attach an export file if you don't mind.

_Originally posted by @ImranR98 in https://github.com/ImranR98/Obtainium/issues/597#issuecomment-1574510841_

**Comment by zeroadam** [comment]
Please rename this appropriately.

I noticed this issue when I added the Aegis GitHub source via picking it from the search in the app. As requested here is the relevant section from the export file.

```
  {
    "id": "${packageName}",
    "url": "https://github.com/beemdevelopment/Aegis",
    "author": "Beemdevelopment",
    "name": "Aegis",
    "installedVersion": null,
    "latestVersion": "v2.1.3",
    "apkUrls": "[[\"aegis-v2.1.3.apk\",\"https://github.com/beemdevelopment/Aegis/releases/download/v2.1.3/aegis-v2.1.3.apk\"]]",
    "preferredApkIndex": 0,
    "additionalSettings": "{\"includePrereleases\":false,\"fallbackToOlderReleases\":true,\"filterReleaseTitlesByRegEx\":\"\",\"trackOnly\":false,\"versionDetection\":\"standardVersionDetection\",\"apkFilterRegEx\":\"\",\"autoApkFilterByArch\":true,\"appName\":\"\"}",
    "lastUpdateCheck": 1685760043185439,
    "pinned": false,
    "categories": [],
    "releaseDate": 1677536970000000,
    "changeLog": "## New features\r\n\r\n* Option to disable the backup reminder\r\n* Improved group selection dropdown during vault export\r\n* New translation: Hebrew\r\n* Updated translations\r\n\r\n## Fixed bugs\r\n\r\n* A crash could occur because a Toast was incorrectly created",
    "overrideSource": null
  },
```

**Comment by ImranR98** [comment]
This was due to the Aegis `build.gradle` declaring its package ID in a variable instead of directly: https://github.com/beemdevelopment/Aegis/blob/master/app/build.gradle#L27

I didn't know this was a thing, so did not account for it. Fix in a minute.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.8-beta

**Comment by zeroadam** [comment]
Awesome!! Confirmed fix from my end with the new release. Many thanks!!
