### ISSUE TITLE
Support for Proton App apks

### ISSUE THREAD

**Issue by Anonsignup37456** [ImranR98/Obtainium#606]
Hello, thank you for making this wonderful app. I made a github for the first time just to say thank you and add this suggestion. 

I think it would be very nice if you could support pulling the apk updates from https://protonapps.com/ for their apps if that is possible.

**Comment by ImranR98** [comment]
Is there any reason you can't use github for those apps? I'd like to keep dev/app-specific sources to a minimum. Besides, that page doesn't seem to include version numbers which would be needed.

**Comment by zeroadam** [comment]
ProtonMail and ProtonVPN are located on GitHub, but unfortunately ProtonCalendar and ProtonDrive are not "open source" yet. All of their apps are available to download their APKs from the https://protonapps.com site. As @ImranR98 mentions, it doesn't seem there would be a way to see when new releases are made available there as the version numbers don't seem to be listed.

**Comment by Sukii23** [comment]
Wouldn't it be more efficient to download proton apps through apkpure? they have all their apps there in an official way.

**Comment by github-deimos** [comment]
> Wouldn't it be more efficient to download proton apps through apkpure? they have all their apps there in an official way.

I confirmed Proton AG does not support apkpure. They specifically stated that those apks appear to be pulled from the google play store, but they are not official in any way. The only official way is google play/apple or protonapps.com. I've encouraged proton to setup a proper versioning scheme or their own fdroid repo.
