### ISSUE TITLE
[Enhancement] Improve alignment of Latest Version and Installed Version on app view page

### ISSUE THREAD

**Issue by ufUNnxagpM** [ImranR98/Obtainium#607]
Currently the App view page displays Installed Version and Latest Version as two text strings on separate lines, which can make it difficult to visually inspect the version diff due to the slight misalignment. For English, the misalignment is small but still noticeable.

# Current
<p align="center">Installed Version: vX.Y.Z</p>
<p align="center">Latest Version: vX.Y.Z</p>

# Proposed
(ignore the table borders, this is mainly just to show the alignment difference)

<table align="center">
  <tr>
    <td text-align="right">Installed Version:</td>
    <td>vX.Y.Z</td>
  </tr>
  <tr>
    <td align="right">Latest Version:</td>
    <td>vX.Y.Z</td>
  </tr>
</table>

It may also be a good idea to have the actual version values put in a monospace font as well to further help with the alignment

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.9-beta
