### ISSUE TITLE
After extensive deletions of all data from Obtaimium for the purpose of a clean restart, everything is always restored

### ISSUE THREAD

**Issue by DwainZwerg** [ImranR98/Obtainium#609]
Hello @ImranR98 ,
I would like to do a cleaninstall. To do this, I first deleted all the apps, checked that they are indeed no longer under "Android>data>dev.imranr.obtainium", cleared the cache and app data in settings, uninstalled the app, moved all backup files to my laptop, restarted my smartphone and reinstalled Obtainium via the latest APK from Github.
I didn't see an empty app list as expected, but all the apps exactly as I had seen them before I deleted the apps completely. Do you have any idea why this is happening?

**Comment by ImranR98** [comment]
No, that doesn't seem possible. Weird, not sure what's going on.

**Comment by DwainZwerg** [comment]
Now that I have done this procedure three times, it works the way I wanted it to. Strange. This has never happened to me before. If it can help: I have a Samsung Galaxy A3 2017-FL (SM A320-FL) with Android 8.0.0.
