### ISSUE TITLE
UI tweak: White screen in Web view

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#61]
When loading webview of an apps github page, screen flashes white. Hurts me 👀 at night. 
Keeping this dark in dark mode would be nice if possible. Perhsps wait for the page to load before displaying?

**Comment by S7venLights** [comment]
This issue is fixed in the alpha version

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.6.0-beta
