### ISSUE TITLE
Help adding Collabora Office from their website

### ISSUE THREAD

**Issue by m0byn** [ImranR98/Obtainium#610]
I am trying to add Collabora Office for Android from their official website [here](https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/). Whenever I click "install", it states the following error: Incompatible:[com.collabora.libreoffice.snapshot]. 

I am not sure whether the App is picking the correct version? 

Could anyone help me in this regard?

Keep up the good work! I just found this app some days ago and I really like this project :)

**Comment by ImranR98** [comment]
You can use the APK filter to make sure it grabs the right architecture APK. Something like 'arm64-v8a' for example.

**Comment by ImranR98** [comment]
Not an obtainium issue. Downloading/installing the apk manually also gives this error.

**Comment by m0byn** [comment]
This is not true in my case. I just installed the app manually and it worked without any problems.

**Comment by ImranR98** [comment]
When the obtainium install fails, the apk will be cached in /Android/data/dev.imranr.obtainium/cache. Could you try installing that one and see what it says

**Comment by m0byn** [comment]
It says the app was not installed as the package is not valid. Shall I try to delete it and reinstall it via obtainium?

**Comment by ImranR98** [comment]
It sounds like the apk obtainium grabs is different from the one you downloaded manually. Are you picking arm64-v8a for 07-13?

**Comment by m0byn** [comment]
I picked arm64-v8a for 07-04. I just tried to install arm64-v8a for 07-13 and got the same error as via obtainium! So it is apk related. Do you know the difference between the two?

**Comment by ImranR98** [comment]
No idea

**Comment by m0byn** [comment]
Ok. Can I make obtainium grab the oldest one of the arm65-v8a?

**Comment by ImranR98** [comment]
You can always put 07-04 into the filter but that would of course disable update notifications. There's no way to make it pick the oldest apk or ignore the newest one.

**Comment by m0byn** [comment]
OK thank you!

**Comment by m0byn** [comment]
BTW: amazing response time! Thank you very much for providing such an amazing application!!
