### ISSUE TITLE
Doesn't detect the right version

### ISSUE THREAD

**Issue by Turhvjbufv** [ImranR98/Obtainium#617]
I added [this link](https://gitlab.com/Nulide/findmydevice) to obtainium and I have 0.2.9 version installed and the app shows that the latest version on gitlab is 0.0.4 even tho 0.2.9 is the latest version( for some reason I can't upload the image currently I'll try again later)

**Comment by ImranR98** [comment]
0.0.4 was the last version with an APK attached: https://gitlab.com/Nulide/findmydevice/-/releases?after=eyJyZWxlYXNlZF9hdCI6IjIwMjEtMDYtMDYgMDg6MDg6MDMuOTAyMjg1MDAwICswMDAwIiwiaWQiOiIyOTQ4ODYwIn0
