### ISSUE TITLE
Provide separate subdomain for regex

### ISSUE THREAD

**Issue by deltahaze** [ImranR98/Obtainium#629]
In the case of trying to add PPSSPP from the [official site's download page](https://www.ppsspp.org/download/) Obtainium always states cannot find suitable release.

Is this behavior related to the apk belonging to the /files/ subdomain instead of /download/? I have attempted to use the following regex 
```
https://www\.ppsspp\.org/files/([A-Za-z0-9]+(_[A-Za-z0-9]+)+)/ppsspp\.apk
``` 
and it still fails. I want to add PPSSPP from the author's site instead of PPSSPP's GitHub, as the repo has no recent builds available. Perhaps it has to be added as a custom source.

**Comment by ImranR98** [comment]
Nothing to do with regex (which only applies to the file name anyways). The reason Obtainium can't find the APK link is because it is not part of the HTML of the page - it gets loaded in with JavaScript separately. With JS disabled, the page is empty. Obtainium can only scrape plain HTML right now.

**Comment by LooneyXIII** [comment]
sorry for re-opening this issues but  there a ways to take from the buildbot of PPSSPP (https://www.ppsspp.org/devbuilds/) where 
having a issue where there is entry in the PPSSPP Github (v1.3) that prevent us for getting updates (v1.17.1)

**Comment by privateemu** [comment]
@LooneyXIII Can you share your current script as far as you have it right now? I would like to get this working and seeing where you're at now would be helpful.

**Comment by RJNY** [comment]
Copying my comment from my emulation pack repo:
https://github.com/RJNY/Obtainium-Emulation-Pack/issues/4#issuecomment-2198321656

So if I `curl` their [development page](https://www.ppsspp.org/devbuilds/), the page is not generated by the backend, so it doesn't give us anything useful to regex. That would suggest that the page is generated by the front-end. With that in mind, I took a look at the dev tools network tab and this link popped out to me: https://builds.ppsspp.org/meta/history-20.json

This is just a theory, but I think we can do the following:
- use this as the preliminary link:  https://builds.ppsspp.org/meta/history-20.json
- Set the `latest_version = response[0].description`
- use the `latest_version` to populate the download link like so: `https://builds.ppsspp.org/builds/${latest_version}/ppsspp.apk`
- profit: https://builds.ppsspp.org/builds/v1.17.1-817-g13506d3d02/ppsspp.apk

I would have to still apply this logic to an obtainium script, but what are your thoughts?
