### ISSUE TITLE
Checksum 

### ISSUE THREAD

**Issue by Baker0o7** [ImranR98/Obtainium#63]
Hi Sir , it will be nice from you if you can add checksum feature where by it can be configured manually thank you always 👍

**Comment by ImranR98** [comment]
Not sure how that would work. The App Sources (GitHub etc.) don't provide a checksum (even if they did I'm not sure what the point would be of grabbing the verification checksum from the same place as the APK itself). Do you mean letting the user enter a checksum manually for Obtainium to compare with the APK it downloads? That would be inconvenient as the value would change with each version (would be even more tricky with background updates if/when those are added)

**Comment by Baker0o7** [comment]
@ImranR98 exactly just like you said sir

**Comment by Baker0o7** [comment]
![Screenshot_20221022-221055_FastHub-RE_1](https://user-images.githubusercontent.com/113295927/197358504-38b1c6b1-ea94-4a39-acaf-d185e3f0f414.png)

**Comment by Baker0o7** [comment]
Some they provide checksums like the above pic👍

**Comment by ImranR98** [comment]
Manual checksum input just isn't practical as they change on every app release, and will cause problems with unattended installs. For Sources that provide checksums (if any, I don't recognize the one from your screenshot and it isn't currently supported), I still don't see the point of trusting a checksum from a source if you don't trust binaries from the same source.
