### ISSUE TITLE
Can not install update, supposedly the version is older

### ISSUE THREAD

**Issue by Tealk** [ImranR98/Obtainium#632]
I get the following error message when I try to install the update of Weatherfly 3:
![Screenshot_20230627-092159.png](https://github.com/ImranR98/Obtainium/assets/12276250/199ad6be-f021-49d7-9395-6efb5b3784d6)

![Screenshot_20230627-092204.png](https://github.com/ImranR98/Obtainium/assets/12276250/08244182-df19-499c-8af3-b3e0fccc9dfa)

**Comment by ImranR98** [comment]
What's the versioncode for your currently installed version? The latest is 1083 (I can't look at the previous one as they have removed older releases). Most likely issue is that the dev is not versioning their releases correctly.

**Comment by ImranR98** [comment]
You can see in the screenshot the versioncode for 0.1.7-beta is 2096, which is higher than the versioncode for 0.1.8-beta (1083).

Android uses this versioncode to prevent downgrades - it's not an Obtainium issue (if you try updating to 0.1.8-beta manually you should also get an error).

Developers are not supposed to use lower versionCodes for newer builds of an app.

**Comment by Tealk** [comment]
i have never looked at the versioncode, i thought it always checks the version itself
thanks for the info
