### ISSUE TITLE
Update all UI tweak

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#64]
When downloading all updates, the installation doesn't begin until all downloads complete, which is fine. But when each apps download completes, the text changes back to 'update available'. I'm thinking it may be confusing to new users, they may think the download failed and begin trying to download it again.
Perhaps the text should change to Waiting… 
instead.

**Comment by ImranR98** [comment]
Didn't mean to close this yet. Looks like GitHub does that automatically if the commit message says it should.

**Comment by S7venLights** [comment]
This issue is fixed in the alpha

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.6.0-beta
