### ISSUE TITLE
Dank Chat update issues.

### ISSUE THREAD

**Issue by Toiletmason** [ImranR98/Obtainium#641]
It doesn't give you the option to pick between the signed release apk, or the debug release.  It gets confused about which one is the most recent. Maybe there is an option already and I'm just a moron. There is a good chance.

**Comment by ImranR98** [comment]
I only see one release here: https://github.com/flex3r/DankChat/releases

**Comment by Toiletmason** [comment]
I would guess that the debug release option is only available at certain times. That could be part of the problem I guess.

**Comment by ImranR98** [comment]
That is the issue - not something Obtainium can fix. You can always use the "include prereleases" and "release filter" options assuming the dev has some consistency in those labels/titles.

**Comment by Toiletmason** [comment]
@ImranR98 Check it now and you'll see what I mean.
