### ISSUE TITLE
Codeberg.org source using incorrect releases 

### ISSUE THREAD

**Issue by mickelsonmichael** [ImranR98/Obtainium#642]
To recreate, add https://codeberg.org/Lacerte/clima either directly or via the search function. Notice Obtainium reports v2.0.0 as the latest version, which is significantly older than the >3 version available from the repo. 

The archived GitHub reports v2.0.1 as the latest release, which is much closer in version but not exact https://github.com/Lacerte/clima/releases

Obtainium v0.13.12-beta

**Comment by ImranR98** [comment]
v2 is the latest release that actually has an apk available.
