### ISSUE TITLE
Package parse error

### ISSUE THREAD

**Issue by 0-Il** [ImranR98/Obtainium#643]
Trying to install https://github.com/SimpleMobileTools/Simple-Camera returns this error
![error](https://github.com/ImranR98/Obtainium/assets/110241471/01ca16ca-5aa4-4551-a9ff-6e6a7a94a2f2)

**Comment by rabywastaken** [comment]
I'm getting that exact same error while trying to install this: https://apkpure.com/screen-orientation-control/net.mm2d.android.orientationfaker/

**Comment by ImranR98** [comment]
Could you both try to download and install the APKs manually? Just want to rule out OS/APK issues.

**Comment by 0-Il** [comment]
@ImranR98, tried to install manually, and you are right: my Android version (7.0) is not supported by Simple Camera. 5.3.1 was the last release my Android version supports. So no problems on your app's side.

**Comment by rabywastaken** [comment]
Never mind, same here, I'm running this on an ancient tablet running Lineage OS 14.1 (Android 7.1) and Screen Orientation Control only supports Android 8 and up. Thanks for the help, you can close this issue.

Also, support root installation in the background when? :P

**Comment by ImranR98** [comment]
See Issue 25
