### ISSUE TITLE
Add Collabora Office repository

### ISSUE THREAD

**Issue by RustoMCSpit** [ImranR98/Obtainium#645]
https://www.collaboraoffice.com/downloads/Collabora-Office-Android-Snapshot/

**Comment by ImranR98** [comment]
I prefer to keep the number of app-specific sources to a minimum (sources that only serve a single app or a few apps from one company).

You can already add the Collabora page as an HTML source. Use the "filter APKs" option with something like "v8a" to specify the APK variant you want.
