### ISSUE TITLE
Prioritize Obtainium over other apps

### ISSUE THREAD

**Issue by novocaiin** [ImranR98/Obtainium#655]
At first I thought #377 is what I'm looking for but that issue seems to be concerned with just the visual sorting, not the actual installation order.

Right now, if multiple updates are available, Obtainium gets updated last. That makes sense from the standpoint of not having to relaunch it to update the rest of the apps.

But it might make more sense to update Obtainium first, so the rest of the apps are updated using the latest Obtainium version with potentially improved mechanisms or squashed bugs.

Not sure if this would be more viable if/when #25 is implemented.

**Comment by ImranR98** [comment]
As far as I know, there's no way for Obtainium to re-open itself after an update, meaning users would need to manually re-open it for the remaining apps to be updated. This would make for a bad UX - if someone chooses to update multiple apps, Obtainium should not close itself without doing so.
