### ISSUE TITLE
Remove / disable showing non-installed apps

### ISSUE THREAD

**Issue by deadcombo** [ImranR98/Obtainium#656]
Hi,

I usually uninstall apps from my launcher and this leaves me with non-installed apps in Obtainium.
I don't have any use for non-installed apps and I'd prefer apps were removed from Obtainium or to disable the feature altogether so I don't have to cleanup on every uninstall.

Thank you for the indispensable app.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.15-beta
