### ISSUE TITLE
Option to disable checking for updates when opening an app

### ISSUE THREAD

**Issue by cohesive-flight** [ImranR98/Obtainium#659]
I get rate limited often, so I get spammed with rate limit messages just for clicking on any app in my collection. 
I'd also like to just view the apps I have in my collection, but it moves/sorts the apps around on first launch.

An option to disable checking for updates when clicking on an app and to disable the sorting that occurs on first launch would be great.

**Comment by ImranR98** [comment]
An option to disable auto-checking on the app page can be added. Not sure what you mean by auto-sorting - apps get loaded in one at a time, so if you have a very large number of apps it might take a while for all of them to load in (might look like moving around/rearranging).

**Comment by ImranR98** [comment]
There's already an issue open to improve load times. For rate limiting, background update checks already pause on rate limit and continue later. Foreground update checking is manual so it wouldn't make sense to pause/delay (when you pull to refresh, the apps checked first are the ones that haven't been checked in the longest time so repeated delayed pulls will eventually cover them all).

**Comment by ImranR98** [comment]
> What if you could make the loading to only update the list visually once it's complete

This is how things used to be, but someone suggested it would be better to be able to interact with already-loaded apps even while other apps are still being loaded in. Matter of personal preference, I prefer the current way too.

> In the meantime displays what the list was right before the app was closed?

Not practical as the user might try to interact with outdated data before the updates have been loaded in. For example if an app was uninstalled externally and the new "remove on uninstall: option is enabled, the app will be removed on first load. But if we show the user an old app list, that app would appear to still be installed and the user would even be able to change it's state (could lead to weird behaviour).

**Comment by ImranR98** [comment]
Added the toggle: https://github.com/ImranR98/Obtainium/releases/tag/v0.13.15-beta

The rest of your concerns are covered by #579

**Comment by ImranR98** [comment]
I don't think it's worth the added complexity (but PRs are welcome).
