### ISSUE TITLE
Feature request: Disable "new installs" by default when tapping on update button

### ISSUE THREAD

**Issue by rak-rak** [ImranR98/Obtainium#66]
Hi, please disable "new installs" by default when tapping on update button.

Reason:
Usually users have a number x apps in the list that are _installed_ on device. Additionally they have y apps in list that are _not installed_, but just being observed.

Now when there is an update for one of the x installed apps, and when now tapping on update button, you will be asked in popup windows to update that app and also install those y apps that are not installed. And it's already enabled. 
So everytime you have to disable installing of those y apps. And be warned, don't forget this to do.

It would be easier, when "new installs" is disabled in popup by default. So users can enable it when needed.

**Comment by ImranR98** [comment]
This makes sense, will add it at some point (probably after resolving #14).

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.6.0-beta
