### ISSUE TITLE
Support Tor Browser

### ISSUE THREAD

**Issue by xmha97** [ImranR98/Obtainium#660]
Please support the Tor Browser.

https://www.torproject.org/download/#android

**Comment by ImranR98** [comment]
This already works with the HTML source (use it with the APK filter option)

**Comment by nichu42** [comment]
Is it possible to parse the version from the file name?

**Comment by ImranR98** [comment]
Not for a source that needs to be so general.

**Comment by ImranR98** [comment]
> Is it possible to parse the version from the file name?

Will be adding this in the next version (see #861). But it's a general solution so will require user-defined regular expressions.

**Comment by nichu42** [comment]
> > Is it possible to parse the version from the file name?
> Will be adding this in the next version (see #861). But it's a general solution so will require user-defined regular expressions.

Excellent! That's exactly what I was looking for.
