### ISSUE TITLE
Regex Version Detection

### ISSUE THREAD

**Issue by SkyNinja** [ImranR98/Obtainium#665]
I'm using Obtainium to install the non-play store version of Private Internet Access. Using the web page as the source and a regex to catch the right link, it installs fine but obviously can't detect a version number. The app filename, however, includes the version number like so:

`pia-android-3.18.0-10581.apk`

I've seen some other apks include the version number before, too. I think having an option to pull the version number from the filename/url with a regex would be super helpful.

Thanks for the awesome app, btw. I've been using it for less than a week and it's already a vital part of my setup.

**Comment by ImranR98** [comment]
While this could be added, I don't think it's worth the added complexity.

Right now, the entire APK URL (not just the filename) is used to generate a "pseudo-version" that can be tracked for changes (meaning you will still get update notifications even though the version you see is a random looking number). This covers the highest amount of possible cases (for example, where the APK filename is always constant but some other part of the URL changes, like `https://example.org/app/v1.1/app.apk` => `.../app/v1.2/app.apk`). So it  would be best to keep using that method, meaning any version string extracted from the filename with a regex would be for display/appearances only (but would still require the extra settings, parsing logic, and changes to the page view).
