### ISSUE TITLE
Possible to add Kali Nethunter app store to supported sources?

### ISSUE THREAD

**Issue by p1asticfantastic** [ImranR98/Obtainium#668]
Would it be possible to add the Kali Nethunter repository to supported sources? Kali has its own F-Droid style app and the repo can be added to standard F-Droid as a third party repo, which is how I search it now.

https://store.nethunter.com/en/

F-Droid repo: https://store.nethunter.com/repo

**Comment by ImranR98** [comment]
No point adding this when you can already add third party f-droid repos
