### ISSUE TITLE
Not seeing beta versions on F-Droid

### ISSUE THREAD

**Issue by Trebor87** [ImranR98/Obtainium#672]
Have just installed and trying your app, very nice, thanks

I have several programs that I run in their beta versions from F-Droid, Fedilab for instance :

Your app see's Latest version as 3.21.2, Installed version as 3.22.2 (which is the latest beta version) so it tries to to update to the old official version, which then gives an error, normal

Can you get it to check the betas versions as well ?

many thanks

**Comment by ImranR98** [comment]
I don't see any beta versions here https://f-droid.org/packages/fr.gouv.etalab.mastodon/

Is there another page you're looking at?

**Comment by Trebor87** [comment]
Hi

You need to opt in to the beta version, though it seems there are none for the moment

I've included four screen shots for you, showing errors, amethyst and Fedilab

Hope it helps
Regards
Trevor

15 Jul 2023 13:49:22 Imran Remtulla ***@***.***>:

**Comment by ImranR98** [comment]
How do you opt in on the f-droid website? Also I don't see any screenshots (might be better to upload directly on github rather than via email).

**Comment by Trebor87** [comment]
Here's the link published by Fedilab

If you like to test new features before others don't forget to become a beta tester.
#FDroid : https://fdroid.fedilab.app/


I'll upload again my screen shots by github later

Have two errors, Fedilab and Amethyst

Regards
Trevor

15 Jul 2023 14:19:27 Imran Remtulla ***@***.***>:

**Comment by ImranR98** [comment]
The link you gave is to a third party f-droid repo which comes with beta versions. This is different from the official f-droid source, which does not have them.

So if you want beta apps, you need to add https://fdroid.fedilab.app/repo and select "third party f droid" in the "Source Override" dropdown. Then fill in the app id and click add.

**Comment by ImranR98** [comment]
This works, tried it: 
![Screenshot_20230715-084738](https://github.com/ImranR98/Obtainium/assets/30463115/d14de444-44ab-45a4-a09a-088ce60a38ec)

**Comment by ImranR98** [comment]
Note that apks from the fedilab third party repo might be signed with different keys than the apks from f-droid, so you might not be able to mix updates from those sources - you will need to uninstall/reinstall.

**Comment by Trebor87** [comment]
Thanks for the info, have changed as suggested the Fedilab in your app, now shows the correct version

Now have to suss out the amethyst error, will play with that a little later

Bravo for your app and the feedback 👏😁
Trevor

15 Jul 2023 14:50:55 Imran Remtulla ***@***.***>:
