### ISSUE TITLE
clicking a tab left of another tab causes a left swoop animation and not a right one

### ISSUE THREAD

**Issue by RustoMCSpit** [ImranR98/Obtainium#675]
bug

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.17-beta

**Comment by RustoMCSpit** [comment]
> https://github.com/ImranR98/Obtainium/releases/tag/v0.13.17-beta

it's bugged, only works if the tab is adjacent the tab. jump from settings to apps and it gives a left swoosh

**Comment by RustoMCSpit** [comment]
to be honest, the animation should be an option to be on in the first place in the settinfs. thanks for the amazing app

**Comment by RustoMCSpit** [comment]
oh this is bizarre, it works sometimes but doesnt other times

**Comment by RustoMCSpit** [comment]
sometimes it keeps throwing me back to the apps section withour prompt, should i scrren record and send??

**Comment by ImranR98** [comment]
Yes, a recording would help. Works every time on my phone
