### ISSUE TITLE
Enhancement Idea: Make adding apps easier

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#68]
May help some new users who don't have github accounts to Include a lists of common apps to choose from to add. It could be a menu within the import/export tab. 

Apps like: 
Auroura Store
Browsers
Messengers
Simple Apps Suite
Mail apps
Map apps
and other common. 

I could put together a list if you like.

The user can make a selection of apps to add and then when they click add Obtanium generates an import file with all the correct preferences (regular expressions etc) needed and adds the apps. 

There could also be a warning that some apps releases are not available anywhere but F-droid or Aurora Store.

**Comment by S7venLights** [comment]
Another Idea is to import from people F-Droid library: 

In F-droid for each app there's a tab for

**Comment by S7venLights** [comment]
Alternatively/aditionally Neostore has a feature where it links to get up with an icon in the top right that looks like this: 
</>
and people could click that and obtainium could be set as the default app for github links and add the app that way.

**Comment by S7venLights** [comment]
Now I don't know if its possible but if already installed apps declare there package name, and obtanium can access this, it could pull that and search f-droid with them and scrape Git links. This way the user need only click one button to import all their installed apps that have Git links.

**Comment by ImranR98** [comment]
Not sure how I feel about hardcoding a list of recommended Apps. A better approach would be to query an external list that changes based on popularity/ratings, like most app stores do. I don't think GitHub provides anything like this (at least for Android apps specifically) but maybe someone else does.

For the other suggestion, it's basically a feature that takes an F-Droid link and converts it to a GitHub link. Definitely doable but I'm not sure if it's worth doing, maybe there should be an external service for that. In general, I'm not a fan of how F-Droid APKs are not compatible with those from other sources (can't update from one to another). Taking people's currently installed F-Droid Apps and giving them a GitHub link could cause problems.

I'll leave this issue open but not sure if it (the F-Droid part) will be implemented. Definitely will add a recommended Apps list if there is a good external API for it.

**Comment by S7venLights** [comment]
Well my main thinking here is finding an easier way for people to get there FOSS app library moved over, copy pasting one link at a time is tedious. 
That's why I thought a list of common apps most people use I choose from in app could help. 

But perhaps the 2nd last idea I posted of Neostore is easiest to implement.
It would at least remove the need to copy paste github links.

To clarify, Neostore already makes the github/lab links accessible in one click, all you need then is for Obtanium to register itself as a default app for Github and Gitlab links and have it ask whether to add apps when links are opened.

and lastly have an explainer linked somewhere so people know about that option.

**Comment by ImranR98** [comment]
Opening GitHub links by default wouldn't work on new versions of Android, as discussed in #51.

**Comment by S7venLights** [comment]
It does work, for me at least.

**Comment by ImranR98** [comment]
With what App? As far as I can tell, Apps on Android 12 can only open links to websites if the website has approved the App.

**Comment by S7venLights** [comment]
With Octodroid. But it's because I changed normal android settings to make Octodroid open Github links. 
Go to settings/Apps/Default Apps/opening links
or
just search settings for 'Opening links'

Then turn on Instant apps
and you can allow apps to open a custom list of supported apps.

There is even an android 'Activity' to launch the 'Opening links' settings menu. 
So you could add a button in Obtanium. 

PS. 
Droidify now also has a button to directly open Git links too.

**Comment by S7venLights** [comment]
# Obtanium could be set to open Git links in the same fashion but it currently doesn't appear in the instant app list.

**Comment by ImranR98** [comment]
As far as I can see, this can't be done for HTTP links on Apps that target Android 12. From what I can tell, [Octocat targets an extremely old version of Android](https://github.com/slapperwan/gh4a/issues/1132), so it is not subject to the new limitations ([here's a comment on the Neo Store repo saying the same about F-Droid](https://github.com/NeoApplications/Neo-Store/issues/345)). For Neo-Store, it looks like [they are using a custom scheme](https://github.com/NeoApplications/Neo-Store/issues/200) (not HTTP) to open F-Droid repo links; I didn't see anything about supporting GitHub or other regular HTTP links.
I tried to get this to work anyways using [this plugin](https://pub.dev/packages/app_links/example), but had no luck.

Closing this issue for now as it doesn't seem doable, but will re-open if anything changes.
Also for the other suggestion about recommended Apps, I think it's best to leave that up to the user; besides idk where the App list could come from or if it's really a good idea to rely on an external source (using an internal hardcoded list has it's own issues).

**Comment by S7venLights** [comment]
Too bad, okay 👍

**Comment by S7venLights** [comment]
At least people can long click on the </> button in Droidify and Neostore to more quickly copy the Git link. 
Perhaps you can just put that advice in the import tab of Obtanium. 
It could say:
Quickly copy Git links of F-droid apps by long pressing the </> button in Droidify or Neostore.
If the repo has an APK release, Obtanium can add them.

**Comment by S7venLights** [comment]
https://github.com/ImranR98/Obtainium/issues/68#issuecomment-1295849929

Is still possible in theory, perhaps a bit hard to do.

**Comment by S7venLights** [comment]
Another thing that could be done is creating a crowd sourced table of android apps released on Gits and grouping the app and package name to the Git link. 
Then make it so the user can search and select the apps they want, and mark them then output a list of Git links. 

https://getgrist.com could be a good platform for this, but I don't have time for such a project.

**Comment by Hate9** [comment]
Off the top of my head, https://github.com/offa/android-foss is regularly updated, crowdsourced to some degree, has regular formatting so it'd be very easy to scrape, and lists both fdroid and non-fdroid links.

**Comment by ImranR98** [comment]
> Off the top of my head, https://github.com/offa/android-foss is regularly updated, crowdsourced to some degree, has regular formatting so it'd be very easy to scrape, and lists both fdroid and non-fdroid links.

This could work

**Comment by candroid-man** [comment]
We can turn Obtainium into a standard app store like Droid-ify, but then when you go to install the app it will go out to the source (GitHub, GitLab, etc.) and grab the latest .APK automatically, and install it rather than downloading it from the repository.

I think you should still be able to manually add apps in case there is some error or something, but I feel like this approach would make Obtainium much more user friendly and simple.

**Comment by ImranR98** [comment]
> We can turn Obtainium into a standard app store like Droid-ify, but then when you go to install the app it will go out to the source (GitHub, GitLab, etc.) and grab the latest .APK automatically, and install it rather than downloading it from the repository.

I think this would be out of scope - not something I want to include in the app itself.

Someone suggested creating a site where people can submit crowdsourced Obtainium configs for apps (#1214). I think this is better than relying on https://github.com/offa/android-foss as suggested earlier because the suggestions there are not guaranteed to work with Obtainium (user-submitted JSON configs would be). Especially now that it's possible to one-click import an app directly into Obtainium (see https://github.com/ImranR98/Obtainium/issues/368#issuecomment-1858777494). Closing this issue in favour of #1214.
