### ISSUE TITLE
Track-Only option bug

### ISSUE THREAD

**Issue by TangyWrecker** [ImranR98/Obtainium#680]
When the "Track-Only" option is activated, the text is shifted to the left.

![Screenshot_20230716-025839_Obtainium](https://github.com/ImranR98/Obtainium/assets/86275501/bc45d458-9f2b-4ee3-a575-c16128f1c860)
![Screenshot_20230716-025843_Obtainium](https://github.com/ImranR98/Obtainium/assets/86275501/880c6a33-1c7d-4b08-a77f-2743389bfae5)
![Screenshot_20230716-025757_Obtainium](https://github.com/ImranR98/Obtainium/assets/86275501/12da432e-28b5-43a0-a75e-04fd4b973b0e)
![Screenshot_20230716-025811_Obtainium](https://github.com/ImranR98/Obtainium/assets/86275501/d8815265-362f-403d-8d5e-a53390c75f47)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.18-beta
