### ISSUE TITLE
personalDNSfilter github and website issues

### ISSUE THREAD

**Issue by AlphaElwedritsch** [ImranR98/Obtainium#681]
hi at all
personalDNSfilter is releasing in github only sources and apks on their website
but to add the website no version will founded.
is there any solution?

thanks

https://www.zenz-solutions.de/personaldnsfilter-wp/

https://github.com/IngoZenz/personaldnsfilter/releases

apk download link:
https://www.zenz-solutions.de/?sdm_process_download=1&download_id=65

**Comment by ImranR98** [comment]
It's better to keep the number of App-specific Sources in Obtainium to a minimum. You can add their F-Droid version instead: https://f-droid.org/en/packages/dnsfilter.android/
