### ISSUE TITLE
Swipe animation

### ISSUE THREAD

**Issue by RustoMCSpit** [ImranR98/Obtainium#683]
1) make it an option 
2) currently it is inverted, going right causes it to fall left and not fall right

**Comment by ImranR98** [comment]
It will be made optional in the next release.

I think the current directions make sense. If you're switching to a page on the right, it should "come in" from the right (right to left).

**Comment by RustoMCSpit** [comment]
> It will be made optional in the next release.
> 
> I think the current directions make sense. If you're switching to a page on the right, it should "come in" from the right (right to left).

this in itself could also be an option called 'swipe direction'

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.18-beta

**Comment by RustoMCSpit** [comment]
you work so fast holy shit
