### ISSUE TITLE
Versions of installed apps not updated on updates check

### ISSUE THREAD

**Issue by tsiflimagas** [ImranR98/Obtainium#684]
I don't know how the app currently works, but it seems that it saves a snapshot of the versions of currently installed apps and then only updates the versions of the apps updated by it. The problem with this is that there can be many scenarios where an app gets a newer version outside of obtainium, but obtainium keeps indicating that there's a newer version, while there's not. So, I think the right way is to update the versions of installed apps on every refresh.

**Comment by ImranR98** [comment]
This is already being done for all apps that have "stabdard version detection" enabled. It can't be done for all apps due to issues with version formatting.

**Comment by ImranR98** [comment]
Is there a specific app you're seeing this with even when standard version detection is enabled?

**Comment by tsiflimagas** [comment]
You're right! It does so already indeed. I don't know how it happened so I got that impression. It's been a few weeks maybe since I migrated apps to a new device and obtainium would somehow suggest many false updates. But now I tested by importing an old export and it behaved as expected, except for BreezyWeather. I also remember it would insist providing an update for OrganicMaps but I can't reproduce it now. Maybe the version I used at that time had some issue in this regard.

**Comment by tsiflimagas** [comment]
Well, nevermind. Version detection was disabled (and somehow unavailable) for these apps. After resetting install status I could enable standard version detection and now it works fine. Tbh some options were a bit confusing to me and didn't bother much changing them, but I think I'm getting my head around them.
