### ISSUE TITLE
Not finding latest version

### ISSUE THREAD

**Issue by Zumux** [ImranR98/Obtainium#697]
Seems obtanium can't find the versions after 4.2.3 for Aurora Store

**Comment by ImranR98** [comment]
In recent versions aurora store apks have been attached in a way that cannot be scraped without using the gitlab api. You should create a gitlab api key and enter it in the settings, you should see newer releases after that. See issue #3.

**Comment by ImranR98** [comment]
Should be possible. Feel free to open another issue for it.

**Comment by sereksim** [comment]
After adding the API key, the new version is found by Obtainium, but the download from https://auroraoss.com/AuroraStore/Stable/fails with the error 403: Forbidden.
-> It still is not possible to update Aurora with Obtainium :(

**Comment by ImranR98** [comment]
The APK is hosted externally, not on GitLab, and the external site is blocking requests from Obtainium. See #854.

**Comment by ImranR98** [comment]
This is due to a recent change on their end - it used to work.

**Comment by DwainZwerg** [comment]
According to https://gitlab.com/AuroraOSS/AuroraStore/-/issues/1052#note_1778388859, the Aurora Store devs have fixed the problem. The download of AuroraStore should work normally again.

In addition, @akramer-zibra is working on a [PR](https://github.com/ImranR98/Obtainium/pull/1411) to avoid such problems with other websites that are protected by Cloudflare.
