### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by ImranR98** [ImranR98/Obtainium#70]
Obtainium has had several new features and bugfixes in the past few weeks, and this has resulted in messy, convoluted code - mainly because I've prioritized getting things to work quickly. That has probably already resulted in some hidden bugs and things will only get messier over time.

The code needs to be cleaned up to make it easier to maintain and debug.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.6.7-beta

**Comment by S7venLights** [comment]
Must have been a task… well done
