### ISSUE TITLE
Not all app versions are visible

### ISSUE THREAD

**Issue by advait404** [ImranR98/Obtainium#701]
I am trying to install yt revanced extended from https://github.com/revanced-apks/build-apps/releases/download/147/youtube-revanced-extended-v18.25.40-all.apk

However, I am not able to select it since only 7 out of the 30+ variations from the release is visible.

**Comment by ImranR98** [comment]
Some of the APKs contain CPU architectures (like "arm-v8a") so Obtainium tries to use that to filter out all APKs that it thinks are not meant for your device architecture. For some reason your repo provides architecture-specific APKs for many apps but not Youtube so the youtube APK gets filtered out.

To avoid this, turn off the "Attempt to filter APKs by CPU architecture" toggle.
