### ISSUE TITLE
App log contains github access token

### ISSUE THREAD

**Issue by 1xFF** [ImranR98/Obtainium#714]
Possible security issue if any error like this shows up in a bug report
EX:

> 2023-07-18 23:47:32.390: info: BG update checking encountered a ClientException with SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = api.github.com, port = 48646, uri=https://1xFF:MY TOKEN@api.github.com/repos/ImranR98/Obtainium/releases?per_page=100, will schedule a retry check in 15 minutes

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.22-beta

**Comment by BabyOilJohnson** [comment]
The PAT is showing up in the app log again.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.11-beta
