### ISSUE TITLE
VLC: Grab New Mirror Link at Download Time

### ISSUE THREAD

**Issue by jcperil** [ImranR98/Obtainium#715]
When you pull to refresh VLC Player, it shows internal server error.

https://github.com/ImranR98/Obtainium/assets/89805719/2e7843ac-7c11-4759-83c3-92d25b4f2a20

**Comment by ImranR98** [comment]
Haven't been able to replicate this. You've added it as a GitLab source, right?

**Comment by jcperil** [comment]
No. As it defaults to HTML, I thought maybe it was appropriate.

Anyway, I added a regex to filter the correct apks and I no longer receive the internal error.

Please close this issue as you see fit. It is resolved from my end. Thanks.

**Comment by XxTriviumxX** [comment]
I have the same issue. cannot install vlc at all. 

on "add source url" i put https://www.videolan.org/vlc/download-android.html.

does not download. I can provide more info upon request.

**Comment by ImranR98** [comment]
@XxTriviumxX the first page does not have APK links, and the second does not have APKs in the releases section.

**Comment by XxTriviumxX** [comment]
hi!  can you help me?  what url should i use?

**Comment by ImranR98** [comment]
The only only official vlc source that i can find that will work with obtainium is their f droid repo.

**Comment by XxTriviumxX** [comment]
this is from Release v0.11.12-beta release notes:

> Render Changelog as MarkDown (https://github.com/ImranR98/Obtainium/issues/369) (for some Sources) + VLC as a Source (https://github.com/ImranR98/Obtainium/issues/367) by @ImranR98 in https://github.com/ImranR98/Obtainium/pull/371


what did adding vlc as a source do? Also "added to source" are telegram and signal. What does the "adding app to source" function do?

If you added vlc to source it should be readily available right? why do i have to download it from the f-droid repo instead?

I really need some explaination about that source feature.. just kinda confused here LOL

**Comment by ImranR98** [comment]
@XxTriviumxX oh wow, sorry I totally forgot we had that as a source 😂

The first link you added should work - I just tried it. What error do you see?

**Comment by XxTriviumxX** [comment]
i had internal server error, but now its:

> warning. the app source is videolan.org but the release package comes from plug-mirror.rcac.purdue.edu. Continue?

should i continue?

**Comment by ImranR98** [comment]
Yes, that's just a standard warning that the actual apk is hosted somewhere else, not on the actual source site. I should probably disable that for VLC, it's more relevant for GitLab and HTML sources.

**Comment by XxTriviumxX** [comment]
it works now!  but earlier today it was shooting me the Internal server error

**Comment by ImranR98** [comment]
> it works now! but earlier today it was shooting me the Internal server error

VLC downloads come from one of several mirrors. I just picked one and hardcoded it but the one they use seems to change. Maybe the one I've used isn't online all the time.

**Comment by ImranR98** [comment]
On further investiagtion, it looks like this is not an Obtainium issue - the VLC website seems to have problems from time to time. Right now, for example, loading the VLC page in a browser and clicking the "APK Package" link takes me to https://get.videolan.org/vlc-android/3.5.4/ which just shows an error saying "none of our mirrors are able to handle your request, please try again later". I'll still make the mirror-related change as it's a good thing anyways, but that won't fix the server error.

**Comment by ImranR98** [comment]
It's really strange - sometimes if I make the same request repeatedly it works after 5-10 tries. Maybe the VLC server is overloaded?

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.23-beta
