### ISSUE TITLE
Description/phrase filter

### ISSUE THREAD

**Issue by Aspect250** [ImranR98/Obtainium#719]
Is there any way to filter out notifications from obtainium if there is not a phrase included in the description of the release, like for example i use obtainium to get Revanced extended updates but I currently do not have any way of filtering those notifications to only updates with "feat(youtube): add support version" included in the description the released update.

P.S thanks for the great app and hope you continue improving it in the future

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.23-beta
