### ISSUE TITLE
Ability to add apps from custom F-Droid repos

### ISSUE THREAD

**Issue by KaMeHb-UA** [ImranR98/Obtainium#72]
A lot of apps (for example, KDE stack) has its own F-Droid repos: https://community.kde.org/Android/FDroid  
Is there any possibility to install apps from there? If no, it would be very nice to see such feature in next releases

**Comment by S7venLights** [comment]
I'm gonna 2nd this, it would be nice to make obtamium the only app I use for updates. For now it's not possible, since not all apps release on Gits and not all Fdroid repos can be added.
Eg: the Tor and Divest OS repos

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.13-beta
