### ISSUE TITLE
For Sources With Optional API Key Inputs, Add Notes Detailing the Benefits (on the Add App Page)

### ISSUE THREAD

**Issue by godSaysHODL** [ImranR98/Obtainium#720]
On https://gitlab.com/AuroraOSS/AuroraStore/-/releases

The latest two releases have a different format for their attachments, and for some reason this is causing Obtainium to ignore the APKs

Specifically 4.2.4 and 4.2.5

**Comment by ImranR98** [comment]
See #697. Leaving this issue open as the Gitlab limitation clearly needs to be communicated in the app itself.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.22-beta
