### ISSUE TITLE
Add back button

### ISSUE THREAD

**Issue by BabyOilJohnson** [ImranR98/Obtainium#721]
Back button on the top left side of the app detail page.
Like this 👇🏼

![Screenshot_20230729-100446_Aurora Store](https://github.com/ImranR98/Obtainium/assets/101601874/a561e7e9-9b45-4924-8f4c-14967d0d153c)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.16-beta
