### ISSUE TITLE
Replace text for removing an app with the typical trash bin icon

### ISSUE THREAD

**Issue by MatsG23** [ImranR98/Obtainium#722]
I think it would be fitting to use the [Material Delete icon](https://fonts.google.com/icons?selected=Material+Icons:delete:) for removing an app (from Obtainium and/or the device). On the one hand, this icon would still be perfectly understandable for this common action. On the other hand, this graphical change would save space .

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.22-beta
