### ISSUE TITLE
Flickering update text size in app list

### ISSUE THREAD

**Issue by MatsG23** [ImranR98/Obtainium#723]
Reproduction steps:
1. start updating an app in Obtainium
2. go to the full list of apps tracked in Obtainium
3. the update text right to the app being updated gets smaller and bigger (noticable as the line break dis- and reappearing)

https://github.com/ImranR98/Obtainium/assets/60609373/5a70e9f8-5a70-4858-8971-64445a5d13b0

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.22-beta
