### ISSUE TITLE
inform user recommended architecture

### ISSUE THREAD

**Issue by RustoMCSpit** [ImranR98/Obtainium#727]

**Comment by ImranR98** [comment]
Could you elaborate. The APK selection dialog already tells you what architectures your device supports.

**Comment by RustoMCSpit** [comment]
> Could you elaborate. The APK selection dialog already tells you what architectures your device supports.

tells you the ideal one

**Comment by ImranR98** [comment]
If your CPU supports it I don't see what makes one more ideal than another.
