### ISSUE TITLE
[Feature Request] Add root install options 

### ISSUE THREAD

**Issue by DevinAndelin** [ImranR98/Obtainium#730]
Hi there! 

Would it be possible to add a feature to install apps as root? Droidify has this option ([I believe this is the relevant code but I didn't look too closely](https://github.com/Droid-ify/client/blob/main/installer/src/main/java/com/looker/installer/installers/RootInstaller.kt#L14) ) and it would make updating apps through Obtanium much easier, especially when you're updating multiple apps.

I generally like the idea of Obtanium much more than F-Droid frontends and I've already moved all of my FOSS apps to your app. This would just be a huge QoL upgrade and would make, in my eyes, Obtanium perfect for me.

Thank you!

**Comment by ImranR98** [comment]
See #25. Support for unofficial/workaround install methods can be looked into once the official method works properly.
