### ISSUE TITLE
Add a Toggle to the HTML Source for Filename-Only Link Sorting

### ISSUE THREAD

**Issue by parkerlreed** [ImranR98/Obtainium#734]
I see the note about the last file alphabetically being picked. 

When I use dolphin emulator as a source it picks the second to latest of what I expect. 

https://dolphin-emu.org/download/

It correctly assumed I wanted one of the ones under the development section but it picked the second to last one which as of right now is 19859. I would think alphabetically the highest number would be picked which would work in this case.

**Comment by ImranR98** [comment]
Sorting is done on [entire links, not just filenames](https://github.com/ImranR98/Obtainium/blob/main/lib/app_sources/html.dart#L114C52-L114C52). The links on the Dophin page have some extra segments - not sure what the logic behind those is.

**Comment by parkerlreed** [comment]
Oh yeah I see what you mean I never noticed that before

https://dl.dolphin-emu.org/builds/a8/3b/dolphin-master-5.0-19863.apk

I'll ask on the server if anybody knows about that.

**Comment by parkerlreed** [comment]
Thanks! That would probably be the best option for being agnostic across different HTML sources.

**Comment by parkerlreed** [comment]
Although not really pertinent to the issue, got an answer to the URL formatting. It's the first two bytes from the SHA256 hash.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.23-beta
