### ISSUE TITLE
Wrong french translation for "ajoutée"

### ISSUE THREAD

**Issue by pled** [ImranR98/Obtainium#735]
Hi,
Just a small error in the french translation. When adding a new application, you can see this : 
![obtainium](https://github.com/ImranR98/Obtainium/assets/2879483/b2da574a-e0df-4352-ade2-81dc817f3688)

I believe correct french word for button should be "Ajouter" (infinitive) and not "Ajoutée" (past participle).

Thank you for your nice app !

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.23-beta
