### ISSUE TITLE
Brave browser apk from github. which one to choose?

### ISSUE THREAD

**Issue by XxTriviumxX** [ImranR98/Obtainium#737]
hi!

This is their repo: https://github.com/brave/brave-browser/releases

They offer many apks. Heres the one obtainium gives me:

Bravearm64Universal.apk
BraveMonoarm.apk
BraveMonoarm64.apk
BraveMonox64.apk
BraveMonox86.apk

If im on a pixel 6a (grapheneOS), which one should i pick? Obtainium indicates my supported cpu architectures are arm64-v8a, armeabi-v7a and armeabi under the apk choices

Whatever choice i make it does not recognize the brave version i have already installed. just waits for me to confirm the installation.

Its like none of the apks are the same as the play store version...

**Comment by pled** [comment]
This is obviously not an issue with Obtainium software.
IMO, you should : 
- first uninstall play store version.
- then install Bravearm64Universal.apk.

You may look at this video for a better understanding : 
https://www.youtube.com/watch?v=JiN37bn0OE8

Hope that helps.

**Comment by XxTriviumxX** [comment]
solution is in the screenshot here:

https://github.com/ImranR98/Obtainium/issues/20#issuecomment-1272396878
