### ISSUE TITLE
'too mamy requests' mode should still allow one add app 

### ISSUE THREAD

**Issue by RustoMCSpit** [ImranR98/Obtainium#738]
there should be a preserved spot prioritising one app to be able to be added

**Comment by ImranR98** [comment]
Not sure what you mean. Are you talking about the GitHub rate limit?

**Comment by ImranR98** [comment]
I'm not sure if this makes sense - we'd be permanently reducing the number of requests that can be used for regular update checking on the off chance that the user might want to add an app during one of the windows when they'd be rate limited. We'd also have to make twice as many requests - the first one to https://api.github.com/rate_limit to check what the remaining request amount it (that itself doesn't count against the limit) so increased latency. If the user only wants to add a single app, they can wait the 30 minutes or add a GitHub API key. If they want to add multiple apps, a single emergency request won't help them much.
