### ISSUE TITLE
keepassdx fdroid wrong version

### ISSUE THREAD

**Issue by privacyonly** [ImranR98/Obtainium#74]
obtainium v0.6.1-beta

version is shown as beta01 instead of 3.5.0 beta01

**Comment by ImranR98** [comment]
Hmm, looks like the code we use to scrape the version does not expects spaces. That sort of thing is always a risk with web scraping. Will be fixed in the next version.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.6.2-beta
