### ISSUE TITLE
Color delete icon in app view red

### ISSUE THREAD

**Issue by MatsG23** [ImranR98/Obtainium#741]
Kind of a follow-up of #722 

The move-to-trash/delete icon is in general mostly painted in a shade of red because the delete button has to be treated with caution as it can cause data loss. I know there is a confirmation dialog that lets you set whether to delete the app only from Obtainium or also from the device.
What do you think is best practice?

I also think that the "Continue" (name of the translation string) button in the confirmation dialog could may be also colored in red and renamed to clarify this is the last step before deletion (like "Delete").

**Comment by ImranR98** [comment]
I'll leave the icon button alone to maintain consistency with the other buttons and the delete button on the main screen (and I think it just looks nicer). Besides, there's a confirmation dialog so that icon button isn't too dangerous. The "continue" button can be red.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.23-beta
