### ISSUE TITLE
Get the option to choose between getting nightly version or official version (like brave's github repo apk)

### ISSUE THREAD

**Issue by XxTriviumxX** [ImranR98/Obtainium#745]
I found out i could download Bravearm64Universal.apk from the brave repo in order to install it. It installed the nightly version. Obtainium did not ask "do you want the official apk or the nightly apk?". I think it would be a great idea to let the user choose.

**Comment by ImranR98** [comment]
Obtainium can't account for all the different ways that developers use GitHub releases (tags, titles, different architectures, nightly/beta builds, etc.). These kinds of cases are what the user-defined "release title filter" is for. See #20.

**Comment by XxTriviumxX** [comment]
thanks for the hint!!!
