### ISSUE TITLE
automatic 'try later?' option for when an app is denied because of rate limits

### ISSUE THREAD

**Issue by RustoMCSpit** [ImranR98/Obtainium#747]
obatinium will try again every hour for three times automatically for the url inputted instead of you having to manually try again

**Comment by ImranR98** [comment]
The ideal way to get past the rate limit is to use an API key. Automatic retry would require saving the user's app add settings without actually adding the app, then start a background job to retry (while making sure it doesn't interfere with the update checking job. Not worth it given the very niche problem.

**Comment by RustoMCSpit** [comment]
> The ideal way to get past the rate limit is to use an API key. Automatic retry would require saving the user's app add settings without actually adding the app, then start a background job to retry (while making sure it doesn't interfere with the update checking job. Not worth it given the very niche problem.

what about simply checking it before any update so it doesnt collide
