### ISSUE TITLE
not a valid fdroid app url

### ISSUE THREAD

**Issue by privacyonly** [ImranR98/Obtainium#75]
v0.6.1-beta
adding
https://f-droid.org/en/packages/org.videolan.vlc/
return "not a valid fdroid app url"

but
https://f-droid.org/packages/org.videolan.vlc/
works

**Comment by ImranR98** [comment]
It's not the `en` that's the problem but the trailing slash `/`. Will fix this soon.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.6.2-beta
