### ISSUE TITLE
What permissons does Obtanium need?

### ISSUE THREAD

**Issue by ayntk-ai** [ImranR98/Obtainium#753]
What permissions does Obtanium need other than to install applications from unknown sources?
I want to disable unknown sources for applications globally if possible and only allow Obtanium with this permission so that everything else is secure.
Can I disable unknown sources for example for Signal and only allow it for Obtanium for security reasons (and updates and the app still work)?

**Comment by ImranR98** [comment]
Obtainium needs network, notification, and app install permissions. The permissions you set for one app cannot affect the functionality of a different one - if Signal itself doesn't try to install apps (which I don't think it does), you don't need to give it the "install unknown apps" permission (I'm not sure you'd even have the option).
