### ISSUE TITLE
How to translate "2-4 items" strings?

### ISSUE THREAD

**Issue by ceskyDJ** [ImranR98/Obtainium#757]
English (and maybe most languages, as Obtainium has been translated to many of them) has just 1 version of plural form. Czech has two 2 versions, so there is a problem with translating strings like:
```json
{
    "apps": {
        "one": "{} App",
        "other": "{} Apps"
    }
}
```

I need something like this to translate it properly to my native language:
```json
{
    "apps": {
        "1": "{} aplikace",
        "2--4": "{} aplikace"
        "5+": "{} aplikací"
    }
}
```

So, I need 3 forms:
- singular
- plural for <2; 4>
- plural for <5; Inf>

**Comment by ImranR98** [comment]
You should be able to use number-specific keys or the "few" key: https://pub.dev/packages/easy_localization#-plurals-plural

**Comment by ceskyDJ** [comment]
Ok, thanks!
