### ISSUE TITLE
Import GitHub Starred list into Obtainium

### ISSUE THREAD

**Issue by katastrophe92** [ImranR98/Obtainium#759]
Hello Obtainium community! Thanks @ImranR98 for this usefull repository☺!

I wish we could import GitHub Starred list or list's into Obtainium? That would be awesome.

In my Starred repositories list's I have a '' Android APK's '' list, this one I would love to import it into Obtainium to have all gathered Apps there and install the ones I need. 

Thanks!

**Comment by ImranR98** [comment]
Looks like GitHub doesn't provide an API for this. At least I couldn't find it anywhere: https://docs.github.com/en/rest/activity/starring?apiVersion=2022-11-28#list-repositories-starred-by-a-user

**Comment by katastrophe92** [comment]
> Looks like GitHub doesn't provide an API for this. At least I couldn't find it anywhere: https://docs.github.com/en/rest/activity/starring?apiVersion=2022-11-28#list-repositories-starred-by-a-user

😔. Too bad. I wish it was doable. Anyway thank you for this awesome app
