### ISSUE TITLE
Wrong and older version on apps that needs to be updated

### ISSUE THREAD

**Issue by andreapx** [ImranR98/Obtainium#764]
Hi,
I've noticed that sometimes Obtanium shows me that there is an update, but the latest version is older than the one installed.
For example for AntennaPod shows that the latest version is 1.0 and the installed version is 3.0.2, for Etar show that the latest version is 1.0 and the installed verion is 1.0.34:
<img src="https://github.com/ImranR98/Obtainium/assets/13846728/95d6d73e-fd32-44dc-a772-26e5fe8e8f0b" width="300" />
<img src="https://github.com/ImranR98/Obtainium/assets/13846728/0c1f6135-ba98-4233-95ed-74ce83baf5f4" width="300" />

**Comment by ImranR98** [comment]
Neither of those repos have APKs available for recent releases. Obtainium falls back to older versions which do have APKs since you have "fallback to older versions" enabled.
