### ISSUE TITLE
dowloading stable brave browser from github downloads only nightly

### ISSUE THREAD

**Issue by flo232017** [ImranR98/Obtainium#767]
Downloading from https://github.com/brave/brave-browser/releases/latest downloads not the stable version, only nightly. When you open https://github.com/brave/brave-browser/releases the first sites there are only nightlys and betas. But some sites later there are a stable version. But I cant download or add this with Obtainium. Paste the Link with the stable version, downloads a nightly.

**Comment by ImranR98** [comment]
Please search existing issues before opening a new one - the explanation and solution for this are in #20.
