### ISSUE TITLE
Add gitlab pre-releases to your app

### ISSUE THREAD

**Issue by ayntk-ai** [ImranR98/Obtainium#768]
Add the Include pre-releases option to GitLab repositories such as https://gitlab.com/AuroraOSS/AppWarden. If that is possible.

**Comment by ImranR98** [comment]
I don't see any prerelease indicator on the repo you linked.

**Comment by ayntk-ai** [comment]
So it only shows the option if there are pre-releases?

**Comment by ImranR98** [comment]
No, I've never seen a pre-release indicator on GitLab - was not aware they had it like GitHub does. I also don't see anything about it in their API example.
