### ISSUE TITLE
No version detection on pre-releases

### ISSUE THREAD

**Issue by ayntk-ai** [ImranR98/Obtainium#769]
When I install seal prereleases through obtanium than I can not detect the version, it says no version detection and I can not switch to the default version detection for prereleases, I need to switch prereleases off to get version detection to work.
It does not work with prereleases from this repository, default version detection only works with prereleases turned off: https://github.com/JunkFood02/Seal.

**Comment by ImranR98** [comment]
Version detection can only work for apps where the version string on github and the real version in the OS both follow a "standard" format like `1.0.0` or `0.9-beta2` etc. The format that is used for prereleases for this app, like `v1.10.0-beta.4`, is not supported.

**Comment by ImranR98** [comment]
See #136.
