### ISSUE TITLE
Version text causes app name to be very narrow

### ISSUE THREAD

**Issue by FlingCarnationProposal** [ImranR98/Obtainium#77]
The version text on the list of apps, when long, causes the app name display to be very narrow. This causes the app's name to display weirdly.

![Tutanota is one thicc boi](https://user-images.githubusercontent.com/109457676/198865175-e791f493-0113-46dc-abbc-e5f4bd05a514.jpg)

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.6.3-beta
