### ISSUE TITLE
Feature request: allow installing unexpected App ID / bypass App ID check

### ISSUE THREAD

**Issue by Mikhail5555** [ImranR98/Obtainium#778]
# Problem:
Some apps (https://github.com/florisboard/florisboard) seem to publish a different App ID for their beta packages then main package. 

# Error:
```
Downloaded package ID does not match existing App ID - dev.patrickgold.florisboard.beta: [dev.patrickgold.florisboard]
```

# Solution:
One of the solutuons would be to convert this error in a warning and allow the user to override/bypass this check.

**Comment by ImranR98** [comment]
Apps with different IDs would be installed separately. So "updating" from florisboard to beta would result in 2 florisboard apps on your phone. You would have to keep switching between the two in your OS keyboard settings. Might lead to confusion for users who don't realize this.

Besides, changes in app ID could indicate a security issue - the user should be warned.

In general, app IDs are meant to be fixed - if it's a new ID, it's a new app.

The best way to handle cases like this is to add a separate entry to Obtainium for each app ID, using one or more filtering options.

**Comment by ImranR98** [comment]
Yes, the app ID for an entry in Obtainium is fixed from the first time the app gets added. So adding a new entry for the beta version should work if you set the options up to grab the beta version when adding it.
