### ISSUE TITLE
Oversized icon for Protonmail

### ISSUE THREAD

**Issue by unchartedpopsicle** [ImranR98/Obtainium#78]
The app view for https://github.com/ProtonMail/proton-mail-android looks like this.

![Screenshot_20221030-100112](https://user-images.githubusercontent.com/89985351/198871385-2bf20ee4-e653-4f34-82d0-8ee27c27c987.png)

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.6.3-beta
