### ISSUE TITLE
Wireless debugging for auto installation and batch updating of apps.

### ISSUE THREAD

**Issue by matt873** [ImranR98/Obtainium#783]
Can you implement an option for wireless debugging like AppManager have?
![Screenshot_20230817-185529](https://github.com/ImranR98/Obtainium/assets/108935493/cc864db4-aea8-41ab-abec-5db1e8355bf3)

**Comment by ImranR98** [comment]
I'm not sure what you mean by "wireless debugging" - are you talking about the APK install method?

**Comment by matt873** [comment]
Yes. it's like shizuku but the app will not need shizuku as it can ask for debugging directly..

**Comment by ImranR98** [comment]
See #636 - supporting non-standard install methods is not in scope (especially since even the official Android APIs are difficult to get working in a Flutter app).
