### ISSUE TITLE
Add app not working

### ISSUE THREAD

**Issue by eloffmarijan** [ImranR98/Obtainium#79]
I can't add mullvad github repo in obtainium.
Showing this error message.
![Screenshot_20221030-145056](https://user-images.githubusercontent.com/101601874/198871519-26a02fa5-ebce-495a-9157-ac446744779b.png)

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.6.3-beta
