### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by bzmshang** [ImranR98/Obtainium#791]
Can you add a batch download?
For example
My software has versions of v0.0.1 and v0.0.2~v0.1.0.
And then each version was subcontracted.
At this point,
I want to download all the v0.0.1～v0.1.0 packages, and it's too hard to download them manually from GitHub, so ask the author if it's possible to do this, put all the versions of the packages I want directly in my custom directory, then create folders according to the version, put apk or zip in the corresponding version, the total large folder is the name of the software I want to download.

**Comment by ImranR98** [comment]
This seems like a very niche use case unique to you. It would also involve completely changing the way things are handled in the app, which is currently build around tracking a single version of an app and downloading then installing a single APK/XAPK. You could use Obtainium's track-only mode to track releases but that's it.
