### ISSUE TITLE
Update of libra is not working

### ISSUE THREAD

**Issue by ayntk-ai** [ImranR98/Obtainium#793]
When I try to update Libra german version from 1.12.5 to 1.12.6 the update fails
https://github.com/markusfisch/Libra

Error code:
Some errors occurred
Conflict: [de.markusfisch.android.libra]

**Comment by ImranR98** [comment]
Sounds like an issue with conflicting signing keys (or similar APK conflict). Try installing the APK manually and see if it works to rule out non-Obtainium issues.

**Comment by ImranR98** [comment]
Closing. Will reopen if it does turn out to be an Obtainium issue. Most likely this is the same as #798.
