### ISSUE TITLE
Updates of older versions version mismatch

### ISSUE THREAD

**Issue by ph00lt0** [ImranR98/Obtainium#794]
The issue I ran in before but now running the beta provided by issue #25 shows me the same issue for the Obtainium app itself.

When you have an newer version installed using a different source the app still shows that it has an update available for you. 
Regardless that the installed version is higher then the version available.

It downloads this older version and then installs which results in the error:
"Cannot install an olderversion of an App: [dev.imranr.obtainium]"

The error makes sense, but perhaps the app should not even attempt to install it nor show that there is an update available when a higher version is already installed.

**Comment by ImranR98** [comment]
This is by design. For apps without standard version detection, there is no way for Obtainium to be sure of which version is higher. Even for apps with standard version detection, downgrading is a possibility for some users: #107
