### ISSUE TITLE
Enhancement request: provide PGP signature file to obtainium .apk files in this github

### ISSUE THREAD

**Issue by lunaticoin** [ImranR98/Obtainium#796]
Aside of sha1sums files for each new apk release, could it be possible to have a .asc/.sig for that .sha1 file? 
Afaik the sha1sum allows me to compare integrity of the apk but not authority and if its the first time I'm installing Obtainium, how can I check it was done by you? 

I believe an .asc/.sig file would be very helpful

**Comment by ImranR98** [comment]
I haven't used PGP before, but looked into it. Future releases will have [`.sig` files alongside the `sha1` hashes](https://github.com/ImranR98/Obtainium/blob/5eac851f8014621e18a5e7dfc440d15c97791a1d/build.sh#L7). My public key is here: https://keyserver.ubuntu.com/pks/lookup?search=contact%40imranr.dev&fingerprint=on&op=index

Obviously you'd have to trust the key server.

**Comment by lunaticoin** [comment]
If you do any public presentation you can add your public key fingerprint at the beginning or at the end so that people can start verifying your key is really yours and bit by bit make it trustworthy. 

Great add!
