### ISSUE TITLE
Webview flashes when doing update checks

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#799]
I have ''show source webpage in app view'' active on Obtainium

When Obtainium is scanning for new versions and I open a apps Fdroid or Gitlab in web view, the the webview flashes black every time it scans a new app. 

I did have Exoerimental flags set on my webview, but I disabled them and tried again and had the same issue (Although I'm not sure if maybe the Flags would only be disabled after a reboot, probably)… Will test in the morning.

**Comment by S7venLights** [comment]
Okay the issue persisted after turning off custom webview flags and rebooting

**Comment by Satanarious** [comment]
> Okay the issue persisted after turning off custom webview flags and rebooting

This happens to me a lot.

**Comment by S7venLights** [comment]
This issue seems to be fixed
