### ISSUE TITLE
Large app icons

### ISSUE THREAD

**Issue by eloffmarijan** [ImranR98/Obtainium#80]
Apps having large icons in app view.
Specifically for protonmail and geometric weather app.
![Screenshot_20221030-145130](https://user-images.githubusercontent.com/101601874/198871736-b156f10e-40db-453a-bc5b-f385035d8c7e.png)
![Screenshot_20221030-145105](https://user-images.githubusercontent.com/101601874/198871741-2f5137f0-781b-45e2-96ba-8a9dd0df2301.png)

**Comment by ImranR98** [comment]
Duplicate of #78
