### ISSUE TITLE
VLC problems. shows 3.5.3 instead of 3.5.4.   cannot be installed after uninstalling. have to install manually.  etc.etc. 

### ISSUE THREAD

**Issue by XxTriviumxX** [ImranR98/Obtainium#801]
Okay. theres a lot going on here. its really weird.

I installed the 3.5.4 version manually by downloading the apk from here: https://www.videolan.org/vlc/download-android.html

If i use "track only", it says 3.5.4... but it keeps telling me to update everytime even though i marked it as installed.

without track only, it says the latest version is 3.5.3... and since i uninstalled 3.5.4, it wont let me install vlc anymore.  error states:

Some errors occurred.
Invbalid: [org.videolan.vlc]

When i checked the mirror indicated here https://www.videolan.org/vlc/download-android.html, 3.5.4 was not there anymore!! i cant get 3.5.4 back.

How can i install vlc back?
Im sorry if i cant give more details, since i am stuck. i cannot go back to give more info.

**Comment by ImranR98** [comment]
When I was working on the vlc source, I did notice this a few times - the latest version sometimes disappeared. Was hoping it was a temporary glitch but I just tried it now and it's clear there's something up with the site. I got 3.5.4 in a browser and obtainium, waited a few minutes and tried again and got 3.5.3 in obtainium (also in the browser after clearing cache).

The vlc source may have to be removed if it keeps being inconsistent. Also takes a long time to return some requests for some reason.

**Comment by XxTriviumxX** [comment]
it's complete madness!! LOL

**Comment by ImranR98** [comment]
Yeah I'm not sure what to do about it - played around and I can't figure out what's causing this (using a VPN sometimes it looks like different regions may have the disappearing version at different times but I'm not 100% sure). Closing the issue for now because it's not something I can fix. If too many people continue to report the error the source will have to be removed.

**Comment by ImranR98** [comment]
#808 also opened about this. Will remove VLC in the next release.

**Comment by XxTriviumxX** [comment]
good decision.  can be easily replaced with Just (Video) Player and mpv

**Comment by ceskyDJ** [comment]
In my opinion VLC is very powerful app. Just (Video) Player looks good but doesn't have some features I need (e.g. better file explorer). But, of course, it's up to @ImranR98.

**Comment by XxTriviumxX** [comment]
go check mpv-android, you might like it!

**Comment by ceskyDJ** [comment]
Ok, thanks! I'll try it.

**Comment by ceskyDJ** [comment]
You're right, it looks very good.

**Comment by ImranR98** [comment]
Removed for now (unless a reliable method is found): https://github.com/ImranR98/Obtainium/releases/tag/v0.14.1-beta

**Comment by ShareASmile** [comment]
> Just (Video) Player looks good but doesn't have some features I need 

Yes. Agree but there is new Video Player developing on the horizon based on ExoPlayer "Next Player". It has become my daily to use Video Player currently.

https://github.com/anilbeesetti/nextplayer

**Comment by ceskyDJ** [comment]
> > Just (Video) Player looks good but doesn't have some features I need 
> 
> Yes. Agree but there is new Video Player developing on the horizon based on ExoPlayer "Next Player". It has become my daily to use Video Player currently.
> 
> https://github.com/anilbeesetti/nextplayer

Hmm, that's the best of all recommendations here. Maybe I'll add a Czech translation to it.
