### ISSUE TITLE
Translation of plurals in other languages

### ISSUE THREAD

**Issue by Daviteusz** [ImranR98/Obtainium#810]
I made changes to the pluralization in #803  but some settings does not have any translations  eg. `hour.other`

Weblate uses this formula for pluralization for Polish language:
`n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2`
How it looks in Weblate:
<img src="https://github.com/ImranR98/Obtainium/assets/11527277/edafae09-e696-42db-b593-9bf269bc0444" width=50%>

```
"hour": {
      "one": "{} godzina",
      "few": "{} godziny",
      "many": "{} godzin"
```
I get this after building the apk:
<img src="https://github.com/ImranR98/Obtainium/assets/11527277/b5a783e0-982c-48a5-84e9-444c5431cedb" width=30%>

`few` works for the number 3, but it should also work for the numbers 2-4, `many` works correctly.

Can you check this? Thanks.

**Comment by ImranR98** [comment]
Not sure I understand what I need to check. Do  your changes in #803 fix the `hour.other` text?

**Comment by Daviteusz** [comment]
NoNo, my PR only changes the plural in pl.json

The problem is that after this change Obtainium still uses `other` when plural 2 is detected, it should use `few` the same as for plural 3 and 4. `many` from plural 5 to infinity works okey.

I don't know how to fix it, so I decided to report this problem.

**Comment by ImranR98** [comment]
According to the documentation [here](https://pub.dev/packages/easy_localization), the `other` prop is not optional. You could try adding it (make the content identical to `few`) and see if that fixes it.

**Comment by Daviteusz** [comment]
It works. I created a script that automatically copies the `few` line and pastes it under `many` as `other` and I will be able to continue using Weblate. Thanks for help.
