### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by nightznero** [ImranR98/Obtainium#811]
Helloz,i would like to know why there is only a Obatnium-similiar icons rather than orginal shown? Its bs apk its not installed or?
![Screenshot_20230826_205351](https://github.com/ImranR98/Obtainium/assets/61750641/cb5e4ff3-cc2b-419e-9413-10fc90abf7a7)
Best Regards, NIGHTZNERO.

**Comment by ImranR98** [comment]
Yes, the icon is taken from the OS, so if the app is not installed, the OS cannot provide any icon. So the Obtainium icon is kept as a placeholder.
