### ISSUE TITLE
Clarification of update behavior

### ISSUE THREAD

**Issue by parkerlreed** [ImranR98/Obtainium#814]
I have background updates turned off and yet a couple of my applications will update immediately after download without the package installer prompt. 

It still updates the application but the only verification I have is what obtainium tells me or manually going into an application and checking the versions. If it gives me the update prompt dialogue that I have to confirm, then at least I know an update definitely happened.

**Comment by ImranR98** [comment]
> I have background updates turned off and yet a couple of my applications will update immediately after download without the package installer prompt.

Do you mean in the background? Or in the UI itself when you start and update update in the app? If it's the latter then this is intended - there's no need to make the user tap multiple buttons if we can just skip the prompt. If the update fails, you'll still get an error dialog - if there's no error that should be enough to verify that the update was installed.

If you mean an actual background process, that's a bug.

**Comment by parkerlreed** [comment]
Yeah I meant tapping update in the application. Removing the package installer prompt leaves a bit of ambiguity if the update actually happened.

**Comment by ImranR98** [comment]
The update button goes away and the on-screen version number changes, but I guess those are both very subtle. Maybe an "Updated" message could be shown at the bottom - make it more obvious without having to click another button.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.2-beta
