### ISSUE TITLE
Show Changelog Inside App

### ISSUE THREAD

**Issue by gloeyisk** [ImranR98/Obtainium#82]
- Possible to add a new window when tapped change log (See Changes option) for new updates inside the app rather than opening browser and (if can) re-write what have been fixed
- A in-built privileged extension (like F-Droid did) for installing a new apps or updating so it'll way easier without interact within the user

**Comment by ImranR98** [comment]
This has been added for sources where it is realistic/reasonable to extract change log text: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.11-beta
