### ISSUE TITLE
Add "Intermediate Link" to HTML Source

### ISSUE THREAD

**Issue by lebr0n23** [ImranR98/Obtainium#820]
Hi!
Is there a way to display the versions/folders of Electrum (https://download.electrum.org/) correctly? Maybe through the custom link filter? I haven't figured out yet how to use it properly, since every other app worked flawlessly without it..

**Comment by ImranR98** [comment]
That wouldn't work with the html source since the apks links are in sub folders. Rather than add this as it's own source, it might make sense to add a "descend one level" toggle (or something like that) to the html source.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.2-beta

You should be able to use the new "Intermediate Link" option with the value `([0-9]+\.)*[0-9]+/$` (which is the in-app hint value too). This will tell Obtainium to look for any links that satisfy the regex (any link which follows a pattern like `1.2.3`), then pick the last one, and then treat _that_ URL as the input for the HTML source.
