### ISSUE TITLE
Change link for VLC to increase reliability

### ISSUE THREAD

**Issue by HelmetOwl** [ImranR98/Obtainium#821]
As per issue #801, VLC has been removed as a source due to lack of reliability.  Consider using this link instead: https://get.videolan.org/vlc-android/.

It lists every version in chronological order. 'Last' is not up to date so you'd need to use the second last line; given that is the most recent version.

**Comment by ImranR98** [comment]
The user input is 'videolan.org' but we already use 'get.videolan.org' behind the scenes. The problem is that that list is inconsistent. I just clicked on your link right now and the page shows '3.5.3' as the latest version, when I know it was 3.5.4 in the past. If I check back later it may have changed - it's been very unreliable.

**Comment by HelmetOwl** [comment]
You're right. I checked before posting and it said 3.5.4, so I assumed it was working, however now it says 3.5.3. If I go to https://get.videolan.org/vlc-android/3.5.4/, it says there are no mirrors to handle the request. Worst part is, I clicked that link from their official [download page](https://www.videolan.org/vlc/download-android.html)  and got that message, I didn't type it in.

From a very cursory look at their [mirrors page](https://www.videolan.org/videolan/mirrors.html), they're using Mirrorbits to load balance the mirrors. When there's no available mirror, we don't see the latest version. You can see the fallback mirrors here: https://get.videolan.org/vlc-android/?mirrorlist. Perhaps use one of them as a temporary solution? [See here](https://github.com/etix/mirrorbits#realtime-file-availability) for more info on Mirrorbits (that's what I did).

**Comment by HelmetOwl** [comment]
You could also scrape and use the "APK package" link from the [official download page](https://www.videolan.org/vlc/download-android.html) and if it says there's no mirrors when the Obtainium user tries to update, just throw an error saying there are no mirrors right now for VLC and to try again later.

**Comment by ImranR98** [comment]
Nice, that could work

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.2-beta

**Comment by HelmetOwl** [comment]
Great, nice work. The only thing I would suggest to improve it now is it's throwing a mirror error when I check for updates for all the apps, but it doesn't need to. You can get the latest version number/name from the URL on the download page and compare that with the currently installed one to inform the user if an update exists. If they don't match, then offer to update and if the update is initiated, it should attempt to use the URL and it's only then that the mirror error might occur. If there is currently no update, there's no reason to send a request to the mirror.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.5-beta
