### ISSUE TITLE
Per-app Auto Update Toggle

### ISSUE THREAD

**Issue by nep2ner** [ImranR98/Obtainium#822]
I've noticed Obtainium has recently started upgrading apps on it's own. This is an amazing feature, but I've had to disable it.

I have a few apps that I use as clients to various self-hosted services. Sometimes updating a client before the server has been updated is problematic. With Obtainium's auto updates, these client apps get updates before I've had time to update their respective backend. Hence, I needed to disable the auto-update feature.

My feature request is to add a auto update toggle *per app* so that I can selectively configure which apps I want to be auto updated and which I only want to be notified about.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.2-beta

**Comment by nep2ner** [comment]
Wow that was really fast, thank you!
