### ISSUE TITLE
question on .otf

### ISSUE THREAD

**Issue by RustoMCSpit** [ImranR98/Obtainium#826]
does obtainium work on this https://github.com/IdreesInc/Monocraft/releases

**Comment by ImranR98** [comment]
You could track releases if you enable "track-only". It's a font, not an app so obtainium cant install it.

**Comment by RustoMCSpit** [comment]
> You could track releases if you enable "track-only". It's a font, not an app so obtainium cant install it.

why not work with fonts

**Comment by ImranR98** [comment]
Out of scope. Obtainium is meant for Android apps and all the code assumes that you're working with APKs.

**Comment by RustoMCSpit** [comment]
> Out of scope. Obtainium is meant for Android apps and all the code assumes that you're working with APKs.

could it be reworked to include .otf
