### ISSUE TITLE
Grouping notification

### ISSUE THREAD

**Issue by BabyOilJohnson** [ImranR98/Obtainium#829]
Now the apps update notifications are in form of separate rather than in single notification. The old way was good.
![Screenshot_20230828-104101_Package installer](https://github.com/ImranR98/Obtainium/assets/101601874/5c94cc6b-1b02-4324-abe3-3d08639e9a2d)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.6-beta
