### ISSUE TITLE
Bug in app interface 

### ISSUE THREAD

**Issue by Sukii23** [ImranR98/Obtainium#830]
![Screenshot_20230829-113950](https://github.com/ImranR98/Obtainium/assets/127705451/18bb2553-ec78-4f78-a878-5664048b767a)

I put the app in the Brazilian language for testing and the app looked like this. i cant even backup app list to delete and install again.. please check this

**Comment by ImranR98** [comment]
This is a weird bug I haven't seen with other languages. I've removed this language from the latest release for now, so that you can continue using the app. I'll add it back once the bug is fixed. You will need to update to this release manually since Obtainium is unusable:  https://github.com/ImranR98/Obtainium/releases/tag/v0.14.4-beta

**Comment by Sukii23** [comment]
thanks, after updating I went back to english and the problem disappeared. again, thank you for developing such a useful and awesome app!

**Comment by ImranR98** [comment]
Reopening the issue as it hasn't actually been fixed.

**Comment by LucasTavaresA** [comment]
maybe its the wrong country code and it should be 'pt-BR' or maybe 'pt_BR', when i find time i will check this

**Comment by LucasTavaresA** [comment]
mine does not detect the language automatically
i suppose some devices can detect the current code

**Comment by ImranR98** [comment]
I tried pt-br (all lowercase) earlier but it didn't help.

**Comment by LucasTavaresA** [comment]
i broke my environment so i can't test anything
but looks like pt-BR.json would be the correct way to do it
https://pub.dev/documentation/easy_localization/latest/

**Comment by ImranR98** [comment]
Just tried that, doesn't help.

**Comment by ImranR98** [comment]
Looks like `br` and `pt_BR` are not on the list of codes supported by this plugin: https://api.flutter.dev/flutter/flutter_localizations/flutter_localizations-library.html

They do have `pt` and `pt_PT`. Would it make sense to use `pt` as Brazilian Portugese and `pt_PT` for the other one?

**Comment by LucasTavaresA** [comment]
i have seen 'portuguese' and 'pt' used in interfaces but never when portugal portuguese is present
i wonder if the translation detection would work like this
but i don't think its a problem

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.18-beta
