### ISSUE TITLE
Add Aptoide as a source

### ISSUE THREAD

**Issue by dalitz-bazalgette** [ImranR98/Obtainium#843]
I think this would be valuable to add as a source because it seems to have a lot of apps that aren't on APKPure.

Aptoide's own [client](http://aptoide.org) is open source. Apparently they've been around in some form since 2009.

In 2017, Waseda University in Tokyo published a [study](https://nsl.cs.waseda.ac.jp/wp-content/uploads/2018/04/submitted_wama2017.pdf) comparing the security of third party Android marketplaces. Aptoide was marked highest in their security index.

**Comment by ImranR98** [comment]
Thanks for pointing out that their client is open source. I previously closed #552 assuming they wouldn't have any public API we could use. It's not meant to be public (no public docs), but their own API the client uses doesn't seem to be protected in any way.

Example: `curl https://ws2.aptoide.com/api/7/getApp/app_id/"$(curl -s https://whatsapp.en.aptoide.com/app | grep -Eo '"app":{"id":[0-9]+' | head -1 | tail -c +13)"`

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.7-beta

**Comment by jonnyhotchkiss** [comment]
So we can use apktoid (source) without using the app, using obtainium?! And obtainium will know which apps **it** has installed? APKToid and HM don't seem to show (or know) what's installed (by them), I see F-Droid has this feature, and is working... 

Which leads me to follow-up question: so we can use F-Droid source(s) without that app? 
Obtainium requires root, right?
👍

**Comment by ImranR98** [comment]
@jonnyhotchkiss Obtainium doesn't require root and doesn't know what apps it installed.
