### ISSUE TITLE
Source Selection

### ISSUE THREAD

**Issue by BraINstinct0** [ImranR98/Obtainium#845]
**Describe the feature**
Two parts:
1. A setting to select which source to include/exclude when searching for an app - some might prefer to avoid a specific searchable source, or avoid sending queries to a source.
2. A setting, which asks if newly added searchable sources should be on by default - for even more control over what is mentioned in 1.

**Comment by ImranR98** [comment]
I'm not sure this is worth adding given that you can already search specific Sources on the Import/Export page.

**Comment by BraINstinct0** [comment]
Can agree, I guess... since this also does not utilise javascript or so, and simply parse data.
I'll consider it as solved
