### ISSUE TITLE
Auto Select Highest VersionCode APK (F-Droid)

### ISSUE THREAD

**Issue by BraINstinct0** [ImranR98/Obtainium#846]
Some F-droid apps, some by mistake, others due to unknown reasons, have multiple same-version numbered apps uploaded like [ACode](https://www.f-droid.org/packages/com.foxdebug.acode/). This may result in users thinking it is up to date, when it actually isn't.
This can be mitigated by first comparing versions, then comparing upload date to ensure the app is reaply up to date.

Alternative: Enable upload date as install version for F-droid, but I'm not sure if this is a valid solution. Version should take precedence over date, as some just upload skipped previous versions to F-droid just for archival purposes.

Honestly I haven't looked into how F-Droid (or Droid-ify, in my case) detect which version is specifically installed, but they both utilise hash/checksum comparing on installation so it could be that.

**Comment by ImranR98** [comment]
The F-Droid API doesn't provide release dates: https://f-droid.org/api/v1/packages/com.foxdebug.acode
Doing this would require Web scraping, which is unreliable. I think it makes more sense to get developers to version their apps correctly.

**Comment by ImranR98** [comment]
Instead, we could add a "pick highest versionCode APK" toggle, which should also work for these cases.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.9-beta

**Comment by BraINstinct0** [comment]
Can confirm this commit effectively solved the issue.
