### ISSUE TITLE
Aptoide not working (can't install)

### ISSUE THREAD

**Issue by ghost** [ImranR98/Obtainium#851]
I tried many apps and I always had the same issue, I don't know why but my guess is that is downloading the Aptoide app itself not the one I requested, that happens if you use the site, or maybe for another reason because you are using the API not the site, and also bigger apps take longer time, so there are other possibilities that I don't know.

![Screenshot_20230904-083511](https://github.com/ImranR98/Obtainium/assets/114379310/0d8e09ac-90a0-4bf0-82d3-8df23cafa3b7)

**Comment by ImranR98** [comment]
Whoops. The app version was being saved as it's ID. Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.10-beta

But you'll need to re-add the apps.
