### ISSUE TITLE
Add new source: Uptodown

### ISSUE THREAD

**Issue by JohnBetaro** [ImranR98/Obtainium#853]
Hi, I hope you'll consider adding this site because it has most of the apps and can be used when apkpure can't download the app for some reason (problem of the site not Obtainium), and also when it serves an app that is not compatible with the phone.

https://en.uptodown.com/

Thank you for your time.

**Comment by ImranR98** [comment]
APKMirror is run by the AndroidPolice news website, so I think it is. APKPure and Aptoide I'm not sure about, but seem okay. Uptodown seems the sketchiest, I've never heard of it before.

I think users should be responsible for making sure their sources are safe, Obtainium is really for automating the manual update checking and install steps more than anything else. But obviously if there's any source that distributes malware or something like that, it wouldn't be added.

**Comment by ImranR98** [comment]
For my later reference:
- Version is in `div.version`
- APK Url: `#detail-download-button` attribute `data-url`
    - Unclear if this is safe/fixed or needs to be grabbed at download time
- App ID: `#technical-information td` (3rd one)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.11-beta
