### ISSUE TITLE
Revanced extended cannot be added

### ISSUE THREAD

**Issue by JW10234** [ImranR98/Obtainium#856]
**Prerequisites**
Please ensure your request is not part of an existing issue.

**Describe the bug**
In the releases section of the revanced extended GitHub eepo, YouTube rvx as well as yt music rvx are distributed. Whenever I try to add the repo, I automatically get yt music rvx even though I wanted to add YouTube rvx. There is no option for selecting, which app I want to have. Have I overlooked something? 

**To Reproduce**
1. Tap on Add app
2. Add this repo : https://github.com/NoName-exe/revanced-extended/releases/

**Screenshots and Logs**

**Please complete the following information:**
 - Device: [Pixel 6 pro]
 - OS: [ GrapheneOS]
 - Obtainium Version [0.14.10-beta]

**Additional context**

**Comment by ImranR98** [comment]
This is a rare case where the automatic CPU archutecture filtering fails (due to multiple apps in one release + archutecture only in some file names). Disable the "Attempt to filter APKs..." toggle and try again.
