### ISSUE TITLE
Anyway to access GitHub private repositories

### ISSUE THREAD

**Issue by JohnBetaro** [ImranR98/Obtainium#857]
Hi, the title says it all, because I have some apps in "my" private repositories that I want to access, maybe if you can use the GitHub Access Token, I already added it but nothing happened, I can use it in GitHub Actions to access them and it works, I hope there will be some solutions.

Thank you for your time.

**Comment by ImranR98** [comment]
This should work if your Access Token has been granted access to read private repos. Use the `repo` scope for classic tokens and the "Contents" permission for fine-grained tokens.

**Comment by ImranR98** [comment]
Just tried it and it does 

If you have the `curl` command available, try running `curl https://JohnBetaro:<token>@api.github.com/repos/JohnBetaro/<repo>/releases` and see if it works. Even if you have no releases available, you should get an empty array in response.

If that doesn't work, you've done something wrong with setting up the PAT or copying it.

If it works, try copy-pasting the `JohnBetaro:<token>` into Obtainium directly - it should work as we are using that exact request in the app.

**Comment by ImranR98** [comment]
Oh wait, all requests use the token except for APK downloads. So that request is probably the issue.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.11-beta
