### ISSUE TITLE
Can't add signal

### ISSUE THREAD

**Issue by BabyOilJohnson** [ImranR98/Obtainium#859]
**Describe the bug**
I can't add signal, getting this error.

**To Reproduce**
1. Go to add app
2. Add the app [URL](https://signal.org)  
3. Click add button

**Screenshots and Logs**
| Error |
|--------|
| ![Screenshot_20230904-215847](https://github.com/ImranR98/Obtainium/assets/101601874/66d00467-98bc-42a2-8359-9a0cf9725723) | 

**Please complete the following information:**
 - Device: [Samsung A30]
 - OS: [Android]
 - Obtainium Version [0.14.10-beta]

**Comment by ImranR98** [comment]
Hmm, it works fine on my devices. Will take a look at the code and see if there's anything obvious that could cause the error. In the meantime, could you try on another device and/or network.

**Comment by ImranR98** [comment]
Signal source does not have any null checks. Probably coming from somewhere else in the app. Let me know if the suggestions changed anything.

**Comment by BabyOilJohnson** [comment]
Yeah, it's working back again.
