### ISSUE TITLE
[Feature Request] Make Changelog Button More Obvious/Clickable 

### ISSUE THREAD

**Issue by keks24** [ImranR98/Obtainium#860]
**Prerequisites**
- [x] Please ensure your request is not part of an existing issue.

**Describe the feature**

I am currently using the following workflow:

1. `Open` Optainium
    1.1. Let it `fetch` all App information.
    1.2. If there is an update (e.g. for `Optainium`), `open` the App page.
    1.3. `Click on` the `repository link`: https://github.com/ImranR98/Obtainium
2. In the `opened default browser`
    2.1. `Scroll down` to the very bottom.
    2.2. `Click on` the link `Releases`.
    2.3. `Read` the `release notes` by clicking on `Releases`.
    2.4. `Close` the `default browser`.
3. `Go back` to `Optainium`.
4. `Update` the App.

If the `direct link` to the `releases page` would be provided, the new workflow would then be like the following:

1. `Open` Optainium
    1.1. Let it `fetch` all App information.
    1.2. If there is an update (e.g. for `Optainium`), `open` the App page.
    1.3. `Click on` the `releases link`: https://github.com/ImranR98/Obtainium/releases
2. In the `opened default browser`
    2.1. `Read` the `release notes`.
    2.2. `Close` the `default browser`.
3. `Go back` to `Optainium`.
4. `Update` the App.

Would it be possible to provide a `direct link` to the `releases page` of added repositories by default or maybe add a `seperate customisable text field`, which will overwrite the default link?

**Describe alternatives you've considered (if applicable)**

Keep using the `current not-so-efficient workflow`.

**Additional context**
![img1](https://github.com/ImranR98/Obtainium/assets/13721064/01b92230-33d2-4bc1-9c14-5928bc6e1cba)

-Ramon

---

PS: Nice issue template!
You can actually put the descriptions in HTML comment tags (`<!-- -->`), so the reporter does not have to remove the text manually. [Ansible](https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE) has very nice issue templates for example. :)

**Comment by ImranR98** [comment]
You can already see release notes directly in the app by clicking on the version number or release date on the main apps list page. Whether the link goes to the releases page or the main repo page is a matter of personal preference, I think it makes more sense as is.

**Comment by ImranR98** [comment]
Thanks for the issue templates tip!

**Comment by keks24** [comment]
> You can already see release notes directly in the app by clicking on the version number or release date on the main apps list page.

I see! That was not obvious to me, that you can click on these.

Although, one needs to be `super-precise` with their fingers or thumbs to do this. There are three options to misclick:

1. Open the `in-App App page`.
2. Open the `fetched Changelogs`.
3. Open the `releases page` in the default browser.

I actually like challenges, but this one should not be one.

Would it be possible to have `clickable buttons` for `big, clumsy fingers`? :smile:

![img2](https://github.com/ImranR98/Obtainium/assets/13721064/3e2fd889-2e15-48bc-8331-6aefd49deb1a)

> Whether the link goes to the releases page or the main repo page is a matter of personal preference, I think it makes more sense as is.

Agreed. Now that link makes more sense to me!

---

Just for the record:
![img1](https://github.com/ImranR98/Obtainium/assets/13721064/f963c541-a5f8-4a55-9f84-a272f8dbe6e9)

**Comment by keks24** [comment]
> > 1. Open the `in-App App page`.
> > 2. Open the `fetched Changelogs`.
> > 3. Open the `releases page` in the default browser.
> 
> 3 should only happen if 2 is not implemented for that source. But yes the box could be made a bit bigger/outlined.

I see, then I may have found a bug?

I have the following Apps added; sorted by `release date` in `descending order`:

![img1](https://github.com/ImranR98/Obtainium/assets/13721064/8dbaa9d3-ee9e-495f-999b-75fa5b238486)

Clicking on `DAVx5's` link `2023-09-07, v4.3.6.1-ose`, which is connected to their [`GitHub` repository](https://github.com/bitfireAT/davx5-ose/releases), opens the `releases page` in my `default browser`.

The links of `Optainium`, `FairEmail`, `NewPipe SponsorBlock` and `FlorisBoard` on the other hand, which are also added via their `GitHub repository link`, behave normally and open the `fetched Changelogs` page.

Only the link of the App `Aurora Store`, which is from `GitLab`, opens in my `default browser`.

I can only guess, that it may be connected to `DAVx5's` release note formatting, which may be a `markdown text block`:

````no-highlight
```no-highlight
<some_release_notes>
```
````

Should I open another issue for this?

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.11-beta

Touch targets are bigger and can optionally be highlighted (disabled by default).

**Comment by ImranR98** [comment]
Also yes DAVx5 does their release notes in a way that doesn't show up in API requests for some reason.

**Comment by keks24** [comment]
> https://github.com/ImranR98/Obtainium/releases/tag/v0.14.11-beta
> 
> Touch targets are bigger and can optionally be highlighted (disabled by default).

Thank you very much for adapting this quickly!

But I would like to note, that the highlighting does not work in `dark mode (with and without high-contrast text)`. :)

> Also yes DAVx5 does their release notes in a way that doesn't show up in API requests for some reason.

I am going to add another issue for this.

**Comment by keks24** [comment]
> I am going to add another issue for this.

See #875.

**Comment by ImranR98** [comment]
> But I would like to note, that the highlighting does not work in `dark mode (with and without high-contrast text)`. :)

Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.12-beta

**Comment by keks24** [comment]
Awesome, works nicely!

**Comment by BabyOilJohnson** [comment]
@ImranR98 can u make it work for black theme too?

**Comment by keks24** [comment]
![img1](https://github.com/ImranR98/Obtainium/assets/13721064/b7b37acd-f796-4979-b841-8fe2005ad34e)

I was tinkering around with the App today and figured out, that you can update Apps directly from the main page; I always thought, that it just indicates a new update...

May I ask to highlight the download button as well?
