### ISSUE TITLE
Error while adding an app

### ISSUE THREAD

**Issue by tabi-ya** [ImranR98/Obtainium#862]
Too many requests (rate limited) - try again in 28 minutes: 

![Screenshot_2023-09-06-00-30-59-37_a13e17678c56528bd2f18fcaaa8af4ba.jpg](https://github.com/ImranR98/Obtainium/assets/135990135/4bb772ef-1ac5-4d5a-9779-00a242dddbd5)

 - Device: OnePlus Nord N200 5G
 - OS: Stock OS
 - Obtainium Version [e.g. 0.14.10-beta]

**Comment by ImranR98** [comment]
A plain key with none of the options should work
