### ISSUE TITLE
Whoa There Message from github

### ISSUE THREAD

**Issue by IndomitableAlbus** [ImranR98/Obtainium#866]
Firstly, this is all new to me so apologies if it's in the wrong place.

Obtainium, Whoa there warning.

I use Obtainium as my primary App manager for all things FOSS etc.

The Apps been great up until recently but now I've started to receive the Whoa there message as seen in the screenshot, evertime I try to install a new App.

The new App will still install ok, it just seems a little slow.

Now I know nothing about this kinda stuff, Obtainium is on it's stock settings and the latest version is installed.

What could possibly be causing this message, as far as I'm aware I've changed nothing.

Please can you advise.

**Comment by ImranR98** [comment]
Your imgur link is not loading. You can attach images directly on github.

**Comment by IndomitableAlbus** [comment]
![Whoa There](https://github.com/ImranR98/Obtainium/assets/96390963/f7ca83b1-3cf7-4d47-a535-1892181031e4)

**Comment by ImranR98** [comment]
Looks like github thinks your traffic is suspicious. Not an Obtainium issue. Besides, if you are able to add and install apps, then it means GitHub API requests are still going through so app functionality should not be affected. You just won't be able to view the website through Obtainium's app details page (and I'm guessing through your browser too). Not sure why they flag you as suspicious, maybe you're on a sketchy VPN?
