### ISSUE TITLE
Upateing the list of Apps is blocked by github because the requests are rated as DDOS attack mistakenly

### ISSUE THREAD

**Issue by mcctuxic** [ImranR98/Obtainium#868]
**Prerequisites**
It is new view on a certain circumstance.

**Describe the bug**
Updating list of installed apps is slow / stops.

**To Reproduce**
Fill Obtainium with a lot of apps, update often. 

**Screenshots and Logs**
(not available, not needed)

**Please complete the following information:**
Pixel 6a, GrapheneOS, Obtainium 0.14.10
The smartphone has no SIMcard and is connected to the internet only
via WiFi. The same router / the same DSL is used by my PC.

Additional context
The problem seems to be, that github blocks or massively throttles IP-address 
ranges, from which they receive a lot of requests of that kind Obtainium is sending. 

Why?
I have a script on my Linux system, which does a similiar thing like obtainium
for a bunch of sources hosted on github. And this script comes to a hold
after checking only a few (~5) repos.
Result: I can no longer update my system :(

I think, github is rating the request send by Obtainium as DDOS attack in the meanwhile.
So, please talk to github how to resolve this issue.
Throttling the request/time send by Obtainium may be a way to go....but /please/ talk
to github.
Blocking this kind of request per IP range hinders far more resources than "only" 
smartphones.
HTH!

**Comment by ImranR98** [comment]
How many apps? Have you added an API key?

**Comment by mcctuxic** [comment]
55
What did you mean with "API key"?

**Comment by ImranR98** [comment]
GitHub rate limits all unauthenticated API requests. You can bypass this by adding a github api key/token in the Obtainium settings. This is noted right below the URL input on the add app page when you put in a GitHub URL.

**Comment by ImranR98** [comment]
This isn't unreasonable - normal way to prevent overuse. You should be able to make an anonymous github account with protonmail if that's a concern.

**Comment by mcctuxic** [comment]
May I suggest, that Obtainium refuses to do anything before the API key is entered...so the API key is required?
This will save github and folks like me a lot  of trouble.
When will this throttling ban will be lifted by giithub against my IP range again?
I want to update my sources for my Linux system....
And: Where do I get that api key/token?

**Comment by ImranR98** [comment]
Many people only have a couple dozen apps and don't need to go through the trouble. You can tap the About link in Obtainium's settings to find out more about github tokens (or look it up).

**Comment by ImranR98** [comment]
The rate limit typically lasts 30 minutes. The error message in Obtainium should have an exact number.

**Comment by mcctuxic** [comment]
There are no error messages in Obtainium.
The About link links to git_lab_. I cannot find any access token related things on git_hub_.
How cab I proceed?
