### ISSUE TITLE
Obtainium Does Not Update Finamp

### ISSUE THREAD

**Issue by TheDarkula** [ImranR98/Obtainium#874]
I have [Finamp](https://github.com/jmshrv/finamp), version `0.6.16` installed.
Obtainium is aware that there is an update (version `0.6.17`).
When I try to upgrade the package, Obtainium goes through the motions of downloading, but then does not actually upgrade the package.

**To Reproduce**
1. Install Finamp, version 0.6.16
2. Try to upgrade the package in Obtainium

- Device: Pixel 6a
- OS: GrapheneOS
- Obtainium Version: 0.14.11

**Comment by ImranR98** [comment]
Not an Obtainium issue. Finamp's latest APK is actually labelled as `0.6.16` - you can confirm this by installing it manually and looking at the app info in settings. Not sure if the developer forgot to increment the APK version or accidentally uploaded an old APK. Until they fix this, you can work around the issue by switching to "No Version Detection" in the Obtainium settings for this app.

**Comment by TheDarkula** [comment]
@ImranR98 Well spotted, and thank you for investigating!
It did seem odd that it was the only outlier.
I will start an issue over there :)
