### ISSUE TITLE
Error: Could not find suitable release

### ISSUE THREAD

**Issue by Dariqq** [ImranR98/Obtainium#877]
**Describe the bug**

Hi, trying to fetch updates for Eternity (https://codeberg.org/Bazsalanszky/Eternity) returns a "Could not find suitable release" error in version "v0.14-11-beta" but is working in version "v0.14-10-beta"  

**To Reproduce**

1. Add Eternity to Obtainium (https://codeberg.org/Bazsalanszky/Eternity)
2. Enable Prereleases (only prereleases are available)
4. Error on version v0.14-11-beta, but not on v0.14-10-beta

**Please complete the following information:**
 - Obtainium Version: v0.14-11-beta

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.12-beta
