### ISSUE TITLE
Show progress when searching for app updates

### ISSUE THREAD

**Issue by MatsG23** [ImranR98/Obtainium#88]
I am using round about 30 FOSS apps that I added to the apps list in Obtainium. Searching for updates manually takes ages and it is annoying to only see a infinite spinner and nothing else.
I propose to add a sth. like a progress bar or a fullscreen activity showing like "App 5/30".

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.6.5-beta

**Comment by S7venLights** [comment]
Nice! works well
