### ISSUE TITLE
Kodi - avoid alpha releases

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#885]
I'm not seeing a way to avoid the Alpha releases here:
https://f-droid.org/en/packages/org.xbmc.kodi/

**Comment by ImranR98** [comment]
Sure, we could add a user-defined regex to filter for specific version parrents. There could also be a toggle to automatically pick the APK that F-droid recommends: https://f-droid.org/api/v1/packages/org.xbmc.kodi

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.14-beta
