### ISSUE TITLE
v0.14.13-beta import error

### ISSUE THREAD

**Issue by Andyj9** [ImranR98/Obtainium#887]
**Prerequisites**

**Describe the bug**

[v0.14.13-beta](app-armv8a-release.apk) import error
Export to new directory - seems to work, creates json file Ok
In editor json seems to look same as older export file done before in Downloads directory.
Older file imports just fine - newer file gives error

Unexpected Error
FileSystem Exception: Failed to decode
data using encoding 'utf-8'. path ='/data/
user/0/dev.imranr.obtainium/cache/
file_piker/obtianium-
export-2003-09-13T10-46-06-785978.json'

**To Reproduce**

Obtainian import button

**Screenshots and Logs**

**Please complete the following information:**
 - Device:  Pixel 3xl and Pixel 5a
 - OS:  Stock Android 12 on 3xl and Stock 13 on 5a
 - Obtainium Version:  v0.14.13-beta

**Additional context**

Tried to move file to Download directory - same error.

PS - Great app - thank  you.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.14-beta
