### ISSUE TITLE
"Update All" or multi-update ability?

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#891]
As it stands now, when we need to update a number of apps, we need to update one, wait until it's done, then a second, etc.  Is it possible to allow selection of a number of apps to be updated in turn?  And/or an "update all"?

Thanks for your work!  Great that this is such an active project.

**Comment by ImranR98** [comment]
Already a button for this at the bottom of the apps page.

**Comment by DiagonalArg** [comment]
@ImranR98 / my apologies, but ... I'm not seeing it!  Are we looking at the same thing?

![23-09-14 00-43-08 0164](https://github.com/ImranR98/Obtainium/assets/5190243/462cbf9b-733b-4387-aeac-80be6e86b438)

The 3 on the right (trash can, pyramid, and ellipsis) are greyed out.  I've looked at all of these and all of the settings.

**Comment by ImranR98** [comment]
Yhr first one with the download icon.

**Comment by ImranR98** [comment]
Before trashcan

**Comment by DiagonalArg** [comment]
I must have had an old version.  All it said before was "Install 65 Apps."  Now I've got the "Update 5 Apps."

Thank you!
