### ISSUE TITLE
Show updatable apps on the top of the list temporarily

### ISSUE THREAD

**Issue by MatsG23** [ImranR98/Obtainium#90]
When updates have been found in the manual update searching progress, you need to go down the list of apps and search for the "Update available" text for every app. This can be very annoying the longer the list of apps is.
It would be great to have list of apps that can be updated on top of the list, probably seperated.

**Comment by S7venLights** [comment]
Hi there's a botton left of filter that quickly shows you only available updates

**Comment by ImranR98** [comment]
Yes, you can use the filter for this. But I guess the option to have a "pin to top" setting for updates would be more convenient.

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.6.5-beta
