### ISSUE TITLE
Could not find a suitable release

### ISSUE THREAD

**Issue by zerobun** [ImranR98/Obtainium#900]
**Prerequisites**

**Describe the bug**

As the name says it can't find a suitable release for an on [Github](https://github.com/Ivy-Apps/ivy-wallet) ]. There's no apk release however I just want to save to it in my collection and get notifs if a new "release" was made. 

**To Reproduce**

**Screenshots and Logs**

**Please complete the following information:**
 - Device: 
 - OS: 
 - Obtainium Version: 

**Additional context**

**Comment by ImranR98** [comment]
> There's no apk release however I just want to save to it in my collection and get notifs if a new "release" was made.

Enable the "track only" toggle.
