### ISSUE TITLE
manually add a link for a website

### ISSUE THREAD

**Issue by nzarbayezid** [ImranR98/Obtainium#904]
I'm looking to manually add a link for a website that has apk files. All I really want is to keep track of the app's version. Basically, I just want to scrape the version info and let me know if there's a newer update compared to the one I have installed. But when I try to add the link, it keeps changing the override source to HTML. Is there any way to let Optainium know that I'm specifically looking for the app called "ticktick" with a version around 6.6.5? Can it even do that?

**Comment by ImranR98** [comment]
The html sources specifically for this use case but it only works with pages that don't use javascript to load their links, and you might need to do some additional configuration. i might be able to help if you link the website

**Comment by nzarbayezid** [comment]
> i might be able to help if you link the website
for example this link (https://liteapks.com/overdrop.html), all i want it the title with the latest version number (Overdrop v2.0), i don't care if Obtainium won't find the link or install the apk. all i want it just inform me about the latest update and what version i installed, then i can take care of the installation manually.

**Comment by ImranR98** [comment]
You would be able to use the HTML source for this if the website didn't require JavaScript to download files. You could  

I tried adding `https://liteapks.com/overdrop.html` as an HTML Source, then setting the "intermediate link" setting to `/download/`. It was able to find the correct APK (`https://play.liteapks.com/Overdrop/Overdrop-2.0-beta1.apk`) but couldn't download it as the website requires JavaScript. Nothing can be done about this unless we switch to a web scraper that can deal with JS-enabled pages.

**Comment by nzarbayezid** [comment]
thanks for replying, as i said i don't care if Obtainium download the apk for me, all i want is read the newest available version and inform me about it. how did you make it work and find the link and the new version? 
i don't know what to do with HTML links.

![Screenshot_2023-09-17-11-19-12-306_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/101425664/b84d0712-cc45-4b22-9453-8024de708f9d)

**Comment by itzshoaibmalik** [comment]
Hi, I needed the same solution. Even for tracking how to do it please...
