### ISSUE TITLE
Can't find suitable release (again) 

### ISSUE THREAD

**Issue by zerobun** [ImranR98/Obtainium#912]
**Prerequisites**

**Describe the bug**

**Screenshots and Logs**

![Screenshot_2023_0917_095205](https://github.com/ImranR98/Obtainium/assets/127630316/242dde1e-1131-4091-bf9e-064e8e5de192)

**Please complete the following information:**
 - Device: 
 - OS: 
 - Obtainium Version: 

**Additional context**

**Comment by zerobun** [comment]
If you would like to check the repo, here's the link: https://github.com/Marekkon5/onetagger-android

**Comment by ImranR98** [comment]
The repo does not have any releases: https://github.com/Marekkon5/onetagger-android/releases
