### ISSUE TITLE
Unauthroized

### ISSUE THREAD

**Issue by Samandamand** [ImranR98/Obtainium#913]
**Describe the bug**
When Obtainuim check for app updates it comes back with unauthorized for all apps.

**Please complete the following information:**
 - Device: Pixel 5a
 - OS: GrapheneOS
 - Obtainium Version: 0.14.16

**Comment by ImranR98** [comment]
You have most likely added an invalid GitHub token. Could you try removing it?

**Comment by Samandamand** [comment]
I didn't have anything in my GitHub token field. I had added one way back but deleted it a bit ago. I reinstalled Obtanium and I am not getting this unauthorized issue anymore.

**Comment by lawson85** [comment]
This happened to me but I cleared it's data and it works now!

**Comment by ImranR98** [comment]
Hopefully this was a one-off. Not sure what could have caused it without a GitHub token.

**Comment by 1xFF** [comment]
I ran into this issue today. I had a token in the past, but my token fields are currently empty.
I tried adding random text as a token and then removing it, didn't change anything.
If the releases are debuggable I could see if it's trying to use anything as a token, but I probably wont be able to reproduce it on a new debug build.
