### ISSUE TITLE
Add Reverse Sort to HTML Source

### ISSUE THREAD

**Issue by lepras** [ImranR98/Obtainium#915]
https://www.stremio.com/downloads

![stremio](https://github.com/ImranR98/Obtainium/assets/109689648/257f194a-ba0d-44a2-a9fe-cb90f944146f)

The apk table can be obtained by this xpath `/html/body/main/section[2]/div/div/div/div/div/div[5]/div[3]` and I think you can obtain the version by substring and index of on the url.

This app is pretty important for streaming.

**Comment by ImranR98** [comment]
This would work with the HTML Source if it had a "reverse sort" toggle (currently it picks the Android TV APK which is higher on the page and cannot be filtered out with any pattern).

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.18-beta

**Comment by lepras** [comment]
Works like a charm, thanks a ton!

**Comment by candroid-man** [comment]
@lepras would you mind sharing your configuration for Stremio?
