### ISSUE TITLE
Expressions to be translated

### ISSUE THREAD

**Issue by gidano** [ImranR98/Obtainium#916]
I see that there are terms at the bottom of the Settings menu that are not in the hungarian language file.
I attached a photo...

![2023-09-18_14h59_32](https://github.com/ImranR98/Obtainium/assets/4068977/a087f331-17df-451b-aafe-e85008527daa)

**Comment by ImranR98** [comment]
The strings are now translate-able instead of being hard-coded: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.18-beta

Still need someone to make a PR with the actual translations.

**Comment by gidano** [comment]
Sorry, is there anything else to translate. THX

![2023-09-23_20h26_45](https://github.com/ImranR98/Obtainium/assets/4068977/242bf69b-7155-4e30-a368-7e6092c07d12)

**Comment by ImranR98** [comment]
Looks like that string is missing from hu.json for some reason - you can go ahead and add it (exists in other language files).

**Comment by gidano** [comment]
Done, thank you. I'll close the thread. :)

**Comment by gidano** [comment]
Maybe you? :D

**Comment by gidano** [comment]
I had to reopen, the "noCategories" still remained!
![2023-09-23_20h48_02](https://github.com/ImranR98/Obtainium/assets/4068977/19a2bb91-16ba-461b-89f4-71a8a7e2f801)
