### ISSUE TITLE
[Bug report] Can't add apps on Nvidia Shield

### ISSUE THREAD

**Issue by IceDBorn** [ImranR98/Obtainium#917]
**Describe the bug**
Whenever I try adding apps to obtainium I get the error indicated below.

**To Reproduce**
1. Go to 'Add App'
2. Add a source url
3. Press 'Add'

**Screenshots and Logs**
![image](https://github.com/ImranR98/Obtainium/assets/51162078/4323c6bf-524c-416e-9639-6e15d508927e)

**Please complete the following information:**
 - Device: Nvidia Shield 2019
 - OS: Stock
 - Obtainium Version: Latest

**Comment by IceDBorn** [comment]
After importing a list of apps I use on my phone, I was able to add apps. Might have something to do with new installs of the app instead of the shield.

**Comment by ImranR98** [comment]
Weird. Hopefully it was a one-off.
