### ISSUE TITLE
Feature: Add support for custom schema 

### ISSUE THREAD

**Issue by FredHappyface** [ImranR98/Obtainium#918]
**Prerequisites**

**Describe the feature**

Hi thanks for this awesome app

I was thinking it would be great to add an install with obtainium option to my repo for my app on GitHub and thought the best way to do this would be by creating a obtainium schema and adding it as a supported URL to Android. Not sure in the details but I was imagining something like 

```
obtainium://url_encode(app_url)
```

Or

```
Https://obtainium.app/url_encode(app_url)
```

Where the schema is obtainium is supported by Android or https if custom schemas are not supported. In the event that Https is chosen, there may be an option to support redirects if using your own domain (though this may have security issues, in which case it may be more secure to choose an invalid domain with an invalid tld). The app URL may either be an encoded URL such as 

```
https://github.com/ImranR98/Obtainium
```

Or could use a custom structure to more explicitly identify the app source? 

```
source=github&url=https://github.com/ImranR98/Obtainium&name=Obtainium
```

For example (I can foresee a few issues with the example given for sources with URL params, though this may be mitigated using different symbology/ structure)

This would be great for raising awareness of obtainium as a valid app source 

**Describe alternatives you've considered (if applicable)**

Leave things be and require a user to take a more explicit, manual, approach to adding apps may have certain security benefits as the expense of usability. Solving the issue of how to deal with what happens if the user doesn't have obtainium would be challenging to solve from a usability vs security perspective. For example using a custom schema might not be supported by the browser. Using an invalid http url may be confusing to the user 

**Additional context**

Thanks for your time on this!

**Comment by ImranR98** [comment]
Could be doable. Mentioning #109 as a related but different issue (HTTP vs. custom URI).

**Comment by ds-jetzt** [comment]
I would be happy to see the implementation.

First of all, a link of the kind "[https://obtainium.app/url_encode(app_url)"](obtainium://url_encode(app_url))" would be sufficient, where only obtainium is opened with the view "Add App" and the URL is already pre-filled.

In addition, a "Share" button on the info page of an installed app would be useful, which then generates exactly such a link. 

These steps would certainly help the project, its distribution and use, and should be relatively easy to implement.

**Comment by pluja** [comment]
This would be a great addition to Obtainium! I think using [Android Verified Applinks](https://developer.android.com/training/app-links/verify-android-applinks) is one way of achieving this (I'm not an Android dev). I see two main benefits on using a link shcema for Obtainium:

- Apps could add Obtainium links to their repository, avoiding the need for third-party app stores and making Obtainium more noticeable.
- Users would need just a click to add an app to Obtainium, improving the UX.

**Comment by ImranR98** [comment]
Added. See #368.
