### ISSUE TITLE
Add an option to keep Obtainium running in the background to check for updates

### ISSUE THREAD

**Issue by bluefly000** [ImranR98/Obtainium#92]
Could you please add an option to keep Obtainium running in the background to check for updates?

I am using a Pixel6a running GrapheneOS and am having the same problem as mentioned in [#87](https://github.com/ImranR98/Obtainium/issues/87). Removing Obtainium from recent apps has stopped it from running in the background. Even without removing it from recent apps, using other apps, opening other profiles, etc. caused Obtainium to go into a suspended state and no longer check for updates in the background. Since there are no background update checks being done, there are no notifications. In my case, I only get notifications if I leave my smartphone for several hours after opening Obtainium.

I thought that adding this option would improve the reliability of the update checks in the background.

**Comment by ImranR98** [comment]
I've added your comment to 87 as it is a duplicate.
