### ISSUE TITLE
Changes with new update

### ISSUE THREAD

**Issue by Satanarious** [ImranR98/Obtainium#924]
It would be great to have a button to open or view in-app, the changes in an app with the respective update. I think sources with straightforward descriptions attached to the APK should be easy to fetch, like:
- Github
- Gitlab
- FDroid
- IzzyOnDroid

Maybe something like this on google play store:

![image](https://github.com/ImranR98/Obtainium/assets/42642682/3eeab431-f884-4015-b377-8e79a1296682)

Any thoughts on if this could be implemented?

**Comment by ImranR98** [comment]
You can ready click the version number on the apps page to do this for supported sources
