### ISSUE TITLE
[BUG] Not detecting pre-release from GH app

### ISSUE THREAD

**Issue by 0xlne** [ImranR98/Obtainium#925]
**Prerequisites**

**Describe the bug**

Obtainium is not detecting pre-release versions of the [App Manager](https://github.com/MuntashirAkon/AppManager) even when selecting to include pre-releases when adding the app to Obtainium.
Obtainium is detecting the latest stable version (3.1.2) but not the pre-release (v4.0.0-alpha02).

**To Reproduce**

1. In Obtainium, click on "+" to add app
2. Paste https://github.com/MuntashirAkon/AppManager as app URL
3. Select "include pre-releases"
4. Click "add"
5. Pull down to refresh

**Screenshots and Logs**

**Please complete the following information:**
 - Device:  Xiaomi Mix Fold 2, Redmagic 6, Samsung Z Fold 3, Samsung Note 10+
 - OS:  Android 13, Android 12, Android 13, Android 13
 - Obtainium Version:  0.14.17

**Additional context**

**Comment by ImranR98** [comment]
Could you share your exact steps? I just added it with no issues.

**Comment by ImranR98** [comment]
This is the response Obtainium gets from the GitHub API: https://api.github.com/repos/MuntashirAkon/AppManager/releases

The pre-release is at the top, but its release date is actually older than some items lower on the list. Obtainium sorts the list by version number (if possible) and by release date to ensure the release picked is always the most recent one by date, even if it is lower on the list returned by GitHub (see #478 and #534). I guess this is one of the rare cases where that's a bad thing.

I'll add a toggle in the next release to make this sorting optional.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.18-beta
