### ISSUE TITLE
Release information not tracked properly for IzzyOnDroid

### ISSUE THREAD

**Issue by M00NJ** [ImranR98/Obtainium#926]
As highlighted in the first screenshot, release information like `version number`, `release date` and `repo owner` is not tracked properly with IzzyOnDorid as the source. I tested it with multiple apps from Izzy and they all have this issue. The correct info is available on IzzyOnDroid, as highlighted in the second screenshot, so it should be possible to grab it.

![Screenshot](https://github.com/ImranR98/Obtainium/assets/82398591/6c7f7ee9-663c-4a88-b9ba-e60281b450f8)
![Screenshot2](https://github.com/ImranR98/Obtainium/assets/82398591/0059502d-cd11-418d-a698-4c90e5f08ec0)

 - Device: Pixel 4a5g
 - OS: Android 13 (GrapheneOS)
 - Obtainium Version: v0.14.17-beta

**Comment by ImranR98** [comment]
The source only supports `android.izzysoft.de` URLs (like https://android.izzysoft.de/repo/apk/com.kieronquinn.app.ambientmusicmod), not `apt.izzysoft.de` ones (like https://apt.izzysoft.de/fdroid/index/apk/com.zionhuang.music). I'll add support for this in the next release.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.18-beta

**Comment by M00NJ** [comment]
Wow, that was really fast. Thanks a lot! You have to remove the app and add it back again for it to work, but it now shows the correct version number and repo owner :)
