### ISSUE TITLE
version detection on v0.14.18 bugged

### ISSUE THREAD

**Issue by zer0fl0w** [ImranR98/Obtainium#929]
version detection on the just released 0.14.18
is totally messed up for me.

at all my devices it finds "new versions" for nearly all apps with totally out of context version-numbers when in real there are no updates.

**Comment by ImranR98** [comment]
Whoops. Not sure what's going on. Just deleted that release.

**Comment by ImranR98** [comment]
Sorry about that, hopefully not too many people downloaded `v0.14.18-beta`. You'll probably need to install the new one manually: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.19-beta
