### ISSUE TITLE
Install new app toggle not respected

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#93]
When you have an app added to obtanium marked as not installed and other apps with updates. 
Clicking the install all button brings up a dialogue that asks if you want to install x number of new updates and install x amount of new apps. 
The toggle, by default, is set to not to install new apps, but it still downloads the new app and asks to install.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.6.6-beta

**Comment by S7venLights** [comment]
You're always so quick to fix, I hope you give yourself some rest on the weekend too 😅
