### ISSUE TITLE
Give install permission popup on every new installed app

### ISSUE THREAD

**Issue by JohnBetaro** [ImranR98/Obtainium#932]
Every time I add a new app, Obtainium takes me to the screen where I should give it the permission to install apps, I gave it already but the same thing will happen over and over again, I think this issue appeared since the latest releass 0.14.19.

I hope you'll take a look, thank you.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.20-beta

**Comment by ImranR98** [comment]
For some reason the new minor update to https://github.com/Baseflow/flutter-permission-handler (`11.0.3`) causes this. I've rolled back to `11.0.1` for now.
