### ISSUE TITLE
How deal with github repo which uses tags?

### ISSUE THREAD

**Issue by einarpersson** [ImranR98/Obtainium#938]
Hi, thank you for this project.

I am trying to add tailscale from [the github repo](https://github.com/tailscale/tailscale-android). There are some old releases but for whatever reason they have stopped using them and only use tags.

How should a user of Obtainium approach this situation so that the tags are used and not releases? I could not figure it out so now I added F-Droid source.

Also - is there a FAQ for questions like this?

**Comment by ImranR98** [comment]
You can't use obtainium to download anything if the developer hasn't made apks available. You could still get notified for new tags by enabling the track only toggle. There's no real FAQ but you could always post in the discussions tab. In the future there might be an FAQ in the wiki section.
