### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by Ab-Mr** [ImranR98/Obtainium#939]
**Community to connect**

Well, so this is just a suggestion, for example a group with a community interested in the application.  

**Just a suggestion**

 I see this as common, needed and necessary..

**Comment by ImranR98** [comment]
I think the discussions tab is enough. You can always start something "unofficial" elsewhere if you think it would be useful.

**Comment by Ab-Mr** [comment]
Maybe you're right:) Thank you.
