### ISSUE TITLE
Some repos are not adding to the app

### ISSUE THREAD

**Issue by Yaswanthroy** [ImranR98/Obtainium#94]
I can't able to add below repos to the app, can you please take a look. Thanks 

https://github.com/whyorean/AuroraStore
https://github.com/whyorean/AuroraDroid
https://github.com/f-droid/fdroidclient
https://github.com/Divested-Mobile/Mull-Fenix
https://github.com/kdrag0n/safetynet-fix
https://github.com/kdrag0n/inter-font-pack
https://github.com/xerta555/Detach
https://github.com/Magisk-Modules-Repo/callrecorder-skvalex
https://github.com/Magisk-Modules-Repo/G-VisualMod
https://github.com/LSPosed/LSPosed.github.io
https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver
https://github.com/M66B/XPrivacyLua
https://github.com/yc9559/qti-mem-opt
https://github.com/Pixel-Props/raven

**Comment by ImranR98** [comment]
None of these repos (as far as I checked) have APK files in the releases sections. Obtainium can't find the app builds because the developers have not made them available on GitHub.

**Comment by ImranR98** [comment]
For Aurora store (and possibly some others), you can use their GitLab repo instead as they release APKs there.

**Comment by S7venLights** [comment]
Auroura store and droid are released on Gitlab

I suggest Neostore or Droidify for apps not released on gitub
