### ISSUE TITLE
Add Steam Link to Steam App Source

### ISSUE THREAD

**Issue by JoshuaFern** [ImranR98/Obtainium#940]
The Steam Link app is located at this download URL: https://media.steampowered.com/steamlink/android/latest/steamlink-android.apk

It's an app for streaming your games from your PC to your Android device.

**Comment by ImranR98** [comment]
Unlike the other 2 apps, this one doesn't have a version (or any per-version unique identifier) that is required for version updates: https://store.steampowered.com/mobile
