### ISSUE TITLE
APKPure: Installs the same version instead of the newer one when updating.

### ISSUE THREAD

**Issue by JohnBetaro** [ImranR98/Obtainium#941]
Hi, this is happening for quite some time but I didn't find someone that talks about it.

I think it is only happening with apps installed from APKPure, when there is an update, it will detect it and will know the version of the new one, but when downloading and installing nothing will happen, the app remains with the same version and I can see that from the app properties in the settings, I don't know why is it downloading the same version, I tried many time time and I confirm that nothing is wrong with the downloading and installing processes.

At the same time, you can go to the site and get the latest version normally if you download it and install it by yourself.

I hope you will take a look at this because it is annoying a little bit.

Note: This problem is not persistent, because after some period of time it will get the newer version, but I wanted to tell you so you'll see what is happening exactly and determine if it is a problem in Obtainium or not.

**Comment by ImranR98** [comment]
Does this happen with all apps or just specific ones?

**Comment by XxTriviumxX** [comment]
happens sometimes with me too. i have to click the source url, and then update by downloading the apk. At least it is telling me there is a new update.

**Comment by ImranR98** [comment]
The way the APKPure source currently works is that we extract the version number from the webpage, but we don't actually use it in the APK download. The APK URL just references "latest" for example `https://d.apkpure.com/b/APK/com.instagram.android?version=latest` (this is one reason why there's no option to download older versions of an app). I tried specifying a version, for example `https://d.apkpure.com/b/APK/com.instagram.android?version=302.1.0.36.111` but that doesn't work.

So what's most likely happening is that there's a time delay between when they update the webpage and when they update the "latest" APK served at the download link. I don't think that's something Obtainium could fix (assuming it's actually the problem).

**Comment by jameshaarrisom4** [comment]
[Renew Driving License](https://parivahanin.com/apply-license-renewal/) through the online Parivahan portal is a simple and convenient process that helps you avoid long RTO visits. You can easily submit your application, upload documents, and pay the required fee digitally.
