### ISSUE TITLE
Ignoring add second repo and error ID apps

### ISSUE THREAD

**Issue by userkilled** [ImranR98/Obtainium#942]
How about adding a checkbox to ignore re-adding an app. And ignore an error in the application ID.
I have some repositories added that need to do just that.
If there is a desire for implementation.

**Comment by ImranR98** [comment]
Why do you need to be able to re-add apps?

**Comment by userkilled** [comment]
If you look at this repository, it has multiple versions of the package.
(Number)s - stable
(Number) - beta

https://github.com/yuliskov/SmartTubeNext

There are different package names going on there. You can get them in different formats through obtanium only through a filter. But you can't add another one to select another package

**Comment by userkilled** [comment]
Or CakeWallet repo. There repo have two package Monero.com and CakeWallet

**Comment by ImranR98** [comment]
This is already doable (I just tried it with the smart tv app). As long as the app IDs arr different, you can add the same URL more than once.

**Comment by ImranR98** [comment]
Add one with prereleases included and one without.

**Comment by userkilled** [comment]
Great. Thanks.


> Add one with prereleases included and one without.
