### ISSUE TITLE
Question: Why can't we download from APKMirror

### ISSUE THREAD

**Issue by JohnBetaro** [ImranR98/Obtainium#952]
Why can't we download from APKMirror? I tried to do a search on the issues but I didn't find anything, maybe I didn't look for it very well, I hope you'll explain what happened since it was once used for downloads.

**Comment by ImranR98** [comment]
See #44

APKMirror was taking steps to block web scraping, which we were able to get around. The dev then requested we stop as it reduces ad revenue. Decided to do so as it's probably right (and they would have easily been able to change their site to better block scraping anyways).
