### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by BabyOilJohnson** [ImranR98/Obtainium#956]
Main screen;
Change "Apps" icon to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aapps%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "add app" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aadd%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "import/export" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aadd%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "setting" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Asettings%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4040)
Change "select all" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aselect_all%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4040), for deselect all change to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adeselect%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "filter apps" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Afilter_list%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "download" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adownload%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)  
Change "delete" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adelete%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "categorize" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Acategory%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "more" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Amore_horiz%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
In "more" settings;
Change tick to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adone%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
Change bookmark to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Abookmark%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
Change share to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Ashare%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
Change reset to [this maybe](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Arestart_alt%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)

In app page;
Change back button to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aarrow_back%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "+” to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aadd%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change "edit" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aedit%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
Change settings to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Asettings%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4040)  
Change delete to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Adelete%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 

In settings page "drop-down arrow" to [this](https://fonts.google.com/icons?selected=Material%20Symbols%20Rounded%3Aarrow_drop_down%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)

**Comment by ImranR98** [comment]
Not sure what the point of this is? Most of these icons are very similar to what we already use. The current icons come built-in to Flutter. Using custom fonts/icons would just add unnecessary size/complexity.

**Comment by BabyOilJohnson** [comment]
> Not sure what the point of this is?

I thought it would make more materialized ui, that's all.
