### ISSUE TITLE
Checking 'Changes' that doesn't have description opens in browser

### ISSUE THREAD

**Issue by Rokhala** [ImranR98/Obtainium#959]
**Prerequisites**
I couldn't find anything doesn't seem to have been a report regarding this.

**Describe the bug**
Checking the latest releases for an app, with no description, for 'Changes' opens the browser.

**To Reproduce**
1. Have an app where the latest release doesn't have description
2. Click on the underlined release date to check what changed

**Please complete the following information:**
 - Device: meizu C9
 - OS: Android 8.1.0
 - Obtainium Version: 0.14.22-beta

**Additional context**
I got this problem when checking for changes from Flexbooru v3.2.1 release which is the current latest release that happens to have no description, with an italic grey "No description provided." in place in the GitHub.
I couldn't verify if it's this app alone as other apps has description making it rare. But that being the only different led me writing this.

**Comment by ImranR98** [comment]
See #875 - this is the same issue.
