### ISSUE TITLE
Inform User of Device APK Architecture

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#96]
Just a nice to have, idea. 
Maybe some people who are new to tech and privacy won't know what APK to pick.
ARM, x64, x86, etc.
If there's a plugin that can detect which the phone supports, maybe there could be a message on the top of the pick APK dialogue that shows what architecture your device supports. 
Could read:
Your device supports: x, y and z

There are device info apps on F-droid that can pull this info somehow, but I don't know of a way to check this in android settings.

**Comment by ImranR98** [comment]
This plugin should work: https://pub.dev/packages/system_info2/example

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.6.8-beta
