### ISSUE TITLE
Error: HandshakeException

### ISSUE THREAD

**Issue by ChuuqoVN** [ImranR98/Obtainium#960]
The past few days I was unable to update apps using Obtainium. Every time the app tries to check for update it gives this error. I don't really know what cause this to happen, maybe when I updated the app from 0.14.21 to 0.14.22 but I'm not sure.

![image](https://github.com/ImranR98/Obtainium/assets/138189060/141728cc-aed5-458f-9735-524aa5aea876)

 - Device: Samsung Galaxy A31
 - OS: Android 12
 - Obtainium Version: v.0.14.22-beta

**Comment by ImranR98** [comment]
Sounds like a network issue. Could you try on another network? Disable VPN if you have one? Also try and see if the repo webpages load in a browser.

**Comment by ChuuqoVN** [comment]
Ok now it works when I disable Adguard's ad blocking. But it used to work fine a few days ago...?

**Comment by ImranR98** [comment]
In that case it's safe to say Adguard is blocking some GitHub API request. No idea why they would think those should be blocked.
