### ISSUE TITLE
Parallelize refresh work

### ISSUE THREAD

**Issue by MatsG23** [ImranR98/Obtainium#963]
**Is your feature request related to a problem? Please describe.**
I have 31 apps registered in Obtainium. Refreshing the full app list takes a few minutes. This is also caused by some app entries taking a bit longer to refresh.

**Describe the feature**
I think the refresh speed could be increased by parallelizing the network requests to all the app sources. Right now due to the speed it seems like only one app source would be fetched at once.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.23-beta

**Comment by ImranR98** [comment]
Just FYI, I had to switch back to serial update checking for background tasks. I'm not sure why but the parallel method seemed to cause some silent crash a lot of the time. Foreground checking (pull to refresh) still uses the parallel method and (which is the main UX improvement for this issue anyways - I'm guessing most people aren't checking how long background updates take). I'll try messing around with the BG process again at some point.

**Comment by ImranR98** [comment]
That doesn't seem to have fixed it. Might be an Android 14 issue (switched to it on both devices shortly after this change). If either of you are on Android <14 did you have any issues with parallel checking in the background task?

**Comment by ImranR98** [comment]
Yeah, parallel updates weren't the issue - will switch back to them in the next release. Not sure why the tasks are crashing so often on my devices.

**Comment by ImranR98** [comment]
Will track the task crashes on the existing issue #608
