### ISSUE TITLE
'Local data has not been initialized'

### ISSUE THREAD

**Issue by plushie-neko** [ImranR98/Obtainium#968]
`LocaleDataException: Locale data has not been initialized, call initializeDateFormatting(<locale>).`

**To Reproduce**
1. Add any app from AppGallery
2. Wait

**Screenshots and Logs**
![IMG_20231007_141205](https://github.com/ImranR98/Obtainium/assets/146845322/ecef5a59-98b5-4214-b12a-fed4ba44a010)
[logs.txt](https://github.com/ImranR98/Obtainium/files/12837586/logs.txt)

 - Device: OnePlus 6T
 - OS: crDroid 9.9
 - Obtainium Version: v0.14.23-beta

**Comment by ImranR98** [comment]
Unable to reproduce this on my end. Could you try exporting your data and resetting the app? Also just to confirm - you're using the Russian language setting, right?

**Comment by plushie-neko** [comment]
[obtainium-export-2023-10-07T22-21-49.522976.json.zip](https://github.com/ImranR98/Obtainium/files/12838624/obtainium-export-2023-10-07T22-21-49.522976.json.zip)
Exported this, maybe will help you somehow. 
No changes after reset, same errors, same logs.
And I'm not using russian language if I get your question right, only app names

**Comment by k03mad** [comment]
Same here

LocaleDataException: Locale data has not been initialized, call initializeDateFormatting(<locale>)

App: https://appgallery.huawei.com/app/C101169535

Error shows up **only** with background update
Obtainium app locale is set to english

**Comment by eylenburg** [comment]
I have this too, all the time

**Comment by awesfdawe** [comment]
Same problem

**Comment by redrezo** [comment]
![IMG_20240325_133240](https://github.com/ImranR98/Obtainium/assets/429967/ecbba9b0-0059-4ee8-b00d-17d34745e147)
Same issue here
Not sure since when, with the first few apps it didnt happen, but now i also got one app from the huawei appgallery

**Comment by para2ox** [comment]
Same. I have apps from AppGallery too.
