### ISSUE TITLE
Please branch notifications title strings from notifications settings strings.

### ISSUE THREAD

**Issue by Daviteusz** [ImranR98/Obtainium#979]
Please branch strings that are used for notifications and notifications settings
Why? E.g. in Polish these translations should be separate, because it is impossible to include them in one string

For notification settings title:
- `"appsPossiblyUpdated": "Informuj o próbach aktualizacji"` 

For received notification title:
- `"appsPossiblyUpdated": "Próbowano zaktualizować aplikację"`

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.27-beta
