### ISSUE TITLE
FR: Add an option to skip notification for updates of specific apps

### ISSUE THREAD

**Issue by foundObjects** [ImranR98/Obtainium#980]
**Prerequisites**
Search finds no similar issues

**Describe the feature**
I'd like a new toggle option added to app settings that prevents notification of updates for that app.

I've added a couple of apps to Obtainium that produce nightly builds (or have full blown continuous integration and deployment) and occasionally I use them to install a CD build when a new feature has been added that I want to test.

Obtainium tries to be helpful and let me know they've been updated - these updates are so frequent that I receive them daily or multiple times per day. I'd like to squelch notifications for these specific apps.

**Describe alternatives you've considered (if applicable)**
I could remove the app from Obtainium completely and manually go to the build page for each app and update it.

**Additional context**
This feature would also be useful if I decide to uninstall an app and don't want to see notifications of updates. This would let me keep an entry in Obtainium so I can re-install the app easily later without being bothered in the meantime.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.27-beta

**Comment by foundObjects** [comment]
Thanks, this is perfect!
