### ISSUE TITLE
Uptodown: No APK Found

### ISSUE THREAD

**Issue by JohnBetaro** [ImranR98/Obtainium#982]
It seems like they changed something again, I hope it won't be rejecting Obtainium's requests because of some checking mechanism so the user must go to their site and download manually.

Note that I checked for many apps not just the one in the screenshot.
<details>
<summary>Screenshot:</summary>
<img src="https://github.com/ImranR98/Obtainium/assets/114379310/c50ba8b5-6b5a-4d0b-be2a-b7e77593ef12" alt="Screenshot">
</details>

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.26-beta
