### ISSUE TITLE
Run parallel update checks, but only in foreground

### ISSUE THREAD

**Issue by BrianAllred** [ImranR98/Obtainium#988]
**Prerequisites**

**Describe the feature**

Instead of only having serial or parallel update checking, why not do serial in the background, when speed isn't as important, and parallel in the foreground, since that seems to work fine?

I'm not familiar with the internals of the app to know how hard or easy this is, but it seems logically straightforward.

**Describe alternatives you've considered (if applicable)**

Alternative is just to stick to one or the other, either longer update checks or less stable background checks.

**Additional context**

**Comment by ImranR98** [comment]
Not sure if you've seen #963. The latesr release does what you're describing (but I find bg checking is still unstable on Android 14). Any discussion should be on the original issue to keep things in one place.
