### ISSUE TITLE
On Version detection for HTML sources 

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#989]
[This souce](https://thomasokken.com/free42/) has a version listed on the webpage ("The latest release is 3.0.21."), but the link to the .apk is [always the same](https://thomasokken.com/free42/download/Free42Android.apk).

Could there be a selection for the version extraction regexp, to look at either the "App source URL" vs. the apk link?

**Edit:**

Also note that on that page, using:

App Source URL: https://thomasokken.com/free42/

Does not work.  Nor does it work to add:

Custom APK Link Filter by Regexp: download/Free42Android.apk

In both cases, it reports "Not Found".  

Using instead:

App Source URL: https://thomasokken.com/free42/download

does work, but then it will never find a new version.

**Comment by DiagonalArg** [comment]
Working! :pray:

**Comment by svemoe** [comment]
I think now it *always* checks the whole page and the option-switch has no function.
Could you please look into this?

**Comment by DiagonalArg** [comment]
> I think now it _always_ checks the whole page and the option-switch has no function. Could you please look into this?

It doesn't appear I'm having that problem.  :thinking: 

GrapheneOS on a Pixel 7.

**Comment by ImranR98** [comment]
Yes, just fixed that in the latest release.
