### ISSUE TITLE
App not updated but it's already at latest version

### ISSUE THREAD

**Issue by faustaahmad** [ImranR98/Obtainium#99]
Step to reproduce:
- Download an app update
- Don't click Install, press side screen when in package installer (it'll cancel the installation)
- App status is updated, but in reality it hasn't & update button is greyed out

**Comment by ImranR98** [comment]
This is a known problem with the installer plugin we use (see "Limitations" in the README). Not much can be done for now.

**Comment by ImranR98** [comment]
Re-opening this (with the 'blocked' tag) since it is a bug, just not one that I see a way of fixing currently.

**Comment by privacyonly** [comment]
I think the old way of doing this is better. where we can press a button, no, this is not installed.

there is something worse.
lets say I installed obtainium, 
then import database, 
now there is an update,
it ask for permission to install unknown apps,
allow,
nothing happened(normally other apps will pop a screen to install the app),
but obtainium said it is already updated.

**Comment by ImranR98** [comment]
> I think the old way of doing this is better. where we can press a button, no, this is not installed.

I don't see the point of this. Any App that is not installed automatically gets marked as not installed when Obtainium starts.

> there is something worse. lets say I installed obtainium, then import database, now there is an update, it ask for permission to install unknown apps, allow, nothing happened(normally other apps will pop a screen to install the app), but obtainium said it is already updated.

Will look into this.

**Comment by elmodor** [comment]
I would love a re-download/re-install button as well.

If an update fails for whatever reason, I have to remove the app from Obtainium, re-add the repository and then I can try to update again. That is very tedious.
Even if Obtainium would be able to catch that the update failed, a re-install button could still come in handy if you simple want to reinstall an app.

**Comment by ImranR98** [comment]
Added a "Reset Install Status" button: https://github.com/ImranR98/Obtainium/releases/tag/v0.7.1-beta
This will grab the real version string from the OS and save that to Obtainium, so you should be able to try updating again.
Will leave the issue open since this is only a workaround. Finding a better plugin would be the ideal solution.

**Comment by ImranR98** [comment]
Now using a synchronous install plugin (combined w/ version detection): https://github.com/ImranR98/Obtainium/releases/tag/v0.12.1-beta

**Comment by S7venLights** [comment]
Well done (ツ)
