### ISSUE TITLE
Treat arm64 as suitable for armv8a and later

### ISSUE THREAD

**Issue by mks-h** [ImranR98/Obtainium#990]
Right now the architecture detection does not automatically choose arm64 for my phone that supports armv8a. This happens with [Cromite GitHub](https://github.com/uazo/cromite/) releases. 

From [Wikipedia](https://en.wikipedia.org/wiki/AArch64):
> AArch64 or ARM64 is the 64-bit extension of the ARM architecture family. It was first introduced with the Armv8-A architecture.

**Comment by ImranR98** [comment]
We take architecture strings directly from the OS and use those to match with APKs - it's the only way to be sure we avoid mistakes. Trying to manually figure out whether a given file name corresponds to a specific APK would be error prone because there's any number of possibilities.
