### ISSUE TITLE
Error at start apk

### ISSUE THREAD

**Issue by artproject-2004** [ImranR98/Obtainium#992]
**Prerequisites**

**Describe the bug**
Application doesn't start, shows error at start.

**To Reproduce**
1. Go to 'Start/run apk'

**Screenshots and Logs**
![Screenshot_20231013-000444_1](https://github.com/ImranR98/Obtainium/assets/22707317/c0d6f0e1-b23e-437c-9e29-50a876e9bc64)

**Please complete the following information:**
 - Device: [Pixel 7] 
 - OS: [GrapheneOS] 
 - Obtainium Version: [0.14.26-beta (2218)]

**Additional context**

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.27-beta

**Comment by artproject-2004** [comment]
Great, its working now.
