### ISSUE TITLE
Third party repo: DivestOS

### ISSUE THREAD

**Issue by imxade** [ImranR98/Obtainium#995]
**Describe the feature**
please add 
https://divestos.org/apks/official/fdroid/repo
to third party searchable repos.

OR

just allow us to add whole repo instead of single app.

**Describe alternatives you've considered (if applicable)**
Currently using f-droid

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.28-beta

**Comment by foxjaw** [comment]
How to form url for add Mulch webview ?
