### ISSUE TITLE
Update 0.14.26-beta just doesn't work

### ISSUE THREAD

**Issue by Dragurashiphylax** [ImranR98/Obtainium#999]
**Describe the bug**
After installing the Obtainium app and updating it (0.14.25-beta -> 0.14.26-beta) it just refuses to work.

**Error message**
FormatException: Unexpected character (at line 251, character 5)

**To Reproduce**
1. Install app from F-Droid (0.14.25 beta)
2. Update Obtainium through Obtainium
3. See the error when opening the app

**Screenshots and Logs**
![Screenshot_20231012_163103.png](https://github.com/ImranR98/Obtainium/assets/99643690/24f69bd6-ee5e-48e4-9114-8546bcfa0e6a)

**Please complete the following information:**
 - Device: Samsung M33 5G
 - OS: Stock OneUI, Android 13
 - Obtainium Version: 0.14.25 from IzzyOnDroid F-Droid repository (and then updated to 0.14.26beta through Obtainium itself)

**Additional context**
The app for some reason cannot

**Comment by ImranR98** [comment]
Yeah, this was an issue with one of the translation files having a syntax error. It should be fixed in the current release that you'll have to install manually.
